SET SQL_SAFE_UPDATES = 0;
SET FOREIGN_KEY_CHECKS=0;

delete from T_CK_CT_TRIP_CARGO_FM;
delete from T_CK_CT_TRIP_CARGO_MM;
delete from T_CK_CT_TRIP_DO;
delete from T_CK_CT_TRIP_DO_ATTACH;
delete from T_CK_CT_TRIP_REIMBURSEMENT;
delete from T_CK_CT_TRIP_CHARGE;
delete from T_CK_CT_TRIP_RATE;
delete from T_CK_CT_TRIP_LOCATION;
delete from T_CK_CT_TRIP;
delete from T_CK_JOB;
delete from T_CK_JOB_TRUCK;
delete from T_CK_JOB_ATTACH;
delete from T_CK_JOB_REJECT;
delete from T_CK_JOB_REMARKS;
delete from T_CK_JOB_ATTACH;
delete from T_CK_CT_JOB_TERM_REQ;
delete from T_CK_CT_JOB_TERM;

delete from T_CK_CT_TO_INVOICE;
delete from T_CK_CT_TO_PAYMENT;
delete from T_CK_RECORD_DATE;
delete from T_CK_CT_CONTACT_DETAIL;

delete from T_CK_CT_PAYMENT;
delete from T_CK_PAYMENT_AUDIT;
delete from T_CK_PAYMENT_TXN;
delete from T_CK_PAYMENT_TXN_LOG;

delete from T_CORE_ATTACH;
delete from T_CORE_AUDITLOG;
delete from T_CORE_EXCEPTION;
delete from T_CK_CT_DEBIT_NOTE;
delete from T_CK_CT_DEBIT_NOTE_ITEM;
delete from T_CK_CT_PLATFORM_INVOICE;
delete from T_CK_CT_PLATFORM_INVOICE_ITEM;
delete from T_CK_CREDIT_SUMMARY;
delete from T_CK_CREDIT_SUMMARY_MONTH;
delete from T_CK_CREDIT_JOURNAL;
delete from T_CK_CREDIT;
delete from T_CK_CT_TRACK_DEVICE;
delete from T_CK_CT_TRACK_LOC;
delete from T_CK_CT_TRACK_LOC_ITEM;

delete from T_CK_TAX_INVOICE;
delete from T_CK_TAX_REPORT;

SET FOREIGN_KEY_CHECKS=1;
SET SQL_SAFE_UPDATES = 1;

-- reset credit
INSERT INTO T_CK_CREDIT (CR_ID, CR_SERVICE_TYPE, CR_COMPANY, CR_STATE, CR_AMT, CR_CCY, CR_DT_START, CR_DT_END, CR_USR_VERIFY, CR_DT_VERIFY, CR_USR_APPROVE, CR_DT_APPROVE, CR_REMARKS, CR_STATUS, CR_DT_CREATE, CR_UID_CREATE, CR_DT_LUPD, CR_UID_LUPD) VALUES('1685415324196', 'CLICTRUCK', 'ALKNAR', 'APPROVED', 500000000, 'IDR', '2023-05-30 00:00:00', '2024-05-30 00:00:00', 'ALKNAR_U001', '2023-05-30 09:58:55', 'ALKNAR_U001', '2023-05-30 09:59:02', NULL, 'A', '2023-05-30 09:59:11', 'SYS', '2023-05-30 09:59:17', 'SYS');
INSERT INTO T_CK_CREDIT_SUMMARY (CRS_ID, CRS_SERVICE_TYPE, CRS_COMPANY, CRS_AMT, CRS_RESERVE, CRS_UTILIZED, CRS_BALANCE, CRS_CCY, CRS_STATUS, CRS_DT_CREATE, CRS_UID_CREATE, CRS_DT_LUPD, CRS_UID_LUPD) VALUES('1685415326215', 'CLICTRUCK', 'ALKNAR', 500000000, 0.0, 0.0, 500000000, 'IDR', 'A', '2023-05-30 09:59:11', 'SYS', '2023-05-30 09:59:11', 'SYS');