SET SQL_SAFE_UPDATES = 0;
SET FOREIGN_KEY_CHECKS=0;

delete from clickargo2.T_CK_CT_CONTRACT;
delete from clickargo2.T_CK_CT_CONTRACT_CHARGE;
delete from clickargo2.T_CK_CT_CONTRACT_REQ;

delete from clickargo2.T_CK_CT_LOCATION;
delete from clickargo2.T_CK_CT_DRV;
delete from clickargo2.T_CK_CT_VEH;
delete from clickargo2.T_CK_CT_RATE_TABLE;
delete from clickargo2.T_CK_CT_RATE_TABLE_REMARK;
delete from clickargo2.T_CK_CT_SAGE_TAX;

delete from T_CK_SAGE_INTEGRATION;
delete from T_CK_SUSPENSION_LOG;

delete from T_CK_SVC_JOURNAL;
delete from T_CK_SVC_SUB;

delete from T_CORE_AUDITLOG;
delete from T_CORE_EXCEPTION;
delete from T_CORE_NOTIFICATION_LOG;
delete from T_CORE_SCHEDULE_JOBLOG;


delete from T_CK_SEQUENCE_NO where SQN_ID != 'CT_ACCN_CODE';

delete from clickargo2.T_CORE_USR_ROLE where UROL_UID NOT like '%GLI%'; 
delete from clickargo2.T_CORE_USR where USR_ACCNID != 'GLI' ;
DELETE FROM clickargo2.T_CORE_ACCN_CONFIG;
DELETE FROM clickargo2.T_CK_ACCN_ATT;
DELETE FROM clickargo2.T_CK_WORKFLOW_REMARK;
delete from clickargo2.T_CORE_ACCN where ACCN_ID != 'GLI' ;

SET FOREIGN_KEY_CHECKS=1;
SET SQL_SAFE_UPDATES = 1;

-- reset credit
INSERT INTO T_CK_CREDIT (CR_ID, CR_SERVICE_TYPE, CR_COMPANY, CR_STATE, CR_AMT, CR_CCY, CR_DT_START, CR_DT_END, CR_USR_VERIFY, CR_DT_VERIFY, CR_USR_APPROVE, CR_DT_APPROVE, CR_REMARKS, CR_STATUS, CR_DT_CREATE, CR_UID_CREATE, CR_DT_LUPD, CR_UID_LUPD) VALUES('1685415324196', 'CLICTRUCK', 'ALKNAR', 'APPROVED', 500000000, 'IDR', '2023-05-30 00:00:00', '2024-05-30 00:00:00', 'ALKNAR_U001', '2023-05-30 09:58:55', 'ALKNAR_U001', '2023-05-30 09:59:02', NULL, 'A', '2023-05-30 09:59:11', 'SYS', '2023-05-30 09:59:17', 'SYS');
INSERT INTO T_CK_CREDIT_SUMMARY (CRS_ID, CRS_SERVICE_TYPE, CRS_COMPANY, CRS_AMT, CRS_RESERVE, CRS_UTILIZED, CRS_BALANCE, CRS_CCY, CRS_STATUS, CRS_DT_CREATE, CRS_UID_CREATE, CRS_DT_LUPD, CRS_UID_LUPD) VALUES('1685415326215', 'CLICTRUCK', 'ALKNAR', 500000000, 0.0, 0.0, 500000000, 'IDR', 'A', '2023-05-30 09:59:11', 'SYS', '2023-05-30 09:59:11', 'SYS');