-- Added stampduty flag
INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICDO_STAMP_DUTY_ON', 'true', 'FLAG WHETHER TO TURN ON STAMP DUTY OR NOT', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');
