-- execute this in case the script below is not yet in prod

ALTER TABLE `clickargo2`.`T_CK_ACCN` 
ADD COLUMN `CACCN_ISPOT_SUB_ACCN` VARCHAR(128) NULL COMMENT 'Sub account for ISPOT, regist in ASCENT' AFTER `CACCN_EPOD_SERVICE`;

ALTER TABLE `clickargo2`.`T_CK_ACCN` 
ADD COLUMN `CACCN_WHATSAPP` TINYINT(1) NULL DEFAULT 0 AFTER `CACCN_ISPOT_SUB_ACCN`,
ADD COLUMN `CACCN_SMS` TINYINT(1) NULL DEFAULT 0 AFTER `CACCN_WHATSAPP`,
ADD COLUMN `CACCN_CO2X` TINYINT(1) NULL DEFAULT 0 AFTER `CACCN_SMS`,
ADD COLUMN `CACCN_ROUTE_PLANNING` TINYINT(1) NULL DEFAULT 0 AFTER `CACCN_CO2X`;


ALTER TABLE `clickargo2`.`T_CK_ACCN` 
ADD COLUMN `CACCN_EXCEL_TEMPLATE_EXAMPLE` VARCHAR(128) NULL AFTER `CACCN_EXCEL_TEMPLATE`;

-- menu for accounts management
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKDO_OA_020200','CKDO','','','Accounts Management','Accounts Management','20200','/manageAccounts/all/list',NULL,'CKDO_OA_020000','A',NOW(),'SYS',NOW(),'SYS');

INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM085', 'Y', 'CKDO', NULL, 'M', NULL, NULL, 'CKDO_OA_020100', 'Static Virtual Account', 'Static Virtual Account','Static Virtual Account','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM086', 'Y', 'CKDO', NULL, 'M', NULL, NULL, 'CKDO_OA_020200', 'Accounts Management', 'Accounts Management','Accounts Management','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');

INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKDO', 'ADMIN', 'PM085', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKDO', 'ADMIN', 'PM086', 'A', NOW(), 'SYS');


-- select * from T_CORE_MENU_EX WHERE UROL_UID='GLI_U001';
-- select * from T_CORE_GRANT_ROLE_EX where GNTRLEX_PERM_ID='PM085';
-- select * from T_CORE_PERM_EX where PERM_ID='PM085';

-- remove manage accounts in system administration
DELETE FROM `T_CORE_GRANT_ROLE_EX` where GNTRLEX_PERM_ID='PM022';
DELETE FROM `T_CORE_PERM_EX` where PERM_ID='PM022';
DELETE FROM `T_CORE_MENU_EX` where MENU_ID='CKDO_MSA_060700';

-- insert new role  for clicdo 

INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKDO','SP_OP_ADMIN','A','OPERATIONS ADMIN',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKDO','SP_L1','A','LEVEL 1 SUPPORT',NOW(),'SYS',NOW(),'SYS');
-- INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKDO','SP_FIN_HD','A','FINANCE HEAD',NOW(),'SYS',NOW(),'SYS');
-- INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKDO','SP_FIN_ADMIN','A','FINANCE ADMIN',NOW(),'SYS',NOW(),'SYS');

-- insert ckdo role for gli_u001 and gli_l1
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('GLI_U001','CKDO','SP_OP_ADMIN','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('GLI_L1','CKDO','SP_L1','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('GLI_U001','CKDO','SP_L1','N','A',NOW(),'SYS', NOW(),'SYS','N');

-- add workflow for clicdo account management
INSERT INTO T_CK_SVC_WORKFLOW(WKFL_ID, WKFL_APPS_CODE, WKFL_ACCN_TYPE, WKFL_ROLE, WKFL_SCV_TYPE, WKFL_ACTION, WKFL_FROM_STATE, WKFL_TO_STATE, WKFL_URI, WKFL_STATUS, WKFL_DT_CREATE, WKFL_UID_CREATE, WKFL_DT_LUPD, WKFL_UID_LUPD)  VALUES('ACNREG_CKDO_1','CKDO','ACC_TYPE_SP','SP_L1','CLICDO','SUBMIT','NEW','SUB','','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_SVC_WORKFLOW(WKFL_ID, WKFL_APPS_CODE, WKFL_ACCN_TYPE, WKFL_ROLE, WKFL_SCV_TYPE, WKFL_ACTION, WKFL_FROM_STATE, WKFL_TO_STATE, WKFL_URI, WKFL_STATUS, WKFL_DT_CREATE, WKFL_UID_CREATE, WKFL_DT_LUPD, WKFL_UID_LUPD)  VALUES('ACNREG_CKDO_2','CKDO','ACC_TYPE_SP','SP_L1','CLICDO','DELETE','NEW','DEL','','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_SVC_WORKFLOW(WKFL_ID, WKFL_APPS_CODE, WKFL_ACCN_TYPE, WKFL_ROLE, WKFL_SCV_TYPE, WKFL_ACTION, WKFL_FROM_STATE, WKFL_TO_STATE, WKFL_URI, WKFL_STATUS, WKFL_DT_CREATE, WKFL_UID_CREATE, WKFL_DT_LUPD, WKFL_UID_LUPD)  VALUES('ACNREG_CKDO_3','CKDO','ACC_TYPE_SP','SP_OP_ADMIN','CLICDO','APPROVE','SUB','APP','','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_SVC_WORKFLOW(WKFL_ID, WKFL_APPS_CODE, WKFL_ACCN_TYPE, WKFL_ROLE, WKFL_SCV_TYPE, WKFL_ACTION, WKFL_FROM_STATE, WKFL_TO_STATE, WKFL_URI, WKFL_STATUS, WKFL_DT_CREATE, WKFL_UID_CREATE, WKFL_DT_LUPD, WKFL_UID_LUPD)  VALUES('ACNREG_CKDO_4','CKDO','ACC_TYPE_SP','SP_OP_ADMIN','CLICDO','REJECT','SUB','REJ','','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_SVC_WORKFLOW(WKFL_ID, WKFL_APPS_CODE, WKFL_ACCN_TYPE, WKFL_ROLE, WKFL_SCV_TYPE, WKFL_ACTION, WKFL_FROM_STATE, WKFL_TO_STATE, WKFL_URI, WKFL_STATUS, WKFL_DT_CREATE, WKFL_UID_CREATE, WKFL_DT_LUPD, WKFL_UID_LUPD)  VALUES('ACNSUS_CKDO_1','CKDO','ACC_TYPE_SP','SP_L1','CLICDO','SUSPEND','APP','SUB','','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_SVC_WORKFLOW(WKFL_ID, WKFL_APPS_CODE, WKFL_ACCN_TYPE, WKFL_ROLE, WKFL_SCV_TYPE, WKFL_ACTION, WKFL_FROM_STATE, WKFL_TO_STATE, WKFL_URI, WKFL_STATUS, WKFL_DT_CREATE, WKFL_UID_CREATE, WKFL_DT_LUPD, WKFL_UID_LUPD)  VALUES('ACNSUS_CKDO_2','CKDO','ACC_TYPE_SP','SP_OP_ADMIN','CLICDO','APPROVE','SUB','SUS','','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_SVC_WORKFLOW(WKFL_ID, WKFL_APPS_CODE, WKFL_ACCN_TYPE, WKFL_ROLE, WKFL_SCV_TYPE, WKFL_ACTION, WKFL_FROM_STATE, WKFL_TO_STATE, WKFL_URI, WKFL_STATUS, WKFL_DT_CREATE, WKFL_UID_CREATE, WKFL_DT_LUPD, WKFL_UID_LUPD)  VALUES('ACNSUS_CKDO_3','CKDO','ACC_TYPE_SP','SP_OP_ADMIN','CLICDO','REJECT','SUB','REJ','','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_SVC_WORKFLOW(WKFL_ID, WKFL_APPS_CODE, WKFL_ACCN_TYPE, WKFL_ROLE, WKFL_SCV_TYPE, WKFL_ACTION, WKFL_FROM_STATE, WKFL_TO_STATE, WKFL_URI, WKFL_STATUS, WKFL_DT_CREATE, WKFL_UID_CREATE, WKFL_DT_LUPD, WKFL_UID_LUPD)  VALUES('ACNTER_CKDO_1','CKDO','ACC_TYPE_SP','SP_L1','CLICDO','TERMINATE','APP','SUB','','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_SVC_WORKFLOW(WKFL_ID, WKFL_APPS_CODE, WKFL_ACCN_TYPE, WKFL_ROLE, WKFL_SCV_TYPE, WKFL_ACTION, WKFL_FROM_STATE, WKFL_TO_STATE, WKFL_URI, WKFL_STATUS, WKFL_DT_CREATE, WKFL_UID_CREATE, WKFL_DT_LUPD, WKFL_UID_LUPD)  VALUES('ACNTER_CKDO_2','CKDO','ACC_TYPE_SP','SP_OP_ADMIN','CLICDO','APPROVE','SUB','TERMINATED','','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_SVC_WORKFLOW(WKFL_ID, WKFL_APPS_CODE, WKFL_ACCN_TYPE, WKFL_ROLE, WKFL_SCV_TYPE, WKFL_ACTION, WKFL_FROM_STATE, WKFL_TO_STATE, WKFL_URI, WKFL_STATUS, WKFL_DT_CREATE, WKFL_UID_CREATE, WKFL_DT_LUPD, WKFL_UID_LUPD)  VALUES('ACNTER_CKDO_3','CKDO','ACC_TYPE_SP','SP_OP_ADMIN','CLICDO','REJECT','SUB','REJ','','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_SVC_WORKFLOW(WKFL_ID, WKFL_APPS_CODE, WKFL_ACCN_TYPE, WKFL_ROLE, WKFL_SCV_TYPE, WKFL_ACTION, WKFL_FROM_STATE, WKFL_TO_STATE, WKFL_URI, WKFL_STATUS, WKFL_DT_CREATE, WKFL_UID_CREATE, WKFL_DT_LUPD, WKFL_UID_LUPD)  VALUES('ACNRESUMPT_CKDO_1','CKDO','ACC_TYPE_SP','SP_L1','CLICDO','RESUMPTION','SUS','SUB','','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_SVC_WORKFLOW(WKFL_ID, WKFL_APPS_CODE, WKFL_ACCN_TYPE, WKFL_ROLE, WKFL_SCV_TYPE, WKFL_ACTION, WKFL_FROM_STATE, WKFL_TO_STATE, WKFL_URI, WKFL_STATUS, WKFL_DT_CREATE, WKFL_UID_CREATE, WKFL_DT_LUPD, WKFL_UID_LUPD)  VALUES('ACNRESUMPT_CKDO_2','CKDO','ACC_TYPE_SP','SP_OP_ADMIN','CLICDO','APPROVE','SUB','APP','','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_SVC_WORKFLOW(WKFL_ID, WKFL_APPS_CODE, WKFL_ACCN_TYPE, WKFL_ROLE, WKFL_SCV_TYPE, WKFL_ACTION, WKFL_FROM_STATE, WKFL_TO_STATE, WKFL_URI, WKFL_STATUS, WKFL_DT_CREATE, WKFL_UID_CREATE, WKFL_DT_LUPD, WKFL_UID_LUPD)  VALUES('ACNRESUMPT_CKDO_3','CKDO','ACC_TYPE_SP','SP_OP_ADMIN','CLICDO','REJECT','SUB','REJ','','A',NOW(),'SYS',NOW(),'SYS');


-- add grant role for sp_l1 for manage account
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKDO', 'SP_L1', 'PM086', 'A', NOW(), 'SYS');

--  alter table to add appscode to separate workflow from different applications
ALTER TABLE `clickargo2`.`T_CK_FORM_CONTROL` 
ADD COLUMN `CTRL_APPS_CODE` VARCHAR(35) NOT NULL AFTER `CTRL_UID_LUPD`;

-- update records for new column
SET SQL_SAFE_UPDATES = 0;
UPDATE T_CK_FORM_CONTROL
	SET CTRL_APPS_CODE  = 'CKDO'
    where CTRL_ENTITY_TYPE like '%DOI%';
SET SQL_SAFE_UPDATES = 1;
    
SET SQL_SAFE_UPDATES = 0;
UPDATE T_CK_FORM_CONTROL
	SET CTRL_APPS_CODE  = 'CKT'
    where CTRL_APPS_CODE ='';
SET SQL_SAFE_UPDATES = 1;
    
-- alter table to add foreign key constraint to tcoreapps
ALTER TABLE `clickargo2`.`T_CK_FORM_CONTROL` 
ADD INDEX `FK_CK_FORM_CONTROL_CORE_APPS_idx` (`CTRL_APPS_CODE` ASC) VISIBLE;
;
ALTER TABLE `clickargo2`.`T_CK_FORM_CONTROL` 
ADD CONSTRAINT `FK_CK_FORM_CONTROL_CORE_APPS`
  FOREIGN KEY (`CTRL_APPS_CODE`)
  REFERENCES `clickargo2`.`T_CORE_APPS` (`APPS_CODE`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


-- SELECT * FROM T_CK_FORM_CONTROL WHERE CTRL_ID BETWEEN 185 AND 212;
-- ADD WORKFLOW FOR ACCN MANAGEMENT FOR CLICDO
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('185','ACC_TYPE_SP',NULL,'SP_L1','ACCN_REGISTRATION','NEW','EDIT','SUBMIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('186','ACC_TYPE_SP',NULL,'SP_L1','ACCN_REGISTRATION','NEW','EDIT','DELETE',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('187','ACC_TYPE_SP',NULL,'SP_L1','ACCN_REGISTRATION','NEW','EDIT','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('188','ACC_TYPE_SP',NULL,'SP_L1','ACCN_REGISTRATION','APP','EDIT','SAVE',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('189','ACC_TYPE_SP',NULL,'SP_L1','ACCN_REGISTRATION','APP','EDIT','SUSPEND',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('190','ACC_TYPE_SP',NULL,'SP_L1','ACCN_REGISTRATION','APP','EDIT','TERMINATE',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('191','ACC_TYPE_SP',NULL,'SP_L1','ACCN_REGISTRATION','APP','EDIT','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('192','ACC_TYPE_SP',NULL,'SP_L1','ACCN_REGISTRATION','NEW','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('193','ACC_TYPE_SP',NULL,'SP_L1','ACCN_REGISTRATION','SUB','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('194','ACC_TYPE_SP',NULL,'SP_L1','ACCN_REGISTRATION','APP','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('195','ACC_TYPE_SP',NULL,'SP_OP_ADMIN','ACCN_REGISTRATION','SUB','VIEW','APPROVE',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('196','ACC_TYPE_SP',NULL,'SP_OP_ADMIN','ACCN_REGISTRATION','SUB','VIEW','REJECT',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('197','ACC_TYPE_SP',NULL,'SP_OP_ADMIN','ACCN_REGISTRATION','SUB','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('198','ACC_TYPE_SP',NULL,'SP_OP_ADMIN','ACCN_REGISTRATION','APP','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('199','ACC_TYPE_SP',NULL,'SP_L1','ACCN_SUSPENSION','APP','VIEW','SUSPEND',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('200','ACC_TYPE_SP',NULL,'SP_L1','ACCN_SUSPENSION','APP','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('201','ACC_TYPE_SP',NULL,'SP_L1','ACCN_SUSPENSION','SUB','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('202','ACC_TYPE_SP',NULL,'SP_L1','ACCN_SUSPENSION','SUS','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('203','ACC_TYPE_SP',NULL,'SP_OP_ADMIN','ACCN_SUSPENSION','SUB','VIEW','APPROVE',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('204','ACC_TYPE_SP',NULL,'SP_OP_ADMIN','ACCN_SUSPENSION','SUB','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('205','ACC_TYPE_SP',NULL,'SP_OP_ADMIN','ACCN_SUSPENSION','SUS','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('206','ACC_TYPE_SP',NULL,'SP_L1','ACCN_TERMINATION','APP','VIEW','TERMINATE',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('207','ACC_TYPE_SP',NULL,'SP_L1','ACCN_TERMINATION','APP','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('208','ACC_TYPE_SP',NULL,'SP_L1','ACCN_TERMINATION','SUB','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('209','ACC_TYPE_SP',NULL,'SP_L1','ACCN_TERMINATION','TERMINATED','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('210','ACC_TYPE_SP',NULL,'SP_OP_ADMIN','ACCN_TERMINATION','SUB','VIEW','APPROVE',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('211','ACC_TYPE_SP',NULL,'SP_OP_ADMIN','ACCN_TERMINATION','SUB','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD,CTRL_APPS_CODE)  VALUES('212','ACC_TYPE_SP',NULL,'SP_OP_ADMIN','ACCN_TERMINATION','TERMINATED','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS','CKDO');

-- users management
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKDO_OA_020300','CKDO','','','Users Management','Users Management','20300','/manageUsers/users/all/list',NULL,'CKDO_OA_020000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM087', 'Y', 'CKDO', NULL, 'M', NULL, NULL, 'CKDO_OA_020300', 'Users Management', 'Users Management','Users Management','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKDO', 'SP_L1', 'PM087', 'A', NOW(), 'SYS');

-- remove manage all users in systems administration
DELETE FROM `T_CORE_GRANT_ROLE_EX` where GNTRLEX_PERM_ID='PM021';
DELETE FROM `T_CORE_PERM_EX` where PERM_ID='PM021';
DELETE FROM `T_CORE_MENU_EX` where MENU_ID='CKDO_MSA_060600';

-- 18 Sep 2024 add op_admin for client account
INSERT INTO `clickargo2`.`T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`, `ROLE_STATUS`, `ROLE_DESC`, `ROLE_DT_CREATE`, `ROLE_UID_CREATE`, `ROLE_DT_LUPD`, `ROLE_UID_LUPD`) VALUES ('CKDO', 'OP_ADMIN', 'A', 'OPERATIONS ADMIN', '2024-09-17 01:25:01', 'SYS', '2024-09-17 01:25:01', 'SYS');
