INSERT INTO `clickargo`.`T_CK_MST_BL_STATE` (`BLST_ID`, `BLST_NAME`, `BLST_DESC`, `BLST_DESC_OTH`, `BLST_STATUS`, `BLST_DT_CREATE`, `BLST_UID_CREATE`, `BLST_DT_LUPD`, `BLST_UID_LUPD`) VALUES ('CLAIMED', 'CLAIMED', 'CLAIMED', 'CLAIMED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
INSERT INTO `clickargo`.`T_CK_MST_BL_STATE` (`BLST_ID`, `BLST_NAME`, `BLST_DESC`, `BLST_DESC_OTH`, `BLST_STATUS`, `BLST_DT_CREATE`, `BLST_UID_CREATE`, `BLST_DT_LUPD`, `BLST_UID_LUPD`) VALUES ('CONFIRMED', 'CONFIRMED', 'CONFIRMED', 'CONFIRMED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

INSERT INTO `clickargo`.`T_CK_MST_JOB_STATE` (`JBST_ID`, `JBST_NAME`, `JBST_DESC`, `JBST_DESC_OTH`, `JBST_STATUS`, `JBST_DT_CREATE`, `JBST_UID_CREATE`, `JBST_DT_LUPD`, `JBST_UID_LUPD`) VALUES ('CLM', 'CLAIMED', 'CLAIMED', 'CLAIMED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

ALTER TABLE `clickargo`.`T_CK_DO` 
DROP FOREIGN KEY `FK_CK_DO_CK_ACCN4`;
ALTER TABLE `clickargo`.`T_CK_DO` 
DROP INDEX `FK_CK_DO_CK_ACCN4` ;
;

ALTER TABLE `clickargo`.`T_CK_DO` 
CHANGE COLUMN `DO_NOTIFY_ACCN` `DO_NOTIFY_ACCN` VARCHAR(255) NULL DEFAULT NULL COMMENT 'NOTIFICATION ACCOUNT ASSOCIATED WITH DO' ;


-- 2023-04-13 Remove submit for do claim
DELETE FROM `clickargo`.`T_CK_FORM_CONTROL` WHERE (`CTRL_ID` = '11');
DELETE FROM `clickargo`.`T_CK_FORM_CONTROL` WHERE (`CTRL_ID` = '14');

