-- 2023-05-05 Nina - Modified navigation labels and groupings
UPDATE `clickargo`.`T_CORE_MENU_EX` SET `MENU_GROUP_LABEL` = 'DO Claim', `MENU_GROUP_LABEL_OTH` = 'DO Claim', `MENU_NAME` = 'DO Claim', `MENU_NAME_OTH` = 'DO Claim' WHERE (`MENU_ID` = 'CK_MS_010000');
UPDATE `clickargo`.`T_CORE_MENU_EX` SET `MENU_GROUP_LABEL` = 'DO Payments', `MENU_GROUP_LABEL_OTH` = 'DO Payments', `MENU_NAME` = 'DO Payments', `MENU_NAME_OTH`= 'DO Payments' WHERE (`MENU_ID` = 'CK_MP_020000');
INSERT INTO `clickargo`.`T_CORE_MENU_EX` (`MENU_ID`, `MENU_APPS_CODE`, `MENU_GROUP_LABEL`, `MENU_GROUP_LABEL_OTH`, `MENU_NAME`, `MENU_NAME_OTH`, `MENU_SEQ`, `MENU_PATH`, `MENU_ICON`, `MENU_STATUS`, `MENU_DT_CREATE`, `MENU_UID_CREATE`, `MENU_DT_LUPD`, `MENU_UID_LUPD`) VALUES ('CK_MP_020300', 'CK', 'Transactions', 'Transactions', 'Transactions', 'Transactions', '40000', '/payments/transactions', NULL, 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');
UPDATE `clickargo`.`T_CORE_PERM_EX` SET `PERM_MENU` = 'CK_MP_020300' WHERE (`PERM_ID` = 'PM025');
UPDATE `clickargo`.`T_CORE_MENU_EX` SET `MENU_SEQ` = '20300', `MENU_PARENT` = 'CK_MP_020000' WHERE (`MENU_ID` = 'CK_MP_020300');
UPDATE `clickargo`.`T_CORE_MENU_EX` SET `MENU_PATH` = '/payments/transactions/list' WHERE (`MENU_ID` = 'CK_MP_020300');

-- Nina - altered to add job type
ALTER TABLE `clickargo`.`T_CK_DO_PAYMENT` 
ADD COLUMN `DOP_JOB_TYPE` VARCHAR(3) NOT NULL COMMENT 'IDC (IMPORT DO CLAIM), IDE (IMPORT DO EXTENSION)' AFTER `DOP_PAYMENT_TXN`;

-- Nina - invoice types for DO Extensions
INSERT INTO `clickargo`.`T_CK_MST_INVOICE_TYPE` (`INVT_ID`, `INVT_NAME`, `INVT_DESC`, `INVT_DESC_OTH`, `INVT_STATUS`, `INVT_DT_CREATE`, `INVT_UID_CREATE`, `INVT_DT_LUPD`, `INVT_UID_LUPD`) VALUES ('I-PLFE', 'INVOICE PLATFORM FEE EXTENSION', 'INVOICE PLATFORM FEE EXTENSION', 'INVOICE PLATFORM FEE EXTENSION', 'A', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'SYS');
INSERT INTO `clickargo`.`T_CK_MST_INVOICE_TYPE` (`INVT_ID`, `INVT_NAME`, `INVT_DESC`, `INVT_DESC_OTH`, `INVT_STATUS`, `INVT_DT_CREATE`, `INVT_UID_CREATE`, `INVT_DT_LUPD`, `INVT_UID_LUPD`) VALUES ('I-OAFE', 'OPTIONAL ADMIN FEE PER DO', 'OPTIONAL ADMIN FEE PER DO', 'OPTIONAL ADMIN FEE PER DO', 'A', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'SYS');
INSERT INTO `clickargo`.`T_CK_MST_INVOICE_TYPE` (`INVT_ID`, `INVT_NAME`, `INVT_DESC`, `INVT_DESC_OTH`, `INVT_STATUS`, `INVT_DT_CREATE`, `INVT_UID_CREATE`, `INVT_DT_LUPD`, `INVT_UID_LUPD`) VALUES ('I-CFE', 'DO CONTAINER FEE', 'DO CONTAINER FEE', 'DO CONTAINER FEE', 'A', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'SYS');



-- 2023-05-07 VIEW TO LIST CONFIRMED JOBS FOR PAYMENT
CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `CONFIRMED_DO_JOBS_VIEW` AS
    SELECT 
        `TBL_CLAIMS`.`JOB_ID` AS `JOB_ID`,
        `TBL_CLAIMS`.`SHIPMENT_TYPE` AS `SHIPMENT_TYPE`,
        `TBL_CLAIMS`.`DO_JOB_TYPE` AS `DO_JOB_TYPE`,
        `TBL_CLAIMS`.`SL_ACCN` AS `SL_ACCN`,
        `TBL_CLAIMS`.`CO_ACCN` AS `CO_ACCN`,
        `TBL_CLAIMS`.`FF_ACCN` AS `FF_ACCN`,
        `TBL_CLAIMS`.`OWNER_ACCN` AS `OWNER_ACCN`,
        `TBL_CLAIMS`.`SUBMITTED_DATE` AS `SUBMITTED_DATE`,
        `TBL_CLAIMS`.`CURRENCY` AS `CURRENCY`,
        `TBL_CLAIMS`.`TOTAL_BY_JOB` AS `TOTAL_BY_JOB`,
        `TBL_CLAIMS`.`JOB_STATE` AS `JOB_STATE`,
        `TBL_CLAIMS`.`DO_LIST_BY_JOB` AS `DO_LIST_BY_JOB`
    FROM
        (SELECT 
            `C`.`DOC_JOB_DO_CLAIM` AS `JOB_ID`,
                `E`.`JOB_SHIPMENT_TYPE` AS `SHIPMENT_TYPE`,
                'CLAIM' AS `DO_JOB_TYPE`,
                `E`.`JOB_SL_ACCN` AS `SL_ACCN`,
                `E`.`JOB_CO_ACCN` AS `CO_ACCN`,
                `E`.`JOB_FF_ACCN` AS `FF_ACCN`,
                `E`.`JOB_OWNER_ACCN` AS `OWNER_ACCN`,
                `F`.`RCD_DT_SUBMIT` AS `SUBMITTED_DATE`,
                `A`.`INV_CCY` AS `CURRENCY`,
                (COALESCE(SUM(`A`.`INV_AMOUNT`), 0) + COALESCE(SUM(`A`.`INV_TAX_AMOUNT`), 0)) AS `TOTAL_BY_JOB`,
                `E`.`JOB_STATE` AS `JOB_STATE`,
                GROUP_CONCAT(DISTINCT `A`.`INV_DO`
                    SEPARATOR ',') AS `DO_LIST_BY_JOB`
        FROM
            (((((`T_CK_DO_INVOICE` `A`
        LEFT JOIN `T_CK_DO` `B` ON ((`A`.`INV_DO` = `B`.`DO_ID`)))
        LEFT JOIN `T_CK_DO_CLAIM` `C` ON ((`C`.`DOC_DO` = `B`.`DO_ID`)))
        LEFT JOIN `T_CK_JOB_DO_CLAIM` `D` ON ((`C`.`DOC_JOB_DO_CLAIM` = `D`.`JOB_ID`)))
        LEFT JOIN `T_CK_JOB` `E` ON ((`D`.`JOB_PARENT` = `E`.`JOB_ID`)))
        LEFT JOIN `T_CK_RECORD_DATE` `F` ON ((`F`.`RCD_ID` = `E`.`JOB_DATES`)))
        WHERE
            (`E`.`JOB_STATE` = 'CON')
        GROUP BY `C`.`DOC_JOB_DO_CLAIM` , `E`.`JOB_SHIPMENT_TYPE` , `F`.`RCD_DT_SUBMIT` , `A`.`INV_CCY` , `E`.`JOB_STATE` , `E`.`JOB_SL_ACCN` , `E`.`JOB_CO_ACCN` , `E`.`JOB_FF_ACCN` , `E`.`JOB_OWNER_ACCN`) `TBL_CLAIMS` 
    UNION SELECT 
        `TBL_EXT`.`JOB_ID` AS `JOB_ID`,
        `TBL_EXT`.`SHIPMENT_TYPE` AS `SHIPMENT_TYPE`,
        `TBL_EXT`.`DO_JOB_TYPE` AS `DO_JOB_TYPE`,
        `TBL_EXT`.`SL_ACCN` AS `SL_ACCN`,
        `TBL_EXT`.`CO_ACCN` AS `CO_ACCN`,
        `TBL_EXT`.`FF_ACCN` AS `FF_ACCN`,
        `TBL_EXT`.`OWNER_ACCN` AS `OWNER_ACCN`,
        `TBL_EXT`.`SUBMITTED_DATE` AS `SUBMITTED_DATE`,
        `TBL_EXT`.`CURRENCY` AS `CURRENCY`,
        `TBL_EXT`.`TOTAL_BY_JOB` AS `TOTAL_BY_JOB`,
        `TBL_EXT`.`JOB_STATE` AS `JOB_STATE`,
        `TBL_EXT`.`DO_LIST_BY_JOB` AS `DO_LIST_BY_JOB`
    FROM
        (SELECT 
            `D`.`JOB_DO_EXT` AS `JOB_ID`,
                `E`.`JOB_SHIPMENT_TYPE` AS `SHIPMENT_TYPE`,
                'EXTENSION' AS `DO_JOB_TYPE`,
                `E`.`JOB_SL_ACCN` AS `SL_ACCN`,
                `E`.`JOB_CO_ACCN` AS `CO_ACCN`,
                `E`.`JOB_FF_ACCN` AS `FF_ACCN`,
                `E`.`JOB_OWNER_ACCN` AS `OWNER_ACCN`,
                `F`.`RCD_DT_SUBMIT` AS `SUBMITTED_DATE`,
                `A`.`INV_CCY` AS `CURRENCY`,
                (COALESCE(SUM(`A`.`INV_AMOUNT`), 0) + COALESCE(SUM(`A`.`INV_TAX_AMOUNT`), 0)) AS `TOTAL_BY_JOB`,
                `E`.`JOB_STATE` AS `JOB_STATE`,
                GROUP_CONCAT(DISTINCT `A`.`INV_DO`
                    SEPARATOR ',') AS `DO_LIST_BY_JOB`
        FROM
            (((((`T_CK_DO_INVOICE` `A`
        LEFT JOIN `T_CK_DO` `B` ON ((`A`.`INV_DO` = `B`.`DO_ID`)))
        LEFT JOIN `T_CK_DO_EXT` `C` ON ((`C`.`DOX_DO` = `B`.`DO_ID`)))
        LEFT JOIN `T_CK_JOB_DO_EXT` `D` ON ((`C`.`DOX_ID` = `D`.`JOB_DO_EXT`)))
        LEFT JOIN `T_CK_JOB` `E` ON ((`D`.`JOB_PARENT` = `E`.`JOB_ID`))  AND ((`A`.`INV_JOB_ID` = `E`.`JOB_ID`)))
        LEFT JOIN `T_CK_RECORD_DATE` `F` ON ((`F`.`RCD_ID` = `E`.`JOB_DATES`)))
        WHERE
            (`A`.`INV_TYPE` IN ('I-OAFE','I-PLFE','I-CFE')) AND
            (`E`.`JOB_STATE` = 'CON')
        GROUP BY `D`.`JOB_ID` , `E`.`JOB_SHIPMENT_TYPE` , `F`.`RCD_DT_SUBMIT` , `A`.`INV_CCY` , `E`.`JOB_STATE` , `E`.`JOB_SL_ACCN` , `E`.`JOB_CO_ACCN` , `E`.`JOB_FF_ACCN` , `E`.`JOB_OWNER_ACCN`) `TBL_EXT`
        ;


-- 2023-05-07 
DELETE FROM `clickargo`.`T_CORE_MENU_EX` WHERE (`MENU_ID` = 'CK_MP_020200');
UPDATE `clickargo`.`T_CORE_MENU_EX` SET `MENU_GROUP_LABEL` = 'Payments', `MENU_GROUP_LABEL_OTH` = 'Payments', `MENU_NAME` = 'Payments', `MENU_NAME_OTH` = 'Payments' WHERE (`MENU_ID` = 'CK_MP_020100');
UPDATE `clickargo`.`T_CORE_MENU_EX` SET `MENU_PATH` = '/payments/active/list' WHERE (`MENU_ID` = 'CK_MP_020100');

DELETE FROM `clickargo`.`T_CK_MST_SERVICE_TYPE` WHERE (`SVCT_ID` = 'CLICDOEXT');

-- 2023-05-10 - add field job id for do invoice
ALTER TABLE `clickargo`.`T_CK_DO_INVOICE` ADD `INV_JOB_ID` varchar(35) NULL COMMENT 'JOB REFERENCE - REFERENCE T_CK_JOB:JOB_ID';
ALTER TABLE `clickargo`.`T_CK_DO_INVOICE` CHANGE INV_JOB_ID INV_JOB_ID varchar(35) COMMENT 'JOB REFERENCE - REFERENCE T_CK_JOB:JOB_ID' AFTER `INV_DO`;
ALTER TABLE `clickargo`.`T_CK_DO_INVOICE` ADD CONSTRAINT `FK_CK_DO_INVOICE_CK_JOB` FOREIGN KEY (`INV_JOB_ID`) REFERENCES `clickargo`.`T_CK_JOB`(`JOB_ID`);

ALTER TABLE `clickargo`.`T_CK_PAYMENT_AUDIT` 
CHANGE COLUMN `PYA_STATE` `PYA_STATE` VARCHAR(30) NULL DEFAULT NULL ;

ALTER TABLE `clickargo`.`T_CK_RECORD_DATE` ADD `RCD_DT_ASSIGNED` DATETIME NULL COMMENT 'RECORD ASSIGNED DATE';
ALTER TABLE `clickargo`.`T_CK_RECORD_DATE` CHANGE `RCD_DT_ASSIGNED` `RCD_DT_ASSIGNED` DATETIME NULL COMMENT 'RECORD ASSIGNED DATE' AFTER `RCD_DT_SUBMIT`;
ALTER TABLE `clickargo`.`T_CK_RECORD_DATE` ADD `RCD_DT_PAID` DATETIME NULL COMMENT 'RECORD PAID DATE';
ALTER TABLE `clickargo`.`T_CK_RECORD_DATE` CHANGE `RCD_DT_PAID` `RCD_DT_PAID` DATETIME NULL COMMENT 'RECORD PAID DATE' AFTER `RCD_DT_ASSIGNED`;

INSERT INTO `clickargo`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES('CLICDO_MSC_VALIDATION_QRCODE', 'http://clicdo.vcargocloud.com/clicdo/qrcode/', 'Host Url Validation QrCode', '2023-02-09 00:00:00', 'SYS', '2023-02-09 00:00:00', 'SYS', 'A');

ALTER TABLE `clickargo`.`T_CK_CNT` ADD `CNT_VALID_DATE` DATETIME NULL COMMENT 'EXPIRATION DATE FROM MSC, TO CALCULATE DO EXTENSION';
ALTER TABLE `clickargo`.`T_CK_CNT` CHANGE `CNT_VALID_DATE` `CNT_VALID_DATE` DATETIME NULL COMMENT 'EXPIRATION DATE FROM MSC, TO CALCULATE DO EXTENSION' AFTER `CNT_STATUS_QUARANTINE`;

CREATE TABLE `clickargo`.`T_CK_DO_PRINTOUT` (
	`PRINTOUT_ID` varchar(35) NOT NULL COMMENT 'PRINTOUT ID',
	`PRINTOUT_JOB_ID` varchar(35) NOT NULL COMMENT 'JOB ID - REFERENCES T_CK_DO_JOB',
	`PRINTOUT_TYPE` varchar(35) NULL COMMENT 'PRINTOUT TYPE',
	`PRINTOUT_DT_CREATE` DATETIME NULL COMMENT 'RECORD CREATE DATE',
	`PRINTOUT_UID_CREATE` VARCHAR(35) NULL COMMENT 'RECORD CREATE USER',
	`PRINTOUT_DT_LUPD` varchar(35) NULL COMMENT 'RECORD UPDATE DATE',
	`PRINTOUT_UID_LUPD` varchar(35) NULL COMMENT 'RECORD UPDATE USER',
	CONSTRAINT `PRIMARY` PRIMARY KEY (`PRINTOUT_ID`),
	CONSTRAINT `FK_CK_DO_PRINTOUT_CK_JOB` FOREIGN KEY (`PRINTOUT_JOB_ID`) REFERENCES `clickargo`.`T_CK_JOB`(`JOB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
ALTER TABLE `clickargo`.`T_CK_DO_PRINTOUT` COMMENT='DO PRINTOUT';

INSERT INTO clickargo.T_CORE_SYSPARAM (SYS_KEY, SYS_VAL, SYS_DESC, SYS_DT_CREATE, SYS_UID_CREATE, SYS_DT_LUPD, SYS_UID_LUPD, SYS_STATUS) VALUES('VAT_PERCENTAGE', '0.11', 'VAT percentage', '2023-05-05 00:00:00', 'SYS', '2023-05-05 00:00:00', 'SYS', 'A');
INSERT INTO clickargo.T_CORE_SYSPARAM (SYS_KEY, SYS_VAL, SYS_DESC, SYS_DT_CREATE, SYS_UID_CREATE, SYS_DT_LUPD, SYS_UID_LUPD, SYS_STATUS) VALUES('WHT_PERCENTAGE', '0.2', 'Withholding tax percentage', '2023-05-05 00:00:00', 'SYS', '2023-05-05 00:00:00', 'SYS', 'A');
INSERT INTO clickargo.T_CORE_SYSPARAM (SYS_KEY, SYS_VAL, SYS_DESC, SYS_DT_CREATE, SYS_UID_CREATE, SYS_DT_LUPD, SYS_UID_LUPD, SYS_STATUS) VALUES('CLICDO_JRXML_DEMURRAGE_INV', 'docs/DOExt.jrxml', 'Delivery Order MSC Template', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');
INSERT INTO clickargo.T_CORE_SYSPARAM (SYS_KEY, SYS_VAL, SYS_DESC, SYS_DT_CREATE, SYS_UID_CREATE, SYS_DT_LUPD, SYS_UID_LUPD, SYS_STATUS) VALUES('CLICDO_PAYMENT_CALLBACK', 'http://clicdo.vcargocloud.com/be/clicdo/api/v1/payment', 'Payment Callback Virtual Account ', '2018-12-01 00:00:00', 'SYS', '2018-12-01 00:00:00', 'SYS', 'A');

-- 2023-06-05 add field submitter
ALTER TABLE clickargo.T_CK_JOB_DO_CLAIM ADD JOB_SUBMITTER varchar(255) NULL COMMENT 'JOB SUBMITTER NAME';
ALTER TABLE clickargo.T_CK_JOB_DO_CLAIM CHANGE JOB_SUBMITTER JOB_SUBMITTER varchar(255) NULL COMMENT 'JOB SUBMITTER NAME' AFTER JOB_DT_DOC_VERIFY;
ALTER TABLE clickargo.T_CK_JOB_DO_CLAIM ADD JOB_DT_SUBMITTER DATETIME NULL COMMENT 'RECORD SUBMITTER DATE';
ALTER TABLE clickargo.T_CK_JOB_DO_CLAIM CHANGE JOB_DT_SUBMITTER JOB_DT_SUBMITTER DATETIME NULL COMMENT 'RECORD SUBMITTER DATE' AFTER JOB_SUBMITTER;
ALTER TABLE clickargo.T_CK_JOB_DO_CLAIM ADD JOB_REMARK varchar(1024) NULL;
ALTER TABLE clickargo.T_CK_JOB_DO_CLAIM CHANGE JOB_REMARK JOB_REMARK varchar(1024) NULL AFTER JOB_DT_SUBMITTER;

-- 2023-06-06 add table do doc attach and do doc attach state
CREATE TABLE `T_CK_MST_DO_DOC_ATTACH_STATE` (
  `DOATT_ID` varchar(35) NOT NULL COMMENT 'DO DOC ATTCH STATE ID',
  `DOATT_NAME` varchar(100) NOT NULL COMMENT 'DO DOC ATTCH STATE NAME',
  `DOATT_DESC` varchar(255) DEFAULT NULL COMMENT 'DO DOC ATTCH STATE DESCRIPTION',
  `DOATT_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'DO DOC ATTCH STATE DESCRIPTION OTHER LANGUAGE',
  `DOATT_STATUS` char(1) DEFAULT NULL COMMENT 'DO DOC ATTCH STATE STATUS',
  `DOATT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `DOATT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `DOATT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `DOATT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`DOATT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DO DOC ATTACH STATE TABLE';

INSERT INTO clickargo.T_CK_MST_DO_DOC_ATTACH_STATE (DOATT_ID, DOATT_NAME, DOATT_DESC, DOATT_DESC_OTH, DOATT_STATUS, DOATT_DT_CREATE, DOATT_UID_CREATE, DOATT_DT_LUPD, DOATT_UID_LUPD) VALUES('NEW', 'NEW', 'NEW', 'NEW', 'A', '2023-06-06 00:00:00', 'SYS', '2023-06-06 00:00:00', 'SYS');
INSERT INTO clickargo.T_CK_MST_DO_DOC_ATTACH_STATE (DOATT_ID, DOATT_NAME, DOATT_DESC, DOATT_DESC_OTH, DOATT_STATUS, DOATT_DT_CREATE, DOATT_UID_CREATE, DOATT_DT_LUPD, DOATT_UID_LUPD) VALUES('OUTSTANDING', 'OUTSTANDING', 'OUTSTANDING', 'OUTSTANDING', 'A', '2023-06-06 00:00:00', 'SYS', '2023-06-06 00:00:00', 'SYS');
INSERT INTO clickargo.T_CK_MST_DO_DOC_ATTACH_STATE (DOATT_ID, DOATT_NAME, DOATT_DESC, DOATT_DESC_OTH, DOATT_STATUS, DOATT_DT_CREATE, DOATT_UID_CREATE, DOATT_DT_LUPD, DOATT_UID_LUPD) VALUES('REJECT', 'REJECT', 'REJECT', 'REJECT', 'A', '2023-06-06 00:00:00', 'SYS', '2023-06-06 00:00:00', 'SYS');
INSERT INTO clickargo.T_CK_MST_DO_DOC_ATTACH_STATE (DOATT_ID, DOATT_NAME, DOATT_DESC, DOATT_DESC_OTH, DOATT_STATUS, DOATT_DT_CREATE, DOATT_UID_CREATE, DOATT_DT_LUPD, DOATT_UID_LUPD) VALUES('VERIFY', 'VERIFY', 'VERIFY', 'VERIFY', 'A', '2023-06-06 00:00:00', 'SYS', '2023-06-06 00:00:00', 'SYS');

CREATE TABLE `T_CK_DO_DOC_ATTACH` (
  `DOCATT_ID` varchar(35) NOT NULL COMMENT 'DOC ATTACH ID - UUID',
  `DOCATT_JOB_ATTCH` varchar(35) DEFAULT NULL COMMENT 'JOB ATTACH REFERENCE - T_CK_JOB_ATTACH:ATT_ID',
  `DOCATT_DOC_STATE` varchar(35) DEFAULT NULL COMMENT 'DOC ATTACH STATE REFERENCE - T_CK_MST_DO_DOC_ATTACH_STATE:DOATT_ID',
  `DOCATT_SUBMITTER_NAME` varchar(255) DEFAULT NULL COMMENT 'DOC ATTACH SUBMITTER NAME',
  `DOCATT_DT_SUBMITTER` datetime DEFAULT NULL COMMENT 'DOC ATTACH SUBMITTER DATE',
  `DOCATT_RETURN_VERIFIER` varchar(35) DEFAULT NULL COMMENT 'DOC ATTACH RETURN VERIFIER',
  `DOCATT_DT_RETURN_VERIFIER` datetime DEFAULT NULL COMMENT 'DOC ATTACH RETURN VIRIFIER DATE',
  `DOCATT_RETURN_REMARK` mediumtext COMMENT 'DOC ATTACH RETURN REMARK',
  `DOCATT_STATUS` char(1) DEFAULT NULL COMMENT 'DOC ATTACH STATUS',
  `DOCATT_DT_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `DOCATT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `DOCATT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `DOCATT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`DOCATT_ID`),
  KEY `FK_CK_DO_DOC_ATTACH_CK_JOB_ATTACH` (`DOCATT_JOB_ATTCH`),
  KEY `FK_CK_DO_DOC_ATTACH_CK_MST_DO_DOC_ATTACH_STATE` (`DOCATT_DOC_STATE`),
  CONSTRAINT `FK_CK_DO_DOC_ATTACH_CK_JOB_ATTACH` FOREIGN KEY (`DOCATT_JOB_ATTCH`) REFERENCES `T_CK_JOB_ATTACH` (`ATT_ID`),
  CONSTRAINT `FK_CK_DO_DOC_ATTACH_CK_MST_DO_DOC_ATTACH_STATE` FOREIGN KEY (`DOCATT_DOC_STATE`) REFERENCES `T_CK_MST_DO_DOC_ATTACH_STATE` (`DOATT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DO DOC ATTACHMENT TABLE';

CREATE TABLE `T_CK_DO_DOC_HISTORY` (
  `DOCH_ID` varchar(35) NOT NULL COMMENT 'DO DOC HISTORY ID - UUID',
  `DOCH_JOB_ATTCH` varchar(35) DEFAULT NULL COMMENT 'JOB ATTACH REFERENCE - T_CK_JOB_ATTACH:ATT_ID',
  `DOCH_DOC_STATE` varchar(35) DEFAULT NULL COMMENT 'DOC HISTORY ATTACH STATE REFERENCE - T_CK_MST_DO_DOC_ATTACH_STATE:DOATT_ID',
  `DOCH_REMARK` varchar(35) DEFAULT NULL COMMENT 'DOC HISTORY REMARK REFERENCE - T_CK_JOB_QUERY:QRY_ID',
  `DOCH_STATUS` char(1) DEFAULT NULL COMMENT 'DOC HISTORY STATUS',
  `DOCH_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `DOCH_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `DOCH_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `DOCH_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`DOCH_ID`),
  KEY `FK_CK_DO_DOC_HISTORY_CK_MST_DO_DOC_ATTACH_STATE` (`DOCH_DOC_STATE`),
  KEY `FK_CK_DO_DOC_HISTORY_CK_JOB_ATTACH` (`DOCH_JOB_ATTCH`),
  KEY `FK_CK_DO_DOC_HISTORY_CK_JOB_QUERY` (`DOCH_REMARK`),
  CONSTRAINT `FK_CK_DO_DOC_HISTORY_CK_JOB_ATTACH` FOREIGN KEY (`DOCH_JOB_ATTCH`) REFERENCES `T_CK_JOB_ATTACH` (`ATT_ID`),
  CONSTRAINT `FK_CK_DO_DOC_HISTORY_CK_JOB_QUERY` FOREIGN KEY (`DOCH_REMARK`) REFERENCES `T_CK_JOB_QUERY` (`QRY_ID`),
  CONSTRAINT `FK_CK_DO_DOC_HISTORY_CK_MST_DO_DOC_ATTACH_STATE` FOREIGN KEY (`DOCH_DOC_STATE`) REFERENCES `T_CK_MST_DO_DOC_ATTACH_STATE` (`DOATT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DO DOC ATTACHEMENT HISTORY TABLE';

ALTER TABLE clickargo.T_CK_JOB_DO_CLAIM ADD JOB_DT_DOC_REJECT DATETIME NULL COMMENT 'DOCUMENT REJECT DATE';
ALTER TABLE clickargo.T_CK_JOB_DO_CLAIM CHANGE JOB_DT_DOC_REJECT JOB_DT_DOC_REJECT DATETIME NULL COMMENT 'DOCUMENT REJECT DATE' AFTER JOB_DT_DOC_VERIFY;

-- 20 Juni 2023 add table do vessel voyage and exchange rate for extension
CREATE TABLE `T_CK_DO_VESSEL_VOYAGE` (
  `VV_ID` varchar(35) NOT NULL COMMENT 'VESSEL VOYAGE ID - UUID',
  `VV_VESSEL_NAME` varchar(45) DEFAULT NULL COMMENT 'VESSEL NAME',
  `VV_VOYAGE_NUMBER` varchar(45) DEFAULT NULL COMMENT 'VOYAGE NUMBER',
  `VV_STATUS` char(1) DEFAULT NULL COMMENT 'VESSEL STATUS',
  `VV_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `VV_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `VV_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `VV_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DO VESSEL VOYAGE';

CREATE TABLE `T_CK_DO_EXCHANGE_RATE` (
  `EXR_ID` varchar(35) NOT NULL COMMENT 'EXCHANGE RATE ID - UUID',
  `EXR_CCY_FROM` varchar(3) DEFAULT NULL COMMENT 'CURRENCY FROM - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `EXR_CCY_TO` varchar(3) DEFAULT NULL COMMENT 'CURRENCY TO - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `EXR_RATE` decimal(15,2) DEFAULT NULL COMMENT 'EXCHANGE RATE',
  `EXR_DT_RATE` datetime DEFAULT NULL COMMENT 'EXCHANGE RATE DATE',
  `EXR_VESSEL_VOYAGE` varchar(35) DEFAULT NULL COMMENT 'VESSEL - REFERENCES T_CK_DO_VESSEL_VOYAGE:VV_ID',
  `EXR_POL` varchar(5) DEFAULT NULL COMMENT 'PORT OF LOADING',
  `EXR_POD` varchar(5) DEFAULT NULL COMMENT 'PORT OF DISCHARGE',
  `EXR_TYPE` varchar(35) DEFAULT NULL COMMENT 'SHIPMENT TYPE - REFERENCES T_CK_MST_SHIPMENT_TYPE:SHT_ID',
  `EXR_STATUS` char(1) DEFAULT NULL COMMENT 'EXCHANGE RATE STATUS',
  `EXR_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `EXR_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `EXR_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `EXR_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`EXR_ID`),
  KEY `FK_CK_DO_EXCHANGE_RATE_CCY_FROM_MST_CURRENCY` (`EXR_CCY_FROM`),
  KEY `FK_CK_DO_EXCHANGE_RATE_CCY_TO_MST_CURRENCY` (`EXR_CCY_TO`),
  KEY `FK_CK_DO_EXCHANGE_RATE_CK_MST_SHIPMENT_TYPE` (`EXR_TYPE`),
  KEY `FK_CK_DO_EXCHANGE_RATE_CK_DO_VESSEL_VOAYGE` (`EXR_VESSEL_VOYAGE`),
  KEY `FK_CK_DO_EXCHANGE_RATE_MST_PORT_POL` (`EXR_POL`),
  KEY `FK_CK_DO_EXCHANGE_RATE_MST_PORT_POD` (`EXR_POD`),
  CONSTRAINT `FK_CK_DO_EXCHANGE_RATE_CCY_FROM_MST_CURRENCY` FOREIGN KEY (`EXR_CCY_FROM`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`),
  CONSTRAINT `FK_CK_DO_EXCHANGE_RATE_CCY_TO_MST_CURRENCY` FOREIGN KEY (`EXR_CCY_TO`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`),
  CONSTRAINT `FK_CK_DO_EXCHANGE_RATE_CK_DO_VESSEL_VOAYGE` FOREIGN KEY (`EXR_VESSEL_VOYAGE`) REFERENCES `T_CK_DO_VESSEL_VOYAGE` (`VV_ID`),
  CONSTRAINT `FK_CK_DO_EXCHANGE_RATE_CK_MST_SHIPMENT_TYPE` FOREIGN KEY (`EXR_TYPE`) REFERENCES `T_CK_MST_SHIPMENT_TYPE` (`SHT_ID`),
  CONSTRAINT `FK_CK_DO_EXCHANGE_RATE_MST_PORT_POD` FOREIGN KEY (`EXR_POD`) REFERENCES `T_MST_PORT` (`PORT_CODE`),
  CONSTRAINT `FK_CK_DO_EXCHANGE_RATE_MST_PORT_POL` FOREIGN KEY (`EXR_POL`) REFERENCES `T_MST_PORT` (`PORT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DO EXCHANGE RATE';

-- 2023 Juli 20 add table t_ck_do_sap for SAP to MSC
-- clickargo.T_CK_DO_SAP definition

CREATE TABLE `T_CK_DO_SAP` (
  `SAP_ID` varchar(35) NOT NULL COMMENT 'THE UNIQUE ID',
  `SAP_JOB_NO` varchar(35) NOT NULL COMMENT 'JOB NUMBER, REFERENCE: T_CK_JOB:JOB_ID',
  `SAP_DEMURRAGE_FEE` decimal(15,2) NOT NULL COMMENT 'DEMURRAGE FEE / I-CFE',
  `SAP_ADMIN_FEE` decimal(15,2) DEFAULT NULL COMMENT 'ADMIN FEE, IF ANY. I-OAFE',
  `SAP_TOTAL_AMOUNT` decimal(15,2) DEFAULT NULL COMMENT 'TOTAL AMOUNT (DEMURRAGE + ADMIN FEE)',
  `SAP_PROFORMA_NO` varchar(45) NOT NULL COMMENT 'T_CK_DO_INVOICE.INV_ID. TAKE THE  I-CFE.',
  `SAP_NO_CNT` smallint DEFAULT NULL COMMENT 'NUMBER OF CONTAINERS',
  `SAP_VALID_DATE` datetime DEFAULT NULL COMMENT 'SAP EXTENSION VALID DATE',
  `SAP_DISBURSEMENT_PAYMENT_REF` varchar(35) DEFAULT NULL COMMENT 'PAYMENT REFERENCE NUMBER',
  `SAP_DISBURSEMENT_DATE` datetime DEFAULT NULL COMMENT 'REFERENCE: T_CK_PAYMENT_TXN WHERE PTX_PAYEE = ''MSC''',
  `SAP_DEBITOR_ID` varchar(45) DEFAULT NULL COMMENT 'SAP DEBITOR ID. ',
  `SAP_STATUS_STATE` varchar(45) DEFAULT NULL COMMENT 'SAP STATUS: PAID, INVOICED, RECONCILE, POSTED',
  `SAP_STATUS` char(1) DEFAULT NULL COMMENT 'SAP STATUS: INACTIVE, ACTIVE',
  `SAP_ACCOUNT_NO` varchar(45) DEFAULT NULL COMMENT 'SAP ACCOUNT NUMBER',
  `SAP_COFF_NAME` varchar(255) DEFAULT NULL COMMENT 'CARGO OWNER OR FORWARDER NAME.',
  `SAP_DOCUMENT_NO` varchar(45) DEFAULT NULL COMMENT 'SAP DOCUMENT NUMBER',
  `SAP_GL_NO` varchar(45) DEFAULT NULL COMMENT 'SAP GENERAL LEDGER NUMBER',
  `SAP_OFFST_ACCT` varchar(45) DEFAULT NULL COMMENT 'SAP OFFST ACCOUNT NUMBER',
  `SAP_TYPE` varchar(45) DEFAULT NULL COMMENT 'SAP DOCUMENT TYPE',
  `SAP_REFERENCE` varchar(45) DEFAULT NULL COMMENT 'REFERENCE NUMBER. SHALL BE THE INVOICE NUMBER.',
  `SAP_ASSIGNMENT` varchar(45) DEFAULT NULL COMMENT 'ASSIGNMENT INFORMATION',
  `SAP_BL_NO` varchar(45) DEFAULT NULL COMMENT 'BL NUMBER',
  `SAP_YEAR_MONTH` varchar(45) DEFAULT NULL COMMENT 'YEAR AND MONTH OF INVOICE',
  `SAP_TEXT` varchar(45) DEFAULT NULL COMMENT 'REMARK',
  `SAP_PROFIT_CTR` varchar(45) DEFAULT NULL COMMENT 'PROFIT CENTER',
  `SAP_AMOUNT_IN_DC` decimal(15,2) DEFAULT NULL COMMENT 'INVOICE AMOUNT',
  `SAP_LCURR` varchar(3) DEFAULT NULL COMMENT 'LOCAL CURRENCY',
  `SAP_AMT_IN_LOCCUR` decimal(15,2) DEFAULT NULL COMMENT 'INVOICE AMOUNT IN LOCAL CURRENCY',
  `SAP_DOC_DATE` datetime DEFAULT NULL COMMENT 'INVOICE DATE FROM MSC EXCEL FILE.',
  `SAP_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `SAP_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `SAP_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `SAP_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATE USER',
  PRIMARY KEY (`SAP_ID`),
  UNIQUE KEY `SAP_ID_UNIQUE` (`SAP_ID`),
  KEY `SAP_FK_JOB_NUMBER_idx` (`SAP_JOB_NO`),
  CONSTRAINT `FK_CK_DO_SAP_CK_JOB` FOREIGN KEY (`SAP_JOB_NO`) REFERENCES `T_CK_JOB` (`JOB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='FOR SAP RECONCILIATION PURPOSE WITH MSC.';