/** DROP INDEX FOR T_CK_CNT */
ALTER TABLE `clickargo`.`T_CK_CNT` 
DROP FOREIGN KEY `FK_CK_CNT_CK_MST_CNT_SIZE`;
ALTER TABLE `clickargo`.`T_CK_CNT` 
DROP INDEX `FK_CK_CNT_CK_MST_CNT_SIZE` ;
;

ALTER TABLE `clickargo`.`T_CK_CNT` 
DROP FOREIGN KEY `FK_CK_CNT_CK_MST_CNT_TYPE`;
ALTER TABLE `clickargo`.`T_CK_CNT` 
DROP INDEX `FK_CK_CNT_CK_MST_CNT_TYPE` ;
;

ALTER TABLE `clickargo`.`T_CK_CNT` 
DROP FOREIGN KEY `FK_CK_CNT_MST_PORT1`;
ALTER TABLE `clickargo`.`T_CK_CNT` 
DROP INDEX `FK_CK_CNT_MST_PORT1` ;
;

ALTER TABLE `clickargo`.`T_CK_CNT` 
DROP FOREIGN KEY `FK_CK_CNT_MST_PORT2`;
ALTER TABLE `clickargo`.`T_CK_CNT` 
DROP INDEX `FK_CK_CNT_MST_PORT2` ;
;

/** NEW TABLE FOR T_CK_MSCGW_AUDIT */
CREATE TABLE `T_CK_MSCGW_AUDIT` (
  `GWA_ID` varchar(35) NOT NULL COMMENT 'MSC GATEWAY AUDIT ID - UUID',
  `GWA_REF` varchar(1024) DEFAULT NULL COMMENT 'MSC GATEWAY REFERENCE - LOGIN SESSON ID',
  `GWA_URI` varchar(2048) DEFAULT NULL COMMENT 'URI INVOKED FOR THE RESTFUL CALL', 
  `GWA_REQ` mediumtext COMMENT 'MSC GATEWAY REQUEST JSON',
  `GWA_RESP` mediumtext COMMENT 'MSC GATEWAY RESPONSE JSON',
  `GWA_ERROR` mediumtext COMMENT 'OPTIONAL ERROR STACK TRACE',
  `GWA_STATE` varchar(3) DEFAULT NULL,
  `GWA_STATUS` char(1) DEFAULT NULL COMMENT 'MSC GATEWAY AUDIT TYPE STATUS',
  `GWA_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `GWA_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `GWA_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `GWA_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`GWA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DO MSC GATEWAY AUDIT LOG';

/** Added CLICDO_JRXML_PLATFORM_FEE_COMM_INV */
INSERT INTO `clickargo`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICDO_JRXML_PLATFORM_FEE_COMM_INV', 'docs/CommercialInvoice.jrxml', 'Platform Fee Commercial Invoice', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

/** Item 34 - Document return need to capture name and date in MSC doc verification */ 
ALTER TABLE `clickargo`.`T_CK_JOB_ATTACH` 
ADD COLUMN `ATT_RETURN_VERIFIER` VARCHAR(35) NULL DEFAULT NULL AFTER `ATT_DT_RETURNED`;
