INSERT INTO T_CORE_SYSPARAM (SYS_KEY, SYS_VAL, SYS_DESC, SYS_DT_CREATE, SYS_UID_CREATE, SYS_DT_LUPD, SYS_UID_LUPD, SYS_STATUS) VALUES('DO_EXT_ADMINISTRATION', '20000', 'ADMINISTRATION FOR DO EXTENSION', '2023-04-08 00:00:00', 'SYS', '2023-04-08 00:00:00', 'SYS', 'A');
INSERT INTO T_CORE_SYSPARAM (SYS_KEY, SYS_VAL, SYS_DESC, SYS_DT_CREATE, SYS_UID_CREATE, SYS_DT_LUPD, SYS_UID_LUPD, SYS_STATUS) VALUES('DO_EXT_PLATFORM_FEE', '75000', 'PLATFORM FEE FOR DO EXTENSION', '2023-04-08 00:00:00', 'SYS', '2023-04-08 00:00:00', 'SYS', 'A');

INSERT INTO T_CK_MST_DO_STATE (DOST_ID, DOST_NAME, DOST_DESC, DOST_DESC_OTH, DOST_STATUS, DOST_DT_CREATE, DOST_UID_CREATE, DOST_DT_LUPD, DOST_UID_LUPD) VALUES('CMPLT', 'COMPLETED', 'COMPLETED', 'COMPLETED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
INSERT INTO T_CK_MST_DO_STATE (DOST_ID, DOST_NAME, DOST_DESC, DOST_DESC_OTH, DOST_STATUS, DOST_DT_CREATE, DOST_UID_CREATE, DOST_DT_LUPD, DOST_UID_LUPD) VALUES('CNCL', 'CANCEL', 'CANCEL', 'CANCEL', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
INSERT INTO T_CK_MST_DO_STATE (DOST_ID, DOST_NAME, DOST_DESC, DOST_DESC_OTH, DOST_STATUS, DOST_DT_CREATE, DOST_UID_CREATE, DOST_DT_LUPD, DOST_UID_LUPD) VALUES('CNF', 'CONFIRM', 'CONFIRM', 'CONFIRM', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
INSERT INTO T_CK_MST_DO_STATE (DOST_ID, DOST_NAME, DOST_DESC, DOST_DESC_OTH, DOST_STATUS, DOST_DT_CREATE, DOST_UID_CREATE, DOST_DT_LUPD, DOST_UID_LUPD) VALUES('NEW', 'NEW', 'NEW', 'NEW', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

-- 2023-04-17 New controls for DO claim for CO
INSERT INTO `T_CK_FORM_CONTROL` (`CTRL_ID`, `CTRL_ACCN_TYPE`, `CTRL_USR_ROLE`, `CTRL_ENTITY_TYPE`, `CTRL_ENTITY_STATE`, `CTRL_FORM_TYPE`, `CTRL_FORM_ACTION`, `CTRL_STATUS`, `CTRL_DT_CREATE`, `CTRL_UID_CREATE`, `CTRL_DT_LUPD`, `CTRL_UID_LUPD`) VALUES ('103', 'ACC_TYPE_CO', 'OFFICER', 'JOB_DOI_FF', 'NEW', 'EDIT', 'SAVE', 'A', '2022-11-15 09:10:55', 'SYS', '2022-11-15 09:10:55', 'SYS');
INSERT INTO `T_CK_FORM_CONTROL` (`CTRL_ID`, `CTRL_ACCN_TYPE`, `CTRL_USR_ROLE`, `CTRL_ENTITY_TYPE`, `CTRL_ENTITY_STATE`, `CTRL_FORM_TYPE`, `CTRL_FORM_ACTION`, `CTRL_STATUS`, `CTRL_DT_CREATE`, `CTRL_UID_CREATE`, `CTRL_DT_LUPD`, `CTRL_UID_LUPD`) VALUES ('104', 'ACC_TYPE_CO', 'OFFICER', 'JOB_DOI_FF', 'NEW', 'EDIT', 'DELETE', 'A', '2022-11-15 09:10:55', 'SYS', '2022-11-15 09:10:55', 'SYS');
INSERT INTO `T_CK_FORM_CONTROL` (`CTRL_ID`, `CTRL_ACCN_TYPE`, `CTRL_USR_ROLE`, `CTRL_ENTITY_TYPE`, `CTRL_ENTITY_STATE`, `CTRL_FORM_TYPE`, `CTRL_FORM_ACTION`, `CTRL_STATUS`, `CTRL_DT_CREATE`, `CTRL_UID_CREATE`, `CTRL_DT_LUPD`, `CTRL_UID_LUPD`) VALUES ('105', 'ACC_TYPE_CO', 'OFFICER', 'JOB_DOI_FF', 'NEW', 'EDIT', 'EXIT', 'A', '2022-11-15 09:10:55', 'SYS', '2022-11-15 09:10:55', 'SYS');

INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICDO_NO_MSC_API_CALL', 'Y', 'If Y, no MSC API call, ', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

-- ADD INVALID IN BL STATE
INSERT INTO `clickargo`.`T_CK_MST_BL_STATE` (`BLST_ID`, `BLST_NAME`, `BLST_DESC`, `BLST_DESC_OTH`, `BLST_STATUS`, `BLST_DT_CREATE`, `BLST_UID_CREATE`, `BLST_DT_LUPD`, `BLST_UID_LUPD`) VALUES ('INVALID', 'INVALID', 'INVALID', 'INVALID', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

-- 2023-04-18 NINA ADDED MENU
INSERT INTO `clickargo`.`T_CORE_MENU_EX` (`MENU_ID`, `MENU_APPS_CODE`, `MENU_GROUP_LABEL`, `MENU_GROUP_LABEL_OTH`, `MENU_NAME`, `MENU_NAME_OTH`, `MENU_SEQ`, `MENU_PATH`, `MENU_ICON`, `MENU_STATUS`, `MENU_DT_CREATE`, `MENU_UID_CREATE`, `MENU_DT_LUPD`, `MENU_UID_LUPD`) VALUES ('CK_MP_020100', 'CK', 'Claims', 'Claims', 'Claims', 'Claims', '20100', '/payments/claim', 'payment', 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');
UPDATE `clickargo`.`T_CORE_MENU_EX` SET `MENU_PATH` = NULL WHERE (`MENU_ID` = 'CK_MP_020000');

DELETE FROM `clickargo`.`T_CORE_GRANT_ROLE_EX` WHERE (`GNTRLEX_APPS_CODE` = 'CK') and (`GNTRLEX_ROLE_ID` = 'ADMIN') and (`GNTRLEX_PERM_ID` = 'PM006');
DELETE FROM `clickargo`.`T_CORE_GRANT_ROLE_EX` WHERE (`GNTRLEX_APPS_CODE` = 'CK') and (`GNTRLEX_ROLE_ID` = 'FINANCE') and (`GNTRLEX_PERM_ID` = 'PM006');
DELETE FROM `clickargo`.`T_CORE_GRANT_ROLE_EX` WHERE (`GNTRLEX_APPS_CODE` = 'CK') and (`GNTRLEX_ROLE_ID` = 'OFFICER') and (`GNTRLEX_PERM_ID` = 'PM006');
DELETE FROM `clickargo`.`T_CORE_GRANT_ROLE_EX` WHERE (`GNTRLEX_APPS_CODE` = 'CK') and (`GNTRLEX_ROLE_ID` = 'OPERATIONS') and (`GNTRLEX_PERM_ID` = 'PM006');
DELETE FROM `clickargo`.`T_CORE_GRANT_ROLE_EX` WHERE (`GNTRLEX_APPS_CODE` = 'CK') and (`GNTRLEX_ROLE_ID` = 'SYS_SUPER_ADMIN') and (`GNTRLEX_PERM_ID` = 'PM006');
DELETE FROM `clickargo`.`T_CORE_PERM_EX` WHERE (`PERM_ID` = 'PM006');
DELETE FROM `clickargo`.`T_CORE_MENU_EX` WHERE (`MENU_ID` = 'CK_MH_040000');


INSERT INTO `clickargo`.`T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'FINANCE', 'PM026', 'A', '2023-02-22 08:18:02', 'SYS');
INSERT INTO `clickargo`.`T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'OPERATIONS', 'PM026', 'A', '2023-02-22 08:18:02', 'SYS');
INSERT INTO `clickargo`.`T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'OFFICER', 'PM026', 'A', '2023-02-22 08:18:02', 'SYS');

INSERT INTO `clickargo`.`T_CORE_MENU_EX` (`MENU_ID`, `MENU_APPS_CODE`, `MENU_GROUP_LABEL`, `MENU_GROUP_LABEL_OTH`, `MENU_NAME`, `MENU_NAME_OTH`, `MENU_SEQ`, `MENU_PATH`, `MENU_ICON`, `MENU_STATUS`, `MENU_DT_CREATE`, `MENU_UID_CREATE`, `MENU_DT_LUPD`, `MENU_UID_LUPD`) VALUES ('CK_MZH_080000', 'CK', 'Help', 'Help', 'Help', 'Help', '80000', '/help', 'help_outline', 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');
UPDATE `clickargo`.`T_CORE_PERM_EX` SET `PERM_MENU` = 'CK_MZH_080000' WHERE (`PERM_ID` = 'PM026');
DELETE FROM `clickargo`.`T_CORE_MENU_EX` WHERE (`MENU_ID` = 'CK_MH_080000');

UPDATE `clickargo`.`T_CORE_MENU_EX` SET `MENU_PARENT` = 'CK_MP_020000' WHERE (`MENU_ID` = 'CK_MP_020100');
INSERT INTO `clickargo`.`T_CORE_MENU_EX` (`MENU_ID`, `MENU_APPS_CODE`, `MENU_GROUP_LABEL`, `MENU_GROUP_LABEL_OTH`, `MENU_NAME`, `MENU_NAME_OTH`, `MENU_SEQ`, `MENU_PATH`, `MENU_ICON`, `MENU_PARENT`, `MENU_STATUS`, `MENU_DT_CREATE`, `MENU_UID_CREATE`, `MENU_DT_LUPD`, `MENU_UID_LUPD`) VALUES ('CK_MP_020200', 'CK', 'Extensions', 'Extensions', 'Extensions', 'Extensions', '20200', '/payments/extension', NULL, 'CK_MP_020000', 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');
UPDATE `clickargo`.`T_CORE_MENU_EX` SET `MENU_ICON` = NULL WHERE (`MENU_ID` = 'CK_MP_020100');

UPDATE `clickargo`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'FF_FINANCE' WHERE (`UROL_UID` = 'ALKNAR_U002') and (`UROL_APPSCODE` = 'CK') and (`UROL_ROLEID` = 'OFFICER') and (`UROL_ADMIN_OPT` = 'N');

-- CREATED NEW ROLE - OFFICER_FINANCE FOR BOTH CO AND FF FINANCE
INSERT INTO `clickargo`.`T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`, `ROLE_STATUS`, `ROLE_DESC`, `ROLE_DT_CREATE`, `ROLE_UID_CREATE`, `ROLE_DT_LUPD`, `ROLE_UID_LUPD`) VALUES ('CK', 'OFFICER_FINANCE', 'A', 'OFFICER_FINANCE', '2022-11-15 09:09:14', 'SYS', '2022-11-15 09:09:14', 'SYS');

-- UPDATE EXISTING USER ROLES FROM FF_FINANCE TO OFFICER_FINANCE
UPDATE `clickargo`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'OFFICER_FINANCE' WHERE (`UROL_UID` = 'ALKNAR_U002') and (`UROL_APPSCODE` = 'CK') and (`UROL_ROLEID` = 'FF_FINANCE') and (`UROL_ADMIN_OPT` = 'N');
UPDATE `clickargo`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'OFFICER_FINANCE' WHERE (`UROL_UID` = 'COMLG_U002') and (`UROL_APPSCODE` = 'CK') and (`UROL_ROLEID` = 'FF_FINANCE') and (`UROL_ADMIN_OPT` = 'N');
UPDATE `clickargo`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'OFFICER_FINANCE' WHERE (`UROL_UID` = 'COMLG_U001') and (`UROL_APPSCODE` = 'CK') and (`UROL_ROLEID` = 'FF_FINANCE') and (`UROL_ADMIN_OPT` = 'N');
UPDATE `clickargo`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'OFFICER_FINANCE' WHERE (`UROL_UID` = 'DUNLS_U001') and (`UROL_APPSCODE` = 'CK') and (`UROL_ROLEID` = 'FF_FINANCE') and (`UROL_ADMIN_OPT` = 'N');
UPDATE `clickargo`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'OFFICER_FINANCE' WHERE (`UROL_UID` = 'FREXID_U001') and (`UROL_APPSCODE` = 'CK') and (`UROL_ROLEID` = 'FF_FINANCE') and (`UROL_ADMIN_OPT` = 'N');
UPDATE `clickargo`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'OFFICER_FINANCE' WHERE (`UROL_UID` = 'GNOCIN_U001') and (`UROL_APPSCODE` = 'CK') and (`UROL_ROLEID` = 'FF_FINANCE') and (`UROL_ADMIN_OPT` = 'N');
UPDATE `clickargo`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'OFFICER_FINANCE' WHERE (`UROL_UID` = 'YINDF_U001') and (`UROL_APPSCODE` = 'CK') and (`UROL_ROLEID` = 'FF_FINANCE') and (`UROL_ADMIN_OPT` = 'N');

-- UPDATED MENU FROM FF_FINANCE TO OFFICER_FINANCE
UPDATE `clickargo`.`T_CORE_GRANT_ROLE_EX` SET `GNTRLEX_ROLE_ID` = 'OFFICER_FINANCE' WHERE (`GNTRLEX_APPS_CODE` = 'CK') and (`GNTRLEX_ROLE_ID` = 'FF_FINANCE') and (`GNTRLEX_PERM_ID` = 'PM001');
UPDATE `clickargo`.`T_CORE_GRANT_ROLE_EX` SET `GNTRLEX_ROLE_ID` = 'OFFICER_FINANCE' WHERE (`GNTRLEX_APPS_CODE` = 'CK') and (`GNTRLEX_ROLE_ID` = 'FF_FINANCE') and (`GNTRLEX_PERM_ID` = 'PM025');

INSERT INTO `clickargo`.`T_CORE_USR_ROLE` (`UROL_UID`, `UROL_APPSCODE`, `UROL_ROLEID`, `UROL_ADMIN_OPT`, `UROL_STATUS`, `UROL_DT_CREATE`, `UROL_UID_CREATE`, `UROL_DT_LUPD`, `UROL_UID_LUPD`, `UROL_TEMP_ROLE`) VALUES ('ALKNAR_U001', 'CK', 'OFFICER_FINANCE', 'N', 'A', '2022-11-15 09:10:07', 'SYS', '2022-11-15 09:10:07', 'SYS', 'N');

-- 2023-04-20 NINA ACCN CONFIG FOR VA FOR CO MAY CHANGE DEPENDING ON WHAT IS SET FOR THIS ACCOUNT
INSERT INTO `clickargo`.`T_CORE_ACCN_CONFIG` (`ACFG_ACCNID`, `ACFG_KEY`, `ACFG_VAL`, `ACFG_DESC`, `ACFG_VALID_FROM_DT`, `ACFG_VALID_TO_DT`, `ACFG_SEQ`, `ACFG_STATUS`, `ACFG_DT_CREATE`, `ACFG_UID_CREATE`, `ACFG_DT_LUPD`, `ACFG_UID_LUPD`) VALUES ('ALKNAR', 'CO2SP_VA_IDR', '9100230215201356', 'FF Payment Account (IDR)', '2022-12-01 00:00:00', '2024-11-30 23:59:59', '1', 'A', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'SYS');

-- 
DELETE FROM `clickargo`.`T_CORE_SYSPARAM` WHERE (`SYS_KEY` = 'PAYMENT_GATEWAY_NODE');
INSERT INTO `clickargo`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('PAYMENT_GATEWAY_CONFIG', '{\"uid\": \"12345\", \"authPwd\": \"222\", \"url\": \"http://43.218.1.176/clicPay/api/v1/clicpay\"}', 'PAYMENT GATEWAY CONFIG', '2018-12-01 00:00:00', 'SYS', '2018-12-01 00:00:00', 'SYS', 'A');
DELETE FROM `clickargo`.`T_CORE_SYSPARAM` WHERE (`SYS_KEY` = 'PAYMENT_GATEWAY_PASSWORD');
DELETE FROM `clickargo`.`T_CORE_SYSPARAM` WHERE (`SYS_KEY` = 'PAYMENT_GATEWAY_USERID');
UPDATE `clickargo`.`T_CORE_SYSPARAM` SET `SYS_VAL` = ' {\"uid\": \"ADEAND_U001\", \"authPwd\": \"xxx\", \"url\": \"http://43.218.1.176/clicPay/api/v1/clicpay\"}' WHERE (`SYS_KEY` = 'PAYMENT_GATEWAY_CONFIG');

INSERT INTO `clickargo`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('MSC_GATEWAY_CONFIG', ' {\"uid\": \"edo@clickargo.com\", \"authPwd\": \"ccdo86\", \"url\": \"http://34.101.126.159:8082/api/v1/getmycargo\"}', 'MSC GATEWAY CONFIG', '2018-12-01 00:00:00', 'SYS', '2018-12-01 00:00:00', 'SYS', 'A');
DELETE FROM `clickargo`.`T_CORE_SYSPARAM` WHERE (`SYS_KEY` = 'IS_MSC_API_GATEWAY');
UPDATE `clickargo`.`T_CORE_SYSPARAM` SET `SYS_VAL` = '{\"uid\": \"edo@clickargo.com\", \"authPwd\": \"ccdo86\", \"url\": \"http://34.101.126.159:8082/api/v1/getmycargo\", \"contentType\": \"application/json\",\"isMock\": \"N\", \"mockUrl\": null, \"mockUid\": null, \"mockPwd\":null}' WHERE (`SYS_KEY` = 'MSC_GATEWAY_CONFIG');
UPDATE `clickargo`.`T_CORE_SYSPARAM` SET `SYS_VAL` = '{\"uid\": \"ADEAND_U001\", \"authPwd\": \"xxx\", \"url\": \"http://43.218.1.176/clicPay/api/v1/clicpay\",\"contentType\": \"application/json\",\"isMock\": \"N\", \"mockUrl\": null, \"mockUid\": null, \"mockPwd\":null}' WHERE (`SYS_KEY` = 'PAYMENT_GATEWAY_CONFIG');


 CREATE TABLE `T_CK_MSCGW_AUDIT` (
  `GWA_ID` varchar(35) NOT NULL COMMENT 'MSC GATEWAY AUDIT ID - UUID',
  `GWA_REF` varchar(1024) DEFAULT NULL COMMENT 'MSC GATEWAY REFERENCE - LOGIN SESSON ID',
  `GWA_URI` varchar(2048) DEFAULT NULL COMMENT 'URI INVOKED FOR THE RESTFUL CALL',
  `GWA_REQ` mediumtext COMMENT 'MSC GATEWAY REQUEST JSON',
  `GWA_RESP` mediumtext COMMENT 'MSC GATEWAY RESPONSE JSON',
  `GWA_ERROR` mediumtext COMMENT 'OPTIONAL ERROR STACK TRACE',
  `GWA_STATE` varchar(3) DEFAULT NULL,
  `GWA_STATUS` char(1) DEFAULT NULL COMMENT 'MSC GATEWAY AUDIT TYPE STATUS',
  `GWA_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `GWA_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `GWA_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `GWA_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`GWA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DO MSC GATEWAY AUDIT LOG';

DELETE FROM `clickargo`.`T_CORE_SYSPARAM` WHERE (`SYS_KEY` = 'MSC_API_GATEWAY_PASSWORD');
DELETE FROM `clickargo`.`T_CORE_SYSPARAM` WHERE (`SYS_KEY` = 'MSC_API_GATEWAY_USERID');

-- 2023-04-28 NINA - Increased payment audit state since this has no reference to any master table. Thus setting this based on the response of the api call.
ALTER TABLE `clickargo`.`T_CK_PAYMENT_AUDIT` 
CHANGE COLUMN `PYA_STATE` `PYA_STATE` VARCHAR(35) NULL DEFAULT NULL ;

ALTER TABLE `clickargo`.`T_CK_MSCGW_AUDIT` 
CHANGE COLUMN `GWA_STATE` `GWA_STATE` VARCHAR(35) NULL DEFAULT NULL ;

-- 2023-05-02 NINA - Added clicdo ext service type
INSERT INTO `clickargo`.`T_CK_MST_SERVICE_TYPE` (`SVCT_ID`, `SVCT_NAME`, `SVCT_DESC`, `SVCT_DESC_OTH`, `SVCT_STATUS`, `SVCT_DT_CREATE`, `SVCT_UID_CREATE`, `SVCT_DT_LUPD`, `SVCT_UID_LUPD`) VALUES ('CLICDOEXT', 'CLICDOEXT', 'CLICDOEXT', 'CLICDOEXT', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
