/** Claim Job Details Attachment Tab */
INSERT INTO `clickargo`.`T_MST_ATT_TYPE` (`MATT_ID`, `MATT_NAME`, `MATT_DESC`, `MATT_DESC_OTH`, `MATT_STATUS`, `MATT_DT_CREATE`, `MATT_UID_CREATE`, `MATT_DT_LUPD`, `MATT_UID_LUPD`, `MATT_EXPIRY`, `MATT_REF_NO`) VALUES ('CGA', 'CONTAINER GUARANTEE', 'CONTAINER GUARANTEE', NULL, 'A', '2018-12-01 00:00:00', 'SYS', '2018-12-01 00:00:00', 'SYS', 'N', 'N');

UPDATE `T_CORE_SYSPARAM` SET `SYS_VAL` = '{\"unAuthorized\":{\"attTypes\":\"SURAT_KUASA\",\"jrxmlPath\":\"docs/SuratKuasa_Period.jrxml\"},\"authorized\":{\"attTypes\":\"SURAT_KUASA\",\"jrxmlPath\":\"docs/SuratKuasa_Auth.jrxml\"}}' WHERE (`SYS_KEY` = 'CLICDO_CO_JOB_ATT_CONFIG');

/** Added Invoice Profoma Fee */
INSERT INTO `clickargo`.`T_CK_MST_INVOICE_TYPE` (`INVT_ID`, `INVT_NAME`, `INVT_DESC`, `INVT_DESC_OTH`, `INVT_STATUS`, `INVT_DT_CREATE`, `INVT_UID_CREATE`, `INVT_DT_LUPD`, `INVT_UID_LUPD`) VALUES ('I-IPF', 'INVOICE PROFORMA FEE', 'INVOICE PROFORMA FEE', 'INVOICE PROFORMA FEE', 'A', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'SYS');

/** Added US Dollars in MST CURRENCY */
INSERT INTO `clickargo`.`T_MST_CURRENCY` (`CCY_CODE`, `CCY_DESCRIPTION`, `CCY_DESCRIPTION_OTH`, `CCY_STATUS`, `CCY_DT_CREATE`, `CCY_UID_CREATE`, `CCY_DT_LUPD`, `CCY_UID_LUPD`) VALUES ('USD', 'US DOLLAR', NULL, 'A', '2021-08-12 09:01:23', 'SYS', '2021-08-12 09:01:23', 'SYS');

/** Added INDONESIAN RUPIAH in MST CURRENCY */
INSERT INTO `T_MST_CURRENCY` (CCY_CODE, CCY_DESCRIPTION, CCY_DESCRIPTION_OTH, CCY_STATUS, CCY_DT_CREATE, CCY_UID_CREATE, CCY_DT_LUPD, CCY_UID_LUPD)VALUES('IDR', 'INDONESIAN RUPIAH', NULL, 'A', '2022-12-12 00:00:00', 'SYS', '2022-12-12 00:00:00', 'SYS');

/** Added I-DCF to replace the current existing I-DC*/
INSERT INTO `clickargo`.`T_CK_MST_INVOICE_TYPE` (`INVT_ID`, `INVT_NAME`, `INVT_DESC`, `INVT_DESC_OTH`, `INVT_STATUS`, `INVT_DT_CREATE`, `INVT_UID_CREATE`, `INVT_DT_LUPD`, `INVT_UID_LUPD`) VALUES ('I-DCF', 'INVOICE DIGITAL CERTIFICATE', 'INVOICE PLATFORM FEE', 'INVOICE PLATFORM FEE', 'A', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'SYS');

/** Added CLICDO_FF_JOB_ATT_CONFIG */
-- INSERT INTO `clickargo`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICDO_FF_JOB_ATT_CONFIG', '{\"unAuthorized\":[{\"attTypes\":\"SURAT_KUASA\",\"authorized\":false,\"jrxmlPath\":\"test\"}],\"authorized\":[{\"attTypes\":\"SURAT_KUASA\",\"authorized\":false,\"jrxmlPath\":\"test\"}]}', 'Location for Surat Kuasa jasper file', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

/** Updated spelling of INVOICE PROFORMA */
UPDATE `clickargo`.`T_CK_MST_INVOICE_TYPE` SET  `INVT_NAME`='INVOICE PROFORMA FEE', `INVT_DESC` = 'INVOICE PROFORMA FEE', `INVT_DESC_OTH` = 'INVOICE PROFORMA FEE' WHERE `INVT_ID` = 'I-IPF';



/** 2022-12-05 Nina updated T_CK_DOI_CNT*/
ALTER TABLE `clickargo`.`T_CK_DOI_CNT` 
DROP FOREIGN KEY `FK_CK_DOI_CNT_CK_DO`;
ALTER TABLE `clickargo`.`T_CK_DOI_CNT` 
ADD INDEX `FK_CK_DOI_CNT_CK_DO_idx` (`DOIC_DOI_ID` ASC) VISIBLE,
DROP PRIMARY KEY;
;
ALTER TABLE `clickargo`.`T_CK_DOI_CNT` 
ADD CONSTRAINT `FK_CK_DOI_CNT_CK_DO`
  FOREIGN KEY (`DOIC_DOI_ID`)
  REFERENCES `clickargo`.`T_CK_DO` (`DO_ID`);


ALTER TABLE `clickargo`.`T_CK_DOI_CNT` 
RENAME TO  `clickargo`.`T_CK_DO_CNT` ;

ALTER TABLE `clickargo`.`T_CK_DO_CNT` 
DROP FOREIGN KEY `FK_CK_DOI_CNT_CK_DO`;
ALTER TABLE `clickargo`.`T_CK_DO_CNT` 
CHANGE COLUMN `DOIC_DOI_ID` `DOIC_DO_ID` VARCHAR(35) NOT NULL COMMENT 'DO ID - REFERENCE T_CK_DO:DO_ID' ;
ALTER TABLE `clickargo`.`T_CK_DO_CNT` 
ADD CONSTRAINT `FK_CK_DOI_CNT_CK_DO`
  FOREIGN KEY (`DOIC_DO_ID`)
  REFERENCES `clickargo`.`T_CK_DO` (`DO_ID`);

INSERT INTO `clickargo`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICDO_JRXML_CONTAINER_GUARANTEE', 'docs/ContainerLoan.jrxml', 'Location of Container Guarantee', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

DELETE FROM `clickargo`.`T_CORE_SYSPARAM` WHERE (`SYS_KEY` = 'CLICDO_CO_JOB_ATT_CONFIG');
DELETE FROM `clickargo`.`T_CORE_SYSPARAM` WHERE (`SYS_KEY` = 'CLICDO_JRXML_SURATKUASA');

INSERT INTO `clickargo`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICDO_JRXML_POA_AUTH', 'docs/POA_Auth.jrxml', 'Locatin for Power of Authority (Authorized)', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');
INSERT INTO `clickargo`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICDO_JRXML_POA_UAUTH', 'docs/POA_UAuth.jrxml', 'Locatin for Power of Authority (Un-Authorized)', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

INSERT INTO `T_CK_FORM_CONTROL` (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD)VALUES('30', 'ACC_TYPE_SL', NULL, 'FINANCE', 'JOB_DOI_FF', 'SUB', 'VIEW', 'VERIFY', NULL, 'A', '2022-11-26 16:41:35', 'SYS', '2022-11-26 16:41:35', 'SYS');

/**2022-12-19 PAYMENT TRANSACTION ATTACHMENT TABLE */
CREATE TABLE `T_CK_PAYMENT_TXN_ATT_INVOICE` (
  `PTX_ATT_INV_ID` varchar(35) NOT NULL COMMENT 'JOB ATTACHMENT ID - UUID',
  `PTX_ATT_INV_JOB` varchar(35) NOT NULL COMMENT 'JOB - REFERENCE T_CK_JOB:JOB_ID FF',
  `PTX_ATT_INV_TYPE` varchar(35) NOT NULL COMMENT 'JOB ATTACHMENT TYPE - REFERENCE T_CK_MST_INVOICE_TYPE:INVT_ID',
  `PTX_ATT_INV_NAME` varchar(256) DEFAULT NULL COMMENT 'JOB ATTACHMENT NAME',
  `PTX_ATT_INV_LOC` varchar(1024) DEFAULT NULL COMMENT 'JOB ATTACHMENT PATH REFERENCE FROM SYS_PARAM SETUP',
  `PTX_ATT_INV_STATUS` char(1) DEFAULT NULL COMMENT 'JOB ATTACHMENT STATUS - A : I ',
  `PTX_ATT_INV_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `PTX_ATT_INV_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `PTX_ATT_INV_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `PTX_ATT_INV_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`PTX_ATT_INV_ID`),
  KEY `FK_CK_PAYMENT_TXN_T_CK_MST_INVOICE_TYPE` (`PTX_ATT_INV_TYPE`),
  KEY `FK_CK_JPAYMENT_TXN_ATT_INVOICE` (`PTX_ATT_INV_JOB`),
  CONSTRAINT `FK_CK_JPAYMENT_TXN_ATT_INVOICE` FOREIGN KEY (`PTX_ATT_INV_JOB`) REFERENCES `T_CK_JOB` (`JOB_ID`),
  CONSTRAINT `FK_CK_PAYMENT_TXN_T_CK_MST_INVOICE_TYPE` FOREIGN KEY (`PTX_ATT_INV_TYPE`) REFERENCES `T_CK_MST_INVOICE_TYPE` (`INVT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='PAYMENT TRANSACTION INVOICE ATTACHMENT TABLE';

INSERT INTO `clickargo`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICDO_JRXML_PROFORMA_FEE_INV', 'docs/ProformaFee.jrxml', 'Proforma Invoice', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');
INSERT INTO `clickargo`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICDO_JRXML_PLATFORM_FEE_INV', 'docs/PlatformFee.jrxml', 'Platform Fee Invoice', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');
INSERT INTO `clickargo`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`,`SYS_STATUS`) VALUES ('CLICDO_PLATFORM_FEE', '{\"currency\": \"IDR\", \"fee\": 2000}', 'Platform fee configuration', '2018-12-01 00:00:00', 'SYS', '2018-12-01 00:00:00', 'SYS','A');

INSERT INTO `T_MST_PORT` (PORT_CODE, PORT_STATUS, PORT_COUNTRY, PORT_TYPE, PORT_DESCRIPTION, PORT_DESCRIPTION_OTH, PORT_DT_CREATE, PORT_UID_CREATE, PORT_DT_LUPD, PORT_UID_LUPD)VALUES('IDJKT', 'A', 'ID', 'PORTT_SEA', 'JAKARTA', NULL, '202-12-20 00:00:00', 'SYS', '202-12-20 00:00:00', 'SYS');
INSERT INTO `T_MST_PORT` (PORT_CODE, PORT_STATUS, PORT_COUNTRY, PORT_TYPE, PORT_DESCRIPTION, PORT_DESCRIPTION_OTH, PORT_DT_CREATE, PORT_UID_CREATE, PORT_DT_LUPD, PORT_UID_LUPD)VALUES('IDSUB', 'A', 'ID', 'PORTT_SEA', 'SURABAYA', NULL, '2019-12-20 00:00:00', 'SYS', '202-12-20 00:00:00', 'SYS');

INSERT INTO `T_CK_MST_INVOICE_TYPE` (INVT_ID, INVT_NAME, INVT_DESC, INVT_DESC_OTH, INVT_STATUS, INVT_DT_CREATE, INVT_UID_CREATE, INVT_DT_LUPD, INVT_UID_LUPD)VALUES('I-IXX', 'INVOICE NAME TO BE CONFIRMED', 'INVOICE NAME TO BE CONFIRMED', 'INVOICE NAME TO BE CONFIRMED', 'A', '2022-12-20 00:00:00', 'SYS', '2022-12-20 00:00:00', 'SYS');

/** 2022-12-21 CK - added attachment type for proforma invoice*/
INSERT INTO `T_MST_ATT_TYPE` VALUES ('PFI','PROFORMA INVOICE','PROFORMA INVOICE',NULL,'A','2018-12-01 00:00:00','SYS','2018-12-01 00:00:00','SYS','N','N');
INSERT INTO `T_MST_ATT_TYPE` VALUES ('ETI','E TAX INVOICE','E TAX INVOICE',NULL,'A','2018-12-01 00:00:00','SYS','2018-12-01 00:00:00','SYS','N','N');

/** 2022-12-21 CK - added state column to record response status e.g. 200, 400, or 500*/
ALTER TABLE `T_CK_PAYMENT_AUDIT` ADD COLUMN PYA_STATE VARCHAR(3) NULL AFTER `PYA_REMARK`;

/** Add component guide for sl query */
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD) VALUES ('41', 'CK', 'CLICDO', 'clicdo.doi.sl.claim.jobs.tabs.query', 'Create a query to inform the responder on the changes or correct documents required on what has been claimed.', NULL, 'A', '2022-11-16 09:13:41', 'SYS', '2022-11-16 09:13:41', 'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD) VALUES ('42', 'CK', 'CLICDO', 'clicdo.doi.sl.claim.jobs.tabs.query.table', 'Click on the EYE icon to view the query made by the Shipping Line and the response to the query. Click on the TRASH BIN to delete the query.', NULL, 'A', '2022-11-16 09:13:41', 'SYS', '2022-11-16 09:13:41', 'SYS');

/** 2022-12-21 CK */
insert into T_MST_ACCN_TYPE (ATYP_ID, ATYP_DESCRIPTION, ATYP_DESCRIPTION_OTH, ATYP_STATUS, ATYP_DT_CREATE, ATYP_UID_CREATE, ATYP_DT_LUPD, ATYP_UID_LUPD)
values ('ACC_TYPE_SP','SERVICE PROVIDER',NULL,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS');

/**2022-12-21 NINA - GLI account */
INSERT INTO `T_CORE_ACCN` (`ACCN_ID`, `ACCN_STATUS`, `ACCN_NAME`, `ACCN_NAME_OTH`, `ACCN_TYPE`, `ACCN_COY_REGN`, `ACCN_NATIONALITY`, `ACCN_ADDR1`, `ACCN_ADDR2`, `ACCN_ADDR3`, `ACCN_PCODE`, `ACCN_CITY`, `ACCN_PROV`, `ACCN_CTYCODE`, `ACCN_TEL`, `ACCN_FAX`, `ACCN_EMAIL`, `ACCN_LOCALE_CD`, `ACCN_DT_REG`, `ACCN_DT_CREATE`, `ACCN_UID_CREATE`, `ACCN_DT_LUPD`, `ACCN_UID_LUPD`, `ACCN_CITY_CODE`) VALUES ('GLI', 'A', 'Guud Logistics Indonesia', 'Guud Logistics Indonesia', 'ACC_TYPE_SP', '21', 'Indonesia', 'The Prime Office Suites Lantai 7', 'Jl Yos Sudarso Kav 30, Sunter Jaya, Jakarta Utara', 'Kota Administrasi Jakarta Utara , DKI Jakarta', '10220', 'Jakarta', 'Jakarta', 'ID', '62215723251', '62215723251', 'support@yamatoindforward.id', '1', '2022-10-01 00:00:00', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'SYS', '21');
INSERT INTO `T_CORE_ACCN_CONFIG` (`ACFG_ACCNID`, `ACFG_KEY`, `ACFG_VAL`, `ACFG_DESC`, `ACFG_VALID_FROM_DT`, `ACFG_VALID_TO_DT`, `ACFG_SEQ`, `ACFG_STATUS`, `ACFG_DT_CREATE`, `ACFG_UID_CREATE`, `ACFG_DT_LUPD`, `ACFG_UID_LUPD`) VALUES ('GLI', 'DO_CLAIM_IDR', '123456', 'STATIC VIRTUAL ACCOUNT FOR IDR CURRENCY', '2022-12-21 10:54:21', '2022-12-21 10:54:21', '1', 'A', '2022-12-21 10:54:21', 'SYS', '2022-12-21 10:54:21', 'SYS');
INSERT INTO `T_CORE_ACCN_CONFIG` (`ACFG_ACCNID`, `ACFG_KEY`, `ACFG_VAL`, `ACFG_DESC`, `ACFG_VALID_FROM_DT`, `ACFG_SEQ`, `ACFG_STATUS`, `ACFG_DT_CREATE`, `ACFG_UID_CREATE`, `ACFG_DT_LUPD`, `ACFG_UID_LUPD`) VALUES ('GLI', 'DO_CLAIM_USD', '654321', 'STATIC VIRTUAL ACCOUNT FOR USD', '2022-12-21 10:54:21', '2', 'A', '2022-12-21 10:54:21', 'SYS', '2022-12-21 10:54:21', 'SYS');

/** 2022-12-22 CK */
INSERT INTO `T_CORE_ACCN_CONFIG` (`ACFG_ACCNID`,`ACFG_KEY`,`ACFG_VAL`,`ACFG_DESC`,`ACFG_VALID_FROM_DT`,`ACFG_VALID_TO_DT`,`ACFG_SEQ`,`ACFG_STATUS`,`ACFG_DT_CREATE`,`ACFG_UID_CREATE`,`ACFG_DT_LUPD`,`ACFG_UID_LUPD`) VALUES
('COMLG','FF2SP_VA_IDR','10.126.4476512','FF Payment Account (IDR)','2022-12-01 00:00:00','2024-11-30 23:59:59',1,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('COMLG','FF2SP_VA_USD','10.126.4472255','FF Payment Account (USD)','2022-12-01 00:00:00','2024-11-30 23:59:59',2,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('DUNLS','FF2SP_VA_IDR','34.555.4256565','FF Payment Account (IDR)','2022-12-01 00:00:00','2024-11-30 23:59:59',1,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('DUNLS','FF2SP_VA_USD','09.888.8096756','FF Payment Account (USD)','2022-12-01 00:00:00','2024-11-30 23:59:59',2,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('FREXID','FF2SP_VA_IDR','54.111.4287094','FF Payment Account (IDR)','2022-12-01 00:00:00','2024-11-30 23:59:59',1,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('FREXID','FF2SP_VA_USD','78.780.0683495','FF Payment Account (USD)','2022-12-01 00:00:00','2024-11-30 23:59:59',2,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('GNOCIN','FF2SP_VA_IDR','77.058.3537678','FF Payment Account (IDR)','2022-12-01 00:00:00','2024-11-30 23:59:59',1,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('GNOCIN','FF2SP_VA_USD','50.482.5903807','FF Payment Account (USD)','2022-12-01 00:00:00','2024-11-30 23:59:59',2,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('YINDF','FF2SP_VA_IDR','13.663.8905486','FF Payment Account (IDR)','2022-12-01 00:00:00','2024-11-30 23:59:59',1,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('YINDF','FF2SP_VA_USD','57.232.1120589','FF Payment Account (USD)','2022-12-01 00:00:00','2024-11-30 23:59:59',2,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('ALKNAR','CO2SL_VA_IDR','8.15.225561','SL Payee Account (IDR)','2022-12-01 00:00:00','2024-11-30 23:59:59',1,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('ALKNAR','CO2SL_VA_USD','7.68.687822','SL Payee Account (USD)','2022-12-01 00:00:00','2024-11-30 23:59:59',2,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('ALMGA','CO2SL_VA_IDR','8.74.687886','SL Payee Account (IDR)','2022-12-01 00:00:00','2024-11-30 23:59:59',1,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('ALMGA','CO2SL_VA_USD','4.33.878855','SL Payee Account (USD)','2022-12-01 00:00:00','2024-11-30 23:59:59',2,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('ASPIND','CO2SL_VA_IDR','1.35.67633','SL Payee Account (IDR)','2022-12-01 00:00:00','2024-11-30 23:59:59',1,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('ASPIND','CO2SL_VA_USD','3.66.790877','SL Payee Account (USD)','2022-12-01 00:00:00','2024-11-30 23:59:59',2,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('SUMTID','CO2SL_VA_IDR','6.33.678639','SL Payee Account (IDR)','2022-12-01 00:00:00','2024-11-30 23:59:59',1,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('SUMTID','CO2SL_VA_USD','4.15.525345','SL Payee Account (USD)','2022-12-01 00:00:00','2024-11-30 23:59:59',2,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('TTIDR','CO2SL_VA_IDR','8.88.686868','SL Payee Account (IDR)','2022-12-01 00:00:00','2024-11-30 23:59:59',1,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('TTIDR','CO2SL_VA_USD','4.54.345884','SL Payee Account (USD)','2022-12-01 00:00:00','2024-11-30 23:59:59',2,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('GLI','DO_SP_BNK','9.65.574257','ClicDO Service Provider (GLI) Merchant Bank ','2022-12-01 00:00:00','2024-11-30 23:59:59',1,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS'),
('GLI','DO_SP_BNK_ACCN ','8.12.907824','ClicDO Service Provider (GLI) Merchant Bank Accn','2022-12-01 00:00:00','2024-11-30 23:59:59',1,'A','2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS');

INSERT INTO `T_CK_COMPONENT_GUIDE` (CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)VALUES('43', 'CK', 'CLICDO', 'clicdo.doi.sl.pay.verify.list', '*Once submitted task has been submitted, the DOs listed within the tasks cannot be updated or removed. The shipping line will proceed to review the letter of authorisation documents, the DO charges will only be shown when the documents have been verified. The DO document and Invoice will only be made available for download once payment has been made and verified by the shipping line.', NULL, 'A', '2022-12-22 11:00:00', 'SYS', '2022-12-22 11:00:00', 'SYS');
INSERT INTO `T_CK_COMPONENT_GUIDE` (CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)VALUES('44', 'CK', 'CLICDO', 'clicdo.doi.sl.doc.verify.list', '*Once submitted task has been submitted, the DOs listed within the tasks cannot be updated or removed. The shipping line will proceed to review the letter of authorisation documents, the DO charges will only be shown when the documents have been verified. The DO document and Invoice will only be made available for download once payment has been made and verified by the shipping line.', NULL, 'A', '2022-12-22 11:00:00', 'SYS', '2022-12-22 11:00:00', 'SYS');

/** 2022-12-22 CK - executed by ck in dev server */
ALTER TABLE `T_CK_PAYMENT_AUDIT` DROP FOREIGN KEY `FK_CK_DO_PAYMENT_AUDIT_CK_PAYMENT_LEDGER`;

/** 2022-12-22 CK - executed by ck in dev server  */
drop index FK_CK_DO_PAYMENT_AUDIT_CK_PAYMENT_LEDGER on T_CK_PAYMENT_AUDIT;

/** 2022-12-22 CK - executed by ck in dev server  */
alter table T_CK_PAYMENT_AUDIT drop column PYA_LEDGER;

/** 2022-12-23 CK - executed by ck in dev server  */
INSERT INTO `T_CK_COMPONENT_GUIDE` (CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)VALUES
('45', 'CK', 'CLICDO', 'clicdo.job-payment.job-listing.table', 'Once payment is made and verified, job status will be updated to "PAYMENT VERIFIED", and  it will be updated to PAID when the actual payment is received.', NULL, 'A', NOW(), 'SYS', NOW(), 'SYS');

/**2022-12-23 REMOVED BUTTON FOR PAY SINCE THERE WILL BE NEW PAYMENT SCREEN TO PAY SELECTED FF JOBS*/
DELETE FROM `T_CK_FORM_CONTROL` WHERE (`CTRL_ID` = '100');
DELETE FROM `T_CK_FORM_CONTROL` WHERE (`CTRL_ID` = '17');

/** new finance officer for freight forwarder*/
INSERT INTO `T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`, `ROLE_STATUS`, `ROLE_DESC`, `ROLE_DT_CREATE`, `ROLE_UID_CREATE`, `ROLE_DT_LUPD`, `ROLE_UID_LUPD`) VALUES ('CK', 'FF_FINANCE', 'A', 'FF FINANCE', '2022-11-15 09:09:14', 'SYS', '2022-11-15 09:09:14', 'SYS');
INSERT INTO `T_CORE_USR_ROLE` (`UROL_UID`, `UROL_APPSCODE`, `UROL_ROLEID`, `UROL_ADMIN_OPT`, `UROL_STATUS`, `UROL_DT_CREATE`, `UROL_UID_CREATE`, `UROL_DT_LUPD`, `UROL_UID_LUPD`, `UROL_TEMP_ROLE`) VALUES ('COMLG_U001', 'CK', 'FF_FINANCE', 'N', 'A', '2022-11-15 09:10:07', 'SYS', '2022-11-15 09:10:07', 'SYS', 'N');

-- REMOVED PAYMENT ACCESS FOR SL FINANCE AND OPERATIONS
UPDATE `clickargo`.`T_CORE_GRANT_ROLE_EX` SET `GNTRLEX_ROLE_ID` = 'FF_FINANCE' WHERE (`GNTRLEX_APPS_CODE` = 'CK') and (`GNTRLEX_ROLE_ID` = 'OFFICER') and (`GNTRLEX_PERM_ID` = 'PM001');
-- DELETE FROM `clickargo`.`T_CORE_GRANT_ROLE_EX` WHERE (`GNTRLEX_APPS_CODE` = 'CK') and (`GNTRLEX_ROLE_ID` = 'FINANCE') and (`GNTRLEX_PERM_ID` = 'PM001');
DELETE FROM `clickargo`.`T_CORE_GRANT_ROLE_EX` WHERE (`GNTRLEX_APPS_CODE` = 'CK') and (`GNTRLEX_ROLE_ID` = 'OPERATIONS') and (`GNTRLEX_PERM_ID` = 'PM001');

/** Added component guide for CONFIRMED FF */
INSERT INTO `clickargo`.`T_CK_COMPONENT_GUIDE` (`CMGU_ID`, `CMGU_APPS_CODE`, `CMGU_SERVICE_TYPE`, `CMGU_COMPONENT_ID`, `CMGU_GUIDE`, `CMGU_GUIDE_OTH`, `CMGU_STATUS`, `CMGU_DT_CREATE`, `CMGU_UID_CREATE`, `CMGU_DT_LUPD`, `CMGU_UID_LUPD`) VALUES ('50', 'CK', 'CLICDO', 'clicdo.doi.ff.claim.jobs.tabs.details.confirmed', 'Once payment is made, DO claim tasks can be started to claim the DO under the BLs.', NULL, 'A', '2022-11-16 09:13:41', 'SYS', '2022-11-16 09:13:41', 'SYS');
INSERT INTO `clickargo`.`T_CK_COMPONENT_GUIDE` (`CMGU_ID`, `CMGU_APPS_CODE`, `CMGU_SERVICE_TYPE`, `CMGU_COMPONENT_ID`, `CMGU_GUIDE`, `CMGU_GUIDE_OTH`, `CMGU_STATUS`, `CMGU_DT_CREATE`, `CMGU_UID_CREATE`, `CMGU_DT_LUPD`, `CMGU_UID_LUPD`) VALUES ('51', 'CK', 'CLICDO', 'clicdo.doi.ff.claim.jobs.tabs.detaills.table.confirmed', 'Click on the Eye icon to view the BL document.', NULL, 'A', '2022-11-16 09:13:41', 'SYS', '2022-11-16 09:13:41', 'SYS');

/** 2022-12-27 CK - executed by ck in dev server  */
INSERT INTO `clickargo`.`T_CK_MST_JOB_STATE`
(`JBST_ID`,`JBST_NAME`, `JBST_DESC`,`JBST_DESC_OTH`,`JBST_STATUS`,`JBST_DT_CREATE`,`JBST_UID_CREATE`,`JBST_DT_LUPD`,`JBST_UID_LUPD`) VALUES ('PYG', 'PAYING', 'PAYING', 'PAYING', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

/** 2022-12-28 CK - executed by ck in dev server  */
INSERT INTO `clickargo`.`T_CORE_SYSPARAM`
(`SYS_KEY`,`SYS_VAL`,`SYS_DESC`,`SYS_DT_CREATE`,`SYS_UID_CREATE`,`SYS_DT_LUPD`,`SYS_UID_LUPD`,`SYS_STATUS`) VALUES ('PAYMENT_GATEWAY_URL', 'http://localhost:80/clicdo/api/v1/clickargo/clicdo/payment/callback', 'Payment Gateway Url', '2022-11-30 00:00:00', 'SYS', '2022-11-30 00:00:00', 'SYS', 'A');

/** 2022-12-28 Nina*/
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICDO_PLATFORM_SERVICE_PROVIDER', 'GLI:XXXXXX-XXXX', 'SERVICE PROVIDER AND FAKTUR SEPARATED BY COLON', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

/** 2023-01-04 New columns for ffjob and co job*/
ALTER TABLE `T_CK_JOB_DOI_FF` 
ADD COLUMN `JOB_DOC_VERIFIED_STATE` VARCHAR(35) NULL COMMENT 'VERIFIED, PENDING_RETURN' AFTER `JOB_UID_LUPD`,
ADD COLUMN `JOB_PAYMENT_VERIFIED_STATE` VARCHAR(35) NULL COMMENT 'PAYMENT_VERIFIED' AFTER `JOB_DOC_VERIFIED_STATE`;

ALTER TABLE `T_CK_JOB_DOI_FF` 
CHANGE COLUMN `JOB_PAYMENT_VERIFIED_STATE` `JOB_PAYMENT_VERIFIED_STATE` VARCHAR(35) NULL DEFAULT NULL COMMENT 'PAYMENT_VERIFIED' AFTER `JOB_DT_PAID`,
CHANGE COLUMN `JOB_DOC_VERIFIED_STATE` `JOB_DOC_VERIFIED_STATE` VARCHAR(35) NULL DEFAULT NULL COMMENT 'VERIFIED, PENDING_RETURN' AFTER `JOB_DT_PAYMENT_VERIFIED`;


ALTER TABLE `T_CK_JOB_DOI_CO` 
ADD COLUMN `JOB_PAYMENT_VERIFIED_STATE` VARCHAR(35) NULL AFTER `JOB_STATUS`,
ADD COLUMN `JOB_DT_PAYMENT_VERIFIED` DATETIME NULL AFTER `JOB_PAYMENT_VERIFIED_STATE`,
ADD COLUMN `JOB_DOC_VERIFIED_STATE` VARCHAR(35) NULL AFTER `JOB_DT_PAYMENT_VERIFIED`,
ADD COLUMN `JOB_DT_DOC_VERIFIED` DATETIME NULL AFTER `JOB_DOC_VERIFIED_STATE`;

ALTER TABLE `clickargo`.`T_CK_JOB_ATTACH` 
ADD COLUMN `ATT_RETURN_FLAG` CHAR(1) NULL DEFAULT 'N' COMMENT 'RETURN REQUIRED FLAG' AFTER `ATT_STATUS`,
ADD COLUMN `ATT_DT_RETURNED` DATETIME NULL DEFAULT NULL COMMENT 'DATE WHEN ORIGINAL COPY IS RETURNED AND VERIFIED' AFTER `ATT_RETURN_FLAG`;

ALTER TABLE `clickargo`.`T_CK_JOB_ATTACH` 
CHANGE COLUMN `ATT_RETURN_FLAG` `ATT_RETURN_FLAG` CHAR(1) NULL DEFAULT NULL COMMENT 'RETURN REQUIRED FLAG' AFTER `ATT_STATUS`;

/** ClicDO 128 */
INSERT INTO `clickargo`.`T_CORE_MENU_EX` (`MENU_ID`, `MENU_APPS_CODE`, `MENU_GROUP_LABEL`, `MENU_GROUP_LABEL_OTH`, `MENU_NAME`, `MENU_NAME_OTH`, `MENU_SEQ`, `MENU_PATH`, `MENU_ICON`, `MENU_PARENT`, `MENU_STATUS`, `MENU_DT_CREATE`, `MENU_UID_CREATE`, `MENU_DT_LUPD`, `MENU_UID_LUPD`) VALUES ('CK_MS_020000', 'CK', 'Documents', 'Documents', 'Documents', 'Documents', '20000', '/', NULL, NULL, 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');
INSERT INTO `clickargo`.`T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`, `PERM_MENU_NAME`, `PERM_DOC_TYPE`, `PERM_DOC_CODE`, `PERM_ACTION`, `PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`, `PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM024', 'Y', 'CK', NULL, 'M', NULL, NULL, 'CK_MS_020000', 'Documents', NULL, NULL, NULL, 'Documents', 'Documents', 'R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
DELETE FROM `clickargo`.`T_CORE_GRANT_ROLE_EX` WHERE `GNTRLEX_ROLE_ID` = 'OPERATIONS' AND GNTRLEX_PERM_ID = 'PM000';
INSERT INTO `clickargo`.`T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`, `GNTRLEX_DT_LUPD`, `GNTRLEX_UID_LUPD`) VALUES ('CK', 'OPERATIONS', 'PM024', 'A', '2022-12-02 06:47:11', 'SYS', NULL, NULL);



/** 2023-01-05 Updated menu with icons */
UPDATE `T_CORE_MENU_EX` SET `MENU_ICON` = 'help_outline' WHERE (`MENU_ID` = 'CK_MH_040000');
UPDATE `T_CORE_MENU_EX` SET `MENU_ICON` = 'payment' WHERE (`MENU_ID` = 'CK_MP_020000');
UPDATE `T_CORE_MENU_EX` SET `MENU_ICON` = 'grid_view' WHERE (`MENU_ID` = 'CK_MS_010000');


/** 2023-01-05 CK - executed by ck in dev server  */
INSERT INTO `clickargo`.`T_CORE_SYSPARAM`
(`SYS_KEY`,`SYS_VAL`,`SYS_DESC`,`SYS_DT_CREATE`,`SYS_UID_CREATE`,`SYS_DT_LUPD`,`SYS_UID_LUPD`,`SYS_STATUS`) VALUES ('APP_ID', 'clicdo', 'Clicdo app id', '2022-11-30 00:00:00', 'SYS', '2022-11-30 00:00:00', 'SYS', 'A');

/** 2023-01-05 CK - executed by ck in dev server  */
INSERT INTO `clickargo`.`T_CORE_SYSPARAM`
(`SYS_KEY`,`SYS_VAL`,`SYS_DESC`,`SYS_DT_CREATE`,`SYS_UID_CREATE`,`SYS_DT_LUPD`,`SYS_UID_LUPD`,`SYS_STATUS`) VALUES ('APP_REF_NUM', 'clicdo-ref-number', 'Clicdo app ref number', '2022-11-30 00:00:00', 'SYS', '2022-11-30 00:00:00', 'SYS', 'A');

/** 2023-01-05 CK - executed by ck in dev server  */
INSERT INTO `clickargo`.`T_CORE_SYSPARAM`
(`SYS_KEY`,`SYS_VAL`,`SYS_DESC`,`SYS_DT_CREATE`,`SYS_UID_CREATE`,`SYS_DT_LUPD`,`SYS_UID_LUPD`,`SYS_STATUS`) VALUES ('INFLOW_PAYMENT_CALLBACK_URL', 'http://clicdo.vcargocloud.com/be/clicdo/api/v1/{paymentProvider}/payment', 'Payment Gateway Url', '2022-11-30 00:00:00', 'SYS', '2022-11-30 00:00:00', 'SYS', 'A');

/** 2023-01-05 CK - executed by ck in dev server  */
INSERT INTO `clickargo`.`T_CORE_SYSPARAM`
(`SYS_KEY`,`SYS_VAL`,`SYS_DESC`,`SYS_DT_CREATE`,`SYS_UID_CREATE`,`SYS_DT_LUPD`,`SYS_UID_LUPD`,`SYS_STATUS`) VALUES ('OUTFLOW_PAYMENT_CALLBACK_URL', 'http://clicdo.vcargocloud.com/be/clicdo/api/v1/{paymentProvider}/payment', 'Payment Gateway Url', '2022-11-30 00:00:00', 'SYS', '2022-11-30 00:00:00', 'SYS', 'A');

/** 2023-01-05 CK - executed by ck in dev server  */
UPDATE `T_CORE_ACCN_CONFIG` SET ACFG_VAL = 'DANAMON' WHERE `ACFG_ACCNID` = 'GLI' AND `ACFG_KEY` = 'DO_SP_BNK';

/** 2023-01-05 CK - executed by ck in dev server  */
DELETE FROM  `clickargo`.`T_CORE_SYSPARAM` WHERE `SYS_KEY` = 'PAYMENT_GATEWAY_URL';

/** CLICDO-129 [ClicDO-MSC-Paymnets verify] UI update For Payments tab **/
DELETE FROM `clickargo`.`T_CORE_GRANT_ROLE_EX` WHERE `GNTRLEX_ROLE_ID` = 'FINANCE' AND GNTRLEX_PERM_ID = 'PM000';
INSERT INTO `clickargo`.`T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`, `GNTRLEX_DT_LUPD`, `GNTRLEX_UID_LUPD`) VALUES ('CK', 'FINANCE', 'PM001', 'A', '2023-01-05 05:40:11', 'SYS', NULL, NULL);

/** Executed in DEV */
UPDATE `T_CORE_MENU_EX` SET `MENU_ICON` = 'content_copy' WHERE (`MENU_ID` = 'CK_MS_020000');

/** Icon for returned documents verification */
INSERT INTO `clickargo`.`T_CK_MST_FORM_ACTION` (`FMACT_ID`, `FMACT_NAME`, `FMACT_DESC`, `FMACT_DESC_OTH`, `FMACT_STATUS`, `FMACT_DT_CREATE`, `FMACT_UID_CREATE`, `FMACT_DT_LUPD`, `FMACT_UID_LUPD`) VALUES ('REVERIFY', 'Form Reverify', 'Form Reverify', 'Form Reverify', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');
INSERT INTO `clickargo`.`T_CK_FORM_CONTROL` (`CTRL_ID`, `CTRL_ACCN_TYPE`, `CTRL_ACCN`, `CTRL_USR_ROLE`, `CTRL_ENTITY_TYPE`, `CTRL_ENTITY_STATE`, `CTRL_FORM_TYPE`, `CTRL_FORM_ACTION`, `CTRL_FORM_ACTION_MENU`, `CTRL_STATUS`, `CTRL_DT_CREATE`, `CTRL_UID_CREATE`, `CTRL_DT_LUPD`, `CTRL_UID_LUPD`) VALUES ('31', 'ACC_TYPE_SL', NULL, 'OPERATIONS', 'JOB_DOI_FF', 'SUB', 'VIEW', 'REVERIFY', NULL, 'A', '2022-11-26 16:41:35', 'SYS', '2022-11-26 16:41:35', 'SYS');

/** Update for document returned verification */
ALTER TABLE `clickargo`.`T_CK_JOB_ATTACH` 
ADD COLUMN `ATT_BL_NO` VARCHAR(255) NULL DEFAULT NULL AFTER `ATT_DT_RETURNED`;

/** 2023-01-11 Added transactions menu for freight forwarder */
INSERT INTO `T_CORE_MENU_EX` (`MENU_ID`, `MENU_APPS_CODE`, `MENU_GROUP_LABEL`, `MENU_GROUP_LABEL_OTH`, `MENU_NAME`, `MENU_NAME_OTH`, `MENU_SEQ`, `MENU_PATH`, `MENU_ICON`, `MENU_PARENT`, `MENU_STATUS`, `MENU_DT_CREATE`, `MENU_UID_CREATE`, `MENU_DT_LUPD`, `MENU_UID_LUPD`) VALUES ('CK_MP_070000', 'CK', 'Transactions', 'Transactions', 'Transactions', 'Transactions', '70000', '/payments', 'payment', null, 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_TYPE`, `PERM_MENU`, `PERM_MENU_NAME`, `PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`, `PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM025', 'Y', 'CK', 'M', 'CK_MP_070000', 'Transactions', 'Transactions', 'Payments', 'R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'FF_FINANCE', 'PM025', 'A', '2022-11-15 09:08:16', 'SYS');
UPDATE `T_CORE_MENU_EX` SET `MENU_PATH` = '/applications/payments/viewPaymentHistory' WHERE (`MENU_ID` = 'CK_MP_070000');

/** Nina: Moved Help to the last part */
INSERT INTO `T_CORE_MENU_EX` (`MENU_ID`, `MENU_APPS_CODE`, `MENU_GROUP_LABEL`, `MENU_GROUP_LABEL_OTH`, `MENU_NAME`, `MENU_NAME_OTH`, `MENU_SEQ`, `MENU_PATH`, `MENU_ICON`, `MENU_STATUS`, `MENU_DT_CREATE`, `MENU_UID_CREATE`, `MENU_DT_LUPD`, `MENU_UID_LUPD`) VALUES ('CK_MH_080000', 'CK', 'Help', 'Help', 'Help', 'Help', '40000', '/help', 'help_outline', 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_TYPE`, `PERM_MENU`, `PERM_MENU_NAME`, `PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`, `PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM026', 'N', 'CK', 'M', 'CK_MH_040000', 'Help', 'Help', 'Help', 'R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');

/** Update the grant role permission for help to delete later the previous one */
UPDATE `clickargo`.`T_CORE_GRANT_ROLE_EX` SET `GNTRLEX_PERM_ID` = 'PM026' WHERE (`GNTRLEX_APPS_CODE` = 'CK') and (`GNTRLEX_ROLE_ID` = 'ADMIN') and (`GNTRLEX_PERM_ID` = 'PM006');
UPDATE `clickargo`.`T_CORE_GRANT_ROLE_EX` SET `GNTRLEX_PERM_ID` = 'PM026' WHERE (`GNTRLEX_APPS_CODE` = 'CK') and (`GNTRLEX_ROLE_ID` = 'FINANCE') and (`GNTRLEX_PERM_ID` = 'PM006');
UPDATE `clickargo`.`T_CORE_GRANT_ROLE_EX` SET `GNTRLEX_PERM_ID` = 'PM026' WHERE (`GNTRLEX_APPS_CODE` = 'CK') and (`GNTRLEX_ROLE_ID` = 'OFFICER') and (`GNTRLEX_PERM_ID` = 'PM006');
UPDATE `clickargo`.`T_CORE_GRANT_ROLE_EX` SET `GNTRLEX_PERM_ID` = 'PM026' WHERE (`GNTRLEX_APPS_CODE` = 'CK') and (`GNTRLEX_ROLE_ID` = 'OPERATIONS') and (`GNTRLEX_PERM_ID` = 'PM006');
UPDATE `clickargo`.`T_CORE_GRANT_ROLE_EX` SET `GNTRLEX_PERM_ID` = 'PM026' WHERE (`GNTRLEX_APPS_CODE` = 'CK') and (`GNTRLEX_ROLE_ID` = 'SYS_SUPER_ADMIN') and (`GNTRLEX_PERM_ID` = 'PM006');
/** Delete the previous */
DELETE FROM `clickargo`.`T_CORE_PERM_EX` WHERE (`PERM_ID` = 'PM006');
UPDATE `clickargo`.`T_CORE_PERM_EX` SET `PERM_MENU` = 'CK_MH_080000' WHERE (`PERM_ID` = 'PM026');
DELETE FROM `clickargo`.`T_CORE_MENU_EX` WHERE (`MENU_ID` = 'CK_MH_040000');
UPDATE `clickargo`.`T_CORE_MENU_EX` SET `MENU_SEQ` = '80000' WHERE (`MENU_ID` = 'CK_MH_080000');
/**------- SCRIPTS ABOVE THIS LINE EXECUTED IN DEV ON 2023-01-11 -----------*/

/** 2023-01-12 ADDED NEW COLUMN IN PAYMENT TRANSACTION FOR PAID DATE */
ALTER TABLE `T_CK_PAYMENT_TXN` 
ADD COLUMN `PTX_DT_PAID` DATETIME NULL AFTER `PTX_STATUS`;

/** 2023-01-12 JIRA CLICDO-146 Verify "+" (Add Job) ClicDO Page: Add Delete Icon during Edit */
INSERT INTO `T_CK_FORM_CONTROL` (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD)VALUES('32', 'ACC_TYPE_CO', NULL, 'OFFICER', 'JOB_DOI_CO', 'NEW', 'EDIT', 'DELETE', NULL, 'A', '2022-01-12 10:30:55', 'SYS', '2022-01-12 10:20:55', 'SYS');

/** 2023-01-15 Merged POA, updated for CONTAINER LOAN LETTER*/
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICDO_JRXML_POA_MERGED', 'docs/POA_Merged.jrxml', 'Locatin for Power of Authority (Authorized)', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');
UPDATE `T_CORE_SYSPARAM` SET `SYS_VAL` = 'docs/ContainerLoanLetter.jrxml' WHERE (`SYS_KEY` = 'CLICDO_JRXML_CONTAINER_GUARANTEE');

/** Component guide for extension jobs list, executed in DEV */
INSERT INTO `clickargo`.`T_CK_COMPONENT_GUIDE` (`CMGU_ID`, `CMGU_APPS_CODE`, `CMGU_SERVICE_TYPE`, `CMGU_COMPONENT_ID`, `CMGU_GUIDE`, `CMGU_GUIDE_OTH`, `CMGU_STATUS`, `CMGU_DT_CREATE`, `CMGU_UID_CREATE`, `CMGU_DT_LUPD`, `CMGU_UID_LUPD`) VALUES ('60', 'CK', 'CLICDO', 'clicdo.doi.ff.extension.jobs.list', 'To view any of your jobs without editing, click on the EYE button. To edit any draft jobs, click on the PENCIL button. To delete any draft jobs, click on the TRASH BIN button.', NULL, 'A', '2022-11-16 09:13:41', 'SYS', '2022-11-16 09:13:41', 'SYS');

/** CLICDO-195 */
ALTER TABLE `clickargo`.`T_CK_JOB_ATTACH` 
ADD COLUMN `ATT_REMARKS_VERIFIER` VARCHAR(2048) NULL DEFAULT NULL COMMENT 'REMARKS FROM VERIFIER' AFTER `ATT_STATUS`;

/** Claim Enhancements - Add BL Type and Container No. in CO Job */
ALTER TABLE `clickargo`.`T_CK_DOI` ADD COLUMN `BL_TYPE` VARCHAR(35) NULL DEFAULT NULL COMMENT 'BL TYPE' AFTER `DOI_RETURN_DEPOT`;
ALTER TABLE `clickargo`.`T_CK_DOI` ADD COLUMN `CONTAINER_NUMBER` VARCHAR(255) NULL DEFAULT NULL COMMENT 'CONTAINER NUMBER' AFTER `BL_TYPE`;

/** CLICDO-224 */
ALTER TABLE `clickargo`.`T_CK_JOB_ATTACH` 
ADD COLUMN `ATT_DT_VALIDITY` DATETIME NULL DEFAULT NULL COMMENT 'VALIDITY DATE OF THE ATTACHMENT' AFTER `ATT_BL_NO`;
/**------- SCRIPTS ABOVE THIS LINE EXECUTED IN DEV ON 2023-01-18 -----------*/


UPDATE `clickargo`.`T_CORE_MENU_EX` SET `MENU_GROUP_LABEL` = 'Pay DO', `MENU_GROUP_LABEL_OTH` = 'Pay DO', `MENU_NAME` = 'Pay DO', `MENU_NAME_OTH` = 'Pay DO' WHERE (`MENU_ID` = 'CK_MP_020000');
INSERT INTO `clickargo`.`T_CORE_MENU_EX` (`MENU_ID`, `MENU_APPS_CODE`, `MENU_GROUP_LABEL`, `MENU_GROUP_LABEL_OTH`, `MENU_NAME`, `MENU_NAME_OTH`, `MENU_SEQ`, `MENU_PATH`, `MENU_ICON`, `MENU_STATUS`, `MENU_DT_CREATE`, `MENU_UID_CREATE`, `MENU_DT_LUPD`, `MENU_UID_LUPD`) VALUES ('CK_MP_040000', 'CK', 'Payments', 'Payments', 'Payments', 'Payments', '40000', '/payments', 'payment', 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');

INSERT INTO `clickargo`.`T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_TYPE`, `PERM_MENU`, `PERM_MENU_NAME`, `PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`, `PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM027', 'Y', 'CK', 'M', 'CK_MP_040000', 'Payments', 'Transactions', 'Payments', 'R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
UPDATE `clickargo`.`T_CORE_GRANT_ROLE_EX` SET `GNTRLEX_PERM_ID` = 'PM027' WHERE (`GNTRLEX_APPS_CODE` = 'CK') and (`GNTRLEX_ROLE_ID` = 'FINANCE') and (`GNTRLEX_PERM_ID` = 'PM001');

UPDATE `clickargo`.`T_CORE_MENU_EX` SET `MENU_GROUP_LABEL` = 'Payments', `MENU_GROUP_LABEL_OTH` = 'Payments', `MENU_NAME` = 'Payments', `MENU_NAME_OTH` = 'Payments' WHERE (`MENU_ID` = 'CK_MP_070000');
UPDATE `clickargo`.`T_CORE_MENU_EX` SET `MENU_ICON` = 'receipt' WHERE (`MENU_ID` = 'CK_MP_070000');

/** Start JIRA CLICDO-232 CO Job submission does not call DODetails immediately, decouple API invocation */
--
-- Table structure for table `SHEDLOCK`
--

DROP TABLE IF EXISTS `SHEDLOCK`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `SHEDLOCK` (
  `name` varchar(64) NOT NULL,
  `lock_until` timestamp(3) NOT NULL,
  `locked_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `locked_by` varchar(255) NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

LOCK TABLES `SHEDLOCK` WRITE;
/*!40000 ALTER TABLE `SHEDLOCK` DISABLE KEYS */;
INSERT INTO `SHEDLOCK` VALUES ('DoiCoJobScheduler','2023-01-29 00:00:00','2023-01-29 00:00:00','local');
/*!40000 ALTER TABLE `SHEDLOCK` ENABLE KEYS */;
UNLOCK TABLES;

/** End JIRA CLICDO-232 CO Job submission does not call DODetails immediately, decouple API invocation */

/** Added OTHERS as attachment type*/
INSERT INTO `clickargo`.`T_MST_ATT_TYPE` (`MATT_ID`, `MATT_NAME`, `MATT_DESC`, `MATT_DESC_OTH`, `MATT_STATUS`, `MATT_DT_CREATE`, `MATT_UID_CREATE`, `MATT_DT_LUPD`, `MATT_UID_LUPD`, `MATT_EXPIRY`, `MATT_REF_NO`) VALUES ('OTH', 'OTHERS', 'OTHERS', NULL, 'A', '2018-12-01 00:00:00', 'SYS', '2018-12-01 00:00:00', 'SYS', 'N', 'N');

/** JIRA CLICDO-238 [FF-Finance ]FF Payment - UI Guide updates */
INSERT INTO `T_CK_COMPONENT_GUIDE` (CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)VALUES('37', 'CK', 'CLICDO', 'clicdo.payment.active.job.listing.table', 'Select at least one job and click the Pay icon for payment. Click the Magnifier icon to view list of DO.', NULL, 'A', '2023-02-01 00:00:00', 'SYS', '2023-02-01 00:00:00', 'SYS');
INSERT INTO `T_CK_COMPONENT_GUIDE` (CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)VALUES('38', 'CK', 'CLICDO', 'clicdo.payment.history.listing.table', 'Click the Eye icon to view Payment Details.', NULL, 'A', '2023-02-01 00:00:00', 'SYS', '2023-02-01 00:00:00', 'SYS');
INSERT INTO `T_CK_COMPONENT_GUIDE` (CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)VALUES('39', 'CK', 'CLICDO', 'clicdo.payment.details.table', 'For active payment, click the Arrow Submit icon to Pay. Click the Download icon to view the invoice.', NULL, 'A', '2023-02-01 00:00:00', 'SYS', '2023-02-01 00:00:00', 'SYS');

			
/** New Admin user */
INSERT INTO `T_CORE_USR` VALUES ('ALKNAR_A001','ALKNAR','A','Y','N','Agung Dwi Jayanto','88888888','Admin','OP','2022-10-01 00:00:00','2022-10-01 00:00:00',NULL,NULL,NULL,'Kawasan Industri Cimareme','Jalan Industri Cimareme II No. 14','Padalarang, West Bandung - 40553','40553','Jakarta','','ID','628568342615','','agung.dwijayanto@guud.company','cc24d68f504fa7db8d2539c16363a44f','','','','','2023-12-01 00:00:00',NULL,'',0,'2022-10-01 00:00:00','2022-10-01 00:00:00','',NULL,NULL,NULL,NULL,'2022-10-01 00:00:00','SYS','2022-10-01 00:00:00','SYS');
INSERT INTO `T_CORE_USR_ROLE` VALUES ('ALKNAR_A001','CK','ADMIN','N','A','2022-11-15 09:10:07','SYS','2022-11-15 09:10:07','SYS','N')

/** master sub menu ship type */
INSERT INTO `T_CORE_MENU_EX` (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)VALUES('CK_MT_050900', 'CK', NULL, NULL, 'Shipment Type', 'Shipment Type', 50900, '/master/shipType/list', NULL, 'CK_MT_050000', 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (PERM_ID, PERM_GROUP, PERM_APPS, PERM_MODULE, PERM_TYPE, PERM_SERVICE, PERM_SERVICE_URI, PERM_MENU, PERM_MENU_NAME, PERM_DOC_TYPE, PERM_DOC_CODE, PERM_ACTION, PERM_DESC, PERM_DESC_OTH, PERM_ACCESS, PERM_DT_ACTIVE, PERM_DT_DEACTIVE, PERM_STATUS, PERM_DT_CREATE, PERM_UID_CREATE, PERM_DT_LUPD, PERM_UID_LUPD)VALUES('PM028', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MT_050900', 'Shipment Type', NULL, NULL, NULL, 'Shipment Type', 'Shipment Type', 'R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');

/** master sub menu shipment type guides */
INSERT INTO `T_CK_COMPONENT_GUIDE` (CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)VALUES('70', 'CK', 'CLICDO', 'clicdo.master.shipment.type.list', '*To edit shipment type record click on the pencil icon, to deactivate/activate it click on the unlink icon and to view the details click on the eye icon.', NULL, 'A', '2023-02-05 00:00:00', 'SYS', '2023-02-05 00:00:00', 'SYS');
INSERT INTO `T_CK_COMPONENT_GUIDE` (CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)VALUES('71', 'CK', 'CLICDO', 'clicdo.master.shipment.type.details', 'Enter the details into the fields below and click Save to save or update the record, click Inactivate to set the status of the record to inactive. To exit this page without saving, click on the Exit button.', NULL, 'A', '2023-02-05 00:00:00', 'SYS', '2023-02-05 00:00:00', 'SYS');
INSERT INTO `T_CK_COMPONENT_GUIDE` (CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)VALUES('72', 'CK', 'CLICDO', 'clicdo.master.shipment.type.audit', 'The updates to the shipment type record are listed in the table below. You can filter the list to determine the changes.', NULL, 'A', '2023-02-05 00:00:00', 'SYS', '2023-02-05 00:00:00', 'SYS');

/** ClicTruck */
DROP TABLE IF EXISTS `T_CK_JOB_TRUCK`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `T_CK_JOB_TRUCK` (
  `JOB_ID` varchar(35) NOT NULL COMMENT 'JOB ID - UUID',
  `JOB_PARENT` varchar(35) NOT NULL COMMENT 'JOB PARENT - REFERENCE T_CK_JOB:JOB_ID',
  `SHIPMENT_REF` varchar(255) DEFAULT NULL COMMENT 'TRUCK SHIPMENT REFERENCE',
  `CUSTOMER_REF` varchar(255) DEFAULT NULL COMMENT 'TRUCK CUSTOMER REFERENCE',
  `JOB_STATUS` char(1) DEFAULT NULL COMMENT 'RECORD STATUS - A : I',    
  `JOB_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `JOB_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `JOB_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `JOB_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`JOB_ID`),
  KEY `FK_CK_JOB_TRUCK_CK_JOB` (`JOB_PARENT`),
  CONSTRAINT `FK_CK_JOB_TRUCK_CK_JOB` FOREIGN KEY (`JOB_PARENT`) REFERENCES `T_CK_JOB` (`JOB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='TRUCK JOB TABLE';
/*!40101 SET character_set_client = @saved_cs_client */;