INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CK','ADMIN','A','ACCOUNT ADMIN',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CK','OFFICER','A','OFFICER',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CK','OPERATIONS','A','OPERATIONS',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CK','FINANCE','A','FINANCE',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CK','SYS_SUPER_ADMIN','A','SYSTEM SUPER ADMIN',NOW(),'SYS',NOW(),'SYS');


INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('ALKNAR_U001','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('ALKNAR_U002','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('ALKNAR_U003','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('ALMGA_U001','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('ALMGA_U002','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('ALMGA_U003','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('ASPIND_U001','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('ASPIND_U002','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('ASPIND_U003','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('COMLG_U001','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('COMLG_U002','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('COMLG_U003','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('DUNLS_U001','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('DUNLS_U002','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('DUNLS_U003','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('FREXID_U001','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('FREXID_U002','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('FREXID_U003','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('GNOCIN_U001','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('GNOCIN_U002','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('GNOCIN_U003','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('MSC_U001','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('MSC_U002','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('MSC_U003','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('MSC_U004','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('MSC_U005','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('SUMTID_U001','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('SUMTID_U002','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('SUMTID_U003','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('TTIDR_U001','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('TTIDR_U002','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('TTIDR_U003','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('YINDF_U001','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('YINDF_U002','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('YINDF_U003','CK','OFFICER','N','A',NOW(),'SYS', NOW(),'SYS','N');

INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MS_010000','CK','Services','Services','Services','Services','10000','/workbench',NULL,NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MP_020000','CK','Payments','Payments','Payments','Payments','20000','/payments',NULL,NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MA_030000','CK','Administrations','Administrations','Administrations','Administrations','30000',NULL,'group',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MA_030100','CK','','','Account Profile','Account Profile','30100','/accountProfile',NULL,'CK_MA_030000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MA_030200','CK','','','Users','Users','30200','/accountUsers',NULL,'CK_MA_030000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MA_030300','CK','','','Authorisations','Authorisations','30400','/accountAuthorisations',NULL,'CK_MA_030000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MH_040000','CK','Help','Help','Help','Help','40000','/help',NULL,NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MT_050000','CK','Master Table','Master Table','Master Table','Master Table','50000',NULL,'table_view',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MT_050100','CK','','','Announcement Type','Announcement Type','50100','/configuration/announcementType/list',NULL,'CK_MT_050000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MT_050200','CK','','','Country Codes','Country Codes','50200','/master/country/list',NULL,'CK_MT_050000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MT_050300','CK','','','Currency Code','Currency Code','50300','/master/currency/list',NULL,'CK_MT_050000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MT_050400','CK','','','Harmonized System Codes','Harmonized System Codes','50400','/master/hsCode/list',NULL,'CK_MT_050000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MT_050500','CK','','','Notification Templates','Notification Templates','50500','/notification/templates/list',NULL,'CK_MT_050000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MT_050600','CK','','','Port Codes','Port Codes','50600','/master/port/list',NULL,'CK_MT_050000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MT_050700','CK','','','Port Terminal','Port Terminal','50700','/master/portTerminal/list',NULL,'CK_MT_050000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MT_050800','CK','','','UOM Codes','UOM Codes','50800','/master/uom/list',NULL,'CK_MT_050000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MSA_060000','CK','System Administrations','System Administrations','System Administrations','System Administrations','60000',NULL,'settings',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MSA_060100','CK','','','Announcement Setup','Announcement Setup','60100','/configuration/announcement/list',NULL,'CK_MSA_060100','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MSA_060200','CK','','','Notification Preferences','Notification Preferences','60200','/configuration/notification/preferences/list',NULL,'CK_MSA_060100','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MSA_060300','CK','','','System Parameters','System Parameters','60300','/administrations/sysparam/list',NULL,'CK_MSA_060100','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MSA_060400','CK','','','Audit Logs','Audit Logs','60400','/administrations/audit/list',NULL,'CK_MSA_060100','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MSA_060500','CK','','','Exceptions','Exceptions','60500','/administrations/exception/list',NULL,'CK_MSA_060100','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MSA_060600','CK','','','Manage All Users','Manage All Users','60600','/manageUsers/users/all/list',NULL,'CK_MSA_060100','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MSA_060700','CK','','','Manage All Accounts','Manage All Accounts','60700','/manageAccounts/all/list',NULL,'CK_MSA_060100','A',NOW(),'SYS',NOW(),'SYS');

INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM000', 'Y', 'CK', NULL, 'M', NULL, NULL, 'CK_MS_010000', 'Services', 'Services','Services','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM001', 'Y', 'CK', NULL, 'M', NULL, NULL, 'CK_MP_020000', 'Payments', 'Payments','Payments','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM002', 'Y', 'CK', NULL, 'M', NULL, NULL, 'CK_MA_030000', 'Administrations', 'Administrations','Administrations','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM003', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MA_030100', 'Account Profile', 'Account Profile','Account Profile','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM004', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MA_030200', 'Users', 'Users','Users','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM005', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MA_030300', 'Authorisations', 'Authorisations','Authorisations','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM006', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MH_040000', 'Help', 'Help','Help','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM007', 'Y', 'CK', NULL, 'M', NULL, NULL, 'CK_MT_050000', 'Master Table', 'Master Table','Master Table','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM008', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MT_050100', 'Announcement Type', 'Announcement Type','Announcement Type','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM009', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MT_050200', 'Country Codes', 'Country Codes','Country Codes','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM010', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MT_050300', 'Currency Code', 'Currency Code','Currency Code','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM011', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MT_050400', 'Harmonized System Codes', 'Harmonized System Codes','Harmonized System Codes','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM012', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MT_050500', 'Notification Templates', 'Notification Templates','Notification Templates','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM013', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MT_050600', 'Port Codes', 'Port Codes','Port Codes','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM014', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MT_050700', 'Port Terminal', 'Port Terminal','Port Terminal','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM015', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MT_050800', 'UOM Codes', 'UOM Codes','UOM Codes','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM016', 'Y', 'CK', NULL, 'M', NULL, NULL, 'CK_MSA_060000', 'System Administrations', 'System Administrations','System Administrations','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM017', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MSA_060100', 'Announcement Setup', 'Announcement Setup','Announcement Setup','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM018', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MSA_060200', 'Notification Preferences', 'Notification Preferences','Notification Preferences','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM019', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MSA_060300', 'System Parameters', 'System Parameters','System Parameters','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM020', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MSA_060400', 'Audit Logs', 'Audit Logs','Audit Logs','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM021', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MSA_060500', 'Exceptions', 'Exceptions','Exceptions','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM022', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MSA_060600', 'Manage All Users', 'Manage All Users','Manage All Users','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM023', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MSA_060700', 'Manage All Accounts', 'Manage All Accounts','Manage All Accounts','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');

INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM008', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM009', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM010', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM011', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM012', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM013', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM014', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM015', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM016', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM017', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM018', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM019', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM020', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM021', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM022', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM023', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM006', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'ADMIN', 'PM002', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'ADMIN', 'PM003', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'ADMIN', 'PM004', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'ADMIN', 'PM005', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'ADMIN', 'PM006', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'ADMIN', 'PM007', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'OFFICER', 'PM000', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'OFFICER', 'PM001', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'OFFICER', 'PM006', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'OFFICER', 'PM007', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'FINANCE', 'PM001', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'FINANCE', 'PM000', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'FINANCE', 'PM006', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'OPERATIONS', 'PM001', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'OPERATIONS', 'PM006', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'OPERATIONS', 'PM000', 'A', NOW(), 'SYS');

/**2022-11-11 Nina*/
ALTER TABLE `T_CK_JOB_DOI_CO` 
DROP FOREIGN KEY `FK_CK_JOB_DOI_CK_JOB_DOI_FF`;
ALTER TABLE `T_CK_JOB_DOI_CO` 
DROP INDEX `FK_CK_JOB_DOI_CK_JOB_DOI_FF_idx` ;
;


ALTER TABLE `T_CK_JOB_DOI_CO` 
ADD INDEX `FK_CK_JOB_DOI_CK_JOB_DOI_FF_idx` (`JOB_ASSIGNED_JOB_FF` ASC) VISIBLE;
;
ALTER TABLE `T_CK_JOB_DOI_CO` 
ADD CONSTRAINT `FK_CK_JOB_DOI_CK_JOB_DOI_FF`
  FOREIGN KEY (`JOB_ASSIGNED_JOB_FF`)
  REFERENCES `T_CK_JOB_DOI_FF` (`JOB_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

INSERT INTO `T_CK_MST_ENTITY_TYPE` (`ENTY_ID`, `ENTY_NAME`, `ENTY_DESC`, `ENTY_DESC_OTH`, `ENTY_STATUS`, `ENTY_DT_CREATE`, `ENTY_UID_CREATE`, `ENTY_DT_LUPD`, `ENTY_UID_LUPD`) VALUES ('TASK_DOI_FF', 'DO Import Task for CO FF', 'DO Import Task for CO FF', 'DO Import Task for CO FF', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');

INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('1','ACC_TYPE_CO',NULL,'OFFICER','JOB_DOI_CO','DRF','EDIT','SAVE',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('2','ACC_TYPE_CO',NULL,'OFFICER','JOB_DOI_CO','DRF','EDIT','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('3','ACC_TYPE_CO',NULL,'OFFICER','JOB_DOI_CO','NEW','EDIT','SAVE',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('4','ACC_TYPE_CO',NULL,'OFFICER','JOB_DOI_CO','NEW','EDIT','SUBMIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('5','ACC_TYPE_CO',NULL,'OFFICER','JOB_DOI_CO','NEW','EDIT','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('6','ACC_TYPE_CO',NULL,'OFFICER','JOB_DOI_CO','SUB','VIEW','CANCEL',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('7','ACC_TYPE_CO',NULL,'OFFICER','JOB_DOI_CO','SUB','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('8','ACC_TYPE_CO',NULL,'OFFICER','JOB_DOI_CO','PROG','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('9','ACC_TYPE_CO',NULL,'OFFICER','JOB_DOI_CO','COM','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('10','ACC_TYPE_FF',NULL,'OFFICER','JOB_DOI_FF','DRF','EDIT','SAVE',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('11','ACC_TYPE_FF',NULL,'OFFICER','JOB_DOI_FF','DRF','EDIT','SUBMIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('12','ACC_TYPE_FF',NULL,'OFFICER','JOB_DOI_FF','DRF','EDIT','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('13','ACC_TYPE_FF',NULL,'OFFICER','JOB_DOI_FF','NEW','EDIT','SAVE',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('14','ACC_TYPE_FF',NULL,'OFFICER','JOB_DOI_FF','NEW','EDIT','SUBMIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('15','ACC_TYPE_FF',NULL,'OFFICER','JOB_DOI_FF','NEW','EDIT','DELETE',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('16','ACC_TYPE_FF',NULL,'OFFICER','JOB_DOI_FF','NEW','EDIT','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('17','ACC_TYPE_FF',NULL,'OFFICER','JOB_DOI_FF','SUB','VIEW','PAY',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('18','ACC_TYPE_FF',NULL,'OFFICER','JOB_DOI_FF','SUB','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('19','ACC_TYPE_FF',NULL,'OFFICER','JOB_DOI_FF','PAID','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('20','ACC_TYPE_FF',NULL,'OFFICER','JOB_DOI_FF','PAID','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('21','ACC_TYPE_FF',NULL,'OFFICER','JOB_DOI_FF','PMV','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('22','ACC_TYPE_FF',NULL,'OFFICER','JOB_DOI_FF','COM','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('23','ACC_TYPE_SL',NULL,'OPERATIONS','JOB_DOI_FF','PMV','VIEW','VERIFY',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('24','ACC_TYPE_SL',NULL,'OPERATIONS','JOB_DOI_FF','PMV','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('25','ACC_TYPE_SL',NULL,'FINANCE','JOB_DOI_FF','PAID','VIEW','VERIFY',NULL,'A',NOW(), 'SYS',NOW(),'SYS');
INSERT INTO T_CK_FORM_CONTROL (CTRL_ID, CTRL_ACCN_TYPE, CTRL_ACCN, CTRL_USR_ROLE, CTRL_ENTITY_TYPE, CTRL_ENTITY_STATE, CTRL_FORM_TYPE, CTRL_FORM_ACTION, CTRL_FORM_ACTION_MENU, CTRL_STATUS, CTRL_DT_CREATE, CTRL_UID_CREATE, CTRL_DT_LUPD, CTRL_UID_LUPD) VALUES('26','ACC_TYPE_SL',NULL,'FINANCE','JOB_DOI_FF','PAID','VIEW','EXIT',NULL,'A',NOW(), 'SYS',NOW(),'SYS');


/** 2022-11-13 Nina*/
ALTER TABLE `T_MST_ATT_TYPE` 
ADD COLUMN `MATT_EXPIRY` CHAR(1) NULL DEFAULT 'N' AFTER `MATT_UID_LUPD`,
ADD COLUMN `MATT_REF_NO` CHAR(1) NULL DEFAULT 'N' AFTER `MATT_EXPIRY`;

/** 2022-11-16 Nina Script for component guide*/
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('1','CK','CLICDO','clicdo.doi.co.jobs.list','When a job is submitted, it is locked and its fields cannot be edited. If there are errors associated with the submitted job, it has to be cancelled before it is picked up for processing by the authorized party (aka Freight Forwarder)',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('2','CK','CLICDO','clicdo.doi.co.jobs.list.table','Each job recordi n the list corresponds to job corresponding to a Bill of Lading (BL) document. These jobs when submitted will be picked up by the Authorized Party (aka Freight Forwarders) stated in the job for DO claiming. Click on eye icon to view the BL in PDF and the cancel icon to cancel the job.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('3','CK','CLICDO','clicdo.doi.co.jobs.tabs.details','Update all the information to ensure correct information about the job is captured. Click Save to save the updated job or click Submit to submit the job to the Authorized Party.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('4','CK','CLICDO','clicdo.doi.co.jobs.tabs.authorisation','Document will be reviewed by shipping line. If there are concerns, the owner of the job will be contacted via email for clarifications. Only after the documents and payment are verified will your Authorized Party be able to download the invoice and start the DO claim process.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('5','CK','CLICDO','clicdo.doi.co.jobs.tabs.authorisation.table','Except Bill of Lading, the authorisation document is generated and digital stamped. Click on Download to view the document in PDF format.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('6','CK','CLICDO','clicdo.doi.co.jobs.tabs.audit','The audited even associated with the job is presented here. Filtering is supported to sniff out audit records by criteria(s).',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('7','CK','CLICDO','clicdo.doi.ff.bl.list','To view any of the Bill of Ladings, click on the DOWNLOAD button. To reject ony Bill of Ladings, click on the REJECT button.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('8','CK','CLICDO','clicdo.doi.ff.bl.list.table','Each job recordi n the list corresponds to a Bill of Lading (BL) document submitted by the Authorizer Party (aka Cargo Owners) for DO claiming. Click on eye icon to view the BL in PDF and then cancel icon to reject the BL.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('9','CK','CLICDO','clicdo.doi.ff.claim.jobs.list','To view any of your jobs without editing, click on the EYE button. To edit any draft jobs, click on the PENCIL button. To delete any draft jobs, click on the TRASH BIN button.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('10','CK','CLICDO','clicdo.doi.ff.claim.jobs.list.table','Active DO claim jobs that you are processing',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('11','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.details','Please update all the information to ensure correct information about the job is captured. Please notethat once the job has been confirmed, BLs cannot be edited or removed from the list.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('12','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.detaills.table','Click on the eye icon to view the BL document. Click on the trash bin to remove BL from the list.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('13','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.attachments','Documents associated with all the BL are captured in the list.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('14','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.attachments.table','Click on the Download icon to download the respective documents. Power of Authority, Letter of Assignment  and Container Loan Application documents are automatically generated by the system.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('15','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.task.details','Once the list of DOs are confirmed clicked on the Submit button to retrieve the DO documents from the shipping line.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('16','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.task.details.table.main','Click on the Eye icon to view the task details on the section below. Click the Pencil icon to edit the task and Trash Bin to remove the task.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('17','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.task.details.table.sub','Click on the Trash Bin to remove DO from the task that are in NEW status. Click on Eye icon to view the DO details.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('18','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.query','Ensure that there are no outstanding queries by the Shipping Line. Document can be manually and temporarily added when there is an outstanding query.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('19','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.query.table','Click on the Response icon to response to the query after you have made the necessary changes requested by the Shipping Line. Click on the Eye icon to view the query made by the Shipping Line and the response to the query.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('20','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.audit','The audited even associated with the job is presented here. Filtering is supported to sniff out audit records by criteria(s).',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('21','CK','CLICDO','clicdo.doi.sl.claim.jobs.list','To view any of your jobs without editing, click on the Eye button. To edit any draft jobs, click on the Pencil button. To delete any draf jobs, click on the Trash Bin button.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('22','CK','CLICDO','clicdo.doi.sl.claim.jobs.list.table','Click on the Document icon to perform document verification. Click on the Money icon to perform payment verification.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('23','CK','CLICDO','clicdo.doi.sl.claim.jobs.tab.docverify.details','The charges amount will be shown once the job is submitted and verified. The proforma invoices are also available for download when the job details and documents are verified. Once payment is made, DO claim tasks ca be started to claim the DO under the BLs.',NULL,'A',NOW(),'SYS',NOW(),'SYS');



/** 2022-11-18 Nina Sysparam attachment base location */
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`,`SYS_STATUS`) VALUES ('CLICDO_ATTCH_BASE_LOCATION', '/Users/ninasilva/Documents/Project/appAttachments/', 'Base location for the attachments', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS','A');

/** 2022-11-21 Marvin master attachments */
-- INSERT INTO `T_MST_ATT_TYPE` VALUES ('ACR','ACCOUNT ACRA','ACCOUNT ACRA',NULL,'A','2018-12-01 00:00:00','SYS','2018-12-01 00:00:00','SYS'),('BL','BILL OF LADING','BILL OF LADING',NULL,'A','2022-10-01 01:00:00','SYS','2018-12-01 00:00:00','SYS'),('CLO','COMPANY LOGO','COMPANY LOGO',NULL,'A','2018-12-01 00:00:00','SYS','2018-12-01 00:00:00','SYS'),('CUS','COMPANY USER SIGNATURES','COMPANY USER SIGNATURES',NULL,'A','2018-12-01 00:00:00','SYS','2018-12-01 00:00:00','SYS'),('LAS','LIST OF AUTHORISED SIGN','LIST OF AUTHORISED SIGN',NULL,'A','2018-12-01 00:00:00','SYS','2018-12-01 00:00:00','SYS'),('LOA','LETTER OF ASSIGNMENT','LETTER OF ASSIGNMENT',NULL,'A','2022-10-01 01:00:00','SYS','2018-12-01 00:00:00','SYS'),('LOI','LETTER OF INDEMNITY','LETTER OF INDEMNITY',NULL,'A','2018-12-01 00:00:00','SYS','2018-12-01 00:00:00','SYS'),('LOU','LETTER OF UNDERTAKING','LETTER OF UNDERTAKING',NULL,'A','2018-12-01 00:00:00','SYS','2018-12-01 00:00:00','SYS'),('PHO','USER PROFILE PICTURE','USER PROFILE PICTURE',NULL,'A','2018-12-01 00:00:00','SYS','2018-12-01 00:00:00','SYS'),('POA','POWER OF AUTHORITY','POWER OF AUTHORITY',NULL,'A','2022-10-01 01:00:00','SYS','2022-10-01 01:00:00','SYS'),('SIG','USER SIGNATURE PHOTO','USER SIGNATURE',NULL,'A','2018-12-01 00:00:00','SYS','2018-12-01 00:00:00','SYS'),('STP','COMPANY STAMP','COMPANY STAMP',NULL,'A','2018-12-01 00:00:00','SYS','2018-12-01 00:00:00','SYS');
INSERT INTO `T_MST_ATT_TYPE` (`MATT_ID`, `MATT_NAME`, `MATT_DESC`, `MATT_STATUS`, `MATT_DT_CREATE`, `MATT_UID_CREATE`, `MATT_DT_LUPD`, `MATT_UID_LUPD`, `MATT_EXPIRY`, `MATT_REF_NO`) VALUES ('BL', 'BILL OF LADING', 'COMPANY LOGO', 'A', '2018-12-01 00:00:00', 'SYS', '2018-12-01 00:00:00', 'SYS', 'N', 'N');

/** 2022-11-22 Nina added new column for sl account refer to T_CK_DOI*/
ALTER TABLE `T_CK_DOI` 
ADD COLUMN `DOI_SL_ACCN` VARCHAR(35) NULL AFTER `DOI_NOTIFY_ACCN`;

/** 2022-11-23 Nina added new column for sl account in T_CK_JOB_DOIC_FF*/
ALTER TABLE `T_CK_JOB_DOI_FF` 
ADD COLUMN `JOB_SL_ACCN` VARCHAR(35) NOT NULL AFTER `JOB_AUTHORIZED_PARTY_ACCN`,
ADD INDEX `FK_CK_JOB_DOI_SL_ACCN_idx` (`JOB_SL_ACCN` ASC) VISIBLE;
;
ALTER TABLE `T_CK_JOB_DOI_FF` 
ADD CONSTRAINT `FK_CK_JOB_DOI_SL_ACCN`
  FOREIGN KEY (`JOB_SL_ACCN`)
  REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

/** 2022-11-24 Marvin added new value for sl account in T_CORE_SYSPARAM*/
INSERT INTO T_CORE_SYSPARAM (SYS_KEY, SYS_VAL, SYS_DESC, SYS_DT_CREATE, SYS_UID_CREATE, SYS_DT_LUPD, SYS_UID_LUPD, SYS_STATUS) 
	VALUES('CLICDO_DEF_SL_ACCN', 'MSC', 'Temporary configuration to default the shipping line when creating claim job.', '2022-11-24 00:00:00', 'SYS', '2022-11-24 00:00:00', 'SYS', 'A');

/** 2022-11-24 Nina - added new table for T_CORE_USR extension */
CREATE TABLE `T_CK_USR_EXT` (
  `UET_ID` varchar(35) NOT NULL,
  `UET_USR_UID` varchar(35) DEFAULT NULL,
  `UET_NOTIF_PREF` varchar(1024) DEFAULT NULL COMMENT 'JSON FORMAT FOR USER NOTIFICAITON PREFERENCE : {email: ‘Y’, sms: ‘Y’, telegram: ‘Y’)',
  `UET_STATUS` char(1) DEFAULT NULL,
  `UET_DT_CREATE` datetime DEFAULT NULL,
  `UET_UID_CREATE` varchar(35) DEFAULT NULL,
  `UET_DT_LUPD` datetime DEFAULT NULL,
  `UET_UID_LUPD` varchar(35) DEFAULT NULL,
  PRIMARY KEY (`UET_ID`),
  KEY `UET_USR_UID` (`UET_USR_UID`),
   CONSTRAINT `F_CK_USR_EXT_ID_TCOREUSR_ID_idx` FOREIGN KEY (`UET_USR_UID`) REFERENCES `T_CORE_USR` (`USR_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


ALTER TABLE `T_CORE_ATTACH` 
ADD COLUMN `ATT_EXT_ATTR` VARCHAR(1024) NULL AFTER `ATT_DT_LUPD`,
ADD COLUMN `ATT_DC_CODE` VARCHAR(35) NULL AFTER `ATT_EXT_ATTR`;


/** 2022-11-25 CK added component guides for task details page*/
Insert into T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  values('24','CK','CLICDO','clicdo.task-details.task-listing.table','*Click on the EYE icon to view the task details on the section below. Click the PENCIL icon to edit the task and TRASH BIN icon to remove the task.', '','A', now(), 'SYS', now(), 'SYS');
Insert into T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  values('25','CK','CLICDO','clicdo.task-details.doi-listing.table','Click on the TRASH BIN to remove DO from the task that are in NEW status. Click on EYE icon to view the DO details.', '','A', now(), 'SYS', now(), 'SYS');
Insert into T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  values('26','CK','CLICDO','clicdo.task-details.footer.info','*Once the list of DO are confirmed click on the Submit button to retrive the DO documents from the shipping line.', '','A', now(), 'SYS', now(), 'SYS');

/** 2022-11-26 Nina */
INSERT INTO `T_CK_COMPONENT_GUIDE` (`CMGU_ID`, `CMGU_APPS_CODE`, `CMGU_SERVICE_TYPE`, `CMGU_COMPONENT_ID`, `CMGU_GUIDE`, `CMGU_STATUS`, `CMGU_DT_CREATE`, `CMGU_UID_CREATE`, `CMGU_DT_LUPD`, `CMGU_UID_LUPD`) VALUES ('27', 'CK', 'CLICDO', 'clicdo.doi.ff.claim.jobs.tabs.details.new', 'The charges amount will be shown once the job is submitted and verified. The proforma invoices are also available for download when the job details and documents are verified. Once payment is made, DO claim tasks can be started to claim the DO under the BLs.', 'A', '2022-11-16 09:13:41', 'SYS', '2022-11-16 09:13:41', 'SYS');
INSERT INTO `T_CK_COMPONENT_GUIDE` (`CMGU_ID`, `CMGU_APPS_CODE`, `CMGU_SERVICE_TYPE`, `CMGU_COMPONENT_ID`, `CMGU_GUIDE`, `CMGU_STATUS`, `CMGU_DT_CREATE`, `CMGU_UID_CREATE`, `CMGU_DT_LUPD`, `CMGU_UID_LUPD`) VALUES ('28', 'CK', 'CLICDO', 'clicdo.doi.ff.claim.jobs.tabs.detaills.table.new', 'Click on the eye icon to view the BL document. BL documents cannot be removed because the job is confirmed.', 'A', '2022-11-16 09:13:41', 'SYS', '2022-11-16 09:13:41', 'SYS');
INSERT INTO `T_CK_COMPONENT_GUIDE` (`CMGU_ID`, `CMGU_APPS_CODE`, `CMGU_SERVICE_TYPE`, `CMGU_COMPONENT_ID`, `CMGU_GUIDE`, `CMGU_STATUS`, `CMGU_DT_CREATE`, `CMGU_UID_CREATE`, `CMGU_DT_LUPD`, `CMGU_UID_LUPD`) VALUES ('29', 'CK', 'CLICDO', 'clicdo.doi.ff.claim.jobs.tabs.details.submittted', 'Once payment is made, DO claim tasks can be started to claim the DO under the BLs.', 'A', '2022-11-16 09:13:41', 'SYS', '2022-11-16 09:13:41', 'SYS');
INSERT INTO `T_CK_COMPONENT_GUIDE` (`CMGU_ID`, `CMGU_APPS_CODE`, `CMGU_SERVICE_TYPE`, `CMGU_COMPONENT_ID`, `CMGU_GUIDE`, `CMGU_STATUS`, `CMGU_DT_CREATE`, `CMGU_UID_CREATE`, `CMGU_DT_LUPD`, `CMGU_UID_LUPD`) VALUES ('30', 'CK', 'CLICDO', 'clicdo.doi.ff.claim.jobs.tabs.detaills.table.submitted', 'Click on the Eye icon to view the BL document. Click the Download icon to download the proforma invoice.', 'A', '2022-11-16 09:13:41', 'SYS', '2022-11-16 09:13:41', 'SYS');
INSERT INTO `T_CK_COMPONENT_GUIDE` (`CMGU_ID`, `CMGU_APPS_CODE`, `CMGU_SERVICE_TYPE`, `CMGU_COMPONENT_ID`, `CMGU_GUIDE`, `CMGU_STATUS`, `CMGU_DT_CREATE`, `CMGU_UID_CREATE`, `CMGU_DT_LUPD`, `CMGU_UID_LUPD`) VALUES ('31', 'CK', 'CLICDO', 'clicdo.doi.ff.claim.jobs.tabs.details.paid', 'Once payment is verified, DO claim tasks can be started to claim the DO under the BLs.', 'A', '2022-11-16 09:13:41', 'SYS', '2022-11-16 09:13:41', 'SYS');
INSERT INTO `T_CK_COMPONENT_GUIDE` (`CMGU_ID`, `CMGU_APPS_CODE`, `CMGU_SERVICE_TYPE`, `CMGU_COMPONENT_ID`, `CMGU_GUIDE`, `CMGU_STATUS`, `CMGU_DT_CREATE`, `CMGU_UID_CREATE`, `CMGU_DT_LUPD`, `CMGU_UID_LUPD`) VALUES ('32', 'CK', 'CLICDO', 'clicdo.doi.ff.claim.jobs.tabs.detaills.table.paid', 'Click on the eye icon to view the BL document. Click the Download icon to download the proforma invoice.', 'A', '2022-11-16 09:13:41', 'SYS', '2022-11-16 09:13:41', 'SYS');
INSERT INTO `T_CK_COMPONENT_GUIDE` (`CMGU_ID`, `CMGU_APPS_CODE`, `CMGU_SERVICE_TYPE`, `CMGU_COMPONENT_ID`, `CMGU_GUIDE`, `CMGU_STATUS`, `CMGU_DT_CREATE`, `CMGU_UID_CREATE`, `CMGU_DT_LUPD`, `CMGU_UID_LUPD`) VALUES ('33', 'CK', 'CLICDO', 'clicdo.doi.ff.claim.jobs.tabs.details.verified', 'Tasks can be started to claim the DO(s) associated with the BL in the list.', 'A', '2022-11-16 09:13:41', 'SYS', '2022-11-16 09:13:41', 'SYS');
INSERT INTO `T_CK_COMPONENT_GUIDE` (`CMGU_ID`, `CMGU_APPS_CODE`, `CMGU_SERVICE_TYPE`, `CMGU_COMPONENT_ID`, `CMGU_GUIDE`, `CMGU_STATUS`, `CMGU_DT_CREATE`, `CMGU_UID_CREATE`, `CMGU_DT_LUPD`, `CMGU_UID_LUPD`) VALUES ('34', 'CK', 'CLICDO', 'clicdo.doi.ff.claim.jobs.tabs.detaills.table.verified', 'Click on the eye icon to view the BL document. Click the download icon to download the proforma invoice.', 'A', '2022-11-16 09:13:41', 'SYS', '2022-11-16 09:13:41', 'SYS');
INSERT INTO `T_CK_COMPONENT_GUIDE` (`CMGU_ID`, `CMGU_APPS_CODE`, `CMGU_SERVICE_TYPE`, `CMGU_COMPONENT_ID`, `CMGU_GUIDE`, `CMGU_STATUS`, `CMGU_DT_CREATE`, `CMGU_UID_CREATE`, `CMGU_DT_LUPD`, `CMGU_UID_LUPD`) VALUES ('35', 'CK', 'CLICDO', 'clicdo.doi.ff.claim.jobs.tabs.details.completed', 'Tasks can be started to claim the DO(s) associated with the BL in the list.', 'A', '2022-11-16 09:13:41', 'SYS', '2022-11-16 09:13:41', 'SYS');
INSERT INTO `T_CK_COMPONENT_GUIDE` (`CMGU_ID`, `CMGU_APPS_CODE`, `CMGU_SERVICE_TYPE`, `CMGU_COMPONENT_ID`, `CMGU_GUIDE`, `CMGU_STATUS`, `CMGU_DT_CREATE`, `CMGU_UID_CREATE`, `CMGU_DT_LUPD`, `CMGU_UID_LUPD`) VALUES ('36', 'CK', 'CLICDO', 'clicdo.doi.ff.claim.jobs.tabs.detaills.table.completed', 'Click on the eye icon to view the BL document. Click the download icon to download the proforma invoice.', 'A', '2022-11-16 09:13:41', 'SYS', '2022-11-16 09:13:41', 'SYS');

/** 2022-11-27 Nina new form action for Query */
INSERT INTO `T_CK_MST_FORM_ACTION` (`FMACT_ID`, `FMACT_NAME`, `FMACT_DESC`, `FMACT_DESC_OTH`, `FMACT_STATUS`, `FMACT_DT_CREATE`, `FMACT_UID_CREATE`, `FMACT_DT_LUPD`, `FMACT_UID_LUPD`) VALUES ('QUERY', 'Form Query', 'Form Query', 'Form Query', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');


/** 2022-11-28 Nina Added dodcument type for surat kuasa*/
INSERT INTO `T_MST_ATT_TYPE` (`MATT_ID`, `MATT_NAME`, `MATT_DESC`, `MATT_STATUS`, `MATT_DT_CREATE`, `MATT_UID_CREATE`, `MATT_DT_LUPD`, `MATT_UID_LUPD`, `MATT_EXPIRY`, `MATT_REF_NO`) VALUES ('SK', 'SURAT KUASA', 'SURAT KUASA', 'A', '2018-12-01 00:00:00', 'SYS', '2018-12-01 00:00:00', 'SYS', 'N', 'N');

/** NOTE: Change to your local path */
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICDO_JRXML_BASE_PATH', '/home/vcc/tomcat9/webapps/clicdo/', 'Base location for jasper, end with /', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICDO_JRXML_SURATKUASA', 'docs/SuratKuasa.jrxml', 'Location for Surat Kuasa jasper file', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

/** 2022-11-29 UPDATED INDEX*/
ALTER TABLE `T_CK_DOI` 
ADD INDEX `FK_CK_DOI_SL_ACCN` (`DOI_SL_ACCN` ASC) VISIBLE;
;

 UPDATE `T_CORE_MENU_EX` SET `MENU_PATH` = '/' WHERE (`MENU_ID` = 'CK_MS_010000');


/** 2022-11-30 CK added do folder path & invoice folder path constants. Note already executed by CK in dev db*/
INSERT INTO T_CORE_SYSPARAM (SYS_KEY, SYS_VAL, SYS_DESC, SYS_DT_CREATE, SYS_UID_CREATE, SYS_DT_LUPD, SYS_UID_LUPD, SYS_STATUS)
VALUES('CLICDO_DO_FOLDER_PATH', '/home/vcc/do/', 'Path of folder to store do', '2022-11-30 00:00:00', 'SYS', '2022-11-30 00:00:00', 'SYS', 'A'),
      ('CLICDO_INVOICE_FOLDER_PATH', '/home/vcc/invoice/', 'Path of folder to store invoice', '2022-11-30 00:00:00', 'SYS', '2022-11-30 00:00:00', 'SYS', 'A');


/** 2022-11-30 added guide for shipping line*/
INSERT INTO `T_CK_COMPONENT_GUIDE` (`CMGU_ID`, `CMGU_APPS_CODE`, `CMGU_SERVICE_TYPE`, `CMGU_COMPONENT_ID`, `CMGU_GUIDE`, `CMGU_STATUS`, `CMGU_DT_CREATE`, `CMGU_UID_CREATE`, `CMGU_DT_LUPD`, `CMGU_UID_LUPD`) VALUES ('37', 'CK', 'CLICDO', 'clicdo.doi.sl.doc.verify.list', 'Once submitted tasks has been submitted, the DOs listed within the tasks cannot be updated or removed. The shipping line will proceed to review the letter of authorisation documents, the DO charges will only be shown when the documents have been verified. The DO document and invoice will only be available for download once payment has been moade and verified by the officer.', 'A', '2022-11-16 09:13:41', 'SYS', '2022-11-16 09:13:41', 'SYS');
INSERT INTO `T_CK_COMPONENT_GUIDE` (`CMGU_ID`, `CMGU_APPS_CODE`, `CMGU_SERVICE_TYPE`, `CMGU_COMPONENT_ID`, `CMGU_GUIDE`, `CMGU_STATUS`, `CMGU_DT_CREATE`, `CMGU_UID_CREATE`, `CMGU_DT_LUPD`, `CMGU_UID_LUPD`) VALUES ('38', 'CK', 'CLICDO', 'clicdo.doi.sl.pay.verify.list', 'Once submitted tasks has been submitted, the DOs listed within the tasks cannot be updated or removed. The shipping line will proceed to review the letter of authorisation documents, the DO charges will only be shown when the documents have been verified. The DO document and invoice will only be available for download once payment has been moade and verified by the officer.', 'A', '2022-11-16 09:13:41', 'SYS', '2022-11-16 09:13:41', 'SYS');

/** 2022-11-30 CK added assigned state for do. Note already executed by CK in dev db */
INSERT INTO `T_CK_MST_DO_STATE` VALUES ('ASG','ASSIGNED','ASSIGNED','ASSIGNED','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');


ALTER TABLE `T_CK_DOI` 
ADD CONSTRAINT `FK_CK_DOI_CORE_ACCN3`
  FOREIGN KEY (`DOI_SL_ACCN`)
  REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

/** 2022-12-02 Nina adding menu for finance and operations */
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'FINANCE', 'PM001', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'FINANCE', 'PM000', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'FINANCE', 'PM006', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'OPERATIONS', 'PM001', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'OPERATIONS', 'PM006', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'OPERATIONS', 'PM000', 'A', NOW(), 'SYS');
 /** 2022-11-30 Attachment configuration for CO jobs*/
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICDO_CO_JOB_ATT_CONFIG', '{\"unAuthorized\":{\"attTypes\":\"SURAT_KUASA\",\"jrxmlPath\":\"docs/SuratKuasa_Period.jrxml\"},\"isAuthorized\":{\"attTypes\":\"SURAT_KUASA\",\"jrxmlPath\":\"docs/SuratKuasa_Auth.jrxml\"}}', 'Location for Surat Kuasa jasper file', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');
INSERT INTO `T_CK_FORM_CONTROL` (`CTRL_ID`, `CTRL_ACCN_TYPE`, `CTRL_USR_ROLE`, `CTRL_ENTITY_TYPE`, `CTRL_ENTITY_STATE`, `CTRL_FORM_TYPE`, `CTRL_FORM_ACTION`, `CTRL_STATUS`, `CTRL_DT_CREATE`, `CTRL_UID_CREATE`, `CTRL_DT_LUPD`, `CTRL_UID_LUPD`) VALUES ('29', 'ACC_TYPE_SL', 'OPERATIONS', 'JOB_DOI_FF', 'SUB', 'VIEW', 'VERIFY', 'A', '2022-11-26 16:41:35', 'SYS', '2022-11-26 16:41:35', 'SYS');


/** Adenny 12/02 Disable Submit on DRAFT Status for DOI FF*/
UPDATE T_CK_FORM_CONTROL SET CTRL_STATUS = 'I' WHERE 
	CTRL_ACCN_TYPE = 'ACC_TYPE_FF' AND CTRL_ENTITY_TYPE = 'JOB_DOI_FF' AND CTRL_ENTITY_STATE = 'DRF' AND CTRL_FORM_ACTION = 'SUBMIT';

/** Added CONFIRM in T_CK_MST_JOB_STATE */
INSERT INTO `clickargo`.`T_CK_MST_JOB_STATE` (`JBST_ID`, `JBST_NAME`, `JBST_DESC`, `JBST_DESC_OTH`, `JBST_STATUS`, `JBST_DT_CREATE`, `JBST_UID_CREATE`, `JBST_DT_LUPD`, `JBST_UID_LUPD`) VALUES ('CON', 'CONFIRMED', 'CONFIRMED', 'CONFIRMED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

/** Added CONFIRM in T_CK_MST_ENTITY_STATE */
INSERT INTO `clickargo`.`T_CK_MST_ENTITY_STATE` (`ENST_ID`, `ENST_NAME`, `ENST_DESC`, `ENST_DESC_OTH`, `ENST_STATUS`, `ENST_DT_CREATE`, `ENST_UID_CREATE`,  `ENST_DT_LUPD`, `ENST_UID_LUPD`) VALUES ('CON', 'CONFIRMED', 'CONFIRMED', 'CONFIRMED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

/** Added T_CK_FORM_CONTROL for CONFIRMED status */
INSERT INTO `clickargo`.`T_CK_FORM_CONTROL` (`CTRL_ID`, `CTRL_ACCN_TYPE`, `CTRL_ACCN`, `CTRL_USR_ROLE`, `CTRL_ENTITY_TYPE`, `CTRL_ENTITY_STATE`, `CTRL_FORM_TYPE`, `CTRL_FORM_ACTION`, `CTRL_FORM_ACTION_MENU`, `CTRL_STATUS`, `CTRL_DT_CREATE`, `CTRL_UID_CREATE`, `CTRL_DT_LUPD`, `CTRL_UID_LUPD`) VALUES 
('100', 'ACC_TYPE_FF', NULL, 'OFFICER', 'JOB_DOI_FF', 'CON', 'EDIT', 'PAY', NULL, 'A', '2022-11-13 13:16:23', 'SYS', '2022-11-13 13:16:23', 'SYS');
INSERT INTO `clickargo`.`T_CK_FORM_CONTROL` (`CTRL_ID`, `CTRL_ACCN_TYPE`, `CTRL_ACCN`, `CTRL_USR_ROLE`, `CTRL_ENTITY_TYPE`, `CTRL_ENTITY_STATE`, `CTRL_FORM_TYPE`, `CTRL_FORM_ACTION`, `CTRL_FORM_ACTION_MENU`, `CTRL_STATUS`, `CTRL_DT_CREATE`, `CTRL_UID_CREATE`, `CTRL_DT_LUPD`, `CTRL_UID_LUPD`) VALUES 
('101', 'ACC_TYPE_FF', NULL, 'OFFICER', 'JOB_DOI_FF', 'CON', 'EDIT', 'EXIT', NULL, 'A', '2022-11-13 13:16:23', 'SYS', '2022-11-13 13:16:23', 'SYS');

/** Added T_MST_ATT_TYPE LOA and POA */
INSERT INTO `T_MST_ATT_TYPE` (MATT_ID, MATT_NAME, MATT_DESC, MATT_DESC_OTH, MATT_STATUS, MATT_DT_CREATE, MATT_UID_CREATE, MATT_DT_LUPD, MATT_UID_LUPD, MATT_EXPIRY, MATT_REF_NO)
VALUES('LOA', 'LETTER OF ASSIGNMENT', 'LETTER OF ASSIGNMENT', NULL, 'A', '2022-10-01 01:00:00', 'SYS', '2018-12-01 00:00:00', 'SYS', 'N', 'N');
INSERT INTO `T_MST_ATT_TYPE` (MATT_ID, MATT_NAME, MATT_DESC, MATT_DESC_OTH, MATT_STATUS, MATT_DT_CREATE, MATT_UID_CREATE, MATT_DT_LUPD, MATT_UID_LUPD, MATT_EXPIRY, MATT_REF_NO)
VALUES('POA', 'POWER OF AUTHORITY', 'POWER OF AUTHORITY', NULL, 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS', 'N', 'N');

/** 2022-12-06 Bill - added new table for payment */
CREATE TABLE `T_CK_PAYMENT_TXN` (
  `PTX_ID` varchar(35) NOT NULL COMMENT 'PAYMENT TXN ID - UUID',
  `PTX_TYPE` varchar(35) DEFAULT NULL COMMENT 'PAYMENT TYPE - REFERENCE T_CK_MST_PAYMENT_TYPE:PTY_ID',
  `PTX_SVC` varchar(35) DEFAULT NULL COMMENT 'CLICKARGO SERVICES - REFERENCE T_CK_MST_SERVICE_TYPE:SVCT_ID',
  `PTX_SVC_REF` varchar(2048) DEFAULT NULL COMMENT 'JOB OR TASK ID REFERENCE FOR THE PAYMENT',
  `PTX_MERCHANT_BANK` varchar(35) DEFAULT NULL COMMENT 'PAYMENT MERCHANT BANK',
  `PTX_PAYER` varchar(35) DEFAULT NULL COMMENT 'PAYER - REFERENCES T_CORE_ACCN:ACCN_ID',
  `PTX_PAYER_BANK_ACCN` varchar(255) DEFAULT NULL COMMENT 'PAYER BANK ACCOUNT NUMBER',
  `PTX_PAYEE` varchar(35) DEFAULT NULL COMMENT 'PAYEE - REFERENCES T_CORE_ACCN:ACCN_ID',
  `PTX_PAYEE_BANK_ACCN` varchar(255) DEFAULT NULL COMMENT 'PAYER BANK ACCOUNT NUMBER',
  `PTX_AMOUNT` decimal(15,2) DEFAULT '0.00' COMMENT 'PAYMENT AMOUNT - 12,0000',
  `PTX_CCY` varchar(3) DEFAULT NULL COMMENT 'CURRENCY  - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `PTX_BANK_REF` varchar(255) DEFAULT NULL COMMENT 'BANK REFERENCE NUMBER - VA',
  `PTX_PAYMENT_STATE` varchar(35) DEFAULT NULL COMMENT 'PAYMENT STATE - SUCCESS : FAIL : NEW',
  `PTX_STATUS` char(1) DEFAULT NULL COMMENT 'RECORD STATUS - A : I',
  `PTX_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `PTX_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `PTX_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `PTX_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`PTX_ID`),
  KEY `FK_CK_PAYMENT_TXN_CK_MST_PAYMENT_TYPE` (`PTX_TYPE`),
  KEY `FK_CK_PAYMENT_TXN_CK_MST_SERVICE_TYPE` (`PTX_SVC`),
  KEY `FK_CK_PAYMENT_TXN_CORE_ACCN1` (`PTX_PAYER`),
  KEY `FK_CK_PAYMENT_TXN_CORE_ACCN2` (`PTX_PAYEE`),
  KEY `FK_CK_PAYMENT_TXN_MST_CCY` (`PTX_CCY`),
  CONSTRAINT `FK_CK_PAYMENT_TXN_CK_MST_PAYMENT_TYPE` FOREIGN KEY (`PTX_TYPE`) REFERENCES `T_CK_MST_PAYMENT_TYPE` (`PTY_ID`),
  CONSTRAINT `FK_CK_PAYMENT_TXN_CK_MST_SERVICE_TYPE` FOREIGN KEY (`PTX_SVC`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),
  CONSTRAINT `FK_CK_PAYMENT_TXN_CORE_ACCN1` FOREIGN KEY (`PTX_PAYER`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_PAYMENT_TXN_CORE_ACCN2` FOREIGN KEY (`PTX_PAYEE`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_PAYMENT_TXN_MST_CCY` FOREIGN KEY (`PTX_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='PAYMENT TXN TABLE';


CREATE TABLE `T_CK_PAYMENT_TXN_INVOICE` (
  `PTI_ID` varchar(35) NOT NULL COMMENT 'PAYMENT TRANSACTION INVOCE REF ID - UUID',  
  `PTI_TXN_ID` varchar(35) NOT NULL COMMENT 'PAYMENT TXN - REFERENCE T_CK_PAYMENT_TXN:PTX_ID',
  `PTI_INV_ID` varchar(35) NOT NULL COMMENT 'PAYMENT TXN INVOICE ID',
  `PTI_STATUS` char(1) DEFAULT NULL COMMENT 'RECORD STATUS - A : I',
  `PTI_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `PTI_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `PTI_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `PTI_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`PTI_ID`),
  CONSTRAINT `FK_CK_PAYMENT_TXN_INVOICE_CK_PAYMENT_TXN` FOREIGN KEY (`PTI_TXN_ID`) REFERENCES `T_CK_PAYMENT_TXN` (`PTX_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='PAYMENT TXN INVOICE REFERENCE';


/** 2022-12-06 Bill - added new tables for base DO */
CREATE TABLE `T_CK_DO` (
  `DO_ID` varchar(35) NOT NULL COMMENT 'DO IMPORT ID - UUID',
  `DO_SHIPMENT_TYPE` varchar(35) NOT NULL COMMENT 'DO SHIPMENT TYPE - REFERENCES T_CK_MST_SHIPMENT_TYPE:SHT_ID',
  `DO_NO` varchar(255) DEFAULT NULL COMMENT 'DO NUMBER',
  `DO_VESSEL_NO` varchar(255) DEFAULT NULL COMMENT 'DO VESSEL OFFICAL NO (VON) - CG002972',
  `DO_VESSEL_NAME` varchar(255) DEFAULT NULL COMMENT 'DO VESSEL NAME - EVERGREEN TERESA',
  `DO_VESSEL_ETA` datetime DEFAULT NULL COMMENT 'DO VESSEL ESTIMATED ARRIVAL TIME - 20201001',
  `DO_VESSEL_ATA` datetime DEFAULT NULL COMMENT 'DO VESSEL ACTUAL ARRIVAL TIME - 20201001 00:00:00',
  `DO_VESSEL_ETD` datetime DEFAULT NULL COMMENT 'DO VESSEL ESTIMATED DEPARTURE TIME - 20201001',
  `DO_VESSEL_ATD` datetime DEFAULT NULL COMMENT 'DO VESSEL ACTUAL DEPARTURE TIME - 20201001 00:00:00',
  `DO_VOYAGE_NO` varchar(255) DEFAULT NULL COMMENT 'DO VOYAGE NO - V.284',
  `DO_TERMINAL` varchar(255) DEFAULT NULL COMMENT 'DO TERMINAL OF DISCHARGE',
  `DO_POL` varchar(5) DEFAULT NULL COMMENT 'DO PORT OF LOADING - REFERENCE T_MST_PORT:PORT_CODE',
  `DO_POD` varchar(5) DEFAULT NULL COMMENT 'DO PORT OF DISCHARGE - REFERENCE T_MST_PORT:PORT_CODE',
  `DO_NO_CNT` smallint DEFAULT '0' COMMENT 'DO NUMBER OF CONTAINERS',
  `DO_STATE` varchar(35) DEFAULT NULL COMMENT 'DO STATE - REFERENCE T_CK_MST_DO_STATE:DOST_ID',
  `DO_DT_DO_SUBMIT` datetime DEFAULT NULL COMMENT 'DO SUBMITTED DATE',
  `DO_DT_DO_CLAIM` datetime DEFAULT NULL COMMENT 'DO CLAIM DATE',
  `DO_DO` varchar(1024) DEFAULT NULL COMMENT 'DO ATTACHMENT PATH REFERENCE FROM SYS_PARAM SETUP',
  `DO_STATUS` char(1) DEFAULT NULL COMMENT 'DO STATUS - A : I ',
  `DO_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `DO_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `DO_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `DO_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`DO_ID`),
  KEY `FK_CK_DO_CK_MST_DO_STATE` (`DO_STATE`),
  KEY `FK_CK_DO_CK_MST_SHIPMENT_TYPE` (`DO_SHIPMENT_TYPE`),
  CONSTRAINT `FK_CK_DO_CK_MST_DOI_STATE` FOREIGN KEY (`DO_STATE`) REFERENCES `T_CK_MST_DO_STATE` (`DOST_ID`),  
  CONSTRAINT `FK_CK_DO_CK_MST_SHIPMENT_TYPE` FOREIGN KEY (`DO_SHIPMENT_TYPE`) REFERENCES `T_CK_MST_SHIPMENT_TYPE` (`SHT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DELIVERY ORDER TABLE';

-- DELIVERY ORDER PARTY -------------------------------------------------------------------------------
CREATE TABLE `T_CK_MST_DO_PARTY_TYPE` (
  `DOPT_ID` varchar(35) NOT NULL COMMENT 'DO PARTY TYPE ID - CONSINGEE : NOTIFY',
  `DOPT_NAME` varchar(100) NOT NULL COMMENT 'DO PARTY TYPE NAME',
  `DOPT_DESC` varchar(255) DEFAULT NULL COMMENT 'DO PARTY TYPE DESCRIPTION',
  `DOPT_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'DO PARTY TYPE  DESCRIPTION OTHER LANGUAGE',
  `DOPT_STATUS` char(1) DEFAULT NULL COMMENT 'DO PARTY TYPE STATUS',
  `DOPT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `DOPT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `DOPT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `DOPT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`DOPT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DO PARTY TYPE TABLE';

INSERT INTO `T_CK_MST_DO_PARTY_TYPE` (`DOPT_ID`,`DOPT_NAME`,`DOPT_DESC`,`DOPT_DESC_OTH`,`DOPT_STATUS`,`DOPT_DT_CREATE`,`DOPT_UID_CREATE`,`DOPT_DT_LUPD`,`DOPT_UID_LUPD`) VALUES ("CONSIGNEE", "CONSIGNEE", "CONSIGNEE", "CONSIGNEE", 'A', "2022-10-01 00:00:00", "SYS", "2022-10-01 00:00:00", "SYS");
INSERT INTO `T_CK_MST_DO_PARTY_TYPE` (`DOPT_ID`,`DOPT_NAME`,`DOPT_DESC`,`DOPT_DESC_OTH`,`DOPT_STATUS`,`DOPT_DT_CREATE`,`DOPT_UID_CREATE`, `DOPT_DT_LUPD`,`DOPT_UID_LUPD`) VALUES ("NOTIFY", "NOTIFY", "NOTIFY", "NOTIFY", 'A', "2022-10-01 00:00:00", "SYS", "2022-10-01 00:00:00", "SYS");

CREATE TABLE `T_CK_DO_PARTY` (
  `DOP_DO_ID` varchar(35) NOT NULL COMMENT 'DO PARTY DO ID - REFERENCES T_CK_DO:DO_ID',
  `DOP_TYPE` varchar(35) NOT NULL COMMENT 'DO PARTY TYPE - REFERENCES T_CK_MST_DO_PARTY_TYPE:DOPT_ID',
  `DOP_USR` varchar(35) DEFAULT NULL COMMENT 'DO CONSIGNEE USER DETALS - REFERENCE T_CORE_USR:USR_UID',
  `DO_ACCN` varchar(35) DEFAULT NULL COMMENT 'DO CONSIGNEE ACCN DETALS - REFERENCE T_CORE_ACCN:ACCN_ID',
  `DOP_STATUS` char(1) DEFAULT NULL COMMENT 'DO PARTY TYPE STATUS',
  `DOP_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `DOP_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `DOP_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `DOP_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`DOP_DO_ID`, `DOP_TYPE`),
  CONSTRAINT `FK_CK_DO_PARTY_CK_DO` FOREIGN KEY (`DOP_DO_ID`) REFERENCES `T_CK_DO` (`DO_ID`),
  CONSTRAINT `FK_CK_DO_PARTY_CK_MST_DO_PARTY_TYPE` FOREIGN KEY (`DOP_TYPE`) REFERENCES `T_CK_MST_DO_PARTY_TYPE` (`DOPT_ID`),
  CONSTRAINT `FK_CK_DO_PARTY_CORE_USR` FOREIGN KEY (`DOP_USR`) REFERENCES `T_CORE_USR` (`USR_UID`),
  CONSTRAINT `FK_CK_DO_PARTY_CORE_ACCN` FOREIGN KEY (`DO_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DELIVERY ORDER PARTY TABLE';

-- DELIVERY INVOICE -------------------------------------------------------------------------------
CREATE TABLE `T_CK_MST_INVOICE_TYPE` (
  `INVT_ID` varchar(35) NOT NULL COMMENT 'INVOICE TYPE ID - ILC : IMF : PLF : DCF',
  `INVT_NAME` varchar(100) NOT NULL COMMENT 'INVOICE TYPE NAME',
  `INVT_DESC` varchar(255) DEFAULT NULL COMMENT 'INVOICE TYPE DESCRIPTION',
  `INVT_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'INVOICE TYPE  DESCRIPTION OTHER LANGUAGE',
  `INVT_STATUS` char(1) DEFAULT NULL COMMENT 'INVOICE TYPE STATUS',
  `INVT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `INVT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `INVT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `INVT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`INVT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='INVOICE TYPE TABLE';

INSERT INTO `T_CK_MST_INVOICE_TYPE` (`INVT_ID`, `INVT_NAME`, `INVT_DESC`, `INVT_DESC_OTH`, `INVT_STATUS`, `INVT_DT_CREATE`, `INVT_UID_CREATE`, `INVT_DT_LUPD`, `INVT_UID_LUPD`) VALUES ("I-ILC", "INVOICE IMPORT LOCAL CHARGE", "INVOICE IMPORT LOCAL CHARGE", "INVOICE IMPORT LOCAL CHARGE", 'A', "2022-10-01 00:00:00", "SYS", "2022-10-01 00:00:00", "SYS");
INSERT INTO `T_CK_MST_INVOICE_TYPE` (`INVT_ID`, `INVT_NAME`, `INVT_DESC`, `INVT_DESC_OTH`, `INVT_STATUS`, `INVT_DT_CREATE`, `INVT_UID_CREATE`, `INVT_DT_LUPD`, `INVT_UID_LUPD`) VALUES ("I-IMF", "INVOICE IMPORT MANIFEST", "INVOICE IMPORT MANIFEST", "INVOICE IMPORT MANIFEST", 'A', "2022-10-01 00:00:00", "SYS", "2022-10-01 00:00:00", "SYS");
INSERT INTO `T_CK_MST_INVOICE_TYPE` (`INVT_ID`, `INVT_NAME`, `INVT_DESC`, `INVT_DESC_OTH`, `INVT_STATUS`, `INVT_DT_CREATE`, `INVT_UID_CREATE`, `INVT_DT_LUPD`, `INVT_UID_LUPD`) VALUES ("I-PLF", "INVOICE PLATFORM FEE", "INVOICE PLATFORM FEE", "INVOICE PLATFORM FEE", 'A', "2022-10-01 00:00:00", "SYS", "2022-10-01 00:00:00", "SYS");
INSERT INTO `T_CK_MST_INVOICE_TYPE` (`INVT_ID`, `INVT_NAME`, `INVT_DESC`, `INVT_DESC_OTH`, `INVT_STATUS`, `INVT_DT_CREATE`, `INVT_UID_CREATE`, `INVT_DT_LUPD`, `INVT_UID_LUPD`) VALUES ("I-DC", "INVOICE DIGITAL CERTIFICATE", "INVOICE PLATFORM FEE", "INVOICE PLATFORM FEE", 'A', "2022-10-01 00:00:00", "SYS", "2022-10-01 00:00:00", "SYS");

CREATE TABLE `T_CK_DO_INVOICE` (
  `INV_ID` varchar(35) NOT NULL COMMENT 'INVOICE ID - UUID',
  `INV_DO_ID` varchar(35) NOT NULL COMMENT 'DO RELATED TO THE INVOICE - REFERECNES T_CK_DO:DO_ID',
  `INV_NO` varchar(255) NOT NULL COMMENT 'INVOICE NUMBER - IMF2001535',
  `INV_TAX_NO` varchar(255) DEFAULT NULL COMMENT 'TAX INVOICE NUMBER FAKTUR PAJAK- 010.003-22 103351310',
  `INV_TYPE` varchar(35) NOT NULL COMMENT 'INVOICE TYPE - REFERECNES T_CK_MST_INVOICE_TYPE:INVT_ID',
  `INV_AMOUNT` decimal(15,2) DEFAULT '0.00' COMMENT 'INVOICE AMOUNT BEFORE TAX - 12,0000',
  `INV_TAX` decimal(15,2) DEFAULT '0.00' COMMENT 'INVOICE TAX AMOUNT - 12,0000',
  `INV_CCY` varchar(3) DEFAULT NULL COMMENT 'INVOICE CURRENCY  - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `INV_DOC` varchar(1024) DEFAULT NULL COMMENT 'INVOICE INVOICE PATH REFERENCE FROM SYS_PARAM SETUP',
  `INV_STATUS` char(1) DEFAULT NULL COMMENT 'INVOICE TYPE STATUS',
  `INV_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `INV_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `INV_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `INV_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',    
  PRIMARY KEY (`INV_ID`),
  CONSTRAINT `FK_CK_DOI_INVOICE_CK_DO` FOREIGN KEY (`INV_DO_ID`) REFERENCES `T_CK_DO` (`DO_ID`),
  CONSTRAINT `FK_CK_DOI_INVOICE_CK_MST_INVOICE_TYPE` FOREIGN KEY (`INV_TYPE`) REFERENCES `T_CK_MST_INVOICE_TYPE` (`INVT_ID`),
  CONSTRAINT `FK_CK_DOI_INVOICE_MST_CCY` FOREIGN KEY (`INV_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DO INVOICE TYPE TABLE'; 


ALTER TABLE `clickargo`.`T_CK_DO_INVOICE` 
ADD COLUMN `INV_DO_REGION` VARCHAR(255) NULL DEFAULT NULL AFTER `INV_DO_ID`;



/** ------------------------ DO NOT WRITE BELOW THIS LINE (FOR NEW SCRIPTS PLEASE ADD IN db_scripts_v0.2.sql) THANK YOU!---------------------*/

