
drop table if exists T_CK_TAX_SEQ;

CREATE TABLE `T_CK_TAX_SEQ` (
  `TS_ID` varchar(35) NOT NULL,
  `TS_SERVICE` varchar(35) NOT NULL COMMENT 'CLICKARGO SERVICE - REFERENCES T_CK_MST_SERVICE_TYPE:SVCT_ID',
  `TS_PREFIX` varchar(35) NOT NULL COMMENT 'LIKE: 010.007.23. 010.009.23.',
  `TS_RANGE_BEGIN` bigint NOT NULL COMMENT 'LIKE: 899000000',
  `TS_RANGE_END` bigint NOT NULL COMMENT 'LIKE: 89009999',
  `TS_RANGE_CURRENT` bigint NOT NULL COMMENT 'LIKE: 89001234',
  `TS_RANGE_FORMAT` varchar(35) NOT NULL COMMENT '%8d',
  `TS_STATUS` char(1) DEFAULT 'A' COMMENT 'E: expired, I: inactive, A:Active',
  `TS_DT_CREATE` datetime DEFAULT NULL,
  `TS_UID_CREATE` varchar(35) DEFAULT NULL,
  `TS_DT_LUPD` datetime DEFAULT NULL,
  `TS_UID_LUPD` varchar(35) DEFAULT NULL,
  PRIMARY KEY (`TS_ID`),
  KEY `FK_CK_TAX_SEQ_CK_MST_SERVICE_TYPE` (`TS_SERVICE`),
  CONSTRAINT `FK_CK_TAX_SEQ_CK_MST_SERVICE_TYPE` FOREIGN KEY (`TS_SERVICE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

ALTER TABLE `clickargo2`.`T_CK_TAX_REPORT` 
ADD COLUMN `TR_SERVICE` VARCHAR(45) NULL AFTER `TR_ID`;

update clickargo2.T_CK_TAX_REPORT 
	set TR_SERVICE = 'CLICTRUCK' 
	where TR_SERVICE is null;

ALTER TABLE `clickargo2`.`T_CK_TAX_INVOICE` 
ADD UNIQUE INDEX `IDX_CK_TAX_INVOICE_TI_NO` (`TI_NO` ASC) VISIBLE;

INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) 
VALUES ('CLICARGO_ATTCH_BASE_LOCATION', '/home/vcc/appAttachments/', 'BASE ATTACHMENT FOR ACCOUNTS RELATED FILES', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

-- 
-- ALTER TABLE `clickargo2`.`T_CK_DO_EXT` 
-- ADD COLUMN `DOX_INV_PLF_TAX_NO` VARCHAR(45) NULL AFTER `DOX_INV_PLF_DOC`;

-- ALTER TABLE `clickargo2`.`T_CK_DO_EXT` 
-- ADD UNIQUE INDEX `IDX_CK_DOX_INV_PLF_TAX_NO` (`DOX_INV_PLF_TAX_NO` ASC) VISIBLE;

ALTER TABLE `clickargo2`.`T_CK_TAX_INVOICE` 
ADD COLUMN `TI_TYPE` VARCHAR(45) NULL COMMENT 'DO or DO-EXT' AFTER `TI_SERVICE`;

ALTER TABLE `clickargo2`.`T_CK_DO_EXT` 
ADD COLUMN `DOX_INV_ADM_DOC` VARCHAR(1024) NULL AFTER `DOX_INV_DMG_DT_ISSUED`;

ALTER TABLE `clickargo2`.`T_CK_DO_EXT` 
ADD COLUMN `DOX_INV_ADM_DT_ISSUED` VARCHAR(1024) NULL AFTER `DOX_INV_ADM_DOC`;

ALTER TABLE `clickargo2`.`T_CK_DO_EXT` 
ADD COLUMN  `DOX_INV_DMG_DOC` varchar(1024) DEFAULT NULL COMMENT 'EXTENSION DO DEMURAGE PDF PATH REFERENCE FROM SYS_PARAM SETUP' AFTER DOX_DT_ISSUED;

ALTER TABLE `clickargo2`.`T_CK_DO_EXT` 
ADD COLUMN  `DOX_INV_DMG_NO` varchar(255) DEFAULT NULL COMMENT 'EXTENSION DO DEMURAGE INVOICE NO' AFTER DOX_INV_DMG_DOC;

ALTER TABLE `clickargo2`.`T_CK_DO_EXT` 
ADD COLUMN  `DOX_INV_DMG_DT_ISSUED` datetime DEFAULT NULL COMMENT 'EXTENSION DO DENURAGE INVOICE ISSUED DATE' AFTER DOX_INV_DMG_NO;

ALTER TABLE `clickargo2`.`T_CK_DO_EXT` 
ADD COLUMN  `DOX_INV_ADM_DOC` varchar(1024) DEFAULT NULL COMMENT 'EXTENSION DO ADMINISTRATION PDF PATH REFERENCE FROM SYS_PARAM SETUP' AFTER DOX_INV_DMG_DT_ISSUED;

ALTER TABLE `clickargo2`.`T_CK_DO_EXT` 
ADD COLUMN  `DOX_INV_ADM_NO` varchar(255) DEFAULT NULL COMMENT 'EXTENSION DO ADMINISTRATION INVOICE NO' AFTER DOX_INV_ADM_DOC;

ALTER TABLE `clickargo2`.`T_CK_DO_EXT` 
ADD COLUMN  `DOX_INV_ADM_DT_ISSUED` datetime DEFAULT NULL COMMENT 'EXTENSION DO ADMINISTRATION INVOICE ISSUED DATE' AFTER DOX_INV_ADM_NO;


-- --

INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD) 
 VALUES('CKDO_MA_030400','CKDO','','','Tax','Tax','30400','/manage/tax',NULL,'CKDO_MA_030000','A',NOW(),'SYS',NOW(),'SYS');

INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  
VALUES('CKDO_MA_030500','CKDO','','','SAGE Integration','SAGE Integration','30500','/opadmin/sageintegrations',NULL,'CKDO_MA_030000','A',NOW(),'SYS',NOW(),'SYS');

INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) 
VALUES ('PMDO030400', 'N', 'CKDO', NULL, 'M', NULL, NULL, 'CKDO_MA_030400', 'Tax', 'Tax','Tax','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');

INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) 
VALUES ('PMDO030500', 'N', 'CKDO', NULL, 'M', NULL, NULL, 'CKDO_MA_030500', 'SAGE Integration', 'SAGE Integration','SAGE Integration','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');


INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) 
VALUES ('CKDO', 'ADMIN', 'PMDO030400', 'A', NOW(), 'SYS');

INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) 
VALUES ('CKDO', 'ADMIN', 'PMDO030500', 'A', NOW(), 'SYS');


-- 
INSERT INTO `clickargo2`.`T_CK_TAX_SEQ` (TS_ID, TS_SERVICE, TS_PREFIX, TS_RANGE_BEGIN, TS_RANGE_END, TS_RANGE_CURRENT, TS_RANGE_FORMAT, TS_STATUS, TS_DT_CREATE, TS_UID_CREATE) 
VALUES ('TXSEQ1','CLICDO', '010.002-24.', '5520345', '5525344', '5520345', '%08d', 'A', '2023-12-31 21:07:16', 'GLI_U001');

UPDATE `clickargo2`.`T_CK_CT_SAGE_TAX` SET `ST_RANGE_END` = '5520344' 
WHERE (`ST_ID` = 'TXSEQ240110060063571') and ST_RANGE_END = '5525344' ;

-- Patch production data

INSERT INTO `clickargo2`.`T_CK_DO_PAYMENT` (`DOP_ID`, `DOP_PAYMENT_TXN`, `DOP_JOB_TYPE`, `DOP_JOB`, `DOP_ITEM`, `DOP_QTY`, `DOP_CCY`, `DOP_AMOUNT`, `DOP_REF`, `DOP_INV_TYPE`, `DOP_INV_NO`, `DOP_ATTACH`, `DOP_STATE`, `DOP_STATUS`, `DOP_DT_CREATE`, `DOP_UID_CREATE`, `DOP_DT_LUPD`, `DOP_UID_LUPD`) 
VALUES ('DPFF1350351358762832000', 'TXNDO13505748293257583', 'IDC', 'DOJF13497427357207001', 'MEDUVJ268758 - INVOICE IMPORT LOCAL CHARGE (DOJF13497427357207001)', '1', 'IDR', '1106000.00', 'CKDOINV240705153635673', 'I-ILC', 'ILC486822024IDN_P', NULL, 'COM', 'A', '2024-07-05 17:19:59', 'CKU01441', '2024-07-05 17:57:14', 'SYS');

INSERT INTO `clickargo2`.`T_CK_DO_PAYMENT` (`DOP_ID`, `DOP_PAYMENT_TXN`, `DOP_JOB_TYPE`, `DOP_JOB`, `DOP_ITEM`, `DOP_QTY`, `DOP_CCY`, `DOP_AMOUNT`, `DOP_REF`, `DOP_INV_TYPE`, `DOP_INV_NO`, `DOP_ATTACH`, `DOP_STATE`, `DOP_STATUS`, `DOP_DT_CREATE`, `DOP_UID_CREATE`, `DOP_DT_LUPD`, `DOP_UID_LUPD`) 
VALUES ('DPFF1350351430717541000', 'TXNDO13505748293257583', 'IDC', 'DOJF13497427357207001', 'MEDUVJ303894 - INVOICE IMPORT LOCAL CHARGE (DOJF13497427357207001)', '1', 'IDR', '1106000.00', 'CKDOINV240705153672057', 'I-ILC', 'ILC486832024IDN_P', NULL, 'COM', 'A', '2024-07-05 17:20:00', 'CKU01441', '2024-07-05 17:57:14', 'SYS');
