package com.guudint.clickargo.container.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCnt generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CNT")
public class TCkCnt extends COAbstractEntity<TCkCnt> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -2009135751913417340L;
	
	// Attributes
	/////////////
	private String cntId;
	private String cntNo;
	private String cntIsoCode;
	private String cntImoCode;
	private String cntType;
	private String cntSize;
	private Integer cntHeight;
	private Integer cntWeight;
	private Integer cntBruto;
	private Character cntFullEmptyIndr;
	private Character cntImdg;
	private String cntImdgUnNo;
	private Byte cntImdgImdgClass;
	private String cntImdgValue;
	private Character cntRfrIndr;
	private Short cntRfrRequiredVoltage;
	private BigDecimal cntRfrRequiredTemperature;
	private Date cntRfrStartPlug;
	private Date cntRfrStopPlug;
	private Integer cntOogTop;
	private Integer cntOogLeft;
	private Integer cntOogRight;
	private String cntSealNo;
	private Date cntStacking;
	private Date cntGateIn;
	private Date cntGateOut;
	private String cntLocation;
	private String cntVesselNo;
	private String cntVesselName;
	private String cntVoyageNo;
	private Date cntVesselEta;
	private Date cntVesselAta;
	private Date cntVesselEtd;
	private Date cntVesselAtd;
	private String cntPod;
	private String cntPol;
	private Date cntDtDischarge;
	private Date cntDtLoad;
	private Character cntDangerousGood;
	private String cntMarksNo;
	private String cntNoPackages;
	private String cntDescription;
	private String cntOwner;
	private String cntTaxid;
	private String cntSender;
	private String cntForwarder;
	private String cntCcacNo;
	private String cntBlAwbNo;
	private String cntStatusCustoms;
	private String cntStatusQuarantine;
	private Date cntValidDate;
	private Date cntDoLastPaidThru;
	private String cntRemarks;
	private Character cntStatus;
	private Date cntDtCreate;
	private String cntUidCreate;
	private Date cntDtLupd;
	private String cntUidLupd;
	
	// Constructors
	///////////////
	public TCkCnt() {
	}

	/**
	 * @param cntId
	 * @param cntNo
	 */
	public TCkCnt(String cntId, String cntNo) {
		this.cntId = cntId;
		this.cntNo = cntNo;
	}

	/**
	 * 
	 * @param cntId
	 * @param cntNo
	 * @param cntIsoCode
	 * @param cntImoCode
	 * @param cntType
	 * @param cntSize
	 * @param cntHeight
	 * @param cntWeight
	 * @param cntBruto
	 * @param cntFullEmptyIndr
	 * @param cntImdg
	 * @param cntImdgUnNo
	 * @param cntImdgImdgClass
	 * @param cntImdgValue
	 * @param cntRfrIndr
	 * @param cntRfrRequiredVoltage
	 * @param cntRfrRequiredTemperature
	 * @param cntRfrStartPlug
	 * @param cntRfrStopPlug
	 * @param cntOogTop
	 * @param cntOogLeft
	 * @param cntOogRight
	 * @param cntSealNo
	 * @param cntStacking
	 * @param cntGateIn
	 * @param cntGateOut
	 * @param cntLocation
	 * @param cntVesselNo
	 * @param cntVesselName
	 * @param cntVoyageNo
	 * @param cntVesselEta
	 * @param cntVesselAta
	 * @param cntVesselEtd
	 * @param cntVesselAtd
	 * @param cntPod
	 * @param cntPol
	 * @param cntDtDischarge
	 * @param cntDtLoad
	 * @param cntDangerousGood
	 * @param cntMarksNo
	 * @param cntNoPackages
	 * @param cntDescription
	 * @param cntOwner
	 * @param cntTaxid
	 * @param cntSender
	 * @param cntForwarder
	 * @param cntCcacNo
	 * @param cntBlAwbNo
	 * @param cntStatusCustoms
	 * @param cntStatusQuarantine
	 * @param cntValidDate
	 * @param cntDoLastPaidThru
	 * @param cntRemarks
	 * @param cntStatus
	 * @param cntDtCreate
	 * @param cntUidCreate
	 * @param cntDtLupd
	 * @param cntUidLupd
	 */
	public TCkCnt(String cntId, String cntNo, String cntIsoCode, String cntImoCode, String cntType, String cntSize,
			Integer cntHeight, Integer cntWeight, Integer cntBruto, Character cntFullEmptyIndr, Character cntImdg,
			String cntImdgUnNo, Byte cntImdgImdgClass, String cntImdgValue, Character cntRfrIndr,
			Short cntRfrRequiredVoltage, BigDecimal cntRfrRequiredTemperature, Date cntRfrStartPlug,
			Date cntRfrStopPlug, Integer cntOogTop, Integer cntOogLeft, Integer cntOogRight, String cntSealNo,
			Date cntStacking, Date cntGateIn, Date cntGateOut, String cntLocation, String cntVesselNo,
			String cntVesselName, String cntVoyageNo, Date cntVesselEta, Date cntVesselAta, Date cntVesselEtd,
			Date cntVesselAtd, String cntPod, String cntPol, Date cntDtDischarge, Date cntDtLoad,
			Character cntDangerousGood, String cntMarksNo, String cntNoPackages, String cntDescription, String cntOwner,
			String cntTaxid, String cntSender, String cntForwarder, String cntCcacNo, String cntBlAwbNo,
			String cntStatusCustoms, String cntStatusQuarantine, Date cntValidDate, Date cntDoLastPaidThru, String cntRemarks,
			Character cntStatus, Date cntDtCreate, String cntUidCreate, Date cntDtLupd, String cntUidLupd) {
		this.cntId = cntId;
		this.cntNo = cntNo;
		this.cntIsoCode = cntIsoCode;
		this.cntImoCode = cntImoCode;
		this.cntType = cntType;
		this.cntSize = cntSize;
		this.cntHeight = cntHeight;
		this.cntWeight = cntWeight;
		this.cntBruto = cntBruto;
		this.cntFullEmptyIndr = cntFullEmptyIndr;
		this.cntImdg = cntImdg;
		this.cntImdgUnNo = cntImdgUnNo;
		this.cntImdgImdgClass = cntImdgImdgClass;
		this.cntImdgValue = cntImdgValue;
		this.cntRfrIndr = cntRfrIndr;
		this.cntRfrRequiredVoltage = cntRfrRequiredVoltage;
		this.cntRfrRequiredTemperature = cntRfrRequiredTemperature;
		this.cntRfrStartPlug = cntRfrStartPlug;
		this.cntRfrStopPlug = cntRfrStopPlug;
		this.cntOogTop = cntOogTop;
		this.cntOogLeft = cntOogLeft;
		this.cntOogRight = cntOogRight;
		this.cntSealNo = cntSealNo;
		this.cntStacking = cntStacking;
		this.cntGateIn = cntGateIn;
		this.cntGateOut = cntGateOut;
		this.cntLocation = cntLocation;
		this.cntVesselNo = cntVesselNo;
		this.cntVesselName = cntVesselName;
		this.cntVoyageNo = cntVoyageNo;
		this.cntVesselEta = cntVesselEta;
		this.cntVesselAta = cntVesselAta;
		this.cntVesselEtd = cntVesselEtd;
		this.cntVesselAtd = cntVesselAtd;
		this.cntPod = cntPod;
		this.cntPol = cntPol;
		this.cntDtDischarge = cntDtDischarge;
		this.cntDtLoad = cntDtLoad;
		this.cntDangerousGood = cntDangerousGood;
		this.cntMarksNo = cntMarksNo;
		this.cntNoPackages = cntNoPackages;
		this.cntDescription = cntDescription;
		this.cntOwner = cntOwner;
		this.cntTaxid = cntTaxid;
		this.cntSender = cntSender;
		this.cntForwarder = cntForwarder;
		this.cntCcacNo = cntCcacNo;
		this.cntBlAwbNo = cntBlAwbNo;
		this.cntStatusCustoms = cntStatusCustoms;
		this.cntStatusQuarantine = cntStatusQuarantine;
		this.cntValidDate = cntValidDate;
		this.cntDoLastPaidThru = cntDoLastPaidThru;
		this.cntRemarks = cntRemarks;
		this.cntStatus = cntStatus;
		this.cntDtCreate = cntDtCreate;
		this.cntUidCreate = cntUidCreate;
		this.cntDtLupd = cntDtLupd;
		this.cntUidLupd = cntUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkCnt o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}
	
	// Properties
	//////////////
	@Id
	@Column(name = "CNT_ID", unique = true, nullable = false, length = 35)
	public String getCntId() {
		return this.cntId;
	}

	public void setCntId(String cntId) {
		this.cntId = cntId;
	}

	@Column(name = "CNT_SIZE", length = 35)
	public String getCntSize() {
		return this.cntSize;
	}

	public void setCntSize(String cntSize) {
		this.cntSize = cntSize;
	}

	@Column(name = "CNT_TYPE", length = 35)
	public String getCntType() {
		return this.cntType;
	}

	public void setCntType(String cntType) {
		this.cntType = cntType;
	}

	@Column(name = "CNT_POD", length = 35)
	public String getCntPod() {
		return this.cntPod;
	}

	public void setCntPod(String cntPod) {
		this.cntPod = cntPod;
	}

	@Column(name = "CNT_POL", length = 35)
	public String getCntPol() {
		return this.cntPol;
	}

	public void setCntPol(String cntPol) {
		this.cntPol = cntPol;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNT_DT_DISCHARGE", length = 19)
	public Date getCntDtDischarge() {
		return this.cntDtDischarge;
	}

	public void setCntDtDischarge(Date cntDtDischarge) {
		this.cntDtDischarge = cntDtDischarge;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNT_DT_LOAD", length = 19)
	public Date getCntDtLoad() {
		return this.cntDtLoad;
	}

	public void setCntDtLoad(Date cntDtLoad) {
		this.cntDtLoad = cntDtLoad;
	}

	@Column(name = "CNT_DANGEROUS_GOOD", length = 1)
	public Character getCntDangerousGood() {
		return this.cntDangerousGood;
	}

	public void setCntDangerousGood(Character cntDangerousGood) {
		this.cntDangerousGood = cntDangerousGood;
	}
	
	@Column(name = "CNT_NO", nullable = false)
	public String getCntNo() {
		return this.cntNo;
	}

	public void setCntNo(String cntNo) {
		this.cntNo = cntNo;
	}

	@Column(name = "CNT_ISO_CODE", length = 35)
	public String getCntIsoCode() {
		return this.cntIsoCode;
	}

	public void setCntIsoCode(String cntIsoCode) {
		this.cntIsoCode = cntIsoCode;
	}

	@Column(name = "CNT_IMO_CODE", length = 35)
	public String getCntImoCode() {
		return this.cntImoCode;
	}

	public void setCntImoCode(String cntImoCode) {
		this.cntImoCode = cntImoCode;
	}

	@Column(name = "CNT_HEIGHT")
	public Integer getCntHeight() {
		return this.cntHeight;
	}

	public void setCntHeight(Integer cntHeight) {
		this.cntHeight = cntHeight;
	}

	@Column(name = "CNT_WEIGHT")
	public Integer getCntWeight() {
		return this.cntWeight;
	}

	public void setCntWeight(Integer cntWeight) {
		this.cntWeight = cntWeight;
	}

	@Column(name = "CNT_BRUTO")
	public Integer getCntBruto() {
		return this.cntBruto;
	}

	public void setCntBruto(Integer cntBruto) {
		this.cntBruto = cntBruto;
	}

	@Column(name = "CNT_FULL_EMPTY_INDR", length = 1)
	public Character getCntFullEmptyIndr() {
		return this.cntFullEmptyIndr;
	}

	public void setCntFullEmptyIndr(Character cntFullEmptyIndr) {
		this.cntFullEmptyIndr = cntFullEmptyIndr;
	}

	@Column(name = "CNT_IMDG", length = 1)
	public Character getCntImdg() {
		return this.cntImdg;
	}

	public void setCntImdg(Character cntImdg) {
		this.cntImdg = cntImdg;
	}

	@Column(name = "CNT_IMDG_UN_NO")
	public String getCntImdgUnNo() {
		return this.cntImdgUnNo;
	}

	public void setCntImdgUnNo(String cntImdgUnNo) {
		this.cntImdgUnNo = cntImdgUnNo;
	}

	@Column(name = "CNT_IMDG_IMDG_CLASS")
	public Byte getCntImdgImdgClass() {
		return this.cntImdgImdgClass;
	}

	public void setCntImdgImdgClass(Byte cntImdgImdgClass) {
		this.cntImdgImdgClass = cntImdgImdgClass;
	}

	@Column(name = "CNT_IMDG_VALUE")
	public String getCntImdgValue() {
		return this.cntImdgValue;
	}

	public void setCntImdgValue(String cntImdgValue) {
		this.cntImdgValue = cntImdgValue;
	}

	@Column(name = "CNT_RFR_INDR", length = 1)
	public Character getCntRfrIndr() {
		return this.cntRfrIndr;
	}

	public void setCntRfrIndr(Character cntRfrIndr) {
		this.cntRfrIndr = cntRfrIndr;
	}

	@Column(name = "CNT_RFR_REQUIRED_VOLTAGE")
	public Short getCntRfrRequiredVoltage() {
		return this.cntRfrRequiredVoltage;
	}

	public void setCntRfrRequiredVoltage(Short cntRfrRequiredVoltage) {
		this.cntRfrRequiredVoltage = cntRfrRequiredVoltage;
	}

	@Column(name = "CNT_RFR_REQUIRED_TEMPERATURE", precision = 5)
	public BigDecimal getCntRfrRequiredTemperature() {
		return this.cntRfrRequiredTemperature;
	}

	public void setCntRfrRequiredTemperature(BigDecimal cntRfrRequiredTemperature) {
		this.cntRfrRequiredTemperature = cntRfrRequiredTemperature;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNT_RFR_START_PLUG", length = 19)
	public Date getCntRfrStartPlug() {
		return this.cntRfrStartPlug;
	}

	public void setCntRfrStartPlug(Date cntRfrStartPlug) {
		this.cntRfrStartPlug = cntRfrStartPlug;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNT_RFR_STOP_PLUG", length = 19)
	public Date getCntRfrStopPlug() {
		return this.cntRfrStopPlug;
	}

	public void setCntRfrStopPlug(Date cntRfrStopPlug) {
		this.cntRfrStopPlug = cntRfrStopPlug;
	}

	@Column(name = "CNT_OOG_TOP")
	public Integer getCntOogTop() {
		return this.cntOogTop;
	}

	public void setCntOogTop(Integer cntOogTop) {
		this.cntOogTop = cntOogTop;
	}

	@Column(name = "CNT_OOG_LEFT")
	public Integer getCntOogLeft() {
		return this.cntOogLeft;
	}

	public void setCntOogLeft(Integer cntOogLeft) {
		this.cntOogLeft = cntOogLeft;
	}

	@Column(name = "CNT_OOG_RIGHT")
	public Integer getCntOogRight() {
		return this.cntOogRight;
	}

	public void setCntOogRight(Integer cntOogRight) {
		this.cntOogRight = cntOogRight;
	}

	@Column(name = "CNT_SEAL_NO")
	public String getCntSealNo() {
		return this.cntSealNo;
	}

	public void setCntSealNo(String cntSealNo) {
		this.cntSealNo = cntSealNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNT_STACKING", length = 19)
	public Date getCntStacking() {
		return this.cntStacking;
	}

	public void setCntStacking(Date cntStacking) {
		this.cntStacking = cntStacking;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNT_GATE_IN", length = 19)
	public Date getCntGateIn() {
		return this.cntGateIn;
	}

	public void setCntGateIn(Date cntGateIn) {
		this.cntGateIn = cntGateIn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNT_GATE_OUT", length = 19)
	public Date getCntGateOut() {
		return this.cntGateOut;
	}

	public void setCntGateOut(Date cntGateOut) {
		this.cntGateOut = cntGateOut;
	}

	@Column(name = "CNT_LOCATION")
	public String getCntLocation() {
		return this.cntLocation;
	}

	public void setCntLocation(String cntLocation) {
		this.cntLocation = cntLocation;
	}

	@Column(name = "CNT_VESSEL_NO")
	public String getCntVesselNo() {
		return this.cntVesselNo;
	}

	public void setCntVesselNo(String cntVesselNo) {
		this.cntVesselNo = cntVesselNo;
	}

	@Column(name = "CNT_VESSEL_NAME")
	public String getCntVesselName() {
		return this.cntVesselName;
	}

	public void setCntVesselName(String cntVesselName) {
		this.cntVesselName = cntVesselName;
	}

	@Column(name = "CNT_VOYAGE_NO")
	public String getCntVoyageNo() {
		return this.cntVoyageNo;
	}

	public void setCntVoyageNo(String cntVoyageNo) {
		this.cntVoyageNo = cntVoyageNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNT_VESSEL_ETA", length = 19)
	public Date getCntVesselEta() {
		return this.cntVesselEta;
	}

	public void setCntVesselEta(Date cntVesselEta) {
		this.cntVesselEta = cntVesselEta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNT_VESSEL_ATA", length = 19)
	public Date getCntVesselAta() {
		return this.cntVesselAta;
	}

	public void setCntVesselAta(Date cntVesselAta) {
		this.cntVesselAta = cntVesselAta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNT_VESSEL_ETD", length = 19)
	public Date getCntVesselEtd() {
		return this.cntVesselEtd;
	}

	public void setCntVesselEtd(Date cntVesselEtd) {
		this.cntVesselEtd = cntVesselEtd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNT_VESSEL_ATD", length = 19)
	public Date getCntVesselAtd() {
		return this.cntVesselAtd;
	}

	public void setCntVesselAtd(Date cntVesselAtd) {
		this.cntVesselAtd = cntVesselAtd;
	}

	@Column(name = "CNT_MARKS_NO", length = 1024)
	public String getCntMarksNo() {
		return this.cntMarksNo;
	}

	public void setCntMarksNo(String cntMarksNo) {
		this.cntMarksNo = cntMarksNo;
	}

	@Column(name = "CNT_NO_PACKAGES", length = 1024)
	public String getCntNoPackages() {
		return this.cntNoPackages;
	}

	public void setCntNoPackages(String cntNoPackages) {
		this.cntNoPackages = cntNoPackages;
	}

	@Column(name = "CNT_DESCRIPTION", length = 16777215)
	public String getCntDescription() {
		return this.cntDescription;
	}

	public void setCntDescription(String cntDescription) {
		this.cntDescription = cntDescription;
	}

	@Column(name = "CNT_OWNER")
	public String getCntOwner() {
		return this.cntOwner;
	}

	public void setCntOwner(String cntOwner) {
		this.cntOwner = cntOwner;
	}

	@Column(name = "CNT_TAXID")
	public String getCntTaxid() {
		return this.cntTaxid;
	}

	public void setCntTaxid(String cntTaxid) {
		this.cntTaxid = cntTaxid;
	}

	@Column(name = "CNT_SENDER")
	public String getCntSender() {
		return this.cntSender;
	}

	public void setCntSender(String cntSender) {
		this.cntSender = cntSender;
	}

	@Column(name = "CNT_FORWARDER")
	public String getCntForwarder() {
		return this.cntForwarder;
	}

	public void setCntForwarder(String cntForwarder) {
		this.cntForwarder = cntForwarder;
	}

	@Column(name = "CNT_CCAC_NO")
	public String getCntCcacNo() {
		return this.cntCcacNo;
	}

	public void setCntCcacNo(String cntCcacNo) {
		this.cntCcacNo = cntCcacNo;
	}

	@Column(name = "CNT_BL_AWB_NO")
	public String getCntBlAwbNo() {
		return this.cntBlAwbNo;
	}

	public void setCntBlAwbNo(String cntBlAwbNo) {
		this.cntBlAwbNo = cntBlAwbNo;
	}

	@Column(name = "CNT_STATUS_CUSTOMS")
	public String getCntStatusCustoms() {
		return this.cntStatusCustoms;
	}

	public void setCntStatusCustoms(String cntStatusCustoms) {
		this.cntStatusCustoms = cntStatusCustoms;
	}

	@Column(name = "CNT_STATUS_QUARANTINE")
	public String getCntStatusQuarantine() {
		return this.cntStatusQuarantine;
	}

	public void setCntStatusQuarantine(String cntStatusQuarantine) {
		this.cntStatusQuarantine = cntStatusQuarantine;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNT_VALID_DATE", length = 19)
	public Date getCntValidDate() {
		return this.cntValidDate;
	}

	public void setCntValidDate(Date cntValidDate) {
		this.cntValidDate = cntValidDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNT_DO_LAST_PAID_THRU", length = 19)
	public Date getCntDoLastPaidThru() {
		return this.cntDoLastPaidThru;
	}

	public void setCntDoLastPaidThru(Date cntDoLastPaidThru) {
		this.cntDoLastPaidThru = cntDoLastPaidThru;
	}

	@Column(name = "CNT_REMARKS", length = 512)
	public String getCntRemarks() {
		return this.cntRemarks;
	}

	public void setCntRemarks(String cntRemarks) {
		this.cntRemarks = cntRemarks;
	}

	@Column(name = "CNT_STATUS", length = 1)
	public Character getCntStatus() {
		return this.cntStatus;
	}

	public void setCntStatus(Character cntStatus) {
		this.cntStatus = cntStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNT_DT_CREATE", length = 19)
	public Date getCntDtCreate() {
		return this.cntDtCreate;
	}

	public void setCntDtCreate(Date cntDtCreate) {
		this.cntDtCreate = cntDtCreate;
	}

	@Column(name = "CNT_UID_CREATE", length = 35)
	public String getCntUidCreate() {
		return this.cntUidCreate;
	}

	public void setCntUidCreate(String cntUidCreate) {
		this.cntUidCreate = cntUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNT_DT_LUPD", length = 19)
	public Date getCntDtLupd() {
		return this.cntDtLupd;
	}

	public void setCntDtLupd(Date cntDtLupd) {
		this.cntDtLupd = cntDtLupd;
	}

	@Column(name = "CNT_UID_LUPD", length = 35)
	public String getCntUidLupd() {
		return this.cntUidLupd;
	}

	public void setCntUidLupd(String cntUidLupd) {
		this.cntUidLupd = cntUidLupd;
	}
}
