package com.guudint.clickargo.credit.model;
// Generated 22 Jun 2023, 6:23:51 pm by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.master.model.TCkMstServiceType;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.master.model.TMstCurrency;

/**
 * TCkCreditSummaryMonth generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CREDIT_SUMMARY_MONTH")
public class TCkCreditSummaryMonth extends COAbstractEntity<TCkCreditSummaryMonth> {

	private static final long serialVersionUID = -4333282862578003346L;
	private TCkCreditSummaryMonthId id;
	private TCkMstServiceType TCkMstServiceType;
	private TCoreAccn TCoreAccn;
	private TMstCurrency TMstCurrency;
	private BigDecimal crsmAmt;
	private BigDecimal crsmReserve;
	private BigDecimal crsmUtilized;
	private BigDecimal crsmBalance;
	private Character crsmStatus;
	private Date crsmDtCreate;
	private String crsmUidCreate;
	private Date crsmDtLupd;
	private String crsmUidLupd;

	public TCkCreditSummaryMonth() {
	}

	public TCkCreditSummaryMonth(TCkCreditSummaryMonthId id, TCoreAccn TCoreAccn) {
		this.id = id;
		this.TCoreAccn = TCoreAccn;
	}

	public TCkCreditSummaryMonth(TCkCreditSummaryMonthId id, TCkMstServiceType TCkMstServiceType, TCoreAccn TCoreAccn,
			TMstCurrency TMstCurrency, BigDecimal crsmAmt, BigDecimal crsmReserve, BigDecimal crsmUtilized, BigDecimal crsmBalance,
			Character crsmStatus, Date crsmDtCreate, String crsmUidCreate, Date crsmDtLupd, String crsmUidLupd) {
		this.id = id;
		this.TCkMstServiceType = TCkMstServiceType;
		this.TCoreAccn = TCoreAccn;
		this.TMstCurrency = TMstCurrency;
		this.crsmAmt = crsmAmt;
		this.crsmReserve = crsmReserve;
		this.crsmUtilized = crsmUtilized;
		this.crsmBalance = crsmBalance;
		this.crsmStatus = crsmStatus;
		this.crsmDtCreate = crsmDtCreate;
		this.crsmUidCreate = crsmUidCreate;
		this.crsmDtLupd = crsmDtLupd;
		this.crsmUidLupd = crsmUidLupd;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "crsmCompany", column = @Column(name = "CRSM_COMPANY", nullable = false, length = 35)),
			@AttributeOverride(name = "crsmMonth", column = @Column(name = "CRSM_MONTH", nullable = false, length = 35)) })
	public TCkCreditSummaryMonthId getId() {
		return this.id;
	}

	public void setId(TCkCreditSummaryMonthId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRSM_SERVICE_TYPE")
	public TCkMstServiceType getTCkMstServiceType() {
		return this.TCkMstServiceType;
	}

	public void setTCkMstServiceType(TCkMstServiceType TCkMstServiceType) {
		this.TCkMstServiceType = TCkMstServiceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRSM_COMPANY", nullable = false, insertable = false, updatable = false)
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRSM_CCY")
	public TMstCurrency getTMstCurrency() {
		return this.TMstCurrency;
	}

	public void setTMstCurrency(TMstCurrency TMstCurrency) {
		this.TMstCurrency = TMstCurrency;
	}

	@Column(name = "CRSM_AMT", precision = 15)
	public BigDecimal getCrsmAmt() {
		return this.crsmAmt;
	}

	public void setCrsmAmt(BigDecimal crsmAmt) {
		this.crsmAmt = crsmAmt;
	}

	@Column(name = "CRSM_RESERVE", precision = 15)
	public BigDecimal getCrsmReserve() {
		return this.crsmReserve;
	}

	public void setCrsmReserve(BigDecimal crsmReserve) {
		this.crsmReserve = crsmReserve;
	}

	@Column(name = "CRSM_UTILIZED", precision = 15)
	public BigDecimal getCrsmUtilized() {
		return this.crsmUtilized;
	}

	public void setCrsmUtilized(BigDecimal crsmUtilized) {
		this.crsmUtilized = crsmUtilized;
	}

	@Column(name = "CRSM_BALANCE", precision = 15)
	public BigDecimal getCrsmBalance() {
		return this.crsmBalance;
	}

	public void setCrsmBalance(BigDecimal crsmBalance) {
		this.crsmBalance = crsmBalance;
	}

	@Column(name = "CRSM_STATUS", length = 1)
	public Character getCrsmStatus() {
		return this.crsmStatus;
	}

	public void setCrsmStatus(Character crsmStatus) {
		this.crsmStatus = crsmStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRSM_DT_CREATE", length = 19)
	public Date getCrsmDtCreate() {
		return this.crsmDtCreate;
	}

	public void setCrsmDtCreate(Date crsmDtCreate) {
		this.crsmDtCreate = crsmDtCreate;
	}

	@Column(name = "CRSM_UID_CREATE", length = 35)
	public String getCrsmUidCreate() {
		return this.crsmUidCreate;
	}

	public void setCrsmUidCreate(String crsmUidCreate) {
		this.crsmUidCreate = crsmUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRSM_DT_LUPD", length = 19)
	public Date getCrsmDtLupd() {
		return this.crsmDtLupd;
	}

	public void setCrsmDtLupd(Date crsmDtLupd) {
		this.crsmDtLupd = crsmDtLupd;
	}

	@Column(name = "CRSM_UID_LUPD", length = 35)
	public String getCrsmUidLupd() {
		return this.crsmUidLupd;
	}

	public void setCrsmUidLupd(String crsmUidLupd) {
		this.crsmUidLupd = crsmUidLupd;
	}

	@Override
	public int compareTo(TCkCreditSummaryMonth o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
