package com.guudint.clickargo.credit.model;
// Generated 22 Sep 2023, 4:48:30 pm by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.beans.BeanUtils;

import com.guudint.clickargo.credit.dto.CkCreditRequest;
import com.guudint.clickargo.master.model.TCkMstServiceType;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.master.model.TMstCurrency;

/**
 * TCkCreditRequest generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CREDIT_REQUEST")
public class TCkCreditRequest extends COAbstractEntity<TCkCreditRequest> {

	private static final long serialVersionUID = -2458545758683329927L;
	private String cruId;
	private TCkMstCreditRequestState TCkMstCreditRequestState;
	private TCkMstServiceType TCkMstServiceType;
	private TCoreAccn TCoreAccn;
	private TMstCurrency TMstCurrency;
	private BigDecimal cruAmt;
	private BigDecimal cruTxnCap;
	private Date cruDtStart;
	private Date cruDtEnd;
	private String cruRequester;
	private String cruRemarks;
	private String cruUsrVerify;
	private Date cruDtVerify;
	private String cruUsrApprove;
	private Date cruDtApprove;
	private String cruUsrReject;
	private Date cruDtReject;
	private String cruApproverRemarks;
	private Character cruStatus;
	private Date cruDtCreate;
	private String cruUidCreate;
	private Date cruDtLupd;
	private String cruUidLupd;
	private Date cruDtSubmitted;
	private String cruUidSubmitted;

	public TCkCreditRequest() {
	}

	public TCkCreditRequest(CkCreditRequest ckCreditRequest) {
		BeanUtils.copyProperties(ckCreditRequest, this);
	}

	public TCkCreditRequest(String cruId) {
		this.cruId = cruId;
	}

	public TCkCreditRequest(String cruId, TCkMstCreditRequestState TCkMstCreditRequestState,
			TCkMstServiceType TCkMstServiceType, TCoreAccn TCoreAccn, TMstCurrency TMstCurrency, BigDecimal cruAmt,
			BigDecimal cruTxnCap, Date cruDtStart, Date cruDtEnd, String cruRemarks, String cruUsrVerify, Date cruDtVerify,
			String cruUsrApprove, Date cruDtApprove, String cruUsrReject, Date cruDtReject, String cruApproverRemarks,
			Character cruStatus, Date cruDtCreate, String cruUidCreate, Date cruDtLupd, String cruUidLupd) {
		this.cruId = cruId;
		this.TCkMstCreditRequestState = TCkMstCreditRequestState;
		this.TCkMstServiceType = TCkMstServiceType;
		this.TCoreAccn = TCoreAccn;
		this.TMstCurrency = TMstCurrency;
		this.cruAmt = cruAmt;
		this.cruTxnCap = cruTxnCap;
		this.cruDtStart = cruDtStart;
		this.cruDtEnd = cruDtEnd;
		this.cruRemarks = cruRemarks;
		this.cruUsrVerify = cruUsrVerify;
		this.cruDtVerify = cruDtVerify;
		this.cruUsrApprove = cruUsrApprove;
		this.cruDtApprove = cruDtApprove;
		this.cruUsrReject = cruUsrReject;
		this.cruDtReject = cruDtReject;
		this.cruApproverRemarks = cruApproverRemarks;
		this.cruStatus = cruStatus;
		this.cruDtCreate = cruDtCreate;
		this.cruUidCreate = cruUidCreate;
		this.cruDtLupd = cruDtLupd;
		this.cruUidLupd = cruUidLupd;
	}

	@Id

	@Column(name = "CRU_ID", unique = true, nullable = false, length = 35)
	public String getCruId() {
		return this.cruId;
	}

	public void setCruId(String cruId) {
		this.cruId = cruId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRU_STATE")
	public TCkMstCreditRequestState getTCkMstCreditRequestState() {
		return this.TCkMstCreditRequestState;
	}

	public void setTCkMstCreditRequestState(TCkMstCreditRequestState TCkMstCreditRequestState) {
		this.TCkMstCreditRequestState = TCkMstCreditRequestState;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRU_SERVICE_TYPE")
	public TCkMstServiceType getTCkMstServiceType() {
		return this.TCkMstServiceType;
	}

	public void setTCkMstServiceType(TCkMstServiceType TCkMstServiceType) {
		this.TCkMstServiceType = TCkMstServiceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRU_COMPANY")
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRU_CCY")
	public TMstCurrency getTMstCurrency() {
		return this.TMstCurrency;
	}

	public void setTMstCurrency(TMstCurrency TMstCurrency) {
		this.TMstCurrency = TMstCurrency;
	}

	@Column(name = "CRU_AMT", precision = 15)
	public BigDecimal getCruAmt() {
		return this.cruAmt;
	}

	public void setCruAmt(BigDecimal cruAmt) {
		this.cruAmt = cruAmt;
	}

	@Column(name = "CRU_TXN_CAP", precision = 15)
	public BigDecimal getCruTxnCap() {
		return this.cruTxnCap;
	}

	public void setCruTxnCap(BigDecimal cruTxnCap) {
		this.cruTxnCap = cruTxnCap;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRU_DT_START", length = 19)
	public Date getCruDtStart() {
		return this.cruDtStart;
	}

	public void setCruDtStart(Date cruDtStart) {
		this.cruDtStart = cruDtStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRU_DT_END", length = 19)
	public Date getCruDtEnd() {
		return this.cruDtEnd;
	}

	public void setCruDtEnd(Date cruDtEnd) {
		this.cruDtEnd = cruDtEnd;
	}

	@Column(name = "CRU_REMARKS", length = 16777215)
	public String getCruRemarks() {
		return this.cruRemarks;
	}

	public void setCruRemarks(String cruRemarks) {
		this.cruRemarks = cruRemarks;
	}

	@Column(name = "CRU_USR_VERIFY", length = 35)
	public String getCruUsrVerify() {
		return this.cruUsrVerify;
	}

	public void setCruUsrVerify(String cruUsrVerify) {
		this.cruUsrVerify = cruUsrVerify;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRU_DT_VERIFY", length = 19)
	public Date getCruDtVerify() {
		return this.cruDtVerify;
	}

	public void setCruDtVerify(Date cruDtVerify) {
		this.cruDtVerify = cruDtVerify;
	}

	@Column(name = "CRU_USR_APPROVE", length = 35)
	public String getCruUsrApprove() {
		return this.cruUsrApprove;
	}

	public void setCruUsrApprove(String cruUsrApprove) {
		this.cruUsrApprove = cruUsrApprove;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRU_DT_APPROVE", length = 19)
	public Date getCruDtApprove() {
		return this.cruDtApprove;
	}

	public void setCruDtApprove(Date cruDtApprove) {
		this.cruDtApprove = cruDtApprove;
	}

	@Column(name = "CRU_USR_REJECT", length = 35)
	public String getCruUsrReject() {
		return this.cruUsrReject;
	}

	public void setCruUsrReject(String cruUsrReject) {
		this.cruUsrReject = cruUsrReject;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRU_DT_REJECT", length = 19)
	public Date getCruDtReject() {
		return this.cruDtReject;
	}

	public void setCruDtReject(Date cruDtReject) {
		this.cruDtReject = cruDtReject;
	}

	@Column(name = "CRU_APPROVER_REMARKS", length = 16777215)
	public String getCruApproverRemarks() {
		return this.cruApproverRemarks;
	}

	public void setCruApproverRemarks(String cruApproverRemarks) {
		this.cruApproverRemarks = cruApproverRemarks;
	}

	@Column(name = "CRU_STATUS", length = 1)
	public Character getCruStatus() {
		return this.cruStatus;
	}

	public void setCruStatus(Character cruStatus) {
		this.cruStatus = cruStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRU_DT_CREATE", length = 19)
	public Date getCruDtCreate() {
		return this.cruDtCreate;
	}

	public void setCruDtCreate(Date cruDtCreate) {
		this.cruDtCreate = cruDtCreate;
	}

	@Column(name = "CRU_UID_CREATE", length = 35)
	public String getCruUidCreate() {
		return this.cruUidCreate;
	}

	public void setCruUidCreate(String cruUidCreate) {
		this.cruUidCreate = cruUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRU_DT_LUPD", length = 19)
	public Date getCruDtLupd() {
		return this.cruDtLupd;
	}

	public void setCruDtLupd(Date cruDtLupd) {
		this.cruDtLupd = cruDtLupd;
	}

	@Column(name = "CRU_UID_LUPD", length = 35)
	public String getCruUidLupd() {
		return this.cruUidLupd;
	}

	public void setCruUidLupd(String cruUidLupd) {
		this.cruUidLupd = cruUidLupd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRU_DT_SUBMITTED", length = 19)
	public Date getCruDtSubmitted() {
		return this.cruDtSubmitted;
	}

	public void setCruDtSubmitted(Date cruDtSubmitted) {
		this.cruDtSubmitted = cruDtSubmitted;
	}

	@Column(name = "CRU_UID_SUBMITTED", length = 35)
	public String getCruUidSubmitted() {
		return this.cruUidSubmitted;
	}

	public void setCruUidSubmitted(String cruUidSubmitted) {
		this.cruUidSubmitted = cruUidSubmitted;
	}

	@Column(name = "CRU_REQUESTER", length = 35)
	public String getCruRequester() {
		return this.cruRequester;
	}

	public void setCruRequester(String cruRequester) {
		this.cruRequester = cruRequester;
	}

	@Override
	public int compareTo(TCkCreditRequest o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
