package com.guudint.clickargo.credit.model;
// Generated 22 Jun 2023, 6:23:51 pm by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCreditSummaryMonthId generated by hbm2java
 */
@Embeddable
public class TCkCreditSummaryMonthId extends COAbstractEntity<TCkCreditSummaryMonthId> {

	private static final long serialVersionUID = -6768524600800367672L;
	private String crsmCompany;
	private String crsmMonth;

	public TCkCreditSummaryMonthId() {
	}

	public TCkCreditSummaryMonthId(String crsmCompany, String crsmMonth) {
		this.crsmCompany = crsmCompany;
		this.crsmMonth = crsmMonth;
	}

	@Column(name = "CRSM_COMPANY", nullable = false, length = 35)
	public String getCrsmCompany() {
		return this.crsmCompany;
	}

	public void setCrsmCompany(String crsmCompany) {
		this.crsmCompany = crsmCompany;
	}

	@Column(name = "CRSM_MONTH", nullable = false, length = 35)
	public String getCrsmMonth() {
		return this.crsmMonth;
	}

	public void setCrsmMonth(String crsmMonth) {
		this.crsmMonth = crsmMonth;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TCkCreditSummaryMonthId))
			return false;
		TCkCreditSummaryMonthId castOther = (TCkCreditSummaryMonthId) other;

		return ((this.getCrsmCompany() == castOther.getCrsmCompany()) || (this.getCrsmCompany() != null
				&& castOther.getCrsmCompany() != null && this.getCrsmCompany().equals(castOther.getCrsmCompany())))
				&& ((this.getCrsmMonth() == castOther.getCrsmMonth()) || (this.getCrsmMonth() != null
						&& castOther.getCrsmMonth() != null && this.getCrsmMonth().equals(castOther.getCrsmMonth())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCrsmCompany() == null ? 0 : this.getCrsmCompany().hashCode());
		result = 37 * result + (getCrsmMonth() == null ? 0 : this.getCrsmMonth().hashCode());
		return result;
	}

	@Override
	public int compareTo(TCkCreditSummaryMonthId o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
