package com.guudint.clickargo.credit.model;
// Generated 22 Sep 2023, 4:48:30 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstCreditRequestState generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_CREDIT_REQUEST_STATE")
public class TCkMstCreditRequestState extends COAbstractEntity<TCkMstCreditRequestState> {

	private static final long serialVersionUID = -5815148588038429713L;
	private String stId;
	private String stName;
	private String stDesc;
	private String stDescOth;
	private Character stStatus;
	private Date stDtCreate;
	private String stUidCreate;
	private Date stDtLupd;
	private String stUidLupd;

	public TCkMstCreditRequestState() {
	}

	public TCkMstCreditRequestState(String stId, String stName) {
		this.stId = stId;
		this.stName = stName;
	}

	public TCkMstCreditRequestState(String stId, String stName, String stDesc, String stDescOth, Character stStatus,
			Date stDtCreate, String stUidCreate, Date stDtLupd, String stUidLupd) {
		this.stId = stId;
		this.stName = stName;
		this.stDesc = stDesc;
		this.stDescOth = stDescOth;
		this.stStatus = stStatus;
		this.stDtCreate = stDtCreate;
		this.stUidCreate = stUidCreate;
		this.stDtLupd = stDtLupd;
		this.stUidLupd = stUidLupd;
	}

	@Id
	@Column(name = "ST_ID", unique = true, nullable = false, length = 35)
	public String getStId() {
		return this.stId;
	}

	public void setStId(String stId) {
		this.stId = stId;
	}

	@Column(name = "ST_NAME", nullable = false, length = 100)
	public String getStName() {
		return this.stName;
	}

	public void setStName(String stName) {
		this.stName = stName;
	}

	@Column(name = "ST_DESC")
	public String getStDesc() {
		return this.stDesc;
	}

	public void setStDesc(String stDesc) {
		this.stDesc = stDesc;
	}

	@Column(name = "ST_DESC_OTH", length = 512)
	public String getStDescOth() {
		return this.stDescOth;
	}

	public void setStDescOth(String stDescOth) {
		this.stDescOth = stDescOth;
	}

	@Column(name = "ST_STATUS", length = 1)
	public Character getStStatus() {
		return this.stStatus;
	}

	public void setStStatus(Character stStatus) {
		this.stStatus = stStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ST_DT_CREATE", length = 19)
	public Date getStDtCreate() {
		return this.stDtCreate;
	}

	public void setStDtCreate(Date stDtCreate) {
		this.stDtCreate = stDtCreate;
	}

	@Column(name = "ST_UID_CREATE", length = 35)
	public String getStUidCreate() {
		return this.stUidCreate;
	}

	public void setStUidCreate(String stUidCreate) {
		this.stUidCreate = stUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ST_DT_LUPD", length = 19)
	public Date getStDtLupd() {
		return this.stDtLupd;
	}

	public void setStDtLupd(Date stDtLupd) {
		this.stDtLupd = stDtLupd;
	}

	@Column(name = "ST_UID_LUPD", length = 35)
	public String getStUidLupd() {
		return this.stUidLupd;
	}

	public void setStUidLupd(String stUidLupd) {
		this.stUidLupd = stUidLupd;
	}

	@Override
	public int compareTo(TCkMstCreditRequestState o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}
}
