-- TXN ----------------------------------------------------------------------------
ALTER TABLE T_CK_CP_TXN ADD TXN_NODE varchar(35) NULL COMMENT 'TXN NODE - REFERENCE T_CK_CP_NODE:NODE_ID';
ALTER TABLE T_CK_CP_TXN CHANGE TXN_NODE TXN_NODE varchar(35) NULL COMMENT 'TXN NODE - REFERENCE T_CK_CP_NODE:NODE_ID' AFTER TXN_ID;
ALTER TABLE T_CK_CP_TXN ADD CONSTRAINT FK_CK_CP_TXN_CK_CP_NODE FOREIGN KEY (TXN_NODE) REFERENCES clickargo.T_CK_CP_NODE(NOD_ID);

-- CREATE LOG TRANSACTION CLIENT ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CP_CLIENT_TXN` (
  `TXN_ID` varchar(35) NOT NULL COMMENT 'TRANSACTION ID - UUID',
  `TXN_NODE` varchar(35) DEFAULT NULL COMMENT 'TXN NODE - REFERENCE T_CK_CP_NODE:NOD_ID',
  `TXN_TYPE` varchar(35) DEFAULT NULL COMMENT 'SERVICE TYPE - PROVIDE BY INVOKER',
  `TXN_SERVICE_REF` varchar(35) DEFAULT NULL COMMENT 'TXN REFERENCE - PROVIDED BY INVOKER',
  `TXN_PARAM` mediumtext COMMENT 'REQUEST PARAMS OF TXN - JSON MAP',
  `TXN_REQ` mediumtext COMMENT 'REQUEST BODY OF TXN - JSON OBJECT OF REQUEST BODY',
  `TXN_DT_REQ` datetime DEFAULT NULL COMMENT 'DATE TIME OF TXN REQUEST',
  `TXN_RESP` mediumtext COMMENT 'RESPONSE BODY OF TXN - JSON OBJECT OF RESPONSE BODY',
  `TXN_RESP_CODE` smallint DEFAULT NULL COMMENT 'HTTP RESPONSE CODE',
  `TXN_DT_RESP` datetime DEFAULT NULL COMMENT 'DATE TIME OF TXN RESPONSE',
  `TXN_STATUS` char(1) DEFAULT NULL COMMENT 'RECORD STATUS - A (ACTIVE) : I (INACTIVE)',
  `TXN_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `TXN_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `TXN_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `TXN_UID_LUPD` varchar(35) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`TXN_ID`),
  KEY `FK_CK_CP_TXN_VA_CK_CP_NODE` (`TXN_NODE`),
  CONSTRAINT `FK_CK_CP_TXN_VA_CK_CP_NODE` FOREIGN KEY (`TXN_NODE`) REFERENCES `T_CK_CP_NODE` (`NOD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='LOG TRANSACTION CLIENT';

-- CREATE CREATION VIRTUAL ACCOUNT TABLE ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CP_CREATION_VA` (
  `CRT_ID` varchar(35) NOT NULL COMMENT 'CREATION ID - UUID',
  `CRT_SERVICE_TYPE` varchar(35) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'SERVICE TYPE - REFERENCE T_CK_MST_SERVICE_TYPE:SVCT_ID',
  `CRT_NODE` varchar(35) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'BANK NAME - REFERENCE T_CK_CP_NODE:NOD_ID',
  `CRT_CCY` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'CURRENCY - REFERENCE T_MST_CURRENCY:CCY_CODE',
  `CRT_VIRTUAL_TYPE` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'VIRTUAL ACCOUNT TYPE',
  `CRT_VIRTUAL_NUMBER` varchar(25) NOT NULL COMMENT 'VIRTUAL ACCOUNT NUMBER',
  `CRT_VRITUAL_NAME` varchar(255) DEFAULT NULL COMMENT 'VIRTUAL ACCOUNT NAME',
  `CRT_VIRTUAL_EMAIL` varchar(255) DEFAULT NULL COMMENT 'VIRTUAL ACCOUNT EMAIL',
  `CRT_DT_VIRTUAL_EXPIRED` datetime DEFAULT NULL COMMENT 'VIRTUAL ACCOUNT EXPIRED DATE',
  `CRT_STATUS` char(1) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'CREATION STATUS',
  `CRT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CRT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CRT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CRT_UID_LUPD` varchar(35) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CRT_ID`),
  KEY `FK_CK_CP_CREATION_VA_CK_MST_SERVICE_TYPE` (`CRT_SERVICE_TYPE`),
  KEY `FK_CK_CP_CREATION_VA_MST_CURRENCY` (`CRT_CCY`),
  KEY `FK_CK_CP_CREATION_VA_MST_BANK` (`CRT_NODE`),
  CONSTRAINT `FK_CK_CP_CREATION_VA_CK_CP_NODE` FOREIGN KEY (`CRT_NODE`) REFERENCES `T_CK_CP_NODE` (`NOD_ID`),
  CONSTRAINT `FK_CK_CP_CREATION_VA_CK_MST_SERVICE_TYPE` FOREIGN KEY (`CRT_SERVICE_TYPE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),
  CONSTRAINT `FK_CK_CP_CREATION_VA_MST_CURRENCY` FOREIGN KEY (`CRT_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='CREATION VIRTUAL ACCOUNT TABLE';

-- ASSIGNMENT VIRTUAL ACCOUNT TABLE ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CP_ASSIGNMENT_VA` (
  `ASGN_ID` varchar(35) NOT NULL COMMENT 'ASSIGNMENT ID - UUID',
  `ASGN_VIRTUAL_NUMBER` varchar(35) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'VIRTUAL ACCOUNT ID - REFERENCE T_CK_CP_CREATION_VA:VA_ID',
  `ASGN_REF_NUMBER` varchar(255) DEFAULT NULL COMMENT 'VIRTUAL ACCOUNT REF NUMBER',
  `ASGN_VIRTUAL_AMOUNT` decimal(15,2) DEFAULT NULL COMMENT 'VIRTUAL ACCOUNT AMOUNT',
  `ASGN_VIRTUAL_STATUS` char(1) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'VIRTUAL ACCOUNT STATUS U (UNPAID) : P (PAID) : C (CANCEL)',
  `ASGN_CALLBACK_URI` varchar(255) DEFAULT NULL COMMENT 'CALLBACK URI',
  `ASGN_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `ASGN_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `ASGN_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `ASGN_UID_LUPD` varchar(35) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`ASGN_ID`),
  KEY `FK_CK_CP_ASSIGNMENT_VA_CK_CP_CREATION_VA` (`ASGN_VIRTUAL_NUMBER`),
  CONSTRAINT `FK_CK_CP_ASSIGNMENT_VA_CK_CP_CREATION_VA` FOREIGN KEY (`ASGN_VIRTUAL_NUMBER`) REFERENCES `T_CK_CP_CREATION_VA` (`CRT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='ASSIGNMENT VIRTUAL ACCOUNT TABLE';

-- PAYMENT VIRTUAL ACCOUNT TABLE ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CP_PAYMENT_VA` (
  `PAY_ID` varchar(35) NOT NULL COMMENT 'PAYMENT ID - UUID',
  `PAY_ASSIGNMENT` varchar(35) DEFAULT NULL COMMENT 'PAYMENT ASSIGNMENT - REFERENCE T_CK_CP_ASSIGNMENT_VA:ASGN_ID',
  `PAY_BILL_REF_NUMBER` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'PAYMENT BILLING REFERENCE NUMBER',
  `PAY_REF_NUMBER` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'PAYMENT REFERNCE NUMBER',
  `PAY_BIN_NO` varchar(255) DEFAULT NULL COMMENT 'PAYMENT BUSINESS IDENTIFICATION NUMBER',
  `PAY_BILL_AMOUNT` decimal(15,2) DEFAULT NULL COMMENT 'BILL AMOUNT',
  `PAY_AMOUNT` decimal(15,2) DEFAULT NULL COMMENT 'PAYMENT AMOUNT',
  `PAY_PAYER_ACCOUNT` varchar(255) DEFAULT NULL COMMENT 'PAYER ACCOUNT',
  `PAY_PAYER_BANK` varchar(255) DEFAULT NULL COMMENT 'PAYER BANK NAME',
  `PAY_DESCRIPTION` varchar(500) DEFAULT NULL COMMENT 'PAYMENT DESCRIPTION',
  `PAY_STATUS` char(1) DEFAULT NULL COMMENT 'PAYMENT STATUS',
  `PAY_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `PAY_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `PAY_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `PAY_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`PAY_ID`),
  KEY `FK_CK_CP_PAYMENT_VA_CK_CP_ASSIGNMENT_VA` (`PAY_ASSIGNMENT`),
  CONSTRAINT `FK_CK_CP_PAYMENT_VA_CK_CP_ASSIGNMENT_VA` FOREIGN KEY (`PAY_ASSIGNMENT`) REFERENCES `T_CK_CP_ASSIGNMENT_VA` (`ASGN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='PAYMENT VIRTUAL ACCOUNT TABLE';

-- DISBURSEMENT TABLE ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CP_DISBURSEMENT_VA` (
  `DIS_ID` varchar(35) NOT NULL COMMENT 'DISBURSEMENT ID - UUID',
  `DIS_SERVICE_TYPE` varchar(35) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'SERVICE TYPE - REFERENCE T_CK_MST_SERVICE_TYPE:SVCT_ID',
  `DIS_NODE` varchar(35) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'NODE - REFERENCE T_CK_CP_NODE:NOD_ID',
  `DIS_REF_NUMBER` varchar(255) DEFAULT NULL COMMENT 'USER REFERENCE NUMBER',
  `DIS_VIRTUAL_NUMBER` varchar(35) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'VIRTUAL ACCOUNT ID - REFERENCE T_CK_CP_CREATION_VA:VA_ID',
  `DIS_VIRTUAL_NAME` varchar(255) DEFAULT NULL COMMENT 'VIRTUAL ACCOUNT NAME',
  `DIS_DEBIT_ACCOUNT` varchar(12) DEFAULT NULL COMMENT 'ACCOUNT DEBIT NUMBER',
  `DIS_BILL_AMOUNT` decimal(15,2) DEFAULT NULL COMMENT 'BILL AMOUNT',
  `DIS_PAY_AMOUNT` decimal(15,2) DEFAULT NULL COMMENT 'PAYMENT AMOUNT',
  `DIS_CCY` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'CURRENCY - REFERENCE T_MST_CURRENCY:CCY_CODE',
  `DIS_BILLER_NAME` varchar(100) DEFAULT NULL COMMENT 'BILLER NAME',
  `DIS_COST_CENTER` varchar(4) DEFAULT NULL COMMENT 'COST CENTER',
  `DIS_STATUS` char(1) DEFAULT NULL COMMENT 'DISBURSEMENT STATUS - I (INQUIRY) : P (PAYMENT)',
  `DIS_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `DIS_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `DIS_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `DIS_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  PRIMARY KEY (`DIS_ID`),
  KEY `FK_CK_CP_DISBURSEMENT_VA_CK_CP_CREATION_VA` (`DIS_VIRTUAL_NUMBER`),
  KEY `FK_CK_CP_DISBURSEMENT_VA_CK_CP_NODE` (`DIS_NODE`),
  KEY `FK_CK_CP_DISBURSEMENT_VA_CK_MST_SERVICE_TYPE` (`DIS_SERVICE_TYPE`),
  KEY `FK_CK_CP_DISBURSEMENT_VA_MST_CURRENCY` (`DIS_CCY`),
  CONSTRAINT `FK_CK_CP_DISBURSEMENT_VA_CK_CP_CREATION_VA` FOREIGN KEY (`DIS_VIRTUAL_NUMBER`) REFERENCES `T_CK_CP_CREATION_VA` (`CRT_ID`),
  CONSTRAINT `FK_CK_CP_DISBURSEMENT_VA_CK_CP_NODE` FOREIGN KEY (`DIS_NODE`) REFERENCES `T_CK_CP_NODE` (`NOD_ID`),
  CONSTRAINT `FK_CK_CP_DISBURSEMENT_VA_CK_MST_SERVICE_TYPE` FOREIGN KEY (`DIS_SERVICE_TYPE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),
  CONSTRAINT `FK_CK_CP_DISBURSEMENT_VA_MST_CURRENCY` FOREIGN KEY (`DIS_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DISBURSEMENT TABLE';

-- DISBURSEMENT NON VA ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CP_DISBURSEMENT_NON_VA` (
  `DISN_ID` varchar(35) NOT NULL COMMENT 'DISBURSEMENT NON VA ID - UUID',
  `DISN_SERVICE_TYPE` varchar(35) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'SERVICE TYPE - REFERENCE T_CK_MST_SERVICE_TYPE:SVCT_ID',
  `DISN_NODE` varchar(35) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'NODE - REFERENCE T_CK_CP_NODE:NOD_ID',
  `DISN_REF_NUMBER` varchar(255) DEFAULT NULL COMMENT 'USER REFERENCE NUMBER',
  `DISN_SENDER_ACCOUNT` varchar(35) DEFAULT NULL COMMENT 'DISBURSEMENT SENDER ACCOUNT',
  `DISN_BENEFICIARY_ACCOUNT_BANK` varchar(35) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'BENEFICIARY BANK REFERENCE - T_MST_BANK:BANK_ID',
  `DISN_BENEFICIARY_ACCOUNT` varchar(35) DEFAULT NULL COMMENT 'BENEFICIARY ACCOUNT',
  `DISN_BENEFICIARY_ACCOUNT_NAME` varchar(255) DEFAULT NULL COMMENT 'BENEFICIARY ACCOUNT NAME',
  `DISN_BENEFICIARY_ACCOUNT_TYPE` varchar(5) DEFAULT NULL COMMENT 'BENEFICIARY ACCOUNT TYPE',
  `DISN_AMOUNT` decimal(15,2) DEFAULT NULL COMMENT 'BILL AMOUNT',
  `DISN_CCY` varchar(3) DEFAULT NULL COMMENT 'BILL CURRENCY REFERENCE - T_MST_CURRENCY:CCY_CODE',
  `DISN_DESCRIPTION` varchar(500) DEFAULT NULL COMMENT 'DESCRIPTION',
  `DISN_STATUS` char(1) DEFAULT NULL COMMENT 'DISBURSEMENT STATUS - I (INQUIRY) : P (PAYMENT)',
  `DISN_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `DISN_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `DISN_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `DISN_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`DISN_ID`),
  KEY `FK_CK_CP_DISBURSEMENT_NON_VA_MST_BANK` (`DISN_BENEFICIARY_ACCOUNT_BANK`),
  KEY `FK_CK_CP_DISBURSEMENT_NON_VA_MST_CURRENCY` (`DISN_CCY`),
  KEY `FK_CK_CP_DISBURSEMENT_NON_VA_MST_SERVICE_TYPE` (`DISN_SERVICE_TYPE`),
  KEY `FK_CK_CP_DISBURSEMENT_NON_VA_CK_CP_NODE` (`DISN_NODE`),
  CONSTRAINT `FK_CK_CP_DISBURSEMENT_NON_VA_CK_CP_NODE` FOREIGN KEY (`DISN_NODE`) REFERENCES `T_CK_CP_NODE` (`NOD_ID`),
  CONSTRAINT `FK_CK_CP_DISBURSEMENT_NON_VA_MST_BANK` FOREIGN KEY (`DISN_BENEFICIARY_ACCOUNT_BANK`) REFERENCES `T_MST_BANK` (`BANK_ID`),
  CONSTRAINT `FK_CK_CP_DISBURSEMENT_NON_VA_MST_CURRENCY` FOREIGN KEY (`DISN_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`),
  CONSTRAINT `FK_CK_CP_DISBURSEMENT_NON_VA_MST_SERVICE_TYPE` FOREIGN KEY (`DISN_SERVICE_TYPE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DISBURSEMENT NON VA TABLE';
-- ---------------------------------------------------------------------------- DML ----------------------------------------------------------------------------
-- T_CK_CP_CODE_CONFIG
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 1, 'BIN_NUMBER', '9100', 'BIN NUMBER', 'BUSINESS IDENTIFICATION NUMBER', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 2, 'BIN_TITLE', 'CLICKARGO', 'BIN TITLE', 'BUSINESS IDENTIFICATION NAME', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 3, 'EXPIRED_DINAMIC_VA', '60', 'EXPIRED DATE ', 'EXPIRED DATE FOR DINAMIC VA', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 4, 'AUTHORIZATION', 'BD!U@7cL!cKar60', 'AUTHORIZATION KEY', 'AUTHORIZATION KEY', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 5, 'PARTNER_ID', 'BDICLK', 'PARTNER ID', 'PARTNER ID GENERATE BY BANK', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 6, 'BASE_URL', 'https://uat-dev.danamon.co.id', 'BASE URL', 'BASE URL DANAMON', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 7, 'AUTH_URL', '/api/oauth/token', 'AUTH URL', 'URL AUTHORIZATION DANAMON', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 8, 'CLIENT_ID', '608fbcfb-9bd1-45d7-ba57-1c910a15ed01', 'CLIENT ID', 'CLIENT ID GENERATE BY BANK', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 9, 'CLIENT_SECRET', '6117e38d-2404-48de-b2fa-53a1b1d5c4fe', 'CLIENT SECRET', 'CLIENT SECRET GENERATE BY BANK', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 10, 'API_KEY', 'a0d957ec-7396-4df8-900e-e4a499542a5e', 'API KEY', 'API KEY GENERATE BY BANK', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 11, 'ADDITIONAL_KEY', 'tW9OQLBkxTx64OWhBa5RYiqOwLSu5LxV1pAr29Hai7M=', 'ADDITIONAL KEY', 'ADDITIONAL KEY GENERATE BY BANK', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 12, 'INQUIRY_TRANSFER', '/v1/api/financialinfo/casa/virtualaccountinquiry', 'INQUIRY TRANSFER URL', 'URL INQUIRY TRANSFER DANAMON', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 13, 'PAYMENT_TRANSFER', '/v1/api/financialtransaction/casa/virtualaccountpayment', 'PAYMENT TRANSFER URL', 'URL PAYMENT TRANSFER DANAMON', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 14, 'SECRET_KEY', '1f99698c-54dd-4511-8978-8b119b7afa04', 'SECRET KEY', 'SECRET KEY GENERATE BY BANK', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 15, 'INQUIRY_BIFAST', '/v1/api/financialinfo/bifast/accountenquiry', 'INQUIRY BI FAST URL', 'URL INQUIRY BI FAST DANAMON', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 16, 'ALIAS_RESOLUTION', '/v1/api/productcreation/bifast/aliasresolution', 'ALIAS RESOLUTION URL', 'URL ALIAS RESOLUTION DANAMON', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 17, 'CREDIT_TRANSFER', '/v1/api/financialtransaction/bifast/credittransfer', 'CREDIT TRANSFER URL', 'URL CREDIT TRANSFER DANAMON', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 18, 'INQUIRY_NAME_OVERBOOKING', '/v1/api/financialinfo/casa/accountinquiryname', 'INQUIRY NAME OVERBOOKING', 'URL INQUIRY NAME OVERBOOKING DANAMON', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 19, 'INQUIRY_BALANCE_OVERBOOKING', '/v1/api/financialinfo/casa/accountinquirybalance', 'INQUIRY BALANCE OVERBOOKING', 'URL INQUIRY BALANCE OVERBOOKING DANAMON', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 20, 'PAYMENT_OVERBOOKING', '/v1/api/financialtransaction/transfer/cashoutoverbooking', 'PAYMENT OVERBOOKING', 'URL PAYMENT OVERBOOKING DANAMON', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
INSERT INTO T_CK_CP_NODE_CONFIG (CFG_NODE, CFG_SEQ, CFG_KEY, CFG_VAL, CFG_DESC, CFG_DESC_OTH, CFG_DT_FROM, CFG_DT_TO, CFG_STATUS, CFG_DT_CREATE, CFG_UID_CREATE, CFG_DT_LUPD, CFG_UID_LUPD) VALUES('DNO', 21, 'INQUIRY_STATUS_OVERBOOKING', '/v1/api/financialinfo/transfer/cashoutoverbooking/inquirystatus', 'INQUIRY STATUS OVERBOOKING', 'URL INQUIRY STATUS OVERBOOKING DANAMON', '2023-05-24 00:00:00', '2023-05-24 00:00:00', 'A', '2023-05-24 00:00:00', 'SYS', '2023-05-24 00:00:00', 'SYS');
