-- 2023 - 07 - 12 --
ALTER TABLE T_CK_CP_DISBURSEMENT_NON_VA ADD DISN_PAYMENT_REF_NUMBER varchar(255) NULL COMMENT 'PAYMENT REFERENCE NUMBER';
ALTER TABLE T_CK_CP_DISBURSEMENT_NON_VA CHANGE DISN_PAYMENT_REF_NUMBER DISN_PAYMENT_REF_NUMBER varchar(255) NULL COMMENT 'PAYMENT REFERENCE NUMBER' AFTER DISN_CCY;

ALTER TABLE T_CK_CP_DISBURSEMENT_VA ADD DIS_PAYMENT_REF_NUMBER varchar(255) NULL COMMENT 'PAYMENT REFERENCE NUMBER';
ALTER TABLE T_CK_CP_DISBURSEMENT_VA CHANGE DIS_PAYMENT_REF_NUMBER DIS_PAYMENT_REF_NUMBER varchar(255) NULL COMMENT 'PAYMENT REFERENCE NUMBER' AFTER DIS_COST_CENTER;
