drop table if exists T_CK_CP_SNAP_AUDIT;

CREATE TABLE `T_CK_CP_SNAP_AUDIT` (
  `SAD_ID` varchar(35) NOT NULL COMMENT 'AUDIT ID - UUID',
  `SAD_TYPE` varchar(3) DEFAULT NULL COMMENT 'TYPE: IN, OUT',
  `SAD_SUB_TYPE` varchar(45) DEFAULT NULL COMMENT 'TYPE: IN, OUT',
  `SAD_TXN_REF` varchar(128) DEFAULT NULL COMMENT 'TXN REF FROM CLICXXX',
  `SAD_TXN_REF_BANK` varchar(256) DEFAULT NULL COMMENT 'TRANSACTION ID FOR THIS TRANSACTION WITH BANK',
  `SAD_URL` varchar(1024) DEFAULT NULL COMMENT 'HTTP URL',
  `SAD_PROXY` varchar(128) DEFAULT NULL COMMENT 'PROXY - SnapInboundInquiryProxy',
  `SAD_REQ_HDR` varchar(2048) DEFAULT NULL COMMENT 'SNAP REQUEST HEADER - JSON OBJECT',
  `SAD_REQ_BODY` varchar(2048) DEFAULT NULL COMMENT 'SNAP REQUEST BODY - JSON OBJECT',
  `SAD_REQ_CONSTRAINTS` varchar(4096) DEFAULT NULL COMMENT 'SNAP REQUEST BODY VALIDATION CONSTRAINTS',
  `SAD_DT_REQ` datetime(3) DEFAULT NULL COMMENT 'SNAP REQUEST DATE TIME',
  `SAD_RSP_HDR` varchar(2048) DEFAULT NULL COMMENT 'SNAP RESPONSE HEADER - JSON OBJECT',
  `SAD_RSP_BODY` varchar(2048) DEFAULT NULL COMMENT 'SNAP RESPONSE BODY - JSON OBJECT',
  `SAD_RSP_CONSTRAINTS` varchar(2048) DEFAULT NULL COMMENT 'SNAP REQUEST BODY VALIDATION CONSTRAINTS',
  `SAD_REP_CODE` varchar(35) DEFAULT NULL COMMENT 'SNAP RESPONSE CODE',
  `SAD_REP_MSG` varchar(256) DEFAULT NULL COMMENT 'SNAP RESPONSE MESSAGE',
  `SAD_DT_RSP` datetime(3) DEFAULT NULL COMMENT 'SNAP RESPONSE DATE TIME',
  `SAD_EXP` varchar(4096) DEFAULT NULL COMMENT 'SNAP EXCEPTION STACK',
  `SAD_DT_EXP` datetime(3) DEFAULT NULL COMMENT 'SNAP EXCEPTION DATE TIME',
  `SAD_SUCCESS` TINYINT(1) DEFAULT NULL COMMENT 'SUCCESS: Y, N',
  `SAD_STATUS` char(1) DEFAULT NULL COMMENT 'RECORD STATUS - A : I',
  `SAD_DT_CREATE` datetime(3) DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `SAD_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `SAD_DT_LUPD` datetime(3) DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `SAD_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`SAD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='SNAP AUDIT';


REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '1', 'BASE_URL', 'https://ct2-dev.clickargo.com/snapMock', 'BASE URL', 'BASE URL DANAMON', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '2', 'CONTENT_TYPE', 'application/json', 'CONTENT_TYPE', 'CONTENT_TYPE', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '3', 'ORIGIN', 'clickargo.com', 'ORIGIN', 'ORIGIN', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '4', 'CHANNEL_ID', '12345', 'CHANNEL_ID', 'CHANNEL_ID', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '5', 'PRIVATE_KEY', 'TUCIgnGSzlMM6Qw2dN4Yk8ZSYKM98YN6DCW08+PBGK4=', 'PRIVATE_KEY', 'PRIVATE_KEY', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '6', 'CLIENT_ID', '9babe06e59684f17ae51a7fb0fa37bdf', 'CLIENT_ID', 'CLIENT_ID', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '7', 'PARTNER_ID', '9babe06e59684f17ae51a7fb0fa37bdf', 'PARTNER_ID', 'PARTNER_ID', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '8', 'SECRET_KEY', 'dz3oyoiVddRYfXypS+LyIJLigOk5c8fi4QUzS4NDIzQ=', 'SECRET_KEY', 'SECRET_KEY', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '9', 'PAY_IN_AUTHORIZATION', 'payInAuthorization', 'PAY_IN_AUTHORIZATION', 'PAY_IN_AUTHORIZATION', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');


REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '51', 'X_FORWARDED_PREFIX', '/be', 'X-FORWARDED-PREFIX', 'X-FORWARDED-PREFIX', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');




REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '115', 'URL_INTERNAL_ACCN_INQUIRY', '/api/v2/account-inquiry-internal', 'URL_INTERNAL_ACCN_INQUIRY', 'URL_INTERNAL_ACCN_INQUIRY', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '116', 'URL_EXTERNAL_ACCN_INQUIRY', '/api/v3/account-inquiry-external', 'URL_EXTERNAL_ACCN_INQUIRY', 'URL_EXTERNAL_ACCN_INQUIRY', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '117', 'URL_INTERNAL_TRANSFER', '/api/v2/transfer-intrabank', 'URL_INTERNAL_TRANSFER', 'URL_INTERNAL_TRANSFER', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '118', 'URL_INTER_TRANSFER', '/api/v3/transfer-interbank', 'URL_INTER_TRANSFER', 'URL_INTER_TRANSFER', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '122', 'URL_RTGS', '/api/v2/transfer-rtgs', 'URL_RTGS', 'URL_RTGS', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '123', 'URL_SKN', '/api/v3/transfer-skn', 'URL_SKN', 'URL_SKN', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '124', 'URL_VA_INQUIRY', '/api/v2/transfer-va/inquiry', 'URL_VA_INQUIRY', 'URL_VA_INQUIRY', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '125', 'URL_VA_PAYMENT', '/api/v2/transfer-va/payment', 'URL_VA_PAYMENT', 'URL_VA_PAYMENT', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '126', 'URL_VA_INQUIRY_STATUS', '/api/v2/transfer-va/status', 'URL_VA_INQUIRY_STATUS', 'URL_VA_INQUIRY_STATUS', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '136', 'URL_TRANS_STATUS_INQUIRY', '/api/v3/transfer/status', 'URL_TRANS_STATUS_INQUIRY', 'URL_TRANS_STATUS_INQUIRY', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '173', 'URL_TOKEN', '/api/v2/access-token/b2b', 'URL_TOKEN', 'URL_TOKEN', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

