

-- Please ignore the file
-- Please ignore the file
-- Please ignore the file
-- Please ignore the file

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '1', 'BASE_URL', 'https://apidevportal.aspi-indonesia.or.id:44310', 'BASE URL', 'BASE URL DANAMON', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '5', 'PRIVATE_KEY', 'TUCIgnGSzlMM6Qw2dN4Yk8ZSYKM98YN6DCW08+PBGK4=', 'PRIVATE_KEY', 'PRIVATE_KEY', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '6', 'CLIENT_ID', '9babe06e59684f17ae51a7fb0fa37bdf', 'CLIENT_ID', 'CLIENT_ID', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');


REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '7', 'PARTNER_ID', '9babe06e59684f17ae51a7fb0fa37bdf', 'PARTNER_ID', 'PARTNER_ID', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');


REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '8', 'SECRET_KEY', 'dz3oyoiVddRYfXypS+LyIJLigOk5c8fi4QUzS4NDIzQ=', 'SECRET_KEY', 'SECRET_KEY', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');



-- begin snapApiPortal

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '115', 'URL_INTERNAL_ACCN_INQUIRY', '/api/v1.0/account-inquiry-internal', 'URL_INTERNAL_ACCN_INQUIRY', 'URL_INTERNAL_ACCN_INQUIRY', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '116', 'URL_EXTERNAL_ACCN_INQUIRY', '/api/v1.0/account-inquiry-external', 'URL_EXTERNAL_ACCN_INQUIRY', 'URL_EXTERNAL_ACCN_INQUIRY', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '117', 'URL_INTERNAL_TRANSFER', '/api/v1.0/transfer-intrabank', 'URL_INTERNAL_TRANSFER', 'URL_INTERNAL_TRANSFER', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '118', 'URL_INTER_TRANSFER', '/api/v1.0/transfer-interbank', 'URL_INTER_TRANSFER', 'URL_INTER_TRANSFER', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '122', 'URL_RTGS', '/api/v1.0/transfer-rtgs', 'URL_RTGS', 'URL_RTGS', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '123', 'URL_SKN', '/api/v1.0/transfer-skn', 'URL_SKN', 'URL_SKN', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '124', 'URL_VA_INQUIRY', '/api/v1.0/transfer-va/inquiry', 'URL_VA_INQUIRY', 'URL_VA_INQUIRY', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '125', 'URL_VA_PAYMENT', '/api/v1.0/transfer-va/payment', 'URL_VA_PAYMENT', 'URL_VA_PAYMENT', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '126', 'URL_VA_INQUIRY_STATUS', '/api/v1.0/transfer-va/status', 'URL_VA_INQUIRY_STATUS', 'URL_VA_INQUIRY_STATUS', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '136', 'URL_TRANS_STATUS_INQUIRY', '/api/v1.0/transfer/status', 'URL_TRANS_STATUS_INQUIRY', 'URL_TRANS_STATUS_INQUIRY', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');

REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '173', 'URL_TOKEN', '/api/v1.0/access-token/b2b', 'URL_TOKEN', 'URL_TOKEN', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');


--
REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '174', 'URL_SIGNATURE_TOKEN', '/api/v1.0/utilities/signature-auth', 'URL_SIGNATURE_TOKEN', 'URL_SIGNATURE_TOKEN', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');


REPLACE INTO `clickargo2`.`T_CK_CP_NODE_CONFIG` (`CFG_NODE`, `CFG_SEQ`, `CFG_KEY`, `CFG_VAL`, `CFG_DESC`, `CFG_DESC_OTH`, `CFG_DT_FROM`, `CFG_DT_TO`, `CFG_STATUS`, `CFG_DT_CREATE`, `CFG_UID_CREATE`) 
VALUES ('DNO', '175', 'URL_SIGNATURE_SERVICE', '/api/v1.0/utilities/signature-service', 'URL_SIGNATURE_SERVICE', 'URL_SIGNATURE_SERVICE', '2023-05-24 00:00:00', '2029-05-24 00:00:00', 'A', SYSDATE(), 'SYS');


