ALTER TABLE `clickargo2`.`T_CK_CP_DISBURSEMENT_VA` 
DROP FOREIGN KEY `FK_CK_CP_DISBURSEMENT_VA_CK_CP_CREATION_VA`;
ALTER TABLE `clickargo2`.`T_CK_CP_DISBURSEMENT_VA` 
DROP INDEX `FK_CK_CP_DISBURSEMENT_VA_CK_CP_CREATION_VA` ;
;