UPDATE `clickargo2`.`T_CORE_ACCN` SET `ACCN_DT_SUSP` = NULL, `ACCN_STATUS` = 'A' WHERE (`ACCN_ID` = 'CK0244');
UPDATE `clickargo2`.`T_CORE_ACCN` SET `ACCN_DT_SUSP` = NULL, `ACCN_STATUS` = 'A' WHERE (`ACCN_ID` = 'CK0263');
UPDATE `clickargo2`.`T_CORE_ACCN` SET `ACCN_DT_SUSP` = NULL, `ACCN_STATUS` = 'A' WHERE (`ACCN_ID` = 'CK0291');
UPDATE `clickargo2`.`T_CORE_ACCN` SET `ACCN_DT_SUSP` = NULL, `ACCN_STATUS` = 'A' WHERE (`ACCN_ID` = 'CK0325');
UPDATE `clickargo2`.`T_CORE_ACCN` SET `ACCN_DT_SUSP` = NULL, `ACCN_STATUS` = 'A' WHERE (`ACCN_ID` = 'CK0372');
