package com.guudint.clickargo.admin.model;
// Generated 22 Dec 2023, 10:52:29 am by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.core.model.TCoreApps;

/**
 * TCkAccnConfigExt generated by hbm2java
 */
@Entity
@Table(name = "T_CK_ACCN_CONFIG_EXT")
public class TCkAccnConfigExt extends COAbstractEntity<TCkAccnConfigExt> {

	private static final long serialVersionUID = -1698859397775385880L;
	private TCkAccnConfigExtId id;
	private TCoreAccn TCoreAccn;
	private TCoreApps TCoreApps;
	private String caeValue;
	private Character caeStatus;
	private Date caeDtCreate;
	private String caeUidCreate;
	private Date caeDtLupd;
	private String caeUidLupd;

	public TCkAccnConfigExt() {
	}

	public TCkAccnConfigExt(TCkAccnConfigExtId id, TCoreAccn TCoreAccn, TCoreApps TCoreApps) {
		this.id = id;
		this.TCoreAccn = TCoreAccn;
		this.TCoreApps = TCoreApps;
	}

	public TCkAccnConfigExt(TCkAccnConfigExtId id, TCoreAccn TCoreAccn, TCoreApps TCoreApps, String caeValue,
			Character caeStatus, Date caeDtCreate, String caeUidCreate, Date caeDtLupd, String caeUidLupd) {
		this.id = id;
		this.TCoreAccn = TCoreAccn;
		this.TCoreApps = TCoreApps;
		this.caeValue = caeValue;
		this.caeStatus = caeStatus;
		this.caeDtCreate = caeDtCreate;
		this.caeUidCreate = caeUidCreate;
		this.caeDtLupd = caeDtLupd;
		this.caeUidLupd = caeUidLupd;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "caeAccnId", column = @Column(name = "CAE_ACCN_ID", nullable = false, length = 35)),
			@AttributeOverride(name = "caeType", column = @Column(name = "CAE_TYPE", nullable = false, length = 35)),
			@AttributeOverride(name = "caeRoleId", column = @Column(name = "CAE_ROLE_ID", nullable = false, length = 35)),
			@AttributeOverride(name = "caeAppsCode", column = @Column(name = "CAE_APPS_CODE", nullable = false, length = 35)) })
	public TCkAccnConfigExtId getId() {
		return this.id;
	}

	public void setId(TCkAccnConfigExtId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAE_ACCN_ID", nullable = false, insertable = false, updatable = false)
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAE_APPS_CODE", nullable = false, insertable = false, updatable = false)
	public TCoreApps getTCoreApps() {
		return this.TCoreApps;
	}

	public void setTCoreApps(TCoreApps TCoreApps) {
		this.TCoreApps = TCoreApps;
	}

	@Column(name = "CAE_VALUE", length = 16777215)
	public String getCaeValue() {
		return this.caeValue;
	}

	public void setCaeValue(String caeValue) {
		this.caeValue = caeValue;
	}

	@Column(name = "CAE_STATUS", length = 1)
	public Character getCaeStatus() {
		return this.caeStatus;
	}

	public void setCaeStatus(Character caeStatus) {
		this.caeStatus = caeStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CAE_DT_CREATE", length = 19)
	public Date getCaeDtCreate() {
		return this.caeDtCreate;
	}

	public void setCaeDtCreate(Date caeDtCreate) {
		this.caeDtCreate = caeDtCreate;
	}

	@Column(name = "CAE_UID_CREATE", length = 35)
	public String getCaeUidCreate() {
		return this.caeUidCreate;
	}

	public void setCaeUidCreate(String caeUidCreate) {
		this.caeUidCreate = caeUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CAE_DT_LUPD", length = 19)
	public Date getCaeDtLupd() {
		return this.caeDtLupd;
	}

	public void setCaeDtLupd(Date caeDtLupd) {
		this.caeDtLupd = caeDtLupd;
	}

	@Column(name = "CAE_UID_LUPD", length = 35)
	public String getCaeUidLupd() {
		return this.caeUidLupd;
	}

	public void setCaeUidLupd(String caeUidLupd) {
		this.caeUidLupd = caeUidLupd;
	}

	@Override
	public int compareTo(TCkAccnConfigExt o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
