package com.guudint.clickargo.admin.model;
// Generated 22 Dec 2023, 10:52:29 am by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkAccnConfigExtId generated by hbm2java
 */
@Embeddable
public class TCkAccnConfigExtId extends COAbstractEntity<TCkAccnConfigExtId> {

	private static final long serialVersionUID = -7309513394406359158L;
	private String caeAccnId;
	private String caeType;
	private String caeRoleId;
	private String caeAppsCode;

	public TCkAccnConfigExtId() {
	}

	public TCkAccnConfigExtId(String caeAccnId, String caeType, String caeRoleId, String caeAppsCode) {
		this.caeAccnId = caeAccnId;
		this.caeType = caeType;
		this.caeRoleId = caeRoleId;
		this.caeAppsCode = caeAppsCode;
	}

	@Column(name = "CAE_ACCN_ID", nullable = false, length = 35)
	public String getCaeAccnId() {
		return this.caeAccnId;
	}

	public void setCaeAccnId(String caeAccnId) {
		this.caeAccnId = caeAccnId;
	}

	@Column(name = "CAE_TYPE", nullable = false, length = 35)
	public String getCaeType() {
		return this.caeType;
	}

	public void setCaeType(String caeType) {
		this.caeType = caeType;
	}

	@Column(name = "CAE_ROLE_ID", nullable = false, length = 35)
	public String getCaeRoleId() {
		return this.caeRoleId;
	}

	public void setCaeRoleId(String caeRoleId) {
		this.caeRoleId = caeRoleId;
	}

	@Column(name = "CAE_APPS_CODE", nullable = false, length = 35)
	public String getCaeAppsCode() {
		return this.caeAppsCode;
	}

	public void setCaeAppsCode(String caeAppsCode) {
		this.caeAppsCode = caeAppsCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TCkAccnConfigExtId))
			return false;
		TCkAccnConfigExtId castOther = (TCkAccnConfigExtId) other;

		return ((this.getCaeAccnId() == castOther.getCaeAccnId()) || (this.getCaeAccnId() != null
				&& castOther.getCaeAccnId() != null && this.getCaeAccnId().equals(castOther.getCaeAccnId())))
				&& ((this.getCaeType() == castOther.getCaeType()) || (this.getCaeType() != null
						&& castOther.getCaeType() != null && this.getCaeType().equals(castOther.getCaeType())))
				&& ((this.getCaeRoleId() == castOther.getCaeRoleId()) || (this.getCaeRoleId() != null
						&& castOther.getCaeRoleId() != null && this.getCaeRoleId().equals(castOther.getCaeRoleId())))
				&& ((this.getCaeAppsCode() == castOther.getCaeAppsCode())
						|| (this.getCaeAppsCode() != null && castOther.getCaeAppsCode() != null
								&& this.getCaeAppsCode().equals(castOther.getCaeAppsCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCaeAccnId() == null ? 0 : this.getCaeAccnId().hashCode());
		result = 37 * result + (getCaeType() == null ? 0 : this.getCaeType().hashCode());
		result = 37 * result + (getCaeRoleId() == null ? 0 : this.getCaeRoleId().hashCode());
		result = 37 * result + (getCaeAppsCode() == null ? 0 : this.getCaeAppsCode().hashCode());
		return result;
	}

	@Override
	public int compareTo(TCkAccnConfigExtId o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
