use ctMigration;

DROP TABLE IF EXISTS ctMigration.TMP_LOC;
CREATE TABLE ctMigration.TMP_LOC (
  `ID` varchar(70) NOT NULL ,
  `TYPE` varchar(35) DEFAULT NULL,
  `COMPANY` varchar(256) DEFAULT NULL,
  `NAME` varchar(256) DEFAULT NULL ,
  `ADDRESS` varchar(256) DEFAULT NULL ,
  `DT_START` datetime DEFAULT NULL ,
  `DT_END` datetime DEFAULT NULL ,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ;

-- delete demo data
delete from TMP_USER where COMPANY_ID in (SELECT ID FROM ctMigration.TMP_COMPANY
where NAME like '%demo%');

delete from TMP_USER where COMPANY_ID in (SELECT ID FROM ctMigration.TMP_COMPANY
where NAME like '%demo%');

delete from TMP_TRUCK where COMPANY in (SELECT ID FROM ctMigration.TMP_COMPANY
where NAME like '%demo%');

delete from TMP_LOC where COMPANY in (SELECT ID FROM ctMigration.TMP_COMPANY
where NAME like '%demo%');

delete from TMP_DRV where COMPANY in (SELECT ID FROM ctMigration.TMP_COMPANY
where NAME like '%demo%');

delete from TMP_CREDIT where COMPANY in (SELECT ID FROM ctMigration.TMP_COMPANY
where NAME like '%demo%');

delete from TMP_CONTRACT where `TO` in (SELECT ID FROM ctMigration.TMP_COMPANY
where NAME like '%demo%');

delete from TMP_CONTRACT where CO_FF in (SELECT ID FROM ctMigration.TMP_COMPANY
where NAME like '%demo%');

-- delete guud user
delete FROM ctMigration.TMP_USER
where EMAIL like '%GUUD.id%';

delete FROM ctMigration.TMP_USER
where EMAIL like '%GUUD.COMPANY%';

-- -------------- process TMP_COMPANY ----------
-- upper case
update TMP_COMPANY set NAME  = UCASE(NAME), ADDR1 = UCASE(ADDR1), EMAIL = UCASE(EMAIL) ;

-- ADD ACCOUNT ID
ALTER TABLE `ctMigration`.`TMP_COMPANY`  ADD COLUMN `ACCN_ID` VARCHAR(45) NULL FIRST;
ALTER TABLE `ctMigration`.`TMP_COMPANY`  ADD COLUMN `ACCN_TYPE` VARCHAR(45) AFTER `TYPE`;


--
-- UPDATE TMP_COMPANY SET ACCN_ID = 'DSVAS'  WHERE NAME = 'DSV AIR & SEA';
-- UPDATE TMP_COMPANY SET ACCN_ID = 'DSVS'  WHERE NAME = 'DSV SOLUTIONS';
-- UPDATE TMP_COMPANY SET ACCN_ID = 'DSVR'  WHERE NAME = 'DSV ROAD';
-- UPDATE TMP_COMPANY SET ACCN_ID = 'DSVTSPL'  WHERE NAME = 'DSV TRANSPORTATION & SERVICES PTE. LTD.';
-- UPDATE TMP_COMPANY SET ACCN_ID = 'DSVKD'  WHERE NAME = 'DSVS-KFC DELIVERY';
-- UPDATE TMP_COMPANY SET ACCN_ID = 'DSVASR'  WHERE NAME = 'DSV A/S ROAD';
-- 

/*
UPDATE TMP_COMPANY AS c JOIN
 ( SELECT ID, row_number() OVER (ORDER BY REG_DATE) AS rn 
      FROM TMP_COMPANY
    ) AS sub
  ON  c.ID = sub.ID
SET c.ACCN_ID = concat('CKS', lpad(sub.rn,4,'0') )
WHERE ACCN_ID NOT LIKE 'DSV%';
 */
 
DELETE FROM TMP_COMPANY tc WHERE tc.ID not in (select UUID from TMP_COMPANY_SG);

UPDATE TMP_COMPANY AS c JOIN
 TMP_COMPANY_SG AS sub
  ON  c.ID = sub.UUID
SET c.ACCN_ID = sub.ACCN_ID;
 
UPDATE TMP_COMPANY set ACCN_TYPE = 'ACC_TYPE_CO' where `TYPE` like '%CO%';
UPDATE TMP_COMPANY set ACCN_TYPE = 'ACC_TYPE_FF' where `TYPE` like '%FF%';
UPDATE TMP_COMPANY set ACCN_TYPE = 'ACC_TYPE_TO' where `TYPE` like '%TC%';

UPDATE TMP_COMPANY set ACCN_TYPE = 'ACC_TYPE_FF_CO' where ID in 
(select CO_COMPANY from TMP_CONTRACT);

-- 
UPDATE TMP_COMPANY c join (
	select *
    from ctMigration.TMP_COMPANY_SG 
    where EPOD = 'N'
    ) as sg on sg.UUID = c.ID
set ACCN_TYPE = 'ACC_TYPE_TO_WJ';


UPDATE TMP_COMPANY set VAT_NO = length(SUBSTRING(VAT_NO, 1,20)) where length(VAT_NO) > 20;

-- -------------- process TMP_USER ----------
-- upper case

ALTER TABLE `ctMigration`.`TMP_USER`  ADD COLUMN `USER_ID` VARCHAR(45) NULL FIRST;
ALTER TABLE `ctMigration`.`TMP_USER`  ADD COLUMN `ENCRYPT_PWD` VARCHAR(100) AFTER `PWD`;
ALTER TABLE `ctMigration`.`TMP_USER`  ADD COLUMN `ACCN_ID` VARCHAR(35) AFTER `USER_ID`;
ALTER TABLE `ctMigration`.`TMP_USER`  ADD COLUMN `USER_NAME` VARCHAR(35) AFTER `ACCN_ID`;
ALTER TABLE `ctMigration`.`TMP_USER`  CHANGE COLUMN `PWD` `PWD` VARCHAR(100) NULL DEFAULT NULL ;

UPDATE `ctMigration`.`TMP_USER` set PWD = concat(EMAIL, '123');
UPDATE TMP_USER SET PWD = ucase(PWD);
-- update ENCRYPT_PWD with Java codes

UPDATE TMP_USER AS c JOIN
 ( SELECT UID, row_number() OVER (ORDER BY REG_DATE, EMAIL) AS rn 
      FROM TMP_USER
    ) AS sub
  ON  c.UID = sub.UID
SET c.USER_ID = concat('CKUS', lpad(sub.rn,5,'0') );

UPDATE TMP_USER AS c JOIN
 ( SELECT ACCN_ID, ID FROM TMP_COMPANY
    ) AS sub
  ON  c.COMPANY_ID = sub.ID
SET c.ACCN_ID = sub.ACCN_ID;

UPDATE TMP_USER SET USER_NAME = substring(EMAIL, 1, LOCATE('@', EMAIL)-1);
UPDATE TMP_USER SET USER_NAME = ucase(USER_NAME);
UPDATE TMP_USER SET EMAIL = ucase(EMAIL);



-- ----------- process TMP_TRUCK
ALTER TABLE `ctMigration`.`TMP_TRUCK` ADD COLUMN `TRUCK_ID` VARCHAR(45) NULL FIRST;
ALTER TABLE `ctMigration`.`TMP_TRUCK` ADD COLUMN `ACCN_ID` VARCHAR(100) AFTER `TRUCK_ID`;
ALTER TABLE `ctMigration`.`TMP_TRUCK` ADD COLUMN `TRUCK_TYPE_ID` VARCHAR(100) AFTER `ACCN_ID`;

update TMP_TRUCK set TYPE  = UCASE(TYPE) ;

UPDATE TMP_TRUCK AS c JOIN
 ( SELECT ID, row_number() OVER (ORDER BY concat(ID, PLATE_NO, CHASSIS_NO)) AS rn 
      FROM TMP_TRUCK
    ) AS sub
  ON  c.ID = sub.ID
SET c.TRUCK_ID = concat('CKTVS', lpad(sub.rn,6,'0') );

UPDATE TMP_TRUCK AS c JOIN
 ( SELECT ACCN_ID, ID FROM TMP_COMPANY
    ) AS sub
  ON  c.COMPANY = sub.ID
SET c.ACCN_ID = sub.ACCN_ID;

-- --- 
UPDATE ctMigration.TMP_TRUCK SET TYPE = 'CONTAINER 20FT' WHERE TYPE = '20';
UPDATE ctMigration.TMP_TRUCK SET TYPE = 'CONTAINER 40FT' WHERE TYPE = '40';

update ctMigration.TMP_TRUCK set type = trim(type);

-- delete FROM clickargo2.T_CK_CT_MST_VEH_TYPE where VHTY_ID not in ('CONTAINER20FT','CONTAINER40FT') ;

INSERT INTO clickargo2.T_CK_CT_MST_VEH_TYPE(VHTY_ID, VHTY_NAME, VHTY_DESC, VHTY_DESC_OTH, VHTY_STATUS, VHTY_DT_CREATE, VHTY_UID_CREATE)
SELECT DISTINCT left(TYPE, 33), TYPE, TYPE, TYPE, 'A', SYSDATE(), 'SYS' FROM ctMigration.TMP_TRUCK
where TYPE NOT IN (SELECT VHTY_NAME FROM clickargo2.T_CK_CT_MST_VEH_TYPE)
group by TYPE;

DELETE FROM `clickargo2`.`T_CK_CT_MST_VEH_TYPE` WHERE (`VHTY_ID` = '14 FT');

-- replace blank character in type id
UPDATE clickargo2.T_CK_CT_MST_VEH_TYPE t 
SET VHTY_ID = REPLACE(VHTY_ID, ' ', ''); 

UPDATE ctMigration.TMP_TRUCK AS c JOIN
 ( (SELECT VHTY_ID, VHTY_NAME FROM clickargo2.T_CK_CT_MST_VEH_TYPE)
    ) AS sub
  ON  TRIM(c.TYPE) = TRIM(sub.VHTY_NAME)
SET c.TRUCK_TYPE_ID = sub.VHTY_ID;

-- ----
-- ------
ALTER TABLE `ctMigration`.`TMP_DRV` ADD COLUMN `DRV_ID` VARCHAR(45) NULL FIRST;
ALTER TABLE `ctMigration`.`TMP_DRV` ADD COLUMN `ACCN_ID` VARCHAR(100) AFTER `DRV_ID`;
-- ALTER TABLE `ctMigration`.`TMP_DRV` ADD COLUMN `NAME_ID` VARCHAR(100) AFTER `ACCN_ID`;


update TMP_DRV set NAME  = UCASE(NAME) ;
update TMP_DRV set USER_NAME  = UCASE(USER_NAME) ;

UPDATE TMP_DRV AS c JOIN
 ( SELECT UID, row_number() OVER (ORDER BY UID) AS rn 
      FROM TMP_DRV
    ) AS sub
  ON  c.UID = sub.UID
SET c.DRV_ID = concat('CKTDS', lpad(sub.rn,6,'0') );

UPDATE TMP_DRV AS c JOIN
 ( SELECT ACCN_ID, ID FROM TMP_COMPANY
    ) AS sub
  ON  c.COMPANY = sub.ID
SET c.ACCN_ID = sub.ACCN_ID;


-- ----------- location

ALTER TABLE `ctMigration`.`TMP_LOC` ADD COLUMN `LOC_ID` VARCHAR(45) NULL FIRST;
ALTER TABLE `ctMigration`.`TMP_LOC` ADD COLUMN `ACCN_ID` VARCHAR(100) AFTER `LOC_ID`;

/*
update TMP_LOC set ADDRESS  = UCASE(ADDRESS) ;
-- first 3 worlds
update ctMigration.TMP_LOC set name = replace(SUBSTRING_INDEX(ADDRESS,' ',3),',','');

UPDATE TMP_LOC AS c JOIN
 ( SELECT ID, row_number() OVER (ORDER BY ID) AS rn 
      FROM TMP_LOC
    ) AS sub
  ON  c.ID = sub.ID
SET c.LOC_ID = concat('CKCTLOC', lpad(sub.rn,6,'0') );

UPDATE TMP_LOC AS c JOIN
 ( SELECT ACCN_ID, ID FROM TMP_COMPANY
    ) AS sub
  ON  c.COMPANY = sub.ID
SET c.ACCN_ID = sub.ACCN_ID;
*/
-- contract

ALTER TABLE `ctMigration`.`TMP_CONTRACT` ADD COLUMN `CON_ID` VARCHAR(45) NULL FIRST;
ALTER TABLE `ctMigration`.`TMP_CONTRACT` ADD COLUMN `TO_ACCN_ID` VARCHAR(100) AFTER `CON_ID`;
ALTER TABLE `ctMigration`.`TMP_CONTRACT` ADD COLUMN `FF_ACCN_ID` VARCHAR(100) AFTER `TO_ACCN_ID`;
ALTER TABLE `ctMigration`.`TMP_CONTRACT` ADD COLUMN `TO_CONC_ID` VARCHAR(100) AFTER `FF_ACCN_ID`;
ALTER TABLE `ctMigration`.`TMP_CONTRACT` ADD COLUMN `FF_CONC_ID` VARCHAR(100) AFTER `TO_CONC_ID`;

ALTER TABLE `ctMigration`.`TMP_CONTRACT` ADD COLUMN `FFCO_CONC_ID` VARCHAR(100) AFTER `FF_CONC_ID`;
ALTER TABLE `ctMigration`.`TMP_CONTRACT` ADD COLUMN `FFCO_ACCN_ID` VARCHAR(100) AFTER `FFCO_CONC_ID`;


UPDATE TMP_CONTRACT AS c JOIN
 ( SELECT ID, row_number() OVER (ORDER BY ID) AS rn 
      FROM TMP_CONTRACT
    ) AS sub
  ON  c.ID = sub.ID
SET c.CON_ID = concat('CKTCC', lpad(sub.rn,6,'0') );

UPDATE TMP_CONTRACT AS c JOIN
 ( SELECT ID, row_number() OVER (ORDER BY ID) AS rn 
      FROM TMP_CONTRACT
    ) AS sub
  ON  c.ID = sub.ID
SET c.TO_CONC_ID = concat('CKTCT', lpad(sub.rn,6,'0') );

UPDATE TMP_CONTRACT AS c JOIN
 ( SELECT ID, row_number() OVER (ORDER BY ID) AS rn 
      FROM TMP_CONTRACT
    ) AS sub
  ON  c.ID = sub.ID
SET c.FF_CONC_ID = concat('CKCCF', lpad(sub.rn,6,'0') );

UPDATE TMP_CONTRACT AS c JOIN
 ( SELECT ID, row_number() OVER (ORDER BY ID) AS rn 
      FROM TMP_CONTRACT WHERE CO_COMPANY IS NOT NULL AND FF_COMPANY IS NOT NULL
    ) AS sub
  ON  c.ID = sub.ID
SET c.FFCO_CONC_ID = concat('FFCO', lpad(sub.rn,6,'0') );


UPDATE TMP_CONTRACT AS c JOIN
 ( SELECT ACCN_ID, ID FROM TMP_COMPANY
    ) AS sub
  ON  c.TO = sub.ID
SET c.TO_ACCN_ID = sub.ACCN_ID;

UPDATE TMP_CONTRACT AS c JOIN
 ( SELECT ACCN_ID, ID FROM TMP_COMPANY
    ) AS sub
  ON  c.FF_COMPANY = sub.ID
SET c.FF_ACCN_ID = sub.ACCN_ID;

UPDATE TMP_CONTRACT AS c JOIN
 ( SELECT ACCN_ID, ID FROM TMP_COMPANY
    ) AS sub
  ON  c.CO_COMPANY = sub.ID
SET c.FFCO_ACCN_ID = sub.ACCN_ID;

-- 
ALTER TABLE `ctMigration`.`TMP_CREDIT` 
CHANGE COLUMN `SERVICE_TYPE` `SERVICE_TYPE` VARCHAR(9) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '' ,
CHANGE COLUMN `STATE` `STATE` VARCHAR(9) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '' ,
CHANGE COLUMN `CCY` `CCY` VARCHAR(3) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '' ,
CHANGE COLUMN `USR_VERIFY` `USR_VERIFY` VARCHAR(3) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '' ,
CHANGE COLUMN `DT_VERIFY` `DT_VERIFY` DATETIME NULL DEFAULT NULL ,
CHANGE COLUMN `USR_APPROVE` `USR_APPROVE` VARCHAR(3) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '' ,
CHANGE COLUMN `DT_APPROVE` `DT_APPROVE` DATETIME NULL DEFAULT NULL ;

-- Credit Limit
ALTER TABLE `ctMigration`.`TMP_CREDIT` ADD COLUMN `CR_ID` VARCHAR(45) DEFAULT NULL FIRST;
ALTER TABLE `ctMigration`.`TMP_CREDIT` ADD COLUMN `CJN_ID` VARCHAR(100) AFTER `CR_ID`;
ALTER TABLE `ctMigration`.`TMP_CREDIT` ADD COLUMN `ACCN_ID` VARCHAR(100) AFTER `CJN_ID`;
ALTER TABLE `ctMigration`.`TMP_CREDIT` ADD COLUMN `CJS_ID` VARCHAR(100) AFTER `CJN_ID`;

UPDATE TMP_CREDIT AS c JOIN
 ( SELECT COMPANY, DT_START, AMT, row_number() OVER (ORDER BY COMPANY, DT_START, AMT) AS rn 
      FROM TMP_CREDIT
    ) AS sub
  ON  c.COMPANY = sub.COMPANY and c.DT_START = sub.DT_START and c.AMT = sub.AMT
SET c.CR_ID = concat('CR', lpad(sub.rn,6,'0') );

UPDATE TMP_CREDIT AS c JOIN
 ( SELECT COMPANY, DT_START, AMT, row_number() OVER (ORDER BY COMPANY, DT_START, AMT) AS rn 
      FROM TMP_CREDIT
    ) AS sub
  ON  c.COMPANY = sub.COMPANY and c.DT_START = sub.DT_START and c.AMT = sub.AMT
SET c.CJN_ID = concat('CJN', lpad(sub.rn,6,'0') );

UPDATE TMP_CREDIT AS c JOIN
 ( SELECT COMPANY, DT_START, AMT, row_number() OVER (ORDER BY COMPANY, DT_START, AMT) AS rn 
      FROM TMP_CREDIT
    ) AS sub
  ON  c.COMPANY = sub.COMPANY and c.DT_START = sub.DT_START and c.AMT = sub.AMT
SET c.CJS_ID = concat('CJS', lpad(sub.rn,6,'0') );


UPDATE TMP_CREDIT AS c JOIN
 ( SELECT ACCN_ID, ID FROM TMP_COMPANY
    ) AS sub
  ON  c.COMPANY = sub.ID
SET c.ACCN_ID = sub.ACCN_ID;

-- -------------- insert into T_CORE_ACCN ----------
-- -----------
ALTER TABLE `clickargo2`.`T_CORE_ACCN`  CHANGE COLUMN `ACCN_ADDR1` `ACCN_ADDR1` VARCHAR(250) NULL DEFAULT NULL ;
ALTER TABLE `clickargo2`.`T_CORE_ACCN`  CHANGE COLUMN `ACCN_PROV` `ACCN_PROV` VARCHAR(20) NULL DEFAULT NULL ;

insert ignore into clickargo2.T_CORE_ACCN(ACCN_ID, ACCN_STATUS, ACCN_NAME, ACCN_NAME_OTH, ACCN_TYPE
, ACCN_COY_REGN, ACCN_ADDR1, ACCN_ADDR2, ACCN_ADDR3, ACCN_PCODE, ACCN_CITY, ACCN_PROV, ACCN_CTYCODE, ACCN_TEL, ACCN_FAX
, ACCN_EMAIL,  ACCN_DT_REG)
	select ACCN_ID, 'A', `NAME`, `NAME`, ACCN_TYPE, VAT_NO, ADDR1, ADDR2, ADDR3, PCODE, CITY, PROV, CTYCODE, TEL, FAX, EMAIL, REG_DATE 
    from TMP_COMPANY where ACCN_TYPE is not null;

    
ALTER TABLE `clickargo2`.`T_CORE_USR`  CHANGE COLUMN `USR_PWD` `USR_PWD` VARCHAR(100) NULL DEFAULT NULL ;

insert ignore into clickargo2.T_CORE_USR(USR_UID, USR_ACCNID, USR_STATUS, USR_TYPE_ONLINE, USR_TYPE_MBOX
, USR_NAME, USR_EMAIL, USR_DT_REG, USR_DT_COMM, USR_PWD, USR_DT_PWD_LUPD, USR_LOGIN_INVCNT, USR_MBOX_ID) 
SELECT USER_ID, ACCN_ID, 'A','Y', 'N', USER_NAME, EMAIL, REG_DATE, sysdate(), ENCRYPT_PWD, sysdate(), 0, '' 
FROM ctMigration.TMP_USER where ACCN_ID in (select ACCN_ID from clickargo2.T_CORE_ACCN);

update clickargo2.T_CORE_USR set USR_CTYCODE = 'SG' where USR_CTYCODE is null;

-- ignore into
insert ignore into  clickargo2.T_CK_CT_VEH(VH_ID, VH_TYPE, VH_STATE, VH_COMPANY, VH_PLATE_NO, VH_LENGTH, VH_WIDTH, VH_HEIGHT, VH_WEIGHT, VH_VOLUME, VH_CHASSIS_NO
,  VH_GPS_IMEI, VH_STATUS, VH_DT_CREATE, VH_UID_CREATE )
select TRUCK_ID, TRUCK_TYPE_ID, 'UNASSIGNED', ACCN_ID,  PLATE_NO, LENGTH, WIDTH, HEIGHT, WEIGHT, VOLUME, CHASSIS_NO, GPS_IMEI, 'A', sysdate(), 'sys' FROM ctMigration.TMP_TRUCK;

--

/*
replace into clickargo2.T_CK_CT_LOCATION(LOC_ID, LOC_TYPE, LOC_COMPANY, LOC_NAME, LOC_ADDRESS, LOC_STATUS, LOC_DT_CREATE, LOC_UID_CREATE)
SELECT LOC_ID, 'ADDRESS', ACCN_ID, NAME, ADDRESS, 'A', sysdate(), 'sys' FROM ctMigration.TMP_LOC
where ACCN_ID in (select ACCN_ID from clickargo2.T_CORE_ACCN);
*/
-- contract
-- TO
insert IGNORE clickargo2.T_CK_CT_CONTRACT_CHARGE(CONC_ID, CONC_PLTFEE_AMT, CONC_PLTFEE_TYPE, CONC_ADDTAX_AMT, CONC_ADDTAX_TYPE, CONC_WHTAX_AMT, CONC_WHTAX_TYPE
, CONC_STATUS, CONC_DT_CREATE, CONC_UID_CREATE)
 select TO_CONC_ID,  TO_PLTFEE_AMT, TO_PLTFEE_TYPE, TO_ADDTAX_AMT, TO_ADDTAX_TYPE, TO_WHTAX_AMT, TO_WHTAX_TYPE
 , 'A', sysdate(), 'sys' from ctMigration.TMP_CONTRACT;
 
 -- FF
 insert IGNORE clickargo2.T_CK_CT_CONTRACT_CHARGE(CONC_ID, CONC_PLTFEE_AMT, CONC_PLTFEE_TYPE, CONC_ADDTAX_AMT, CONC_ADDTAX_TYPE, CONC_WHTAX_AMT, CONC_WHTAX_TYPE
, CONC_STATUS, CONC_DT_CREATE, CONC_UID_CREATE)
 select FF_CONC_ID, CO_FF_PLTFEE_AMT, CO_FF_PLTFEE_TYPE, CO_FF_ADDTAX_AMT, CO_FF_ADDTAX_TYPE, CO_FF_WHTAX_AMT, CO_FF_WHTAX_TYPE
 , 'A', sysdate(), 'sys' from ctMigration.TMP_CONTRACT;
 
insert  IGNORE into clickargo2.T_CK_CT_CONTRACT(CON_ID, CON_NAME, CON_CCY, CON_DT_START, CON_DT_END, CON_TO, CON_CHARGE_TO, CON_PAYTERM_TO
, CON_CO_FF, CON_CHARGE_CO_FF, CON_PAYTERM_CO_FF, CON_STATUS, CON_DT_CREATE, CON_UID_CREATE)
select CON_ID, CONTRACT_NAME, CCY, DT_START, DT_END, TO_ACCN_ID, TO_CONC_ID, 30, FF_ACCN_ID,  FF_CONC_ID, 30, 'A', sysdate(), 'sys'
FROM ctMigration.TMP_CONTRACT
where TO_ACCN_ID in (select ACCN_ID from clickargo2.T_CORE_ACCN) and FF_ACCN_ID in (select ACCN_ID from clickargo2.T_CORE_ACCN);

update clickargo2.T_CK_CT_CONTRACT as cc join (
	select CON_ID, CONTRACT_NAME  FROM ctMigration.TMP_CONTRACT
	) as tc
    on cc.CON_ID = tc.CON_ID
    set cc.CON_NAME = tc.CONTRACT_NAME
    where tc.CONTRACT_NAME is not null
;

insert ignore into clickargo2.T_CK_CT_FF_CO(FFCO_ID, FFCO_FF, FFCO_CO, FFCO_STATUS, FFCO_DT_CREATE)
select FFCO_CONC_ID, FF_ACCN_ID, FFCO_ACCN_ID, 'A', sysdate() from ctMigration.TMP_CONTRACT where FFCO_CONC_ID is not null;


-- credit limit
INSERT ignore INTO `clickargo2`.`T_CK_CREDIT_SUMMARY` (`CRS_ID`, `CRS_SERVICE_TYPE`, `CRS_COMPANY`, `CRS_AMT`, `CRS_RESERVE`, `CRS_UTILIZED`, `CRS_BALANCE`
, `CRS_CCY`, `CRS_STATUS`, `CRS_DT_CREATE`, `CRS_UID_CREATE`)
VALUES ('CJS000001', 'CLICTRUCK', 'DSVAS', '10000000000.00', '0.00', '0.00', '10000000000.00', 'IDR', 'A', '2023-12-12 14:10:09', 'sys');

INSERT ignore INTO `clickargo2`.`T_CK_CREDIT` (`CR_ID`, `CR_SERVICE_TYPE`, `CR_COMPANY`, `CR_STATE`, `CR_AMT`, `CR_TXN_CAP`, `CR_CCY`, `CR_DT_START`, `CR_DT_END`, `CR_STATUS`, `CR_DT_CREATE`)
 VALUES ('CR_DSV', 'CLICTRUCK', 'DSVAS', 'APPROVED', '100000.00', '100000.00', 'IDR', '2023-11-16 15:23:00', '2040-05-30 00:00:00', 'A', '2023-11-27 08:56:59');

-- user role


insert ignore into clickargo2.T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE)
SELECT USR_UID, 'CKT', 'OFFICER', 'N', 'A', SYSDATE(), 'SYS', SYSDATE(), 'SYS','N' FROM clickargo2.T_CORE_USR;

insert ignore into clickargo2.T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE)
SELECT USR_UID, 'CKT', 'ADMIN', 'N', 'A', SYSDATE(), 'SYS', SYSDATE(), 'SYS','N' FROM clickargo2.T_CORE_USR;

insert ignore into clickargo2.T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE)
SELECT USR_UID, 'CKT', 'FF_ADMIN', 'N', 'A', SYSDATE(), 'SYS', SYSDATE(), 'SYS','N' FROM clickargo2.T_CORE_USR
where USR_ACCNID in (SELECT ACCN_ID FROM clickargo2.T_CORE_ACCN where ACCN_TYPE = 'ACC_TYPE_FF');

insert ignore into clickargo2.T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE)
SELECT USR_UID, 'CKT', 'OP_ADMIN_WJ', 'N', 'A', SYSDATE(), 'SYS', SYSDATE(), 'SYS','N' FROM clickargo2.T_CORE_USR
where USR_ACCNID in (SELECT ACCN_ID FROM clickargo2.T_CORE_ACCN where ACCN_TYPE = 'ACC_TYPE_TO_WJ');

insert ignore into clickargo2.T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE)
SELECT USR_UID, 'CKT', 'OP_ADMIN', 'N', 'A', SYSDATE(), 'SYS', SYSDATE(), 'SYS','N' FROM clickargo2.T_CORE_USR
where USR_ACCNID in (SELECT ACCN_ID FROM clickargo2.T_CORE_ACCN where ACCN_TYPE = 'ACC_TYPE_TO');
-- 

-- delete FROM clickargo2.T_CK_CT_CONTRACT where CON_ID IN ('CKCTCONC000012', 'CKCTCONC000111', 'CKCTCONC000072', 'CKCTCONC000099');

-- driver
-- delete from clickargo2.T_CK_CT_DRV;

replace into clickargo2.T_CK_CT_DRV(DRV_ID, DRV_NAME, DRV_STATE, DRV_COMPANY, DRV_MOBILE_ID
, DRV_STATUS, DRV_DT_CREATE, DRV_UID_CREATE)
SELECT DRV_ID, NAME, 'UNASSIGNED', ACCN_ID, USER_NAME
	, 'A',sysdate(), 'sys'  FROM ctMigration.TMP_DRV
where ACCN_ID in (select ACCN_ID from clickargo2.T_CORE_ACCN);


update clickargo2.T_CK_CT_DRV set DRV_MOBILE_ID = trim(DRV_MOBILE_ID);
update clickargo2.T_CK_CT_DRV SET DRV_MOBILE_PASSWORD = md5(concat(DRV_MOBILE_ID, '123'));  -- only md5 mobileId.

update clickargo2.T_CK_CT_DRV set DRV_PHONE = '-' where DRV_PHONE is null;
update clickargo2.T_CK_CT_DRV set DRV_EMAIL = '-' where DRV_EMAIL is null;


update TMP_USER SET ENCRYPT_PWD = md5(concat(USER_ID,PWD));

update clickargo2.T_CORE_USR set USR_PWD = md5(concat(USR_UID,USR_EMAIL,'123'))
where USR_UID like 'CKUS%' 
	and USR_ACCNID != 'GLI';
-- where USR_PWD is null ;

update clickargo2.T_CORE_USR set USR_NAME = ucase(USR_NAME);
update clickargo2.T_CORE_ACCN set ACCN_NAME = ucase(ACCN_NAME);

INSERT INTO clickargo2.T_CK_SVC_SUB
(SUB_ID, SUB_TYPE, SUB_STATE, SUB_SUBSCRIBER, SUB_DT_START, SUB_DT_VALID, SUB_AUTO_RENEW
	, SUB_UID_VERIFY, SUB_DT_VERIFY, SUB_UID_APPROVE, SUB_DT_APPROVE
    , SUB_STATUS, SUB_DT_CREATE, SUB_UID_CREATE, SUB_DT_LUPD, SUB_UID_LUPD)
select CONCAT('CK0',ROUND(rand()*100000)), 'CLICTRUCK', 'APR',accn_id, '2023-01-01 00:00:00', '2033-01-01 00:00:00','N'
	,'sys',sysdate(),'sys',sysdate(),'A',sysdate(),'sys',null,null
from clickargo2.T_CORE_ACCN tca 
where tca.ACCN_ID not in (select distinct SUB_SUBSCRIBER from  clickargo2.T_CK_SVC_SUB where SUB_TYPE='CLICTRUCK' and SUB_STATE='APR' );

-- 
INSERT INTO `clickargo2`.`T_CK_CT_LOCATION` (`LOC_ID`, `LOC_TYPE`, `LOC_COMPANY`, `LOC_NAME`, `LOC_ADDRESS`, `LOC_DT_START`, `LOC_DT_END`, `LOC_STATUS`, `LOC_DT_CREATE`, `LOC_UID_CREATE`)
 VALUES ('LOC_DSVAS_OTH', 'REGION', 'DSVASR', 'OTHER', 'OTHER', '2023-02-01 00:00:00', '2040-02-01 00:00:00', 'A', SYSDATE(), 'SYS');
 
INSERT INTO `clickargo2`.`T_CK_CT_LOCATION` (`LOC_ID`, `LOC_TYPE`, `LOC_COMPANY`, `LOC_NAME`, `LOC_ADDRESS`, `LOC_DT_START`, `LOC_DT_END`, `LOC_STATUS`, `LOC_DT_CREATE`, `LOC_UID_CREATE`)
 VALUES ('LOC_DSVAS_OTH2', 'REGION', 'DSVASR', 'OTHER2', 'OTHER2', '2023-02-01 00:00:00', '2040-02-01 00:00:00', 'A', SYSDATE(), 'SYS');

INSERT IGNORE INTO `clickargo2`.`T_CORE_ACCN_CONFIG` (`ACFG_ACCNID`, `ACFG_KEY`, `ACFG_VAL`, `ACFG_DESC`, `ACFG_VALID_FROM_DT`, `ACFG_VALID_TO_DT`, `ACFG_SEQ`, `ACFG_STATUS`, `ACFG_DT_CREATE`, `ACFG_UID_CREATE`, `ACFG_DT_LUPD`) 
VALUES ('DSVASR', 'MOBILE_ENABLED', 'Y', 'MOBILE_ENABLED', '2023-09-13 09:43:40', '2023-09-13 09:43:40', '1', 'A', '2023-09-13 09:43:40', 'SYS', '2023-11-23 11:09:37');

REPLACE INTO `clickargo2`.`T_CORE_ACCN_CONFIG` (`ACFG_ACCNID`, `ACFG_KEY`, `ACFG_VAL`, `ACFG_DESC`, `ACFG_VALID_FROM_DT`, `ACFG_VALID_TO_DT`, `ACFG_SEQ`, `ACFG_STATUS`, `ACFG_DT_CREATE`, `ACFG_UID_CREATE`, `ACFG_DT_LUPD`, `ACFG_UID_LUPD`) 
VALUES ('DSVAS', 'FINANCE_OPTIONS', 'NON_FINANCE', 'FINANCE_OPTIONS', '2023-12-03 22:12:10', '2023-12-03 22:12:10', '1', 'A', '2023-12-03 22:12:10', 'GLI_U001', '2023-12-03 22:12:10', 'GLI_U001');
