-- T_CORE_MENU_EX
INSERT INTO clickargo2.T_CORE_MENU_EX
(MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)
VALUES('CKDO_OA_010000', 'CKDO', 'Disbursement', 'Disbursement', 'Disbursement', 'Disbursement', 10000, '/opadmin/disbursement', 'table_view', NULL, 'A', '2022-11-15 09:06:44', 'SYS', '2022-11-15 09:06:44', 'SYS');
INSERT INTO clickargo2.T_CORE_MENU_EX
(MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)
VALUES('CKDO_OA_020000', 'CKDO', 'Operations Administration', 'Operations Administration', 'Operations Administration', 'Operations Administration', 20000, '', 'admin_panel_settings', NULL, 'A', '2024-01-12 14:54:57', 'SYS', '2024-01-12 14:54:57', 'SYS');
INSERT INTO clickargo2.T_CORE_MENU_EX
(MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)
VALUES('CKDO_OA_020100', 'CKDO', '', '', 'Static Virtual Account', 'Static Virtual Account', 20100, '/opadmin/staticva', NULL, 'CKDO_OA_020000', 'A', '2024-01-12 14:54:57', 'SYS', '2024-01-12 14:54:57', 'SYS');

-- T_CORE_PERM_EX
INSERT INTO clickargo2.T_CORE_PERM_EX
(PERM_ID, PERM_GROUP, PERM_APPS, PERM_MODULE, PERM_TYPE, PERM_SERVICE, PERM_SERVICE_URI, PERM_MENU, PERM_MENU_NAME, PERM_DOC_TYPE, PERM_DOC_CODE, PERM_ACTION, PERM_DESC, PERM_DESC_OTH, PERM_ACCESS, PERM_DT_ACTIVE, PERM_DT_DEACTIVE, PERM_STATUS, PERM_DT_CREATE, PERM_UID_CREATE, PERM_DT_LUPD, PERM_UID_LUPD)
VALUES('PM083', 'Y', 'CKDO', NULL, 'M', NULL, NULL, 'CKDO_OA_010000', 'Disbursement', NULL, NULL, NULL, 'Disbursement', 'Disbursement', 'R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO clickargo2.T_CORE_PERM_EX
(PERM_ID, PERM_GROUP, PERM_APPS, PERM_MODULE, PERM_TYPE, PERM_SERVICE, PERM_SERVICE_URI, PERM_MENU, PERM_MENU_NAME, PERM_DOC_TYPE, PERM_DOC_CODE, PERM_ACTION, PERM_DESC, PERM_DESC_OTH, PERM_ACCESS, PERM_DT_ACTIVE, PERM_DT_DEACTIVE, PERM_STATUS, PERM_DT_CREATE, PERM_UID_CREATE, PERM_DT_LUPD, PERM_UID_LUPD)
VALUES('PM084', 'Y', 'CKDO', NULL, 'M', NULL, NULL, 'CKDO_OA_020000', 'Operations Administration', NULL, NULL, NULL, 'Operations Administration', 'Operations Administration', 'R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');


-- T_CORE_GRANT_ROLE_EX

-- DELETE T_CORE_GRANT_ROLE_EX
DELETE FROM clickargo2.T_CORE_GRANT_ROLE_EX
WHERE GNTRLEX_APPS_CODE='CKDO' AND GNTRLEX_ROLE_ID='ADMIN' AND GNTRLEX_PERM_ID='PM002';
DELETE FROM clickargo2.T_CORE_GRANT_ROLE_EX
WHERE GNTRLEX_APPS_CODE='CKDO' AND GNTRLEX_ROLE_ID='ADMIN' AND GNTRLEX_PERM_ID='PM003';
DELETE FROM clickargo2.T_CORE_GRANT_ROLE_EX
WHERE GNTRLEX_APPS_CODE='CKDO' AND GNTRLEX_ROLE_ID='ADMIN' AND GNTRLEX_PERM_ID='PM004';
DELETE FROM clickargo2.T_CORE_GRANT_ROLE_EX
WHERE GNTRLEX_APPS_CODE='CKDO' AND GNTRLEX_ROLE_ID='ADMIN' AND GNTRLEX_PERM_ID='PM005';
DELETE FROM clickargo2.T_CORE_GRANT_ROLE_EX
WHERE GNTRLEX_APPS_CODE='CKDO' AND GNTRLEX_ROLE_ID='ADMIN' AND GNTRLEX_PERM_ID='PM007';
DELETE FROM clickargo2.T_CORE_GRANT_ROLE_EX
WHERE GNTRLEX_APPS_CODE='CKDO' AND GNTRLEX_ROLE_ID='OPERATIONS' AND GNTRLEX_PERM_ID='PM068';

-- ADD NEW T_CORE_GRANT_ROLE_EX
INSERT INTO clickargo2.T_CORE_GRANT_ROLE_EX
(GNTRLEX_APPS_CODE, GNTRLEX_ROLE_ID, GNTRLEX_PERM_ID, GNTRLEX_STATUS, GNTRLEX_DT_CREATE, GNTRLEX_UID_CREATE, GNTRLEX_DT_LUPD, GNTRLEX_UID_LUPD)
VALUES('CKDO', 'ADMIN', 'PM067', 'A', '2024-01-12 14:55:01', 'SYS', NULL, NULL);
INSERT INTO clickargo2.T_CORE_GRANT_ROLE_EX
(GNTRLEX_APPS_CODE, GNTRLEX_ROLE_ID, GNTRLEX_PERM_ID, GNTRLEX_STATUS, GNTRLEX_DT_CREATE, GNTRLEX_UID_CREATE, GNTRLEX_DT_LUPD, GNTRLEX_UID_LUPD)
VALUES('CKDO', 'ADMIN', 'PM084', 'A', '2024-01-12 14:55:01', 'SYS', NULL, NULL);
