package com.guudint.clickargo.task.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.common.model.TCkRecordDate;
import com.guudint.clickargo.job.model.TCkJob;
import com.guudint.clickargo.master.model.TCkMstShipmentType;
import com.guudint.clickargo.master.model.TCkMstTaskState;
import com.guudint.clickargo.master.model.TCkMstTaskType;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkTask generated by hbm2java
 */
@Entity
@Table(name = "T_CK_TASK")
public class TCkTask extends COAbstractEntity<TCkTask> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -6684966441533032174L;
	
	// Attributes
	/////////////
	private String tskId;
	private TCkJob TCkJob;
	private TCkMstShipmentType TCkMstShipmentType;
	private TCkMstTaskState TCkMstTaskState;
	private TCkMstTaskType TCkMstTaskType;
	private TCkRecordDate TCkRecordDate;
	private TCoreAccn TCoreAccnByTskFfAccn;
	private TCoreAccn TCoreAccnByTskCoAccn;
	private TCoreAccn TCoreAccnByTskSlAccn;
	private TCoreAccn TCoreAccnByTskOwnerAccn;
	private TCoreAccn TCoreAccnByTskToAccn;
	private String tskReference;
	private String tskRemarks;
	private Character tskStatus;
	private Date tskDtCreate;
	private String tskUidCreate;
	private Date tskDtLupd;
	private String tskUidLupd;

	// Constructors
	////////////////
	public TCkTask() {
	}

	/**
	 * @param tskId
	 * @param TCkJob
	 * @param TCkMstShipmentType
	 * @param TCkMstTaskState
	 * @param TCkMstTaskType
	 */
	public TCkTask(String tskId, TCkJob TCkJob, TCkMstShipmentType TCkMstShipmentType, TCkMstTaskState TCkMstTaskState,
			TCkMstTaskType TCkMstTaskType) {
		this.tskId = tskId;
		this.TCkJob = TCkJob;
		this.TCkMstShipmentType = TCkMstShipmentType;
		this.TCkMstTaskState = TCkMstTaskState;
		this.TCkMstTaskType = TCkMstTaskType;
	}

	/**
	 * @param tskId
	 * @param TCkJob
	 * @param TCkMstShipmentType
	 * @param TCkMstTaskState
	 * @param TCkMstTaskType
	 * @param TCkRecordDate
	 * @param tskReference
	 * @param tskRemarks
	 * @param tskStatus
	 * @param tskDtCreate
	 * @param tskUidCreate
	 * @param tskDtLupd
	 * @param tskUidLupd
	 */
	public TCkTask(String tskId, TCkJob TCkJob, TCkMstShipmentType TCkMstShipmentType, TCkMstTaskState TCkMstTaskState,
			TCkMstTaskType TCkMstTaskType, TCkRecordDate TCkRecordDate, TCoreAccn TCoreAccnByTskFfAccn, TCoreAccn TCoreAccnByTskCoAccn, 
			TCoreAccn TCoreAccnByTskSlAccn, TCoreAccn TCoreAccnByTskOwnerAccn, TCoreAccn TCoreAccnByTskToAccn, String tskReference, String tskRemarks,
			Character tskStatus, Date tskDtCreate, String tskUidCreate, Date tskDtLupd, String tskUidLupd) {
		this.tskId = tskId;
		this.TCkJob = TCkJob;
		this.TCkMstShipmentType = TCkMstShipmentType;
		this.TCkMstTaskState = TCkMstTaskState;
		this.TCkMstTaskType = TCkMstTaskType;
		this.TCkRecordDate = TCkRecordDate;
		this.TCoreAccnByTskFfAccn = TCoreAccnByTskFfAccn;
		this.TCoreAccnByTskCoAccn = TCoreAccnByTskFfAccn;
		this.TCoreAccnByTskSlAccn = TCoreAccnByTskSlAccn;
		this.TCoreAccnByTskOwnerAccn = TCoreAccnByTskOwnerAccn;
		this.TCoreAccnByTskToAccn = TCoreAccnByTskToAccn ;
		this.tskReference = tskReference;
		this.tskRemarks = tskRemarks;
		this.tskStatus = tskStatus;
		this.tskDtCreate = tskDtCreate;
		this.tskUidCreate = tskUidCreate;
		this.tskDtLupd = tskDtLupd;
		this.tskUidLupd = tskUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkTask o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

	
	// Properties
	/////////////
	@Id
	@Column(name = "TSK_ID", unique = true, nullable = false, length = 35)
	public String getTskId() {
		return this.tskId;
	}

	public void setTskId(String tskId) {
		this.tskId = tskId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TSK_JOB", nullable = false)
	public TCkJob getTCkJob() {
		return this.TCkJob;
	}

	public void setTCkJob(TCkJob TCkJob) {
		this.TCkJob = TCkJob;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TSK_SHIPMENT_TYPE", nullable = false)
	public TCkMstShipmentType getTCkMstShipmentType() {
		return this.TCkMstShipmentType;
	}

	public void setTCkMstShipmentType(TCkMstShipmentType TCkMstShipmentType) {
		this.TCkMstShipmentType = TCkMstShipmentType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TSK_STATE", nullable = false)
	public TCkMstTaskState getTCkMstTaskState() {
		return this.TCkMstTaskState;
	}

	public void setTCkMstTaskState(TCkMstTaskState TCkMstTaskState) {
		this.TCkMstTaskState = TCkMstTaskState;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TSK_TYPE", nullable = false)
	public TCkMstTaskType getTCkMstTaskType() {
		return this.TCkMstTaskType;
	}

	public void setTCkMstTaskType(TCkMstTaskType TCkMstTaskType) {
		this.TCkMstTaskType = TCkMstTaskType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TSK_DATES")
	public TCkRecordDate getTCkRecordDate() {
		return this.TCkRecordDate;
	}

	public void setTCkRecordDate(TCkRecordDate TCkRecordDate) {
		this.TCkRecordDate = TCkRecordDate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TSK_FF_ACCN")
	public TCoreAccn getTCoreAccnByTskFfAccn() {
		return this.TCoreAccnByTskFfAccn;
	}

	public void setTCoreAccnByTskFfAccn(TCoreAccn TCoreAccnByTskFfAccn) {
		this.TCoreAccnByTskFfAccn = TCoreAccnByTskFfAccn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TSK_CO_ACCN")
	public TCoreAccn getTCoreAccnByTskCoAccn() {
		return this.TCoreAccnByTskCoAccn;
	}

	public void setTCoreAccnByTskCoAccn(TCoreAccn TCoreAccnByTskCoAccn) {
		this.TCoreAccnByTskCoAccn = TCoreAccnByTskCoAccn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TSK_SL_ACCN")
	public TCoreAccn getTCoreAccnByTskSlAccn() {
		return this.TCoreAccnByTskSlAccn;
	}

	public void setTCoreAccnByTskSlAccn(TCoreAccn TCoreAccnByTskSlAccn) {
		this.TCoreAccnByTskSlAccn = TCoreAccnByTskSlAccn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TSK_OWNER_ACCN")
	public TCoreAccn getTCoreAccnByTskOwnerAccn() {
		return this.TCoreAccnByTskOwnerAccn;
	}

	public void setTCoreAccnByTskOwnerAccn(TCoreAccn TCoreAccnByTskOwnerAccn) {
		this.TCoreAccnByTskOwnerAccn = TCoreAccnByTskOwnerAccn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TSK_TO_ACCN")
	public TCoreAccn getTCoreAccnByTskToAccn() {
		return this.TCoreAccnByTskToAccn;
	}

	public void setTCoreAccnByTskToAccn(TCoreAccn TCoreAccnByTskToAccn) {
		this.TCoreAccnByTskToAccn = TCoreAccnByTskToAccn;
	}
	
	@Column(name = "TSK_REFERENCE")
	public String getTskReference() {
		return this.tskReference;
	}

	public void setTskReference(String tskReference) {
		this.tskReference = tskReference;
	}

	@Column(name = "TSK_REMARKS", length = 16777215)
	public String getTskRemarks() {
		return this.tskRemarks;
	}

	public void setTskRemarks(String tskRemarks) {
		this.tskRemarks = tskRemarks;
	}

	@Column(name = "TSK_STATUS", length = 1)
	public Character getTskStatus() {
		return this.tskStatus;
	}

	public void setTskStatus(Character tskStatus) {
		this.tskStatus = tskStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TSK_DT_CREATE", length = 19)
	public Date getTskDtCreate() {
		return this.tskDtCreate;
	}

	public void setTskDtCreate(Date tskDtCreate) {
		this.tskDtCreate = tskDtCreate;
	}

	@Column(name = "TSK_UID_CREATE", length = 35)
	public String getTskUidCreate() {
		return this.tskUidCreate;
	}

	public void setTskUidCreate(String tskUidCreate) {
		this.tskUidCreate = tskUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TSK_DT_LUPD", length = 19)
	public Date getTskDtLupd() {
		return this.tskDtLupd;
	}

	public void setTskDtLupd(Date tskDtLupd) {
		this.tskDtLupd = tskDtLupd;
	}

	@Column(name = "TSK_UID_LUPD", length = 35)
	public String getTskUidLupd() {
		return this.tskUidLupd;
	}

	public void setTskUidLupd(String tskUidLupd) {
		this.tskUidLupd = tskUidLupd;
	}

}
