package com.guudint.clickargo.task.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.master.model.TMstAttType;

/**
 * TCkTaskAttach generated by hbm2java
 */
@Entity
@Table(name = "T_CK_TASK_ATTACH")
public class TCkTaskAttach extends COAbstractEntity<TCkTaskAttach> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -7748177867580956179L;
	
	// Attributes
	//////////////
	private String attId;
	private TCkTask TCkTask;
	private TMstAttType TMstAttType;
	private String attName;
	private String attLoc;
	private Character attStatus;
	private Date attDtCreate;
	private String attUidCreate;
	private Date attDtLupd;
	private String attUidLupd;

	// Constructors
	////////////////
	public TCkTaskAttach() {
	}

	/**
	 * @param attId
	 * @param TCkTask
	 * @param TMstAttType
	 */
	public TCkTaskAttach(String attId, TCkTask TCkTask, TMstAttType TMstAttType) {
		this.attId = attId;
		this.TCkTask = TCkTask;
		this.TMstAttType = TMstAttType;
	}

	/**
	 * @param attId
	 * @param TCkTask
	 * @param TMstAttType
	 * @param attName
	 * @param attLoc
	 * @param attStatus
	 * @param attDtCreate
	 * @param attUidCreate
	 * @param attDtLupd
	 * @param attUidLupd
	 */
	public TCkTaskAttach(String attId, TCkTask TCkTask, TMstAttType TMstAttType, String attName, String attLoc,
			Character attStatus, Date attDtCreate, String attUidCreate, Date attDtLupd, String attUidLupd) {
		this.attId = attId;
		this.TCkTask = TCkTask;
		this.TMstAttType = TMstAttType;
		this.attName = attName;
		this.attLoc = attLoc;
		this.attStatus = attStatus;
		this.attDtCreate = attDtCreate;
		this.attUidCreate = attUidCreate;
		this.attDtLupd = attDtLupd;
		this.attUidLupd = attUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkTaskAttach o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}
	
	// Properties
	/////////////
	@Id
	@Column(name = "ATT_ID", unique = true, nullable = false, length = 35)
	public String getAttId() {
		return this.attId;
	}

	public void setAttId(String attId) {
		this.attId = attId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ATT_TASK", nullable = false)
	public TCkTask getTCkTask() {
		return this.TCkTask;
	}

	public void setTCkTask(TCkTask TCkTask) {
		this.TCkTask = TCkTask;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ATT_TYPE", nullable = false)
	public TMstAttType getTMstAttType() {
		return this.TMstAttType;
	}

	public void setTMstAttType(TMstAttType TMstAttType) {
		this.TMstAttType = TMstAttType;
	}

	@Column(name = "ATT_NAME", length = 256)
	public String getAttName() {
		return this.attName;
	}

	public void setAttName(String attName) {
		this.attName = attName;
	}

	@Column(name = "ATT_LOC", length = 1024)
	public String getAttLoc() {
		return this.attLoc;
	}

	public void setAttLoc(String attLoc) {
		this.attLoc = attLoc;
	}

	@Column(name = "ATT_STATUS", length = 1)
	public Character getAttStatus() {
		return this.attStatus;
	}

	public void setAttStatus(Character attStatus) {
		this.attStatus = attStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ATT_DT_CREATE", length = 19)
	public Date getAttDtCreate() {
		return this.attDtCreate;
	}

	public void setAttDtCreate(Date attDtCreate) {
		this.attDtCreate = attDtCreate;
	}

	@Column(name = "ATT_UID_CREATE", length = 35)
	public String getAttUidCreate() {
		return this.attUidCreate;
	}

	public void setAttUidCreate(String attUidCreate) {
		this.attUidCreate = attUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ATT_DT_LUPD", length = 19)
	public Date getAttDtLupd() {
		return this.attDtLupd;
	}

	public void setAttDtLupd(Date attDtLupd) {
		this.attDtLupd = attDtLupd;
	}

	@Column(name = "ATT_UID_LUPD", length = 35)
	public String getAttUidLupd() {
		return this.attUidLupd;
	}

	public void setAttUidLupd(String attUidLupd) {
		this.attUidLupd = attUidLupd;
	}
}
