package com.guudint.clickargo.tax.model;
// Generated 13 Jul 2023, 5:34:10 pm by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.beans.BeanUtils;

import com.guudint.clickargo.tax.dto.CkTaxInvoice;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkTaxInvoice generated by hbm2java
 */
@Entity
@Table(name = "T_CK_TAX_INVOICE")
public class TCkTaxInvoice extends COAbstractEntity<TCkTaxInvoice> {

	private static final long serialVersionUID = -7517468748698064138L;
	private String tiId;
	private TCoreAccn TCoreAccn;
	private String tiService;
	private String tiType;
	private String tiNo;
	private BigDecimal tiAmt;
	private String tiDoc;
	private Date tiDtUpload;
	private String tiUsrUpload;
	private String tiInvNo;
	private Date tiInvDtIssue;
	private String tiJobNo;
	private Character tiStatus;
	private Date tiDtCreate;
	private String tiUidCreate;
	private Date tiDtLupd;
	private String tiUidLupd;

	public TCkTaxInvoice() {
	}

	public TCkTaxInvoice(CkTaxInvoice ckTaxInvoice) {
		BeanUtils.copyProperties(ckTaxInvoice, this);
	}

	public TCkTaxInvoice(String tiId, String tiService, String tiNo, String tiDoc, String tiInvNo) {
		this.tiId = tiId;
		this.tiService = tiService;
		this.tiNo = tiNo;
		this.tiDoc = tiDoc;
		this.tiInvNo = tiInvNo;
	}

	public TCkTaxInvoice(String tiId, TCoreAccn TCoreAccn, String tiService, String tiNo, BigDecimal tiAmt,
			String tiDoc, Date tiDtUpload, String tiUsrUpload, String tiInvNo, Date tiInvDtIssue, String tiJobNo,
			Character tiStatus, Date tiDtCreate, String tiUidCreate, Date tiDtLupd, String tiUidLupd) {
		this.tiId = tiId;
		this.TCoreAccn = TCoreAccn;
		this.tiService = tiService;
		this.tiNo = tiNo;
		this.tiAmt = tiAmt;
		this.tiDoc = tiDoc;
		this.tiDtUpload = tiDtUpload;
		this.tiUsrUpload = tiUsrUpload;
		this.tiInvNo = tiInvNo;
		this.tiInvDtIssue = tiInvDtIssue;
		this.tiJobNo = tiJobNo;
		this.tiStatus = tiStatus;
		this.tiDtCreate = tiDtCreate;
		this.tiUidCreate = tiUidCreate;
		this.tiDtLupd = tiDtLupd;
		this.tiUidLupd = tiUidLupd;
	}

	@Id
	@Column(name = "TI_ID", unique = true, nullable = false, length = 35)
	public String getTiId() {
		return this.tiId;
	}

	public void setTiId(String tiId) {
		this.tiId = tiId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TI_ACCN")
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@Column(name = "TI_SERVICE", nullable = false, length = 35)
	public String getTiService() {
		return this.tiService;
	}

	public void setTiService(String tiService) {
		this.tiService = tiService;
	}

	@Column(name = "TI_TYPE")
	public String getTiType() {
		return tiType;
	}

	public void setTiType(String tiType) {
		this.tiType = tiType;
	}

	@Column(name = "TI_NO", nullable = false, length = 35)
	public String getTiNo() {
		return this.tiNo;
	}

	public void setTiNo(String tiNo) {
		this.tiNo = tiNo;
	}

	@Column(name = "TI_AMT", precision = 15)
	public BigDecimal getTiAmt() {
		return this.tiAmt;
	}

	public void setTiAmt(BigDecimal tiAmt) {
		this.tiAmt = tiAmt;
	}

	@Column(name = "TI_DOC", nullable = false, length = 1024)
	public String getTiDoc() {
		return this.tiDoc;
	}

	public void setTiDoc(String tiDoc) {
		this.tiDoc = tiDoc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TI_DT_UPLOAD", length = 19)
	public Date getTiDtUpload() {
		return this.tiDtUpload;
	}

	public void setTiDtUpload(Date tiDtUpload) {
		this.tiDtUpload = tiDtUpload;
	}

	@Column(name = "TI_USR_UPLOAD", length = 35)
	public String getTiUsrUpload() {
		return this.tiUsrUpload;
	}

	public void setTiUsrUpload(String tiUsrUpload) {
		this.tiUsrUpload = tiUsrUpload;
	}

	@Column(name = "TI_INV_NO", nullable = false, length = 256)
	public String getTiInvNo() {
		return this.tiInvNo;
	}

	public void setTiInvNo(String tiInvNo) {
		this.tiInvNo = tiInvNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TI_INV_DT_ISSUE", length = 19)
	public Date getTiInvDtIssue() {
		return this.tiInvDtIssue;
	}

	public void setTiInvDtIssue(Date tiInvDtIssue) {
		this.tiInvDtIssue = tiInvDtIssue;
	}

	@Column(name = "TI_JOB_NO", length = 35)
	public String getTiJobNo() {
		return this.tiJobNo;
	}

	public void setTiJobNo(String tiJobNo) {
		this.tiJobNo = tiJobNo;
	}

	@Column(name = "TI_STATUS", length = 1)
	public Character getTiStatus() {
		return this.tiStatus;
	}

	public void setTiStatus(Character tiStatus) {
		this.tiStatus = tiStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TI_DT_CREATE", length = 19)
	public Date getTiDtCreate() {
		return this.tiDtCreate;
	}

	public void setTiDtCreate(Date tiDtCreate) {
		this.tiDtCreate = tiDtCreate;
	}

	@Column(name = "TI_UID_CREATE", length = 35)
	public String getTiUidCreate() {
		return this.tiUidCreate;
	}

	public void setTiUidCreate(String tiUidCreate) {
		this.tiUidCreate = tiUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TI_DT_LUPD", length = 19)
	public Date getTiDtLupd() {
		return this.tiDtLupd;
	}

	public void setTiDtLupd(Date tiDtLupd) {
		this.tiDtLupd = tiDtLupd;
	}

	@Column(name = "TI_UID_LUPD", length = 35)
	public String getTiUidLupd() {
		return this.tiUidLupd;
	}

	public void setTiUidLupd(String tiUidLupd) {
		this.tiUidLupd = tiUidLupd;
	}

	@Override
	public int compareTo(TCkTaxInvoice o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
