package com.guudint.clickargo.tax.model;
// Generated 13 Jul 2023, 5:34:10 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.beans.BeanUtils;

import com.guudint.clickargo.tax.dto.CkTaxReport;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkTaxReport generated by hbm2java
 */
@Entity
@Table(name = "T_CK_TAX_REPORT")
public class TCkTaxReport extends COAbstractEntity<TCkTaxReport> {

	private static final long serialVersionUID = -7009935228773141951L;
	private String trId;
	private String trService;
	private String trName;
	private String trDoc;
	private Integer trNumRecords;
	private Character trStatus;
	private Date trDtCreate;
	private String trUidCreate;
	private Date trDtLupd;
	private String trUidLupd;

	public TCkTaxReport() {
	}

	public TCkTaxReport(CkTaxReport ckTaxReport) {
		BeanUtils.copyProperties(ckTaxReport, this);
	}

	public TCkTaxReport(String trId) {
		this.trId = trId;
	}

	public TCkTaxReport(String trId, String trName, String trDoc, Integer trNumRecords, Character trStatus,
			Date trDtCreate, String trUidCreate, Date trDtLupd, String trUidLupd) {
		this.trId = trId;
		this.trName = trName;
		this.trDoc = trDoc;
		this.trNumRecords = trNumRecords;
		this.trStatus = trStatus;
		this.trDtCreate = trDtCreate;
		this.trUidCreate = trUidCreate;
		this.trDtLupd = trDtLupd;
		this.trUidLupd = trUidLupd;
	}

	@Id

	@Column(name = "TR_ID", unique = true, nullable = false, length = 35)
	public String getTrId() {
		return this.trId;
	}

	public void setTrId(String trId) {
		this.trId = trId;
	}

	@Column(name = "TR_SERVICE", length = 45)
	public String getTrService() {
		return this.trService;
	}

	public void setTrService(String trService) {
		this.trService = trService;
	}

	@Column(name = "TR_NAME", length = 256)
	public String getTrName() {
		return this.trName;
	}

	public void setTrName(String trName) {
		this.trName = trName;
	}

	@Column(name = "TR_DOC", length = 1024)
	public String getTrDoc() {
		return this.trDoc;
	}

	public void setTrDoc(String trDoc) {
		this.trDoc = trDoc;
	}

	@Column(name = "TR_NUM_RECORDS")
	public Integer getTrNumRecords() {
		return this.trNumRecords;
	}

	public void setTrNumRecords(Integer trNumRecords) {
		this.trNumRecords = trNumRecords;
	}

	@Column(name = "TR_STATUS", length = 1)
	public Character getTrStatus() {
		return this.trStatus;
	}

	public void setTrStatus(Character trStatus) {
		this.trStatus = trStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TR_DT_CREATE", length = 19)
	public Date getTrDtCreate() {
		return this.trDtCreate;
	}

	public void setTrDtCreate(Date trDtCreate) {
		this.trDtCreate = trDtCreate;
	}

	@Column(name = "TR_UID_CREATE", length = 35)
	public String getTrUidCreate() {
		return this.trUidCreate;
	}

	public void setTrUidCreate(String trUidCreate) {
		this.trUidCreate = trUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TR_DT_LUPD", length = 19)
	public Date getTrDtLupd() {
		return this.trDtLupd;
	}

	public void setTrDtLupd(Date trDtLupd) {
		this.trDtLupd = trDtLupd;
	}

	@Column(name = "TR_UID_LUPD", length = 35)
	public String getTrUidLupd() {
		return this.trUidLupd;
	}

	public void setTrUidLupd(String trUidLupd) {
		this.trUidLupd = trUidLupd;
	}

	@Override
	public int compareTo(TCkTaxReport o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
