package com.guudint.clickargo.tax.model;
// Generated 21 Jun 2024, 2:16:22 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.beans.BeanUtils;

import com.guudint.clickargo.tax.dto.CkTaxSeq;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkTaxSeq generated by hbm2java
 */
@Entity
@Table(name = "T_CK_TAX_SEQ")
public class TCkTaxSeq extends COAbstractEntity<TCkTaxReport> {

	private static final long serialVersionUID = -1L;

	private String tsId;
	private String tsService;
	private String tsPrefix;
	private long tsRangeBegin;
	private long tsRangeEnd;
	private long tsRangeCurrent;
	private String tsRangeFormat;
	private Character tsStatus;
	private Date tsDtCreate;
	private String tsUidCreate;
	private Date tsDtLupd;
	private String tsUidLupd;

	public TCkTaxSeq() {
	}

	public TCkTaxSeq(CkTaxSeq ckTaxSeq) {
		BeanUtils.copyProperties(ckTaxSeq, this);
	}

	public TCkTaxSeq(String tsId) {
		this.tsId = tsId;
	}
	
	public TCkTaxSeq(String tsId, String tsPrefix, long tsRangeBegin, long tsRangeEnd, long tsRangeCurrent,
			String tsRangeFormat) {
		this.tsId = tsId;
		this.tsPrefix = tsPrefix;
		this.tsRangeBegin = tsRangeBegin;
		this.tsRangeEnd = tsRangeEnd;
		this.tsRangeCurrent = tsRangeCurrent;
		this.tsRangeFormat = tsRangeFormat;
	}

	public TCkTaxSeq(String tsId, String tsPrefix, long tsRangeBegin, long tsRangeEnd, long tsRangeCurrent,
			String tsRangeFormat, Character tsStatus, Date tsDtCreate, String tsUidCreate, Date tsDtLupd,
			String tsUidLupd) {
		this.tsId = tsId;
		this.tsPrefix = tsPrefix;
		this.tsRangeBegin = tsRangeBegin;
		this.tsRangeEnd = tsRangeEnd;
		this.tsRangeCurrent = tsRangeCurrent;
		this.tsRangeFormat = tsRangeFormat;
		this.tsStatus = tsStatus;
		this.tsDtCreate = tsDtCreate;
		this.tsUidCreate = tsUidCreate;
		this.tsDtLupd = tsDtLupd;
		this.tsUidLupd = tsUidLupd;
	}

	@Override
	public int compareTo(TCkTaxReport o) {
		return 0;
	}

	@Override
	public void init() {
	
	}
	
	@Id

	@Column(name = "TS_ID", unique = true, nullable = false, length = 35)
	public String getTsId() {
		return this.tsId;
	}

	public void setTsId(String tsId) {
		this.tsId = tsId;
	}

	@Column(name = "TS_SERVICE", nullable = false, length = 35)
	public String getTsService() {
		return this.tsService;
	}

	public void setTsService(String tsService) {
		this.tsService = tsService;
	}

	@Column(name = "TS_PREFIX", nullable = false, length = 35)
	public String getTsPrefix() {
		return this.tsPrefix;
	}

	public void setTsPrefix(String tsPrefix) {
		this.tsPrefix = tsPrefix;
	}

	@Column(name = "TS_RANGE_BEGIN", nullable = false)
	public long getTsRangeBegin() {
		return this.tsRangeBegin;
	}

	public void setTsRangeBegin(long tsRangeBegin) {
		this.tsRangeBegin = tsRangeBegin;
	}

	@Column(name = "TS_RANGE_END", nullable = false)
	public long getTsRangeEnd() {
		return this.tsRangeEnd;
	}

	public void setTsRangeEnd(long tsRangeEnd) {
		this.tsRangeEnd = tsRangeEnd;
	}

	@Column(name = "TS_RANGE_CURRENT", nullable = false)
	public long getTsRangeCurrent() {
		return this.tsRangeCurrent;
	}

	public void setTsRangeCurrent(long tsRangeCurrent) {
		this.tsRangeCurrent = tsRangeCurrent;
	}

	@Column(name = "TS_RANGE_FORMAT", nullable = false, length = 35)
	public String getTsRangeFormat() {
		return this.tsRangeFormat;
	}

	public void setTsRangeFormat(String tsRangeFormat) {
		this.tsRangeFormat = tsRangeFormat;
	}

	@Column(name = "TS_STATUS", length = 1)
	public Character getTsStatus() {
		return this.tsStatus;
	}

	public void setTsStatus(Character tsStatus) {
		this.tsStatus = tsStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TS_DT_CREATE", length = 19)
	public Date getTsDtCreate() {
		return this.tsDtCreate;
	}

	public void setTsDtCreate(Date tsDtCreate) {
		this.tsDtCreate = tsDtCreate;
	}

	@Column(name = "TS_UID_CREATE", length = 35)
	public String getTsUidCreate() {
		return this.tsUidCreate;
	}

	public void setTsUidCreate(String tsUidCreate) {
		this.tsUidCreate = tsUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TS_DT_LUPD", length = 19)
	public Date getTsDtLupd() {
		return this.tsDtLupd;
	}

	public void setTsDtLupd(Date tsDtLupd) {
		this.tsDtLupd = tsDtLupd;
	}

	@Column(name = "TS_UID_LUPD", length = 35)
	public String getTsUidLupd() {
		return this.tsUidLupd;
	}

	public void setTsUidLupd(String tsUidLupd) {
		this.tsUidLupd = tsUidLupd;
	}

}
