use ctMigration;

DROP TABLE IF EXISTS ctMigration.TMP_LOC;
CREATE TABLE ctMigration.TMP_LOC (
  `ID` varchar(70) NOT NULL ,
  `TYPE` varchar(35) DEFAULT NULL,
  `COMPANY` varchar(256) DEFAULT NULL,
  `NAME` varchar(256) DEFAULT NULL ,
  `ADDRESS` varchar(256) DEFAULT NULL ,
  `DT_START` datetime DEFAULT NULL ,
  `DT_END` datetime DEFAULT NULL ,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ;

-- delete demo data
delete from TMP_USER where COMPANY_ID in (SELECT ID FROM ctMigration.TMP_COMPANY
where NAME like '%demo%');

delete from TMP_USER where COMPANY_ID in (SELECT ID FROM ctMigration.TMP_COMPANY
where NAME like '%demo%');

delete from TMP_TRUCK where COMPANY in (SELECT ID FROM ctMigration.TMP_COMPANY
where NAME like '%demo%');

delete from TMP_LOC where COMPANY in (SELECT ID FROM ctMigration.TMP_COMPANY
where NAME like '%demo%');

delete from TMP_DRV where COMPANY in (SELECT ID FROM ctMigration.TMP_COMPANY
where NAME like '%demo%');

delete from TMP_CREDIT where COMPANY in (SELECT ID FROM ctMigration.TMP_COMPANY
where NAME like '%demo%');

delete from TMP_CONTRACT where `TO` in (SELECT ID FROM ctMigration.TMP_COMPANY
where NAME like '%demo%');

delete from TMP_CONTRACT where CO_FF in (SELECT ID FROM ctMigration.TMP_COMPANY
where NAME like '%demo%');

-- delete guud user
delete FROM ctMigration.TMP_USER
where EMAIL like '%GUUD%';

-- -------------- process TMP_COMPANY ----------
-- upper case
update TMP_COMPANY set NAME  = UCASE(NAME), ADDR1 = UCASE(ADDR1) ;

-- ADD ACCOUNT ID
ALTER TABLE `ctMigration`.`TMP_COMPANY`  ADD COLUMN `ACCN_ID` VARCHAR(45) NULL FIRST;
ALTER TABLE `ctMigration`.`TMP_COMPANY`  ADD COLUMN `ACCN_TYPE` VARCHAR(45) AFTER `TYPE`;

UPDATE TMP_COMPANY AS c JOIN
 ( SELECT ID, row_number() OVER (ORDER BY REG_DATE) AS rn 
      FROM TMP_COMPANY
    ) AS sub
  ON  c.ID = sub.ID
SET c.ACCN_ID = concat('CK', lpad(sub.rn,4,'0') );

UPDATE TMP_COMPANY set ACCN_TYPE = 'ACC_TYPE_CO' where `TYPE` like '%CO%';
UPDATE TMP_COMPANY set ACCN_TYPE = 'ACC_TYPE_FF' where `TYPE` like '%FF%';
UPDATE TMP_COMPANY set ACCN_TYPE = 'ACC_TYPE_TO' where `TYPE` like '%TC%';

UPDATE TMP_COMPANY set VAT_NO = length(SUBSTRING(VAT_NO, 1,20)) where length(VAT_NO) > 20;

-- -------------- process TMP_USER ----------
-- upper case

ALTER TABLE `ctMigration`.`TMP_USER`  ADD COLUMN `USER_ID` VARCHAR(45) NULL FIRST;
ALTER TABLE `ctMigration`.`TMP_USER`  ADD COLUMN `ENCRYPT_PWD` VARCHAR(100) AFTER `PWD`;
ALTER TABLE `ctMigration`.`TMP_USER`  ADD COLUMN `ACCN_ID` VARCHAR(35) AFTER `USER_ID`;
ALTER TABLE `ctMigration`.`TMP_USER`  ADD COLUMN `USER_NAME` VARCHAR(35) AFTER `ACCN_ID`;
ALTER TABLE `ctMigration`.`TMP_USER`  CHANGE COLUMN `PWD` `PWD` VARCHAR(100) NULL DEFAULT NULL ;

UPDATE `ctMigration`.`TMP_USER` set PWD = concat(EMAIL, '123');
UPDATE TMP_USER SET PWD = ucase(PWD);
-- update ENCRYPT_PWD with Java codes

UPDATE TMP_USER AS c JOIN
 ( SELECT UID, row_number() OVER (ORDER BY REG_DATE, EMAIL) AS rn 
      FROM TMP_USER
    ) AS sub
  ON  c.UID = sub.UID
SET c.USER_ID = concat('CKU', lpad(sub.rn,5,'0') );

UPDATE TMP_USER AS c JOIN
 ( SELECT ACCN_ID, ID FROM TMP_COMPANY
    ) AS sub
  ON  c.COMPANY_ID = sub.ID
SET c.ACCN_ID = sub.ACCN_ID;

UPDATE TMP_USER SET USER_NAME = substring(EMAIL, 1, LOCATE('@', EMAIL)-1);
UPDATE TMP_USER SET USER_NAME = ucase(USER_NAME);
UPDATE TMP_USER SET EMAIL = ucase(EMAIL);

-- -----------
/*
drop table if exists clickargo2.T_TMP_USER;

CREATE TABLE clickargo2.`T_TMP_USER` (
  `USER_ID` varchar(35) NOT NULL,
  `USER_PLAIN_PWD` varchar(100)  NULL,
  `USER_ENCRYPT_PWD` varchar(100)  NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
*/
-- insert into clickargo2.T_TMP_USER(USER_ID, USER_PLAIN_PWD) SELECT USER_ID, PWD FROM ctMigration.TMP_USER;
/*
update TMP_USER as u join
( select USER_ID, USER_ENCRYPT_PWD from clickargo2.T_TMP_USER
	) as sub
on u.USER_ID = sub.USER_ID
set ENCRYPT_PWD = USER_ENCRYPT_PWD;
*/

update TMP_USER as u join
( select USER_ID, USER_PLAIN_PWD, USER_ENCRYPT_PWD from clickargo2.T_TMP_USER
	) as sub
on u.PWD = sub.USER_PLAIN_PWD
set ENCRYPT_PWD = USER_ENCRYPT_PWD
where ENCRYPT_PWD is null;

-- ----------- process TMP_TRUCK
ALTER TABLE `ctMigration`.`TMP_TRUCK` ADD COLUMN `TRUCK_ID` VARCHAR(45) NULL FIRST;
ALTER TABLE `ctMigration`.`TMP_TRUCK` ADD COLUMN `ACCN_ID` VARCHAR(100) AFTER `TRUCK_ID`;
ALTER TABLE `ctMigration`.`TMP_TRUCK` ADD COLUMN `TRUCK_TYPE_ID` VARCHAR(100) AFTER `ACCN_ID`;

update TMP_TRUCK set TYPE  = UCASE(TYPE) ;

UPDATE TMP_TRUCK AS c JOIN
 ( SELECT ID, row_number() OVER (ORDER BY concat(ID, PLATE_NO, CHASSIS_NO)) AS rn 
      FROM TMP_TRUCK
    ) AS sub
  ON  c.ID = sub.ID
SET c.TRUCK_ID = concat('CKCTVEH', lpad(sub.rn,6,'0') );

UPDATE TMP_TRUCK AS c JOIN
 ( SELECT ACCN_ID, ID FROM TMP_COMPANY
    ) AS sub
  ON  c.COMPANY = sub.ID
SET c.ACCN_ID = sub.ACCN_ID;

-- --- 
UPDATE ctMigration.TMP_TRUCK SET TYPE = 'CONTAINER 20FT' WHERE TYPE = '20';
UPDATE ctMigration.TMP_TRUCK SET TYPE = 'CONTAINER 40FT' WHERE TYPE = '40';

update ctMigration.TMP_TRUCK set type = trim(type);

INSERT INTO clickargo2.T_CK_CT_MST_VEH_TYPE(VHTY_ID, VHTY_NAME, VHTY_DESC, VHTY_DESC_OTH, VHTY_STATUS, VHTY_DT_CREATE, VHTY_UID_CREATE)
SELECT DISTINCT TYPE, TYPE, TYPE, TYPE, 'A', SYSDATE(), 'SYS' FROM ctMigration.TMP_TRUCK
where TYPE NOT IN (SELECT VHTY_NAME FROM clickargo2.T_CK_CT_MST_VEH_TYPE)
group by TYPE;

-- replace blank character in type id
UPDATE clickargo2.T_CK_CT_MST_VEH_TYPE t 
SET VHTY_ID = REPLACE(VHTY_ID, ' ', ''); 

UPDATE ctMigration.TMP_TRUCK AS c JOIN
 ( (SELECT VHTY_ID, VHTY_NAME FROM clickargo2.T_CK_CT_MST_VEH_TYPE)
    ) AS sub
  ON  TRIM(c.TYPE) = TRIM(sub.VHTY_NAME)
SET c.TRUCK_TYPE_ID = sub.VHTY_ID;

-- ----
ALTER TABLE `ctMigration`.`TMP_DRV` ADD COLUMN `DRV_ID` VARCHAR(45) NULL FIRST;
ALTER TABLE `ctMigration`.`TMP_DRV` ADD COLUMN `ACCN_ID` VARCHAR(100) AFTER `DRV_ID`;

update TMP_DRV set NAME  = UCASE(NAME) ;

UPDATE TMP_DRV AS c JOIN
 ( SELECT UID, row_number() OVER (ORDER BY UID) AS rn 
      FROM TMP_DRV
    ) AS sub
  ON  c.UID = sub.UID
SET c.DRV_ID = concat('CKCTDRV', lpad(sub.rn,6,'0') );

UPDATE TMP_DRV AS c JOIN
 ( SELECT ACCN_ID, ID FROM TMP_COMPANY
    ) AS sub
  ON  c.COMPANY = sub.ID
SET c.ACCN_ID = sub.ACCN_ID;

-- ----------- location

ALTER TABLE `ctMigration`.`TMP_LOC` ADD COLUMN `LOC_ID` VARCHAR(45) NULL FIRST;
ALTER TABLE `ctMigration`.`TMP_LOC` ADD COLUMN `ACCN_ID` VARCHAR(100) AFTER `LOC_ID`;

/*
update TMP_LOC set ADDRESS  = UCASE(ADDRESS) ;
-- first 3 worlds
update ctMigration.TMP_LOC set name = replace(SUBSTRING_INDEX(ADDRESS,' ',3),',','');

UPDATE TMP_LOC AS c JOIN
 ( SELECT ID, row_number() OVER (ORDER BY ID) AS rn 
      FROM TMP_LOC
    ) AS sub
  ON  c.ID = sub.ID
SET c.LOC_ID = concat('CKCTLOC', lpad(sub.rn,6,'0') );

UPDATE TMP_LOC AS c JOIN
 ( SELECT ACCN_ID, ID FROM TMP_COMPANY
    ) AS sub
  ON  c.COMPANY = sub.ID
SET c.ACCN_ID = sub.ACCN_ID;
*/
-- contract

ALTER TABLE `ctMigration`.`TMP_CONTRACT` ADD COLUMN `CON_ID` VARCHAR(45) NULL FIRST;
ALTER TABLE `ctMigration`.`TMP_CONTRACT` ADD COLUMN `TO_ACCN_ID` VARCHAR(100) AFTER `CON_ID`;
ALTER TABLE `ctMigration`.`TMP_CONTRACT` ADD COLUMN `FF_ACCN_ID` VARCHAR(100) AFTER `TO_ACCN_ID`;
ALTER TABLE `ctMigration`.`TMP_CONTRACT` ADD COLUMN `TO_CONC_ID` VARCHAR(100) AFTER `FF_ACCN_ID`;
ALTER TABLE `ctMigration`.`TMP_CONTRACT` ADD COLUMN `FF_CONC_ID` VARCHAR(100) AFTER `TO_CONC_ID`;


UPDATE TMP_CONTRACT AS c JOIN
 ( SELECT ID, row_number() OVER (ORDER BY ID) AS rn 
      FROM TMP_CONTRACT
    ) AS sub
  ON  c.ID = sub.ID
SET c.CON_ID = concat('CKCTCONC', lpad(sub.rn,6,'0') );

UPDATE TMP_CONTRACT AS c JOIN
 ( SELECT ID, row_number() OVER (ORDER BY ID) AS rn 
      FROM TMP_CONTRACT
    ) AS sub
  ON  c.ID = sub.ID
SET c.TO_CONC_ID = concat('CKCTCCHT', lpad(sub.rn,6,'0') );

UPDATE TMP_CONTRACT AS c JOIN
 ( SELECT ID, row_number() OVER (ORDER BY ID) AS rn 
      FROM TMP_CONTRACT
    ) AS sub
  ON  c.ID = sub.ID
SET c.FF_CONC_ID = concat('CKCTCCHF', lpad(sub.rn,6,'0') );


UPDATE TMP_CONTRACT AS c JOIN
 ( SELECT ACCN_ID, ID FROM TMP_COMPANY
    ) AS sub
  ON  c.TO = sub.ID
SET c.TO_ACCN_ID = sub.ACCN_ID;

UPDATE TMP_CONTRACT AS c JOIN
 ( SELECT ACCN_ID, ID FROM TMP_COMPANY
    ) AS sub
  ON  c.CO_FF = sub.ID
SET c.FF_ACCN_ID = sub.ACCN_ID;

-- 
ALTER TABLE `ctMigration`.`TMP_CREDIT` 
CHANGE COLUMN `SERVICE_TYPE` `SERVICE_TYPE` VARCHAR(9) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '' ,
CHANGE COLUMN `STATE` `STATE` VARCHAR(9) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '' ,
CHANGE COLUMN `CCY` `CCY` VARCHAR(3) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '' ,
CHANGE COLUMN `USR_VERIFY` `USR_VERIFY` VARCHAR(3) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '' ,
CHANGE COLUMN `DT_VERIFY` `DT_VERIFY` DATETIME NULL DEFAULT NULL ,
CHANGE COLUMN `USR_APPROVE` `USR_APPROVE` VARCHAR(3) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT '' ,
CHANGE COLUMN `DT_APPROVE` `DT_APPROVE` DATETIME NULL DEFAULT NULL ;

-- Credit Limit
ALTER TABLE `ctMigration`.`TMP_CREDIT` ADD COLUMN `CR_ID` VARCHAR(45) DEFAULT NULL FIRST;
ALTER TABLE `ctMigration`.`TMP_CREDIT` ADD COLUMN `CJN_ID` VARCHAR(100) AFTER `CR_ID`;
ALTER TABLE `ctMigration`.`TMP_CREDIT` ADD COLUMN `ACCN_ID` VARCHAR(100) AFTER `CJN_ID`;
ALTER TABLE `ctMigration`.`TMP_CREDIT` ADD COLUMN `CJS_ID` VARCHAR(100) AFTER `CJN_ID`;

UPDATE TMP_CREDIT AS c JOIN
 ( SELECT COMPANY, DT_START, AMT, row_number() OVER (ORDER BY COMPANY, DT_START, AMT) AS rn 
      FROM TMP_CREDIT
    ) AS sub
  ON  c.COMPANY = sub.COMPANY and c.DT_START = sub.DT_START and c.AMT = sub.AMT
SET c.CR_ID = concat('CR', lpad(sub.rn,6,'0') );

UPDATE TMP_CREDIT AS c JOIN
 ( SELECT COMPANY, DT_START, AMT, row_number() OVER (ORDER BY COMPANY, DT_START, AMT) AS rn 
      FROM TMP_CREDIT
    ) AS sub
  ON  c.COMPANY = sub.COMPANY and c.DT_START = sub.DT_START and c.AMT = sub.AMT
SET c.CJN_ID = concat('CJN', lpad(sub.rn,6,'0') );

UPDATE TMP_CREDIT AS c JOIN
 ( SELECT COMPANY, DT_START, AMT, row_number() OVER (ORDER BY COMPANY, DT_START, AMT) AS rn 
      FROM TMP_CREDIT
    ) AS sub
  ON  c.COMPANY = sub.COMPANY and c.DT_START = sub.DT_START and c.AMT = sub.AMT
SET c.CJS_ID = concat('CJS', lpad(sub.rn,6,'0') );


UPDATE TMP_CREDIT AS c JOIN
 ( SELECT ACCN_ID, ID FROM TMP_COMPANY
    ) AS sub
  ON  c.COMPANY = sub.ID
SET c.ACCN_ID = sub.ACCN_ID;

-- -------------- insert into T_CORE_ACCN ----------
-- -----------
ALTER TABLE `clickargo2`.`T_CORE_ACCN`  CHANGE COLUMN `ACCN_ADDR1` `ACCN_ADDR1` VARCHAR(250) NULL DEFAULT NULL ;
ALTER TABLE `clickargo2`.`T_CORE_ACCN`  CHANGE COLUMN `ACCN_PROV` `ACCN_PROV` VARCHAR(20) NULL DEFAULT NULL ;

insert ignore into clickargo2.T_CORE_ACCN(ACCN_ID, ACCN_STATUS, ACCN_NAME, ACCN_NAME_OTH, ACCN_TYPE
, ACCN_COY_REGN, ACCN_ADDR1, ACCN_ADDR2, ACCN_ADDR3, ACCN_PCODE, ACCN_CITY, ACCN_PROV, ACCN_CTYCODE, ACCN_TEL, ACCN_FAX
, ACCN_EMAIL,  ACCN_DT_REG)
	select ACCN_ID, 'A', `NAME`, `NAME`, ACCN_TYPE, VAT_NO, ADDR1, ADDR2, ADDR3, PCODE, CITY, PROV, CTYCODE, TEL, FAX, EMAIL, REG_DATE 
    from TMP_COMPANY where ACCN_TYPE is not null
		and ACCN_ID in (select ACCN_ID from ctMigration.SAGE_BANK_ACCOUNT);
    
ALTER TABLE `clickargo2`.`T_CORE_USR`  CHANGE COLUMN `USR_PWD` `USR_PWD` VARCHAR(100) NULL DEFAULT NULL ;

insert ignore into clickargo2.T_CORE_USR(USR_UID, USR_ACCNID, USR_STATUS, USR_TYPE_ONLINE, USR_TYPE_MBOX
, USR_NAME, USR_EMAIL, USR_DT_REG, USR_DT_COMM, USR_PWD, USR_DT_PWD_LUPD, USR_LOGIN_INVCNT, USR_MBOX_ID) 
SELECT USER_ID, ACCN_ID, 'A','Y', 'N', USER_NAME, EMAIL, REG_DATE, sysdate(), ENCRYPT_PWD, sysdate(), 0, '' 
FROM ctMigration.TMP_USER where ACCN_ID in (select ACCN_ID from clickargo2.T_CORE_ACCN);

update clickargo2.T_CORE_USR set USR_CTYCODE = 'ID' where USR_CTYCODE is null;

-- ignore into
insert ignore into  clickargo2.T_CK_CT_VEH(VH_ID, VH_TYPE, VH_STATE, VH_COMPANY, VH_PLATE_NO, VH_LENGTH, VH_WIDTH, VH_HEIGHT, VH_WEIGHT, VH_VOLUME, VH_CHASSIS_NO
,  VH_GPS_IMEI, VH_STATUS, VH_DT_CREATE, VH_UID_CREATE )
select TRUCK_ID, TRUCK_TYPE_ID, 'UNASSIGNED', ACCN_ID,  PLATE_NO, LENGTH, WIDTH, HEIGHT, WEIGHT, VOLUME, CHASSIS_NO, GPS_IMEI, 'A', sysdate(), 'sys' FROM ctMigration.TMP_TRUCK;

--
replace into clickargo2.T_CK_CT_DRV(DRV_ID, DRV_NAME, DRV_STATE, DRV_COMPANY, DRV_STATUS, DRV_DT_CREATE, DRV_UID_CREATE)
SELECT DRV_ID, NAME, 'UNASSIGNED', ACCN_ID, 'A',sysdate(), 'sys'  FROM ctMigration.TMP_DRV
where ACCN_ID in (select ACCN_ID from clickargo2.T_CORE_ACCN);

/*
replace into clickargo2.T_CK_CT_LOCATION(LOC_ID, LOC_TYPE, LOC_COMPANY, LOC_NAME, LOC_ADDRESS, LOC_STATUS, LOC_DT_CREATE, LOC_UID_CREATE)
SELECT LOC_ID, 'ADDRESS', ACCN_ID, NAME, ADDRESS, 'A', sysdate(), 'sys' FROM ctMigration.TMP_LOC
where ACCN_ID in (select ACCN_ID from clickargo2.T_CORE_ACCN);
*/
-- contract
-- TO
insert IGNORE clickargo2.T_CK_CT_CONTRACT_CHARGE(CONC_ID, CONC_PLTFEE_AMT, CONC_PLTFEE_TYPE, CONC_ADDTAX_AMT, CONC_ADDTAX_TYPE, CONC_WHTAX_AMT, CONC_WHTAX_TYPE
, CONC_STATUS, CONC_DT_CREATE, CONC_UID_CREATE)
 select TO_CONC_ID,  TO_PLTFEE_AMT, TO_PLTFEE_TYPE, TO_ADDTAX_AMT, TO_ADDTAX_TYPE, TO_WHTAX_AMT, TO_WHTAX_TYPE
 , 'A', sysdate(), 'sys' from ctMigration.TMP_CONTRACT;
 
 -- FF
 insert IGNORE clickargo2.T_CK_CT_CONTRACT_CHARGE(CONC_ID, CONC_PLTFEE_AMT, CONC_PLTFEE_TYPE, CONC_ADDTAX_AMT, CONC_ADDTAX_TYPE, CONC_WHTAX_AMT, CONC_WHTAX_TYPE
, CONC_STATUS, CONC_DT_CREATE, CONC_UID_CREATE)
 select FF_CONC_ID, CO_FF_PLTFEE_AMT, CO_FF_PLTFEE_TYPE, CO_FF_ADDTAX_AMT, CO_FF_ADDTAX_TYPE, CO_FF_WHTAX_AMT, CO_FF_WHTAX_TYPE
 , 'A', sysdate(), 'sys' from ctMigration.TMP_CONTRACT;
 
insert  IGNORE into clickargo2.T_CK_CT_CONTRACT(CON_ID, CON_NAME, CON_CCY, CON_DT_START, CON_DT_END, CON_TO, CON_CHARGE_TO, CON_PAYTERM_TO
, CON_CO_FF, CON_CHARGE_CO_FF, CON_PAYTERM_CO_FF, CON_STATUS, CON_DT_CREATE, CON_UID_CREATE)
select CON_ID, CON_ID, CCY, DT_START, DT_END, TO_ACCN_ID, TO_CONC_ID, 30, FF_ACCN_ID,  FF_CONC_ID, 30, 'A', sysdate(), 'sys'
FROM ctMigration.TMP_CONTRACT
where TO_ACCN_ID in (select ACCN_ID from clickargo2.T_CORE_ACCN) and FF_ACCN_ID in (select ACCN_ID from clickargo2.T_CORE_ACCN);

-- credit limit
insert ignore into clickargo2.T_CK_CREDIT(CR_ID, CR_SERVICE_TYPE, CR_COMPANY, CR_STATE, CR_AMT, CR_CCY, CR_DT_START, CR_DT_END
, CR_USR_VERIFY, CR_DT_VERIFY, CR_USR_APPROVE, CR_DT_APPROVE, CR_STATUS, CR_DT_CREATE, CR_UID_CREATE)
select CR_ID, SERVICE_TYPE, ACCN_ID, STATE, AMT, CCY, DT_START, DT_END
, USR_VERIFY, DT_VERIFY, USR_APPROVE, DT_APPROVE, 'A', sysdate(), 'sys' FROM ctMigration.TMP_CREDIT
where ACCN_ID in (select ACCN_ID from clickargo2.T_CORE_ACCN);

update clickargo2.T_CK_CREDIT c set CR_STATE = 'APPROVED';

INSERT ignore INTO `clickargo2`.`T_CK_MST_JOURNAL_TXN_TYPE` (`JTT_ID`, `JTT_NAME`, `JTT_DESC`, `JTT_DESC_OTH`, `JTT_STATUS`, `JTT_DT_CREATE`, `JTT_UID_CREATE`) 
VALUES ('JOB_TRANSFERED', 'JOB_TRANSFERED', 'JOB_TRANSFERED', 'JOB_TRANSFERED', 'A', '2023-05-30 00:00:00', 'SYS');

insert ignore into clickargo2.T_CK_CREDIT_JOURNAL(CJN_ID, CJN_SERVICE_TYPE, CJN_COMPANY, CJN_TXN_TYPE
, CJN_RESERVE, CJN_UTILIZED, CJN_CCY, CJN_STATUS, CJN_DT_CREATE, CJN_UID_CREATE)
select CJN_ID, SERVICE_TYPE, ACCN_ID, 'JOB_TRANSFERED', 0, AMT_USED, CCY, 'A',sysdate(),'sys'
 from ctMigration.TMP_CREDIT
where ACCN_ID in (select ACCN_ID from clickargo2.T_CORE_ACCN);

insert ignore into clickargo2.T_CK_CREDIT_SUMMARY(CRS_ID, CRS_SERVICE_TYPE, CRS_COMPANY, CRS_AMT, CRS_RESERVE, CRS_UTILIZED, CRS_BALANCE
	, CRS_CCY, CRS_STATUS, CRS_DT_CREATE, CRS_UID_CREATE )
select CJS_ID, 'CLICTRUCK', ACCN_ID, AMT, 0,AMT_USED, AMT-AMT_USED, CCY, 'A', sysdate(),'sys' FROM ctMigration.TMP_CREDIT
where ACCN_ID in (select ACCN_ID from clickargo2.T_CORE_ACCN) ;

-- user role


insert ignore into clickargo2.T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE)
SELECT USR_UID, 'CKT', 'OFFICER', 'N', 'A', SYSDATE(), 'SYS', SYSDATE(), 'SYS','N' FROM clickargo2.T_CORE_USR;

insert ignore into clickargo2.T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE)
SELECT USR_UID, 'CKT', 'ADMIN', 'N', 'A', SYSDATE(), 'SYS', SYSDATE(), 'SYS','N' FROM clickargo2.T_CORE_USR;

insert ignore into clickargo2.T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE)
SELECT USR_UID, 'CKT', 'FF_FINANCE', 'N', 'A', SYSDATE(), 'SYS', SYSDATE(), 'SYS','N' FROM clickargo2.T_CORE_USR
where USR_ACCNID in (SELECT ACCN_ID FROM clickargo2.T_CORE_ACCN where ACCN_TYPE = 'ACC_TYPE_CO');

insert ignore into clickargo2.T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE)
SELECT USR_UID, 'CKT', 'FINANCE', 'N', 'A', SYSDATE(), 'SYS', SYSDATE(), 'SYS','N' FROM clickargo2.T_CORE_USR
where USR_ACCNID in (SELECT ACCN_ID FROM clickargo2.T_CORE_ACCN where ACCN_TYPE = 'ACC_TYPE_TO');

insert ignore into clickargo2.T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE)
SELECT USR_UID, 'CKT', 'OP_ADMIN', 'N', 'A', SYSDATE(), 'SYS', SYSDATE(), 'SYS','N' FROM clickargo2.T_CORE_USR
where USR_ACCNID in (SELECT ACCN_ID FROM clickargo2.T_CORE_ACCN where ACCN_TYPE = 'ACC_TYPE_TO');
-- 

-- delete FROM clickargo2.T_CK_CT_CONTRACT where CON_ID IN ('CKCTCONC000012', 'CKCTCONC000111', 'CKCTCONC000072', 'CKCTCONC000099');

update clickargo2.T_CK_CT_DRV set DRV_PHONE = '-' where DRV_PHONE is null;
update clickargo2.T_CK_CT_DRV set DRV_EMAIL = '-' where DRV_EMAIL is null;

update clickargo2.T_CORE_USR as u join
( select USER_ID, USER_PLAIN_PWD, USER_ENCRYPT_PWD from clickargo2.T_TMP_USER
	) as sub
on concat(u.USR_EMAIL,'123') = sub.USER_PLAIN_PWD
set USR_PWD = USER_ENCRYPT_PWD
where USR_UID like 'CKU%' ;
-- where USR_PWD is null ;

update clickargo2.T_CORE_USR set USR_NAME = ucase(USR_NAME);
update clickargo2.T_CORE_ACCN set ACCN_NAME = ucase(ACCN_NAME);


