package com.guudint.clickargo.common.model;
// Generated 12 Mar 2024, 11:43:37 am by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkAccn generated by hbm2java
 */
@Entity
@Table(name = "T_CK_ACCN")
public class TCkAccn extends COAbstractEntity<TCkAccn>{

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1L;
	
	private String caccnId;
	private TCoreAccn TCoreAccn;
	private String caccnFinancingType;
	private String caccnFinancer;
	private String caccnExcelTemplate;
	private String caccnExcelTemplateExample;
	private String caccnEpodJrxml; //CACCN_EPOD_JRXML
	private String caccnEpodService; //CACCN_EPOD_SERVICE
	//private BigDecimal caccnCreditLimit;
	private String caccnIspotSubAccn;
	
	private Boolean caccnWhatsapp;
	private Boolean caccnSms;
	private Boolean caccnCo2x;
	private Boolean caccnRoutePlanning;
	
	private char caccnStatus;
	private Date caccnDtCreate;
	private String caccnUidCreate;
	private Date caccnDtLupd;
	private String caccnUidLupd;

	public TCkAccn() {
	}

	public TCkAccn(String caccnId) {
		this.caccnId = caccnId;
	}

	public TCkAccn(TCoreAccn TCoreAccn, String caccnFinancer, char caccnStatus, Date caccnDtCreate,
			String caccnUidCreate) {
		this.TCoreAccn = TCoreAccn;
		this.caccnFinancer = caccnFinancer;
		this.caccnStatus = caccnStatus;
		this.caccnDtCreate = caccnDtCreate;
		this.caccnUidCreate = caccnUidCreate;
	}

	public TCkAccn(TCoreAccn TCoreAccn, String caccnFinancer, char caccnStatus, Date caccnDtCreate,
			String caccnUidCreate, Date caccnDtLupd, String caccnUidLupd) {
		this.TCoreAccn = TCoreAccn;
		this.caccnFinancer = caccnFinancer;
		this.caccnStatus = caccnStatus;
		this.caccnDtCreate = caccnDtCreate;
		this.caccnUidCreate = caccnUidCreate;
		this.caccnDtLupd = caccnDtLupd;
		this.caccnUidLupd = caccnUidLupd;
	}


	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkAccn o) {
		return 0;
	}

	@Override
	public void init() {
		
	}

	@Id
	@Column(name = "CACCN_ID", unique = true, nullable = false, length = 70)
	public String getCaccnId() {
		return this.caccnId;
	}

	public void setCaccnId(String caccnId) {
		this.caccnId = caccnId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CACCN_ID", nullable = false, insertable = false, updatable = false)
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@Column(name = "CACCN_FINANCER", length = 70)
	public String getCaccnFinancer() {
		return this.caccnFinancer;
	}

	public void setCaccnFinancer(String caccnFinancer) {
		this.caccnFinancer = caccnFinancer;
	}

	@Column(name = "CACCN_EXCEL_TEMPLATE", length = 65535)
	public String getCaccnExcelTemplate() {
		return this.caccnExcelTemplate;
	}

	public void setCaccnExcelTemplate(String caccnExcelTemplate) {
		this.caccnExcelTemplate = caccnExcelTemplate;
	}

	@Column(name = "CACCN_EXCEL_TEMPLATE_EXAMPLE")
	public String getCaccnExcelTemplateExample() {
		return caccnExcelTemplateExample;
	}

	public void setCaccnExcelTemplateExample(String caccnExcelTemplateExample) {
		this.caccnExcelTemplateExample = caccnExcelTemplateExample;
	}

	@Column(name = "CACCN_EPOD_JRXML")
	public String getCaccnEpodJrxml() {
		return caccnEpodJrxml;
	}

	public void setCaccnEpodJrxml(String caccnEpodJrxml) {
		this.caccnEpodJrxml = caccnEpodJrxml;
	}

	@Column(name = "CACCN_EPOD_SERVICE")
	public String getCaccnEpodService() {
		return caccnEpodService;
	}

	public void setCaccnEpodService(String caccnEpodService) {
		this.caccnEpodService = caccnEpodService;
	}

	@Column(name = "CACCN_ISPOT_SUB_ACCN")
	public String getCaccnIspotSubAccn() {
		return caccnIspotSubAccn;
	}

	public void setCaccnIspotSubAccn(String caccnIspotSubAccn) {
		this.caccnIspotSubAccn = caccnIspotSubAccn;
	}

	@Column(name = "CACCN_WHATSAPP")
	public Boolean getCaccnWhatsapp() {
		return this.caccnWhatsapp;
	}

	public void setCaccnWhatsapp(Boolean caccnWhatsapp) {
		this.caccnWhatsapp = caccnWhatsapp;
	}

	@Column(name = "CACCN_SMS")
	public Boolean getCaccnSms() {
		return this.caccnSms;
	}

	public void setCaccnSms(Boolean caccnSms) {
		this.caccnSms = caccnSms;
	}

	@Column(name = "CACCN_CO2X")
	public Boolean getCaccnCo2x() {
		return this.caccnCo2x;
	}

	public void setCaccnCo2x(Boolean caccnCo2x) {
		this.caccnCo2x = caccnCo2x;
	}

	@Column(name = "CACCN_ROUTE_PLANNING")
	public Boolean getCaccnRoutePlanning() {
		return this.caccnRoutePlanning;
	}

	public void setCaccnRoutePlanning(Boolean caccnRoutePlanning) {
		this.caccnRoutePlanning = caccnRoutePlanning;
	}

	/*-
	@Column(name = "CACCN_CREDIT_LIMIT", precision = 15)
	public BigDecimal getCaccnCreditLimit() {
		return this.caccnCreditLimit;
	}

	public void setCaccnCreditLimit(BigDecimal caccnCreditLimit) {
		this.caccnCreditLimit = caccnCreditLimit;
	}
*/
	@Column(name = "CACCN_STATUS", nullable = false, length = 1)
	public char getCaccnStatus() {
		return this.caccnStatus;
	}

	public void setCaccnStatus(char caccnStatus) {
		this.caccnStatus = caccnStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CACCN_DT_CREATE", nullable = false, length = 19)
	public Date getCaccnDtCreate() {
		return this.caccnDtCreate;
	}

	public void setCaccnDtCreate(Date caccnDtCreate) {
		this.caccnDtCreate = caccnDtCreate;
	}

	@Column(name = "CACCN_UID_CREATE", nullable = false, length = 35)
	public String getCaccnUidCreate() {
		return this.caccnUidCreate;
	}

	public void setCaccnUidCreate(String caccnUidCreate) {
		this.caccnUidCreate = caccnUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CACCN_DT_LUPD", length = 19)
	public Date getCaccnDtLupd() {
		return this.caccnDtLupd;
	}

	public void setCaccnDtLupd(Date caccnDtLupd) {
		this.caccnDtLupd = caccnDtLupd;
	}

	@Column(name = "CACCN_UID_LUPD", length = 35)
	public String getCaccnUidLupd() {
		return this.caccnUidLupd;
	}

	public void setCaccnUidLupd(String caccnUidLupd) {
		this.caccnUidLupd = caccnUidLupd;
	}

	@Column(name = "CACCN_FINANCING_TYPE", length = 35)
	public String getCaccnFinancingType() {
		return caccnFinancingType;
	}

	
	public void setCaccnFinancingType(String caccnFinancingType) {
		this.caccnFinancingType = caccnFinancingType;
	}

	
}
