package com.guudint.clickargo.common.model;
// Generated 20 Mar 2024, 1:27:52 pm by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkAccnOpm generated by hbm2java
 */
@Entity
@Table(name = "T_CK_ACCN_OPM")
public class TCkAccnOpm extends COAbstractEntity<TCkAccnOpm>{

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1L;
	//public static final String PREFIX_ID = "CAO";
	
	private String caoId;
	private TCoreAccn TCoreAccn;
	private String caoType;
	private String caoFinancer;
	private BigDecimal caoCreditLimit;
	private Date caoDtApprove;
	private Date caoDtExpiry;
	private Date caoDtClose;
	private Date caoDtSuspend;
	private Date caoDtUnsuspend;
	private Character caoStatus;
	private Date caoDtCreate;
	private String caoUidCreate;
	private Date caoDtLupd;
	private String caoUidLupd;

	public TCkAccnOpm() {
	}

	public TCkAccnOpm(String caoId) {
		this.caoId = caoId;
	}

	public TCkAccnOpm(String caoId, TCoreAccn TCoreAccn, String caoType, String caoFinancer, BigDecimal caoCreditLimit,
			Date caoDtApprove, Date caoDtExpiry, Date caoDtClose, Date caoDtSuspend, Date caoDtUnsuspend,
			Character caoStatus, Date caoDtCreate, String caoUidCreate, Date caoDtLupd, String caoUidLupd) {
		this.caoId = caoId;
		this.TCoreAccn = TCoreAccn;
		this.caoType = caoType;
		this.caoFinancer = caoFinancer;
		this.caoCreditLimit = caoCreditLimit;
		this.caoDtApprove = caoDtApprove;
		this.caoDtExpiry = caoDtExpiry;
		this.caoDtClose = caoDtClose;
		this.caoDtSuspend = caoDtSuspend;
		this.caoDtUnsuspend = caoDtUnsuspend;
		this.caoStatus = caoStatus;
		this.caoDtCreate = caoDtCreate;
		this.caoUidCreate = caoUidCreate;
		this.caoDtLupd = caoDtLupd;
		this.caoUidLupd = caoUidLupd;
	}


	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkAccnOpm o) {
		return 0;
	}

	@Override
	public void init() {
		
	}

	@Id

	@Column(name = "CAO_ID", unique = true, nullable = false, length = 35)
	public String getCaoId() {
		return this.caoId;
	}

	public void setCaoId(String caoId) {
		this.caoId = caoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAO_ID", nullable = false, insertable = false, updatable = false)
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@Column(name = "CAO_TYPE", length = 2)
	public String getCaoType() {
		return this.caoType;
	}

	public void setCaoType(String caoType) {
		this.caoType = caoType;
	}

	@Column(name = "CAO_FINANCER", length = 35)
	public String getCaoFinancer() {
		return this.caoFinancer;
	}

	public void setCaoFinancer(String caoFinancer) {
		this.caoFinancer = caoFinancer;
	}

	@Column(name = "CAO_CREDIT_LIMIT", precision = 15)
	public BigDecimal getCaoCreditLimit() {
		return this.caoCreditLimit;
	}

	public void setCaoCreditLimit(BigDecimal caoCreditLimit) {
		this.caoCreditLimit = caoCreditLimit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CAO_DT_APPROVE", length = 19)
	public Date getCaoDtApprove() {
		return this.caoDtApprove;
	}

	public void setCaoDtApprove(Date caoDtApprove) {
		this.caoDtApprove = caoDtApprove;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CAO_DT_EXPIRY", length = 19)
	public Date getCaoDtExpiry() {
		return this.caoDtExpiry;
	}

	public void setCaoDtExpiry(Date caoDtExpiry) {
		this.caoDtExpiry = caoDtExpiry;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CAO_DT_CLOSE", length = 19)
	public Date getCaoDtClose() {
		return this.caoDtClose;
	}

	public void setCaoDtClose(Date caoDtClose) {
		this.caoDtClose = caoDtClose;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CAO_DT_SUSPEND", length = 19)
	public Date getCaoDtSuspend() {
		return this.caoDtSuspend;
	}

	public void setCaoDtSuspend(Date caoDtSuspend) {
		this.caoDtSuspend = caoDtSuspend;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CAO_DT_UNSUSPEND", length = 19)
	public Date getCaoDtUnsuspend() {
		return this.caoDtUnsuspend;
	}

	public void setCaoDtUnsuspend(Date caoDtUnsuspend) {
		this.caoDtUnsuspend = caoDtUnsuspend;
	}

	@Column(name = "CAO_STATUS", length = 1)
	public Character getCaoStatus() {
		return this.caoStatus;
	}

	public void setCaoStatus(Character caoStatus) {
		this.caoStatus = caoStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CAO_DT_CREATE", length = 19)
	public Date getCaoDtCreate() {
		return this.caoDtCreate;
	}

	public void setCaoDtCreate(Date caoDtCreate) {
		this.caoDtCreate = caoDtCreate;
	}

	@Column(name = "CAO_UID_CREATE", length = 35)
	public String getCaoUidCreate() {
		return this.caoUidCreate;
	}

	public void setCaoUidCreate(String caoUidCreate) {
		this.caoUidCreate = caoUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CAO_DT_LUPD", length = 19)
	public Date getCaoDtLupd() {
		return this.caoDtLupd;
	}

	public void setCaoDtLupd(Date caoDtLupd) {
		this.caoDtLupd = caoDtLupd;
	}

	@Column(name = "CAO_UID_LUPD", length = 35)
	public String getCaoUidLupd() {
		return this.caoUidLupd;
	}

	public void setCaoUidLupd(String caoUidLupd) {
		this.caoUidLupd = caoUidLupd;
	}

}
