package com.guudint.clickargo.common.model;
// Generated 4 Nov, 2022 4:34:47 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.master.model.TCkMstServiceType;
import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.core.model.TCoreApps;

/**
 * TCkComponentGuide generated by hbm2java
 */
@Entity
@Table(name = "T_CK_COMPONENT_GUIDE")
public class TCkComponentGuide extends COAbstractEntity<TCkComponentGuide> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 7876660134551481326L;
	
	// Attributes
	/////////////
	private String cmguId;
	private TCkMstServiceType TCkMstServiceType;
	private TCoreApps TCoreApps;
	private String cmguComponentId;
	private String cmguGuide;
	private String cmguGuideOth;
	private Character cmguStatus;
	private Date cmguDtCreate;
	private String cmguUidCreate;
	private Date cmguDtLupd;
	private String cmguUidLupd;

	// Constructors
	///////////////
	public TCkComponentGuide() {
	}

	/**
	 * @param cmguId
	 * @param TCoreApps
	 * @param cmguComponentId
	 */
	public TCkComponentGuide(String cmguId, TCoreApps TCoreApps, String cmguComponentId) {
		this.cmguId = cmguId;
		this.TCoreApps = TCoreApps;
		this.cmguComponentId = cmguComponentId;
	}

	/**
	 * @param cmguId
	 * @param TCkMstServiceType
	 * @param TCoreApps
	 * @param cmguComponentId
	 * @param cmguGuide
	 * @param cmguGuideOth
	 * @param cmguStatus
	 * @param cmguDtCreate
	 * @param cmguUidCreate
	 * @param cmguDtLupd
	 * @param cmguUidLupd
	 */
	public TCkComponentGuide(String cmguId, TCkMstServiceType TCkMstServiceType, TCoreApps TCoreApps,
			String cmguComponentId, String cmguGuide, String cmguGuideOth, Character cmguStatus, Date cmguDtCreate,
			String cmguUidCreate, Date cmguDtLupd, String cmguUidLupd) {
		this.cmguId = cmguId;
		this.TCkMstServiceType = TCkMstServiceType;
		this.TCoreApps = TCoreApps;
		this.cmguComponentId = cmguComponentId;
		this.cmguGuide = cmguGuide;
		this.cmguGuideOth = cmguGuideOth;
		this.cmguStatus = cmguStatus;
		this.cmguDtCreate = cmguDtCreate;
		this.cmguUidCreate = cmguUidCreate;
		this.cmguDtLupd = cmguDtLupd;
		this.cmguUidLupd = cmguUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	*/
	@Override
	public int compareTo(TCkComponentGuide o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	*/
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}
	
	// Properties
	/////////////
	@Id
	@Column(name = "CMGU_ID", unique = true, nullable = false, length = 35)
	public String getCmguId() {
		return this.cmguId;
	}

	public void setCmguId(String cmguId) {
		this.cmguId = cmguId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CMGU_SERVICE_TYPE")
	public TCkMstServiceType getTCkMstServiceType() {
		return this.TCkMstServiceType;
	}

	public void setTCkMstServiceType(TCkMstServiceType TCkMstServiceType) {
		this.TCkMstServiceType = TCkMstServiceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CMGU_APPS_CODE", nullable = false)
	public TCoreApps getTCoreApps() {
		return this.TCoreApps;
	}

	public void setTCoreApps(TCoreApps TCoreApps) {
		this.TCoreApps = TCoreApps;
	}

	@Column(name = "CMGU_COMPONENT_ID", nullable = false, length = 1024)
	public String getCmguComponentId() {
		return this.cmguComponentId;
	}

	public void setCmguComponentId(String cmguComponentId) {
		this.cmguComponentId = cmguComponentId;
	}

	@Column(name = "CMGU_GUIDE", length = 16777215)
	public String getCmguGuide() {
		return this.cmguGuide;
	}

	public void setCmguGuide(String cmguGuide) {
		this.cmguGuide = cmguGuide;
	}

	@Column(name = "CMGU_GUIDE_OTH", length = 16777215)
	public String getCmguGuideOth() {
		return this.cmguGuideOth;
	}

	public void setCmguGuideOth(String cmguGuideOth) {
		this.cmguGuideOth = cmguGuideOth;
	}

	@Column(name = "CMGU_STATUS", length = 1)
	public Character getCmguStatus() {
		return this.cmguStatus;
	}

	public void setCmguStatus(Character cmguStatus) {
		this.cmguStatus = cmguStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CMGU_DT_CREATE", length = 19)
	public Date getCmguDtCreate() {
		return this.cmguDtCreate;
	}

	public void setCmguDtCreate(Date cmguDtCreate) {
		this.cmguDtCreate = cmguDtCreate;
	}

	@Column(name = "CMGU_UID_CREATE", length = 35)
	public String getCmguUidCreate() {
		return this.cmguUidCreate;
	}

	public void setCmguUidCreate(String cmguUidCreate) {
		this.cmguUidCreate = cmguUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CMGU_DT_LUPD", length = 19)
	public Date getCmguDtLupd() {
		return this.cmguDtLupd;
	}

	public void setCmguDtLupd(Date cmguDtLupd) {
		this.cmguDtLupd = cmguDtLupd;
	}

	@Column(name = "CMGU_UID_LUPD", length = 35)
	public String getCmguUidLupd() {
		return this.cmguUidLupd;
	}

	public void setCmguUidLupd(String cmguUidLupd) {
		this.cmguUidLupd = cmguUidLupd;
	}
}
