package com.guudint.clickargo.common.model;
// Generated 7 Nov, 2022 5:51:04 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.core.model.TCoreApps;
import com.vcc.camelone.master.model.TMstAccnType;

/**
 * TCkFormControl generated by hbm2java
 */
@Entity
@Table(name = "T_CK_FORM_CONTROL")
public class TCkFormControl extends COAbstractEntity<TCkFormControl> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 5162367349172192778L;

	// Attributes
	/////////////
	private String ctrlId;
	private TCkMstEntityState TCkMstEntityState;
	private TCkMstEntityType TCkMstEntityType;
	private TCkMstFormAction TCkMstFormAction;
	private TCkMstFormType TCkMstFormType;
	private TCoreAccn TCoreAccn;
	private TMstAccnType TMstAccnType;
	private TCoreApps TCoreApps;
	private String ctrlUsrRole;
	private String ctrlFormActionMenu;
	private char ctrlStatus;
	private Date ctrlDtCreate;
	private String ctrlUidCreate;
	private Date ctrlDtLupd;
	private String ctrlUidLupd;

	// Constructors
	///////////////
	public TCkFormControl() {
	}

	/**
	 * @param ctrlId
	 * @param TCkMstEntityState
	 * @param TCkMstEntityType
	 * @param TCkMstFormAction
	 * @param TCkMstFormType
	 * @param TMstAccnType
	 * @param ctrlUsrRole
	 * @param ctrlStatus
	 */
	public TCkFormControl(String ctrlId, TCkMstEntityState TCkMstEntityState, TCkMstEntityType TCkMstEntityType,
			TCkMstFormAction TCkMstFormAction, TCkMstFormType TCkMstFormType, TMstAccnType TMstAccnType,
			String ctrlUsrRole, char ctrlStatus) {
		this.ctrlId = ctrlId;
		this.TCkMstEntityState = TCkMstEntityState;
		this.TCkMstEntityType = TCkMstEntityType;
		this.TCkMstFormAction = TCkMstFormAction;
		this.TCkMstFormType = TCkMstFormType;
		this.TMstAccnType = TMstAccnType;
		this.ctrlUsrRole = ctrlUsrRole;
		this.ctrlStatus = ctrlStatus;
	}

	/**
	 * @param ctrlId
	 * @param TCkMstEntityState
	 * @param TCkMstEntityType
	 * @param TCkMstFormAction
	 * @param TCkMstFormType
	 * @param TCoreAccn
	 * @param TMstAccnType
	 * @param ctrlUsrRole
	 * @param ctrlFormActionMenu
	 * @param ctrlStatus
	 * @param ctrlDtCreate
	 * @param ctrlUidCreate
	 * @param ctrlDtLupd
	 * @param ctrlUidLupd
	 */
	public TCkFormControl(String ctrlId, TCkMstEntityState TCkMstEntityState, TCkMstEntityType TCkMstEntityType,
			TCkMstFormAction TCkMstFormAction, TCkMstFormType TCkMstFormType, TCoreAccn TCoreAccn,
			TMstAccnType TMstAccnType, String ctrlUsrRole, String ctrlFormActionMenu, char ctrlStatus,
			Date ctrlDtCreate, String ctrlUidCreate, Date ctrlDtLupd, String ctrlUidLupd) {
		this.ctrlId = ctrlId;
		this.TCkMstEntityState = TCkMstEntityState;
		this.TCkMstEntityType = TCkMstEntityType;
		this.TCkMstFormAction = TCkMstFormAction;
		this.TCkMstFormType = TCkMstFormType;
		this.TCoreAccn = TCoreAccn;
		this.TMstAccnType = TMstAccnType;
		this.ctrlUsrRole = ctrlUsrRole;
		this.ctrlFormActionMenu = ctrlFormActionMenu;
		this.ctrlStatus = ctrlStatus;
		this.ctrlDtCreate = ctrlDtCreate;
		this.ctrlUidCreate = ctrlUidCreate;
		this.ctrlDtLupd = ctrlDtLupd;
		this.ctrlUidLupd = ctrlUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkFormControl o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	// Properties
	/////////////
	@Id
	@Column(name = "CTRL_ID", unique = true, nullable = false, length = 35)
	public String getCtrlId() {
		return this.ctrlId;
	}

	public void setCtrlId(String ctrlId) {
		this.ctrlId = ctrlId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTRL_ENTITY_STATE", nullable = false)
	public TCkMstEntityState getTCkMstEntityState() {
		return this.TCkMstEntityState;
	}

	public void setTCkMstEntityState(TCkMstEntityState TCkMstEntityState) {
		this.TCkMstEntityState = TCkMstEntityState;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTRL_ENTITY_TYPE", nullable = false)
	public TCkMstEntityType getTCkMstEntityType() {
		return this.TCkMstEntityType;
	}

	public void setTCkMstEntityType(TCkMstEntityType TCkMstEntityType) {
		this.TCkMstEntityType = TCkMstEntityType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTRL_FORM_ACTION", nullable = false)
	public TCkMstFormAction getTCkMstFormAction() {
		return this.TCkMstFormAction;
	}

	public void setTCkMstFormAction(TCkMstFormAction TCkMstFormAction) {
		this.TCkMstFormAction = TCkMstFormAction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTRL_FORM_TYPE", nullable = false)
	public TCkMstFormType getTCkMstFormType() {
		return this.TCkMstFormType;
	}

	public void setTCkMstFormType(TCkMstFormType TCkMstFormType) {
		this.TCkMstFormType = TCkMstFormType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTRL_ACCN")
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTRL_ACCN_TYPE", nullable = false)
	public TMstAccnType getTMstAccnType() {
		return this.TMstAccnType;
	}

	public void setTMstAccnType(TMstAccnType TMstAccnType) {
		this.TMstAccnType = TMstAccnType;
	}

	@Column(name = "CTRL_USR_ROLE", nullable = false, length = 35)
	public String getCtrlUsrRole() {
		return this.ctrlUsrRole;
	}

	public void setCtrlUsrRole(String ctrlUsrRole) {
		this.ctrlUsrRole = ctrlUsrRole;
	}

	@Column(name = "CTRL_FORM_ACTION_MENU")
	public String getCtrlFormActionMenu() {
		return this.ctrlFormActionMenu;
	}

	public void setCtrlFormActionMenu(String ctrlFormActionMenu) {
		this.ctrlFormActionMenu = ctrlFormActionMenu;
	}

	@Column(name = "CTRL_STATUS", nullable = false, length = 1)
	public char getCtrlStatus() {
		return this.ctrlStatus;
	}

	public void setCtrlStatus(char ctrlStatus) {
		this.ctrlStatus = ctrlStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CTRL_DT_CREATE", length = 19)
	public Date getCtrlDtCreate() {
		return this.ctrlDtCreate;
	}

	public void setCtrlDtCreate(Date ctrlDtCreate) {
		this.ctrlDtCreate = ctrlDtCreate;
	}

	@Column(name = "CTRL_UID_CREATE", length = 35)
	public String getCtrlUidCreate() {
		return this.ctrlUidCreate;
	}

	public void setCtrlUidCreate(String ctrlUidCreate) {
		this.ctrlUidCreate = ctrlUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CTRL_DT_LUPD", length = 19)
	public Date getCtrlDtLupd() {
		return this.ctrlDtLupd;
	}

	public void setCtrlDtLupd(Date ctrlDtLupd) {
		this.ctrlDtLupd = ctrlDtLupd;
	}

	@Column(name = "CTRL_UID_LUPD", length = 35)
	public String getCtrlUidLupd() {
		return this.ctrlUidLupd;
	}

	public void setCtrlUidLupd(String ctrlUidLupd) {
		this.ctrlUidLupd = ctrlUidLupd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTRL_APPS_CODE", nullable = false)
	public TCoreApps getTCoreApps() {
		return this.TCoreApps;
	}

	public void setTCoreApps(TCoreApps TCoreApps) {
		this.TCoreApps = TCoreApps;
	}

}
