package com.guudint.clickargo.common.model;
// Generated 7 Nov, 2022 5:51:04 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstFormAction generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_FORM_ACTION")
public class TCkMstFormAction extends COAbstractEntity<TCkMstFormAction> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -6663354620694253832L;

	// Attributes
	/////////////
	private String fmactId;
	private String fmactName;
	private String fmactDesc;
	private String fmactDescOth;
	private Character fmactStatus;
	private Date fmactDtCreate;
	private String fmactUidCreate;
	private Date fmactDtLupd;
	private String fmactUidLupd;

	// Constructors
	///////////////
	public TCkMstFormAction() {
	}

	/**
	 * @param fmactId
	 * @param fmactName
	 */
	public TCkMstFormAction(String fmactId, String fmactName) {
		this.fmactId = fmactId;
		this.fmactName = fmactName;
	}

	/**
	 * @param fmactId
	 * @param fmactName
	 * @param fmactDesc
	 * @param fmactDescOth
	 * @param fmactStatus
	 * @param fmactDtCreate
	 * @param fmactUidCreate
	 * @param fmactDtLupd
	 * @param fmactUidLupd
	 */
	public TCkMstFormAction(String fmactId, String fmactName, String fmactDesc, String fmactDescOth,
			Character fmactStatus, Date fmactDtCreate, String fmactUidCreate, Date fmactDtLupd, String fmactUidLupd) {
		this.fmactId = fmactId;
		this.fmactName = fmactName;
		this.fmactDesc = fmactDesc;
		this.fmactDescOth = fmactDescOth;
		this.fmactStatus = fmactStatus;
		this.fmactDtCreate = fmactDtCreate;
		this.fmactUidCreate = fmactUidCreate;
		this.fmactDtLupd = fmactDtLupd;
		this.fmactUidLupd = fmactUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkMstFormAction o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	// Properties
	/////////////
	@Id
	@Column(name = "FMACT_ID", unique = true, nullable = false, length = 35)
	public String getFmactId() {
		return this.fmactId;
	}

	public void setFmactId(String fmactId) {
		this.fmactId = fmactId;
	}

	@Column(name = "FMACT_NAME", nullable = false, length = 100)
	public String getFmactName() {
		return this.fmactName;
	}

	public void setFmactName(String fmactName) {
		this.fmactName = fmactName;
	}

	@Column(name = "FMACT_DESC")
	public String getFmactDesc() {
		return this.fmactDesc;
	}

	public void setFmactDesc(String fmactDesc) {
		this.fmactDesc = fmactDesc;
	}

	@Column(name = "FMACT_DESC_OTH", length = 512)
	public String getFmactDescOth() {
		return this.fmactDescOth;
	}

	public void setFmactDescOth(String fmactDescOth) {
		this.fmactDescOth = fmactDescOth;
	}

	@Column(name = "FMACT_STATUS", length = 1)
	public Character getFmactStatus() {
		return this.fmactStatus;
	}

	public void setFmactStatus(Character fmactStatus) {
		this.fmactStatus = fmactStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FMACT_DT_CREATE", length = 19)
	public Date getFmactDtCreate() {
		return this.fmactDtCreate;
	}

	public void setFmactDtCreate(Date fmactDtCreate) {
		this.fmactDtCreate = fmactDtCreate;
	}

	@Column(name = "FMACT_UID_CREATE", length = 35)
	public String getFmactUidCreate() {
		return this.fmactUidCreate;
	}

	public void setFmactUidCreate(String fmactUidCreate) {
		this.fmactUidCreate = fmactUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FMACT_DT_LUPD", length = 19)
	public Date getFmactDtLupd() {
		return this.fmactDtLupd;
	}

	public void setFmactDtLupd(Date fmactDtLupd) {
		this.fmactDtLupd = fmactDtLupd;
	}

	@Column(name = "FMACT_UID_LUPD", length = 35)
	public String getFmactUidLupd() {
		return this.fmactUidLupd;
	}

	public void setFmactUidLupd(String fmactUidLupd) {
		this.fmactUidLupd = fmactUidLupd;
	}
}
