package com.guudint.clickargo.common.model;
// Generated 23 Sep 2023, 2:27:49 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstRemarkType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_REMARK_TYPE")
public class TCkMstRemarkType extends COAbstractEntity<TCkMstRemarkType> {

	private static final long serialVersionUID = -1326380449403134201L;
	private String rtId;
	private String rtName;
	private String rtDesc;
	private String rtDescOth;
	private Character rtStatus;
	private Date rtDtCreate;
	private String rtUidCreate;
	private Date rtDtLupd;
	private String rtUidLupd;

	public TCkMstRemarkType() {
	}

	public TCkMstRemarkType(String rtId) {
		this.rtId = rtId;
	}

	public TCkMstRemarkType(String rtId, String rtName, String rtDesc, String rtDescOth, Character rtStatus,
			Date rtDtCreate, String rtUidCreate, Date rtDtLupd, String rtUidLupd) {
		this.rtId = rtId;
		this.rtName = rtName;
		this.rtDesc = rtDesc;
		this.rtDescOth = rtDescOth;
		this.rtStatus = rtStatus;
		this.rtDtCreate = rtDtCreate;
		this.rtUidCreate = rtUidCreate;
		this.rtDtLupd = rtDtLupd;
		this.rtUidLupd = rtUidLupd;
	}

	@Id

	@Column(name = "RT_ID", unique = true, nullable = false, length = 35)
	public String getRtId() {
		return this.rtId;
	}

	public void setRtId(String rtId) {
		this.rtId = rtId;
	}

	@Column(name = "RT_NAME", length = 128)
	public String getRtName() {
		return this.rtName;
	}

	public void setRtName(String rtName) {
		this.rtName = rtName;
	}

	@Column(name = "RT_DESC", length = 45)
	public String getRtDesc() {
		return this.rtDesc;
	}

	public void setRtDesc(String rtDesc) {
		this.rtDesc = rtDesc;
	}

	@Column(name = "RT_DESC_OTH", length = 512)
	public String getRtDescOth() {
		return this.rtDescOth;
	}

	public void setRtDescOth(String rtDescOth) {
		this.rtDescOth = rtDescOth;
	}

	@Column(name = "RT_STATUS", length = 1)
	public Character getRtStatus() {
		return this.rtStatus;
	}

	public void setRtStatus(Character rtStatus) {
		this.rtStatus = rtStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RT_DT_CREATE", length = 19)
	public Date getRtDtCreate() {
		return this.rtDtCreate;
	}

	public void setRtDtCreate(Date rtDtCreate) {
		this.rtDtCreate = rtDtCreate;
	}

	@Column(name = "RT_UID_CREATE", length = 35)
	public String getRtUidCreate() {
		return this.rtUidCreate;
	}

	public void setRtUidCreate(String rtUidCreate) {
		this.rtUidCreate = rtUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RT_DT_LUPD", length = 19)
	public Date getRtDtLupd() {
		return this.rtDtLupd;
	}

	public void setRtDtLupd(Date rtDtLupd) {
		this.rtDtLupd = rtDtLupd;
	}

	@Column(name = "RT_UID_LUPD", length = 35)
	public String getRtUidLupd() {
		return this.rtUidLupd;
	}

	public void setRtUidLupd(String rtUidLupd) {
		this.rtUidLupd = rtUidLupd;
	}

	@Override
	public int compareTo(TCkMstRemarkType o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
