package com.guudint.clickargo.common.model;
// Generated 23 Sep 2023, 2:27:49 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstWorkflowType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_WORKFLOW_TYPE")
public class TCkMstWorkflowType extends COAbstractEntity<TCkMstWorkflowType> {

	private static final long serialVersionUID = -7399877206242459050L;
	private String wktId;
	private String wktName;
	private String wktDesc;
	private String wktDescOth;
	private Character wktStatus;
	private Date wktDtCreate;
	private String wktUidCreate;
	private Date wktDtLupd;
	private String wktUidLupd;

	public TCkMstWorkflowType() {
	}

	public TCkMstWorkflowType(String wktId) {
		this.wktId = wktId;
	}

	public TCkMstWorkflowType(String wktId, String wktName, String wktDesc, String wktDescOth, Character wktStatus,
			Date wktDtCreate, String wktUidCreate, Date wktDtLupd, String wktUidLupd) {
		this.wktId = wktId;
		this.wktName = wktName;
		this.wktDesc = wktDesc;
		this.wktDescOth = wktDescOth;
		this.wktStatus = wktStatus;
		this.wktDtCreate = wktDtCreate;
		this.wktUidCreate = wktUidCreate;
		this.wktDtLupd = wktDtLupd;
		this.wktUidLupd = wktUidLupd;
	}

	@Id

	@Column(name = "WKT_ID", unique = true, nullable = false, length = 35)
	public String getWktId() {
		return this.wktId;
	}

	public void setWktId(String wktId) {
		this.wktId = wktId;
	}

	@Column(name = "WKT_NAME", length = 128)
	public String getWktName() {
		return this.wktName;
	}

	public void setWktName(String wktName) {
		this.wktName = wktName;
	}

	@Column(name = "WKT_DESC", length = 45)
	public String getWktDesc() {
		return this.wktDesc;
	}

	public void setWktDesc(String wktDesc) {
		this.wktDesc = wktDesc;
	}

	@Column(name = "WKT_DESC_OTH", length = 512)
	public String getWktDescOth() {
		return this.wktDescOth;
	}

	public void setWktDescOth(String wktDescOth) {
		this.wktDescOth = wktDescOth;
	}

	@Column(name = "WKT_STATUS", length = 1)
	public Character getWktStatus() {
		return this.wktStatus;
	}

	public void setWktStatus(Character wktStatus) {
		this.wktStatus = wktStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "WKT_DT_CREATE", length = 19)
	public Date getWktDtCreate() {
		return this.wktDtCreate;
	}

	public void setWktDtCreate(Date wktDtCreate) {
		this.wktDtCreate = wktDtCreate;
	}

	@Column(name = "WKT_UID_CREATE", length = 35)
	public String getWktUidCreate() {
		return this.wktUidCreate;
	}

	public void setWktUidCreate(String wktUidCreate) {
		this.wktUidCreate = wktUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "WKT_DT_LUPD", length = 19)
	public Date getWktDtLupd() {
		return this.wktDtLupd;
	}

	public void setWktDtLupd(Date wktDtLupd) {
		this.wktDtLupd = wktDtLupd;
	}

	@Column(name = "WKT_UID_LUPD", length = 35)
	public String getWktUidLupd() {
		return this.wktUidLupd;
	}

	public void setWktUidLupd(String wktUidLupd) {
		this.wktUidLupd = wktUidLupd;
	}

	@Override
	public int compareTo(TCkMstWorkflowType o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
