package com.guudint.clickargo.common.model;
// Generated 7 Nov, 2022 5:51:04 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstEntityType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_ENTITY_TYPE")
public class TCkMstEntityType extends COAbstractEntity<TCkMstEntityType> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -2522081309951222818L;

	// Attributes
	/////////////
	private String entyId;
	private String entyName;
	private String entyDesc;
	private String entyDescOth;
	private Character entyStatus;
	private Date entyDtCreate;
	private String entyUidCreate;
	private Date entyDtLupd;
	private String entyUidLupd;

	// Constructors
	///////////////
	public TCkMstEntityType() {
	}

	/**
	 * @param entyId
	 * @param entyName
	 */
	public TCkMstEntityType(String entyId, String entyName) {
		this.entyId = entyId;
		this.entyName = entyName;
	}

	/**
	 * @param entyId
	 * @param entyName
	 * @param entyDesc
	 * @param entyDescOth
	 * @param entyStatus
	 * @param entyDtCreate
	 * @param entyUidCreate
	 * @param entyDtLupd
	 * @param entyUidLupd
	 */
	public TCkMstEntityType(String entyId, String entyName, String entyDesc, String entyDescOth, Character entyStatus,
			Date entyDtCreate, String entyUidCreate, Date entyDtLupd, String entyUidLupd) {
		this.entyId = entyId;
		this.entyName = entyName;
		this.entyDesc = entyDesc;
		this.entyDescOth = entyDescOth;
		this.entyStatus = entyStatus;
		this.entyDtCreate = entyDtCreate;
		this.entyUidCreate = entyUidCreate;
		this.entyDtLupd = entyDtLupd;
		this.entyUidLupd = entyUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkMstEntityType o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	// Properties
	/////////////
	@Id
	@Column(name = "ENTY_ID", unique = true, nullable = false, length = 35)
	public String getEntyId() {
		return this.entyId;
	}

	public void setEntyId(String entyId) {
		this.entyId = entyId;
	}

	@Column(name = "ENTY_NAME", nullable = false, length = 100)
	public String getEntyName() {
		return this.entyName;
	}

	public void setEntyName(String entyName) {
		this.entyName = entyName;
	}

	@Column(name = "ENTY_DESC")
	public String getEntyDesc() {
		return this.entyDesc;
	}

	public void setEntyDesc(String entyDesc) {
		this.entyDesc = entyDesc;
	}

	@Column(name = "ENTY_DESC_OTH", length = 512)
	public String getEntyDescOth() {
		return this.entyDescOth;
	}

	public void setEntyDescOth(String entyDescOth) {
		this.entyDescOth = entyDescOth;
	}

	@Column(name = "ENTY_STATUS", length = 1)
	public Character getEntyStatus() {
		return this.entyStatus;
	}

	public void setEntyStatus(Character entyStatus) {
		this.entyStatus = entyStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENTY_DT_CREATE", length = 19)
	public Date getEntyDtCreate() {
		return this.entyDtCreate;
	}

	public void setEntyDtCreate(Date entyDtCreate) {
		this.entyDtCreate = entyDtCreate;
	}

	@Column(name = "ENTY_UID_CREATE", length = 35)
	public String getEntyUidCreate() {
		return this.entyUidCreate;
	}

	public void setEntyUidCreate(String entyUidCreate) {
		this.entyUidCreate = entyUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENTY_DT_LUPD", length = 19)
	public Date getEntyDtLupd() {
		return this.entyDtLupd;
	}

	public void setEntyDtLupd(Date entyDtLupd) {
		this.entyDtLupd = entyDtLupd;
	}

	@Column(name = "ENTY_UID_LUPD", length = 35)
	public String getEntyUidLupd() {
		return this.entyUidLupd;
	}

	public void setEntyUidLupd(String entyUidLupd) {
		this.entyUidLupd = entyUidLupd;
	}

}
