package com.guudint.clickargo.common.model;
// Generated 7 Nov, 2022 5:51:04 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstFormType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_FORM_TYPE")
public class TCkMstFormType extends COAbstractEntity<TCkMstFormType> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -55149611497468968L;

	// Attributes
	//////////////
	private String fmtypId;
	private String fmtypName;
	private String fmtypDesc;
	private String fmtypDescOth;
	private Character fmtypStatus;
	private Date fmtypDtCreate;
	private String fmtypUidCreate;
	private Date fmtypDtLupd;
	private String fmtypUidLupd;

	// Constructors
	///////////////
	public TCkMstFormType() {
	}

	/**
	 * @param fmtypId
	 * @param fmtypName
	 */
	public TCkMstFormType(String fmtypId, String fmtypName) {
		this.fmtypId = fmtypId;
		this.fmtypName = fmtypName;
	}

	/**
	 * @param fmtypId
	 * @param fmtypName
	 * @param fmtypDesc
	 * @param fmtypDescOth
	 * @param fmtypStatus
	 * @param fmtypDtCreate
	 * @param fmtypUidCreate
	 * @param fmtypDtLupd
	 * @param fmtypUidLupd
	 */
	public TCkMstFormType(String fmtypId, String fmtypName, String fmtypDesc, String fmtypDescOth,
			Character fmtypStatus, Date fmtypDtCreate, String fmtypUidCreate, Date fmtypDtLupd, String fmtypUidLupd) {
		this.fmtypId = fmtypId;
		this.fmtypName = fmtypName;
		this.fmtypDesc = fmtypDesc;
		this.fmtypDescOth = fmtypDescOth;
		this.fmtypStatus = fmtypStatus;
		this.fmtypDtCreate = fmtypDtCreate;
		this.fmtypUidCreate = fmtypUidCreate;
		this.fmtypDtLupd = fmtypDtLupd;
		this.fmtypUidLupd = fmtypUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkMstFormType o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	// Properties
	/////////////
	@Id
	@Column(name = "FMTYP_ID", unique = true, nullable = false, length = 35)
	public String getFmtypId() {
		return this.fmtypId;
	}

	public void setFmtypId(String fmtypId) {
		this.fmtypId = fmtypId;
	}

	@Column(name = "FMTYP_NAME", nullable = false, length = 100)
	public String getFmtypName() {
		return this.fmtypName;
	}

	public void setFmtypName(String fmtypName) {
		this.fmtypName = fmtypName;
	}

	@Column(name = "FMTYP_DESC")
	public String getFmtypDesc() {
		return this.fmtypDesc;
	}

	public void setFmtypDesc(String fmtypDesc) {
		this.fmtypDesc = fmtypDesc;
	}

	@Column(name = "FMTYP_DESC_OTH", length = 512)
	public String getFmtypDescOth() {
		return this.fmtypDescOth;
	}

	public void setFmtypDescOth(String fmtypDescOth) {
		this.fmtypDescOth = fmtypDescOth;
	}

	@Column(name = "FMTYP_STATUS", length = 1)
	public Character getFmtypStatus() {
		return this.fmtypStatus;
	}

	public void setFmtypStatus(Character fmtypStatus) {
		this.fmtypStatus = fmtypStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FMTYP_DT_CREATE", length = 19)
	public Date getFmtypDtCreate() {
		return this.fmtypDtCreate;
	}

	public void setFmtypDtCreate(Date fmtypDtCreate) {
		this.fmtypDtCreate = fmtypDtCreate;
	}

	@Column(name = "FMTYP_UID_CREATE", length = 35)
	public String getFmtypUidCreate() {
		return this.fmtypUidCreate;
	}

	public void setFmtypUidCreate(String fmtypUidCreate) {
		this.fmtypUidCreate = fmtypUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FMTYP_DT_LUPD", length = 19)
	public Date getFmtypDtLupd() {
		return this.fmtypDtLupd;
	}

	public void setFmtypDtLupd(Date fmtypDtLupd) {
		this.fmtypDtLupd = fmtypDtLupd;
	}

	@Column(name = "FMTYP_UID_LUPD", length = 35)
	public String getFmtypUidLupd() {
		return this.fmtypUidLupd;
	}

	public void setFmtypUidLupd(String fmtypUidLupd) {
		this.fmtypUidLupd = fmtypUidLupd;
	}

}
