package com.guudint.clickargo.common.model;
// Generated 7 Nov, 2022 5:51:04 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstEntityState generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_ENTITY_STATE")
public class TCkMstEntityState extends COAbstractEntity<TCkMstEntityState> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 4140723126600218268L;

	// Attributes
	/////////////
	private String enstId;
	private String enstName;
	private String enstDesc;
	private String enstDescOth;
	private Character enstStatus;
	private Date enstDtCreate;
	private String enstUidCreate;
	private Date enstDtLupd;
	private String enstUidLupd;

	// Constructors
	///////////////
	public TCkMstEntityState() {
	}

	/**
	 * @param enstId
	 * @param enstName
	 */
	public TCkMstEntityState(String enstId, String enstName) {
		this.enstId = enstId;
		this.enstName = enstName;
	}

	/**
	 * @param enstId
	 * @param enstName
	 * @param enstDesc
	 * @param enstDescOth
	 * @param enstStatus
	 * @param enstDtCreate
	 * @param enstUidCreate
	 * @param enstDtLupd
	 * @param enstUidLupd
	 */
	public TCkMstEntityState(String enstId, String enstName, String enstDesc, String enstDescOth, Character enstStatus,
			Date enstDtCreate, String enstUidCreate, Date enstDtLupd, String enstUidLupd) {
		this.enstId = enstId;
		this.enstName = enstName;
		this.enstDesc = enstDesc;
		this.enstDescOth = enstDescOth;
		this.enstStatus = enstStatus;
		this.enstDtCreate = enstDtCreate;
		this.enstUidCreate = enstUidCreate;
		this.enstDtLupd = enstDtLupd;
		this.enstUidLupd = enstUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkMstEntityState o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	// Properties
	/////////////
	@Id
	@Column(name = "ENST_ID", unique = true, nullable = false, length = 35)
	public String getEnstId() {
		return this.enstId;
	}

	public void setEnstId(String enstId) {
		this.enstId = enstId;
	}

	@Column(name = "ENST_NAME", nullable = false, length = 100)
	public String getEnstName() {
		return this.enstName;
	}

	public void setEnstName(String enstName) {
		this.enstName = enstName;
	}

	@Column(name = "ENST_DESC")
	public String getEnstDesc() {
		return this.enstDesc;
	}

	public void setEnstDesc(String enstDesc) {
		this.enstDesc = enstDesc;
	}

	@Column(name = "ENST_DESC_OTH", length = 512)
	public String getEnstDescOth() {
		return this.enstDescOth;
	}

	public void setEnstDescOth(String enstDescOth) {
		this.enstDescOth = enstDescOth;
	}

	@Column(name = "ENST_STATUS", length = 1)
	public Character getEnstStatus() {
		return this.enstStatus;
	}

	public void setEnstStatus(Character enstStatus) {
		this.enstStatus = enstStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENST_DT_CREATE", length = 19)
	public Date getEnstDtCreate() {
		return this.enstDtCreate;
	}

	public void setEnstDtCreate(Date enstDtCreate) {
		this.enstDtCreate = enstDtCreate;
	}

	@Column(name = "ENST_UID_CREATE", length = 35)
	public String getEnstUidCreate() {
		return this.enstUidCreate;
	}

	public void setEnstUidCreate(String enstUidCreate) {
		this.enstUidCreate = enstUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENST_DT_LUPD", length = 19)
	public Date getEnstDtLupd() {
		return this.enstDtLupd;
	}

	public void setEnstDtLupd(Date enstDtLupd) {
		this.enstDtLupd = enstDtLupd;
	}

	@Column(name = "ENST_UID_LUPD", length = 35)
	public String getEnstUidLupd() {
		return this.enstUidLupd;
	}

	public void setEnstUidLupd(String enstUidLupd) {
		this.enstUidLupd = enstUidLupd;
	}
}
