package com.guudint.clickargo.common.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkRecordDate generated by hbm2java
 */
@Entity
@Table(name = "T_CK_RECORD_DATE")
public class TCkRecordDate extends COAbstractEntity<TCkRecordDate> {

	// Static Attributes
	/////////////////////
	private static final long serialVersionUID = 8427895169209926769L;

	// Attributes
	//////////////
	private String rcdId;
	private Date rcdDtDrft;
	private Date rcdDtStart;
	private String rcdUidStart;
	private Date rcdDtExpiry;
	private String rcdUidExpiry;
	private Date rcdDtSubmit;
	private String rcdUidSubmit;
	private Date rcdDtAccepted;
	private String rcdUidAccepted;
	private Date rcdDtAssigned;
	private String rcdUidAssigned;
	private Date rcdDtBilled;
	private String rcdUidBilled;
	private Date rcdDtVerified;
	private String rcdUidVerified;
	private Date rcdDtApproved;
	private String rcdUidApproved;
	private Date rcdDtPaid;
	private String rcdUidPaid;
	private Date rcdDtComplete;
	private String rcdUidComplete;
	private Date rcdDtCancel;
	private String rcdUidCancel;
	private Date rcdDtReject;
	private String rcdUidReject;
	private Date rcdDtDelete;
	private String rcdUidDelete;

	private Date rcdDtBillVerified;
	private String rcdUidBillVerified;
	private Date rcdDtBillApproved;
	private String rcdUidBillApproved;
	private Date rcdDtBillRejected;
	private String rcdUidBillRejected;

	private Date rcdDtBillAcknowledged;
	private String rcdUidBillAcknowledged;

	// Constructors
	///////////////
	public TCkRecordDate() {
	}

	/**
	 * @param rcdId
	 */
	public TCkRecordDate(String rcdId) {
		this.rcdId = rcdId;
	}

	/**
	 * @param rcdId
	 * @param rcdDtDrft
	 * @param rcdDtStart
	 * @param rcdDtExpiry
	 * @param rcdDtSubmit
	 * @param rcdDtAssigned
	 * @param rcdDtPaid
	 * @param rcdDtComplete
	 * @param rcdDtCancel
	 * @param rcdDtReject
	 * @param rcdDtDelete
	 */
	public TCkRecordDate(String rcdId, Date rcdDtDrft, Date rcdDtStart, Date rcdDtExpiry, Date rcdDtSubmit,
			Date rcdDtAssigned, Date rcdDtPaid, Date rcdDtComplete, Date rcdDtCancel, Date rcdDtReject,
			Date rcdDtDelete) {
		this.rcdId = rcdId;
		this.rcdDtDrft = rcdDtDrft;
		this.rcdDtStart = rcdDtStart;
		this.rcdDtExpiry = rcdDtExpiry;
		this.rcdDtSubmit = rcdDtSubmit;
		this.rcdDtAssigned = rcdDtAssigned;
		this.rcdDtPaid = rcdDtPaid;
		this.rcdDtComplete = rcdDtComplete;
		this.rcdDtCancel = rcdDtCancel;
		this.rcdDtReject = rcdDtReject;
		this.rcdDtDelete = rcdDtDelete;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkRecordDate arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
	
	// Properties
	/////////////
	@Id
	@Column(name = "RCD_ID", unique = true, nullable = false, length = 35)
	public String getRcdId() {
		return this.rcdId;
	}

	public void setRcdId(String rcdId) {
		this.rcdId = rcdId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RCD_DT_DRFT", length = 19)
	public Date getRcdDtDrft() {
		return this.rcdDtDrft;
	}

	public void setRcdDtDrft(Date rcdDtDrft) {
		this.rcdDtDrft = rcdDtDrft;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RCD_DT_START", length = 19)
	public Date getRcdDtStart() {
		return this.rcdDtStart;
	}

	public void setRcdDtStart(Date rcdDtStart) {
		this.rcdDtStart = rcdDtStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RCD_DT_EXPIRY", length = 19)
	public Date getRcdDtExpiry() {
		return this.rcdDtExpiry;
	}

	public void setRcdDtExpiry(Date rcdDtExpiry) {
		this.rcdDtExpiry = rcdDtExpiry;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RCD_DT_SUBMIT", length = 19)
	public Date getRcdDtSubmit() {
		return this.rcdDtSubmit;
	}

	public void setRcdDtSubmit(Date rcdDtSubmit) {
		this.rcdDtSubmit = rcdDtSubmit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RCD_DT_ASSIGNED", length = 19)
	public Date getRcdDtAssigned() {
		return this.rcdDtAssigned;
	}

	public void setRcdDtAssigned(Date rcdDtAssigned) {
		this.rcdDtAssigned = rcdDtAssigned;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RCD_DT_PAID", length = 19)
	public Date getRcdDtPaid() {
		return this.rcdDtPaid;
	}

	public void setRcdDtPaid(Date rcdDtPaid) {
		this.rcdDtPaid = rcdDtPaid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RCD_DT_COMPLETE", length = 19)
	public Date getRcdDtComplete() {
		return this.rcdDtComplete;
	}

	public void setRcdDtComplete(Date rcdDtComplete) {
		this.rcdDtComplete = rcdDtComplete;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RCD_DT_CANCEL", length = 19)
	public Date getRcdDtCancel() {
		return this.rcdDtCancel;
	}

	public void setRcdDtCancel(Date rcdDtCancel) {
		this.rcdDtCancel = rcdDtCancel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RCD_DT_REJECT", length = 19)
	public Date getRcdDtReject() {
		return this.rcdDtReject;
	}

	public void setRcdDtReject(Date rcdDtReject) {
		this.rcdDtReject = rcdDtReject;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RCD_DT_DELETE", length = 19)
	public Date getRcdDtDelete() {
		return this.rcdDtDelete;
	}

	public void setRcdDtDelete(Date rcdDtDelete) {
		this.rcdDtDelete = rcdDtDelete;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RCD_DT_ACCEPTED", length = 19)
	public Date getRcdDtAccepted() {
		return rcdDtAccepted;
	}

	public void setRcdDtAccepted(Date rcdDtAccepted) {
		this.rcdDtAccepted = rcdDtAccepted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RCD_DT_VERIFIED", length = 19)
	public Date getRcdDtVerified() {
		return rcdDtVerified;
	}

	public void setRcdDtVerified(Date rcdDtVerified) {
		this.rcdDtVerified = rcdDtVerified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RCD_DT_APPROVED", length = 19)
	public Date getRcdDtApproved() {
		return rcdDtApproved;
	}

	public void setRcdDtApproved(Date rcdDtApproved) {
		this.rcdDtApproved = rcdDtApproved;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RCD_DT_BILLED", length = 19)
	public Date getRcdDtBilled() {
		return rcdDtBilled;
	}

	public void setRcdDtBilled(Date rcdDtBilled) {
		this.rcdDtBilled = rcdDtBilled;
	}

	@Column(name = "RCD_UID_START", length = 35)
	public String getRcdUidStart() {
		return rcdUidStart;
	}

	public void setRcdUidStart(String rcdUidStart) {
		this.rcdUidStart = rcdUidStart;
	}

	@Column(name = "RCD_UID_EXPIRY", length = 35)
	public String getRcdUidExpiry() {
		return rcdUidExpiry;
	}

	public void setRcdUidExpiry(String rcdUidExpiry) {
		this.rcdUidExpiry = rcdUidExpiry;
	}

	@Column(name = "RCD_UID_SUBMIT", length = 35)
	public String getRcdUidSubmit() {
		return rcdUidSubmit;
	}

	public void setRcdUidSubmit(String rcdUidSubmit) {
		this.rcdUidSubmit = rcdUidSubmit;
	}

	@Column(name = "RCD_UID_ACCEPTED", length = 35)
	public String getRcdUidAccepted() {
		return rcdUidAccepted;
	}

	public void setRcdUidAccepted(String rcdUidAccepted) {
		this.rcdUidAccepted = rcdUidAccepted;
	}

	@Column(name = "RCD_UID_ASSIGNED", length = 35)
	public String getRcdUidAssigned() {
		return rcdUidAssigned;
	}

	public void setRcdUidAssigned(String rcdUidAssigned) {
		this.rcdUidAssigned = rcdUidAssigned;
	}

	@Column(name = "RCD_UID_BILLED", length = 35)
	public String getRcdUidBilled() {
		return rcdUidBilled;
	}

	public void setRcdUidBilled(String rcdUidBilled) {
		this.rcdUidBilled = rcdUidBilled;
	}

	@Column(name = "RCD_UID_VERIFIED", length = 35)
	public String getRcdUidVerified() {
		return rcdUidVerified;
	}

	public void setRcdUidVerified(String rcdUidVerified) {
		this.rcdUidVerified = rcdUidVerified;
	}

	@Column(name = "RCD_UID_APPROVED", length = 35)
	public String getRcdUidApproved() {
		return rcdUidApproved;
	}

	public void setRcdUidApproved(String rcdUidApproved) {
		this.rcdUidApproved = rcdUidApproved;
	}

	@Column(name = "RCD_UID_PAID", length = 35)
	public String getRcdUidPaid() {
		return rcdUidPaid;
	}

	public void setRcdUidPaid(String rcdUidPaid) {
		this.rcdUidPaid = rcdUidPaid;
	}

	@Column(name = "RCD_UID_COMPLETE", length = 35)
	public String getRcdUidComplete() {
		return rcdUidComplete;
	}

	public void setRcdUidComplete(String rcdUidComplete) {
		this.rcdUidComplete = rcdUidComplete;
	}

	@Column(name = "RCD_UID_CANCEL", length = 35)
	public String getRcdUidCancel() {
		return rcdUidCancel;
	}

	public void setRcdUidCancel(String rcdUidCancel) {
		this.rcdUidCancel = rcdUidCancel;
	}

	@Column(name = "RCD_UID_REJECT", length = 35)
	public String getRcdUidReject() {
		return rcdUidReject;
	}

	public void setRcdUidReject(String rcdUidReject) {
		this.rcdUidReject = rcdUidReject;
	}

	@Column(name = "RCD_UID_DELETE", length = 35)
	public String getRcdUidDelete() {
		return rcdUidDelete;
	}

	public void setRcdUidDelete(String rcdUidDelete) {
		this.rcdUidDelete = rcdUidDelete;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RCD_DT_BILL_VERIFIED", length = 19)
	public Date getRcdDtBillVerified() {
		return rcdDtBillVerified;
	}

	public void setRcdDtBillVerified(Date rcdDtBillVerified) {
		this.rcdDtBillVerified = rcdDtBillVerified;
	}

	@Column(name = "RCD_UID_BILL_VERIFIED", length = 35)
	public String getRcdUidBillVerified() {
		return rcdUidBillVerified;
	}

	public void setRcdUidBillVerified(String rcdUidBillVerified) {
		this.rcdUidBillVerified = rcdUidBillVerified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RCD_DT_BILL_APPROVED", length = 19)
	public Date getRcdDtBillApproved() {
		return rcdDtBillApproved;
	}

	public void setRcdDtBillApproved(Date rcdDtBillApproved) {
		this.rcdDtBillApproved = rcdDtBillApproved;
	}

	@Column(name = "RCD_UID_BILL_APPROVED", length = 35)
	public String getRcdUidBillApproved() {
		return rcdUidBillApproved;
	}

	public void setRcdUidBillApproved(String rcdUidBillApproved) {
		this.rcdUidBillApproved = rcdUidBillApproved;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RCD_DT_BILL_REJECTED", length = 19)
	public Date getRcdDtBillRejected() {
		return rcdDtBillRejected;
	}

	public void setRcdDtBillRejected(Date rcdDtBillRejected) {
		this.rcdDtBillRejected = rcdDtBillRejected;
	}

	@Column(name = "RCD_UID_BILL_REJECTED", length = 35)
	public String getRcdUidBillRejected() {
		return rcdUidBillRejected;
	}

	public void setRcdUidBillRejected(String rcdUidBillRejected) {
		this.rcdUidBillRejected = rcdUidBillRejected;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RCD_DT_BILL_ACKNOWLEDGED", length = 19)
	public Date getRcdDtBillAcknowledged() {
		return rcdDtBillAcknowledged;
	}

	public void setRcdDtBillAcknowledged(Date rcdDtBillAcknowledged) {
		this.rcdDtBillAcknowledged = rcdDtBillAcknowledged;
	}

	@Column(name = "RCD_UID_BILL_ACKNOWLEDGED", length = 35)
	public String getRcdUidBillAcknowledged() {
		return rcdUidBillAcknowledged;
	}

	public void setRcdUidBillAcknowledged(String rcdUidBillAcknowledged) {
		this.rcdUidBillAcknowledged = rcdUidBillAcknowledged;
	}

}
