package com.guudint.clickargo.common.model;
// Generated 20 Dec 2023, 3:08:55 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.cac.model.TCorePermEx;
import com.vcc.camelone.ccm.model.TCoreUsr;
import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.core.model.TCoreApps;

/**
 * TCkGrantUserEx generated by hbm2java
 */
@Entity
@Table(name = "T_CK_UNGRANT_USER_EX")
public class TCkUnGrantUserEx extends COAbstractEntity<TCkUnGrantUserEx> {

	private static final long serialVersionUID = 6983850660456051977L;
	private TCkUnGrantUserExId id;
	private TCoreApps TCoreApps;
	private TCorePermEx TCorePermEx;
	private TCoreUsr TCoreUsr;
	private char grntueStatus;
	private Date grntueDtCreate;
	private String grntueUidCreate;
	private Date grntueDtLupd;
	private String grntueUidLupd;

	public TCkUnGrantUserEx() {
	}

	public TCkUnGrantUserEx(TCkUnGrantUserExId id, TCoreApps TCoreApps, TCorePermEx TCorePermEx, TCoreUsr TCoreUsr,
			char grntueStatus, Date grntueDtCreate, String grntueUidCreate) {
		this.id = id;
		this.TCoreApps = TCoreApps;
		this.TCorePermEx = TCorePermEx;
		this.TCoreUsr = TCoreUsr;
		this.grntueStatus = grntueStatus;
		this.grntueDtCreate = grntueDtCreate;
		this.grntueUidCreate = grntueUidCreate;
	}

	public TCkUnGrantUserEx(TCkUnGrantUserExId id, TCoreApps TCoreApps, TCorePermEx TCorePermEx, TCoreUsr TCoreUsr,
			char grntueStatus, Date grntueDtCreate, String grntueUidCreate, Date grntueDtLupd, String grntueUidLupd) {
		this.id = id;
		this.TCoreApps = TCoreApps;
		this.TCorePermEx = TCorePermEx;
		this.TCoreUsr = TCoreUsr;
		this.grntueStatus = grntueStatus;
		this.grntueDtCreate = grntueDtCreate;
		this.grntueUidCreate = grntueUidCreate;
		this.grntueDtLupd = grntueDtLupd;
		this.grntueUidLupd = grntueUidLupd;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "grntueUsrId", column = @Column(name = "GRNTUE_USR_ID", nullable = false, length = 35)),
			@AttributeOverride(name = "grntueAppsCode", column = @Column(name = "GRNTUE_APPS_CODE", nullable = false, length = 35)),
			@AttributeOverride(name = "grntuePermExId", column = @Column(name = "GRNTUE_PERM_EX_ID", nullable = false, length = 35)) })
	public TCkUnGrantUserExId getId() {
		return this.id;
	}

	public void setId(TCkUnGrantUserExId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GRNTUE_APPS_CODE", nullable = false, insertable = false, updatable = false)
	public TCoreApps getTCoreApps() {
		return this.TCoreApps;
	}

	public void setTCoreApps(TCoreApps TCoreApps) {
		this.TCoreApps = TCoreApps;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GRNTUE_PERM_EX_ID", nullable = false, insertable = false, updatable = false)
	public TCorePermEx getTCorePermEx() {
		return this.TCorePermEx;
	}

	public void setTCorePermEx(TCorePermEx TCorePermEx) {
		this.TCorePermEx = TCorePermEx;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GRNTUE_USR_ID", nullable = false, insertable = false, updatable = false)
	public TCoreUsr getTCoreUsr() {
		return this.TCoreUsr;
	}

	public void setTCoreUsr(TCoreUsr TCoreUsr) {
		this.TCoreUsr = TCoreUsr;
	}

	@Column(name = "GRNTUE_STATUS", nullable = false, length = 1)
	public char getGrntueStatus() {
		return this.grntueStatus;
	}

	public void setGrntueStatus(char grntueStatus) {
		this.grntueStatus = grntueStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GRNTUE_DT_CREATE", nullable = false, length = 19)
	public Date getGrntueDtCreate() {
		return this.grntueDtCreate;
	}

	public void setGrntueDtCreate(Date grntueDtCreate) {
		this.grntueDtCreate = grntueDtCreate;
	}

	@Column(name = "GRNTUE_UID_CREATE", nullable = false, length = 35)
	public String getGrntueUidCreate() {
		return this.grntueUidCreate;
	}

	public void setGrntueUidCreate(String grntueUidCreate) {
		this.grntueUidCreate = grntueUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GRNTUE_DT_LUPD", length = 19)
	public Date getGrntueDtLupd() {
		return this.grntueDtLupd;
	}

	public void setGrntueDtLupd(Date grntueDtLupd) {
		this.grntueDtLupd = grntueDtLupd;
	}

	@Column(name = "GRNTUE_UID_LUPD", length = 35)
	public String getGrntueUidLupd() {
		return this.grntueUidLupd;
	}

	public void setGrntueUidLupd(String grntueUidLupd) {
		this.grntueUidLupd = grntueUidLupd;
	}

	@Override
	public int compareTo(TCkUnGrantUserEx o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
