package com.guudint.clickargo.common.model;
// Generated 20 Dec 2023, 3:08:55 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.cac.model.TCorePermEx;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.core.model.TCoreApps;

/**
 * TCkGrantAccountEx generated by hbm2java
 */
@Entity
@Table(name = "T_CK_UNGRANT_ACCOUNT_EX")
public class TCkUnGrantAccountEx extends COAbstractEntity<TCkUnGrantAccountEx> {

	private static final long serialVersionUID = 4327204672304776764L;
	private TCkUnGrantAccountExId id;
	private TCoreAccn TCoreAccn;
	private TCoreApps TCoreApps;
	private TCorePermEx TCorePermEx;
	private char grntaStatus;
	private Date grntaDtCreate;
	private String grntaUidCreate;
	private Date grntaDtLupd;
	private String grntaUidLupd;

	public TCkUnGrantAccountEx() {
	}

	public TCkUnGrantAccountEx(TCkUnGrantAccountExId id, TCoreAccn TCoreAccn, TCoreApps TCoreApps, TCorePermEx TCorePermEx,
			char grntaStatus, Date grntaDtCreate, String grntaUidCreate) {
		this.id = id;
		this.TCoreAccn = TCoreAccn;
		this.TCoreApps = TCoreApps;
		this.TCorePermEx = TCorePermEx;
		this.grntaStatus = grntaStatus;
		this.grntaDtCreate = grntaDtCreate;
		this.grntaUidCreate = grntaUidCreate;
	}

	public TCkUnGrantAccountEx(TCkUnGrantAccountExId id, TCoreAccn TCoreAccn, TCoreApps TCoreApps, TCorePermEx TCorePermEx,
			char grntaStatus, Date grntaDtCreate, String grntaUidCreate, Date grntaDtLupd, String grntaUidLupd) {
		this.id = id;
		this.TCoreAccn = TCoreAccn;
		this.TCoreApps = TCoreApps;
		this.TCorePermEx = TCorePermEx;
		this.grntaStatus = grntaStatus;
		this.grntaDtCreate = grntaDtCreate;
		this.grntaUidCreate = grntaUidCreate;
		this.grntaDtLupd = grntaDtLupd;
		this.grntaUidLupd = grntaUidLupd;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "grntaAccnId", column = @Column(name = "GRNTA_ACCN_ID", nullable = false, length = 35)),
			@AttributeOverride(name = "grntaAppsCode", column = @Column(name = "GRNTA_APPS_CODE", nullable = false, length = 35)),
			@AttributeOverride(name = "grntaPermExId", column = @Column(name = "GRNTA_PERM_EX_ID", nullable = false, length = 35)) })
	public TCkUnGrantAccountExId getId() {
		return this.id;
	}

	public void setId(TCkUnGrantAccountExId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GRNTA_ACCN_ID", nullable = false, insertable = false, updatable = false)
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GRNTA_APPS_CODE", nullable = false, insertable = false, updatable = false)
	public TCoreApps getTCoreApps() {
		return this.TCoreApps;
	}

	public void setTCoreApps(TCoreApps TCoreApps) {
		this.TCoreApps = TCoreApps;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GRNTA_PERM_EX_ID", nullable = false, insertable = false, updatable = false)
	public TCorePermEx getTCorePermEx() {
		return this.TCorePermEx;
	}

	public void setTCorePermEx(TCorePermEx TCorePermEx) {
		this.TCorePermEx = TCorePermEx;
	}

	@Column(name = "GRNTA_STATUS", nullable = false, length = 1)
	public char getGrntaStatus() {
		return this.grntaStatus;
	}

	public void setGrntaStatus(char grntaStatus) {
		this.grntaStatus = grntaStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GRNTA_DT_CREATE", nullable = false, length = 19)
	public Date getGrntaDtCreate() {
		return this.grntaDtCreate;
	}

	public void setGrntaDtCreate(Date grntaDtCreate) {
		this.grntaDtCreate = grntaDtCreate;
	}

	@Column(name = "GRNTA_UID_CREATE", nullable = false, length = 35)
	public String getGrntaUidCreate() {
		return this.grntaUidCreate;
	}

	public void setGrntaUidCreate(String grntaUidCreate) {
		this.grntaUidCreate = grntaUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "GRNTA_DT_LUPD", length = 19)
	public Date getGrntaDtLupd() {
		return this.grntaDtLupd;
	}

	public void setGrntaDtLupd(Date grntaDtLupd) {
		this.grntaDtLupd = grntaDtLupd;
	}

	@Column(name = "GRNTA_UID_LUPD", length = 35)
	public String getGrntaUidLupd() {
		return this.grntaUidLupd;
	}

	public void setGrntaUidLupd(String grntaUidLupd) {
		this.grntaUidLupd = grntaUidLupd;
	}

	@Override
	public int compareTo(TCkUnGrantAccountEx o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
