package com.guudint.clickargo.common.model;
// Generated 20 Dec 2023, 3:08:55 pm by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkGrantAccountExId generated by hbm2java
 */
@Embeddable
public class TCkUnGrantAccountExId extends COAbstractEntity<TCkUnGrantAccountExId> {

	private static final long serialVersionUID = 3231527043232616739L;
	private String grntaAccnId;
	private String grntaAppsCode;
	private String grntaPermExId;
	private String grntaRoleId;

	public TCkUnGrantAccountExId() {
	}

	public TCkUnGrantAccountExId(String grntaAccnId, String grntaAppsCode, String grntaPermExId, String grntaRoleId) {
		this.grntaAccnId = grntaAccnId;
		this.grntaAppsCode = grntaAppsCode;
		this.grntaPermExId = grntaPermExId;
		this.grntaRoleId = grntaRoleId;
	}

	@Column(name = "GRNTA_ACCN_ID", nullable = false, length = 35)
	public String getGrntaAccnId() {
		return this.grntaAccnId;
	}

	public void setGrntaAccnId(String grntaAccnId) {
		this.grntaAccnId = grntaAccnId;
	}

	@Column(name = "GRNTA_APPS_CODE", nullable = false, length = 35)
	public String getGrntaAppsCode() {
		return this.grntaAppsCode;
	}

	public void setGrntaAppsCode(String grntaAppsCode) {
		this.grntaAppsCode = grntaAppsCode;
	}

	@Column(name = "GRNTA_PERM_EX_ID", nullable = false, length = 35)
	public String getGrntaPermExId() {
		return this.grntaPermExId;
	}

	public void setGrntaPermExId(String grntaPermExId) {
		this.grntaPermExId = grntaPermExId;
	}

	@Column(name = "GRNTA_ROLE_ID", nullable = false, length = 35)
	public String getGrntaRoleId() {
		return this.grntaRoleId;
	}
	
	public void setGrntaRoleId(String grntaRoleId) {
		this.grntaRoleId = grntaRoleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TCkUnGrantAccountExId))
			return false;
		TCkUnGrantAccountExId castOther = (TCkUnGrantAccountExId) other;

		return ((this.getGrntaAppsCode() == castOther.getGrntaAppsCode())
				|| (this.getGrntaAppsCode() != null && castOther.getGrntaAppsCode() != null
						&& this.getGrntaAppsCode().equals(castOther.getGrntaAppsCode())))
				&& ((this.getGrntaAccnId() == castOther.getGrntaAccnId())
						|| (this.getGrntaAccnId() != null && castOther.getGrntaAccnId() != null
								&& this.getGrntaAccnId().equals(castOther.getGrntaAccnId())))
				&& ((this.getGrntaRoleId() == castOther.getGrntaRoleId())
						|| (this.getGrntaRoleId() != null && castOther.getGrntaRoleId() != null
								&& this.getGrntaRoleId().equals(castOther.getGrntaRoleId())))
				&& (this.getGrntaPermExId() == castOther.getGrntaPermExId())
				|| (this.getGrntaPermExId() != null && castOther.getGrntaPermExId() != null
						&& this.getGrntaPermExId().equals(castOther.getGrntaPermExId()));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getGrntaAppsCode() == null ? 0 : this.getGrntaAppsCode().hashCode());
		result = 37 * result + (getGrntaAccnId() == null ? 0 : this.getGrntaAccnId().hashCode());
		result = 37 * result + (getGrntaRoleId() == null ? 0 : this.getGrntaRoleId().hashCode());
		result = 37 * result + (getGrntaPermExId() == null ? 0 : this.getGrntaPermExId().hashCode());
return result;
	}

	@Override
	public int compareTo(TCkUnGrantAccountExId o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
