package com.guudint.clickargo.common.model;
// Generated 20 Dec 2023, 3:08:55 pm by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkGrantUserExId generated by hbm2java
 */
@Embeddable
public class TCkUnGrantUserExId extends COAbstractEntity<TCkUnGrantUserExId> {

	private static final long serialVersionUID = -6806029758599411578L;
	private String grntueUsrId;
	private String grntueAppsCode;
	private String grntuePermExId;
	private String grntueRoleId;

	public TCkUnGrantUserExId() {
	}

	public TCkUnGrantUserExId(String grntueUsrId, String grntueAppsCode, String grntuePermExId, String grntueRoleId) {
		this.grntueUsrId = grntueUsrId;
		this.grntueAppsCode = grntueAppsCode;
		this.grntuePermExId = grntuePermExId;
		this.grntueRoleId = grntueRoleId;
	}

	@Column(name = "GRNTUE_USR_ID", nullable = false, length = 35)
	public String getGrntueUsrId() {
		return this.grntueUsrId;
	}

	public void setGrntueUsrId(String grntueUsrId) {
		this.grntueUsrId = grntueUsrId;
	}

	@Column(name = "GRNTUE_APPS_CODE", nullable = false, length = 35)
	public String getGrntueAppsCode() {
		return this.grntueAppsCode;
	}

	public void setGrntueAppsCode(String grntueAppsCode) {
		this.grntueAppsCode = grntueAppsCode;
	}

	@Column(name = "GRNTUE_PERM_EX_ID", nullable = false, length = 35)
	public String getGrntuePermExId() {
		return this.grntuePermExId;
	}

	public void setGrntuePermExId(String grntuePermExId) {
		this.grntuePermExId = grntuePermExId;
	}

	@Column(name = "GRNTUE_ROLE_ID", nullable = false, length = 35)
	public String getGrntueRoleId() {
		return this.grntueRoleId;
	}

	public void setGrntueRoleId(String grntueRoleId) {
		this.grntueRoleId = grntueRoleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TCkUnGrantUserExId))
			return false;
		TCkUnGrantUserExId castOther = (TCkUnGrantUserExId) other;

		return ((this.getGrntueUsrId() == castOther.getGrntueUsrId()) || (this.getGrntueUsrId() != null
				&& castOther.getGrntueUsrId() != null && this.getGrntueUsrId().equals(castOther.getGrntueUsrId())))
				&& ((this.getGrntueAppsCode() == castOther.getGrntueAppsCode())
						|| (this.getGrntueAppsCode() != null && castOther.getGrntueAppsCode() != null
								&& this.getGrntueAppsCode().equals(castOther.getGrntueAppsCode())))
				&& ((this.getGrntuePermExId() == castOther.getGrntuePermExId())
						|| (this.getGrntuePermExId() != null && castOther.getGrntuePermExId() != null
								&& this.getGrntuePermExId().equals(castOther.getGrntuePermExId())))
				&& ((this.getGrntueRoleId() == castOther.getGrntueRoleId())
						|| (this.getGrntueRoleId() != null && castOther.getGrntueRoleId() != null
								&& this.getGrntueRoleId().equals(castOther.getGrntueRoleId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getGrntueUsrId() == null ? 0 : this.getGrntueUsrId().hashCode());
		result = 37 * result + (getGrntueAppsCode() == null ? 0 : this.getGrntueAppsCode().hashCode());
		result = 37 * result + (getGrntuePermExId() == null ? 0 : this.getGrntuePermExId().hashCode());
		result = 37 * result + (getGrntueRoleId() == null ? 0 : this.getGrntueRoleId().hashCode());
		return result;
	}

	@Override
	public int compareTo(TCkUnGrantUserExId o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
