package com.guudint.clickargo.common.model;
// Generated 19 Oct 2023, 12:03:19 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtWhitelabel generated by hbm2java
 */
@Entity
@Table(name = "T_CK_WHITELABEL")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkWhitelabel extends COAbstractEntity<TCkWhitelabel> {

	private static final long serialVersionUID = -8681591015609983923L;
	private String wlId;
	private TCoreAccn TCoreAccn;
	private String wlName;
	private Character wlStatus;
	private String wlImgLoc;
	private Date wlDtCreate;
	private String wtUidCreate;
	private Date wlDtLupd;
	private String wlUidLupd;

	public TCkWhitelabel() {
	}

	public TCkWhitelabel(String wlId, TCoreAccn TCoreAccn, String wlName) {
		this.wlId = wlId;
		this.TCoreAccn = TCoreAccn;
		this.wlName = wlName;
	}

	public TCkWhitelabel(String wlId, TCoreAccn TCoreAccn, String wlName, Character wlStatus, String wlImgLoc,
			Date wlDtCreate, String wtUidCreate, Date wlDtLupd, String wlUidLupd) {
		this.wlId = wlId;
		this.TCoreAccn = TCoreAccn;
		this.wlName = wlName;
		this.wlStatus = wlStatus;
		this.wlImgLoc = wlImgLoc;
		this.wlDtCreate = wlDtCreate;
		this.wtUidCreate = wtUidCreate;
		this.wlDtLupd = wlDtLupd;
		this.wlUidLupd = wlUidLupd;
	}

	@Id

	@Column(name = "WL_ID", unique = true, nullable = false, length = 35)
	public String getWlId() {
		return this.wlId;
	}

	public void setWlId(String wlId) {
		this.wlId = wlId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "WL_ACCN_ID", nullable = false)
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@Column(name = "WL_NAME", nullable = false, length = 35)
	public String getWlName() {
		return this.wlName;
	}

	public void setWlName(String wlName) {
		this.wlName = wlName;
	}

	@Column(name = "WL_STATUS", length = 1)
	public Character getWlStatus() {
		return this.wlStatus;
	}

	public void setWlStatus(Character wlStatus) {
		this.wlStatus = wlStatus;
	}

	@Column(name = "WL_IMG_LOC", length = 1024)
	public String getWlImgLoc() {
		return this.wlImgLoc;
	}

	public void setWlImgLoc(String wlImgLoc) {
		this.wlImgLoc = wlImgLoc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "WL_DT_CREATE", length = 19)
	public Date getWlDtCreate() {
		return this.wlDtCreate;
	}

	public void setWlDtCreate(Date wlDtCreate) {
		this.wlDtCreate = wlDtCreate;
	}

	@Column(name = "WT_UID_CREATE", length = 35)
	public String getWtUidCreate() {
		return this.wtUidCreate;
	}

	public void setWtUidCreate(String wtUidCreate) {
		this.wtUidCreate = wtUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "WL_DT_LUPD", length = 19)
	public Date getWlDtLupd() {
		return this.wlDtLupd;
	}

	public void setWlDtLupd(Date wlDtLupd) {
		this.wlDtLupd = wlDtLupd;
	}

	@Column(name = "WL_UID_LUPD", length = 35)
	public String getWlUidLupd() {
		return this.wlUidLupd;
	}

	public void setWlUidLupd(String wlUidLupd) {
		this.wlUidLupd = wlUidLupd;
	}

	@Override
	public int compareTo(TCkWhitelabel o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

}
