package com.guudint.clickargo.common.model;
// Generated 23 Sep 2023, 2:27:49 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkWorkflowRemark generated by hbm2java
 */
@Entity
@Table(name = "T_CK_WORKFLOW_REMARK")
public class TCkWorkflowRemark extends COAbstractEntity<TCkWorkflowRemark> {

	private static final long serialVersionUID = 8429371983874104720L;
	private String arId;
	private TCkMstRemarkType TCkMstRemarkType;
	private TCkMstWorkflowType TCkMstWorkflowType;
	private TCoreAccn TCoreAccn;
	private String arRemark;
	private Character atStatus;
	private Date atDtCreate;
	private String atUidCreate;
	private Date atDtLupd;
	private String atUidLupd;

	public TCkWorkflowRemark() {
	}

	public TCkWorkflowRemark(String arId, TCkMstRemarkType TCkMstRemarkType, TCkMstWorkflowType TCkMstWorkflowType,
			TCoreAccn TCoreAccn, String arRemark) {
		this.arId = arId;
		this.TCkMstRemarkType = TCkMstRemarkType;
		this.TCkMstWorkflowType = TCkMstWorkflowType;
		this.TCoreAccn = TCoreAccn;
		this.arRemark = arRemark;
	}

	public TCkWorkflowRemark(String arId, TCkMstRemarkType TCkMstRemarkType, TCkMstWorkflowType TCkMstWorkflowType,
			TCoreAccn TCoreAccn, String arRemark, Character atStatus, Date atDtCreate, String atUidCreate,
			Date atDtLupd, String atUidLupd) {
		this.arId = arId;
		this.TCkMstRemarkType = TCkMstRemarkType;
		this.TCkMstWorkflowType = TCkMstWorkflowType;
		this.TCoreAccn = TCoreAccn;
		this.arRemark = arRemark;
		this.atStatus = atStatus;
		this.atDtCreate = atDtCreate;
		this.atUidCreate = atUidCreate;
		this.atDtLupd = atDtLupd;
		this.atUidLupd = atUidLupd;
	}

	@Id

	@Column(name = "AR_ID", unique = true, nullable = false, length = 35)
	public String getArId() {
		return this.arId;
	}

	public void setArId(String arId) {
		this.arId = arId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AR_TYPE", nullable = false)
	public TCkMstRemarkType getTCkMstRemarkType() {
		return this.TCkMstRemarkType;
	}

	public void setTCkMstRemarkType(TCkMstRemarkType TCkMstRemarkType) {
		this.TCkMstRemarkType = TCkMstRemarkType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AR_WORKFLOW", nullable = false)
	public TCkMstWorkflowType getTCkMstWorkflowType() {
		return this.TCkMstWorkflowType;
	}

	public void setTCkMstWorkflowType(TCkMstWorkflowType TCkMstWorkflowType) {
		this.TCkMstWorkflowType = TCkMstWorkflowType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AR_ACCN", nullable = false)
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@Column(name = "AR_REMARK", nullable = false, length = 16777215)
	public String getArRemark() {
		return this.arRemark;
	}

	public void setArRemark(String arRemark) {
		this.arRemark = arRemark;
	}

	@Column(name = "AT_STATUS", length = 1)
	public Character getAtStatus() {
		return this.atStatus;
	}

	public void setAtStatus(Character atStatus) {
		this.atStatus = atStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AT_DT_CREATE", length = 19)
	public Date getAtDtCreate() {
		return this.atDtCreate;
	}

	public void setAtDtCreate(Date atDtCreate) {
		this.atDtCreate = atDtCreate;
	}

	@Column(name = "AT_UID_CREATE", length = 35)
	public String getAtUidCreate() {
		return this.atUidCreate;
	}

	public void setAtUidCreate(String atUidCreate) {
		this.atUidCreate = atUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AT_DT_LUPD", length = 19)
	public Date getAtDtLupd() {
		return this.atDtLupd;
	}

	public void setAtDtLupd(Date atDtLupd) {
		this.atDtLupd = atDtLupd;
	}

	@Column(name = "AT_UID_LUPD", length = 35)
	public String getAtUidLupd() {
		return this.atUidLupd;
	}

	public void setAtUidLupd(String atUidLupd) {
		this.atUidLupd = atUidLupd;
	}

	@Override
	public int compareTo(TCkWorkflowRemark o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
