

INSERT INTO `clickargo2`.`T_CK_SVC_SUB` (`SUB_ID`, `SUB_TYPE`, `SUB_STATE`, `SUB_SUBSCRIBER`, `SUB_DT_START`, `SUB_DT_VALID`, `SUB_AUTO_RENEW`, `SUB_UID_VERIFY`, `SUB_DT_VERIFY`, `SUB_UID_APPROVE`, `SUB_DT_APPROVE`, `SUB_STATUS`, `SUB_DT_CREATE`, `SUB_UID_CREATE`) 
VALUES ('CK0007', 'CLICTRUCK', 'APR', 'CK0007', sysdate(), '2033-01-01 00:00:00', 'N', 'sys', sysdate(), 'sys', sysdate(), 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_SVC_SUB` (`SUB_ID`, `SUB_TYPE`, `SUB_STATE`, `SUB_SUBSCRIBER`, `SUB_DT_START`, `SUB_DT_VALID`, `SUB_AUTO_RENEW`, `SUB_UID_VERIFY`, `SUB_DT_VERIFY`, `SUB_UID_APPROVE`, `SUB_DT_APPROVE`, `SUB_STATUS`, `SUB_DT_CREATE`, `SUB_UID_CREATE`) 
VALUES ('CK0008', 'CLICTRUCK', 'APR', 'CK0008', sysdate(), '2033-01-01 00:00:00', 'N', 'sys', sysdate(), 'sys', sysdate(), 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_SVC_SUB` (`SUB_ID`, `SUB_TYPE`, `SUB_STATE`, `SUB_SUBSCRIBER`, `SUB_DT_START`, `SUB_DT_VALID`, `SUB_AUTO_RENEW`, `SUB_UID_VERIFY`, `SUB_DT_VERIFY`, `SUB_UID_APPROVE`, `SUB_DT_APPROVE`, `SUB_STATUS`, `SUB_DT_CREATE`, `SUB_UID_CREATE`) 
VALUES ('CK0009', 'CLICTRUCK', 'APR', 'CK0009', sysdate(), '2033-01-01 00:00:00', 'N', 'sys', sysdate(), 'sys', sysdate(), 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_SVC_SUB` (`SUB_ID`, `SUB_TYPE`, `SUB_STATE`, `SUB_SUBSCRIBER`, `SUB_DT_START`, `SUB_DT_VALID`, `SUB_AUTO_RENEW`, `SUB_UID_VERIFY`, `SUB_DT_VERIFY`, `SUB_UID_APPROVE`, `SUB_DT_APPROVE`, `SUB_STATUS`, `SUB_DT_CREATE`, `SUB_UID_CREATE`) 
VALUES ('CK0010', 'CLICTRUCK', 'APR', 'CK0010', sysdate(), '2033-01-01 00:00:00', 'N', 'sys', sysdate(), 'sys', sysdate(), 'A', sysdate(), 'sys');
