package com.guudint.clickargo.docs.util;

import java.io.ByteArrayOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.apache.log4j.Logger;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;

import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.export.SimpleExporterInput;
import net.sf.jasperreports.export.SimpleOutputStreamExporterOutput;

/**
 * Utility class to generate the supporting documents generated by the system.
 */
public class JasperDocsUtil {

	// Static Attributes
	////////////////////
	private static Logger log = Logger.getLogger(JasperDocsUtil.class);

	/***
	 * Generate report for template with list. This is applicable for preview where
	 * the request to generate the PDF is initiated from the client.
	 * 
	 * @param request
	 * @param jrXmlString
	 * @param parameters
	 * @return
	 */
	public static byte[] createPDF(HttpServletRequest request, String jrXmlString, Map<String, Object> parameters) {
		ByteArrayOutputStream byteStream = null;
		try {
			JasperReport jasperReport = getReportTemplate(request, jrXmlString);

			JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, new JREmptyDataSource());

			byteStream = new ByteArrayOutputStream();
			JasperExportManager.exportReportToPdfStream(jasperPrint, byteStream);

		} catch (Exception e) {
			log.error("createPDF", e);
		} finally {
			try {
				if (null != byteStream) {
					byteStream.close();
				}
			} catch (Exception e) {
				log.error("createPDF", e);
			}
		}
		if (byteStream != null) {
			return byteStream.toByteArray();
		} else {
			return null;
		}
	}

	/***
	 * Generate report for template with list.
	 * 
	 * @param request
	 * @param jrXmlString
	 * @param parameters
	 * @return
	 */
	public static byte[] createPDF(String basePath, String jrXmlString, Map<String, Object> parameters) {
		ByteArrayOutputStream byteStream = null;
		try {
			JasperReport jasperReport = getReportTemplate(basePath, jrXmlString);

			JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, new JREmptyDataSource());

			byteStream = new ByteArrayOutputStream();
			JasperExportManager.exportReportToPdfStream(jasperPrint, byteStream);

		} catch (Exception e) {
			log.error("createPDF", e);
		} finally {
			try {
				if (null != byteStream) {
					byteStream.close();
				}
			} catch (Exception e) {
				log.error("createPDF", e);
			}
		}
		if (byteStream != null) {
			return byteStream.toByteArray();
		} else {
			return null;
		}
	}

	/***
	 * Generate report for template without list. This is applicable for preview
	 * where the request to generate the PDF is initiated from the client.
	 * 
	 * @param request
	 * @param jrXmlString
	 * @param parameters
	 * @param dataSource
	 * @return
	 */
	public static byte[] createPDF(HttpServletRequest request, String jrXmlString, Map<String, Object> parameters,
			JRBeanCollectionDataSource dataSource) {

		ByteArrayOutputStream byteStream = null;
		try {
			JasperReport jasperReport = getReportTemplate(request, jrXmlString);

			JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, dataSource);

			byteStream = new ByteArrayOutputStream();
			JasperExportManager.exportReportToPdfStream(jasperPrint, byteStream);

		} catch (Exception e) {
			log.error("createPDF", e);
		} finally {
			try {
				if (null != byteStream) {
					byteStream.close();
				}
			} catch (Exception ex) {
				log.error("createPDF", ex);
			}
		}

		if (byteStream != null) {
			return byteStream.toByteArray();
		} else {
			return null;
		}
	}

	/***
	 * Generate report for template without list.
	 * 
	 * @param request
	 * @param jrXmlString
	 * @param parameters
	 * @param dataSource
	 * @return
	 */
	public static byte[] createPDF(String basePath, String jrXmlString, Map<String, Object> parameters,
			JRBeanCollectionDataSource dataSource) {

		ByteArrayOutputStream byteStream = null;
		try {
			JasperReport jasperReport = getReportTemplate(basePath, jrXmlString);

			JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, dataSource);

			byteStream = new ByteArrayOutputStream();
			JasperExportManager.exportReportToPdfStream(jasperPrint, byteStream);

		} catch (Exception e) {
			e.printStackTrace();
			log.error("createPDF", e);
		} finally {
			try {
				if (null != byteStream) {
					byteStream.close();
					byteStream.flush();
				}
			} catch (Exception ex) {
				ex.printStackTrace();
				log.error("createPDF", ex);
			}
		}

		if (byteStream != null) {
			return byteStream.toByteArray();
		} else {
			return null;
		}
	}

	/***
	 * Generate report for template without list.
	 * 
	 * @param request
	 * @param jrXmlString
	 * @param parameters
	 * @param dataSource
	 * @return
	 */
	public static byte[] createPDF(String basePath, List<String> jrXmlString, Map<String, Object> parameters,
			JRBeanCollectionDataSource dataSource) {

		ByteArrayOutputStream byteStream = null;
		List<JasperPrint> list = new ArrayList<JasperPrint>();
		JRPdfExporter exp = new JRPdfExporter();
		for (String jrxmlFile : jrXmlString) {

			try {

				JasperReport jasperReport = getReportTemplate(basePath, jrxmlFile);
				JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, dataSource);
				list.add(jasperPrint);
//				byteStream = new ByteArrayOutputStream();
//				JasperExportManager.exportReportToPdfStream(jasperPrint, byteStream);

			} catch (Exception e) {
				e.printStackTrace();
				log.error("createPDF", e);
			} finally {
				try {
					if (null != byteStream) {
						byteStream.close();
						byteStream.flush();
					}
				} catch (Exception ex) {
					ex.printStackTrace();
					log.error("createPDF", ex);
				}
			}
		}

		if (!list.isEmpty()) {
			try {
				byteStream = new ByteArrayOutputStream();
				exp.setExporterInput(SimpleExporterInput.getInstance(list));
				exp.setExporterOutput(new SimpleOutputStreamExporterOutput(byteStream));
				exp.exportReport();

			} catch (Exception ex) {
				ex.printStackTrace();
			}

		}

		if (byteStream != null) {
			return byteStream.toByteArray();
		} else {
			return null;
		}
	}

	/***
	 *
	 * @param fileName
	 * @return
	 */
	public static HttpHeaders getPDFHeader(String fileName) {
		HttpHeaders headers = new HttpHeaders();
		headers.setContentType(MediaType.parseMediaType("application/pdf"));
		StringBuilder builder = new StringBuilder("inline; filename=\"");
		builder.append(fileName).append('\"');
		headers.add("Content-Disposition", builder.toString());
		headers.setCacheControl("must-revalidate, post-check=0, pre-check=0");
		return headers;
	}

	/***
	 *
	 * @param request
	 * @param jrXmlString
	 * @return
	 * @throws Exception
	 */
	private static JasperReport getReportTemplate(HttpServletRequest request, String jrXmlString) throws Exception {
		return JasperCompileManager.compileReport(request.getSession().getServletContext().getRealPath(jrXmlString));
	}

	/***
	 *
	 * @param request
	 * @param jrXmlString
	 * @return
	 * @throws Exception
	 */
	private static JasperReport getReportTemplate(String basePath, String jrXmlString) throws Exception {
		return JasperCompileManager.compileReport(basePath.concat(jrXmlString));
	}

}
