package com.guudint.clickargo.payment.model;
// Generated 6 Dec, 2022 12:37:38 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkPaymentTxnInvoice generated by hbm2java
 */
@Entity
@Table(name = "T_CK_PAYMENT_TXN_INVOICE")
public class TCkPaymentTxnInvoice extends COAbstractEntity<TCkPaymentTxnInvoice> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -2964572944756531489L;
	
	// Attributes
	//////////////
	private String ptiId;
	private TCkPaymentTxn TCkPaymentTxn;
	private String ptiInvId;
	private Character ptiStatus;
	private Date ptiDtCreate;
	private String ptiUidCreate;
	private Date ptiDtLupd;
	private String ptiUidLupd;

	// Constructors
	///////////////
	public TCkPaymentTxnInvoice() {
	}

	/**
	 * @param ptiId
	 * @param TCkPaymentTxn
	 * @param ptiInvId
	 */
	public TCkPaymentTxnInvoice(String ptiId, TCkPaymentTxn TCkPaymentTxn, String ptiInvId) {
		this.ptiId = ptiId;
		this.TCkPaymentTxn = TCkPaymentTxn;
		this.ptiInvId = ptiInvId;
	}

	/**
	 * @param ptiId
	 * @param TCkPaymentTxn
	 * @param ptiInvId
	 * @param ptiStatus
	 * @param ptiDtCreate
	 * @param ptiUidCreate
	 * @param ptiDtLupd
	 * @param ptiUidLupd
	 */
	public TCkPaymentTxnInvoice(String ptiId, TCkPaymentTxn TCkPaymentTxn, String ptiInvId, Character ptiStatus,
			Date ptiDtCreate, String ptiUidCreate, Date ptiDtLupd, String ptiUidLupd) {
		this.ptiId = ptiId;
		this.TCkPaymentTxn = TCkPaymentTxn;
		this.ptiInvId = ptiInvId;
		this.ptiStatus = ptiStatus;
		this.ptiDtCreate = ptiDtCreate;
		this.ptiUidCreate = ptiUidCreate;
		this.ptiDtLupd = ptiDtLupd;
		this.ptiUidLupd = ptiUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	*/
	@Override
	public int compareTo(TCkPaymentTxnInvoice o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	*/
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}
	
	// Properties
	//////////////
	@Id
	@Column(name = "PTI_ID", unique = true, nullable = false, length = 35)
	public String getPtiId() {
		return this.ptiId;
	}

	public void setPtiId(String ptiId) {
		this.ptiId = ptiId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PTI_TXN_ID", nullable = false)
	public TCkPaymentTxn getTCkPaymentTxn() {
		return this.TCkPaymentTxn;
	}

	public void setTCkPaymentTxn(TCkPaymentTxn TCkPaymentTxn) {
		this.TCkPaymentTxn = TCkPaymentTxn;
	}

	@Column(name = "PTI_INV_ID", nullable = false, length = 35)
	public String getPtiInvId() {
		return this.ptiInvId;
	}

	public void setPtiInvId(String ptiInvId) {
		this.ptiInvId = ptiInvId;
	}

	@Column(name = "PTI_STATUS", length = 1)
	public Character getPtiStatus() {
		return this.ptiStatus;
	}

	public void setPtiStatus(Character ptiStatus) {
		this.ptiStatus = ptiStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PTI_DT_CREATE", length = 19)
	public Date getPtiDtCreate() {
		return this.ptiDtCreate;
	}

	public void setPtiDtCreate(Date ptiDtCreate) {
		this.ptiDtCreate = ptiDtCreate;
	}

	@Column(name = "PTI_UID_CREATE", length = 35)
	public String getPtiUidCreate() {
		return this.ptiUidCreate;
	}

	public void setPtiUidCreate(String ptiUidCreate) {
		this.ptiUidCreate = ptiUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PTI_DT_LUPD", length = 19)
	public Date getPtiDtLupd() {
		return this.ptiDtLupd;
	}

	public void setPtiDtLupd(Date ptiDtLupd) {
		this.ptiDtLupd = ptiDtLupd;
	}

	@Column(name = "PTI_UID_LUPD", length = 35)
	public String getPtiUidLupd() {
		return this.ptiUidLupd;
	}

	public void setPtiUidLupd(String ptiUidLupd) {
		this.ptiUidLupd = ptiUidLupd;
	}
}
