package com.guudint.clickargo.payment.model;
// Generated 22 Jun 2023, 6:23:51 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.master.model.TCkMstServiceType;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkPaymentTerms generated by hbm2java
 */
@Entity
@Table(name = "T_CK_PAYMENT_TERMS")
public class TCkPaymentTerms extends COAbstractEntity<TCkPaymentTerms> {

	private static final long serialVersionUID = -4613654241993170359L;
	private String ptId;
	private TCkMstServiceType TCkMstServiceType;
	private TCoreAccn TCoreAccn;
	private Integer ptPymentTerms;
	private Integer ptMonthlyCap;
	private Character ptStatus;
	private Date ptDtCreate;
	private String ptUidCreate;
	private Date ptDtLupd;
	private String ptUidLupd;

	public TCkPaymentTerms() {
	}

	public TCkPaymentTerms(String ptId, TCoreAccn TCoreAccn) {
		this.ptId = ptId;
		this.TCoreAccn = TCoreAccn;
	}

	public TCkPaymentTerms(String ptId, TCkMstServiceType TCkMstServiceType, TCoreAccn TCoreAccn, Integer ptPymentTerms,
			Integer ptMonthlyCap, Character ptStatus, Date ptDtCreate, String ptUidCreate, Date ptDtLupd,
			String ptUidLupd) {
		this.ptId = ptId;
		this.TCkMstServiceType = TCkMstServiceType;
		this.TCoreAccn = TCoreAccn;
		this.ptPymentTerms = ptPymentTerms;
		this.ptMonthlyCap = ptMonthlyCap;
		this.ptStatus = ptStatus;
		this.ptDtCreate = ptDtCreate;
		this.ptUidCreate = ptUidCreate;
		this.ptDtLupd = ptDtLupd;
		this.ptUidLupd = ptUidLupd;
	}

	@Id

	@Column(name = "PT_ID", unique = true, nullable = false, length = 35)
	public String getPtId() {
		return this.ptId;
	}

	public void setPtId(String ptId) {
		this.ptId = ptId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PT_SERVICE_TYPE")
	public TCkMstServiceType getTCkMstServiceType() {
		return this.TCkMstServiceType;
	}

	public void setTCkMstServiceType(TCkMstServiceType TCkMstServiceType) {
		this.TCkMstServiceType = TCkMstServiceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PT_COMPANY", nullable = false)
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@Column(name = "PT_PYMENT_TERMS")
	public Integer getPtPymentTerms() {
		return this.ptPymentTerms;
	}

	public void setPtPymentTerms(Integer ptPymentTerms) {
		this.ptPymentTerms = ptPymentTerms;
	}

	@Column(name = "PT_MONTHLY_CAP")
	public Integer getPtMonthlyCap() {
		return this.ptMonthlyCap;
	}

	public void setPtMonthlyCap(Integer ptMonthlyCap) {
		this.ptMonthlyCap = ptMonthlyCap;
	}

	@Column(name = "PT_STATUS", length = 1)
	public Character getPtStatus() {
		return this.ptStatus;
	}

	public void setPtStatus(Character ptStatus) {
		this.ptStatus = ptStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PT_DT_CREATE", length = 19)
	public Date getPtDtCreate() {
		return this.ptDtCreate;
	}

	public void setPtDtCreate(Date ptDtCreate) {
		this.ptDtCreate = ptDtCreate;
	}

	@Column(name = "PT_UID_CREATE", length = 35)
	public String getPtUidCreate() {
		return this.ptUidCreate;
	}

	public void setPtUidCreate(String ptUidCreate) {
		this.ptUidCreate = ptUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PT_DT_LUPD", length = 19)
	public Date getPtDtLupd() {
		return this.ptDtLupd;
	}

	public void setPtDtLupd(Date ptDtLupd) {
		this.ptDtLupd = ptDtLupd;
	}

	@Column(name = "PT_UID_LUPD", length = 35)
	public String getPtUidLupd() {
		return this.ptUidLupd;
	}

	public void setPtUidLupd(String ptUidLupd) {
		this.ptUidLupd = ptUidLupd;
	}

	@Override
	public int compareTo(TCkPaymentTerms o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
