package com.guudint.clickargo.payment.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.master.model.TCkMstPaymentType;
import com.guudint.clickargo.master.model.TCkMstServiceType;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.master.model.TMstCurrency;

/**
 * TCkPaymentLedger generated by hbm2java
 */
@Entity
@Table(name = "T_CK_PAYMENT_LEDGER")
public class TCkPaymentLedger extends COAbstractEntity<TCkPaymentLedger> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 3103545240167614951L;
	
	// Attributes
	/////////////
	private String pylId;
	private TCkMstPaymentType TCkMstPaymentType;
	private TCkMstServiceType TCkMstServiceType;
	private TCoreAccn TCoreAccnByPylPayee;
	private TCoreAccn TCoreAccnByPylPayer;
	private TMstCurrency TMstCurrency;
	private String pylServiceReference;
	private String pylMerchantBank;
	private String pylPayerBankAccn;
	private String pylPayeeBankAccn;
	private BigDecimal pylAmount;
	private String pylBankRef;
	private String pylPaymentState;
	private Character pylStatus;
	private Date pylDtCreate;
	private String pylUidCreate;
	private Date pylDtLupd;
	private String pylUidLupd;

	// Constructors
	///////////////
	public TCkPaymentLedger() {
	}

	/**
	 * @param pylId
	 */
	public TCkPaymentLedger(String pylId) {
		this.pylId = pylId;
	}

	/**
	 * @param pylId
	 * @param TCkMstPaymentType
	 * @param TCkMstServiceType
	 * @param TCoreAccnByPylPayee
	 * @param TCoreAccnByPylPayer
	 * @param TMstCurrency
	 * @param pylServiceReference
	 * @param pylMerchantBank
	 * @param pylPayerBankAccn
	 * @param pylPayeeBankAccn
	 * @param pylAmount
	 * @param pylBankRef
	 * @param pylPaymentState
	 * @param pylStatus
	 * @param pylDtCreate
	 * @param pylUidCreate
	 * @param pylDtLupd
	 * @param pylUidLupd
	 * @param TCkPaymentAudits
	 */
	public TCkPaymentLedger(String pylId, TCkMstPaymentType TCkMstPaymentType, TCkMstServiceType TCkMstServiceType,
			TCoreAccn TCoreAccnByPylPayee, TCoreAccn TCoreAccnByPylPayer, TMstCurrency TMstCurrency,
			String pylServiceReference, String pylMerchantBank, String pylPayerBankAccn, String pylPayeeBankAccn,
			BigDecimal pylAmount, String pylBankRef, String pylPaymentState, Character pylStatus, Date pylDtCreate,
			String pylUidCreate, Date pylDtLupd, String pylUidLupd, Set<TCkPaymentAudit> TCkPaymentAudits) {
		this.pylId = pylId;
		this.TCkMstPaymentType = TCkMstPaymentType;
		this.TCkMstServiceType = TCkMstServiceType;
		this.TCoreAccnByPylPayee = TCoreAccnByPylPayee;
		this.TCoreAccnByPylPayer = TCoreAccnByPylPayer;
		this.TMstCurrency = TMstCurrency;
		this.pylServiceReference = pylServiceReference;
		this.pylMerchantBank = pylMerchantBank;
		this.pylPayerBankAccn = pylPayerBankAccn;
		this.pylPayeeBankAccn = pylPayeeBankAccn;
		this.pylAmount = pylAmount;
		this.pylBankRef = pylBankRef;
		this.pylPaymentState = pylPaymentState;
		this.pylStatus = pylStatus;
		this.pylDtCreate = pylDtCreate;
		this.pylUidCreate = pylUidCreate;
		this.pylDtLupd = pylDtLupd;
		this.pylUidLupd = pylUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkPaymentLedger o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}
	
	// Properties
	//////////////
	@Id
	@Column(name = "PYL_ID", unique = true, nullable = false, length = 35)
	public String getPylId() {
		return this.pylId;
	}

	public void setPylId(String pylId) {
		this.pylId = pylId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PYL_TYPE")
	public TCkMstPaymentType getTCkMstPaymentType() {
		return this.TCkMstPaymentType;
	}

	public void setTCkMstPaymentType(TCkMstPaymentType TCkMstPaymentType) {
		this.TCkMstPaymentType = TCkMstPaymentType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PYL_SERVICE")
	public TCkMstServiceType getTCkMstServiceType() {
		return this.TCkMstServiceType;
	}

	public void setTCkMstServiceType(TCkMstServiceType TCkMstServiceType) {
		this.TCkMstServiceType = TCkMstServiceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PYL_PAYEE")
	public TCoreAccn getTCoreAccnByPylPayee() {
		return this.TCoreAccnByPylPayee;
	}

	public void setTCoreAccnByPylPayee(TCoreAccn TCoreAccnByPylPayee) {
		this.TCoreAccnByPylPayee = TCoreAccnByPylPayee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PYL_PAYER")
	public TCoreAccn getTCoreAccnByPylPayer() {
		return this.TCoreAccnByPylPayer;
	}

	public void setTCoreAccnByPylPayer(TCoreAccn TCoreAccnByPylPayer) {
		this.TCoreAccnByPylPayer = TCoreAccnByPylPayer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PYL_CCY")
	public TMstCurrency getTMstCurrency() {
		return this.TMstCurrency;
	}

	public void setTMstCurrency(TMstCurrency TMstCurrency) {
		this.TMstCurrency = TMstCurrency;
	}

	@Column(name = "PYL_SERVICE_REFERENCE", length = 35)
	public String getPylServiceReference() {
		return this.pylServiceReference;
	}

	public void setPylServiceReference(String pylServiceReference) {
		this.pylServiceReference = pylServiceReference;
	}

	@Column(name = "PYL_MERCHANT_BANK", length = 35)
	public String getPylMerchantBank() {
		return this.pylMerchantBank;
	}

	public void setPylMerchantBank(String pylMerchantBank) {
		this.pylMerchantBank = pylMerchantBank;
	}

	@Column(name = "PYL_PAYER_BANK_ACCN")
	public String getPylPayerBankAccn() {
		return this.pylPayerBankAccn;
	}

	public void setPylPayerBankAccn(String pylPayerBankAccn) {
		this.pylPayerBankAccn = pylPayerBankAccn;
	}

	@Column(name = "PYL_PAYEE_BANK_ACCN")
	public String getPylPayeeBankAccn() {
		return this.pylPayeeBankAccn;
	}

	public void setPylPayeeBankAccn(String pylPayeeBankAccn) {
		this.pylPayeeBankAccn = pylPayeeBankAccn;
	}

	@Column(name = "PYL_AMOUNT", precision = 15)
	public BigDecimal getPylAmount() {
		return this.pylAmount;
	}

	public void setPylAmount(BigDecimal pylAmount) {
		this.pylAmount = pylAmount;
	}

	@Column(name = "PYL_BANK_REF")
	public String getPylBankRef() {
		return this.pylBankRef;
	}

	public void setPylBankRef(String pylBankRef) {
		this.pylBankRef = pylBankRef;
	}

	@Column(name = "PYL_PAYMENT_STATE", length = 35)
	public String getPylPaymentState() {
		return this.pylPaymentState;
	}

	public void setPylPaymentState(String pylPaymentState) {
		this.pylPaymentState = pylPaymentState;
	}

	@Column(name = "PYL_STATUS", length = 1)
	public Character getPylStatus() {
		return this.pylStatus;
	}

	public void setPylStatus(Character pylStatus) {
		this.pylStatus = pylStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PYL_DT_CREATE", length = 19)
	public Date getPylDtCreate() {
		return this.pylDtCreate;
	}

	public void setPylDtCreate(Date pylDtCreate) {
		this.pylDtCreate = pylDtCreate;
	}

	@Column(name = "PYL_UID_CREATE", length = 35)
	public String getPylUidCreate() {
		return this.pylUidCreate;
	}

	public void setPylUidCreate(String pylUidCreate) {
		this.pylUidCreate = pylUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PYL_DT_LUPD", length = 19)
	public Date getPylDtLupd() {
		return this.pylDtLupd;
	}

	public void setPylDtLupd(Date pylDtLupd) {
		this.pylDtLupd = pylDtLupd;
	}

	@Column(name = "PYL_UID_LUPD", length = 35)
	public String getPylUidLupd() {
		return this.pylUidLupd;
	}

	public void setPylUidLupd(String pylUidLupd) {
		this.pylUidLupd = pylUidLupd;
	}

}
