package com.guudint.clickargo.payment.model;
// Generated 19 Dec 2022, 10:45:00 am by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.job.model.TCkJob;
import com.guudint.clickargo.master.model.TCkMstInvoiceType;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkPaymentTxnAttInvoice generated by hbm2java
 */
@Entity
@Table(name = "T_CK_PAYMENT_TXN_ATT_INVOICE")
public class TCkPaymentTxnAttInvoice extends COAbstractEntity<TCkPaymentTxnAttInvoice> {

	private static final long serialVersionUID = -4146313171756240405L;
	private String ptxAttInvId;
	private TCkJob TCkJob;
	private TCkMstInvoiceType TCkMstInvoiceType;
	private String ptxAttInvName;
	private String ptxAttInvLoc;
	private Character ptxAttInvStatus;
	private Date ptxAttInvDtCreate;
	private String ptxAttInvUidCreate;
	private Date ptxAttInvDtLupd;
	private String ptxAttInvUidLupd;

	public TCkPaymentTxnAttInvoice() {
	}

	public TCkPaymentTxnAttInvoice(String ptxAttInvId, TCkJob TCkJob, TCkMstInvoiceType TCkMstInvoiceType) {
		this.ptxAttInvId = ptxAttInvId;
		this.TCkJob = TCkJob;
		this.TCkMstInvoiceType = TCkMstInvoiceType;
	}

	public TCkPaymentTxnAttInvoice(String ptxAttInvId, TCkJob TCkJob, TCkMstInvoiceType TCkMstInvoiceType,
			String ptxAttInvName, String ptxAttInvLoc, Character ptxAttInvStatus, Date ptxAttInvDtCreate,
			String ptxAttInvUidCreate, Date ptxAttInvDtLupd, String ptxAttInvUidLupd) {
		this.ptxAttInvId = ptxAttInvId;
		this.TCkJob = TCkJob;
		this.TCkMstInvoiceType = TCkMstInvoiceType;
		this.ptxAttInvName = ptxAttInvName;
		this.ptxAttInvLoc = ptxAttInvLoc;
		this.ptxAttInvStatus = ptxAttInvStatus;
		this.ptxAttInvDtCreate = ptxAttInvDtCreate;
		this.ptxAttInvUidCreate = ptxAttInvUidCreate;
		this.ptxAttInvDtLupd = ptxAttInvDtLupd;
		this.ptxAttInvUidLupd = ptxAttInvUidLupd;
	}

	@Id

	@Column(name = "PTX_ATT_INV_ID", unique = true, nullable = false, length = 35)
	public String getPtxAttInvId() {
		return this.ptxAttInvId;
	}

	public void setPtxAttInvId(String ptxAttInvId) {
		this.ptxAttInvId = ptxAttInvId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PTX_ATT_INV_JOB", nullable = false)
	public TCkJob getTCkJob() {
		return this.TCkJob;
	}

	public void setTCkJob(TCkJob TCkJob) {
		this.TCkJob = TCkJob;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PTX_ATT_INV_TYPE", nullable = false)
	public TCkMstInvoiceType getTCkMstInvoiceType() {
		return this.TCkMstInvoiceType;
	}

	public void setTCkMstInvoiceType(TCkMstInvoiceType TCkMstInvoiceType) {
		this.TCkMstInvoiceType = TCkMstInvoiceType;
	}

	@Column(name = "PTX_ATT_INV_NAME", length = 256)
	public String getPtxAttInvName() {
		return this.ptxAttInvName;
	}

	public void setPtxAttInvName(String ptxAttInvName) {
		this.ptxAttInvName = ptxAttInvName;
	}

	@Column(name = "PTX_ATT_INV_LOC", length = 1024)
	public String getPtxAttInvLoc() {
		return this.ptxAttInvLoc;
	}

	public void setPtxAttInvLoc(String ptxAttInvLoc) {
		this.ptxAttInvLoc = ptxAttInvLoc;
	}

	@Column(name = "PTX_ATT_INV_STATUS", length = 1)
	public Character getPtxAttInvStatus() {
		return this.ptxAttInvStatus;
	}

	public void setPtxAttInvStatus(Character ptxAttInvStatus) {
		this.ptxAttInvStatus = ptxAttInvStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PTX_ATT_INV_DT_CREATE", length = 19)
	public Date getPtxAttInvDtCreate() {
		return this.ptxAttInvDtCreate;
	}

	public void setPtxAttInvDtCreate(Date ptxAttInvDtCreate) {
		this.ptxAttInvDtCreate = ptxAttInvDtCreate;
	}

	@Column(name = "PTX_ATT_INV_UID_CREATE", length = 35)
	public String getPtxAttInvUidCreate() {
		return this.ptxAttInvUidCreate;
	}

	public void setPtxAttInvUidCreate(String ptxAttInvUidCreate) {
		this.ptxAttInvUidCreate = ptxAttInvUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PTX_ATT_INV_DT_LUPD", length = 19)
	public Date getPtxAttInvDtLupd() {
		return this.ptxAttInvDtLupd;
	}

	public void setPtxAttInvDtLupd(Date ptxAttInvDtLupd) {
		this.ptxAttInvDtLupd = ptxAttInvDtLupd;
	}

	@Column(name = "PTX_ATT_INV_UID_LUPD", length = 35)
	public String getPtxAttInvUidLupd() {
		return this.ptxAttInvUidLupd;
	}

	public void setPtxAttInvUidLupd(String ptxAttInvUidLupd) {
		this.ptxAttInvUidLupd = ptxAttInvUidLupd;
	}

	@Override
	public int compareTo(TCkPaymentTxnAttInvoice arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
