package com.guudint.clickargo.payment.model;
// Generated 6 Dec, 2022 12:37:38 AM by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.master.model.TCkMstPaymentType;
import com.guudint.clickargo.master.model.TCkMstServiceType;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.master.model.TMstCurrency;

/**
 * TCkPaymentTxn generated by hbm2java
 */
@Entity
@Table(name = "T_CK_PAYMENT_TXN")
public class TCkPaymentTxn extends COAbstractEntity<TCkPaymentTxn> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 3954550320769517629L;

	// Attributes
	/////////////
	private String ptxId;
	private TCkMstPaymentType TCkMstPaymentType;
	private TCkMstServiceType TCkMstServiceType;
	private TCoreAccn TCoreAccnByPtxPayee;
	private TCoreAccn TCoreAccnByPtxPayer;
	private TMstCurrency TMstCurrency;
	private String ptxSvcRef;
	private String ptxMerchantBank;
	private String ptxPayerBankAccn;
	private String ptxPayeeBankAccn;
	private String ptxPayeeBankAccnName;
	private BigDecimal ptxAmount;
	private String ptxBankRef;
	private String ptxPaymentState;
	private Date ptxDtPaid;
	private Date ptxDtFinApproved;
	private String ptxUidFinApproved;
	private Date ptxDtFinVerified;
	private String ptxUidFinVerified;
	private Date ptxDtDue;
	private Character ptxStatus;
	private Date ptxDtCreate;
	private String ptxUidCreate;
	private Date ptxDtLupd;
	private String ptxUidLupd;

	// Constructors
	///////////////
	public TCkPaymentTxn() {
	}

	/**
	 * @param ptxId
	 */
	public TCkPaymentTxn(String ptxId) {
		this.ptxId = ptxId;
	}

	/**
	 * @param ptxId
	 * @param TCkMstPaymentType
	 * @param TCkMstServiceType
	 * @param TCoreAccnByPtxPayee
	 * @param TCoreAccnByPtxPayer
	 * @param TMstCurrency
	 * @param ptxSvcRef
	 * @param ptxMerchantBank
	 * @param ptxPayerBankAccn
	 * @param ptxPayeeBankAccn
	 * @param ptxAmount
	 * @param ptxBankRef
	 * @param ptxPaymentState
	 * @param ptxStatus
	 * @param ptxDtCreate
	 * @param ptxUidCreate
	 * @param ptxDtLupd
	 * @param ptxUidLupd
	 */
	public TCkPaymentTxn(String ptxId, TCkMstPaymentType TCkMstPaymentType, TCkMstServiceType TCkMstServiceType,
			TCoreAccn TCoreAccnByPtxPayee, TCoreAccn TCoreAccnByPtxPayer, TMstCurrency TMstCurrency, String ptxSvcRef,
			String ptxMerchantBank, String ptxPayerBankAccn, String ptxPayeeBankAccn, BigDecimal ptxAmount,
			String ptxBankRef, String ptxPaymentState, Character ptxStatus, Date ptxDtCreate, String ptxUidCreate,
			Date ptxDtLupd, String ptxUidLupd) {
		this.ptxId = ptxId;
		this.TCkMstPaymentType = TCkMstPaymentType;
		this.TCkMstServiceType = TCkMstServiceType;
		this.TCoreAccnByPtxPayee = TCoreAccnByPtxPayee;
		this.TCoreAccnByPtxPayer = TCoreAccnByPtxPayer;
		this.TMstCurrency = TMstCurrency;
		this.ptxSvcRef = ptxSvcRef;
		this.ptxMerchantBank = ptxMerchantBank;
		this.ptxPayerBankAccn = ptxPayerBankAccn;
		this.ptxPayeeBankAccn = ptxPayeeBankAccn;
		this.ptxAmount = ptxAmount;
		this.ptxBankRef = ptxBankRef;
		this.ptxPaymentState = ptxPaymentState;
		this.ptxStatus = ptxStatus;
		this.ptxDtCreate = ptxDtCreate;
		this.ptxUidCreate = ptxUidCreate;
		this.ptxDtLupd = ptxDtLupd;
		this.ptxUidLupd = ptxUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkPaymentTxn o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	// Properties
	/////////////
	@Id
	@Column(name = "PTX_ID", unique = true, nullable = false, length = 35)
	public String getPtxId() {
		return this.ptxId;
	}

	public void setPtxId(String ptxId) {
		this.ptxId = ptxId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PTX_TYPE")
	public TCkMstPaymentType getTCkMstPaymentType() {
		return this.TCkMstPaymentType;
	}

	public void setTCkMstPaymentType(TCkMstPaymentType TCkMstPaymentType) {
		this.TCkMstPaymentType = TCkMstPaymentType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PTX_SVC")
	public TCkMstServiceType getTCkMstServiceType() {
		return this.TCkMstServiceType;
	}

	public void setTCkMstServiceType(TCkMstServiceType TCkMstServiceType) {
		this.TCkMstServiceType = TCkMstServiceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PTX_PAYEE")
	public TCoreAccn getTCoreAccnByPtxPayee() {
		return this.TCoreAccnByPtxPayee;
	}

	public void setTCoreAccnByPtxPayee(TCoreAccn TCoreAccnByPtxPayee) {
		this.TCoreAccnByPtxPayee = TCoreAccnByPtxPayee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PTX_PAYER")
	public TCoreAccn getTCoreAccnByPtxPayer() {
		return this.TCoreAccnByPtxPayer;
	}

	public void setTCoreAccnByPtxPayer(TCoreAccn TCoreAccnByPtxPayer) {
		this.TCoreAccnByPtxPayer = TCoreAccnByPtxPayer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PTX_CCY")
	public TMstCurrency getTMstCurrency() {
		return this.TMstCurrency;
	}

	public void setTMstCurrency(TMstCurrency TMstCurrency) {
		this.TMstCurrency = TMstCurrency;
	}

	@Column(name = "PTX_SVC_REF", length = 35)
	public String getPtxSvcRef() {
		return this.ptxSvcRef;
	}

	public void setPtxSvcRef(String ptxSvcRef) {
		this.ptxSvcRef = ptxSvcRef;
	}

	@Column(name = "PTX_MERCHANT_BANK", length = 35)
	public String getPtxMerchantBank() {
		return this.ptxMerchantBank;
	}

	public void setPtxMerchantBank(String ptxMerchantBank) {
		this.ptxMerchantBank = ptxMerchantBank;
	}

	@Column(name = "PTX_PAYER_BANK_ACCN")
	public String getPtxPayerBankAccn() {
		return this.ptxPayerBankAccn;
	}

	public void setPtxPayerBankAccn(String ptxPayerBankAccn) {
		this.ptxPayerBankAccn = ptxPayerBankAccn;
	}

	@Column(name = "PTX_PAYEE_BANK_ACCN")
	public String getPtxPayeeBankAccn() {
		return this.ptxPayeeBankAccn;
	}

	public void setPtxPayeeBankAccn(String ptxPayeeBankAccn) {
		this.ptxPayeeBankAccn = ptxPayeeBankAccn;
	}
	
	
	@Column(name = "PTX_PAYEE_BANK_ACCN_NAME")
	public String getPtxPayeeBankAccnName() {
		return ptxPayeeBankAccnName;
	}

	public void setPtxPayeeBankAccnName(String ptxPayeeBankAccnName) {
		this.ptxPayeeBankAccnName = ptxPayeeBankAccnName;
	}

	@Column(name = "PTX_AMOUNT", precision = 15)
	public BigDecimal getPtxAmount() {
		return this.ptxAmount;
	}

	public void setPtxAmount(BigDecimal ptxAmount) {
		this.ptxAmount = ptxAmount;
	}

	@Column(name = "PTX_BANK_REF")
	public String getPtxBankRef() {
		return this.ptxBankRef;
	}

	public void setPtxBankRef(String ptxBankRef) {
		this.ptxBankRef = ptxBankRef;
	}

	@Column(name = "PTX_PAYMENT_STATE", length = 35)
	public String getPtxPaymentState() {
		return this.ptxPaymentState;
	}

	public void setPtxPaymentState(String ptxPaymentState) {
		this.ptxPaymentState = ptxPaymentState;
	}

	@Column(name = "PTX_STATUS", length = 1)
	public Character getPtxStatus() {
		return this.ptxStatus;
	}

	public void setPtxStatus(Character ptxStatus) {
		this.ptxStatus = ptxStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PTX_DT_PAID", length = 19)
	public Date getPtxDtPaid() {
		return ptxDtPaid;
	}

	public void setPtxDtPaid(Date ptxDtPaid) {
		this.ptxDtPaid = ptxDtPaid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PTX_DT_CREATE", length = 19)
	public Date getPtxDtCreate() {
		return this.ptxDtCreate;
	}

	public void setPtxDtCreate(Date ptxDtCreate) {
		this.ptxDtCreate = ptxDtCreate;
	}

	@Column(name = "PTX_UID_CREATE", length = 35)
	public String getPtxUidCreate() {
		return this.ptxUidCreate;
	}

	public void setPtxUidCreate(String ptxUidCreate) {
		this.ptxUidCreate = ptxUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PTX_DT_LUPD", length = 19)
	public Date getPtxDtLupd() {
		return this.ptxDtLupd;
	}

	public void setPtxDtLupd(Date ptxDtLupd) {
		this.ptxDtLupd = ptxDtLupd;
	}

	@Column(name = "PTX_UID_LUPD", length = 35)
	public String getPtxUidLupd() {
		return this.ptxUidLupd;
	}

	public void setPtxUidLupd(String ptxUidLupd) {
		this.ptxUidLupd = ptxUidLupd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PTX_DT_FIN_APPROVED", length = 19)
	public Date getPtxDtFinApproved() {
		return ptxDtFinApproved;
	}

	public void setPtxDtFinApproved(Date ptxDtFinApproved) {
		this.ptxDtFinApproved = ptxDtFinApproved;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PTX_DT_DUE", length = 19)
	public Date getPtxDtDue() {
		return ptxDtDue;
	}

	public void setPtxDtDue(Date ptxDtDue) {
		this.ptxDtDue = ptxDtDue;
	}

	@Column(name = "PTX_UID_FIN_APPROVED", length = 35)
	public String getPtxUidFinApproved() {
		return ptxUidFinApproved;
	}

	public void setPtxUidFinApproved(String ptxUidFinApproved) {
		this.ptxUidFinApproved = ptxUidFinApproved;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PTX_DT_FIN_VERIFIED", length = 19)
	public Date getPtxDtFinVerified() {
		return ptxDtFinVerified;
	}

	public void setPtxDtFinVerified(Date ptxDtFinVerified) {
		this.ptxDtFinVerified = ptxDtFinVerified;
	}

	
	@Column(name = "PTX_UID_FIN_VERIFIED", length = 35)
	public String getPtxUidFinVerified() {
		return ptxUidFinVerified;
	}

	public void setPtxUidFinVerified(String ptxUidFinVerified) {
		this.ptxUidFinVerified = ptxUidFinVerified;
	}

}
