package com.guudint.clickargo.payment.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.master.model.TCkMstPaymentAuditType;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkPaymentAudit generated by hbm2java
 */
@Entity
@Table(name = "T_CK_PAYMENT_AUDIT")
public class TCkPaymentAudit extends COAbstractEntity<TCkPaymentAudit> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1532967946262795165L;
	
	// Attributes
	/////////////
	private String pyaId;
	private TCkMstPaymentAuditType TCkMstPaymentAuditType;
	private String pyaReference;
	private String pyaReq;
	private String pyaResp;
	private String pyaCb;
	private String pyaRemark;
	private String pyaState;
	private Character pyaStatus;
	private Date pyaDtCreate;
	private String pyaUidCreate;
	private Date pyaDtLupd;
	private String pyaUidLupd;

	// Constructors
	///////////////
	public TCkPaymentAudit() {
	}

	/**
	 * @param pyaId
	 * @param TCkMstPaymentAuditType
	 */
	public TCkPaymentAudit(String pyaId, TCkMstPaymentAuditType TCkMstPaymentAuditType) {
		this.pyaId = pyaId;
		this.TCkMstPaymentAuditType = TCkMstPaymentAuditType;
	}

	/**
	 * @param pyaId
	 * @param TCkMstPaymentAuditType
	 * @param pyaReference
	 * @param pyaReq
	 * @param pyaResp
	 * @param pyaCb
	 * @param pyaRemark
	 * @param pyaStatus
	 * @param pyaDtCreate
	 * @param pyaUidCreate
	 * @param pyaDtLupd
	 * @param pyaUidLupd
	 */
	public TCkPaymentAudit(String pyaId, TCkMstPaymentAuditType TCkMstPaymentAuditType,
			String pyaReference, String pyaReq, String pyaResp, String pyaCb,
			String pyaRemark, Character pyaStatus, Date pyaDtCreate, String pyaUidCreate, Date pyaDtLupd,
			String pyaUidLupd) {
		this.pyaId = pyaId;
		this.TCkMstPaymentAuditType = TCkMstPaymentAuditType;
		this.pyaReference = pyaReference;
		this.pyaReq = pyaReq;
		this.pyaResp = pyaResp;
		this.pyaCb = pyaCb;
		this.pyaRemark = pyaRemark;
		this.pyaStatus = pyaStatus;
		this.pyaDtCreate = pyaDtCreate;
		this.pyaUidCreate = pyaUidCreate;
		this.pyaDtLupd = pyaDtLupd;
		this.pyaUidLupd = pyaUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkPaymentAudit o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}
	
	// Properties
	/////////////
	@Id
	@Column(name = "PYA_ID", unique = true, nullable = false, length = 35)
	public String getPyaId() {
		return this.pyaId;
	}

	public void setPyaId(String pyaId) {
		this.pyaId = pyaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PYA_TYPE", nullable = false)
	public TCkMstPaymentAuditType getTCkMstPaymentAuditType() {
		return this.TCkMstPaymentAuditType;
	}

	public void setTCkMstPaymentAuditType(TCkMstPaymentAuditType TCkMstPaymentAuditType) {
		this.TCkMstPaymentAuditType = TCkMstPaymentAuditType;
	}

	@Column(name = "PYA_REFERENCE", length = 1024)
	public String getPyaReference() {
		return this.pyaReference;
	}

	public void setPyaReference(String pyaReference) {
		this.pyaReference = pyaReference;
	}

	@Column(name = "PYA_REQ", length = 16777215)
	public String getPyaReq() {
		return this.pyaReq;
	}

	public void setPyaReq(String pyaReq) {
		this.pyaReq = pyaReq;
	}

	@Column(name = "PYA_RESP", length = 16777215)
	public String getPyaResp() {
		return this.pyaResp;
	}

	public void setPyaResp(String pyaResp) {
		this.pyaResp = pyaResp;
	}

	@Column(name = "PYA_CB", length = 16777215)
	public String getPyaCb() {
		return this.pyaCb;
	}

	public void setPyaCb(String pyaCb) {
		this.pyaCb = pyaCb;
	}

	@Column(name = "PYA_REMARK", length = 16777215)
	public String getPyaRemark() {
		return this.pyaRemark;
	}

	public void setPyaRemark(String pyaRemark) {
		this.pyaRemark = pyaRemark;
	}

	@Column(name = "PYA_STATUS", length = 1)
	public Character getPyaStatus() {
		return this.pyaStatus;
	}

	public void setPyaState(String pyaState) {
		this.pyaState = pyaState;
	}

	@Column(name = "PYA_STATE", length = 35)
	public String getPyaState() {
		return pyaState;
	}

	public void setPyaStatus(Character pyaStatus) {
		this.pyaStatus = pyaStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PYA_DT_CREATE", length = 19)
	public Date getPyaDtCreate() {
		return this.pyaDtCreate;
	}

	public void setPyaDtCreate(Date pyaDtCreate) {
		this.pyaDtCreate = pyaDtCreate;
	}

	@Column(name = "PYA_UID_CREATE", length = 35)
	public String getPyaUidCreate() {
		return this.pyaUidCreate;
	}

	public void setPyaUidCreate(String pyaUidCreate) {
		this.pyaUidCreate = pyaUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PYA_DT_LUPD", length = 19)
	public Date getPyaDtLupd() {
		return this.pyaDtLupd;
	}

	public void setPyaDtLupd(Date pyaDtLupd) {
		this.pyaDtLupd = pyaDtLupd;
	}

	@Column(name = "PYA_UID_LUPD", length = 35)
	public String getPyaUidLupd() {
		return this.pyaUidLupd;
	}

	public void setPyaUidLupd(String pyaUidLupd) {
		this.pyaUidLupd = pyaUidLupd;
	}
}
