package com.guudint.clickargo.payment.model;
// Generated 23 Aug 2023, 3:51:16 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkPaymentTxnLog generated by hbm2java
 */
@Entity
@Table(name = "T_CK_PAYMENT_TXN_LOG")
public class TCkPaymentTxnLog extends COAbstractEntity<TCkPaymentTxnLog> {

	private static final long serialVersionUID = -5408860364696866557L;
	private String ptxlId;
	private TCkPaymentTxn TCkPaymentTxn;
	private String ptxlTxnState;
	private String ptxlRemarks;
	private Date ptxlDtCreate;
	private String ptxlUidCreate;
	private Date ptxlDtLupd;
	private String ptxlUidLupd;

	public TCkPaymentTxnLog() {
	}

	public TCkPaymentTxnLog(String ptxlId) {
		this.ptxlId = ptxlId;
	}

	public TCkPaymentTxnLog(String ptxlId, TCkPaymentTxn TCkPaymentTxn, String ptxlTxnState, String ptxlRemarks,
			Date ptxlDtCreate, String ptxlUidCreate, Date ptxlDtLupd, String ptxlUidLupd) {
		this.ptxlId = ptxlId;
		this.TCkPaymentTxn = TCkPaymentTxn;
		this.ptxlTxnState = ptxlTxnState;
		this.ptxlRemarks = ptxlRemarks;
		this.ptxlDtCreate = ptxlDtCreate;
		this.ptxlUidCreate = ptxlUidCreate;
		this.ptxlDtLupd = ptxlDtLupd;
		this.ptxlUidLupd = ptxlUidLupd;
	}

	@Id

	@Column(name = "PTXL_ID", unique = true, nullable = false, length = 35)
	public String getPtxlId() {
		return this.ptxlId;
	}

	public void setPtxlId(String ptxlId) {
		this.ptxlId = ptxlId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PTXL_TXN_REF", nullable = false)
	public TCkPaymentTxn getTCkPaymentTxn() {
		return this.TCkPaymentTxn;
	}

	public void setTCkPaymentTxn(TCkPaymentTxn TCkPaymentTxn) {
		this.TCkPaymentTxn = TCkPaymentTxn;
	}

	@Column(name = "PTXL_TXN_STATE", length = 35)
	public String getPtxlTxnState() {
		return this.ptxlTxnState;
	}

	public void setPtxlTxnState(String ptxlTxnState) {
		this.ptxlTxnState = ptxlTxnState;
	}

	@Column(name = "PTXL_REMARKS", length = 16777215)
	public String getPtxlRemarks() {
		return this.ptxlRemarks;
	}

	public void setPtxlRemarks(String ptxlRemarks) {
		this.ptxlRemarks = ptxlRemarks;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PTXL_DT_CREATE", length = 19)
	public Date getPtxlDtCreate() {
		return this.ptxlDtCreate;
	}

	public void setPtxlDtCreate(Date ptxlDtCreate) {
		this.ptxlDtCreate = ptxlDtCreate;
	}

	@Column(name = "PTXL_UID_CREATE", length = 35)
	public String getPtxlUidCreate() {
		return this.ptxlUidCreate;
	}

	public void setPtxlUidCreate(String ptxlUidCreate) {
		this.ptxlUidCreate = ptxlUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PTXL_DT_LUPD", length = 19)
	public Date getPtxlDtLupd() {
		return this.ptxlDtLupd;
	}

	public void setPtxlDtLupd(Date ptxlDtLupd) {
		this.ptxlDtLupd = ptxlDtLupd;
	}

	@Column(name = "PTXL_UID_LUPD", length = 35)
	public String getPtxlUidLupd() {
		return this.ptxlUidLupd;
	}

	public void setPtxlUidLupd(String ptxlUidLupd) {
		this.ptxlUidLupd = ptxlUidLupd;
	}

	@Override
	public int compareTo(TCkPaymentTxnLog o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
