
-- OP_ADMIN_WJ can view Value-Added Services

UPDATE `clickargo2`.`T_CORE_PERM_EX` SET `PERM_MENU_NAME` = 'Value-Added Services' WHERE (`PERM_ID` = 'PM078');

INSERT INTO `clickargo2`.`T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) 
VALUES ('CKT', 'OP_ADMIN_WJ', 'PM078', 'A', '2024-05-20 13:59:27', 'SYS');

