-- Component guides. Below no need to re-execute. --
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('1','CK','CLICDO','clicdo.doi.co.jobs.list','When a job is submitted, it is locked and its fields cannot be edited. If there are errors associated with the submitted job, it has to be cancelled before it is picked up for processing by the authorized party (aka Freight Forwarder)',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('2','CK','CLICDO','clicdo.doi.co.jobs.list.table','Each job record in the list corresponds to job corresponding to a Bill of Lading (BL) document. These jobs when submitted will be picked up by the Authorized Party (aka Freight Forwarders) stated in the job for DO claiming. Click on eye icon to view the BL in PDF and the cancel icon to cancel the job.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('3','CK','CLICDO','clicdo.doi.co.jobs.tabs.details','Update all the information to ensure correct information about the job is captured. Click Save to save the updated job or click Submit to submit the job to the Authorized Party.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('4','CK','CLICDO','clicdo.doi.co.jobs.tabs.authorisation','Document will be reviewed by shipping line. If there are concerns, the owner of the job will be contacted via email for clarifications. Only after the documents and payment are verified will your Authorized Party be able to download the invoice and start the DO claim process.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('5','CK','CLICDO','clicdo.doi.co.jobs.tabs.authorisation.table','Except Bill of Lading, the authorisation document is generated and digital stamped. Click on Download to view the document in PDF format.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('6','CK','CLICDO','clicdo.doi.co.jobs.tabs.audit','The audited even associated with the job is presented here. Filtering is supported to sniff out audit records by criteria(s).',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('7','CK','CLICDO','clicdo.doi.ff.bl.list','To view any of the Bill of Ladings, click on the DOWNLOAD button. To reject ony Bill of Ladings, click on the REJECT button.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('8','CK','CLICDO','clicdo.doi.ff.bl.list.table','Each job recordi n the list corresponds to a Bill of Lading (BL) document submitted by the Authorizer Party (aka Cargo Owners) for DO claiming. Click on eye icon to view the BL in PDF and then cancel icon to reject the BL.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('9','CK','CLICDO','clicdo.doi.ff.claim.jobs.list','To view any of your jobs without editing, click on the EYE button. To edit any draft jobs, click on the PENCIL button. To delete any draft jobs, click on the TRASH BIN button.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('10','CK','CLICDO','clicdo.doi.ff.claim.jobs.list.table','Active DO claim jobs that you are processing',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('11','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.details','Please update all the information to ensure correct information about the job is captured. Please notethat once the job has been confirmed, BLs cannot be edited or removed from the list.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('12','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.detaills.table','Click on the eye icon to view the BL document. Click on the trash bin to remove BL from the list.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('13','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.attachments','Documents associated with all the BL are captured in the list.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('14','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.attachments.table','Click on the Download icon to download the respective documents. Power of Authority, Letter of Assignment  and Container Loan Application documents are automatically generated by the system.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('15','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.task.details','Once the list of DOs are confirmed clicked on the Submit button to retrieve the DO documents from the shipping line.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('16','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.task.details.table.main','Click on the Eye icon to view the task details on the section below. Click the Pencil icon to edit the task and Trash Bin to remove the task.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('17','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.task.details.table.sub','Click on the Trash Bin to remove DO from the task that are in NEW status. Click on Eye icon to view the DO details.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('18','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.query','Ensure that there are no outstanding queries by the Shipping Line. Document can be manually and temporarily added when there is an outstanding query.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('19','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.query.table','Click on the Response icon to response to the query after you have made the necessary changes requested by the Shipping Line. Click on the Eye icon to view the query made by the Shipping Line and the response to the query.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('20','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.audit','The audited even associated with the job is presented here. Filtering is supported to sniff out audit records by criteria(s).',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('21','CK','CLICDO','clicdo.doi.sl.claim.jobs.list','To view any of your jobs without editing, click on the Eye button. To edit any draft jobs, click on the Pencil button. To delete any draf jobs, click on the Trash Bin button.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('22','CK','CLICDO','clicdo.doi.sl.claim.jobs.list.table','Click on the Document icon to perform document verification. Click on the Money icon to perform payment verification.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('23','CK','CLICDO','clicdo.doi.sl.claim.jobs.tab.docverify.details','The charges amount will be shown once the job is submitted and verified. The proforma invoices are also available for download when the job details and documents are verified. Once payment is made, DO claim tasks ca be started to claim the DO under the BLs.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('24','CK','CLICDO','clicdo.task-details.task-listing.table','Click on the EYE icon to view the task details on the section below. Click the PENCIL icon to edit the task and TRASH BIN icon to remove the task.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('25','CK','CLICDO','clicdo.task-details.doi-listing.table','Click on the TRASH BIN to remove DO from the task that are in NEW status. Click on EYE icon to view the DO details.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('26','CK','CLICDO','clicdo.task-details.footer.info','Once the list of DO are confirmed click on the Submit button to retrive the DO documents from the shipping line.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('27','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.details.new','The charges amount will be shown once the job is submitted and verified. The proforma invoices are also available for download when the job details and documents are verified. Once payment is made, DO claim tasks can be started to claim the DO under the BLs.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('28','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.detaills.table.new','Click on the eye icon to view the BL document. BL documents cannot be removed because the job is confirmed.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('29','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.details.submittted','Once payment is made, DO claim tasks can be started to claim the DO under the BLs.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('30','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.detaills.table.submitted','Click on the Eye icon to view the BL document. Click the Download icon to download the proforma invoice.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('31','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.details.paid','Once payment is verified, DO claim tasks can be started to claim the DO under the BLs.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('32','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.detaills.table.paid','Click on the eye icon to view the BL document. Click the Download icon to download the proforma invoice.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('33','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.details.verified','Tasks can be started to claim the DO(s) associated with the BL in the list.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('34','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.detaills.table.verified','Click on the eye icon to view the BL document. Click the download icon to download the proforma invoice.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('35','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.details.completed','Tasks can be started to claim the DO(s) associated with the BL in the list.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('36','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.detaills.table.completed','Click on the eye icon to view the BL document. Click the download icon to download the proforma invoice.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('37','CK','CLICDO','clicdo.payment.active.job.listing.table','Select at least one job and click the Pay icon for payment. Click the Magnifier icon to view list of DO.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('38','CK','CLICDO','clicdo.payment.history.listing.table','Click the Eye icon to view Payment Details.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('39','CK','CLICDO','clicdo.payment.details.table','For active payment, click the Arrow Submit icon to Pay. Click the Download icon to view the invoice.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('41','CK','CLICDO','clicdo.doi.sl.claim.jobs.tabs.query','Create a query to inform the responder on the changes or correct documents required on what has been claimed.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('42','CK','CLICDO','clicdo.doi.sl.claim.jobs.tabs.query.table','Click on the EYE icon to view the query made by the Shipping Line and the response to the query. Click on the TRASH BIN to delete the query.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('43','CK','CLICDO','clicdo.doi.sl.pay.verify.list','Once submitted task has been submitted, the DOs listed within the tasks cannot be updated or removed. The shipping line will proceed to review the letter of authorisation documents, the DO charges will only be shown when the documents have been verified. The DO document and Invoice will only be made available for download once payment has been made and verified by the shipping line.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('44','CK','CLICDO','clicdo.doi.sl.doc.verify.list','Once submitted task has been submitted, the DOs listed within the tasks cannot be updated or removed. The shipping line will proceed to review the letter of authorisation documents, the DO charges will only be shown when the documents have been verified. The DO document and Invoice will only be made available for download once payment has been made and verified by the shipping line.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('45','CK','CLICDO','clicdo.job-payment.job-listing.table','Once payment is made and verified, job status will be updated to PAYMENT VERIFIED"',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('50','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.details.confirmed','Once payment is made, DO claim tasks can be started to claim the DO under the BLs.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('51','CK','CLICDO','clicdo.doi.ff.claim.jobs.tabs.detaills.table.confirmed','Click on the Eye icon to view the BL document.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('60','CK','CLICDO','clicdo.doi.ff.extension.jobs.list','To view any of your jobs without editing, click on the EYE button. To edit any draft jobs, click on the PENCIL button. To delete any draft jobs, click on the TRASH BIN button.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('70','CK','CLICDO','clicdo.master.shipment.type.list','*To edit shipment type record click on the pencil icon, to deactivate/activate it click on the unlink icon and to view the details click on the eye icon.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('71','CK','CLICDO','clicdo.master.shipment.type.details','Enter the details into the fields below and click Save to save or update the record, click Inactivate to set the status of the record to inactive. To exit this page without saving, click on the Exit button.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('72','CK','CLICDO','clicdo.master.shipment.type.audit','The updates to the shipment type record are listed in the table below. You can filter the list to determine the changes.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('73','CK','CLICDO','clicdo.mydo.jobs.list','The list below shows the active DOs that you are having. Containers of active DO have yet been returned to the Depo. ',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('74','CK','CLICDO','clicdo.mydo.tabs.details','DO general details are presented in the various sections below.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('75','CK','CLICDO','clicdo.mydo.tabs.invoices','The invoices associated with the DO are presented in the table below. These invoices are official invoices that are issued by the shipping line.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('76','CK','CLICDO','clicdo.mydo.tabs.containers','The containers associated with the DO are presented in the table below.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('77','CK','CLICDO','clicdo.mydo.tabs.extensions','The Do extensions associated with the DO are presented in the table below.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('78','CK','CLICDO','clicdo.extension.jobs.list','The list below shows the DO extension jobs. Once the extension jobs are paid the DO are presented in your DO listing.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('79','CK','CLICDO','clicdo.extension.tabs.details','DO Extension details are presented in the various sections below. If you confirm the extension, you will be able to pay for the DO extension.',NULL,'A',NOW(),'SYS',NOW(),'SYS');

-- New component guide for ClicTruck. To be executed once go to production -- 
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('80','CKT','CLICTRUCK','clictruck.job.general.details','Trucking job details such as the reference numbers, dates and party details.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('81','CKT','CLICTRUCK','clictruck.job.trip.charges','Location details, trip charges (if applicable), and cargo and truck details. For trip charges, click on Open Price to change pricing. For predefined trip charges, click Rate Table icon.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('82','CKT','CLICTRUCK','clictruck.job.supporting.docs','Upload or download supporting documents of the trucking job.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('83','CKT','CLICTRUCK','clictruck.job.audit','The audited event associated with the job is presented here. Filtering is supported to sniff out audit records by criteria(s).',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('84','CKT','CLICTRUCK','clictruck.job.driver.truck','Driver and truck selection to assign the trucking job to. Selecting Others will assign Driver or Truck not in the predefined list.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('85','CKT','CLICTRUCK','clictruck.job.delivery.order','Delivery Order details such as DO Number and the DO document to be uploaded when Starting and Stopping (Delivered) a trucking job.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('86','CKT','CLICTRUCK','clictruck.job.tracking','Tracks the location of the truck if GPS is attached to the vehicle.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('87','CKT','CLICTRUCK','clictruck.job.invoice.details','Trip Charge Invoice and Re-imbursement to be uploaded or updated by the Trucking Operator for Cargo Owner to approve.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('88','CKT','CLICTRUCK','clictruck.job.remarks','Job related remarks such as Rejection or Approval.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('89','CKT','CLICTRUCK','clictruck.payment.details','Consolidated jobs invoices in one transaction.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('90','CKT','CLICTRUCK','clictruck.payment.audit','The audited event associated with the payment transaction is presented here. Filtering is supported to sniff out audit records by criteria(s).',NULL,'A',NOW(),'SYS',NOW(),'SYS');

INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('91','CKT','CLICTRUCK','clictruck.administration.truck.list','Manage truck details, update existing record or add new truck.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('92','CKT','CLICTRUCK','clictruck.administration.truck.details','Truck details such as Chasis, Dimension and Weight can be updated. Notification can be configured for maintenance and expiry dates of insurance, licenses, etc. based on date or distance.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('93','CKT','CLICTRUCK','clictruck.administration.truck.audit','The audited event associated with the truck is presented here. Filtering is supported to sniff out audit records by criteria(s).',NULL,'A',NOW(),'SYS',NOW(),'SYS');

INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('94','CKT','CLICTRUCK','clictruck.administration.driver.list','Manage drivers. Update existing record or add new driver.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('95','CKT','CLICTRUCK','clictruck.administration.driver.details','Driver details such as Driver\'s License and Photo, Contact Details and Driver Mobile App User Id and Password.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('96','CKT','CLICTRUCK','clictruck.administration.driver.audit','The audited event associated with the driver is presented here. Filtering is supported to sniff out audit records by criteria(s).',NULL,'A',NOW(),'SYS',NOW(),'SYS');

INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('97','CKT','CLICTRUCK','clictruck.administration.location.list','Manage locations details. Update existing record or add new location.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('98','CKT','CLICTRUCK','clictruck.administration.location.details','Location details such as type whether it is ADDRESS or REGION. Validty details for the location pair is saved as well as the coordinates to be used when Tracking for the truck.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('99','CKT','CLICTRUCK','clictruck.administration.location.audit','The audited event associated with the location is presented here. Filtering is supported to sniff out audit records by criteria(s).',NULL,'A',NOW(),'SYS',NOW(),'SYS');

INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('100','CKT','CLICTRUCK','clictruck.administration.ratetable.list','Manage rate tables. Update existing record or add new rate table.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('101','CKT','CLICTRUCK','clictruck.administration.ratetable.details','Rate table details such as Validity Details, Party Details and associated rates by location.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('102','CKT','CLICTRUCK','clictruck.administration.ratetable.comments','Rate table changes are submitted and subject for verification and approval. Remarks are listed here.',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('103','CKT','CLICTRUCK','clictruck.administration.ratetable.audit','The audited event associated with the rate table is presented here. Filtering is supported to sniff out audit records by criteria(s).',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('104','CKT','CLICTRUCK','clictruck.administration.ratetable.sp.list','Lists of rate table update request submitted by Trucking Operator.',NULL,'A',NOW(),'SYS',NOW(),'SYS');

INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('106','CKT','CLICTRUCK','clictruck.administration.truck.performance.list','Truck performance listing by job and the time it enters the destination 30 meters and 100 meters respectively.',NULL,'A',NOW(),'SYS',NOW(),'SYS');

INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('107','CKT','CLICTRUCK','clictruck.administration.chassis.list','Manage truck chasis details. Chassis options can be viewed in Manage Truck',NULL,'A',NOW(),'SYS',NOW(),'SYS');

INSERT INTO T_CK_COMPONENT_GUIDE(CMGU_ID, CMGU_APPS_CODE, CMGU_SERVICE_TYPE, CMGU_COMPONENT_ID, CMGU_GUIDE, CMGU_GUIDE_OTH, CMGU_STATUS, CMGU_DT_CREATE, CMGU_UID_CREATE, CMGU_DT_LUPD, CMGU_UID_LUPD)  VALUES('108','CKT','CLICTRUCK','clictruck.account.admin.users.list','Manage users. Update user details, Reset Password, Deactivate, and Activate user status.',NULL,'A',NOW(),'SYS',NOW(),'SYS');