-- 2023-08-28 New workflow for gli document verification
INSERT INTO `T_CK_MST_FORM_ACTION` (`FMACT_ID`, `FMACT_NAME`, `FMACT_DESC`, `FMACT_DESC_OTH`, `FMACT_STATUS`, `FMACT_DT_CREATE`, `FMACT_UID_CREATE`, `FMACT_DT_LUPD`, `FMACT_UID_LUPD`) VALUES ('ACKNOWLEDGE_BILL', 'Acknowledge Job Billing', 'Acknowledge Job Billing', 'Approve Job Billing', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');

INSERT INTO `T_CK_MST_JOB_STATE` (`JBST_ID`, `JBST_NAME`, `JBST_DESC`, `JBST_DESC_OTH`, `JBST_STATUS`, `JBST_DT_CREATE`, `JBST_UID_CREATE`, `JBST_DT_LUPD`, `JBST_UID_LUPD`) VALUES ('ACK_BILL', 'BILLING ACKNOWLEDGED', 'BILLING ACKNOWLEDGED', 'BILLING VERIFIED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

INSERT INTO `T_CK_MST_ENTITY_STATE` (`ENST_ID`, `ENST_NAME`, `ENST_DESC`, `ENST_DESC_OTH`, `ENST_STATUS`, `ENST_DT_CREATE`, `ENST_UID_CREATE`, `ENST_DT_LUPD`, `ENST_UID_LUPD`) VALUES ('ACK_BILL', 'BILLING ACKNOWLEDGED', 'BILLING ACKNOWLEDGED', 'BILLING APPROVED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

-- execute workflow.sql

-- execute navigation.sql

-- execute formcontrol.sql
ALTER TABLE `T_CK_RECORD_DATE` 
ADD COLUMN `RCD_DT_BILL_ACKNOWLEDGED` DATETIME NULL AFTER `RCD_UID_BILL_VERIFIED`,
ADD COLUMN `RCD_UID_BILL_ACKNOWLEDGED` VARCHAR(35) NULL AFTER `RCD_DT_BILL_ACKNOWLEDGED`;

UPDATE `T_CORE_SYSPARAM` SET `SYS_KEY` = 'CLICTRUCK_DAYS_FROM_DUEDT', `SYS_DESC` = 'NO. OF DAYS FROM INV DUE DATE TO AUTO SUSPEND THE ACCOUNT' WHERE (`SYS_KEY` = 'CT_ACCN_SUSPENDED_INTERVAL');

-- scripts above deployed in production on 08Sep23-- 

INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_DOC_VERIFY_ENABLE', 'N', 'Flag to enable or disable GLI document verification of billed jobs.', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

-- execute workflow.sql

-- execute formcontrol.sql


