-- CREDIT STATE (MASTER) ----------------------------------------------------------------------------
CREATE TABLE `T_CK_MST_CREDIT_STATE` (
  `CRST_ID` varchar(35) NOT NULL COMMENT 'CREDIT STATE ID - VERIFIED : APPROVED : REJECTED : SUSPENDED',
  `CRST_NAME` varchar(100) NOT NULL COMMENT 'CREDIT STATE NAME',
  `CRST_DESC` varchar(255) DEFAULT NULL COMMENT 'CREDIT STATE DESCRIPTION',
  `CRST_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'CREDIT STATE DESCRIPTION OTHER LANGUAGE',
  `CRST_STATUS` char(1) DEFAULT NULL COMMENT 'CREDIT STATE STATUS',
  `CRST_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CRST_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CRST_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CRST_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CRST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='CREDIT STATE TABLE';

INSERT INTO T_CK_MST_CREDIT_STATE (CRST_ID, CRST_NAME, CRST_DESC, CRST_DESC_OTH, CRST_STATUS, CRST_DT_CREATE, CRST_UID_CREATE, CRST_DT_LUPD, CRST_UID_LUPD) VALUES('DRAFT', 'DRAFT', 'DRAFT', 'DRAFT', 'A', '2023-05-30 00:00:00', 'SYS', '2023-05-30 00:00:00', 'SYS');
INSERT INTO T_CK_MST_CREDIT_STATE (CRST_ID, CRST_NAME, CRST_DESC, CRST_DESC_OTH, CRST_STATUS, CRST_DT_CREATE, CRST_UID_CREATE, CRST_DT_LUPD, CRST_UID_LUPD) VALUES('VERIFY', 'VERIFY', 'VERIFY', 'VERIFY', 'A', '2023-05-30 00:00:00', 'SYS', '2023-05-30 00:00:00', 'SYS');
INSERT INTO T_CK_MST_CREDIT_STATE (CRST_ID, CRST_NAME, CRST_DESC, CRST_DESC_OTH, CRST_STATUS, CRST_DT_CREATE, CRST_UID_CREATE, CRST_DT_LUPD, CRST_UID_LUPD) VALUES('APPROVED', 'APPROVED', 'APPROVED', 'APPROVED', 'A', '2023-05-30 00:00:00', 'SYS', '2023-05-30 00:00:00', 'SYS');
INSERT INTO T_CK_MST_CREDIT_STATE (CRST_ID, CRST_NAME, CRST_DESC, CRST_DESC_OTH, CRST_STATUS, CRST_DT_CREATE, CRST_UID_CREATE, CRST_DT_LUPD, CRST_UID_LUPD) VALUES('REJECTED', 'REJECTED', 'REJECTED', 'REJECTED', 'A', '2023-05-30 00:00:00', 'SYS', '2023-05-30 00:00:00', 'SYS');
INSERT INTO T_CK_MST_CREDIT_STATE (CRST_ID, CRST_NAME, CRST_DESC, CRST_DESC_OTH, CRST_STATUS, CRST_DT_CREATE, CRST_UID_CREATE, CRST_DT_LUPD, CRST_UID_LUPD) VALUES('SUSPENDED', 'SUSPENDED', 'SUSPENDED', 'SUSPENDED', 'A', '2023-05-30 00:00:00', 'SYS', '2023-05-30 00:00:00', 'SYS');
INSERT INTO T_CK_MST_CREDIT_STATE (CRST_ID, CRST_NAME, CRST_DESC, CRST_DESC_OTH, CRST_STATUS, CRST_DT_CREATE, CRST_UID_CREATE, CRST_DT_LUPD, CRST_UID_LUPD) VALUES('UNSUSPENDED', 'UNSUSPENDED', 'UNSUSPENDED', 'UNSUSPENDED', 'A', '2023-05-30 00:00:00', 'SYS', '2023-05-30 00:00:00', 'SYS');

-- CREDIT TABLE ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CREDIT` (
  `CR_ID` varchar(35) NOT NULL COMMENT 'RECORD ID - UUID',
  `CR_SERVCE_TYPE` varchar(35) DEFAULT NULL COMMENT 'CREDIT SERVICE TYPE - REFERENCES T_CK_MST_SERVICE_TYPE:SVCT_ID',
  `CR_COMPANY` varchar(35) DEFAULT NULL COMMENT 'CREDIT COMPANY ACCOUNT - REFERENCES T_CORE_ACCN:ACCN_ID',  
  `CR_STATE` varchar(35) DEFAULT NULL COMMENT 'CREDIT STATE - REFERENCES T_CK_MST_CREDIT_STATE:CRST_ID',  
  `CR_AMT` mediumint DEFAULT 0 COMMENT 'CREDIT AMOUNT',
  `CR_CCY` varchar(3) DEFAULT NULL COMMENT 'CURRENCY  - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `CR_DT_START` datetime DEFAULT NULL COMMENT 'CREDIT START DATE TIME',
  `CR_DT_END` datetime DEFAULT NULL COMMENT 'CREDIT END DATE TIME',
  `CR_USR_VERIFY` varchar(35) DEFAULT NULL COMMENT 'CREDIT VERIFIER',
  `CR_DT_VERIFY` datetime DEFAULT NULL COMMENT 'CREDIT VERIFIED DATE TIME',
  `CR_USR_APPROVE` varchar(35) DEFAULT NULL COMMENT 'CREDIT APPROVER',
  `CR_DT_APPROVE` datetime DEFAULT NULL COMMENT 'CREDIT APPROVED DATE TIME',
  `CR_REMARKS` mediumtext DEFAULT NULL COMMENT 'REMARKS FOR CREDIT APPROVAL',
  `CR_STATUS` char(1) DEFAULT NULL COMMENT 'CREDIT RECORD STATUS',
  `CR_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CR_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CR_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CR_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CR_ID`),
  CONSTRAINT `FK_CK_CREDIT_CK_MST_SERVICE_TYPE` FOREIGN KEY (`CR_SERVCE_TYPE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),
  CONSTRAINT `FK_CK_CREDIT_CORE_ACCN` FOREIGN KEY (`CR_COMPANY`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),  
  CONSTRAINT `FK_CK_CREDIT_CK_MST_CREDIT_STATE` FOREIGN KEY (`CR_STATE`) REFERENCES `T_CK_MST_CREDIT_STATE` (`CRST_ID`),  
  CONSTRAINT `FK_CK_CREDIT_MST_CURRENCY` FOREIGN KEY (`CR_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='CREDIT TABLE';

ALTER TABLE T_CK_CREDIT MODIFY COLUMN CR_AMT double(15,2) DEFAULT 0 NULL COMMENT 'CREDIT AMOUNT';
ALTER TABLE T_CK_CREDIT CHANGE CR_SERVCE_TYPE CR_SERVICE_TYPE varchar(35) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL COMMENT 'CREDIT SERVICE TYPE - REFERENCES T_CK_MST_SERVICE_TYPE:SVCT_ID';
ALTER TABLE T_CK_CREDIT ADD CR_USR_REJECT varchar(35) NULL COMMENT 'CREDIT REJECT';
ALTER TABLE T_CK_CREDIT CHANGE CR_USR_REJECT CR_USR_REJECT varchar(35) NULL COMMENT 'CREDIT REJECT' AFTER CR_DT_APPROVE;
ALTER TABLE T_CK_CREDIT ADD CR_DT_REJECT DATETIME NULL COMMENT 'CREDIT REJECT DATE TIME';
ALTER TABLE T_CK_CREDIT CHANGE CR_DT_REJECT CR_DT_REJECT DATETIME NULL COMMENT 'CREDIT REJECT DATE TIME' AFTER CR_USR_REJECT;
ALTER TABLE T_CK_CREDIT ADD CONSTRAINT FK_CK_CREDIT_VERIFY_CORE_USR FOREIGN KEY (CR_USR_VERIFY) REFERENCES T_CORE_USR(USR_UID);
ALTER TABLE T_CK_CREDIT ADD CONSTRAINT FK_CK_CREDIT_APPROVE_CORE_USR FOREIGN KEY (CR_USR_APPROVE) REFERENCES T_CORE_USR(USR_UID);
ALTER TABLE T_CK_CREDIT ADD CONSTRAINT FK_CK_CREDIT_REJECT_CORE_USR FOREIGN KEY (CR_USR_REJECT) REFERENCES T_CORE_USR(USR_UID);
ALTER TABLE T_CK_CREDIT ADD CR_TXN_CAP DOUBLE(15, 2) NULL COMMENT 'MONTHLY TRANSACTION CAP';
ALTER TABLE T_CK_CREDIT CHANGE CR_TXN_CAP CR_TXN_CAP DOUBLE(15, 2) NULL COMMENT 'MONTHLY TRANSACTION CAP' AFTER CR_AMT;

-- CREDIT SUMMARY TABLE ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CREDIT_SUMMARY` (
  `CRS_ID` varchar(35) NOT NULL COMMENT 'RECORD ID - UUID',
  `CRS_SERVCE_TYPE` varchar(35) DEFAULT NULL COMMENT 'CREDIT SUMMARY SERVICE TYPE - REFERENCES T_CK_MST_SERVICE_TYPE:SVCT_ID',
  `CRS_COMPANY` varchar(35) DEFAULT NULL COMMENT 'CREDIT SUMMARY COMPANY ACCOUNT - REFERENCES T_CORE_ACCN:ACCN_ID',  
  `CRS_AMT` mediumint DEFAULT 0 COMMENT 'CREDIT SUMMARY AMOUNT',
  `CRS_RESERVE` mediumint DEFAULT 0 COMMENT 'CREDIT SUMMARY RESERVE',
  `CRS_UTILIZED` mediumint DEFAULT 0 COMMENT 'CREDIT SUMMARY UTILIZED',
  `CRS_BALANCE` mediumint DEFAULT 0 COMMENT 'CREDIT SUMMARY BALANCE',
  `CRS_CCY` varchar(3) DEFAULT NULL COMMENT 'CURRENCY  - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `CRS_STATUS` char(1) DEFAULT NULL COMMENT 'CREDIT RECORD STATUS',
  `CRS_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CRS_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CRS_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CRS_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CRS_ID`),
  CONSTRAINT `FK_CK_CREDIT_SUMMARY_CK_MST_SERVICE_TYPE` FOREIGN KEY (`CRS_SERVCE_TYPE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),
  CONSTRAINT `FK_CK_CREDIT_SUMMARY_CORE_ACCN` FOREIGN KEY (`CRS_COMPANY`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),  
  CONSTRAINT `FK_CK_CREDIT_SUMMARY_MST_CURRENCY` FOREIGN KEY (`CRS_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='CREDIT SUMMARY TABLE';

ALTER TABLE T_CK_CREDIT_SUMMARY MODIFY COLUMN CRS_AMT double(15, 2) DEFAULT 0 NULL COMMENT 'CREDIT SUMMARY AMOUNT';
ALTER TABLE T_CK_CREDIT_SUMMARY MODIFY COLUMN CRS_RESERVE double(15, 2) DEFAULT 0 NULL COMMENT 'CREDIT SUMMARY RESERVE';
ALTER TABLE T_CK_CREDIT_SUMMARY MODIFY COLUMN CRS_UTILIZED double(15, 2) DEFAULT 0 NULL COMMENT 'CREDIT SUMMARY UTILIZED';
ALTER TABLE T_CK_CREDIT_SUMMARY MODIFY COLUMN CRS_BALANCE double(15, 2) DEFAULT 0 NULL COMMENT 'CREDIT SUMMARY BALANCE';
ALTER TABLE T_CK_CREDIT_SUMMARY CHANGE CRS_SERVCE_TYPE CRS_SERVICE_TYPE varchar(35) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL COMMENT 'CREDIT SUMMARY SERVICE TYPE - REFERENCES T_CK_MST_SERVICE_TYPE:SVCT_ID';
ALTER TABLE T_CK_CREDIT_SUMMARY ADD CRS_CREDIT varchar(35) NULL COMMENT 'CREDIT - REFERENCE T_CK_CREDIT:CR_ID';
ALTER TABLE T_CK_CREDIT_SUMMARY CHANGE CRS_CREDIT CRS_CREDIT varchar(35) NULL COMMENT 'CREDIT - REFERENCE T_CK_CREDIT:CR_ID' AFTER CRS_ID;
ALTER TABLE T_CK_CREDIT_SUMMARY ADD CONSTRAINT FK_CK_CREDIT_SUMMARY_CK_CREDIT FOREIGN KEY (CRS_CREDIT) REFERENCES T_CK_CREDIT(CR_ID);

ALTER TABLE T_CK_CREDIT_SUMMARY DROP FOREIGN KEY FK_CK_CREDIT_SUMMARY_CK_CREDIT;
ALTER TABLE T_CK_CREDIT_SUMMARY DROP COLUMN CRS_CREDIT;


-- JOURNAL TRANSACTION TYPE (MASTER) ----------------------------------------------------------------------------
CREATE TABLE `T_CK_MST_JOURNAL_TXN_TYPE` (
  `JTT_ID` varchar(35) NOT NULL COMMENT 'JOURNAL TXN TYPE ID - JOB_SUBMIT:JOB_WITHDRAW:JOB_REJECT:JOB_ACCEPT:JOB_APPROVE:PAYMENT_JOB:PAYMENT_TOPUP',
  `JTT_NAME` varchar(100) NOT NULL COMMENT 'SHIPMENT STATE NAME',
  `JTT_DESC` varchar(255) DEFAULT NULL COMMENT 'SHIPMENT STATE DESCRIPTION',
  `JTT_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'SHIPMENT STATE DESCRIPTION OTHER LANGUAGE',
  `JTT_STATUS` char(1) DEFAULT NULL COMMENT 'SHIPMENT STATE STATUS',
  `JTT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `JTT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `JTT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `JTT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`JTT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='JOURNAL TXN TYPE TABLE';

INSERT INTO T_CK_MST_JOURNAL_TXN_TYPE (JTT_ID, JTT_NAME, JTT_DESC, JTT_DESC_OTH, JTT_STATUS, JTT_DT_CREATE, JTT_UID_CREATE, JTT_DT_LUPD, JTT_UID_LUPD) VALUES('CR_ADJUSTMENT', 'CR_ADJUSTMENT', 'CR_ADJUSTMENT', 'CR_ADJUSTMENT', 'A', '2023-05-30 00:00:00', 'SYS', NULL, NULL);
INSERT INTO T_CK_MST_JOURNAL_TXN_TYPE (JTT_ID, JTT_NAME, JTT_DESC, JTT_DESC_OTH, JTT_STATUS, JTT_DT_CREATE, JTT_UID_CREATE, JTT_DT_LUPD, JTT_UID_LUPD) VALUES('JOB_APPROVE', 'JOB_APPROVE', 'JOB_APPROVE', 'JOB_APPROVE', 'A', '2023-05-30 00:00:00', 'SYS', '2023-05-30 00:00:00', 'SYS');
INSERT INTO T_CK_MST_JOURNAL_TXN_TYPE (JTT_ID, JTT_NAME, JTT_DESC, JTT_DESC_OTH, JTT_STATUS, JTT_DT_CREATE, JTT_UID_CREATE, JTT_DT_LUPD, JTT_UID_LUPD) VALUES('JOB_CANCEL', 'JOB_CANCEL', 'JOB_CANCEL', 'JOB_CANCEL', 'A', '2023-05-30 00:00:00', 'SYS', '2023-05-30 00:00:00', 'SYS');
INSERT INTO T_CK_MST_JOURNAL_TXN_TYPE (JTT_ID, JTT_NAME, JTT_DESC, JTT_DESC_OTH, JTT_STATUS, JTT_DT_CREATE, JTT_UID_CREATE, JTT_DT_LUPD, JTT_UID_LUPD) VALUES('JOB_PAYMENT', 'JOB_PAYMENT', 'JOB_PAYMENT', 'JOB_PAYMENT', 'A', '2023-05-30 00:00:00', 'SYS', '2023-05-30 00:00:00', 'SYS');
INSERT INTO T_CK_MST_JOURNAL_TXN_TYPE (JTT_ID, JTT_NAME, JTT_DESC, JTT_DESC_OTH, JTT_STATUS, JTT_DT_CREATE, JTT_UID_CREATE, JTT_DT_LUPD, JTT_UID_LUPD) VALUES('JOB_PAYMENT_APPROVE', 'JOB_PAYMENT_APPROVE', 'JOB_PAYMENT_APPROVE', 'JOB_PAYMENT_APPROVE', 'A', '2023-05-30 00:00:00', 'SYS', '2023-05-30 00:00:00', 'SYS');
INSERT INTO T_CK_MST_JOURNAL_TXN_TYPE (JTT_ID, JTT_NAME, JTT_DESC, JTT_DESC_OTH, JTT_STATUS, JTT_DT_CREATE, JTT_UID_CREATE, JTT_DT_LUPD, JTT_UID_LUPD) VALUES('JOB_REJECT', 'JOB_REJECT', 'JOB_REJECT', 'JOB_REJECT', 'A', '2023-05-30 00:00:00', 'SYS', '2023-05-30 00:00:00', 'SYS');
INSERT INTO T_CK_MST_JOURNAL_TXN_TYPE (JTT_ID, JTT_NAME, JTT_DESC, JTT_DESC_OTH, JTT_STATUS, JTT_DT_CREATE, JTT_UID_CREATE, JTT_DT_LUPD, JTT_UID_LUPD) VALUES('JOB_SUBMIT', 'JOB_SUBMIT', 'JOB_SUBMIT', 'JOB_SUBMIT', 'A', '2023-05-30 00:00:00', 'SYS', '2023-05-30 00:00:00', 'SYS');
INSERT INTO T_CK_MST_JOURNAL_TXN_TYPE (JTT_ID, JTT_NAME, JTT_DESC, JTT_DESC_OTH, JTT_STATUS, JTT_DT_CREATE, JTT_UID_CREATE, JTT_DT_LUPD, JTT_UID_LUPD) VALUES('JOB_SUBMIT_REIMBURSEMENT', 'JOB_SUBMIT_REIMBURSEMENT', 'JOB_SUBMIT_REIMBURSEMENT', 'JOB_SUBMIT_REIMBURSEMENT', 'A', '2023-05-30 00:00:00', 'SYS', '2023-05-30 00:00:00', 'SYS');
INSERT INTO T_CK_MST_JOURNAL_TXN_TYPE (JTT_ID, JTT_NAME, JTT_DESC, JTT_DESC_OTH, JTT_STATUS, JTT_DT_CREATE, JTT_UID_CREATE, JTT_DT_LUPD, JTT_UID_LUPD) VALUES('JOB_TRANSFERED', 'JOB_TRANSFERED', 'JOB_TRANSFERED', 'JOB_TRANSFERED', 'A', '2023-05-30 00:00:00', 'SYS', NULL, NULL);


-- CREDIT JOURNAL TABLE ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CREDIT_JOURNAL` (
  `CJN_ID` varchar(35) NOT NULL COMMENT 'RECORD ID - UUID',
  `CJN_SERVCE_TYPE` varchar(35) DEFAULT NULL COMMENT 'CREDIT JOURNAL SERVICE TYPE - REFERENCES T_CK_MST_SERVICE_TYPE:SVCT_ID',
  `CJN_COMPANY` varchar(35) DEFAULT NULL COMMENT 'CREDIT JOURNAL COMPANY ACCOUNT - REFERENCES T_CORE_ACCN:ACCN_ID',  
  `CJN_TXN_TYPE` varchar(35) DEFAULT NULL COMMENT 'CREDIT JOURNAL TRANSACITON TYPE - REFERNCES T_CK_MST_JOURNAL_TXN_TYPE:JTT_ID',
  `CJN_TXN_REF` varchar(255) DEFAULT NULL COMMENT 'CREDIT JOURNAL TRANSACITON REFERENCE - JOB ID OR PAYMENT ID',
  `CJN_RESERVE` mediumint DEFAULT 0 COMMENT 'CREDIT SUMMARY RESERVE',
  `CJN_UTILIZED` mediumint DEFAULT 0 COMMENT 'CREDIT SUMMARY UTILIZED',
  `CJN_CCY` varchar(3) DEFAULT NULL COMMENT 'CURRENCY  - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `CJN_STATUS` char(1) DEFAULT NULL COMMENT 'CREDIT RECORD STATUS',
  `CJN_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CJN_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CJN_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CJN_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CJN_ID`),
  CONSTRAINT `FK_CK_JOURNAL_CK_MST_SERVICE_TYPE` FOREIGN KEY (`CJN_SERVCE_TYPE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),
  CONSTRAINT `FK_CK_JOURNAL_CORE_ACCN` FOREIGN KEY (`CJN_COMPANY`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),  
  CONSTRAINT `FK_CK_JOURNAL_CK_MST_JOURNAL_TXN_TYPE` FOREIGN KEY (`CJN_TXN_TYPE`) REFERENCES `T_CK_MST_JOURNAL_TXN_TYPE` (`JTT_ID`),  
  CONSTRAINT `FK_CK_JOURNAL_MST_CURRENCY` FOREIGN KEY (`CJN_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='CREDIT JOURNAL TABLE';

ALTER TABLE T_CK_CREDIT_JOURNAL MODIFY COLUMN CJN_RESERVE double(15, 2) DEFAULT 0 NULL COMMENT 'CREDIT SUMMARY RESERVE';
ALTER TABLE T_CK_CREDIT_JOURNAL MODIFY COLUMN CJN_UTILIZED double(15, 2) DEFAULT 0 NULL COMMENT 'CREDIT SUMMARY UTILIZED';
ALTER TABLE T_CK_CREDIT_JOURNAL CHANGE CJN_SERVCE_TYPE CJN_SERVICE_TYPE varchar(35) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL COMMENT 'CREDIT JOURNAL SERVICE TYPE - REFERENCES T_CK_MST_SERVICE_TYPE:SVCT_ID';

-- T_CK_PAYMENT_TERMS TABLE ----------------------------------------------------------------------------
CREATE TABLE `T_CK_PAYMENT_TERMS` (
  `PT_ID` varchar(35) NOT NULL COMMENT 'RECORD ID - UUID',
  `PT_COMPANY` varchar(35) NOT NULL COMMENT 'CREDIT SUMMARY COMPANY ACCOUNT - REFERENCES T_CORE_ACCN:ACCN_ID',
  `PT_SERVICE_TYPE` varchar(35) DEFAULT NULL COMMENT 'CREDIT SUMMARY SERVICE TYPE - REFERENCES T_CK_MST_SERVICE_TYPE:SVCT_ID',
  `PT_PYMENT_TERMS` INT DEFAULT 0 COMMENT 'PAYMENT TERMS: 30 days, 60 days, 90 days',
  `PT_MONTHLY_CAP` INT DEFAULT 0 COMMENT 'CREDIT LIMIT CAP: 2, 3',
  `PT_STATUS` char(1) DEFAULT NULL COMMENT 'CREDIT RECORD STATUS',
  `PT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `PT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `PT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `PT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (PT_ID),
  CONSTRAINT `FK_CK_CREDIT_PAYMENT_TERMS_CK_MST_SERVICE_TYPE` FOREIGN KEY (`PT_SERVICE_TYPE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),
  CONSTRAINT `FK_CK_CREDIT_PAYMENT_TERMS_CORE_ACCN` FOREIGN KEY (`PT_COMPANY`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='CO PAYMENT TERMS';

-- T_CK_CREDIT_SUMMARY_MONTH TABLE ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CREDIT_SUMMARY_MONTH` (
  `CRSM_COMPANY` varchar(35) NOT NULL COMMENT 'CREDIT SUMMARY COMPANY ACCOUNT - REFERENCES T_CORE_ACCN:ACCN_ID',
  `CRSM_MONTH` varchar(35) NOT NULL COMMENT 'MONTHLY : 202305, 202306, 202306',
  `CRSM_SERVICE_TYPE` varchar(35) DEFAULT NULL COMMENT 'CREDIT SUMMARY SERVICE TYPE - REFERENCES T_CK_MST_SERVICE_TYPE:SVCT_ID',
  `CRSM_AMT` double(15,2) DEFAULT '0.00' COMMENT 'CREDIT SUMMARY AMOUNT',
  `CRSM_RESERVE` double(15,2) DEFAULT '0.00' COMMENT 'CREDIT SUMMARY RESERVE',
  `CRSM_UTILIZED` double(15,2) DEFAULT '0.00' COMMENT 'CREDIT SUMMARY UTILIZED',
  `CRSM_BALANCE` double(15,2) DEFAULT '0.00' COMMENT 'CREDIT SUMMARY BALANCE',
  `CRSM_CCY` varchar(3) DEFAULT NULL COMMENT 'CURRENCY  - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `CRSM_STATUS` char(1) DEFAULT NULL COMMENT 'CREDIT RECORD STATUS',
  `CRSM_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CRSM_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CRSM_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CRSM_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (CRSM_COMPANY, CRSM_MONTH),
  CONSTRAINT `FK_CK_CREDIT_SUMM_MONTH_CK_MST_SERVICE_TYPE` FOREIGN KEY (`CRSM_SERVICE_TYPE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),
  CONSTRAINT `FK_CK_CREDIT_SUMM_MONTH_CORE_ACCN` FOREIGN KEY (`CRSM_COMPANY`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_CREDIT_SUMM_MONTH_MST_CURRENCY` FOREIGN KEY (`CRSM_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='CREDIT SUMMARY MONTHLY TABLE';

-- TRIGGER TGR_AI_SUM_CREDIT ----------------------------------------------------------------------------
CREATE TRIGGER `TGR_AU_SUM_CREDIT` AFTER UPDATE ON `T_CK_CREDIT_JOURNAL` FOR EACH ROW UPDATE T_CK_CREDIT_SUMMARY,
(
	SELECT SUM(CJN_RESERVE) vReserved, SUM(CJN_UTILIZED) vUtillized
	FROM T_CK_CREDIT_JOURNAL
	WHERE CJN_COMPANY = OLD.CJN_COMPANY AND CJN_SERVICE_TYPE = OLD.CJN_SERVICE_TYPE AND CJN_CCY = OLD.CJN_CCY
) src
	SET 
	CRS_BALANCE =CRS_AMT - (vReserved + vUtillized), CRS_RESERVE = vReserved,	CRS_UTILIZED = vUtillized		
	WHERE CRS_SERVICE_TYPE = NEW.CJN_SERVICE_TYPE AND CRS_COMPANY = NEW.CJN_COMPANY AND CRS_CCY = NEW.CJN_CCY;

-- TGR_AU_SUM_CREDIT ----------------------------------------------------------------------------
CREATE TRIGGER `TGR_AI_SUM_CREDIT` AFTER INSERT ON `T_CK_CREDIT_JOURNAL` FOR EACH ROW UPDATE T_CK_CREDIT_SUMMARY,
(
	SELECT SUM(CJN_RESERVE) vReserved, SUM(CJN_UTILIZED) vUtilized
	FROM T_CK_CREDIT_JOURNAL
	WHERE CJN_COMPANY = NEW.CJN_COMPANY AND CJN_SERVICE_TYPE = NEW.CJN_SERVICE_TYPE AND CJN_CCY = NEW.CJN_CCY
) src
	SET CRS_BALANCE = CRS_AMT - (vReserved + vUtilized), CRS_RESERVE = vReserved,	CRS_UTILIZED = vUtilized	
	WHERE CRS_SERVICE_TYPE = NEW.CJN_SERVICE_TYPE AND CRS_COMPANY = NEW.CJN_COMPANY AND CRS_CCY = NEW.CJN_CCY;

-- TGR_AI_SUM_CREDIT_MONHTLY ----------------------------------------------------------------------------
CREATE TRIGGER `TGR_AI_SUM_CREDIT_MONHTLY` AFTER INSERT ON `T_CK_CREDIT_JOURNAL` FOR EACH ROW 
replace into T_CK_CREDIT_SUMMARY_MONTH(CRSM_COMPANY, CRSM_MONTH, CRSM_SERVICE_TYPE, CRSM_AMT, CRSM_RESERVE, CRSM_UTILIZED, CRSM_BALANCE
, CRSM_CCY, CRSM_STATUS, CRSM_DT_CREATE, CRSM_UID_CREATE)
select CJN_COMPANY, date_format(CJN_DT_CREATE, '%Y%m'), CJN_SERVICE_TYPE, 0, sum(CJN_RESERVE), sum(CJN_UTILIZED), 0
, CJN_CCY, 'A', sysdate(), 'sys'
FROM T_CK_CREDIT_JOURNAL
where CJN_SERVICE_TYPE = NEW.CJN_SERVICE_TYPE AND CJN_COMPANY = NEW.CJN_COMPANY AND CJN_CCY = NEW.CJN_CCY
	and date_format(now(), '%Y%m') =date_format(CJN_DT_CREATE, '%Y%m')
	and CJN_COMPANY in (select ACCN_ID from T_CORE_ACCN)
group by CJN_SERVICE_TYPE, CJN_COMPANY, CJN_CCY, date_format(CJN_DT_CREATE, '%Y%m');

-- TGR_AU_SUM_CREDIT_MONHTLY ----------------------------------------------------------------------------
CREATE TRIGGER `TGR_AU_SUM_CREDIT_MONHTLY` AFTER UPDATE ON `T_CK_CREDIT_JOURNAL` FOR EACH ROW 
replace into T_CK_CREDIT_SUMMARY_MONTH(CRSM_COMPANY, CRSM_MONTH, CRSM_SERVICE_TYPE, CRSM_AMT, CRSM_RESERVE, CRSM_UTILIZED, CRSM_BALANCE
, CRSM_CCY, CRSM_STATUS, CRSM_DT_CREATE, CRSM_UID_CREATE)
select CJN_COMPANY, date_format(CJN_DT_CREATE, '%Y%m'), CJN_SERVICE_TYPE, 0, sum(CJN_RESERVE), sum(CJN_UTILIZED), 0
, CJN_CCY, 'A', sysdate(), 'sys'
FROM T_CK_CREDIT_JOURNAL
where CJN_SERVICE_TYPE = NEW.CJN_SERVICE_TYPE AND CJN_COMPANY = NEW.CJN_COMPANY AND CJN_CCY = NEW.CJN_CCY
	and date_format(now(), '%Y%m') =date_format(CJN_DT_CREATE, '%Y%m')
	and CJN_COMPANY in (select ACCN_ID from T_CORE_ACCN)
group by CJN_SERVICE_TYPE, CJN_COMPANY, CJN_CCY, date_format(CJN_DT_CREATE, '%Y%m');

-- to execute in production on deployment start --
ALTER TABLE T_CK_CREDIT MODIFY COLUMN CR_AMT double(15,2) DEFAULT 0 NULL COMMENT 'CREDIT AMOUNT';
ALTER TABLE T_CK_CREDIT ADD CR_USR_REJECT varchar(35) NULL COMMENT 'CREDIT REJECT';
ALTER TABLE T_CK_CREDIT CHANGE CR_USR_REJECT CR_USR_REJECT varchar(35) NULL COMMENT 'CREDIT REJECT' AFTER CR_DT_APPROVE;
ALTER TABLE T_CK_CREDIT ADD CR_DT_REJECT DATETIME NULL COMMENT 'CREDIT REJECT DATE TIME';
ALTER TABLE T_CK_CREDIT CHANGE CR_DT_REJECT CR_DT_REJECT DATETIME NULL COMMENT 'CREDIT REJECT DATE TIME' AFTER CR_USR_REJECT;
ALTER TABLE T_CK_CREDIT ADD CONSTRAINT FK_CK_CREDIT_REJECT_CORE_USR FOREIGN KEY (CR_USR_REJECT) REFERENCES T_CORE_USR(USR_UID);
ALTER TABLE T_CK_CREDIT ADD CR_TXN_CAP DOUBLE(15, 2) NULL COMMENT 'MONTHLY TRANSACTION CAP';
ALTER TABLE T_CK_CREDIT CHANGE CR_TXN_CAP CR_TXN_CAP DOUBLE(15, 2) NULL COMMENT 'MONTHLY TRANSACTION CAP' AFTER CR_AMT;


ALTER TABLE T_CK_CREDIT_SUMMARY MODIFY COLUMN CRS_AMT double(15, 2) DEFAULT 0 NULL COMMENT 'CREDIT SUMMARY AMOUNT';
ALTER TABLE T_CK_CREDIT_SUMMARY MODIFY COLUMN CRS_RESERVE double(15, 2) DEFAULT 0 NULL COMMENT 'CREDIT SUMMARY RESERVE';
ALTER TABLE T_CK_CREDIT_SUMMARY MODIFY COLUMN CRS_UTILIZED double(15, 2) DEFAULT 0 NULL COMMENT 'CREDIT SUMMARY UTILIZED';
ALTER TABLE T_CK_CREDIT_SUMMARY MODIFY COLUMN CRS_BALANCE double(15, 2) DEFAULT 0 NULL COMMENT 'CREDIT SUMMARY BALANCE';
ALTER TABLE T_CK_CREDIT_SUMMARY ADD CRS_CREDIT varchar(35) NULL COMMENT 'CREDIT - REFERENCE T_CK_CREDIT:CR_ID';
ALTER TABLE T_CK_CREDIT_SUMMARY CHANGE CRS_CREDIT CRS_CREDIT varchar(35) NULL COMMENT 'CREDIT - REFERENCE T_CK_CREDIT:CR_ID' AFTER CRS_ID;
ALTER TABLE T_CK_CREDIT_SUMMARY ADD CONSTRAINT FK_CK_CREDIT_SUMMARY_CK_CREDIT FOREIGN KEY (CRS_CREDIT) REFERENCES T_CK_CREDIT(CR_ID);

ALTER TABLE T_CK_CREDIT_SUMMARY DROP FOREIGN KEY FK_CK_CREDIT_SUMMARY_CK_CREDIT;
ALTER TABLE T_CK_CREDIT_SUMMARY DROP COLUMN CRS_CREDIT;

INSERT INTO T_CK_MST_JOURNAL_TXN_TYPE (JTT_ID, JTT_NAME, JTT_DESC, JTT_DESC_OTH, JTT_STATUS, JTT_DT_CREATE, JTT_UID_CREATE, JTT_DT_LUPD, JTT_UID_LUPD) VALUES('CR_ADJUSTMENT', 'CR_ADJUSTMENT', 'CR_ADJUSTMENT', 'CR_ADJUSTMENT', 'A', '2023-05-30 00:00:00', 'SYS', NULL, NULL);

ALTER TABLE T_CK_CREDIT_JOURNAL MODIFY COLUMN CJN_RESERVE double(15, 2) DEFAULT 0 NULL COMMENT 'CREDIT SUMMARY RESERVE';
ALTER TABLE T_CK_CREDIT_JOURNAL MODIFY COLUMN CJN_UTILIZED double(15, 2) DEFAULT 0 NULL COMMENT 'CREDIT SUMMARY UTILIZED';
-- to execute in production on deployment  end --