SET SQL_SAFE_UPDATES = 0;
SET FOREIGN_KEY_CHECKS=0;
DELETE FROM T_CORE_ROLE where ROLE_APPSCODE='CKT';
SET SQL_SAFE_UPDATES = 1;
SET FOREIGN_KEY_CHECKS=1;

INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','ADMIN','A','ACCOUNT ADMIN',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','OFFICER','A','OFFICER',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','FF_FINANCE','A','FINANCE',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','OP_ADMIN','A','OPERATIONS ADMIN',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','SP_OP_ADMIN','A','OPERATIONS ADMIN',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','SP_L1','A','LEVEL 1 SUPPORT',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','SP_COM','A','COMMERCIAL',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','SP_BZ_HD','A','BUSINESS HEAD',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','SP_FIN_HD','A','FINANCE HEAD',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','SP_FIN_ADMIN','A','FINANCE ADMIN',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','SYS_SUPER_ADMIN','A','SYSTEM SUPER ADMIN',NOW(),'SYS',NOW(),'SYS');

SELECT * FROM T_CORE_ROLE WHERE ROLE_APPSCODE='CKT';

-- temporary old roles -- 
-- INSERT INTO `clickargo2`.`T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`, `ROLE_STATUS`, `ROLE_DESC`, `ROLE_DT_CREATE`, `ROLE_UID_CREATE`, `ROLE_DT_LUPD`, `ROLE_UID_LUPD`) VALUES ('CKT', 'ADMIN', 'A', 'ACCOUNT ADMINISTRATOR', '2022-11-15 09:06:28', 'SYS', '2022-11-15 09:06:28', 'SYS');
-- INSERT INTO `clickargo2`.`T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`, `ROLE_STATUS`, `ROLE_DESC`, `ROLE_DT_CREATE`, `ROLE_UID_CREATE`, `ROLE_DT_LUPD`, `ROLE_UID_LUPD`) VALUES ('CKT', 'FF_FINANCE', 'A', 'FINANCE OFFICER', '2022-11-15 09:09:14', 'SYS', '2022-11-15 09:09:14', 'SYS');
-- INSERT INTO `clickargo2`.`T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`, `ROLE_STATUS`, `ROLE_DESC`, `ROLE_DT_CREATE`, `ROLE_UID_CREATE`, `ROLE_DT_LUPD`, `ROLE_UID_LUPD`) VALUES ('CKT', 'FINANCE_ADMIN', 'A', 'FINANCE ADMIN', '2023-07-12 17:57:44', 'SYS', '2023-07-12 17:57:44', 'SYS');
-- INSERT INTO `clickargo2`.`T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`, `ROLE_STATUS`, `ROLE_DESC`, `ROLE_DT_CREATE`, `ROLE_UID_CREATE`, `ROLE_DT_LUPD`, `ROLE_UID_LUPD`) VALUES ('CKT', 'FINANCE_APPROVER', 'A', 'FINANCE APPROVER', '2023-06-10 10:42:43', 'SYS', '2023-06-10 10:42:43', 'SYS');
-- INSERT INTO `clickargo2`.`T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`, `ROLE_STATUS`, `ROLE_DESC`, `ROLE_DT_CREATE`, `ROLE_UID_CREATE`, `ROLE_DT_LUPD`, `ROLE_UID_LUPD`) VALUES ('CKT', 'FINANCE_VERIFIER', 'A', 'FINANCE VERIFIER', '2023-06-10 10:42:43', 'SYS', '2023-06-10 10:42:43', 'SYS');
-- INSERT INTO `clickargo2`.`T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`, `ROLE_STATUS`, `ROLE_DESC`, `ROLE_DT_CREATE`, `ROLE_UID_CREATE`, `ROLE_DT_LUPD`, `ROLE_UID_LUPD`) VALUES ('CKT', 'OFFICER', 'A', 'OPERATIONS OFFICER', '2018-12-01 00:00:00', 'SYS', '2018-12-01 00:00:00', 'SYS');
-- INSERT INTO `clickargo2`.`T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`, `ROLE_STATUS`, `ROLE_DESC`, `ROLE_DT_CREATE`, `ROLE_UID_CREATE`, `ROLE_DT_LUPD`, `ROLE_UID_LUPD`) VALUES ('CKT', 'OP_ADMIN', 'A', 'OPERATIONS ADMINISTRATOR', '2022-11-15 09:09:14', 'SYS', '2022-11-15 09:09:14', 'SYS');
-- INSERT INTO `clickargo2`.`T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`, `ROLE_STATUS`, `ROLE_DESC`, `ROLE_DT_CREATE`, `ROLE_UID_CREATE`, `ROLE_DT_LUPD`, `ROLE_UID_LUPD`) VALUES ('CKT', 'OP_CS', 'A', 'CUSTOMER SERVICE', '2023-09-07 14:19:27', 'SYS', '2023-09-07 14:19:27', 'SYS');
-- INSERT INTO `clickargo2`.`T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`, `ROLE_STATUS`, `ROLE_DESC`, `ROLE_DT_CREATE`, `ROLE_UID_CREATE`, `ROLE_DT_LUPD`, `ROLE_UID_LUPD`) VALUES ('CKT', 'SP_OP_ADMIN', 'A', 'SERVICE PROVIDER OPERATIONS ADMIN', '2023-08-07 18:08:06', 'SYS', '2023-08-07 18:08:06', 'SYS');

-- TO UPDATE THE USER ROLES 
UPDATE `clickargo2`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'SP_FIN_ADMIN' WHERE (`UROL_UID` = 'GLI_U00VER') and (`UROL_APPSCODE` = 'CKT') and (`UROL_ROLEID` = 'FINANCE_VERIFIER') and (`UROL_ADMIN_OPT` = 'N');
UPDATE `clickargo2`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'SP_FIN_ADMIN' WHERE (`UROL_UID` = 'GLI_U001') and (`UROL_APPSCODE` = 'CKT') and (`UROL_ROLEID` = 'FINANCE_VERIFIER') and (`UROL_ADMIN_OPT` = 'A');
UPDATE `clickargo2`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'SP_FIN_HD' WHERE (`UROL_UID` = 'GLI_U00APP') and (`UROL_APPSCODE` = 'CKT') and (`UROL_ROLEID` = 'FINANCE_APPROVER') and (`UROL_ADMIN_OPT` = 'N');
UPDATE `clickargo2`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'SP_COM' WHERE (`UROL_UID` = 'GLI_CS') and (`UROL_APPSCODE` = 'CKT') and (`UROL_ROLEID` = 'SP_OP_ADMIN') and (`UROL_ADMIN_OPT` = 'A');
UPDATE `clickargo2`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'SP_BZ_HD' WHERE (`UROL_UID` = 'GLI_BZ_HD') and (`UROL_APPSCODE` = 'CKT') and (`UROL_ROLEID` = 'FINANCE_VERIFIER') and (`UROL_ADMIN_OPT` = 'A');
UPDATE `clickargo2`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'SP_FIN_HD' WHERE (`UROL_UID` = 'GLI_FINANCE_HD') and (`UROL_APPSCODE` = 'CKT') and (`UROL_ROLEID` = 'FINANCE_APPROVER') and (`UROL_ADMIN_OPT` = 'A');
UPDATE `clickargo2`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'SP_L1' WHERE (`UROL_UID` = 'GLI_L1') and (`UROL_APPSCODE` = 'CKT') and (`UROL_ROLEID` = 'SP_OP_ADMIN') and (`UROL_ADMIN_OPT` = 'A');
UPDATE `clickargo2`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'SP_OP_ADMIN' WHERE (`UROL_UID` = 'GLI000') and (`UROL_APPSCODE` = 'CKT') and (`UROL_ROLEID` = 'OP_ADMIN') and (`UROL_ADMIN_OPT` = 'A');
UPDATE `clickargo2`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'SP_FIN_ADMIN' WHERE (`UROL_UID` = 'GLI_DOC_VER') and (`UROL_APPSCODE` = 'CKT') and (`UROL_ROLEID` = 'FINANCE_VERIFIER') and (`UROL_ADMIN_OPT` = 'A');

select * from T_CORE_USR_ROLE where UROL_APPSCODE='CKT' AND UROL_UID LIKE 'GLI%';

-- for local new roles only -- 
-- UPDATE `clickargo2`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'SP_FIN_HD' WHERE (`UROL_UID` = 'GLI_BZ_HD') and (`UROL_APPSCODE` = 'CKT') and (`UROL_ROLEID` = 'FINANCE_APPROVER') and (`UROL_ADMIN_OPT` = 'A');
-- UPDATE `clickargo2`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'SP_L1' WHERE (`UROL_UID` = 'GLI_CS') and (`UROL_APPSCODE` = 'CKT') and (`UROL_ROLEID` = 'FINANCE_APPROVER') and (`UROL_ADMIN_OPT` = 'A');
-- UPDATE `clickargo2`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'SP_FIN_ADMIN' WHERE (`UROL_UID` = 'GLI_DOC_VER') and (`UROL_APPSCODE` = 'CKT') and (`UROL_ROLEID` = 'FINANCE_VERIFIER') and (`UROL_ADMIN_OPT` = 'A');
-- UPDATE `clickargo2`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'SP_FIN_HD' WHERE (`UROL_UID` = 'GLI_L1') and (`UROL_APPSCODE` = 'CKT') and (`UROL_ROLEID` = 'FINANCE_APPROVER') and (`UROL_ADMIN_OPT` = 'A');
-- UPDATE `clickargo2`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'SP_FIN_HD' WHERE (`UROL_UID` = 'GLI_U00APP') and (`UROL_APPSCODE` = 'CKT') and (`UROL_ROLEID` = 'FINANCE_APPROVER') and (`UROL_ADMIN_OPT` = 'N');
-- UPDATE `clickargo2`.`T_CORE_USR_ROLE` SET `UROL_ROLEID` = 'SP_FIN_ADMIN' WHERE (`UROL_UID` = 'GLI_U00VER') and (`UROL_APPSCODE` = 'CKT') and (`UROL_ROLEID` = 'FINANCE_VERIFIER') and (`UROL_ADMIN_OPT` = 'N');

select * from T_CORE_ROLE;
