CREATE TABLE `T_CK_MST_ESTAMP_METHOD` (
  `ESM_ID` varchar(35) NOT NULL COMMENT 'MASTER METHOD',
  `ESM_NAME` varchar(100) DEFAULT NULL COMMENT 'METHOD NAME',
  `ESM_DESCRIPTION` varchar(255) DEFAULT NULL COMMENT 'METHOD DESCRIPTION',
  `ESM_STATUS` char(1) DEFAULT NULL COMMENT 'METHOD STATUS: A: ACTIVE, I: INACTIVE',
  `ESM_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `ESM_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `ESM_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATE DATE',
  `ESM_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`ESM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

INSERT INTO T_CK_MST_ESTAMP_METHOD (ESM_ID, ESM_NAME, ESM_DESCRIPTION, ESM_STATUS, ESM_DT_CREATE, ESM_UID_CREATE, ESM_DT_LUPD, ESM_UID_LUPD) VALUES('AUTH TOKEN', 'AUTHORIZATION TOKEN', 'AUTHORIZATION TOKEN', 'A', '2023-09-13 00:00:00', 'SYS', '2023-09-13 00:00:00', 'SYS');
INSERT INTO T_CK_MST_ESTAMP_METHOD (ESM_ID, ESM_NAME, ESM_DESCRIPTION, ESM_STATUS, ESM_DT_CREATE, ESM_UID_CREATE, ESM_DT_LUPD, ESM_UID_LUPD) VALUES('STAMP DOCUMENT', 'STAMP DOCUMENT', 'STAMP DOCUMENT', 'A', '2023-09-13 00:00:00', 'SYS', '2023-09-13 00:00:00', 'SYS');
INSERT INTO T_CK_MST_ESTAMP_METHOD (ESM_ID, ESM_NAME, ESM_DESCRIPTION, ESM_STATUS, ESM_DT_CREATE, ESM_UID_CREATE, ESM_DT_LUPD, ESM_UID_LUPD) VALUES('STAMP DOCUMENT DETAIL', 'STAMP DOCUMENT DETAIL', 'STAMP DOCUMENT DETAIL', 'A', '2023-09-13 00:00:00', 'SYS', '2023-09-13 00:00:00', 'SYS');
INSERT INTO T_CK_MST_ESTAMP_METHOD (ESM_ID, ESM_NAME, ESM_DESCRIPTION, ESM_STATUS, ESM_DT_CREATE, ESM_UID_CREATE, ESM_DT_LUPD, ESM_UID_LUPD) VALUES('STAMP DOWNLOAD', 'STAMP DOWNLOAD', 'STAMP DOWNLOAD', 'A', '2023-09-13 00:00:00', 'SYS', '2023-09-13 00:00:00', 'SYS');


CREATE TABLE `T_CK_ESTAMP_TXN` (
  `EST_ID` varchar(35) NOT NULL COMMENT 'ESTAMP TRANSACTION ID',
  `EST_METHOD` varchar(35) DEFAULT NULL COMMENT 'METHOD NAME, REFERENCE : T_CK_MST_ESTAMP_METHOD:EMS_ID',
  `EST_REQ` mediumtext COMMENT 'REQUEST BODY OF TXN - JSON OBJECT OF REQUEST BODY',
  `EST_DT_REQ` datetime DEFAULT NULL COMMENT 'DATE TIME OF REQUEST',
  `EST_RESP` mediumtext COMMENT 'RESPONSE BNODY OF TXN - JSON OBJECT PF RESPONSE BODY',
  `EST_DT_RESP` datetime DEFAULT NULL COMMENT 'DATE TIME OF RESPONSE',
  `EST_RESP_CODE` smallint DEFAULT NULL COMMENT 'HTTP RESPONSE CODE',
  `EST_STATUS` char(1) DEFAULT NULL COMMENT 'RECORD STATUS - A : I',
  `EST_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `EST_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `EST_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `EST_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`EST_ID`),
  KEY `FK_CK_ESTAMP_TXN_CK_MST_ESTAMP_METHOD` (`EST_METHOD`),
  CONSTRAINT `FK_CK_ESTAMP_TXN_CK_MST_ESTAMP_METHOD` FOREIGN KEY (`EST_METHOD`) REFERENCES `T_CK_MST_ESTAMP_METHOD` (`ESM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

INSERT INTO T_CORE_SYSPARAM (SYS_KEY, SYS_VAL, SYS_DESC, SYS_DT_CREATE, SYS_UID_CREATE, SYS_DT_LUPD, SYS_UID_LUPD, SYS_STATUS) VALUES('STAMP_GATEWAY_CONFIG', '{"url":"https://sandbox-api.mekari.com/v2/esign/v1","clientId":"pxubTWSZnX8dMMvJ","clientSecret":"FaN3YPa6rd8Mq3ueOeCFQPLQ9iKMaxkD","contentType":"application/json","code":"RO65OQqZt5aWXbxmg4K1Gxc7Cd0F7bkh"}', 'STAMP GATEWAY CONFIG', '2018-12-01 00:00:00', 'SYS', '2018-12-01 00:00:00', 'SYS', 'A');
INSERT INTO T_CORE_SYSPARAM (SYS_KEY, SYS_VAL, SYS_DESC, SYS_DT_CREATE, SYS_UID_CREATE, SYS_DT_LUPD, SYS_UID_LUPD, SYS_STATUS) VALUES('STAMP_GATEWAY_REFRESH_TOKEN', 'n8aNC7jJxjGDHWOtsFPitqcqXrG3qk1u', 'STAMP GATEWAY REFRESH TOKEN', '2018-12-01 00:00:00', 'SYS', '2018-12-01 00:00:00', 'SYS', 'A');

CREATE TABLE `T_CK_ESTAMP_DOC` (
  `ESD_ID` varchar(35) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT 'ESTAMP DOC ID - UUID',
  `ESD_SVC` varchar(35) NOT NULL COMMENT 'APPLICATION: CLICDO, CLICTRUCK, CLICGATEPASS, CLICDECLARE',
  `ESD_INV_ID` varchar(35) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT 'INVOICE ID',
  `ESD_INV_TYPE` varchar(100) DEFAULT NULL COMMENT 'INVOICE TYPE: DEBIT NOTE, PLATFORM FEE',
  `ESD_STAMP_STATUS` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'STAMPING STATUS FROM MEKARI: NONE, IN PROGRESS, SUCCESS, FINISH, PENDING, FAILED',
  `ESD_DOC_ID` varchar(100) DEFAULT NULL COMMENT 'DOCUMENT ID FROM MEKARI',
  `ESD_FILENAME` varchar(255) DEFAULT NULL COMMENT 'FILENAME FROM MEKARI',
  `ESD_DOC` varchar(1024) DEFAULT NULL COMMENT 'DOCUMENT INVOICE',
  `ESD_DOC_URL` varchar(1024) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'DOCUMENT URL FROM  MEKARI',
  `ESD_STATUS` char(1) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'STAMPING STATUS',
  `ESD_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `ESD_UID_CREATE` varchar(35) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `ESD_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `ESD_UID_LUPD` varchar(35) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`ESD_ID`),
  KEY `FK_CK_ESTAMP_DOC_CK_MST_SERVICE_TYPE` (`ESD_SVC`),
  CONSTRAINT `FK_CK_ESTAMP_DOC_CK_MST_SERVICE_TYPE` FOREIGN KEY (`ESD_SVC`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- 2024-01-25 TO BE EXECUTED IN PROD ONCE DEPLOYED
INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('STAMP_GATEWAY_AUTH_DTLS', '{\"accessToken\": null ,\"refreshToken\": null, \"expiresIn\": null, \"lastRunTime\": null}', 'STAMP GATEWAY AUTHORIZATION DETAILS TO BE USED EVERY API CALL', '2018-12-01 00:00:00', 'SYS', '2024-01-24 16:23:31', 'SYS', 'A');
INSERT INTO `T_CK_MST_ESTAMP_METHOD` (`ESM_ID`, `ESM_NAME`, `ESM_DESCRIPTION`, `ESM_STATUS`, `ESM_DT_CREATE`, `ESM_UID_CREATE`, `ESM_DT_LUPD`, `ESM_UID_LUPD`) VALUES ('REFRESH TOKEN', 'REFRESH TOKEN', 'REFRESH TOKEN', 'A', '2023-09-13 00:00:00', 'SYS', '2023-09-13 00:00:00', 'SYS');
