drop trigger TGR_AU_SUM_CREDIT;
drop trigger TGR_AI_SUM_CREDIT;
drop trigger TGR_AD_SUM_CREDIT;
drop trigger TGR_AI_SUM_CREDIT_MONHTLY;
drop trigger TGR_AU_SUM_CREDIT_MONHTLY;

-- TRIGGER TGR_AU_SUM_CREDIT ----------------------------------------------------------------------------
CREATE TRIGGER `TGR_AU_SUM_CREDIT` AFTER UPDATE ON `T_CK_CREDIT_JOURNAL` FOR EACH ROW UPDATE T_CK_CREDIT_SUMMARY,
(
	SELECT SUM(CJN_RESERVE) vReserved, SUM(CJN_UTILIZED) vUtillized
	FROM T_CK_CREDIT_JOURNAL
	WHERE CJN_COMPANY = OLD.CJN_COMPANY AND CJN_SERVICE_TYPE = OLD.CJN_SERVICE_TYPE AND CJN_CCY = OLD.CJN_CCY
) src
	SET 
	CRS_BALANCE =CRS_AMT - (vReserved + vUtillized), CRS_RESERVE = vReserved,	CRS_UTILIZED = vUtillized		
	WHERE CRS_SERVICE_TYPE = NEW.CJN_SERVICE_TYPE AND CRS_COMPANY = NEW.CJN_COMPANY AND CRS_CCY = NEW.CJN_CCY;

-- TGR_AI_SUM_CREDIT ----------------------------------------------------------------------------
CREATE TRIGGER `TGR_AI_SUM_CREDIT` AFTER INSERT ON `T_CK_CREDIT_JOURNAL` FOR EACH ROW UPDATE T_CK_CREDIT_SUMMARY,
(
	SELECT SUM(CJN_RESERVE) vReserved, SUM(CJN_UTILIZED) vUtilized
	FROM T_CK_CREDIT_JOURNAL
	WHERE CJN_COMPANY = NEW.CJN_COMPANY AND CJN_SERVICE_TYPE = NEW.CJN_SERVICE_TYPE AND CJN_CCY = NEW.CJN_CCY
) src
	SET CRS_BALANCE = CRS_AMT - (vReserved + vUtilized), CRS_RESERVE = vReserved,	CRS_UTILIZED = vUtilized	
	WHERE CRS_SERVICE_TYPE = NEW.CJN_SERVICE_TYPE AND CRS_COMPANY = NEW.CJN_COMPANY AND CRS_CCY = NEW.CJN_CCY;

CREATE TRIGGER `TGR_AD_SUM_CREDIT` AFTER DELETE ON `T_CK_CREDIT_JOURNAL` FOR EACH ROW UPDATE clickargo2.T_CK_CREDIT_SUMMARY,
(
	SELECT SUM(CJN_RESERVE) vReserved, SUM(CJN_UTILIZED) vUtillized
	FROM clickargo2.T_CK_CREDIT_JOURNAL
	WHERE CJN_COMPANY = OLD.CJN_COMPANY AND CJN_SERVICE_TYPE = OLD.CJN_SERVICE_TYPE AND CJN_CCY = OLD.CJN_CCY
) src
	SET 
	CRS_BALANCE =CRS_AMT - (vReserved + vUtillized), CRS_RESERVE = vReserved,	CRS_UTILIZED = vUtillized		
	WHERE CRS_SERVICE_TYPE = OLD.CJN_SERVICE_TYPE  and CRS_COMPANY = OLD.CJN_COMPANY AND CRS_CCY = OLD.CJN_CCY;


CREATE TRIGGER `TGR_AI_SUM_CREDIT_MONHTLY` AFTER INSERT ON `T_CK_CREDIT_JOURNAL` FOR EACH ROW replace into T_CK_CREDIT_SUMMARY_MONTH(CRSM_COMPANY, CRSM_MONTH, CRSM_SERVICE_TYPE, CRSM_AMT, CRSM_RESERVE, CRSM_UTILIZED, CRSM_BALANCE
, CRSM_CCY, CRSM_STATUS, CRSM_DT_CREATE, CRSM_UID_CREATE)
select CJN_COMPANY, date_format(CJN_DT_CREATE, '%Y%m'), CJN_SERVICE_TYPE, 0, sum(CJN_RESERVE), sum(CJN_UTILIZED), 0
, CJN_CCY, 'A', sysdate(), 'sys'
FROM T_CK_CREDIT_JOURNAL
where CJN_SERVICE_TYPE = NEW.CJN_SERVICE_TYPE AND CJN_COMPANY = NEW.CJN_COMPANY AND CJN_CCY = NEW.CJN_CCY
	and date_format(now(), '%Y%m') =date_format(CJN_DT_CREATE, '%Y%m')
	and CJN_COMPANY in (select ACCN_ID from T_CORE_ACCN)
group by CJN_SERVICE_TYPE, CJN_COMPANY, CJN_CCY, date_format(CJN_DT_CREATE, '%Y%m');

CREATE TRIGGER `TGR_AU_SUM_CREDIT_MONHTLY` AFTER UPDATE ON `T_CK_CREDIT_JOURNAL` FOR EACH ROW replace into T_CK_CREDIT_SUMMARY_MONTH(CRSM_COMPANY, CRSM_MONTH, CRSM_SERVICE_TYPE, CRSM_AMT, CRSM_RESERVE, CRSM_UTILIZED, CRSM_BALANCE
, CRSM_CCY, CRSM_STATUS, CRSM_DT_CREATE, CRSM_UID_CREATE)
select CJN_COMPANY, date_format(CJN_DT_CREATE, '%Y%m'), CJN_SERVICE_TYPE, 0, sum(CJN_RESERVE), sum(CJN_UTILIZED), 0
, CJN_CCY, 'A', sysdate(), 'sys'
FROM T_CK_CREDIT_JOURNAL
where CJN_SERVICE_TYPE = NEW.CJN_SERVICE_TYPE AND CJN_COMPANY = NEW.CJN_COMPANY AND CJN_CCY = NEW.CJN_CCY
	and date_format(now(), '%Y%m') =date_format(CJN_DT_CREATE, '%Y%m')
	and CJN_COMPANY in (select ACCN_ID from T_CORE_ACCN)
group by CJN_SERVICE_TYPE, CJN_COMPANY, CJN_CCY, date_format(CJN_DT_CREATE, '%Y%m');

