INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','SP_OP_ADMIN','A','SERVICE PROVIDER OPERATIONS ADMIN',NOW(),'SYS',NOW(),'SYS');

INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('GLI_U001','CKT','SP_OP_ADMIN','N','A',NOW(),'SYS', NOW(),'SYS','N');

-- execute navigation.sql

/** Added CT_ACCN_SUSPENDED_INTERVAL for scheduler */
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CT_ACCN_SUSPENDED_INTERVAL', '3', 'Interval Days for Account Suspension', '2022-11-30 00:00:00', 'SYS', '2022-11-30 00:00:00', 'SYS', 'A');

/** T_CK_SUSPENSION_LOG */
CREATE TABLE `T_CK_SUSPENSION_LOG` (
  `SL_ID` varchar(35) NOT NULL COMMENT 'SUSPENSIONID - UUD',
  `SL_EVENT` varchar(35) NOT NULL COMMENT 'SUSPENSION EVENT - SUSPEND|UNSUSPEND',
  `SL_ACCNID` varchar(35) DEFAULT NULL COMMENT 'ACCN THAT IS SUSPENDED OR UNSUSPENDED',
  `SL_REMARKS` varchar(2048) DEFAULT NULL COMMENT 'SUSPENSION/UNSUSPENSION COMMENTS',
  `SL_DETAILS` mediumtext DEFAULT NULL COMMENT 'SUSPENSION DETAILS - JSON LIST OF INVOICES WITH NUMBER:DUE DATE:AMOUNT DETAILS',
  `SL_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `SL_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER - SYS FOR SCHEDULER AUTOMATED SUSPENSION',
  PRIMARY KEY (`SL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

/** Added PAID, CANCELLED in T_CK_CT_MST_TO_INVOICE_STATE */
INSERT INTO `T_CK_CT_MST_TO_INVOICE_STATE` (`INST_ID`, `INST_NAME`, `INST_DESC`, `INST_DESC_OTH`, `INST_STATUS`, `INST_DT_CREATE`, `INST_UID_CREATE`, `INST_DT_LUPD`, `INST_UID_LUPD`) VALUES ('PAID', 'PAID', 'PAID', 'PAID', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
INSERT INTO `T_CK_CT_MST_TO_INVOICE_STATE` (`INST_ID`, `INST_NAME`, `INST_DESC`, `INST_DESC_OTH`, `INST_STATUS`, `INST_DT_CREATE`, `INST_UID_CREATE`, `INST_DT_LUPD`, `INST_UID_LUPD`) VALUES ('CANCELLED', 'CANCELLED', 'CANCELLED', 'CANCELLED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

/** Added CANCELLED in T_CK_CT_MST_DEBIT_NOTE_STATE */
INSERT INTO `T_CK_CT_MST_DEBIT_NOTE_STATE` (`DNST_ID`, `DNST_NAME`, `DNST_DESC`, `DNST_DESC_OTH`, `DNST_STATUS`, `DNST_DT_CREATE`, `DNST_UID_CREATE`, `DNST_DT_LUPD`, `DNST_UID_LUPD`) VALUES ('CANCELLED', 'CANCELLED', 'CANCELLED', 'CANCELLED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

/** For the action bit mask for multi-select */
CREATE TABLE `T_CK_SVC_ACTION_MASK` (
  `SAM_ID` varchar(35) NOT NULL COMMENT 'WORK FLOW ID - UUID',
  `SAM_APPS_CODE` varchar(35) NOT NULL COMMENT 'APPS CODES - REFERENCES T_CORE_APPS:APPS_CODE',
  `SAM_ACCN_TYPE` varchar(35) NOT NULL COMMENT 'ACCOUNT TYPE - REFERENCES T_MST_ACCN_TYPE',
  `SAM_ROLE` varchar(35) NOT NULL COMMENT 'ROLE - REFERENCES T_CORE_ROLE:ROLE_APPSCODE,ROLE_ID',
  `SAM_SCV_TYPE` varchar(35) NOT NULL COMMENT 'SERVICE TYPE - REFERENCES T_CK_MST_SERVICE_TYPE:SVCT_ID',
  `SAM_STATE` varchar(35) NOT NULL COMMENT 'JOB STATE - REFERENCES T_CK_MST_JOB_STATE:JBST_ID',
  `SAM_MASK` BIT(12) NOT NULL COMMENT '24 bit STATE MASK OF THE ACTIONS',
  `SAM_STATUS` char(1) NOT NULL,
  `SAM_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATE DATE',
  `SAM_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATE USER',
  `SAM_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATE DATE',
  `SAM_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATE USER',
  PRIMARY KEY (`SAM_ID`),
  CONSTRAINT `FK_CK_SVC_ACTION_MASK_ACCN_TYPE` FOREIGN KEY (`SAM_ACCN_TYPE`) REFERENCES `T_MST_ACCN_TYPE` (`ATYP_ID`),
  CONSTRAINT `FK_CK_SVC_ACTION_MASK_CK_MST_JOB_STATE` FOREIGN KEY (`SAM_STATE`) REFERENCES `T_CK_MST_JOB_STATE` (`JBST_ID`),
  CONSTRAINT `FK_CK_SVC_ACTION_MASK_CK_MST_SERVICE_TYPE` FOREIGN KEY (`SAM_SCV_TYPE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),
  CONSTRAINT `FK_CK_SVC_ACTION_MASK_CORE_APPS` FOREIGN KEY (`SAM_APPS_CODE`) REFERENCES `T_CORE_APPS` (`APPS_CODE`),
  CONSTRAINT `FK_CK_SVC_ACTION_MASK_CORE_ROLE` FOREIGN KEY (`SAM_APPS_CODE`, `SAM_ROLE`) REFERENCES `T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='SERVICE ACTION BITMASK';


INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('1','CKT','ACC_TYPE_CO','OFFICER','CLICTRUCK','NEW',B'0000000001','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('2','CKT','ACC_TYPE_CO','OFFICER','CLICTRUCK','SUB',B'0000000010','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('3','CKT','ACC_TYPE_TO','OFFICER','CLICTRUCK','SUB',B'0000001100','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('4','CKT','ACC_TYPE_TO','OFFICER','CLICTRUCK','REJ',B'0000000000','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('5','CKT','ACC_TYPE_TO','OFFICER','CLICTRUCK','ACP',B'0000010000','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('6','CKT','ACC_TYPE_TO','OFFICER','CLICTRUCK','ASG',B'0000100000','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('7','CKT','ACC_TYPE_TO','OFFICER','CLICTRUCK','ONGOING',B'0001000000','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('8','CKT','ACC_TYPE_TO','FF_FINANCE','CLICTRUCK','DLV',B'0010000000','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('9','CKT','ACC_TYPE_CO','FF_FINANCE','CLICTRUCK','BILLED',B'0100000000','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('10','CKT','ACC_TYPE_CO','FF_FINANCE','CLICTRUCK','VER_BILL',B'1000000000','A',NOW(),'SYS', NOW(),'SYS');



UPDATE `T_CK_MST_SERVICE_TYPE` SET `SVCT_NAME` = 'ClicDeclare', `SVCT_DESC` = 'ClicDeclare', `SVCT_DESC_OTH` = 'ClicDeclare' WHERE (`SVCT_ID` = 'CLICDEC');
UPDATE `T_CK_MST_SERVICE_TYPE` SET `SVCT_NAME` = 'ClicDepo', `SVCT_DESC` = 'ClicDepo', `SVCT_DESC_OTH` = 'ClicDepo', `SVCT_STATUS` = 'I' WHERE (`SVCT_ID` = 'CLICDEPO');
UPDATE `T_CK_MST_SERVICE_TYPE` SET `SVCT_NAME` = 'ClicDO', `SVCT_DESC` = 'ClicDO', `SVCT_DESC_OTH` = 'ClicDO' WHERE (`SVCT_ID` = 'CLICDO');
UPDATE `T_CK_MST_SERVICE_TYPE` SET `SVCT_NAME` = 'ClicGatepass', `SVCT_DESC` = 'ClicGatepass', `SVCT_DESC_OTH` = 'ClicGatepass' WHERE (`SVCT_ID` = 'CLICGP');
UPDATE `T_CK_MST_SERVICE_TYPE` SET `SVCT_NAME` = 'ClicTDS', `SVCT_DESC` = 'ClicTDS', `SVCT_DESC_OTH` = 'ClicTDS', `SVCT_STATUS` = 'I' WHERE (`SVCT_ID` = 'CLICTDS');
UPDATE `T_CK_MST_SERVICE_TYPE` SET `SVCT_NAME` = 'ClicTruck', `SVCT_DESC` = 'ClicTruck', `SVCT_DESC_OTH` = 'ClicTruck' WHERE (`SVCT_ID` = 'CLICTRUCK');

/** For development purpose only */
UPDATE `T_CORE_NOTIFICATION_DEVICE` SET `NDEV_CONFIG` = '{\"PORT\":\"587\",\"PASSWORD\":\"wwcdcrywtgwvglsq\",\"HOST\":\"smtp.gmail.com\",\"USERNAME\":\"camelone.vcc@gmail.com\",\"SSL\":\"true\", \"TLS_REQ\":\"true\", \"TLS\":\"true\"}' WHERE (`NDEV_ID` = 'MP_DEV_EMAIL') and (`NDEV_APPSCODE` = 'CONE');
UPDATE `T_CORE_NOTIFICATION_DEVICE` SET `NDEV_APPSCODE` = 'CKT' WHERE (`NDEV_ID` = 'MP_DEV_EMAIL') and (`NDEV_APPSCODE` = 'CONE');

INSERT INTO `T_CORE_NOTIFICATION_TEMPLATE`(`NTPL_ID`,`NTPL_APPSCODE`,`NTPL_CHANNEL_TYPE`,`NTPL_CONTENT_TYPE`,`NTPL_SUBJECT`,`NTPL_TEMPALTE`,`NTPL_SEQ`,`NTPL_DESC`,`NTPL_STATUS`,`NTPL_UID_CREATE`,`NTPL_DT_CREATE`,`NTPL_UID_LUPD`,`NTPL_DT_LUPD`)  VALUES('CKT_NTL_0001','CKT','CHN_TYPE_EMAIL','CNT_TYPE_HTML','Job Accepted','<html> <style> html, body{font-family: "Roboto", sans-serif;} #container {width: 800px;border: 1px solid gray;padding: 10px 20px;} .innerContainer {padding: 0px 0px;} #footerContainer {background-color: #f2f3f4;color: darkslategray;padding: 5px 15px;margin-top: 15px;} .button {width: 300px;height: 50px;background-color:steelblue;color: white;margin:50px 0px;justify-content: center;align-items: center;display: flex;} </style> <body> <div id=container> <div id=titleContainer class=innerContainer> <img width=100 height=62 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> <div id=bodyContainer class=innerContainer> <h1>Job has been accepted!</h1> <p>Job(s) :jobNumber has been accepted</p> <p>For a complete list of the job(s), see your <a href=:jobDetailLink>job details</a></p> <a href=:jobDetailLink><div class=button>Click Here</div></a> </div> <div id=footerContainer class=innerContainer> <p><a style=color:inherit href=:privacyStatementLink>Privacy Statement</a></p> <p>:sp_details</p> <img width=50 height=31 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> </div> </body> </html>','1','Notification to CO Operations when job is Accepted','A','SYS',NOW(),'SYS',NOW());
INSERT INTO `T_CORE_NOTIFICATION_TEMPLATE`(`NTPL_ID`,`NTPL_APPSCODE`,`NTPL_CHANNEL_TYPE`,`NTPL_CONTENT_TYPE`,`NTPL_SUBJECT`,`NTPL_TEMPALTE`,`NTPL_SEQ`,`NTPL_DESC`,`NTPL_STATUS`,`NTPL_UID_CREATE`,`NTPL_DT_CREATE`,`NTPL_UID_LUPD`,`NTPL_DT_LUPD`)  VALUES('CKT_NTL_0002','CKT','CHN_TYPE_EMAIL','CNT_TYPE_HTML','Job Rejected','<html> <style> html, body{font-family: "Roboto", sans-serif;} #container {width: 800px;border: 1px solid gray;padding: 10px 20px;} .innerContainer {padding: 0px 0px;} #footerContainer {background-color: #f2f3f4;color: darkslategray;padding: 5px 15px;margin-top: 15px;} .button {width: 300px;height: 50px;background-color:steelblue;color: white;margin:50px 0px;justify-content: center;align-items: center;display: flex;} </style> <body> <div id=container> <div id=titleContainer class=innerContainer> <img width=100 height=62 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> <div id=bodyContainer class=innerContainer> <h1>Job has been rejected!</h1> <p>Job(s) :jobNumber has been rejected</p> <p>For a complete list of the job(s), see your <a href=:jobDetailLink>job details</a></p> <a href=:jobDetailLink><div class=button>Click Here</div></a> </div> <div id=footerContainer class=innerContainer> <p><a style=color:inherit href=:privacyStatementLink>Privacy Statement</a></p> <p>:sp_details</p> <img width=50 height=31 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> </div> </body> </html>','2','Notification to CO Operations when job is Rejected','A','SYS',NOW(),'SYS',NOW());
INSERT INTO `T_CORE_NOTIFICATION_TEMPLATE`(`NTPL_ID`,`NTPL_APPSCODE`,`NTPL_CHANNEL_TYPE`,`NTPL_CONTENT_TYPE`,`NTPL_SUBJECT`,`NTPL_TEMPALTE`,`NTPL_SEQ`,`NTPL_DESC`,`NTPL_STATUS`,`NTPL_UID_CREATE`,`NTPL_DT_CREATE`,`NTPL_UID_LUPD`,`NTPL_DT_LUPD`)  VALUES('CKT_NTL_0003','CKT','CHN_TYPE_EMAIL','CNT_TYPE_HTML','Job Delivered','<html> <style> html, body{font-family: "Roboto", sans-serif;} #container {width: 800px;border: 1px solid gray;padding: 10px 20px;} .innerContainer {padding: 0px 0px;} #footerContainer {background-color: #f2f3f4;color: darkslategray;padding: 5px 15px;margin-top: 15px;} .button {width: 300px;height: 50px;background-color:steelblue;color: white;margin:50px 0px;justify-content: center;align-items: center;display: flex;} </style> <body> <div id=container> <div id=titleContainer class=innerContainer> <img width=100 height=62 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> <div id=bodyContainer class=innerContainer> <h1>Job has been delivered!</h1> <p>Job(s) :jobNumber has been delivered</p> <p>For a complete list of the job(s), see your <a href=:jobDetailLink>job details</a></p> <a href=:jobDetailLink><div class=button>Click Here</div></a> </div> <div id=footerContainer class=innerContainer> <p><a style=color:inherit href=:privacyStatementLink>Privacy Statement</a></p> <p>:sp_details</p> <img width=50 height=31 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> </div> </body> </html>','3','Notification to CO Operations when job is Delivered','A','SYS',NOW(),'SYS',NOW());
INSERT INTO `T_CORE_NOTIFICATION_TEMPLATE`(`NTPL_ID`,`NTPL_APPSCODE`,`NTPL_CHANNEL_TYPE`,`NTPL_CONTENT_TYPE`,`NTPL_SUBJECT`,`NTPL_TEMPALTE`,`NTPL_SEQ`,`NTPL_DESC`,`NTPL_STATUS`,`NTPL_UID_CREATE`,`NTPL_DT_CREATE`,`NTPL_UID_LUPD`,`NTPL_DT_LUPD`)  VALUES('CKT_NTL_0004','CKT','CHN_TYPE_EMAIL','CNT_TYPE_HTML','Invoice Submitted','<html> <style> html, body{font-family: "Roboto", sans-serif;} #container {width: 800px;border: 1px solid gray;padding: 10px 20px;} .innerContainer {padding: 0px 0px;} #footerContainer {background-color: #f2f3f4;color: darkslategray;padding: 5px 15px;margin-top: 15px;} .button {width: 300px;height: 50px;background-color:steelblue;color: white;margin:50px 0px;justify-content: center;align-items: center;display: flex;} </style> <body> <div id=container> <div id=titleContainer class=innerContainer> <img width=100 height=62 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> <div id=bodyContainer class=innerContainer> <h1>Job Invoice has been submitted to you!</h1> <p>Job invoice(s) :invoiceNumber has been submitted to you for verification and approval.</p> <p>For a complete list of the job(s), see your <a href=:jobDetailLink>job details.</a></p> <a href=:jobDetailLink><div class=button>Click Here</div></a> </div> <div id=footerContainer class=innerContainer> <p><a style=color:inherit href=:privacyStatementLink>Privacy Statement</a></p> <p>:sp_details</p> <img width=50 height=31 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> </div> </body> </html>','4','Notification to CO Operations when TO bill the job.','A','SYS',NOW(),'SYS',NOW());
INSERT INTO `T_CORE_NOTIFICATION_TEMPLATE`(`NTPL_ID`,`NTPL_APPSCODE`,`NTPL_CHANNEL_TYPE`,`NTPL_CONTENT_TYPE`,`NTPL_SUBJECT`,`NTPL_TEMPALTE`,`NTPL_SEQ`,`NTPL_DESC`,`NTPL_STATUS`,`NTPL_UID_CREATE`,`NTPL_DT_CREATE`,`NTPL_UID_LUPD`,`NTPL_DT_LUPD`)  VALUES('CKT_NTL_0005','CKT','CHN_TYPE_EMAIL','CNT_TYPE_HTML','Invoice Verified','<html> <style> html, body{font-family: "Roboto", sans-serif;} #container {width: 800px;border: 1px solid gray;padding: 10px 20px;} .innerContainer {padding: 0px 0px;} #footerContainer {background-color: #f2f3f4;color: darkslategray;padding: 5px 15px;margin-top: 15px;} .button {width: 300px;height: 50px;background-color:steelblue;color: white;margin:50px 0px;justify-content: center;align-items: center;display: flex;} </style> <body> <div id=container> <div id=titleContainer class=innerContainer> <img width=100 height=62 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> <div id=bodyContainer class=innerContainer> <h1>Job Invoice has been verified!</h1> <p>Job invoice(s) :invoiceNumber has been verified</p> <p>For a complete list of the job(s), see your <a href=:jobDetailLink>job details</a></p> <a href=:jobDetailLink><div class=button>Click Here</div></a> </div> <div id=footerContainer class=innerContainer> <p><a style=color:inherit href=:privacyStatementLink>Privacy Statement</a></p> <p>:sp_details</p> <img width=50 height=31 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> </div> </body> </html>','5','Notification to CO Finance when the Billed Job is verified by Cargo Owner','A','SYS',NOW(),'SYS',NOW());
INSERT INTO `T_CORE_NOTIFICATION_TEMPLATE`(`NTPL_ID`,`NTPL_APPSCODE`,`NTPL_CHANNEL_TYPE`,`NTPL_CONTENT_TYPE`,`NTPL_SUBJECT`,`NTPL_TEMPALTE`,`NTPL_SEQ`,`NTPL_DESC`,`NTPL_STATUS`,`NTPL_UID_CREATE`,`NTPL_DT_CREATE`,`NTPL_UID_LUPD`,`NTPL_DT_LUPD`)  VALUES('CKT_NTL_0006','CKT','CHN_TYPE_EMAIL','CNT_TYPE_HTML','Job Submitted','<html> <style> html, body{font-family: "Roboto", sans-serif;} #container {width: 800px;border: 1px solid gray;padding: 10px 20px;} .innerContainer {padding: 0px 0px;} #footerContainer {background-color: #f2f3f4;color: darkslategray;padding: 5px 15px;margin-top: 15px;} .button {width: 300px;height: 50px;background-color:steelblue;color: white;margin:50px 0px;justify-content: center;align-items: center;display: flex;} </style> <body> <div id=container> <div id=titleContainer class=innerContainer> <img width=100 height=62 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> <div id=bodyContainer class=innerContainer> <h1>Job has been submitted to you!</h1> <p>Job(s) :jobNumber has been submitted to you</p> <p>For a complete list of the job(s), see your <a href=:jobDetailLink>job details</a></p> <a href=:jobDetailLink><div class=button>Click Here</div></a> </div> <div id=footerContainer class=innerContainer> <p><a style=color:inherit href=:privacyStatementLink>Privacy Statement</a></p> <p>:sp_details</p> <img width=50 height=31 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> </div> </body> </html>','6','Notification to TO when job is submitted.','A','SYS',NOW(),'SYS',NOW());
INSERT INTO `T_CORE_NOTIFICATION_TEMPLATE`(`NTPL_ID`,`NTPL_APPSCODE`,`NTPL_CHANNEL_TYPE`,`NTPL_CONTENT_TYPE`,`NTPL_SUBJECT`,`NTPL_TEMPALTE`,`NTPL_SEQ`,`NTPL_DESC`,`NTPL_STATUS`,`NTPL_UID_CREATE`,`NTPL_DT_CREATE`,`NTPL_UID_LUPD`,`NTPL_DT_LUPD`)  VALUES('CKT_NTL_0007','CKT','CHN_TYPE_EMAIL','CNT_TYPE_HTML','Invoice Approved','<html> <style> html, body{font-family: "Roboto", sans-serif;} #container {width: 800px;border: 1px solid gray;padding: 10px 20px;} .innerContainer {padding: 0px 0px;} #footerContainer {background-color: #f2f3f4;color: darkslategray;padding: 5px 15px;margin-top: 15px;} .button {width: 300px;height: 50px;background-color:steelblue;color: white;margin:50px 0px;justify-content: center;align-items: center;display: flex;} </style> <body> <div id=container> <div id=titleContainer class=innerContainer> <img width=100 height=62 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> <div id=bodyContainer class=innerContainer> <h1>Job Invoice has been approved!</h1> <p>Job invoice(s) :invoiceNumber has been approved.</p> <p>For a complete list of the job(s), see your <a href=:jobDetailLink>job details</a></p> <a href=:jobDetailLink><div class=button>Click Here</div></a> </div> <div id=footerContainer class=innerContainer> <p><a style=color:inherit href=:privacyStatementLink>Privacy Statement</a></p> <p>:sp_details</p> <img width=50 height=31 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> </div> </body> </html>','7','Notification to TO Finance  when Invoice is Approved by CO','A','SYS',NOW(),'SYS',NOW());
INSERT INTO `T_CORE_NOTIFICATION_TEMPLATE`(`NTPL_ID`,`NTPL_APPSCODE`,`NTPL_CHANNEL_TYPE`,`NTPL_CONTENT_TYPE`,`NTPL_SUBJECT`,`NTPL_TEMPALTE`,`NTPL_SEQ`,`NTPL_DESC`,`NTPL_STATUS`,`NTPL_UID_CREATE`,`NTPL_DT_CREATE`,`NTPL_UID_LUPD`,`NTPL_DT_LUPD`)  VALUES('CKT_NTL_0008','CKT','CHN_TYPE_EMAIL','CNT_TYPE_HTML','Invoice Rejected','<html> <style> html, body{font-family: "Roboto", sans-serif;} #container {width: 800px;border: 1px solid gray;padding: 10px 20px;} .innerContainer {padding: 0px 0px;} #footerContainer {background-color: #f2f3f4;color: darkslategray;padding: 5px 15px;margin-top: 15px;} .button {width: 300px;height: 50px;background-color:steelblue;color: white;margin:50px 0px;justify-content: center;align-items: center;display: flex;} </style> <body> <div id=container> <div id=titleContainer class=innerContainer> <img width=100 height=62 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> <div id=bodyContainer class=innerContainer> <h1>Job Invoice has been rejected!</h1> <p>Job invoice(s) :invoiceNumber has been accepted</p> <p>For a complete list of the job(s), see your <a href=:jobDetailLink>job details</a></p> <a href=:jobDetailLink><div class=button>Click Here</div></a> </div> <div id=footerContainer class=innerContainer> <p><a style=color:inherit href=:privacyStatementLink>Privacy Statement</a></p> <p>:sp_details</p> <img width=50 height=31 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> </div> </body> </html>','8','Notification to TO Finance  when Invoice is Rejected by CO','A','SYS',NOW(),'SYS',NOW());
INSERT INTO `T_CORE_NOTIFICATION_TEMPLATE`(`NTPL_ID`,`NTPL_APPSCODE`,`NTPL_CHANNEL_TYPE`,`NTPL_CONTENT_TYPE`,`NTPL_SUBJECT`,`NTPL_TEMPALTE`,`NTPL_SEQ`,`NTPL_DESC`,`NTPL_STATUS`,`NTPL_UID_CREATE`,`NTPL_DT_CREATE`,`NTPL_UID_LUPD`,`NTPL_DT_LUPD`)  VALUES('CKT_NTL_0009','CKT','CHN_TYPE_EMAIL','CNT_TYPE_HTML','Payment Completed','<html> <style> html, body{font-family: "Roboto", sans-serif;} #container {width: 800px;border: 1px solid gray;padding: 10px 20px;} .innerContainer {padding: 0px 0px;} #footerContainer {background-color: #f2f3f4;color: darkslategray;padding: 5px 15px;margin-top: 15px;} .button {width: 300px;height: 50px;background-color:steelblue;color: white;margin:50px 0px;justify-content: center;align-items: center;display: flex;} </style> <body> <div id=container> <div id=titleContainer class=innerContainer> <img width=100 height=62 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> <div id=bodyContainer class=innerContainer> <h1>Job Invoice has been paid!</h1> <p>Job invoice(s) :invoiceNumber has been paid</p> <p>For a complete list of the job(s), see your <a href=:jobDetailLink>job details</a></p> <a href=:jobDetailLink><div class=button>Click Here</div></a> </div> <div id=footerContainer class=innerContainer> <p><a style=color:inherit href=:privacyStatementLink>Privacy Statement</a></p> <p>:sp_details</p> <img width=50 height=31 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> </div> </body> </html>','9','Notification to TO Finance when GLI has completed the payment.','A','SYS',NOW(),'SYS',NOW());
INSERT INTO `T_CORE_NOTIFICATION_TEMPLATE`(`NTPL_ID`,`NTPL_APPSCODE`,`NTPL_CHANNEL_TYPE`,`NTPL_CONTENT_TYPE`,`NTPL_SUBJECT`,`NTPL_TEMPALTE`,`NTPL_SEQ`,`NTPL_DESC`,`NTPL_STATUS`,`NTPL_UID_CREATE`,`NTPL_DT_CREATE`,`NTPL_UID_LUPD`,`NTPL_DT_LUPD`)  VALUES('CKT_NTL_0010','CKT','CHN_TYPE_EMAIL','CNT_TYPE_HTML','Invoice Approved','<html> <style> html, body{font-family: "Roboto", sans-serif;} #container {width: 800px;border: 1px solid gray;padding: 10px 20px;} .innerContainer {padding: 0px 0px;} #footerContainer {background-color: #f2f3f4;color: darkslategray;padding: 5px 15px;margin-top: 15px;} .button {width: 300px;height: 50px;background-color:steelblue;color: white;margin:50px 0px;justify-content: center;align-items: center;display: flex;} </style> <body> <div id=container> <div id=titleContainer class=innerContainer> <img width=100 height=62 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> <div id=bodyContainer class=innerContainer> <h1>Job Invoice has been approved!</h1> <p>Job invoice(s) :invoiceNumber has been approved.</p> <p>For a complete list of the job(s), see your <a href=:jobDetailLink>job details</a></p> <a href=:jobDetailLink><div class=button>Click Here</div></a> </div> <div id=footerContainer class=innerContainer> <p><a style=color:inherit href=:privacyStatementLink>Privacy Statement</a></p> <p>:sp_details</p> <img width=50 height=31 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> </div> </body> </html>','10','Notification to GLI F1 when TO invoice is approved by CO','A','SYS',NOW(),'SYS',NOW());
INSERT INTO `T_CORE_NOTIFICATION_TEMPLATE`(`NTPL_ID`,`NTPL_APPSCODE`,`NTPL_CHANNEL_TYPE`,`NTPL_CONTENT_TYPE`,`NTPL_SUBJECT`,`NTPL_TEMPALTE`,`NTPL_SEQ`,`NTPL_DESC`,`NTPL_STATUS`,`NTPL_UID_CREATE`,`NTPL_DT_CREATE`,`NTPL_UID_LUPD`,`NTPL_DT_LUPD`)  VALUES('CKT_NTL_0011','CKT','CHN_TYPE_EMAIL','CNT_TYPE_HTML','Payment Created','<html> <style> html, body{font-family: "Roboto", sans-serif;} #container {width: 800px;border: 1px solid gray;padding: 10px 20px;} .innerContainer {padding: 0px 0px;} #footerContainer {background-color: #f2f3f4;color: darkslategray;padding: 5px 15px;margin-top: 15px;} .button {width: 300px;height: 50px;background-color:steelblue;color: white;margin:50px 0px;justify-content: center;align-items: center;display: flex;} </style> <body> <div id=container> <div id=titleContainer class=innerContainer> <img width=100 height=62 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> <div id=bodyContainer class=innerContainer> <h1>Job Payment has been created!</h1> <p>Job payment(s) :jobPaymentNumber has been approved.</p> <p>For a complete list of the job(s), see your <a href=:jobDetailLink>job details</a></p> <a href=:jobDetailLink><div class=button>Click Here</div></a> </div> <div id=footerContainer class=innerContainer> <p><a style=color:inherit href=:privacyStatementLink>Privacy Statement</a></p> <p>:sp_details</p> <img width=50 height=31 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> </div> </body> </html>','11','Notification to GLI F2 when F1 created the Payment Transaction from approved Billling','A','SYS',NOW(),'SYS',NOW());
INSERT INTO `T_CORE_NOTIFICATION_TEMPLATE`(`NTPL_ID`,`NTPL_APPSCODE`,`NTPL_CHANNEL_TYPE`,`NTPL_CONTENT_TYPE`,`NTPL_SUBJECT`,`NTPL_TEMPALTE`,`NTPL_SEQ`,`NTPL_DESC`,`NTPL_STATUS`,`NTPL_UID_CREATE`,`NTPL_DT_CREATE`,`NTPL_UID_LUPD`,`NTPL_DT_LUPD`)  VALUES('CKT_NTL_0012','CKT','CHN_TYPE_EMAIL','CNT_TYPE_HTML','Payment Verified','<html> <style> html, body{font-family: "Roboto", sans-serif;} #container {width: 800px;border: 1px solid gray;padding: 10px 20px;} .innerContainer {padding: 0px 0px;} #footerContainer {background-color: #f2f3f4;color: darkslategray;padding: 5px 15px;margin-top: 15px;} .button {width: 300px;height: 50px;background-color:steelblue;color: white;margin:50px 0px;justify-content: center;align-items: center;display: flex;} </style> <body> <div id=container> <div id=titleContainer class=innerContainer> <img width=100 height=62 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> <div id=bodyContainer class=innerContainer> <h1>Job Payment has been verified!</h1> <p>Job payment(s) :jobPaymentNumber has been verified.</p> <p>For a complete list of the job(s), see your <a href=:jobDetailLink>job details</a></p> <a href=:jobDetailLink><div class=button>Click Here</div></a> </div> <div id=footerContainer class=innerContainer> <p><a style=color:inherit href=:privacyStatementLink>Privacy Statement</a></p> <p>:sp_details</p> <img width=50 height=31 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> </div> </body> </html>','12','Notification to GLI F3 when F2 verified the Payment Transaction','A','SYS',NOW(),'SYS',NOW());
INSERT INTO `T_CORE_NOTIFICATION_TEMPLATE`(`NTPL_ID`,`NTPL_APPSCODE`,`NTPL_CHANNEL_TYPE`,`NTPL_CONTENT_TYPE`,`NTPL_SUBJECT`,`NTPL_TEMPALTE`,`NTPL_SEQ`,`NTPL_DESC`,`NTPL_STATUS`,`NTPL_UID_CREATE`,`NTPL_DT_CREATE`,`NTPL_UID_LUPD`,`NTPL_DT_LUPD`)  VALUES('CKT_NTL_0013','CKT','CHN_TYPE_EMAIL','CNT_TYPE_HTML','Payment Completed','<html> <style> html, body{font-family: "Roboto", sans-serif;} #container {width: 800px;border: 1px solid gray;padding: 10px 20px;} .innerContainer {padding: 0px 0px;} #footerContainer {background-color: #f2f3f4;color: darkslategray;padding: 5px 15px;margin-top: 15px;} .button {width: 300px;height: 50px;background-color:steelblue;color: white;margin:50px 0px;justify-content: center;align-items: center;display: flex;} </style> <body> <div id=container> <div id=titleContainer class=innerContainer> <img width=100 height=62 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> <div id=bodyContainer class=innerContainer> <h1>Job Payment has been paid!</h1> <p>Job payment(s) :jobPaymentNumber has been paid</p> <p>For a complete list of the job(s), see your <a href=:jobDetailLink>job details</a></p> <a href=:jobDetailLink><div class=button>Click Here</div></a> </div> <div id=footerContainer class=innerContainer> <p><a style=color:inherit href=:privacyStatementLink>Privacy Statement</a></p> <p>:sp_details</p> <img width=50 height=31 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> </div> </body> </html>','13','Notification to Commercial, GLI F1 when the outbound payment has been completed','A','SYS',NOW(),'SYS',NOW());
INSERT INTO `T_CORE_NOTIFICATION_TEMPLATE`(`NTPL_ID`,`NTPL_APPSCODE`,`NTPL_CHANNEL_TYPE`,`NTPL_CONTENT_TYPE`,`NTPL_SUBJECT`,`NTPL_TEMPALTE`,`NTPL_SEQ`,`NTPL_DESC`,`NTPL_STATUS`,`NTPL_UID_CREATE`,`NTPL_DT_CREATE`,`NTPL_UID_LUPD`,`NTPL_DT_LUPD`)  VALUES('CKT_NTL_0014','CKT','CHN_TYPE_EMAIL','CNT_TYPE_HTML','Payment Failed','<html> <style> html, body{font-family: "Roboto", sans-serif;} #container {width: 800px;border: 1px solid gray;padding: 10px 20px;} .innerContainer {padding: 0px 0px;} #footerContainer {background-color: #f2f3f4;color: darkslategray;padding: 5px 15px;margin-top: 15px;} .button {width: 300px;height: 50px;background-color:steelblue;color: white;margin:50px 0px;justify-content: center;align-items: center;display: flex;} </style> <body> <div id=container> <div id=titleContainer class=innerContainer> <img width=100 height=62 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> <div id=bodyContainer class=innerContainer> <h1>Job Payment has failed!</h1> <p>Job payment(s) :jobPaymentNumber has failed.</p> <p>For a complete list of the job(s), see your <a href=:jobDetailLink>job details</a></p> <a href=:jobDetailLink><div class=button>Click Here</div></a> </div> <div id=footerContainer class=innerContainer> <p><a style=color:inherit href=:privacyStatementLink>Privacy Statement</a></p> <p>:sp_details</p> <img width=50 height=31 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> </div> </body> </html>','14','Notification to Commerical, GLI F1, L1-Support when the outbound payment has failed','A','SYS',NOW(),'SYS',NOW());

UPDATE `T_CORE_NOTIFICATION_TEMPLATE` SET `NTPL_TEMPALTE` = '<html> <style> html, body{font-family: "Roboto", sans-serif;} #container {width: 800px;border: 1px solid gray;padding: 10px 20px;} .innerContainer {padding: 0px 0px;} #footerContainer {background-color: #f2f3f4;color: darkslategray;padding: 5px 15px;margin-top: 15px;} .button {width: 300px;height: 50px;background-color:steelblue;color: white;margin:50px 0px;justify-content: center;align-items: center;display: flex;} </style> <body> <div id=container> <div id=titleContainer class=innerContainer> <img width=100 height=62 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> <div id=bodyContainer class=innerContainer> <h1>Job Invoice has been rejected!</h1> <p>Job invoice(s) :invoiceNumber has been rejected</p> <p>For a complete list of the job(s), see your <a href=:jobDetailLink>job details</a></p> <a href=:jobDetailLink><div class=button>Click Here</div></a> </div> <div id=footerContainer class=innerContainer> <p><a style=color:inherit href=:privacyStatementLink>Privacy Statement</a></p> <p>:sp_details</p> <img width=50 height=31 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> </div> </body> </html>'
WHERE (`NTPL_ID` = 'CKT_NTL_0008') and (`NTPL_SUBJECT` = 'Invoice Rejected');

UPDATE `T_CORE_NOTIFICATION_TEMPLATE` SET `NTPL_TEMPALTE` = '<html> <style> html, body{font-family: "Roboto", sans-serif;} #container {width: 800px;border: 1px solid gray;padding: 10px 20px;} .innerContainer {padding: 0px 0px;} #footerContainer {background-color: #f2f3f4;color: darkslategray;padding: 5px 15px;margin-top: 15px;} .button {width: 300px;height: 50px;background-color:steelblue;color: white;margin:50px 0px;justify-content: center;align-items: center;display: flex;} </style> <body> <div id=container> <div id=titleContainer class=innerContainer> <img width=100 height=62 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> <div id=bodyContainer class=innerContainer> <h1>Job Payment has been created!</h1> <p>Job payment(s) :jobPaymentNumber has been created.</p> <p>For a complete list of the job(s), see your <a href=:jobDetailLink>job details</a></p> <a href=:jobDetailLink><div class=button>Click Here</div></a> </div> <div id=footerContainer class=innerContainer> <p><a style=color:inherit href=:privacyStatementLink>Privacy Statement</a></p> <p>:sp_details</p> <img width=50 height=31 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> </div> </body> </html>'
WHERE (`NTPL_ID` = 'CKT_NTL_0011') and (`NTPL_SUBJECT` = 'Payment Created');

DELETE FROM `T_CK_SVC_ACTION_MASK` WHERE (`SAM_ID` = '1');
DELETE FROM `T_CK_SVC_ACTION_MASK` WHERE (`SAM_ID` = '10');
DELETE FROM `T_CK_SVC_ACTION_MASK` WHERE (`SAM_ID` = '11');
DELETE FROM `T_CK_SVC_ACTION_MASK` WHERE (`SAM_ID` = '12');
DELETE FROM `T_CK_SVC_ACTION_MASK` WHERE (`SAM_ID` = '2');
DELETE FROM `T_CK_SVC_ACTION_MASK` WHERE (`SAM_ID` = '3');
DELETE FROM `T_CK_SVC_ACTION_MASK` WHERE (`SAM_ID` = '4');
DELETE FROM `T_CK_SVC_ACTION_MASK` WHERE (`SAM_ID` = '5');
DELETE FROM `T_CK_SVC_ACTION_MASK` WHERE (`SAM_ID` = '6');
DELETE FROM `T_CK_SVC_ACTION_MASK` WHERE (`SAM_ID` = '7');
DELETE FROM `T_CK_SVC_ACTION_MASK` WHERE (`SAM_ID` = '8');
DELETE FROM `T_CK_SVC_ACTION_MASK` WHERE (`SAM_ID` = '9');

INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('1','CKT','ACC_TYPE_CO','OFFICER','CLICTRUCK','NEW',B'00000000011','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('2','CKT','ACC_TYPE_CO','OFFICER','CLICTRUCK','SUB',B'00000000100','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('3','CKT','ACC_TYPE_TO','OFFICER','CLICTRUCK','SUB',B'00000011000','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('4','CKT','ACC_TYPE_TO','OFFICER','CLICTRUCK','REJ',B'00000000000','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('5','CKT','ACC_TYPE_TO','OFFICER','CLICTRUCK','ACP',B'00000100000','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('6','CKT','ACC_TYPE_TO','OFFICER','CLICTRUCK','ASG',B'00001000000','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('7','CKT','ACC_TYPE_TO','OFFICER','CLICTRUCK','ONGOING',B'00010000000','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('8','CKT','ACC_TYPE_TO','FF_FINANCE','CLICTRUCK','DLV',B'00100000000','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('9','CKT','ACC_TYPE_CO','FF_FINANCE','CLICTRUCK','BILLED',B'01000000000','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('10','CKT','ACC_TYPE_CO','FF_FINANCE','CLICTRUCK','VER_BILL',B'10000000000','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('11','CKT','ACC_TYPE_SP','FINANCE_VERIFIER','CLICTRUCK','NEW',B'01000000000','A',NOW(),'SYS', NOW(),'SYS');
INSERT INTO T_CK_SVC_ACTION_MASK(SAM_ID, SAM_APPS_CODE, SAM_ACCN_TYPE, SAM_ROLE, SAM_SCV_TYPE, SAM_STATE, SAM_MASK, SAM_STATUS, SAM_DT_CREATE, SAM_UID_CREATE, SAM_DT_LUPD, SAM_UID_LUPD)  VALUES('12','CKT','ACC_TYPE_SP','FINANCE_APPROVER','CLICTRUCK','VER_BILL',B'10000000000','A',NOW(),'SYS', NOW(),'SYS');

/** When deploy in production, remember to add TO/COFF in subscription*/
INSERT INTO `T_CK_SVC_SUB` (`SUB_ID`, `SUB_TYPE`, `SUB_STATE`, `SUB_SUBSCRIBER`, `SUB_DT_START`, `SUB_DT_VALID`, `SUB_AUTO_RENEW`, `SUB_UID_VERIFY`, `SUB_DT_VERIFY`, `SUB_UID_APPROVE`, `SUB_DT_APPROVE`, `SUB_STATUS`, `SUB_DT_CREATE`, `SUB_UID_CREATE`, `SUB_DT_LUPD`, `SUB_UID_LUPD`) VALUES ('1666855052080B', 'CLICTRUCK', 'APR', 'BERAM', '2022-10-01 00:00:00', '2023-10-01 00:00:00', 'N', 'SYS', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'A', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'SYS');
INSERT INTO `T_CK_SVC_SUB` (`SUB_ID`, `SUB_TYPE`, `SUB_STATE`, `SUB_SUBSCRIBER`, `SUB_DT_START`, `SUB_DT_VALID`, `SUB_AUTO_RENEW`, `SUB_UID_VERIFY`, `SUB_DT_VERIFY`, `SUB_UID_APPROVE`, `SUB_DT_APPROVE`, `SUB_STATUS`, `SUB_DT_CREATE`, `SUB_UID_CREATE`, `SUB_DT_LUPD`, `SUB_UID_LUPD`) VALUES ('20230816GLICKT', 'CLICTRUCK', 'APR', 'GLI', '2022-10-01 00:00:00', '2023-10-01 00:00:00', 'N', 'SYS', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'A', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'SYS');
INSERT INTO `T_CK_SVC_SUB` (`SUB_ID`, `SUB_TYPE`, `SUB_STATE`, `SUB_SUBSCRIBER`, `SUB_DT_START`, `SUB_DT_VALID`, `SUB_AUTO_RENEW`, `SUB_UID_VERIFY`, `SUB_DT_VERIFY`, `SUB_UID_APPROVE`, `SUB_DT_APPROVE`, `SUB_STATUS`, `SUB_DT_CREATE`, `SUB_UID_CREATE`, `SUB_DT_LUPD`, `SUB_UID_LUPD`) VALUES ('20230816GLICKDO', 'CLICDO', 'APR', 'GLI', '2022-10-01 00:00:00', '2023-10-01 00:00:00', 'N', 'SYS', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'A', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'SYS');
INSERT INTO `T_CK_SVC_SUB` (`SUB_ID`, `SUB_TYPE`, `SUB_STATE`, `SUB_SUBSCRIBER`, `SUB_DT_START`, `SUB_DT_VALID`, `SUB_AUTO_RENEW`, `SUB_UID_VERIFY`, `SUB_DT_VERIFY`, `SUB_UID_APPROVE`, `SUB_DT_APPROVE`, `SUB_STATUS`, `SUB_DT_CREATE`, `SUB_UID_CREATE`, `SUB_DT_LUPD`, `SUB_UID_LUPD`) VALUES ('20230816GLICKDEC', 'CLICDEC', 'APR', 'GLI', '2022-10-01 00:00:00', '2023-10-01 00:00:00', 'N', 'SYS', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'A', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'SYS');
INSERT INTO `T_CK_SVC_SUB` (`SUB_ID`, `SUB_TYPE`, `SUB_STATE`, `SUB_SUBSCRIBER`, `SUB_DT_START`, `SUB_DT_VALID`, `SUB_AUTO_RENEW`, `SUB_UID_VERIFY`, `SUB_DT_VERIFY`, `SUB_UID_APPROVE`, `SUB_DT_APPROVE`, `SUB_STATUS`, `SUB_DT_CREATE`, `SUB_UID_CREATE`, `SUB_DT_LUPD`, `SUB_UID_LUPD`) VALUES ('20230816GLICKGP', 'CLICGP', 'APR', 'GLI', '2022-10-01 00:00:00', '2023-10-01 00:00:00', 'N', 'SYS', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'A', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'SYS');

/** Only for local environment; for production change localhost:port to production base url*/
UPDATE `T_CORE_APPS` SET `APPS_LAUNCH_URL` = 'https://id2.clickargo.com/clickargo' WHERE (`APPS_CODE` = 'CK');
UPDATE `T_CORE_APPS` SET `APPS_LAUNCH_URL` = 'https://id2.clickargo.com/clictruck' WHERE (`APPS_CODE` = 'CKT');

-- execute navigation.sql to update menu navigation

INSERT INTO `T_CK_CT_MST_TO_INVOICE_STATE` (`INST_ID`, `INST_NAME`, `INST_DESC`, `INST_DESC_OTH`, `INST_STATUS`, `INST_DT_CREATE`, `INST_UID_CREATE`, `INST_DT_LUPD`, `INST_UID_LUPD`) VALUES ('PENDING', 'PENDING', 'PENDING', 'PENDING', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
INSERT INTO `T_CK_CT_MST_DEBIT_NOTE_STATE` (`DNST_ID`, `DNST_NAME`, `DNST_DESC`, `DNST_DESC_OTH`, `DNST_STATUS`, `DNST_DT_CREATE`, `DNST_UID_CREATE`, `DNST_DT_LUPD`, `DNST_UID_LUPD`) VALUES ('PENDING', 'PENDING', 'PENDING', 'PENDING', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

-- executed in uat on 23-Aug-2023 --
UPDATE `T_CORE_SYSPARAM` SET `SYS_VAL` = '6' WHERE (`SYS_KEY` = 'MAX_LOGIN_ATTEMPTS_CONFIG');
INSERT INTO `T_CK_CT_MST_DEBIT_NOTE_STATE` (`DNST_ID`, `DNST_NAME`, `DNST_DESC`, `DNST_DESC_OTH`, `DNST_STATUS`, `DNST_DT_CREATE`, `DNST_UID_CREATE`, `DNST_DT_LUPD`, `DNST_UID_LUPD`) VALUES ('PAYING', 'PAYING', 'PAYING', 'PAYING', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
INSERT INTO `T_CK_CT_MST_TO_INVOICE_STATE` (`INST_ID`, `INST_NAME`, `INST_DESC`, `INST_DESC_OTH`, `INST_STATUS`, `INST_DT_CREATE`, `INST_UID_CREATE`, `INST_DT_LUPD`, `INST_UID_LUPD`) VALUES ('PAYING', 'PAYING', 'PAYING', 'PAYING', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

-- Added for commercial team to view
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'SP_OP_ADMIN', 'PM034', 'A', NOW(), 'SYS');

-- executed in prod on 26 Aug 2023 --
-- do not add below this line --