
INSERT INTO `clickargo2`.`T_MST_ACCN_TYPE` (`ATYP_ID`, `ATYP_DESCRIPTION`, `ATYP_STATUS`, `ATYP_DT_CREATE`, `ATYP_UID_CREATE`) 
VALUES ('ACC_TYPE_FF_CO', 'FF-CO', 'A', sysdate(), 'SYS');

INSERT INTO `clickargo2`.`T_CK_SEQUENCE_NO` (`SQN_ID`, `SQN_DESC`, `SQN_KEY`, `SQN_SEQ`, `SQN_DT_CREATE`, `SQN_UID_CREATE`) 
VALUES ('CT_USER_CODE', 'USER CODE FORMAT', 'CKU%04d', '1000', SYSDATE(), 'SYS');

CREATE TABLE `T_CK_CT_FF_CO` (
  `FFCO_ID` varchar(35) NOT NULL COMMENT 'ASSOCIATION ID - UUID',
  `FFCO_FF` varchar(35) DEFAULT NULL COMMENT 'FREIGHT FORWARDER ACCN - REFERENCES T_CORE_ACCN:ACCN_ID',
  `FFCO_CO` varchar(35) DEFAULT NULL COMMENT 'CARGO OWNER ACCN - REFERENCES T_CORE_ACCN:ACCN_ID',
  `FFCO_REF` varchar(255) DEFAULT NULL COMMENT 'ASSOCATION REFERENCE NUMBER',
  `FFCO_REMARKS` mediumtext COMMENT 'ASSOCIATION REMARKS',
  `FFCO_DT_START` datetime DEFAULT NULL COMMENT 'START DATE OF ASSOCATION',
  `FFCO_DT_END` datetime DEFAULT NULL COMMENT 'END DATE OF ASSOCATION',
  `FFCO_STATUS` char(1) DEFAULT NULL COMMENT 'RECORD STATUS - A : I',
  `FFCO_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `FFCO_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `FFCO_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `FFCO_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`FFCO_ID`),
  CONSTRAINT `FK_CK_CT_FF_CO_CORE_ACCN1` FOREIGN KEY (`FFCO_FF`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_CT_FF_CO_CORE_ACCN2` FOREIGN KEY (`FFCO_CO`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='ASSOCIATION TABLE BETWEEN FF AND CO';

INSERT INTO `clickargo2`.`T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`, `ROLE_STATUS`, `ROLE_DESC`, `ROLE_DT_CREATE`, `ROLE_UID_CREATE`, `ROLE_DT_LUPD`, `ROLE_UID_LUPD`) 
VALUES ('CKT', 'FF_CO_ADMIN', 'A', 'FF-CO ADMIN', SYSDATE(), 'SYS', SYSDATE(), 'SYS');

INSERT INTO `clickargo2`.`T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`, `ROLE_STATUS`, `ROLE_DESC`, `ROLE_DT_CREATE`, `ROLE_UID_CREATE`, `ROLE_DT_LUPD`, `ROLE_UID_LUPD`) 
VALUES ('CKT', 'FF_ADMIN', 'A', 'FF_ADMIN', SYSDATE(), 'SYS', SYSDATE(), 'SYS');



UPDATE `clickargo2`.`T_CORE_PERM_EX` SET `PERM_GROUP` = 'N' WHERE (`PERM_ID` = 'PM036');

INSERT INTO `clickargo2`.`T_CORE_USR_ROLE` (`UROL_UID`, `UROL_APPSCODE`, `UROL_ROLEID`, `UROL_ADMIN_OPT`, `UROL_STATUS`, `UROL_DT_CREATE`, `UROL_UID_CREATE`, `UROL_DT_LUPD`, `UROL_UID_LUPD`, `UROL_TEMP_ROLE`) VALUES ('CKU00477', 'CKT', 'FF_ADMIN', 'N', 'A', '2023-06-17 16:51:09', 'SYS', '2023-06-17 16:51:09', 'SYS', 'N');



