

-- JOB TRUCK
ALTER TABLE `clickargo2`.`T_CK_JOB_TRUCK` 
ADD COLUMN `JOB_FINANCE_OPT` varchar(35) NULL DEFAULT 'NF' COMMENT 'JOB FINANCED OPTIONS -  NF:BC:OC/OT' AFTER `JOB_IS_FINANCED`,
ADD COLUMN `JOB_FINANCER` varchar(35) DEFAULT NULL COMMENT 'JOB FINANCER -  OCBC:UOB:BCA' AFTER `JOB_FINANCE_OPT`;

ALTER TABLE `clickargo2`.`T_CK_JOB_TRUCK` 
ADD COLUMN `JOB_DT_OPM_UTILIZE` datetime DEFAULT null COMMENT 'push job to OPM time' AFTER `JOB_FINANCER`;


drop table if exists T_CK_CT_CONTRACT_FINANCE;
drop table if exists T_CK_CREDIT_FINANCE;
drop table if exists T_CK_CREDIT_FINANCE_JOURNAL;
drop table if exists T_CK_CREDIT_FINANCE_SUMMARY;

drop table if exists T_CK_ACCN_OPM;
drop table if exists T_CK_ACCN;

drop table if exists T_CK_CT_CONTRACT_OPM;
drop table if exists T_CK_OPM;
drop table if exists T_CK_OPM_JOURNAL;
drop table if exists T_CK_OPM_SUMMARY;
drop table if exists T_CK_CT_MST_OPM_RATE;

-- Move data from T_CORE_ACCN_CONFIG to this table ???
CREATE TABLE `T_CK_ACCN` (
  `CACCN_ID` varchar(70) NOT NULL,
  `CACCN_FINANCING_TYPE` VARCHAR(35) NULL COMMENT 'NF (NON-FINANCING)  | BC (BALANCE SHEET FINANCING) | OT (IF ACCN TYPE IS TRUCKING OPERATOR) | OC (IF ACCNTYPE IS CARGO OWNER)',
  `CACCN_FINANCER` varchar(70)  NULL COMMENT 'GLI , OCBC',
  `CACCN_STATUS` char(1) NOT NULL,
  `CACCN_DT_CREATE` datetime NOT NULL COMMENT 'Contains the date where this record is created.',
  `CACCN_UID_CREATE` varchar(35) NOT NULL COMMENT 'Contains the User ID that create this record.',
  `CACCN_DT_LUPD` datetime DEFAULT NULL COMMENT 'Contains the date where this record is last updated.',
  `CACCN_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'Contains the User ID that last update this record.',
  PRIMARY KEY (`CACCN_ID`),
  CONSTRAINT `FKY__T_CK_ACCN__ID` FOREIGN KEY (`CACCN_ID`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


-- CONTRACT TABLE
CREATE TABLE `T_CK_ACCN_OPM` (
  `CAO_ID` varchar(35) NOT NULL COMMENT 'CONTRACT FINANCE ID - UUID',
  `CAO_TYPE` char(2) DEFAULT NULL COMMENT 'CONTRACT FINANCE TYPE - NF:BC:OC/OT',
  `CAO_FINANCER` varchar(35) DEFAULT NULL COMMENT 'CONTRACT FINANCER - OCBC:BCA:UOB',
  `CAO_CREDIT_LIMIT` decimal(15,2) DEFAULT '0.00' COMMENT 'FACILITY LIMIT',
  `CAO_DT_APPROVE` datetime DEFAULT NULL COMMENT 'FACILITY LIMIT APPROVAL DATE',
  `CAO_DT_EXPIRY` datetime DEFAULT NULL COMMENT 'FACILITY LIMIT EXPIRY DATE',
  `CAO_DT_CLOSE` datetime DEFAULT NULL COMMENT 'FACILITY LIMIT CLOSURE DATE',
  `CAO_DT_SUSPEND` datetime DEFAULT NULL COMMENT 'FACILITY LIMIT LAST SUSPENSION DATE',
  `CAO_DT_UNSUSPEND` datetime DEFAULT NULL COMMENT 'FACILITY LIMIT LAST UNSUSPENSION DATE',
  `CAO_STATUS` char(1) DEFAULT NULL COMMENT 'CONTRACT STATE STATUS',
  `CAO_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CAO_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CAO_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CAO_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CAO_ID`),
  CONSTRAINT `FK_CK_CT_CONTRACT_OPM_CORE_ACCN` FOREIGN KEY (`CAO_ID`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='ACCOUNT FINANCE TABLE';

-- CREDIT LIMIT
CREATE TABLE `T_CK_OPM` (
  `OPM_ID` varchar(35) NOT NULL COMMENT 'RECORD ID - UUID',
  `OPM_SERVICE_TYPE` varchar(35) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'CREDIT SERVICE TYPE - REFERENCES T_CK_MST_SERVICE_TYPE:SVCT_ID',
  `OPM_COMPANY` varchar(35) DEFAULT NULL COMMENT 'CREDIT COMPANY ACCOUNT - REFERENCES T_CORE_ACCN:ACCN_ID',
  `OPM_FINANCER` varchar(35) DEFAULT NULL COMMENT 'CREDIT FINANCER - OCBC:BCA:UOB', 
  `OPM_STATE` varchar(35) DEFAULT NULL COMMENT 'CREDIT STATE - REFERENCES T_CK_MST_CREDIT_STATE:CRST_ID',
  `OPM_AMT` double(15,2) DEFAULT '0.00' COMMENT 'CREDIT AMOUNT',
  `OPM_CCY` varchar(3) DEFAULT NULL COMMENT 'CURRENCY  - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `OPM_DT_START` datetime DEFAULT NULL COMMENT 'CREDIT START DATE TIME',
  `OPM_DT_END` datetime DEFAULT NULL COMMENT 'CREDIT END DATE TIME',
  `OPM_USR_VERIFY` varchar(35) DEFAULT NULL COMMENT 'CREDIT VERIFIER',
  `OPM_DT_VERIFY` datetime DEFAULT NULL COMMENT 'CREDIT VERIFIED DATE TIME',
  `OPM_USR_APPROVE` varchar(35) DEFAULT NULL COMMENT 'CREDIT APPROVER',
  `OPM_DT_APPROVE` datetime DEFAULT NULL COMMENT 'CREDIT APPROVED DATE TIME',
  `OPM_REMARKS` mediumtext COMMENT 'REMARKS FOR CREDIT APPROVAL',
  `OPM_STATUS` char(1) DEFAULT NULL COMMENT 'CREDIT RECORD STATUS',
  `OPM_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `OPM_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `OPM_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `OPM_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`OPM_ID`),
  CONSTRAINT `FK_CK_CREDIT_OPM_CK_MST_CREDIT_STATE` FOREIGN KEY (`OPM_STATE`) REFERENCES `T_CK_MST_CREDIT_STATE` (`CRST_ID`),
  CONSTRAINT `FK_CK_CREDIT_OPM_CK_MST_SERVICE_TYPE` FOREIGN KEY (`OPM_SERVICE_TYPE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),
  CONSTRAINT `FK_CK_CREDIT_OPM_CORE_ACCN` FOREIGN KEY (`OPM_COMPANY`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_CREDIT_OPM_MST_CURRENCY` FOREIGN KEY (`OPM_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='OTHER PEOPLE MONEY TABLE';

CREATE TABLE `T_CK_OPM_JOURNAL` (
  `OPMJ_ID` varchar(35) NOT NULL COMMENT 'RECORD ID - UUID',
  `OPMJ_SERVICE_TYPE` varchar(35) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'CREDIT JOURNAL SERVICE TYPE - REFERENCES T_CK_MST_SERVICE_TYPE:SVCT_ID',
  `OPMJ_COMPANY` varchar(35) DEFAULT NULL COMMENT 'CREDIT JOURNAL COMPANY ACCOUNT - REFERENCES T_CORE_ACCN:ACCN_ID',
  `OPMJ_TXN_TYPE` varchar(35) DEFAULT NULL COMMENT 'CREDIT JOURNAL TRANSACITON TYPE - REFERNCES T_CK_MST_JOURNAL_TXN_TYPE:JTT_ID',
  `OPMJ_TXN_REF` varchar(255) DEFAULT NULL COMMENT 'CREDIT JOURNAL TRANSACITON REFERENCE - JOB ID OR PAYMENT ID',
  `OPMJ_RESERVE` double(15,2) DEFAULT '0.00' COMMENT 'CREDIT SUMMARY RESERVE',
  `OPMJ_UTILIZED` double(15,2) DEFAULT '0.00' COMMENT 'CREDIT SUMMARY UTILIZED',
  `OPMJ_CCY` varchar(3) DEFAULT NULL COMMENT 'CURRENCY  - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `OPMJ_STATUS` char(1) DEFAULT NULL COMMENT 'CREDIT RECORD STATUS',
  `OPMJ_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `OPMJ_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `OPMJ_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `OPMJ_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`OPMJ_ID`),
  KEY `FK_CK_OPM_JOURNAL_CK_MST_SERVICE_TYPE` (`OPMJ_SERVICE_TYPE`),
  KEY `FK_CK_OPM_JOURNAL_CORE_ACCN` (`OPMJ_COMPANY`),
  KEY `FK_CK_OPM_JOURNAL_CK_MST_JOURNAL_TXN_TYPE` (`OPMJ_TXN_TYPE`),
  KEY `FK_CK_OPM_JOURNAL_MST_CURRENCY` (`OPMJ_CCY`),
  CONSTRAINT `FK_CK_OPM_JOURNAL_CK_MST_JOURNAL_TXN_TYPE` FOREIGN KEY (`OPMJ_TXN_TYPE`) REFERENCES `T_CK_MST_JOURNAL_TXN_TYPE` (`JTT_ID`),
  CONSTRAINT `FK_CK_OPM_JOURNAL_CK_MST_SERVICE_TYPE` FOREIGN KEY (`OPMJ_SERVICE_TYPE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),
  CONSTRAINT `FK_CK_OPM_JOURNAL_CORE_ACCN` FOREIGN KEY (`OPMJ_COMPANY`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_OPM_JOURNAL_MST_CURRENCY` FOREIGN KEY (`OPMJ_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='OPM JOURNAL TABLE';

CREATE TABLE `T_CK_OPM_SUMMARY` (
  `OPMS_ID` varchar(35) NOT NULL COMMENT 'RECORD ID - UUID',
  `OPMS_SERVICE_TYPE` varchar(35) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'CREDIT SUMMARY SERVICE TYPE - REFERENCES T_CK_MST_SERVICE_TYPE:SVCT_ID',
  `OPMS_COMPANY` varchar(35) DEFAULT NULL COMMENT 'CREDIT SUMMARY COMPANY ACCOUNT - REFERENCES T_CORE_ACCN:ACCN_ID',
  `OPMS_AMT` double(15,2) DEFAULT '0.00' COMMENT 'CREDIT SUMMARY AMOUNT',
  `OPMS_RESERVE` double(15,2) DEFAULT '0.00' COMMENT 'CREDIT SUMMARY RESERVE',
  `OPMS_UTILIZED` double(15,2) DEFAULT '0.00' COMMENT 'CREDIT SUMMARY UTILIZED',
  `OPMS_BALANCE` double(15,2) DEFAULT '0.00' COMMENT 'CREDIT SUMMARY BALANCE',
  `OPMS_CCY` varchar(3) DEFAULT NULL COMMENT 'CURRENCY  - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `OPMS_STATUS` char(1) DEFAULT NULL COMMENT 'CREDIT RECORD STATUS',
  `OPMS_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `OPMS_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `OPMS_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `OPMS_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  `OPMS_CREDIT` varchar(35) DEFAULT NULL COMMENT 'CREDIT - REFERENCE T_CK_CREDIT:CR_ID',
  PRIMARY KEY (`OPMS_ID`),
  KEY `FK_CK_OPM_SUMMARY_CK_MST_SERVICE_TYPE` (`OPMS_SERVICE_TYPE`),
  KEY `FK_CK_OPM_SUMMARY_CORE_ACCN` (`OPMS_COMPANY`),
  KEY `FK_CK_OPM_SUMMARY_MST_CURRENCY` (`OPMS_CCY`),
  CONSTRAINT `FK_CK_OPM_SUMMARY_CK_MST_SERVICE_TYPE` FOREIGN KEY (`OPMS_SERVICE_TYPE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),
  CONSTRAINT `FK_CK_OPM_SUMMARY_CORE_ACCN` FOREIGN KEY (`OPMS_COMPANY`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_OPM_SUMMARY_MST_CURRENCY` FOREIGN KEY (`OPMS_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='OPM SUMMARY TABLE';

CREATE TABLE `T_CK_CT_MST_OPM_RATE` (
  `OPMR_ID` varchar(35) NOT NULL,
  `OPMR_BANK` varchar(35) DEFAULT NULL COMMENT 'BANK ID - REFERENCES T_MST_BANK:BANK_ID',
  `OPMR_DT_START` datetime DEFAULT NULL COMMENT 'RATE START DATE TIME',
  `OPMR_DT_END` datetime DEFAULT NULL COMMENT 'RATE END DATE TIME',
  `OPMR_PERCENT_BANK` double(15,5) DEFAULT '0.015' COMMENT 'RATE FOR BANK', 
  `OPMR_PERCENT_GLI` double(15,5) DEFAULT '0.01' COMMENT 'RATE FOR GLI', 
  `OPMR_PAYTERM_CO` int DEFAULT NULL,
  `OPMR_PAYTERM_TO` int DEFAULT NULL,
  `OPMR_CCY` varchar(3) DEFAULT NULL COMMENT ' CURRENCY - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `OPMR_STATUS` char(1) NOT NULL,
  `OPMR_DT_CREATE` datetime DEFAULT NULL,
  `OPMR_UID_CREATE` varchar(35) DEFAULT NULL,
  `OPMR_DT_LUPD` datetime DEFAULT NULL,
  `OPMR_UID_LUPD` varchar(35) DEFAULT NULL,
  KEY `T_CK_CT_MST_OPM_RATE_BANK` (`OPMR_BANK`),
  KEY `T_CK_CT_MST_OPM_RATE_CURRENCY` (`OPMR_CCY`),
  CONSTRAINT `T_CK_CT_MST_OPM_RATE_BANK` FOREIGN KEY (`OPMR_BANK`) REFERENCES `T_MST_BANK` (`BANK_ID`),
  CONSTRAINT `T_CK_CT_MST_OPM_RATE_CURRENCY` FOREIGN KEY (`OPMR_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`),
  PRIMARY KEY (`OPMR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

INSERT IGNORE INTO `clickargo2`.`T_MST_BANK` (`BANK_ID`, `BANK_STATUS`, `BANK_DESCRIPTION`, `BANK_ADDR1`, `BANK_ADDR2`, `BANK_ADDR3`, `BANK_PCODE`, `BANK_CITY`, `BANK_PROV`, `BANK_TEL`, `BANK_FAX`, `BANK_EMAIL`, `BANK_DT_CREATE`, `BANK_UID_CREATE`, `BANK_DT_LUPD`, `BANK_UID_LUPD`, `BANK_IS_ONLINE`, `BANK_LOGO_FILE_DATA`) 
VALUES ('OCBC', 'A', 'OCBC', 'OCBC', 'Tower 3 ', 'Marina Bay', '018987', 'Singapore', '', '6566888888', '', 'support@dbs.com.sg', '2018-12-01 00:00:00', 'SYS', '2018-12-01 00:00:00', 'SYS', 'N', '');

INSERT INTO `clickargo2`.`T_MST_BANK` (`BANK_ID`, `BANK_STATUS`, `BANK_DESCRIPTION`, `BANK_ADDR1`, `BANK_ADDR2`, `BANK_ADDR3`, `BANK_PCODE`, `BANK_CITY`, `BANK_PROV`, `BANK_TEL`, `BANK_FAX`, `BANK_EMAIL`, `BANK_DT_CREATE`, `BANK_UID_CREATE`, `BANK_DT_LUPD`, `BANK_UID_LUPD`, `BANK_IS_ONLINE`, `BANK_LOGO_FILE_DATA`) 
VALUES ('AMAR', 'A', 'AMAR', 'AMAR', 'Tower 3 ', 'Marina Bay', '018987', 'Singapore', '', '6566888888', '', 'support@ARMAR.com.sg', '2018-12-01 00:00:00', 'SYS', '2018-12-01 00:00:00', 'SYS', 'N', '');


REPLACE INTO `clickargo2`.`T_CK_CT_MST_OPM_RATE` (`OPMR_ID`, `OPMR_BANK`, `OPMR_DT_START`, `OPMR_DT_END`, `OPMR_PERCENT_BANK`, `OPMR_PERCENT_GLI`, `OPMR_PAYTERM_CO`, `OPMR_PAYTERM_TO`, `OPMR_CCY`, `OPMR_STATUS`, `OPMR_DT_CREATE`, `OPMR_UID_CREATE`) 
VALUES ('OCBC1', 'OCBC', '2024-01-01', '2026-1-01', '0.015', '0.01', '30', '7', 'IDR', 'A', sysdate(), 'SYS');
REPLACE INTO `clickargo2`.`T_CK_CT_MST_OPM_RATE` (`OPMR_ID`, `OPMR_BANK`, `OPMR_DT_START`, `OPMR_DT_END`, `OPMR_PERCENT_BANK`, `OPMR_PERCENT_GLI`, `OPMR_PAYTERM_CO`, `OPMR_PAYTERM_TO`, `OPMR_CCY`, `OPMR_STATUS`, `OPMR_DT_CREATE`, `OPMR_UID_CREATE`) 
VALUES ('OCBC2', 'OCBC', '2024-01-01', '2026-1-01', '0.020', '0.015', '45', '7', 'IDR', 'A', sysdate(), 'SYS');
REPLACE INTO `clickargo2`.`T_CK_CT_MST_OPM_RATE` (`OPMR_ID`, `OPMR_BANK`, `OPMR_DT_START`, `OPMR_DT_END`, `OPMR_PERCENT_BANK`, `OPMR_PERCENT_GLI`, `OPMR_PAYTERM_CO`, `OPMR_PAYTERM_TO`, `OPMR_CCY`, `OPMR_STATUS`, `OPMR_DT_CREATE`, `OPMR_UID_CREATE`) 
VALUES ('OCBC3', 'OCBC', '2024-01-01', '2026-1-01', '0.025', '0.020', '60', '7', 'IDR', 'A', sysdate(), 'SYS');


REPLACE INTO `clickargo2`.`T_CK_CT_MST_OPM_RATE` (`OPMR_ID`, `OPMR_BANK`, `OPMR_DT_START`, `OPMR_DT_END`, `OPMR_PERCENT_BANK`, `OPMR_PERCENT_GLI`, `OPMR_PAYTERM_CO`, `OPMR_PAYTERM_TO`, `OPMR_CCY`, `OPMR_STATUS`, `OPMR_DT_CREATE`, `OPMR_UID_CREATE`) 
VALUES ('AMAR1', 'AMAR', '2024-01-01', '2026-1-01', '0.015', '0.01', '30', '7', 'IDR', 'A', sysdate(), 'SYS');
REPLACE INTO `clickargo2`.`T_CK_CT_MST_OPM_RATE` (`OPMR_ID`, `OPMR_BANK`, `OPMR_DT_START`, `OPMR_DT_END`, `OPMR_PERCENT_BANK`, `OPMR_PERCENT_GLI`, `OPMR_PAYTERM_CO`, `OPMR_PAYTERM_TO`, `OPMR_CCY`, `OPMR_STATUS`, `OPMR_DT_CREATE`, `OPMR_UID_CREATE`) 
VALUES ('AMAR2', 'AMAR', '2024-01-01', '2026-1-01', '0.020', '0.015', '45', '7', 'IDR', 'A', sysdate(), 'SYS');
REPLACE INTO `clickargo2`.`T_CK_CT_MST_OPM_RATE` (`OPMR_ID`, `OPMR_BANK`, `OPMR_DT_START`, `OPMR_DT_END`, `OPMR_PERCENT_BANK`, `OPMR_PERCENT_GLI`, `OPMR_PAYTERM_CO`, `OPMR_PAYTERM_TO`, `OPMR_CCY`, `OPMR_STATUS`, `OPMR_DT_CREATE`, `OPMR_UID_CREATE`) 
VALUES ('AMAR3', 'AMAR', '2024-01-01', '2026-1-01', '0.025', '0.020', '60', '7', 'IDR', 'A', sysdate(), 'SYS');


ALTER TABLE `clickargo2`.`T_MST_BANK` 
ADD COLUMN `BANK_URL` VARCHAR(256) NULL COMMENT 'BANK LANDING PAGE OR REGISTRATION PAGE' AFTER `BANK_LOGO_FILE_DATA`,
ADD COLUMN `BANK_CONNECTION_TYPE` VARCHAR(35) NULL COMMENT 'SFTP | FTP | WS (WEBSERVICE)' AFTER `BANK_URL`,
ADD COLUMN `BANK_CONNECTION_DETAILS` VARCHAR(1024) NULL COMMENT 'JSON FORMAT CONNECTION DETAILS' AFTER `BANK_CONNECTION_TYPE`;

-- test data
UPDATE `clickargo2`.`T_MST_BANK` SET `BANK_URL` = 'https://www.ocbc.id/en/individu' WHERE (`BANK_ID` = 'OCBC');
UPDATE `clickargo2`.`T_MST_BANK` SET `BANK_URL` = 'https://amarbank.co.id/' WHERE (`BANK_ID` = 'AMAR');

DROP TRIGGER IF EXISTS TGR_AI_SUM_OPM;
DROP TRIGGER IF EXISTS TGR_AU_SUM_OPM;

CREATE TRIGGER TGR_AU_SUM_OPM AFTER UPDATE ON T_CK_OPM_JOURNAL FOR EACH ROW UPDATE T_CK_OPM_SUMMARY,
( SELECT sum(OPMJ_RESERVE) vReserved, sum(OPMJ_UTILIZED) as vUtillized
FROM clickargo2.T_CK_OPM_JOURNAL opj
where OPMJ_COMPANY = NEW.OPMJ_COMPANY AND OPMJ_SERVICE_TYPE = NEW.OPMJ_SERVICE_TYPE AND OPMJ_CCY = NEW.OPMJ_CCY
group by OPMJ_SERVICE_TYPE, OPMJ_COMPANY, OPMJ_CCY) src
	SET OPMS_BALANCE =OPMS_AMT - (vReserved + vUtillized), OPMS_RESERVE = vReserved, OPMS_UTILIZED = vUtillized		
	WHERE OPMS_SERVICE_TYPE = NEW.OPMJ_SERVICE_TYPE AND OPMS_COMPANY = NEW.OPMJ_COMPANY AND OPMS_CCY = NEW.OPMJ_CCY;

CREATE TRIGGER TGR_AI_SUM_OPM AFTER INSERT ON T_CK_OPM_JOURNAL FOR EACH ROW UPDATE T_CK_OPM_SUMMARY,
( SELECT sum(OPMJ_RESERVE) vReserved, sum(OPMJ_UTILIZED) as vUtillized
FROM clickargo2.T_CK_OPM_JOURNAL opj
where OPMJ_COMPANY = NEW.OPMJ_COMPANY AND OPMJ_SERVICE_TYPE = NEW.OPMJ_SERVICE_TYPE AND OPMJ_CCY = NEW.OPMJ_CCY
group by OPMJ_SERVICE_TYPE, OPMJ_COMPANY, OPMJ_CCY) src
	SET OPMS_BALANCE =OPMS_AMT - (vReserved + vUtillized), OPMS_RESERVE = vReserved, OPMS_UTILIZED = vUtillized		
	WHERE OPMS_SERVICE_TYPE = NEW.OPMJ_SERVICE_TYPE AND OPMS_COMPANY = NEW.OPMJ_COMPANY AND OPMS_CCY = NEW.OPMJ_CCY;

INSERT INTO `clickargo2`.`T_CK_MST_PAYMENT_TYPE` (`PTY_ID`, `PYT_NAME`, `PYT_DESC`, `PYT_DESC_OTH`, `PYT_STATUS`, `PYT_DT_CREATE`, `PYT_UID_CREATE`)
 VALUES ('OPM', 'Other People Money', 'Other People Money', 'Other People Money', 'A', sysdate(), 'SYS');

drop table if exists T_CK_OPM_SFTP_LOG;

CREATE TABLE `T_CK_OPM_SFTP_LOG` (
  `OPMSL_ID` varchar(35) NOT NULL COMMENT 'OPM EXCEL FILE LOG ID - UUID',
  `OPMSL_FINANCER` varchar(35) DEFAULT NULL COMMENT 'FINANCER: BANK:OCBC',
  `OPMSL_DIRECTION` varchar(35) DEFAULT NULL COMMENT 'OUT: PUSH FILE TO BANK, IN: PULL FILE FROM BANK',
  `OPMSL_FILE_TYPE` varchar(35) DEFAULT NULL COMMENT 'CP, CU, CD, CT, CS, CE',
  `OPMSL_FILE_NAME` varchar(256) DEFAULT NULL COMMENT 'EXCEL FILE NAME',
  `OPMSL_FILE_PATH` varchar(512) DEFAULT NULL COMMENT 'EXCEL FILE NAME AND PATH IN LOCAL',
  `OPMSL_FILE_SIZE` int DEFAULT NULL COMMENT 'EXCEL FILE LEGNTH',
  `OPMSL_ACCN_IDS` varchar(256) DEFAULT NULL,
  `OPMSL_JOB_IDS` varchar(2048) DEFAULT NULL,
  `OPMSL_DT_FILE_CREATE` datetime DEFAULT NULL COMMENT 'FILE PULL OR PUSH TO FTP TIME',
  `OPMSL_DT_FILE_PUSH2SFTP` datetime DEFAULT NULL COMMENT 'ONLY FOR OUT',
  `OPMSL_REMARK` varchar(1024) DEFAULT NULL,
  `OPMSL_ERROR_FILE_NAME` varchar(256) DEFAULT NULL COMMENT 'ERROR FILE NAME',
  `OPMSL_ERROR_FILE_PATH` varchar(512) DEFAULT NULL COMMENT 'ERROR FILE PATH',
  `OPMSL_ERROR_FILE_SIZE` int DEFAULT NULL COMMENT 'ERROR FILE CONTEXT LENGTH',
  `OPMSL_ERROR_ACCN_IDS` varchar(256) DEFAULT NULL,
  `OPMSL_ERROR_JOB_IDS` varchar(2048) DEFAULT NULL,
  `OPMSL_DT_ERROR_FILE_CREATE` datetime DEFAULT NULL COMMENT 'ERROR FILE CREATE DATE',
  `OPMSL_DT_ERROR_FILE_PUSH2SFTP` datetime DEFAULT NULL,
  `OPMSL_ERROR_FILE_REMARK` varchar(1024) DEFAULT NULL,
  `OPMSL_STATUS` char(1) DEFAULT NULL COMMENT 'OPM STATE STATUS',
  `OPMSL_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `OPMSL_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `OPMSL_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `OPMSL_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`OPMSL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT=' OPM SFTP LOG TABLE';

INSERT INTO `clickargo2`.`T_CK_MST_JOURNAL_TXN_TYPE` (`JTT_ID`, `JTT_NAME`, `JTT_DESC`, `JTT_DESC_OTH`, `JTT_STATUS`, `JTT_DT_CREATE`, `JTT_UID_CREATE`) 
VALUES ('JOB_OPM_ACCEPT', 'JOB_OPM_ACCEPT', 'JOB_OPM_ACCEPT', 'JOB_OPM_ACCEPT', 'A', SYSDATE(), 'SYS');


UPDATE `clickargo2`.`T_MST_BANK` SET `BANK_CONNECTION_TYPE` = 'SFTP', `BANK_CONNECTION_DETAILS` = '{\"host\":\"43.218.212.20\",\"userId\":\"sftpOcbc\",\"password\":\"sftpOcbc\",\"path\":\"/sftpOcbc/fromGuud/\",\"outpath\":\"/sftpOcbc/toGuud/\" }'
 WHERE (`BANK_ID` = 'OCBC');

-- FOR ACCOUNT INQUIRY FOR BANK KYC
DROP TABLE IF EXISTS T_CK_CT_ACCN_INQ_REQ;
CREATE TABLE `T_CK_CT_ACCN_INQ_REQ` (
  `AIR_ID` varchar(35) NOT NULL,
  `AIR_ACCN_ID` varchar(35) DEFAULT NULL COMMENT 'REFERENCE TO T_CORE_ACCN:ACCN_ID',
  `AIR_EMAIL_REQ` varchar(128) NOT NULL,
  `AIR_REMARKS` mediumtext,
  `AIR_REQ_STATE` varchar(35) DEFAULT NULL COMMENT 'PENDING | PROCESSED | QUERIED',
  `AIR_PROCESS_BY` varchar(35) DEFAULT NULL COMMENT 'REFERENCE TO T_CORE_USR:USR_UID',
  `AIR_DT_PROCESSED` datetime DEFAULT NULL,
  `AIR_STATUS` char(1) DEFAULT NULL,
  `AIR_DT_CREATE` datetime DEFAULT NULL,
  `AIR_UID_CREATE` varchar(35) DEFAULT NULL,
  `AIR_DT_LUPD` datetime DEFAULT NULL,
  `AIR_UID_LUPD` varchar(35) DEFAULT NULL,
  PRIMARY KEY (`AIR_ID`),
  KEY `FK_AIR_ACCNID_TCOREACCN_ACCNID_idx` (`AIR_ACCN_ID`),
  KEY `FK_AIR_PROCESSBY_TCOREUSR_USRUID_idx` (`AIR_PROCESS_BY`),
  CONSTRAINT `FK_AIR_ACCNID_TCOREACCN_ACCNID` FOREIGN KEY (`AIR_ACCN_ID`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_AIR_PROCESSBY_TCOREUSR_USRUID` FOREIGN KEY (`AIR_PROCESS_BY`) REFERENCES `T_CORE_USR` (`USR_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


-- new menu
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_OA_081300','CKT','','','Account Inquiry Request','Account Inquiry Request','81300','/opadmin/inquiry/accn/list',NULL,'CKT_OA_080000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM073', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_OA_081300', 'Account Inquiry Request', 'Account Inquiry Request','Account Inquiry Request','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'SP_OP_ADMIN', 'PM073', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'SP_L1', 'PM073', 'A', NOW(), 'SYS');

DROP TABLE IF EXISTS T_CK_CT_ACCN_INQ_REQ_DOCS;
CREATE TABLE `T_CK_CT_ACCN_INQ_REQ_DOCS` (
  `AIRD_ID` varchar(35) NOT NULL,
  `AIRD_AIR_ID` varchar(35) NOT NULL COMMENT 'REFERENCE TO T_CK_CT_ACCN_INQ_REQ:AIR_ID',
  `AIRD_ATT_TYPE` varchar(35) DEFAULT NULL COMMENT 'REFERENCE TO T_MST_ATT_TYPE:MATT_ID',
  `AIRD_FILENAME` varchar(256) DEFAULT NULL,
  `AIRD_DOC` varchar(1024) DEFAULT NULL COMMENT 'LOCATION OF THE FILE UPLOADED',
  `AIRD_STATUS` char(1) DEFAULT NULL,
  `AIRD_DT_CREATE` datetime DEFAULT NULL,
  `AIRD_UID_CREATE` varchar(35) DEFAULT NULL,
  `AIRD_DT_LUPD` datetime DEFAULT NULL,
  `AIRD_UID_LUPD` varchar(35) DEFAULT NULL,
  PRIMARY KEY (`AIRD_ID`),
  KEY `F_TMSTATTYPE_TYPEID_ATTTYPE_idx` (`AIRD_ATT_TYPE`),
  KEY `FK_T_CKCT_INQ_REQ_AIR_ID_idx` (`AIRD_AIR_ID`),
  CONSTRAINT `FK_T_CKCT_INQ_REQ_AIR_ID` FOREIGN KEY (`AIRD_AIR_ID`) REFERENCES `T_CK_CT_ACCN_INQ_REQ` (`AIR_ID`),
  CONSTRAINT `FK_TMSTATTYPE_MATT_ID_ATTTYPE` FOREIGN KEY (`AIRD_ATT_TYPE`) REFERENCES `T_MST_ATT_TYPE` (`MATT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


INSERT INTO `T_CORE_NOTIFICATION_TEMPLATE`(`NTPL_ID`,`NTPL_APPSCODE`,`NTPL_CHANNEL_TYPE`,`NTPL_CONTENT_TYPE`,`NTPL_SUBJECT`,`NTPL_TEMPALTE`,`NTPL_SEQ`,`NTPL_DESC`,`NTPL_STATUS`,`NTPL_UID_CREATE`,`NTPL_DT_CREATE`,`NTPL_UID_LUPD`,`NTPL_DT_LUPD`)  VALUES('CKT_NTL_0062','CKT','CHN_TYPE_EMAIL','CNT_TYPE_HTML','Re: Account Inquiry [:subject]','<html> <style> html, body{font-family: "Roboto", sans-serif;} #container {width: 800px;border: 1px solid gray;padding: 10px 20px;} .innerContainer {padding: 0px 0px;} #footerContainer {background-color: #f2f3f4;color: darkslategray;padding: 5px 15px;margin-top: 15px;} .button {width: 300px;height: 50px;background-color:steelblue;color: white;margin:50px 0px;justify-content: center;align-items: center;display: flex;} </style> <body> <div id=container> <div id=titleContainer class=innerContainer> <img width=100 height=62 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> <div id=bodyContainer class=innerContainer> <p><br></p> <p>Please find attached requested documents for the account. <p><br></p></div> <div id=footerContainer class=innerContainer> <p><a style=color:inherit href=:privacyStatementLink>Privacy Statement</a></p> <p>:sp_details</p> <img width=50 height=31 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> </div> </body> </html>','62','Notification for Account Inquiry Request','A','SYS',NOW(),'SYS',NOW());

INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_OPM_MAX_LIMIT', '35000000', 'AMOUNT MAXIMUM LIMIT FOR OPM FINANCING', '2022-11-30 00:00:00', 'SYS', '2022-11-30 00:00:00', 'SYS', 'A');


-- remove the ff_finance for manage rate table and manage chassis
DELETE FROM `clickargo2`.`T_CORE_GRANT_ROLE_EX` WHERE (`GNTRLEX_APPS_CODE` = 'CKT') and (`GNTRLEX_ROLE_ID` = 'FF_FINANCE') and (`GNTRLEX_PERM_ID` = 'PM033');
DELETE FROM `clickargo2`.`T_CORE_GRANT_ROLE_EX` WHERE (`GNTRLEX_APPS_CODE` = 'CKT') and (`GNTRLEX_ROLE_ID` = 'FF_FINANCE') and (`GNTRLEX_PERM_ID` = 'PM070');


-- ALTER CONTRACT TABLE
ALTER TABLE `clickargo2`.`T_CK_CT_CONTRACT` 
ADD COLUMN `CON_FINANCE_MODEL` VARCHAR(35) NULL COMMENT 'OPM-CO, OPM-TO, BSF' AFTER `CON_DT_END`;

ALTER TABLE `clickargo2`.`T_CK_CT_CONTRACT` 
ADD COLUMN `CON_OPM` VARCHAR(35) NULL COMMENT 'CONTRACT OPM BANK - REFERENCES T_CK_CT_CONTRACT_CHARGE:CONC_ID' AFTER `CON_PAYTERM_CO_FF`;

ALTER TABLE `clickargo2`.`T_CK_CT_CONTRACT` 
ADD COLUMN `CON_OPM_BANK` VARCHAR(35) NULL COMMENT 'OCBC' AFTER `CON_OPM`;


ALTER TABLE `clickargo2`.`T_CK_CT_CONTRACT` 
ADD CONSTRAINT  `FK_CK_CT_CONTRACT_CK_CT_CONTRACT_CHARGE3` FOREIGN KEY (`CON_OPM`) REFERENCES `T_CK_CT_CONTRACT_CHARGE` (`CONC_ID`);

ALTER TABLE `clickargo2`.`T_CK_CT_CONTRACT` 
ADD CONSTRAINT  `FK_CK_CT_CONTRACT_CK_MST_BANK` FOREIGN KEY (`CON_OPM_BANK`) REFERENCES `T_MST_BANK` (`BANK_ID`);

-- ALTER CONTRACT REQ TABLE
ALTER TABLE `clickargo2`.`T_CK_CT_CONTRACT_REQ` 
ADD COLUMN `CR_OPM_BANK` VARCHAR(35) NULL DEFAULT NULL COMMENT 'REFERENCE TO T_MST_BANK' AFTER `CR_PAYTERM_CO_FF`,
ADD COLUMN `CR_CHARGE_OPM` VARCHAR(35) NULL COMMENT 'BANK CHARGE - REFERENCES T_CK_CT_CONTRACT_REQ_CHARGE:CONC_ID' AFTER `CR_OPM_BANK`;

ALTER TABLE `clickargo2`.`T_CK_CT_CONTRACT_REQ` 
ADD INDEX `FK_CK_CT_CONTRACT_REQ_CK_CT_CONTRACT_REQ_OPM_idx` (`CR_CHARGE_OPM` ASC) VISIBLE;
;
ALTER TABLE `clickargo2`.`T_CK_CT_CONTRACT_REQ` 
ADD CONSTRAINT `FK_CK_CT_CONTRACT_REQ_CK_CT_CONTRACT_REQ_OPM`
  FOREIGN KEY (`CR_CHARGE_OPM`)
  REFERENCES `clickargo2`.`T_CK_CT_CONTRACT_CHARGE` (`CONC_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `clickargo2`.`T_CK_CT_CONTRACT_REQ` 
ADD INDEX `FK_CK_CT_CONTRACT_REQ_BANK_idx` (`CR_OPM_BANK` ASC) VISIBLE;
;
ALTER TABLE `clickargo2`.`T_CK_CT_CONTRACT_REQ` 
ADD CONSTRAINT `FK_CK_CT_CONTRACT_REQ_BANK`
  FOREIGN KEY (`CR_OPM_BANK`)
  REFERENCES `clickargo2`.`T_MST_BANK` (`BANK_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `clickargo2`.`T_CK_CT_CONTRACT_REQ` 
ADD COLUMN `CR_FINANCE_MODEL` VARCHAR(35) NULL COMMENT 'OPM-CO, OPM-TO, BSF' AFTER `CR_CHARGE_OPM`;


-- FOR CONTRRACT REQUEST
INSERT INTO `clickargo2`.`T_CK_MST_ENTITY_STATE` (`ENST_ID`, `ENST_NAME`, `ENST_DESC`, `ENST_DESC_OTH`, `ENST_STATUS`, `ENST_DT_CREATE`, `ENST_UID_CREATE`, `ENST_DT_LUPD`, `ENST_UID_LUPD`) VALUES ('EX', 'EXPORTED', 'EXPORTED', 'EXPORTED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');


INSERT INTO `T_CORE_NOTIFICATION_TEMPLATE`(`NTPL_ID`,`NTPL_APPSCODE`,`NTPL_CHANNEL_TYPE`,`NTPL_CONTENT_TYPE`,`NTPL_SUBJECT`,`NTPL_TEMPALTE`,`NTPL_SEQ`,`NTPL_DESC`,`NTPL_STATUS`,`NTPL_UID_CREATE`,`NTPL_DT_CREATE`,`NTPL_UID_LUPD`,`NTPL_DT_LUPD`)  
VALUES('CKT_NTL_0000','CKT','CHN_TYPE_EMAIL','CNT_TYPE_HTML',':subject','<html>  <body> <p>:sp_details</p> </body> </html>','0','Blank Email Template','A','SYS',NOW(),'SYS',NOW());

INSERT INTO `clickargo2`.`T_CK_CT_MST_SAGE_INT_STATE` (`SIS_ID`, `SIS_NAME`, `SIS_DESC`, `SIS_DESC_OTH`, `SIS_STATUS`, `SIS_DT_CREATE`, `SIS_UID_CREATE`) 
VALUES ('APPROVE', 'APPROVE', 'APPROVE', 'APPROVE', 'A', '2023-08-23 09:19:18', 'sys');

INSERT INTO `clickargo2`.`T_CK_CT_MST_SAGE_INT_STATE` (`SIS_ID`, `SIS_NAME`, `SIS_DESC`, `SIS_DESC_OTH`, `SIS_STATUS`, `SIS_DT_CREATE`, `SIS_UID_CREATE`) 
VALUES ('ERROR', 'ERROR', 'ERROR', 'ERROR', 'A', '2023-08-23 09:19:18', 'sys');

