
INSERT INTO `clickargo2`.`T_CORE_ACCN` (`ACCN_ID`, `ACCN_STATUS`, `ACCN_NAME`, `ACCN_TYPE`, `ACCN_COY_REGN`
, `ACCN_ADDR1`, `ACCN_PCODE`, `ACCN_CITY`, `ACCN_PROV`, `ACCN_CTYCODE`, `ACCN_TEL`, `ACCN_EMAIL`, `ACCN_DT_REG`, `ACCN_DT_CREATE`, `ACCN_UID_CREATE`) 
VALUES ('UNQ', 'A', 'UNIQLO (SINGAPORE) PTE. LTD.', 'ACC_TYPE_FF', '1'
, '1 Maritime Square, #07-02, HarbourFront Centre', '099253', 'Singapore', 'Singapore', 'SG', '+6500000000', 'test@uniqlo.com', sysdate(), sysdate(), 'GLI_U001');


INSERT INTO `clickargo2`.`T_CORE_USR` (`USR_UID`, `USR_ACCNID`, `USR_STATUS`, `USR_TYPE_ONLINE`, `USR_TYPE_MBOX`, `USR_NAME`, `USR_DT_REG`
, `USR_DT_COMM`, `USR_ADDR3`, `USR_CTYCODE`, `USR_TEL`, `USR_EMAIL`, `USR_PWD`, `USR_DT_PWD_LUPD`, `USR_LOGIN_INVCNT`, `USR_MBOX_ID`) 
VALUES ('UNQ0001', 'UNQ', 'A', 'Y', 'N', 'UNQ0001', sysdate()
, sysdate(), 'street', 'SG', '+6500000000', 'test1@uniqlo.com', '512f8e7587803a6bc4a89ed552e9f6ce'
, sysdate(), '0', '');

INSERT INTO `clickargo2`.`T_CORE_USR` (`USR_UID`, `USR_ACCNID`, `USR_STATUS`, `USR_TYPE_ONLINE`, `USR_TYPE_MBOX`, `USR_NAME`, `USR_DT_REG`
, `USR_DT_COMM`, `USR_ADDR3`, `USR_CTYCODE`, `USR_TEL`, `USR_EMAIL`, `USR_PWD`, `USR_DT_PWD_LUPD`, `USR_LOGIN_INVCNT`, `USR_MBOX_ID`) 
VALUES ('UNQ0002', 'UNQ', 'A', 'Y', 'N', 'UNQ0002', sysdate()
, sysdate(), 'street', 'SG', '+6500000000', 'test2@uniqlo.com', '512f8e7587803a6bc4a89ed552e9f6ce'
, sysdate(), '0', '');

update T_CORE_USR set USR_PWD = md5(concat(USR_UID, 'password123')) where USR_UID = 'UNQ0001';
update T_CORE_USR set USR_PWD = md5(concat(USR_UID, 'password123')) where USR_UID = 'UNQ0002';


INSERT INTO `clickargo2`.`T_CORE_USR_ROLE` (`UROL_UID`, `UROL_APPSCODE`, `UROL_ROLEID`, `UROL_ADMIN_OPT`, `UROL_STATUS`, `UROL_DT_CREATE`, `UROL_UID_CREATE`, `UROL_DT_LUPD`, `UROL_TEMP_ROLE`) 
VALUES ('UNQ0001', 'CKT', 'ADMIN', 'N', 'A', sysdate(), 'SYS', sysdate(),'N');
INSERT INTO `clickargo2`.`T_CORE_USR_ROLE` (`UROL_UID`, `UROL_APPSCODE`, `UROL_ROLEID`, `UROL_ADMIN_OPT`, `UROL_STATUS`, `UROL_DT_CREATE`, `UROL_UID_CREATE`, `UROL_DT_LUPD`,  `UROL_TEMP_ROLE`) 
VALUES ('UNQ0001', 'CKT', 'OFFICER', 'N', 'A', sysdate(), 'SYS', sysdate(),'N');

-- --------
INSERT INTO `clickargo2`.`T_CK_CT_CONTRACT_CHARGE` (`CONC_ID`, `CONC_PLTFEE_AMT`, `CONC_PLTFEE_TYPE`, `CONC_ADDTAX_AMT`, `CONC_ADDTAX_TYPE`, `CONC_WHTAX_AMT`, `CONC_WHTAX_TYPE`, `CONC_STATUS`, `CONC_DT_CREATE`, `CONC_UID_CREATE`) 
VALUES ('CRCHGSSAUNQ1', '0.00', 'P', '0.00', 'P', '0.00', 'P', 'A', sysdate(), '');
INSERT INTO `clickargo2`.`T_CK_CT_CONTRACT_CHARGE` (`CONC_ID`, `CONC_PLTFEE_AMT`, `CONC_PLTFEE_TYPE`, `CONC_ADDTAX_AMT`, `CONC_ADDTAX_TYPE`, `CONC_WHTAX_AMT`, `CONC_WHTAX_TYPE`, `CONC_STATUS`, `CONC_DT_CREATE`, `CONC_UID_CREATE`) 
VALUES ('CRCHGSSAUNQ2', '0.00', 'P', '0.00', 'P', '0.00', 'P', 'A', sysdate(), '');


INSERT INTO `clickargo2`.`T_CK_CT_CONTRACT` (`CON_ID`, `CON_NAME`, `CON_CCY`, `CON_DT_START`, `CON_DT_END`, `CON_TO`, `CON_CHARGE_TO`, `CON_PAYTERM_TO`, `CON_CO_FF`, `CON_CHARGE_CO_FF`, `CON_PAYTERM_CO_FF`, `CON_STATUS`, `CON_DT_CREATE`, `CON_UID_CREATE`)
 VALUES ('CKTCC000067', 'SSA-UNQ', 'SGD', '2024-05-01 00:00:00', '2030-12-31 00:00:00', 'SSA', 'CRCHGSSAUNQ1', '30', 'UNQ', 'CRCHGSSAUNQ2', '30', 'A', '2024-07-15 09:21:21', 'sys');
