SET SQL_SAFE_UPDATES = 0;
DELETE FROM `T_CORE_GRANT_ROLE_EX`;
SET SQL_SAFE_UPDATES = 1;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM `T_CORE_PERM_EX`;
SET SQL_SAFE_UPDATES = 1;

SET SQL_SAFE_UPDATES = 0;
SET FOREIGN_KEY_CHECKS=0;
DELETE FROM `T_CORE_MENU_EX`;
SET SQL_SAFE_UPDATES = 1;
SET FOREIGN_KEY_CHECKS=1;

INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_MA_030000','CKT','Administrations','Administrations','Administrations','Administrations','30000',NULL,'group',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_MA_030100','CKT','','','Manage Trucks','Manage Trucks','30100','/administrations/truck-management/list',NULL,'CKT_MA_030000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_MA_030200','CKT','','','Manage Drivers','Manage Drivers','30200','/administrations/driver-management/list',NULL,'CKT_MA_030000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_MA_030300','CKT','','','Manage Locations','Manage Locations','30300','/administrations/location-management/list',NULL,'CKT_MA_030000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_MA_030400','CKT','','','Manage Rentals','Manage Rentals','30400','/administrations/rental-management/list',NULL,'CKT_MA_030000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_MA_040000','CKT','Manage Contracts','Manage Contracts','Manage Contracts','Manage Contracts','40000','/administrations/contract-management/list',NULL,NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_MA_030600','CKT','','','Manage Rate Table','Manage Rate Table','30600','/administrations/rateTable-management/list',NULL,'CKT_MA_030000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_MH_080000','CKT','Help','Help','Help','Help','80000','/help',NULL,NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_MS_010000','CKT','Services','Services','Services','Services','10000','/',NULL,NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MA_030000','CK','Administrations','Administrations','Administrations','Administrations','30000',NULL,'group',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MA_030100','CK','','','Account Profile','Account Profile','30100','/accountProfile',NULL,'CK_MA_030000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MA_030200','CK','','','Users','Users','30200','/accountUsers',NULL,'CK_MA_030000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MA_030300','CK','','','Authorisations','Authorisations','30400','/accountAuthorisations',NULL,'CK_MA_030000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MP_020000','CK','DO Payments','DO Payments','DO Payments','DO Payments','20000',NULL,'payment',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MP_020100','CK','Payments','Payments','Payments','Payments','20100','/payments/active/list',NULL,'CK_MP_020000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MP_020300','CK','Transactions','Transactions','Transactions','Transactions','20300','/payments/transactions/list',NULL,'CK_MP_020000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MP_040000','CK','Payments','Payments','Payments','Payments','40000','/applications/payments/do/sl','payment',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MP_070000','CK','Payments','Payments','Payments','Payments','70000','/applications/payments/viewPaymentHistory','receipt',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MSA_060000','CK','System Administrations','System Administrations','System Administrations','System Administrations','60000',NULL,'settings',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MSA_060100','CK','','','Announcement Setup','Announcement Setup','60100','/configuration/announcement/list',NULL,'CK_MSA_060000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MSA_060200','CK','','','Notification Preferences','Notification Preferences','60200','/configuration/notification/preferences/list',NULL,'CK_MSA_060000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MSA_060300','CK','','','System Parameters','System Parameters','60300','/administrations/sysparam/list',NULL,'CK_MSA_060000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MSA_060400','CK','','','Audit Logs','Audit Logs','60400','/administrations/audit/list',NULL,'CK_MSA_060000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MSA_060500','CK','','','Exceptions','Exceptions','60500','/administrations/exception/list',NULL,'CK_MSA_060000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MSA_060600','CK','','','Manage All Users','Manage All Users','60600','/manageUsers/users/all/list',NULL,'CK_MSA_060000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MSA_060700','CK','','','Manage All Accounts','Manage All Accounts','60700','/manageAccounts/all/list',NULL,'CK_MSA_060000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MS_010000','CK','DO Claim','DO Claim','DO Claim','DO Claim','10000','/','grid_view',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MS_020000','CK','Documents','Documents','Documents','Documents','20000','/','content_copy',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MT_050000','CK','Master Table','Master Table','Master Table','Master Table','50000',NULL,'table_view',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MT_050100','CK','','','Announcement Type','Announcement Type','50100','/configuration/announcementType/list',NULL,'CK_MT_050000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MT_050200','CK','','','Country Codes','Country Codes','50200','/master/country/list',NULL,'CK_MT_050000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MT_050300','CK','','','Currency Code','Currency Code','50300','/master/currency/list',NULL,'CK_MT_050000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MT_050400','CK','','','Harmonized System Codes','Harmonized System Codes','50400','/master/hsCode/list',NULL,'CK_MT_050000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MT_050500','CK','','','Notification Templates','Notification Templates','50500','/notification/templates/list',NULL,'CK_MT_050000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MT_050600','CK','','','Port Codes','Port Codes','50600','/master/port/list',NULL,'CK_MT_050000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MT_050700','CK','','','Port Terminal','Port Terminal','50700','/master/portTerminal/list',NULL,'CK_MT_050000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MT_050800','CK','','','UOM Codes','UOM Codes','50800','/master/uom/list',NULL,'CK_MT_050000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CK_MZH_080000','CK','Help','Help','Help','Help','80000','/help','help_outline',NULL,'A',NOW(),'SYS',NOW(),'SYS');

INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM000', 'Y', 'CK', NULL, 'M', NULL, NULL, 'CK_MS_010000', 'Services', 'Services','Services','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM001', 'Y', 'CK', NULL, 'M', NULL, NULL, 'CK_MP_020000', 'Payments', 'Payments','Payments','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM002', 'Y', 'CK', NULL, 'M', NULL, NULL, 'CK_MA_030000', 'Administrations', 'Administrations','Administrations','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM003', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MA_030100', 'Account Profile', 'Account Profile','Account Profile','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM004', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MA_030200', 'Users', 'Users','Users','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM005', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MA_030300', 'Authorisations', 'Authorisations','Authorisations','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM007', 'Y', 'CK', NULL, 'M', NULL, NULL, 'CK_MT_050000', 'Master Table', 'Master Table','Master Table','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM008', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MT_050100', 'Announcement Type', 'Announcement Type','Announcement Type','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM009', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MT_050200', 'Country Codes', 'Country Codes','Country Codes','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM010', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MT_050300', 'Currency Code', 'Currency Code','Currency Code','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM011', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MT_050400', 'Harmonized System Codes', 'Harmonized System Codes','Harmonized System Codes','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM012', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MT_050500', 'Notification Templates', 'Notification Templates','Notification Templates','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM013', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MT_050600', 'Port Codes', 'Port Codes','Port Codes','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM014', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MT_050700', 'Port Terminal', 'Port Terminal','Port Terminal','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM015', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MT_050800', 'UOM Codes', 'UOM Codes','UOM Codes','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM016', 'Y', 'CK', NULL, 'M', NULL, NULL, 'CK_MSA_060000', 'System Administrations', 'System Administrations','System Administrations','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM017', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MSA_060100', 'Announcement Setup', 'Announcement Setup','Announcement Setup','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM018', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MSA_060200', 'Notification Preferences', 'Notification Preferences','Notification Preferences','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM019', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MSA_060300', 'System Parameters', 'System Parameters','System Parameters','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM020', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MSA_060400', 'Audit Logs', 'Audit Logs','Audit Logs','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM021', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MSA_060500', 'Exceptions', 'Exceptions','Exceptions','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM022', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MSA_060600', 'Manage All Users', 'Manage All Users','Manage All Users','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM023', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MSA_060700', 'Manage All Accounts', 'Manage All Accounts','Manage All Accounts','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM024', 'Y', 'CK', NULL, 'M', NULL, NULL, 'CK_MS_020000', 'Documents', 'Documents','Documents','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM025', 'Y', 'CK', NULL, 'M', NULL, NULL, 'CK_MP_020300', 'Transactions', 'Transactions','Payments','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM026', 'N', 'CK', NULL, 'M', NULL, NULL, 'CK_MZH_080000', 'Help', 'Help','Help','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM027', 'Y', 'CK', NULL, 'M', NULL, NULL, 'CK_MP_040000', 'Payments', 'Transactions','Payments','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM028', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_MS_010000', 'Services', 'Services','Services','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM029', 'Y', 'CKT', NULL, 'M', NULL, NULL, 'CKT_MA_030000', 'Administrations', 'Administrations','Administrations','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM030', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_MA_030100', 'Manage Trucks', 'Manage Trucks','Manage Trucks','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM031', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_MA_030200', 'Manage Drivers', 'Manage Drivers','Manage Drivers','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM032', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_MA_030300', 'Manage Locations', 'Manage Locations','Manage Locations','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM033', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_MA_030400', 'Manage Rentals', 'Manage Rentals','Manage Rentals','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM034', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_MA_040000', 'Manage Contracts', 'Manage Contracts','Manage Contracts','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM035', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_MH_080000', 'Help', 'Help','Help','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM036', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_MA_030600', 'Manage Rate Table', 'Manage Rate Table','Manage Rate Table','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');

INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'ADMIN', 'PM002', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'ADMIN', 'PM003', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'ADMIN', 'PM004', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'ADMIN', 'PM005', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'ADMIN', 'PM007', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'FINANCE', 'PM026', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'FINANCE', 'PM027', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'OFFICER', 'PM000', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'OFFICER', 'PM026', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'OFFICER_FINANCE', 'PM001', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'OFFICER_FINANCE', 'PM025', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'OPERATIONS', 'PM024', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'OPERATIONS', 'PM026', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM008', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM009', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM010', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM011', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM012', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM013', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM014', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM015', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM016', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM017', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM018', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM019', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM020', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM021', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM022', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CK', 'SYS_SUPER_ADMIN', 'PM023', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'ADMIN', 'PM028', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'ADMIN', 'PM029', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'ADMIN', 'PM030', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'ADMIN', 'PM031', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'ADMIN', 'PM032', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'ADMIN', 'PM033', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'ADMIN', 'PM034', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'ADMIN', 'PM035', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'ADMIN', 'PM036', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'FF_FINANCE', 'PM028', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'FF_FINANCE', 'PM035', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'OFFICER', 'PM028', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'OFFICER', 'PM035', 'A', NOW(), 'SYS');

-- user for GLI --
INSERT INTO `T_CORE_USR` (`USR_UID`, `USR_ACCNID`, `USR_STATUS`, `USR_TYPE_ONLINE`, `USR_TYPE_MBOX`, `USR_NAME`, `USR_PASS_NID`, `USR_TITLE`, `USR_DEPT`, `USR_DT_REG`, `USR_DT_COMM`, `USR_ADDR1`, `USR_ADDR2`, `USR_ADDR3`, `USR_PCODE`, `USR_CITY`, `USR_PROV`, `USR_CTYCODE`, `USR_TEL`, `USR_FAX`, `USR_EMAIL`, `USR_PWD`, `USR_PWD_1`, `USR_PWD_2`, `USR_PWD_3`, `USR_PWD_4`, `USR_DT_PWD_LUPD`, `USR_PWD_FORCE`, `USR_LOGIN_INVCNT`, `USR_DT_LOGINOK`, `USR_DT_LOGINERR`, `USR_MBOX_ID`, `USR_DT_CREATE`, `USR_UID_CREATE`, `USR_DT_LUPD`, `USR_UID_LUPD`) VALUES ('GLI_U001', 'GLI', 'A', 'Y', 'N', 'GLI Admin', '888888888', 'Officer', 'OP', '2022-10-01 00:00:00', '2022-10-01 00:00:00', 'Wisma Keiai 12A Floor', 'l.Jendral Sudirman Kav. 3', 'Jakarta 10220', '10220', 'Jakarta', '', 'ID', '622476928448', '', 'agung.dwijayanto@guud.company', '506deab161da9d9c64fc22b0a1796ecc', '', '', '', '', '2023-12-01 00:00:00', '', '0', '2022-10-01 00:00:00', '2022-10-01 00:00:00', '', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'SYS');
INSERT INTO `T_CORE_USR_ROLE` (`UROL_UID`, `UROL_APPSCODE`, `UROL_ROLEID`, `UROL_ADMIN_OPT`, `UROL_STATUS`, `UROL_DT_CREATE`, `UROL_UID_CREATE`, `UROL_DT_LUPD`, `UROL_UID_LUPD`, `UROL_TEMP_ROLE`) VALUES ('GLI_U001', 'CKT', 'ADMIN', 'N', 'A', '2022-11-15 09:10:07', 'SYS', '2022-11-15 09:10:07', 'SYS', 'N');


-- FOR STORING SEQUENCE NOS TO BE USED LATER --- 
DROP TABLE IF EXISTS T_CK_SEQUENCE_NO;
CREATE TABLE `T_CK_SEQUENCE_NO` (
  `SQN_ID` VARCHAR(35) NOT NULL,
  `SQN_DESC` VARCHAR(255) NULL,
  `SQN_KEY` VARCHAR(35) NULL,
  `SQN_SEQ` INT NULL,
  `SQN_DT_CREATE` DATETIME NULL,
  `SQN_UID_CREATE` VARCHAR(35) NULL,
  `SQN_DT_LUPD` DATETIME NULL,
  `SQN_UID_LUPD` VARCHAR(35) NULL,
  PRIMARY KEY (`SQN_ID`));


INSERT INTO `T_CK_SEQUENCE_NO` (`SQN_ID`, `SQN_DESC`, `SQN_KEY`, `SQN_SEQ`, `SQN_DT_CREATE`, `SQN_UID_CREATE`, `SQN_DT_LUPD`, `SQN_UID_LUPD`) VALUES ('CT_PF_INV_NO', 'PLATFORM FEE SEQ. NO', 'CLICTRUCK-YYYYMMDD-%05d', '1', '2023-06-03 03:47:51', 'SYS', '2023-06-03 03:47:51', 'SYS');
INSERT INTO `T_CK_SEQUENCE_NO` (`SQN_ID`, `SQN_DESC`, `SQN_KEY`, `SQN_SEQ`, `SQN_DT_CREATE`, `SQN_UID_CREATE`, `SQN_DT_LUPD`, `SQN_UID_LUPD`) VALUES ('CT_DN_NO', 'DEBIT NOTE SEQ. NO', 'CLICTRUCK-YYYYMMDD-%05d', '5', '2023-06-03 03:47:51', 'SYS', '2023-06-03 03:47:51', 'SYS');


ALTER TABLE `T_CK_JOB_TRUCK` 
ADD COLUMN `JOB_TOTAL_PLATFORM_FEES` DECIMAL(15,2) NULL AFTER `JOB_TOTAL_REIMBURSEMENTS`;

ALTER TABLE `T_CK_CT_DEBIT_NOTE` 
ADD COLUMN `DN_DT_DUE` DATETIME NULL DEFAULT NULL COMMENT 'DEBIT NOTE DATE' AFTER `DN_DT_ISSUE`,
ADD COLUMN `DN_NAME` VARCHAR(256) NULL DEFAULT NULL COMMENT 'DEBIT NOTE FILE NAME' AFTER `DN_TO`,
ADD COLUMN `DN_LOC` VARCHAR(1024) NULL DEFAULT NULL COMMENT 'DEBIT NOTE PATH' AFTER `DN_NAME`;

ALTER TABLE `T_CK_CT_DEBIT_NOTE` 
ADD COLUMN `DN_AMOUNT` DECIMAL(15,2) NULL AFTER `DN_AGE_BAND`;

CREATE TABLE `T_CK_CT_PLATFORM_INVOICE` (
  `INV_ID` varchar(35) NOT NULL COMMENT 'INVOICE ID - UUID',
  `INV_STATE` varchar(35) NOT NULL COMMENT 'INVOICE STATE - REFERENCES T_CK_CT_MST_TO_INVOICE_STATE:INST_ID',
  `INV_JOB_ID` varchar(35) DEFAULT NULL COMMENT 'JOB ID - NO REFERENCE HERE JUST FOR QUICK JOINT',
  `INV_TRIP` varchar(35) DEFAULT NULL COMMENT 'TRIP INVOICE - REFERENCE T_CK_CT_TRIP:TR_ID',
  `INV_NO` varchar(256) NOT NULL COMMENT 'INVOICE NUMBER - PROVIDED BY TO',
  `INV_DT_ISSUE` datetime DEFAULT NULL COMMENT 'INVOICE ISSUE DATE',
  `INV_DT_DUE` datetime DEFAULT NULL COMMENT 'INVOICE DUE DATE',
  `INV_FROM` varchar(35) DEFAULT NULL COMMENT 'INVOICE FROM - REFERENCES T_CORE_ACCN:ACCN_ID',
  `INV_TO` varchar(35) DEFAULT NULL COMMENT 'INVOICE TO - REFERENCES T_CORE_ACCN:ACCN_ID',
  `INV_NAME` varchar(256) DEFAULT NULL COMMENT 'INVOICE FILE NAME',
  `INV_LOC` varchar(1024) DEFAULT NULL COMMENT 'INVOICE PATH AS ZIP FILE IF THERE ARE MUTLIPLE INVOICES REFERENCE FROM SYS_PARAM SETUP',
  `INV_INVOCIER_COMMENT` mediumtext COMMENT 'COMMENTS BY INVOICER',
  `INV_INVOCIEE_REMARKS` mediumtext COMMENT 'REMARKS BY INVOICEE',
  `INV_STATUS` char(1) DEFAULT NULL COMMENT 'REIMBURSEMENT STATUS',
  `INV_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `INV_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `INV_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `INV_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`INV_ID`),
  CONSTRAINT `FK_CK_CT_PLATFORM_INVOICE_CK_CT_MST_TO_INVOICE_STATE` FOREIGN KEY (`INV_STATE`) REFERENCES `T_CK_CT_MST_TO_INVOICE_STATE` (`INST_ID`),
  CONSTRAINT `FK_CK_CT_PLATFORM_INVOICE_CK_CT_TRIP` FOREIGN KEY (`INV_TRIP`) REFERENCES `T_CK_CT_TRIP` (`TR_ID`),
  CONSTRAINT `FK_CK_CT_PLATFORM_INVOICE_CORE_ACCN1` FOREIGN KEY (`INV_FROM`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_CT_PLATFORM_INVOICE_CORE_ACCN2` FOREIGN KEY (`INV_TO`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='PLATFORM FEE INVOICE TABLE';


ALTER TABLE `T_CK_CT_PLATFORM_INVOICE` 
ADD COLUMN `INV_AMOUNT` DECIMAL(15,2) NULL AFTER `INV_NO`;

ALTER TABLE `T_CK_PAYMENT_AUDIT` 
CHANGE COLUMN `PYA_STATE` `PYA_STATE` VARCHAR(35) NULL DEFAULT NULL ;


ALTER TABLE `T_CK_CT_LOCATION` 
ADD COLUMN `LOC_LATITUDE` VARCHAR(1024) NULL AFTER `LOC_REMARKS`,
ADD COLUMN `LOC_LONGITUDE` VARCHAR(1024) NULL AFTER `LOC_LATITUDE`;

-- 2023-June-05 Above script executed in Dev Server --- 

-- for clictruck callback to pass to clicpay
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_IN_PAYMENT_CALLBACK_URL', 'http://clicdo.vcargocloud.com/be/clictruck/api/v1/clickargo/clictruck/payment/paid', 'Callback for Clicpay to inform Clictruck that paid has been made', '2022-11-30 00:00:00', 'SYS', '2022-11-30 00:00:00', 'SYS', 'A');

-- Executed in Dev above this line --

-- 2023-June-06
ALTER TABLE `T_CK_CT_LOCATION` 
ADD COLUMN `LOC_GPS` VARCHAR(1024) NULL DEFAULT NULL AFTER `LOC_ADDRESS`;

ALTER TABLE `T_CK_CT_CONTRACT` 
ADD COLUMN `CON_PAYTERM_TO` INT NULL AFTER `CON_CHARGE_TO`,
ADD COLUMN `CON_PAYTERM_CO_FF` INT NULL AFTER `CON_CHARGE_CO_FF`;

-- 2023-June-07 Jasper file location 
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_JRXML_BASE_PATH', '/home/vcc/jasper/', 'Base location for jasper', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_JRXML_DEBIT_NOTE_PATH', 'docs/DebitNote.jrxml', 'Debit note jrxml file', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES('CLICTRUCK_JRXML_INVOICE_PATH', 'docs/InvoiceClictruck.jrxml', 'Proforma Invoice', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

-- 2023-June-08 Clictruck Attachment
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES('KEY_CLICTRUCK_ATTCH_BASE_LOCATION', '/home/vcc/appAttachments/clictruck/', 'Base location for the attachments', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

-- 2023-June-09 
-- INSERT INTO `T_CORE_ACCN_CONFIG` (`ACFG_ACCNID`, `ACFG_KEY`, `ACFG_VAL`, `ACFG_DESC`, `ACFG_VALID_FROM_DT`, `ACFG_VALID_TO_DT`, `ACFG_SEQ`, `ACFG_STATUS`, `ACFG_DT_CREATE`, `ACFG_UID_CREATE`, `ACFG_DT_LUPD`, `ACFG_UID_LUPD`) VALUES ('GLI', 'SP2TO_VA_IDR', '9100230215102227', 'TO Payee Account (IDR)', '2022-12-01 00:00:00', '2024-11-30 23:59:59', '1', 'A', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'SYS');
-- INSERT INTO `T_CORE_ACCN_CONFIG` (`ACFG_ACCNID`, `ACFG_KEY`, `ACFG_VAL`, `ACFG_DESC`, `ACFG_VALID_FROM_DT`, `ACFG_VALID_TO_DT`, `ACFG_SEQ`, `ACFG_STATUS`, `ACFG_DT_CREATE`, `ACFG_UID_CREATE`, `ACFG_DT_LUPD`, `ACFG_UID_LUPD`) VALUES ('BERAM', 'BANK_DETAILS', 'DNO:000067950337', 'TO Merchant Bank ', '2022-12-01 00:00:00', '2024-11-30 23:59:59', '1', 'A', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'SYS');


ALTER TABLE `T_CK_JOB_TRUCK` 
ADD COLUMN `JOB_VEH_OTH` VARCHAR(512) NULL DEFAULT NULL AFTER `JOB_VEH`,
ADD COLUMN `JOB_DRV_OTH` VARCHAR(512) NULL DEFAULT NULL AFTER `JOB_DRV`;

INSERT INTO `T_CK_MST_ENTITY_TYPE` (`ENTY_ID`, `ENTY_NAME`, `ENTY_DESC`, `ENTY_DESC_OTH`, `ENTY_STATUS`, `ENTY_DT_CREATE`, `ENTY_UID_CREATE`, `ENTY_DT_LUPD`, `ENTY_UID_LUPD`) VALUES ('JOB_TRUCK_OUT_PAY', 'TRUCK Job Payment', 'TRUCK Job Payment', 'TRUCK Job Payment', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');

INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','FINANCE_VERIFIER','A','FINANCE VERIFIER',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','FINANCE_APPROVER','A','FINANCE VERIFIER',NOW(),'SYS',NOW(),'SYS');

INSERT INTO `T_CORE_USR` (`USR_UID`, `USR_ACCNID`, `USR_STATUS`, `USR_TYPE_ONLINE`, `USR_TYPE_MBOX`, `USR_NAME`, `USR_PASS_NID`, `USR_TITLE`, `USR_DEPT`, `USR_DT_REG`, `USR_DT_COMM`, `USR_ADDR1`, `USR_ADDR2`, `USR_ADDR3`, `USR_PCODE`, `USR_CITY`, `USR_PROV`, `USR_CTYCODE`, `USR_TEL`, `USR_FAX`, `USR_EMAIL`, `USR_PWD`, `USR_PWD_1`, `USR_PWD_2`, `USR_PWD_3`, `USR_PWD_4`, `USR_DT_PWD_LUPD`, `USR_PWD_FORCE`, `USR_LOGIN_INVCNT`, `USR_DT_LOGINOK`, `USR_DT_LOGINERR`, `USR_MBOX_ID`, `USR_DT_CREATE`, `USR_UID_CREATE`, `USR_DT_LUPD`, `USR_UID_LUPD`) VALUES ('GLI_U00VER', 'GLI', 'A', 'Y', 'N', 'GLI FINANCE VERIFIER', '888888888', 'Officer', 'OP', '2022-10-01 00:00:00', '2022-10-01 00:00:00', 'Wisma Keiai 12A Floor', 'l.Jendral Sudirman Kav. 3', 'Jakarta 10220', '10220', 'Jakarta', '', 'ID', '622476928448', '', 'agung.dwijayanto@guud.company', '2e162e9548ab5606c39e331b49eb153f', '', '', '', '', '2023-12-01 00:00:00', '', '0', '2022-10-01 00:00:00', '2022-10-01 00:00:00', '', '2022-10-01 00:00:00', 'SYS', '2023-06-09 10:51:37', 'SYS');
INSERT INTO `T_CORE_USR` (`USR_UID`, `USR_ACCNID`, `USR_STATUS`, `USR_TYPE_ONLINE`, `USR_TYPE_MBOX`, `USR_NAME`, `USR_PASS_NID`, `USR_TITLE`, `USR_DEPT`, `USR_DT_REG`, `USR_DT_COMM`, `USR_ADDR1`, `USR_ADDR2`, `USR_ADDR3`, `USR_PCODE`, `USR_CITY`, `USR_PROV`, `USR_CTYCODE`, `USR_TEL`, `USR_FAX`, `USR_EMAIL`, `USR_PWD`, `USR_PWD_1`, `USR_PWD_2`, `USR_PWD_3`, `USR_PWD_4`, `USR_DT_PWD_LUPD`, `USR_PWD_FORCE`, `USR_LOGIN_INVCNT`, `USR_DT_LOGINOK`, `USR_DT_LOGINERR`, `USR_MBOX_ID`, `USR_DT_CREATE`, `USR_UID_CREATE`, `USR_DT_LUPD`, `USR_UID_LUPD`) VALUES ('GLI_U00APP', 'GLI', 'A', 'Y', 'N', 'GLI FINANCE VERIFIER', '888888888', 'Officer', 'OP', '2022-10-01 00:00:00', '2022-10-01 00:00:00', 'Wisma Keiai 12A Floor', 'l.Jendral Sudirman Kav. 3', 'Jakarta 10220', '10220', 'Jakarta', '', 'ID', '622476928448', '', 'agung.dwijayanto@guud.company', '8a4df2e0f3a2b905cceb0bf2d238b9cd', '', '', '', '', '2023-12-01 00:00:00', '', '0', '2022-10-01 00:00:00', '2022-10-01 00:00:00', '', '2022-10-01 00:00:00', 'SYS', '2023-06-09 10:51:37', 'SYS');

INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','FINANCE_VERIFIER','A','FINANCE VERIFIER',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','FINANCE_APPROVER','A','FINANCE VERIFIER',NOW(),'SYS',NOW(),'SYS');


INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'FINANCE_VERIFIER', 'PM028', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'FINANCE_VERIFIER', 'PM035', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'FINANCE_APPROVER', 'PM028', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'FINANCE_APPROVER', 'PM035', 'A', NOW(), 'SYS');

INSERT INTO `T_CK_MST_PAYMENT_AUDIT_TYPE` (`PATY_ID`, `PYT_NAME`, `PYT_DESC`, `PYT_DESC_OTH`, `PYT_STATUS`, `PYT_DT_CREATE`, `PYT_UID_CREATE`, `PYT_DT_LUPD`, `PYT_UID_LUPD`) VALUES ('CP_REQ', 'CANCEL PAYMENT REQUEST', 'CANCEL PAYMENT REQUEST', 'CANCEL PAYMENT REQUEST', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');


-- 2023-June-11 changes to platform invoice and debit note tables --- 
ALTER TABLE `T_CK_CT_PLATFORM_INVOICE` 
DROP COLUMN `INV_AMOUNT`;

ALTER TABLE `T_CK_CT_PLATFORM_INVOICE` 
ADD COLUMN `INV_AMT` DECIMAL(15,2) NULL DEFAULT 0.0 AFTER `INV_TO`,
ADD COLUMN `INV_VAT` DECIMAL(15,2) NULL DEFAULT 0.0 AFTER `INV_AMT`,
ADD COLUMN `INV_STAMP_DUTY` DECIMAL(15,2) NULL DEFAULT 0.0 AFTER `INV_VAT`,
ADD COLUMN `INV_TOTAL` DECIMAL(15,2) NULL DEFAULT 0.0 AFTER `INV_STAMP_DUTY`;

ALTER TABLE `T_CK_CT_DEBIT_NOTE` 
DROP COLUMN `DN_AMOUNT`;


ALTER TABLE `T_CK_CT_DEBIT_NOTE` 
ADD COLUMN `DN_AMT` DECIMAL(15,2) NULL DEFAULT 0.0 AFTER `DN_TO`,
ADD COLUMN `DN_VAT` DECIMAL(15,2) NULL DEFAULT 0.0 AFTER `DN_AMT`,
ADD COLUMN `DN_STAMP_DUTY` DECIMAL(15,2) NULL DEFAULT 0.0 AFTER `DN_VAT`,
ADD COLUMN `DN_TOTAL` DECIMAL(15,2) NULL DEFAULT 0.0 AFTER `DN_STAMP_DUTY`;


CREATE TABLE `T_CK_CT_PLATFORM_INVOICE_ITEM` (
  `ITM_ID` varchar(35) NOT NULL COMMENT 'INVOICE ITEM ID - UUID',
  `ITM_INVOICE` varchar(35) DEFAULT NULL COMMENT 'PLATFORM INVOICE REFERENCES - T_CK_CT_PLATFORM_INVOICE:INV_ID',
  `ITM_SNO` smallint COMMENT 'SEQUENCE NUMBER OF THE ITEM - 1,2,3',  
  `ITM_ITEM` mediumtext COMMENT 'DESCRIPTION OF THE ITEM IN INVOICE',
  `ITM_QTY` smallint DEFAULT '0' COMMENT 'QTY OF THE ITEM IN INVOICE',
  `ITM_CCY` varchar(3) DEFAULT NULL COMMENT 'CURRENCY OF THE PAYMENT - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `ITM_UNIT_PRICE` decimal(15,2) DEFAULT '0.00' COMMENT 'UNIT PRICE OF THE ITEM',
  `ITM_AMOUNT` decimal(15,2) DEFAULT '0.00' COMMENT 'AMOUNT TO BE ITEM TO BE PAID',
  `ITM_REF` mediumtext COMMENT 'REFERENCES FOR ITEM TO BE PAID - JOB NUMBER : TRIP NUMBER',
  `ITM_STATUS` char(1) DEFAULT NULL COMMENT 'PAYMENT RECORD AUDIT TYPE STATUS',
  `ITM_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `ITM_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `ITM_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `ITM_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`ITM_ID`),
  CONSTRAINT `FK_CK_CT_PLATFORM_INVOICE_ITEM_CK_CT_PLATFORM_INVOICE` FOREIGN KEY (`ITM_INVOICE`) REFERENCES `T_CK_CT_PLATFORM_INVOICE` (`INV_ID`),
  CONSTRAINT `FK_CK_CT_PLATFORM_INVOICE_ITEM_MST_CURRENCY` FOREIGN KEY (`ITM_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='PLATFORM INVOICE ITEM';



CREATE TABLE `T_CK_CT_DEBIT_NOTE_ITEM` (
  `ITM_ID` varchar(35) NOT NULL COMMENT 'INVOICE ITEM ID - UUID',
  `ITM_DEBIT_NOTE` varchar(35) DEFAULT NULL COMMENT 'DEBIT NOTE REFERENCES - T_CK_CT_DEBIT_NOTE:DN_ID',
  `ITM_SNO` smallint COMMENT 'SEQUENCE NUMBER OF THE ITEM - 1,2,3',  
  `ITM_ITEM` mediumtext COMMENT 'DESCRIPTION OF THE ITEM IN INVOICE',
  `ITM_QTY` smallint DEFAULT '0' COMMENT 'QTY OF THE ITEM IN INVOICE',
  `ITM_CCY` varchar(3) DEFAULT NULL COMMENT 'CURRENCY OF THE PAYMENT - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `ITM_UNIT_PRICE` decimal(15,2) DEFAULT '0.00' COMMENT 'UNIT PRICE OF THE ITEM',
  `ITM_AMOUNT` decimal(15,2) DEFAULT '0.00' COMMENT 'AMOUNT TO BE ITEM TO BE PAID',
  `ITM_REF` mediumtext COMMENT 'REFERENCES FOR ITEM TO BE PAID - JOB NUMBER : TRIP NUMBER',
  `ITM_STATUS` char(1) DEFAULT NULL COMMENT 'PAYMENT RECORD AUDIT TYPE STATUS',
  `ITM_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `ITM_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `ITM_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `ITM_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`ITM_ID`),
  CONSTRAINT `FK_CK_CT_DEBIT_NOTE_ITEM_CK_CT_DEBIT_NOTE` FOREIGN KEY (`ITM_DEBIT_NOTE`) REFERENCES `T_CK_CT_DEBIT_NOTE` (`DN_ID`),
  CONSTRAINT `FK_CK_CT_DEBIT_NOTE_ITEM_MST_CURRENCY` FOREIGN KEY (`ITM_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DEBIT NOTE ITEM';



INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_VAT_PERCENTAGE', '0.11', 'VAT PERCENTAGE', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_STAMP_DUTY_LIMIT', '5000000', 'LIMIT AMOUNT TO CHARGE STAMP DUTY ', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_STAMP_DUTY_VALUE', '10000', 'STAMP DUTY VALUE IF INV AMOUNT IS GREATER THAN THE LIMIT AMOUNT', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_DEFAULT_CURRENCY', 'IDR', 'Default currency for Clictruck', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

CREATE TABLE `T_CK_JOB_REJECT` (
  `JOBR_ID` varchar(35) NOT NULL,
  `JOBR_JOB` varchar(35) DEFAULT NULL COMMENT 'REFERENCE TO JOB',
  `JOBR_SEQ` int DEFAULT NULL,
  `JOBR_UID_REJECT` varchar(35) DEFAULT NULL COMMENT 'REFERENCE TO USERID THAT DID THE REJECTION',
  `JOBR_DT_REJECT` datetime DEFAULT NULL,
  `JOBR_REASON` mediumtext,
  PRIMARY KEY (`JOBR_ID`),
  KEY `FK_CK_JOB_REJECT_CK_JOB_idx` (`JOBR_JOB`),
  CONSTRAINT `FK_CK_JOB_REJECT_CK_JOB_idx` FOREIGN KEY (`JOBR_JOB`) REFERENCES `T_CK_JOB` (`JOB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


ALTER TABLE `T_CK_CT_TO_INVOICE` 
CHANGE COLUMN `INV_NO` `INV_NO` VARCHAR(256) NULL COMMENT 'INVOICE NUMBER - PROVIDED BY TO' ;


UPDATE `T_CORE_SYSPARAM` SET `SYS_VAL` = 'http://ct2-uat.vcargocloud.com/be/clictruck/api/v1/clickargo/clictruck/payment/paid' WHERE (`SYS_KEY` = 'CLICTRUCK_IN_PAYMENT_CALLBACK_URL');

UPDATE `T_CORE_SYSPARAM` SET `SYS_VAL` = 'docs/InvoiceClictruck.jrxml' WHERE (`SYS_KEY` = 'CLICTRUCK_JRXML_INVOICE_PATH');

UPDATE `T_CK_SEQUENCE_NO` SET `SQN_KEY` = 'CT-DN-YYYYMMDD-%05d' WHERE (`SQN_ID` = 'CT_DN_NO');
UPDATE `T_CK_SEQUENCE_NO` SET `SQN_KEY` = 'CT-PF-YYYYMMDD-%05d' WHERE (`SQN_ID` = 'CT_PF_INV_NO');

INSERT INTO `T_CK_MST_ENTITY_STATE` (`ENST_ID`, `ENST_NAME`, `ENST_DESC`, `ENST_DESC_OTH`, `ENST_STATUS`, `ENST_DT_CREATE`, `ENST_UID_CREATE`, `ENST_DT_LUPD`, `ENST_UID_LUPD`) VALUES ('FAIL', 'FAILED', 'FAILED', 'FAILED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_DEFAULT_PAYTERMS_TO', '5', 'No. of days that GLI need to pay to Trucking Operator from the DN issue date', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

-- 16 June 2023 New menu for Account Profile for Admin - 

INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_AA_050000','CKT','Account Administration','Account Administration','Account Administration','Account Administration','50000',NULL,'group',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_AA_050100','CKT','','','Account Profile','Account Profile','50100','/account/profile',NULL,'CKT_AA_050000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_AA_050200','CKT','','','Manage Users','Manage Users','50200','/account/users',NULL,'CKT_AA_050000','A',NOW(),'SYS',NOW(),'SYS');

INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM037', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_AA_050000', 'Account Administration', 'Account Administration','Account Administration','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM038', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_AA_050100', 'Account Profile', 'Account Profile','Account Profile','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM039', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_AA_050200', 'Manage Users', 'Manage Users','Manage Users','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');

INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'ADMIN', 'PM037', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'ADMIN', 'PM038', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'ADMIN', 'PM039', 'A', NOW(), 'SYS');

INSERT INTO `T_CORE_USR_ROLE` (`UROL_UID`, `UROL_APPSCODE`, `UROL_ROLEID`, `UROL_ADMIN_OPT`, `UROL_STATUS`, `UROL_DT_CREATE`, `UROL_UID_CREATE`, `UROL_DT_LUPD`, `UROL_UID_LUPD`, `UROL_TEMP_ROLE`) VALUES ('ALKNAR_U001', 'CKT', 'ADMIN', 'N', 'A', '2022-11-15 09:10:07', 'SYS', '2022-11-15 09:10:07', 'SYS', 'N');



INSERT INTO `T_CK_SEQUENCE_NO` (`SQN_ID`, `SQN_DESC`, `SQN_KEY`, `SQN_SEQ`, `SQN_DT_CREATE`, `SQN_UID_CREATE`) 
VALUES ('CT_SAGE_BATCH_NO', 'CT_SAGE_BATCH_NO', '%04d', '1', '2023-06-03 03:47:51', 'SYS');


CREATE TABLE T_CK_CT_SAGE (
  `SAGE_ID` varchar(35) NOT NULL COMMENT 'ID, RANDOM STRING',
  `SAGE_BATCH_NO` varchar(35) NOT NULL COMMENT 'SAGE EXCEL FILE BATCH NO.',
  `SAGE_FILE_LOC` varchar(1024) NOT NULL COMMENT 'EXCEL FILE PATH',
  `SAGE_DT_START` datetime NOT NULL COMMENT 'DATA',
  `SAGE_DT_END` datetime NOT NULL COMMENT 'SAGE EXCEL FILE BATCH NO.',
  `SAGE_STATUS` char(1) DEFAULT NULL,
  `SAGE_DT_CREATE` datetime DEFAULT NULL,
  `SAGE_UID_CREATE` varchar(35) DEFAULT NULL,
  `SAGE_DT_LUPD` datetime DEFAULT NULL,
  `SAGE_UID_LUPD` varchar(35) DEFAULT NULL,
  PRIMARY KEY (`SAGE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


CREATE TABLE T_CK_CT_SAGE_TAX (
  `ST_ID` varchar(35) NOT NULL,
  `ST_PREFIX` varchar(35) NOT NULL COMMENT 'LIKE: 010.007.23. 010.009.23.',
  `ST_RANGE_BEGIN` BIGINT NOT NULL COMMENT 'LIKE: 899000000',
  `ST_RANGE_END` BIGINT NOT NULL COMMENT 'LIKE: 89009999',
  `ST_RANGE_CURRENT` BIGINT NOT NULL COMMENT 'LIKE: 89001234',
  `ST_RANGE_FORMAT` varchar(35) NOT NULL COMMENT '%8d',
  `ST_STATUS` char(1) DEFAULT 'A'  COMMENT 'E: expired, I: inactive, A:Active',
  `ST_DT_CREATE` datetime DEFAULT NULL,
  `ST_UID_CREATE` varchar(35) DEFAULT NULL,
  `ST_DT_LUPD` datetime DEFAULT NULL,
  `ST_UID_LUPD` varchar(35) DEFAULT NULL,
  PRIMARY KEY (`ST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


REPLACE INTO `T_CK_CT_SAGE_TAX` (`ST_ID`, `ST_PREFIX`, `ST_RANGE_BEGIN`, `ST_RANGE_END`, `ST_RANGE_CURRENT`, `ST_RANGE_FORMAT`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`) 
VALUES ('1', '010.007.23.', '899000000', '89009999', '0', '%08d',  'A', '2023-06-03 03:47:51', 'sys');


ALTER TABLE T_CK_CT_PLATFORM_INVOICE
ADD COLUMN `INV_SAGE_TAX_NO` varchar(35) NULL AFTER `INV_TOTAL`;


INSERT INTO `T_CORE_ACCN_CONFIG` (`ACFG_ACCNID`, `ACFG_KEY`, `ACFG_VAL`, `ACFG_DESC`, `ACFG_VALID_FROM_DT`, `ACFG_VALID_TO_DT`, `ACFG_SEQ`, `ACFG_STATUS`, `ACFG_DT_CREATE`, `ACFG_UID_CREATE`, `ACFG_DT_LUPD`, `ACFG_UID_LUPD`) VALUES ('BERAM', 'BANK_DETAILS', 'UOB:4683003578', 'TO Merchant Bank ', '2022-12-01 00:00:00', '2024-11-30 23:59:59', '1', 'A', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'SYS');

-- 19 June 2023 - new role for managing the administration for TO (e.g. trucks, location etc)
INSERT INTO `T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`, `ROLE_STATUS`, `ROLE_DESC`, `ROLE_DT_CREATE`, `ROLE_UID_CREATE`, `ROLE_DT_LUPD`, `ROLE_UID_LUPD`) VALUES ('CKT', 'OP_ADMIN', 'A', 'Operations Admin', '2022-11-15 09:09:14', 'SYS', '2022-11-15 09:09:14', 'SYS');

INSERT INTO `T_CORE_USR_ROLE` (`UROL_UID`, `UROL_APPSCODE`, `UROL_ROLEID`, `UROL_ADMIN_OPT`, `UROL_STATUS`, `UROL_DT_CREATE`, `UROL_UID_CREATE`, `UROL_DT_LUPD`, `UROL_UID_LUPD`, `UROL_TEMP_ROLE`) VALUES ('BERAM_U001', 'CKT', 'OP_ADMIN', 'N', 'A', '2022-11-15 09:10:07', 'SYS', '2022-11-15 09:10:07', 'SYS', 'N');

/** CT-98 - [Trucking Operations-Trucking Jobs-Import] Unable to Reject Assigned Jobs */
INSERT INTO `T_CK_SVC_WORKFLOW` (`WKFL_ID`, `WKFL_APPS_CODE`, `WKFL_ACCN_TYPE`, `WKFL_ROLE`, `WKFL_SCV_TYPE`, `WKFL_ACTION`, `WKFL_FROM_STATE`, `WKFL_TO_STATE`, `WKFL_URI`, `WKFL_STATUS`, `WKFL_DT_CREATE`, `WKFL_UID_CREATE`, `WKFL_DT_LUPD`, `WKFL_UID_LUPD`) VALUES ('101', 'CKT', 'ACC_TYPE_TO', 'OFFICER', 'CLICTRUCK', 'REJECT', 'ASG', 'NEW', '', 'A', '2023-06-05 12:05:27', 'SYS', '2023-06-05 12:05:27', 'SYS');

UPDATE `T_CORE_ACCN_CONFIG` SET `ACFG_KEY` = 'BANK_DETAIL' WHERE (`ACFG_ACCNID` = 'BERAM') and (`ACFG_KEY` = 'BANK_DETAILS');

-- -- Note: execute workflow.sql 

INSERT INTO `T_CK_MST_PAYMENT_AUDIT_TYPE` (`PATY_ID`, `PYT_NAME`, `PYT_DESC`, `PYT_DESC_OTH`, `PYT_STATUS`, `PYT_DT_CREATE`, `PYT_UID_CREATE`, `PYT_DT_LUPD`, `PYT_UID_LUPD`) VALUES ('PY_VA', 'MAKE PAYMENT VIA STATIC VA', 'MAKE PAYMENT VIA STATIC VA', 'MAKE PAYMENT VIA STATIC VA', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

CREATE TABLE `T_CK_CT_TO_PAYMENT` (
  `TOP_ID` varchar(35) NOT NULL COMMENT 'UUID',
  `TOP_ACCN_TO` varchar(35) DEFAULT NULL COMMENT 'REFERENCES TO T_CORE_ACCN:ACCNID TRUCKING OPERATOR',
  `TOP_DT_TRANSFER` datetime DEFAULT NULL COMMENT '7 CALENDARS AFTER CO APPROVED INVOICE',
  `TOP_AMT` decimal(15,2) DEFAULT NULL,
  `TOP_REFERENCE` varchar(2048) DEFAULT NULL COMMENT 'T_CK_PAYMENT REFERENCE',
  `TOP_JSON` mediumtext COMMENT 'JSON OBJECT FOR THE API CALL TO CLICPAY PAYMENT GATEWAY FOR FUNDSTRANSFER',
  `TOP_EXCEPTION` mediumtext COMMENT 'EXCEPTION RETURNED BY THE CLICPAY PAYMENT GATEWAY',
  `TOP_STATUS` char(1) DEFAULT NULL COMMENT 'A:ACTIVE; I:INACTIVE',
  `TOP_DT_CREATE` datetime DEFAULT NULL,
  `TOP_UID_CREATE` varchar(35) DEFAULT NULL,
  `TOP_DT_LUPD` datetime DEFAULT NULL,
  `TOP_UID_LUPD` varchar(35) DEFAULT NULL,
  PRIMARY KEY (`TOP_ID`),
  KEY `FK_TOP_ACCN_TO_CORE_ACCN_idx` (`TOP_ACCN_TO`),
  CONSTRAINT `FK_TOP_ACCN_TO_CORE_ACCN` FOREIGN KEY (`TOP_ACCN_TO`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


-- 2023-06-28 Updated actions/workflow for billing verify, reject and approve
INSERT INTO `T_CK_MST_FORM_ACTION` (`FMACT_ID`, `FMACT_NAME`, `FMACT_DESC`, `FMACT_DESC_OTH`, `FMACT_STATUS`, `FMACT_DT_CREATE`, `FMACT_UID_CREATE`, `FMACT_DT_LUPD`, `FMACT_UID_LUPD`) VALUES ('VERIFY_BILL', 'Verify Job Billing', 'Verify Job Billing', 'Verify Job Billing', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');
INSERT INTO `T_CK_MST_FORM_ACTION` (`FMACT_ID`, `FMACT_NAME`, `FMACT_DESC`, `FMACT_DESC_OTH`, `FMACT_STATUS`, `FMACT_DT_CREATE`, `FMACT_UID_CREATE`, `FMACT_DT_LUPD`, `FMACT_UID_LUPD`) VALUES ('APPROVE_BILL', 'Approve Job Billing', 'Approve Job Billing', 'Approve Job Billing', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');
INSERT INTO `T_CK_MST_FORM_ACTION` (`FMACT_ID`, `FMACT_NAME`, `FMACT_DESC`, `FMACT_DESC_OTH`, `FMACT_STATUS`, `FMACT_DT_CREATE`, `FMACT_UID_CREATE`, `FMACT_DT_LUPD`, `FMACT_UID_LUPD`) VALUES ('REJECT_BILL', 'Reject Job Billing', 'Reject Job Billing', 'Reject Job Billing', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');

INSERT INTO `T_CK_MST_ENTITY_STATE` (`ENST_ID`, `ENST_NAME`, `ENST_DESC`, `ENST_DESC_OTH`, `ENST_STATUS`, `ENST_DT_CREATE`, `ENST_UID_CREATE`, `ENST_DT_LUPD`, `ENST_UID_LUPD`) VALUES ('VER_BILL', 'BILLING VERIFIED', 'BILLING VERIFIED', 'BILLING VERIFIED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
INSERT INTO `T_CK_MST_ENTITY_STATE` (`ENST_ID`, `ENST_NAME`, `ENST_DESC`, `ENST_DESC_OTH`, `ENST_STATUS`, `ENST_DT_CREATE`, `ENST_UID_CREATE`, `ENST_DT_LUPD`, `ENST_UID_LUPD`) VALUES ('APP_BILL', 'BILLING APPROVED', 'BILLING APPROVED', 'BILLING APPROVED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
INSERT INTO `T_CK_MST_ENTITY_STATE` (`ENST_ID`, `ENST_NAME`, `ENST_DESC`, `ENST_DESC_OTH`, `ENST_STATUS`, `ENST_DT_CREATE`, `ENST_UID_CREATE`, `ENST_DT_LUPD`, `ENST_UID_LUPD`) VALUES ('REJ_BILL', 'BILLING REJECTED', 'BILLING REJECTED', 'BILLING REJECTED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

ALTER TABLE `T_CK_RECORD_DATE` 
ADD COLUMN `RCD_DT_BILL_REJECTED` DATETIME NULL AFTER `RCD_UID_BILLED`,
ADD COLUMN `RCD_UID_BILL_REJECTED` VARCHAR(35) NULL AFTER `RCD_DT_BILL_REJECTED`,
ADD COLUMN `RCD_DT_BILL_VERIFIED` DATETIME NULL AFTER `RCD_UID_BILL_REJECTED`,
ADD COLUMN `RCD_UID_BILL_VERIFIED` VARCHAR(35) NULL AFTER `RCD_DT_BILL_VERIFIED`,
ADD COLUMN `RCD_DT_BILL_APPROVED` DATETIME NULL AFTER `RCD_UID_BILL_VERIFIED`,
ADD COLUMN `RCD_UID_BILL_APPROVED` VARCHAR(35) NULL AFTER `RCD_DT_BILL_APPROVED`;


INSERT INTO `T_CK_MST_JOB_STATE` (`JBST_ID`, `JBST_NAME`, `JBST_DESC`, `JBST_DESC_OTH`, `JBST_STATUS`, `JBST_DT_CREATE`, `JBST_UID_CREATE`, `JBST_DT_LUPD`, `JBST_UID_LUPD`) VALUES ('VER_BILL', 'BILLING VERIFIED', 'BILLING VERIFIED', 'BILLING VERIFIED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
INSERT INTO `T_CK_MST_JOB_STATE` (`JBST_ID`, `JBST_NAME`, `JBST_DESC`, `JBST_DESC_OTH`, `JBST_STATUS`, `JBST_DT_CREATE`, `JBST_UID_CREATE`, `JBST_DT_LUPD`, `JBST_UID_LUPD`) VALUES ('APP_BILL', 'BILLING APPROVED', 'BILLING APPROVED', 'BILLING APPROVED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
INSERT INTO `T_CK_MST_JOB_STATE` (`JBST_ID`, `JBST_NAME`, `JBST_DESC`, `JBST_DESC_OTH`, `JBST_STATUS`, `JBST_DT_CREATE`, `JBST_UID_CREATE`, `JBST_DT_LUPD`, `JBST_UID_LUPD`) VALUES ('REJ_BILL', 'BILLING REJECTED', 'BILLING REJECTED', 'BILLING APPROVED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');


ALTER TABLE `T_CK_JOB_TRUCK` 
ADD COLUMN `JOB_IN_PAYMENT_DT_DUE` DATETIME NULL AFTER `JOB_OUT_PAYMENT_STATE`,
ADD COLUMN `JOB_OUT_PAYMENT_DT_DUE` DATETIME NULL AFTER `JOB_IN_PAYMENT_DT_DUE`;



CREATE TABLE `T_CORE_USR_RESET` (
  `USR_UID` varchar(35)  NOT NULL,
  `USR_EMAIL` varchar(128)  NOT NULL,
  `USR_TOKEN` varchar(1024)  NOT NULL,
  `USR_EXP_DATE` datetime NOT NULL,
  `USR_STATUS` char(1)  DEFAULT NULL,
  `USR_DT_CREATE` datetime DEFAULT NULL,
  `USR_UID_CREATE` varchar(35)  DEFAULT NULL,
  `USR_DT_LUPD` datetime DEFAULT NULL,
  `USR_UID_LUPD` varchar(35)  DEFAULT NULL,
  PRIMARY KEY (`USR_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;




-- 2023-07-04 Executed in Prod
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_SCHEDULED_PAYOUT_TIME', '6', 'Time in 24 hours format the payout fundtransfer will be triggered.', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

-- start here 07/12/2023 for production -- 
-- 2023-07-12 NOT IN PROD YET START -- 
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','FINANCE_ADMIN','A','FINANCE ADMIN',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('GLI_U001','CKT','FINANCE_ADMIN','N','A',NOW(),'SYS', NOW(),'SYS','N');

INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_FA_060000','CKT','Finance Administration','Finance Administration','Finance Administration','Finance Administration','60000',NULL,'account_balance',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_FA_060100','CKT','','','Sage Excel Report','Sage Excel Report','60100','/manage/sage/excel',NULL,'CKT_FA_060000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_FA_060200','CKT','','','Manage Sage Tax No.','Manage Sage Tax No.','60200','/manage/sage/tax',NULL,'CKT_FA_060000','A',NOW(),'SYS',NOW(),'SYS');

INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM040', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_FA_060000', 'Finance Administration', 'Finance Administration','Finance Administration','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM041', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_FA_060100', 'Sage Excel Report', 'Sage Excel Report','Sage Excel Report','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM042', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_FA_060200', 'Manage Sage Tax No.', 'Manage Sage Tax No.','Manage Sage Tax No.','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');


INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'FINANCE_ADMIN', 'PM040', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'FINANCE_ADMIN', 'PM041', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'FINANCE_ADMIN', 'PM042', 'A', NOW(), 'SYS');

UPDATE `T_CORE_MENU_EX` SET `MENU_ICON` = 'help' WHERE (`MENU_ID` = 'CKT_MH_080000');
UPDATE `T_CORE_MENU_EX` SET `MENU_ICON` = 'manage_accounts' WHERE (`MENU_ID` = 'CKT_AA_050000');
UPDATE `T_CORE_MENU_EX` SET `MENU_ICON` = 'admin_panel_settings' WHERE (`MENU_ID` = 'CKT_MA_030000');
UPDATE `T_CORE_MENU_EX` SET `MENU_ICON` = 'grid_view' WHERE (`MENU_ID` = 'CKT_MS_010000');
UPDATE `T_CORE_MENU_EX` SET `MENU_ICON` = 'handshake' WHERE (`MENU_ID` = 'CKT_MA_040000');
-- 2023-07-12 NOT IN PROD YET END -- 

-- executed in Prod on July 4, 2023 ---
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_STAMP_DUTY_ON', 'false', 'FLAG WHETHER TO TURN ON STAMP DUTY OR NOT', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

ALTER TABLE `T_CK_CT_PLATFORM_INVOICE` 
ADD COLUMN `INV_REFRESH` SMALLINT NULL DEFAULT 0 COMMENT 'THIS IS USE TO REGENERATE THE PDF' AFTER `INV_INVOCIEE_REMARKS`;

ALTER TABLE `T_CK_CT_DEBIT_NOTE` 
ADD COLUMN `DN_REFRESH` SMALLINT NULL DEFAULT 0 COMMENT 'THIS IS USE TO REGENERATE PDF' AFTER `DN_AGE_BAND`;
-- executed in Prod on July 4, 2023 ---


-- 2023-Jul-06 NOT IN PROD YET START -- 
DELETE FROM `T_CORE_ROLE` WHERE (`ROLE_APPSCODE` = 'CKT') and (`ROLE_ID` = 'OFFICER_FINANCE');
UPDATE `T_CORE_ROLE` SET `ROLE_DESC` = 'Billed Job approver before payment' WHERE (`ROLE_APPSCODE` = 'CKT') and (`ROLE_ID` = 'FINANCE_APPROVER');
UPDATE `T_CORE_ROLE` SET `ROLE_DESC` = 'Billed Job verifier before payment' WHERE (`ROLE_APPSCODE` = 'CKT') and (`ROLE_ID` = 'FINANCE_VERIFIER');
UPDATE `T_CORE_ROLE` SET `ROLE_DESC` = 'CO/FF Finance' WHERE (`ROLE_APPSCODE` = 'CKT') and (`ROLE_ID` = 'FF_FINANCE');
UPDATE `T_CORE_ROLE` SET `ROLE_DESC` = 'Account administrator' WHERE (`ROLE_APPSCODE` = 'CKT') and (`ROLE_ID` = 'ADMIN');
UPDATE `T_CORE_ROLE` SET `ROLE_DESC` = 'Role for Tax, Sage, etc.' WHERE (`ROLE_APPSCODE` = 'CKT') and (`ROLE_ID` = 'FINANCE_ADMIN');

UPDATE `T_CORE_ROLE` SET `ROLE_DESC` = 'CO/FF/TO  Operations officer' WHERE (`ROLE_APPSCODE` = 'CKT') and (`ROLE_ID` = 'OFFICER');
UPDATE `T_CORE_ROLE` SET `ROLE_DESC` = 'TO Operations Officer Admin to manage master tables such as vehicle, location, etc.' WHERE (`ROLE_APPSCODE` = 'CKT') and (`ROLE_ID` = 'OP_ADMIN');
UPDATE `T_CORE_ROLE` SET `ROLE_DESC` = 'CO/FF/TO Finance' WHERE (`ROLE_APPSCODE` = 'CKT') and (`ROLE_ID` = 'FF_FINANCE');


-- new menu 
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_MA_030700','CKT','','','Live Monitoring','Live Monitoring','30700','/administrations/live-monitoring',NULL,'CKT_MA_030000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_MA_030800','CKT','','','Historical Monitoring','Historical Monitoring','30800','/administrations/historical-monitoring',NULL,'CKT_MA_030000','A',NOW(),'SYS',NOW(),'SYS');

INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM043', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_MA_030700', 'Live Monitoring', 'Live Monitoring','Live Monitoring','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM044', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_MA_030800', 'Historical Monitoring', 'Historical Monitoring','Historical Monitoring','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');


INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'OP_ADMIN', 'PM043', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'OP_ADMIN', 'PM044', 'A', NOW(), 'SYS');
-- 2023-Jul-06 NOT IN PROD YET END --


-- 2023-JUL-11 NEW COLUMNS FOR PAYMENT TXN EXECUTED IN PROD -- 
ALTER TABLE `T_CK_PAYMENT_TXN` 
ADD COLUMN `PTX_DT_DUE` DATETIME NULL AFTER `PTX_DT_PAID`,
ADD COLUMN `PTX_DT_FIN_APPROVED` DATETIME NULL AFTER `PTX_DT_DUE`;

ALTER TABLE `T_CK_PAYMENT_TXN` 
ADD COLUMN `PTX_UID_FIN_APPROVED` VARCHAR(35) NULL AFTER `PTX_DT_FIN_APPROVED`,
ADD COLUMN `PTX_DT_FIN_VERIFIED` DATETIME NULL AFTER `PTX_UID_FIN_APPROVED`,
ADD COLUMN `PTX_UID_FIN_VERIFIED` VARCHAR(35) NULL AFTER `PTX_DT_FIN_VERIFIED`;
-- 2023-JUL-11 NEW COLUMNS FOR PAYMENT TXN EXECUTED IN PROD -- 

-- 2023-jul-13 new tables for tax modules -- 
CREATE TABLE `T_CK_TAX_INVOICE` (
  `TI_ID` varchar(35) NOT NULL COMMENT 'UNIQUE ID',
  `TI_SERVICE` varchar(35) NOT NULL COMMENT 'CLICKARGO SERVICE - REFERENCES T_CK_MST_SERVICE_TYPE:SVCT_ID',
  `TI_NO` varchar(35) NOT NULL COMMENT 'TAX NO - 010.007.23. 010.009.23.',
  `TI_AMT` decimal(15,2) DEFAULT 0.0 COMMENT 'TAX AMOUNT',
  `TI_DOC` varchar(1024) NOT NULL COMMENT 'FULL PATH PDF LOCATION GENERATED FROM AUTHORIZED SYSTEM',
  `TI_DT_UPLOAD` datetime DEFAULT NULL COMMENT 'DATE TIME WHEN TAX PDF IS UPLOADED',
  `TI_USR_UPLOAD` varchar(35) DEFAULT NULL COMMENT 'USR WHO UPLOADED TAX PDF',
  `TI_INV_NO` varchar(256) NOT NULL COMMENT 'INVOICE NUMBER',
  `TI_INV_DT_ISSUE` datetime DEFAULT NULL COMMENT 'INVOICE ISSUE DATE',
  `TI_JOB_NO` varchar(35) DEFAULT NULL COMMENT 'JOB NUMBER ASSOICATED WITH TAX AND INVOICE',
  `TI_ACCN` varchar(35) DEFAULT NULL COMMENT 'CUSTOMER ACCOUNT - REFERNCES T_CORE_ACCN:ACCN_ID',
  `TI_STATUS` char(1) DEFAULT 'N' COMMENT 'N: NEW E:EXPORTED C: COMPLETED WITH PDF UPLOADED ',
  `TI_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `TI_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `TI_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `TI_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`TI_ID`),
  CONSTRAINT `FK_CK_TAX_INVOICE_CK_MST_SERVICE_TYPE` FOREIGN KEY (`TI_SERVICE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),  
  CONSTRAINT `FK_CK_TAX_INVOICE_CORE_ACCN` FOREIGN KEY (`TI_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT 'TAX INVOICE TABLE';


CREATE TABLE `T_CK_TAX_REPORT` (
  `TR_ID` varchar(35) NOT NULL COMMENT 'UNIQUE ID',
  `TR_NAME` varchar(256) DEFAULT NULL COMMENT 'EXCEL FILE NAME - TAX_CK_DDMMYYYY',
  `TR_DOC` varchar(1024) DEFAULT NULL COMMENT 'FULL PATH EXCEL LOCATION',
  `TR_NUM_RECORDS` mediumint DEFAULT 0 COMMENT 'NUMBER OF RECORDS EXPORTED',
  `TR_STATUS` char(1) DEFAULT 'N' COMMENT 'N: NEW D:DOWNLOADED',
  `TR_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `TR_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `TR_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `TR_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`TR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT 'TAX REPORT TABLE';

/** REPORTS: Initial updates for reports T_MST_RPT_FILTYPE and T_MST_RPT_COLTYPE */
SET SQL_SAFE_UPDATES = 0;
DELETE FROM `T_MST_RPT_FILTYPE`;
SET SQL_SAFE_UPDATES = 1;
INSERT INTO T_MST_RPT_FILTYPE (`RPTFT_ID`, `RPTFT_CAPTION`, `RPTFT_CAPTION_OTH`, `RPTFT_STATUS`, `RPTFT_UID_CREATE`, `RPTFT_DT_CREATE`, `RPTFT_UID_LUPD`, `RPTFT_UID_LUD`) VALUES ('C', 'Checkbox', NULL, 'A', 'SYS', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00');
INSERT INTO T_MST_RPT_FILTYPE (`RPTFT_ID`, `RPTFT_CAPTION`, `RPTFT_CAPTION_OTH`, `RPTFT_STATUS`, `RPTFT_UID_CREATE`, `RPTFT_DT_CREATE`, `RPTFT_UID_LUPD`, `RPTFT_UID_LUD`) VALUES ('D', 'Date', NULL, 'A', 'SYS', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00');
INSERT INTO T_MST_RPT_FILTYPE (`RPTFT_ID`, `RPTFT_CAPTION`, `RPTFT_CAPTION_OTH`, `RPTFT_STATUS`, `RPTFT_UID_CREATE`, `RPTFT_DT_CREATE`, `RPTFT_UID_LUPD`, `RPTFT_UID_LUD`) VALUES ('L', 'Listbox', NULL, 'A', 'SYS', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00');
INSERT INTO T_MST_RPT_FILTYPE (`RPTFT_ID`, `RPTFT_CAPTION`, `RPTFT_CAPTION_OTH`, `RPTFT_STATUS`, `RPTFT_UID_CREATE`, `RPTFT_DT_CREATE`, `RPTFT_UID_LUPD`, `RPTFT_UID_LUD`) VALUES ('R', 'Date Range', NULL, 'A', 'SYS', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00');
INSERT INTO T_MST_RPT_FILTYPE (`RPTFT_ID`, `RPTFT_CAPTION`, `RPTFT_CAPTION_OTH`, `RPTFT_STATUS`, `RPTFT_UID_CREATE`, `RPTFT_DT_CREATE`, `RPTFT_UID_LUPD`, `RPTFT_UID_LUD`) VALUES ('T', 'Text', NULL, 'A', 'SYS', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00');

SET SQL_SAFE_UPDATES = 0;
DELETE FROM `T_MST_RPT_COLTYPE`;
SET SQL_SAFE_UPDATES = 1;
INSERT INTO T_MST_RPT_COLTYPE (`RPTCT_ID`, `RPTCT_CAPTION`, `RPTCT_CAPTION_OTH`, `RPTCT_STATUS`, `RPTCT_UID_CREATE`, `RPTCT_DT_CREATE`, `RPTCT_UID_LUPD`, `RPTCT_DT_LUPD`) VALUES ('D', 'DATE', 'Date', 'A', 'SYS', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00');
INSERT INTO T_MST_RPT_COLTYPE (`RPTCT_ID`, `RPTCT_CAPTION`, `RPTCT_CAPTION_OTH`, `RPTCT_STATUS`, `RPTCT_UID_CREATE`, `RPTCT_DT_CREATE`, `RPTCT_UID_LUPD`, `RPTCT_DT_LUPD`) VALUES ('M', 'MONEY', 'Money', 'A', 'SYS', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00');
INSERT INTO T_MST_RPT_COLTYPE (`RPTCT_ID`, `RPTCT_CAPTION`, `RPTCT_CAPTION_OTH`, `RPTCT_STATUS`, `RPTCT_UID_CREATE`, `RPTCT_DT_CREATE`, `RPTCT_UID_LUPD`, `RPTCT_DT_LUPD`) VALUES ('N', 'NUMERIC', 'Numeric', 'A', 'SYS', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00');
INSERT INTO T_MST_RPT_COLTYPE (`RPTCT_ID`, `RPTCT_CAPTION`, `RPTCT_CAPTION_OTH`, `RPTCT_STATUS`, `RPTCT_UID_CREATE`, `RPTCT_DT_CREATE`, `RPTCT_UID_LUPD`, `RPTCT_DT_LUPD`) VALUES ('T', 'TEXT', 'Text', 'A', 'SYS', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00');

/** REPORTS: Initial updates for reports, for showing Reports Menu T_CORE_MENU_EX, T_CORE_PERM_EX, T_CORE_GRANT_ROLE_EX */
INSERT INTO T_CORE_MENU_EX (`MENU_ID`, `MENU_APPS_CODE`, `MENU_GROUP_LABEL`, `MENU_GROUP_LABEL_OTH`, `MENU_NAME`, `MENU_NAME_OTH`, `MENU_SEQ`, `MENU_PATH`, `MENU_ICON`, `MENU_PARENT`, `MENU_STATUS`, `MENU_DT_CREATE`, `MENU_UID_CREATE`, `MENU_DT_LUPD`, `MENU_UID_LUPD`) VALUES ('CKT_MR_010000', 'CKT', 'Reports', 'Reports', 'Reports', 'Reports', '60300', '/administrations/report/list', NULL, NULL, 'A', '2020-12-20 00:00:00', 'SYS', '2020-12-20 00:00:00', 'SYS');
INSERT INTO T_CORE_PERM_EX (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`, `PERM_MENU_NAME`, `PERM_DOC_TYPE`, `PERM_DOC_CODE`, `PERM_ACTION`, `PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`, `PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM058', 'Y', 'CKT', NULL, 'M', NULL, NULL, 'CKT_MR_010000', 'Reports', NULL, NULL, NULL, 'Reports', 'Reports', 'R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
/** REPORTS: Adding below statement adds Report Menu to user with ADMIN role */
INSERT INTO T_CORE_GRANT_ROLE_EX (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`, `GNTRLEX_DT_LUPD`, `GNTRLEX_UID_LUPD`) VALUES ('CKT', 'ADMIN', 'PM058', 'A', '2021-04-14 11:09:21', 'SYS', NULL, NULL);

-- DO NOT APPEND HERE - NEW SQL SCRIPT V.03 HAS BEEN CREATED --- 