ALTER TABLE `clickargo2`.`T_CK_CT_TRIP_RATE` 
ADD COLUMN `TR_PARENT` VARCHAR(35) DEFAULT NULL AFTER `TR_ID`,
ADD INDEX `FK_CK_TRIP_RATE_CK_TRIP_RATE_idx` (`TR_PARENT` ASC) VISIBLE;
;

ALTER TABLE `clickargo2`.`T_CK_CT_TRIP_RATE` 
ADD CONSTRAINT `FK_CK_TRIP_RATE_CK_TRIP_RATE`
  FOREIGN KEY (`TR_PARENT`)
  REFERENCES `clickargo2`.`T_CK_CT_TRIP_RATE` (`TR_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `clickargo2`.`T_CK_CT_TRIP_RATE` 
ADD COLUMN `TR_TYPE` CHAR(1) NULL DEFAULT 'S' COMMENT 'S:SINGLE,M:MULTI,C:CHILD' AFTER `TR_PARENT`,
ADD COLUMN `TR_SEQ` INT NULL DEFAULT 0 AFTER `TR_TYPE`;

ALTER TABLE `clickargo2`.`T_CK_CT_TRIP` 
ADD COLUMN `TR_SEQ` INT NULL DEFAULT 0 AFTER `TR_JOB`;