/** For HOTFIX items **/

CREATE TABLE `T_CK_JOB_REMARKS` (
  `JOBR_ID` varchar(35) NOT NULL,
  `JOBR_REMARK_TYPE` char NOT NULL COMMENT 'V:VERIFY | A:APPROVE | R:REJECT',
  `JOBR_JOB` varchar(35) DEFAULT NULL COMMENT 'REFERENCE TO JOB',
  `JOBR_SEQ` int DEFAULT NULL,
  `JOBR_UID_CREATED` varchar(35) DEFAULT NULL COMMENT 'REFERENCE TO USERID THAT DID THE REMARKS',
  `JOBR_DT_REMARKS` datetime DEFAULT NULL,
  `JOBR_REASON` mediumtext,
  PRIMARY KEY (`JOBR_ID`),
  KEY `FK_CK_JOB_REMARKS_CK_JOB_idx` (`JOBR_JOB`),
  CONSTRAINT `FK_CK_JOB_REMARKS_CK_JOB_idx` FOREIGN KEY (`JOBR_JOB`) REFERENCES `T_CK_JOB` (`JOB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

INSERT INTO T_CK_MST_CREDIT_UPDATE_STATE (ST_ID, ST_NAME, ST_DESC, ST_DESC_OTH, ST_STATUS, ST_DT_CREATE, ST_UID_CREATE, ST_DT_LUPD, ST_UID_LUPD) VALUES('ACT', 'ACTIVED', 'ACTIVED', 'ACTIVED', 'A', '2023-09-27 16:52:03', 'SYS', '2023-09-27 16:52:03', 'SYS');

INSERT INTO T_CK_MST_FORM_ACTION (FMACT_ID,FMACT_NAME,FMACT_DESC,FMACT_DESC_OTH,FMACT_STATUS,FMACT_DT_CREATE,FMACT_UID_CREATE,FMACT_DT_LUPD,FMACT_UID_LUPD) VALUES
	 ('RESUMPTION','Form Unsuspend','Form Unsuspend','Form Unsuspend','A','2022-10-01 01:00:00','SYS','2022-10-01 01:00:00','SYS');

INSERT INTO T_CK_MST_ENTITY_STATE(ENST_ID,ENST_NAME,ENST_DESC,ENST_DESC_OTH,ENST_STATUS,ENST_DT_CREATE,ENST_UID_CREATE,ENST_DT_LUPD,ENST_UID_LUPD) VALUES
	 ('RESUMPTION','RESUMPTION','RESUMPTION','RESUMPTION','A','2020-10-01 00:00:00','SYS','2020-10-01 00:00:00','SYS');

INSERT INTO T_CK_MST_ENTITY_TYPE(ENTY_ID,ENTY_NAME,ENTY_DESC,ENTY_DESC_OTH,ENTY_STATUS,ENTY_DT_CREATE,ENTY_UID_CREATE,ENTY_DT_LUPD,ENTY_UID_LUPD) VALUES
	 ('ACCN_RESUMPTION','Account Resumption','Account Resumption','Account Resumption','A','2022-10-01 01:00:00','SYS','2022-10-01 01:00:00','SYS');
     
     
-- execute workflow.sql

INSERT INTO T_CK_MST_REMARK_TYPE(RT_ID,RT_NAME,RT_DESC,RT_DESC_OTH,RT_STATUS,RT_DT_CREATE,RT_UID_CREATE,RT_DT_LUPD,RT_UID_LUPD) VALUES
	 ('RESUMPT_APPROVE','RESUMPTION APPROVED','RESUMPTION APPROVED','RESUMPTION APPROVED','A','2023-09-23 07:56:04','SYS','2023-09-23 07:56:04','SYS'),
	 ('RESUMPT_REJECT','RESUMPTION REJECTED','RESUMPTION REJECTED','RESUMPTION REJECTED','A','2023-09-23 07:56:04','SYS','2023-09-23 07:56:04','SYS'),
	 ('RESUMPT_REQ','RESUMPTION REQUEST','RESUMPTION REQUEST','RESUMPTION REQUEST','A','2023-09-23 07:56:04','SYS','2023-09-23 07:56:04','SYS');

INSERT INTO T_CK_MST_WORKFLOW_TYPE(WKT_ID,WKT_NAME,WKT_DESC,WKT_DESC_OTH,WKT_STATUS,WKT_DT_CREATE,WKT_UID_CREATE,WKT_DT_LUPD,WKT_UID_LUPD) VALUES
	 ('ACCN_RESUMPT','ACCOUNT RESUMPTION','ACCOUNT RESUMPTION','ACCOUNT RESUMPTION','A','2023-09-23 07:49:32','SYS','2023-09-23 07:49:32','SYS'),
     ('CONTRACT_REQ','CONTRACT REQUEST','CONTRACT REQUEST','CONTRACT REQUEST','A','2023-09-23 07:49:32','SYS','2023-09-23 07:49:32','SYS');	     
   

-- execute formcontrol.sql

CREATE TABLE `T_CK_WHITELABEL` (
  `WL_ID` varchar(35) NOT NULL,
  `WL_ACCN_ID` varchar(35) NOT NULL COMMENT 'REFERENCE TO T_CORE_ACCN:ACCN_ID',
  `WL_NAME` varchar(35) NOT NULL COMMENT 'SHORTENED ACCOUNT NAME OF TRUCKING OPERATOR TO BE USED IN REDIRECTION',
  `WL_STATUS` char(1) DEFAULT NULL,
  `WL_IMG_LOC` varchar(1024) DEFAULT NULL COMMENT 'LOCATION OF THE BACKGROUND IMAGE TO USE',
  `WL_DT_CREATE` datetime DEFAULT NULL,
  `WT_UID_CREATE` varchar(35) DEFAULT NULL,
  `WL_DT_LUPD` datetime DEFAULT NULL,
  `WL_UID_LUPD` varchar(35) DEFAULT NULL,
  PRIMARY KEY (`WL_ID`),
  KEY `FK_CK_CT_WL_CORE_ACCN` (`WL_ACCN_ID`),
  CONSTRAINT `FK_CK_CT_WL_CORE_ACCN` FOREIGN KEY (`WL_ACCN_ID`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='FOR WHITE LABEL CUSTOM LOGIN PAGE';



INSERT INTO `clickargo2`.`T_CK_MST_JOURNAL_TXN_TYPE` (`JTT_ID`, `JTT_NAME`, `JTT_DESC`, `JTT_DESC_OTH`, `JTT_STATUS`, `JTT_DT_CREATE`, `JTT_UID_CREATE`) 
VALUES ('JOB_TERMINATION', 'JOB_TERMINATION', 'JOB_TERMINATION', 'JOB_TERMINATION', 'A', SYSDATE(), 'SYS');

-- execute navigation.sql

-- above scripts executed in prod on 10/29 : do not add below this line -- 
-- execute navigation.sql


-- DO NOT EXECUTE SCRIPT ABOVE THIS LINE ; ALREADY DEPLOYED IN PRODUCTION ON 10/29-- 


-- For credit limit update -- 
-- only change table name

drop table if exists T_CK_CREDIT_UPDATE;
drop table if exists T_CK_MST_CREDIT_UPDATE_STATE;

CREATE TABLE `T_CK_MST_CREDIT_REQUEST_STATE` (
  `ST_ID` varchar(35) NOT NULL COMMENT 'CREDIT UPDATE STATE ID - NEW : SUBMITTED : DELETED : APPROVE : REJECTED : ACTIVE',
  `ST_NAME` varchar(100) NOT NULL COMMENT 'CREDIT UPDATE  STATE NAME',
  `ST_DESC` varchar(255) DEFAULT NULL COMMENT 'CREDIT UPDATE STATE DESCRIPTION',
  `ST_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'CREDIT UPDATE STATE DESCRIPTION OTHER LANGUAGE',
  `ST_STATUS` char(1) DEFAULT NULL COMMENT 'CREDIT UPDATE STATE STATUS',
  `ST_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `ST_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `ST_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `ST_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`ST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='CREDIT UPDATE STATE TABLE';

INSERT INTO `T_CK_MST_CREDIT_REQUEST_STATE` (`ST_ID`,`ST_NAME`,`ST_DESC`,`ST_DESC_OTH`,`ST_STATUS`,`ST_DT_CREATE`,`ST_UID_CREATE`,`ST_DT_LUPD`,`ST_UID_LUPD`)  VALUES('NEW','NEW','NEW','NEW','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO `T_CK_MST_CREDIT_REQUEST_STATE` (`ST_ID`,`ST_NAME`,`ST_DESC`,`ST_DESC_OTH`,`ST_STATUS`,`ST_DT_CREATE`,`ST_UID_CREATE`,`ST_DT_LUPD`,`ST_UID_LUPD`)  VALUES('SUB','SUBMITTED','SUBMITTED','SUBMITTED','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO `T_CK_MST_CREDIT_REQUEST_STATE` (`ST_ID`,`ST_NAME`,`ST_DESC`,`ST_DESC_OTH`,`ST_STATUS`,`ST_DT_CREATE`,`ST_UID_CREATE`,`ST_DT_LUPD`,`ST_UID_LUPD`)  VALUES('DEL','DELETED','DELETED','DELETED','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO `T_CK_MST_CREDIT_REQUEST_STATE` (`ST_ID`,`ST_NAME`,`ST_DESC`,`ST_DESC_OTH`,`ST_STATUS`,`ST_DT_CREATE`,`ST_UID_CREATE`,`ST_DT_LUPD`,`ST_UID_LUPD`)  VALUES('APP','APPROVED','APPROVED','APPROVED','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO `T_CK_MST_CREDIT_REQUEST_STATE` (`ST_ID`,`ST_NAME`,`ST_DESC`,`ST_DESC_OTH`,`ST_STATUS`,`ST_DT_CREATE`,`ST_UID_CREATE`,`ST_DT_LUPD`,`ST_UID_LUPD`)  VALUES('REJ','REJECTED','REJECTED','REJECTED','A',NOW(),'SYS',NOW(),'SYS');

CREATE TABLE `T_CK_CREDIT_REQUEST` (
  `CRU_ID` varchar(35) NOT NULL COMMENT 'RECORD ID - UUID',
  `CRU_SERVICE_TYPE` varchar(35) DEFAULT NULL COMMENT 'CREDIT SERVICE TYPE - REFERENCES T_CK_MST_CREDIT_REQUEST_STATE:ST_ID',
  `CRU_COMPANY` varchar(35) DEFAULT NULL COMMENT 'CREDIT COMPANY ACCOUNT - REFERENCES T_CORE_ACCN:ACCN_ID',
  `CRU_STATE` varchar(35) DEFAULT NULL COMMENT 'CREDIT STATE - REFERENCES T_CK_MST_CREDIT_STATE:CRST_ID',
  `CRU_AMT` double(15,2) DEFAULT '0.00' COMMENT 'CREDIT AMOUNT',
  `CRU_TXN_CAP` double(15,2) DEFAULT NULL COMMENT 'MONTHLY TRANSACTION CAP',
  `CRU_CCY` varchar(3) DEFAULT NULL COMMENT 'CURRENCY  - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `CRU_DT_START` datetime DEFAULT NULL COMMENT 'CREDIT START DATE TIME',
  `CRU_DT_END` datetime DEFAULT NULL COMMENT 'CREDIT END DATE TIME',
  `CRU_REMARKS` mediumtext COMMENT 'REMARKS FROM REQUESTER',
  `CRU_USR_VERIFY` varchar(35) DEFAULT NULL COMMENT 'CREDIT VERIFIER',
  `CRU_DT_VERIFY` datetime DEFAULT NULL COMMENT 'CREDIT VERIFIED DATE TIME',
  `CRU_USR_APPROVE` varchar(35) DEFAULT NULL COMMENT 'CREDIT APPROVER',
  `CRU_DT_APPROVE` datetime DEFAULT NULL COMMENT 'CREDIT APPROVED DATE TIME',
  `CRU_USR_REJECT` varchar(35) DEFAULT NULL COMMENT 'CREDIT REJECT',
  `CRU_DT_REJECT` datetime DEFAULT NULL COMMENT 'CREDIT REJECT DATE TIME',
  `CRU_APPROVER_REMARKS` mediumtext COMMENT 'REMARKS FOR CREDIT APPROVAL OR REJECTION',
  `CRU_STATUS` char(1) DEFAULT NULL COMMENT 'CREDIT RECORD STATUS',
  `CRU_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CRU_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CRU_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CRU_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CRU_ID`),
  CONSTRAINT `FK_CK_CREDIT_UPDATE_CK_MST_CREDIT_UPDATE_STATE` FOREIGN KEY (`CRU_STATE`) REFERENCES `T_CK_MST_CREDIT_REQUEST_STATE` (`ST_ID`),
  CONSTRAINT `FK_CK_CREDIT_UPDATE_CK_MST_SERVICE_TYPE` FOREIGN KEY (`CRU_SERVICE_TYPE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),
  CONSTRAINT `FK_CK_CREDIT_UPDATE_CORE_ACCN` FOREIGN KEY (`CRU_COMPANY`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_CREDIT_UPDATE_MST_CURRENCY` FOREIGN KEY (`CRU_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='CREDIT UPDATE TABLE';



ALTER TABLE clickargo2.T_CK_CREDIT_REQUEST ADD COLUMN CRU_DT_SUBMITTED DATETIME;
ALTER TABLE clickargo2.T_CK_CREDIT_REQUEST ADD COLUMN CRU_UID_SUBMITTED VARCHAR(35);
ALTER TABLE clickargo2.T_CK_CREDIT_REQUEST ADD COLUMN CRU_REQUESTER VARCHAR(35);

INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('STAMP_GATEWAY_CALLBACK', 'http://43.218.190.246:8080/clickargo/api/v1/clickargo/estamp/callback', 'CALLBACK FOR STAMP', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');
UPDATE `T_CORE_SYSPARAM` SET `SYS_VAL` = 'true' WHERE (`SYS_KEY` = 'CLICTRUCK_STAMP_DUTY_ON');

INSERT INTO T_CK_MST_CREDIT_REQUEST_STATE (ST_ID, ST_NAME, ST_DESC, ST_DESC_OTH, ST_STATUS, ST_DT_CREATE, ST_UID_CREATE, ST_DT_LUPD, ST_UID_LUPD) VALUES('ACT', 'ACTIVED', 'ACTIVED', 'ACTIVED', 'A', '2023-09-27 16:52:03', 'SYS', '2023-09-27 16:52:03', 'SYS');


-- execute navigation.sql
-- execute email_notification.sql

INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_EMAIL_APPROVAL_VALIDITY', '7', 'NO. OF DAYS THE LINK FOR BILLING APPROVAL LINK IS VALID', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

INSERT INTO `T_CORE_SYSPARAM` (SYS_KEY,SYS_VAL,SYS_DESC,SYS_DT_CREATE,SYS_UID_CREATE,SYS_DT_LUPD,SYS_UID_LUPD,SYS_STATUS) VALUES
	 ('CLICTRUCK_JRXML_DRAFT_DN_PATH','docs/DraftDebitNote.jrxml','Draft Debit Note',now(),'SYS',now(),'SYS','A'),
	 ('CLICTRUCK_JRXML_DRAFT_INVOICE_PATH','docs/DraftInvoiceClictruck.jrxml','Draft Platform Fee Commercial Invoice',now(),'SYS',now(),'SYS','A');
	 
-- deployed in production 01Jan2024 -- 