-- Account
-- 1: DSVAS
-- 2: DB Schenker
INSERT INTO `clickargo2`.`T_CORE_ACCN` (`ACCN_ID`, `ACCN_STATUS`, `ACCN_NAME`, `ACCN_TYPE`, `ACCN_COY_REGN`, `ACCN_ADDR1`, `ACCN_ADDR2`, `ACCN_PCODE`, `ACCN_CITY`, `ACCN_PROV`, `ACCN_CTYCODE`, `ACCN_TEL`, `ACCN_EMAIL`, `ACCN_DT_REG`, `ACCN_DT_CREATE`, `ACCN_UID_CREATE`, `ACCN_DT_LUPD`, `ACCN_UID_LUPD`) 
VALUES ('DSCH', 'A', 'DB Schenker', 'ACC_TYPE_FF', '1', 'Address Line 1', 'Address Line 2', '123456', 'Singapore', 'Singapore', 'SG', '+6512345678', 'Mohamad.Syafiq@dbschenker.com', sysdate(), sysdate(), 'GLI_U001', sysdate(), 'GLI_U001');
-- 3: CWL
-- 4: LAP
INSERT INTO `clickargo2`.`T_CORE_ACCN` (`ACCN_ID`, `ACCN_STATUS`, `ACCN_NAME`, `ACCN_TYPE`, `ACCN_COY_REGN`, `ACCN_ADDR1`, `ACCN_ADDR2`, `ACCN_PCODE`, `ACCN_CITY`, `ACCN_PROV`, `ACCN_CTYCODE`, `ACCN_TEL`, `ACCN_EMAIL`, `ACCN_DT_REG`, `ACCN_DT_CREATE`, `ACCN_UID_CREATE`, `ACCN_DT_LUPD`, `ACCN_UID_LUPD`)
 VALUES ('LAP', 'A', 'Logisteed Asia-Pacific Pte. Ltd.', 'ACC_TYPE_FF', '1', 'Address Line 1', 'Address Line 2', '123456', 'Singapore', 'Singapore', 'SG', '+6512345678', 'test@guud.company', '2024-10-03 17:20:11', '2024-10-03 17:20:11', 'GLI_U001', '2024-10-03 17:20:11', 'GLI_U001');
-- 5: AWOT
INSERT INTO `clickargo2`.`T_CORE_ACCN` (`ACCN_ID`, `ACCN_STATUS`, `ACCN_NAME`, `ACCN_TYPE`, `ACCN_COY_REGN`, `ACCN_ADDR1`, `ACCN_ADDR2`, `ACCN_PCODE`, `ACCN_CITY`, `ACCN_PROV`, `ACCN_CTYCODE`, `ACCN_TEL`, `ACCN_EMAIL`, `ACCN_DT_REG`, `ACCN_DT_CREATE`, `ACCN_UID_CREATE`, `ACCN_DT_LUPD`, `ACCN_UID_LUPD`) 
VALUES ('AWOT', 'A', 'AWOT Global Logistics (S) Pte Ltd', 'ACC_TYPE_FF', '1', 'Address Line 1', 'Address Line 2', '123456', 'Singapore', 'Singapore', 'SG', '+6512345678', 'test@guud.company', '2024-10-03 17:21:16', '2024-10-03 17:21:16', 'GLI_U001', '2024-10-03 17:21:16', 'GLI_U001');
-- 6:MMD
INSERT INTO `clickargo2`.`T_CORE_ACCN` (`ACCN_ID`, `ACCN_STATUS`, `ACCN_NAME`, `ACCN_TYPE`, `ACCN_COY_REGN`, `ACCN_ADDR1`, `ACCN_ADDR2`, `ACCN_PCODE`, `ACCN_CITY`, `ACCN_PROV`, `ACCN_CTYCODE`, `ACCN_TEL`, `ACCN_EMAIL`, `ACCN_DT_REG`, `ACCN_DT_CREATE`, `ACCN_UID_CREATE`, `ACCN_DT_LUPD`, `ACCN_UID_LUPD`) 
VALUES ('MMD', 'A', 'MMD', 'ACC_TYPE_FF', '1', 'Address Line 1', 'Address Line 2', '123456', 'Singapore', 'Singapore', 'SG', '+6512345678', 'test@guud.company', '2024-10-03 17:21:50', '2024-10-03 17:21:50', 'GLI_U001', '2024-10-03 17:21:50', 'GLI_U001');


-- Users
INSERT INTO `clickargo2`.`T_CORE_USR` (`USR_UID`, `USR_ACCNID`, `USR_STATUS`, `USR_TYPE_ONLINE`, `USR_TYPE_MBOX`, `USR_NAME`, `USR_PASS_NID`, `USR_TITLE`, `USR_DEPT`, `USR_DT_REG`, `USR_DT_COMM`, `USR_DT_DEREG`, `USR_DT_REREG`, `USR_ADDR1`, `USR_ADDR2`, `USR_ADDR3`, `USR_PCODE`, `USR_CITY`, `USR_PROV`, `USR_CTYCODE`, `USR_TEL`, `USR_FAX`, `USR_EMAIL`, `USR_PWD`, `USR_PWD_1`, `USR_PWD_2`, `USR_PWD_3`, `USR_PWD_4`, `USR_DT_PWD_LUPD`, `USR_PWD_VALIDTY`, `USR_LOGIN_INVCNT`, `USR_DT_LOGINOK`, `USR_DT_LOGINERR`, `USR_MBOX_ID`, `USR_MBOX_MAXCNT`, `USR_MBOX_MAXSIZ`, `USR_DUR_INBX`, `USR_DUR_ARCH`, `USR_DT_CREATE`, `USR_UID_CREATE`, `USR_DT_LUPD`, `USR_UID_LUPD`) 
VALUES ('DSCH001', 'DSCH', 'A', 'A', 'A', 'DSCH001', 'DSCH001', 'DSCH001', '', sysdate(), sysdate(), sysdate(), sysdate(), 'TEST', 'SSS', 'DSCH001@guud.company', '761118', '1001 - CHHLOUNG', '10 - KRATIE', 'AD', '+85516919081', '', 'benjamin.lim+dsv@guud.company_123', '', '', '', '', '', '2024-07-16 21:17:45', '0', '0', '2024-07-16 21:03:36', '2024-07-16 21:03:36', 'Default', '0', '0', '0', '0', '2024-07-16 21:05:23', 'CKUS00323', '2024-09-11 00:19:34', 'TO_DSV_001');
UPDATE  `clickargo2`.`T_CORE_USR`  SET USR_PWD = md5('DSCH001Password123!') where USR_UID = 'DSCH001';

INSERT INTO `clickargo2`.`T_CORE_USR` (`USR_UID`, `USR_ACCNID`, `USR_STATUS`, `USR_TYPE_ONLINE`, `USR_TYPE_MBOX`, `USR_NAME`, `USR_PASS_NID`, `USR_TITLE`, `USR_DEPT`, `USR_DT_REG`, `USR_DT_COMM`, `USR_DT_DEREG`, `USR_DT_REREG`, `USR_ADDR1`, `USR_ADDR2`, `USR_ADDR3`, `USR_PCODE`, `USR_CITY`, `USR_PROV`, `USR_CTYCODE`, `USR_TEL`, `USR_FAX`, `USR_EMAIL`, `USR_PWD`, `USR_PWD_1`, `USR_PWD_2`, `USR_PWD_3`, `USR_PWD_4`, `USR_DT_PWD_LUPD`, `USR_PWD_VALIDTY`, `USR_LOGIN_INVCNT`, `USR_DT_LOGINOK`, `USR_DT_LOGINERR`, `USR_MBOX_ID`, `USR_MBOX_MAXCNT`, `USR_MBOX_MAXSIZ`, `USR_DUR_INBX`, `USR_DUR_ARCH`, `USR_DT_CREATE`, `USR_UID_CREATE`, `USR_DT_LUPD`, `USR_UID_LUPD`) 
VALUES ('LAP001', 'LAP', 'A', 'A', 'A', 'LAP001', 'LAP001', '', '', sysdate(), sysdate(), sysdate(), sysdate(), 'TEST', 'SSS', 'LAP001@guud.company', '761118', '1001 - CHHLOUNG', '10 - KRATIE', 'AD', '+85516919081', '', 'benjamin.lim+dsv@guud.company_123', '', '', '', '', '', '2024-07-16 21:17:45', '0', '0', '2024-07-16 21:03:36', '2024-07-16 21:03:36', 'Default', '0', '0', '0', '0', '2024-07-16 21:05:23', 'CKUS00323', '2024-09-11 00:19:34', 'TO_DSV_001');
UPDATE  `clickargo2`.`T_CORE_USR`  SET USR_PWD = md5('LAP001Password123!') where USR_UID = 'LAP001';

INSERT INTO `clickargo2`.`T_CORE_USR` (`USR_UID`, `USR_ACCNID`, `USR_STATUS`, `USR_TYPE_ONLINE`, `USR_TYPE_MBOX`, `USR_NAME`, `USR_PASS_NID`, `USR_TITLE`, `USR_DEPT`, `USR_DT_REG`, `USR_DT_COMM`, `USR_DT_DEREG`, `USR_DT_REREG`, `USR_ADDR1`, `USR_ADDR2`, `USR_ADDR3`, `USR_PCODE`, `USR_CITY`, `USR_PROV`, `USR_CTYCODE`, `USR_TEL`, `USR_FAX`, `USR_EMAIL`, `USR_PWD`, `USR_PWD_1`, `USR_PWD_2`, `USR_PWD_3`, `USR_PWD_4`, `USR_DT_PWD_LUPD`, `USR_PWD_VALIDTY`, `USR_LOGIN_INVCNT`, `USR_DT_LOGINOK`, `USR_DT_LOGINERR`, `USR_MBOX_ID`, `USR_MBOX_MAXCNT`, `USR_MBOX_MAXSIZ`, `USR_DUR_INBX`, `USR_DUR_ARCH`, `USR_DT_CREATE`, `USR_UID_CREATE`, `USR_DT_LUPD`, `USR_UID_LUPD`) 
VALUES ('AWOT001', 'AWOT', 'A', 'A', 'A', 'AWOT001', 'AWOT001', '', '', sysdate(), sysdate(), sysdate(), sysdate(), 'TEST', 'SSS', 'AWOT001@guud.company', '761118', '1001 - CHHLOUNG', '10 - KRATIE', 'AD', '+85516919081', '', 'benjamin.lim+dsv@guud.company_123', '', '', '', '', '', '2024-07-16 21:17:45', '0', '0', '2024-07-16 21:03:36', '2024-07-16 21:03:36', 'Default', '0', '0', '0', '0', '2024-07-16 21:05:23', 'CKUS00323', '2024-09-11 00:19:34', 'TO_DSV_001');
UPDATE  `clickargo2`.`T_CORE_USR`  SET USR_PWD = md5('AWOT001Password123!') where USR_UID = 'AWOT001';

INSERT INTO `clickargo2`.`T_CORE_USR` (`USR_UID`, `USR_ACCNID`, `USR_STATUS`, `USR_TYPE_ONLINE`, `USR_TYPE_MBOX`, `USR_NAME`, `USR_PASS_NID`, `USR_TITLE`, `USR_DEPT`, `USR_DT_REG`, `USR_DT_COMM`, `USR_DT_DEREG`, `USR_DT_REREG`, `USR_ADDR1`, `USR_ADDR2`, `USR_ADDR3`, `USR_PCODE`, `USR_CITY`, `USR_PROV`, `USR_CTYCODE`, `USR_TEL`, `USR_FAX`, `USR_EMAIL`, `USR_PWD`, `USR_PWD_1`, `USR_PWD_2`, `USR_PWD_3`, `USR_PWD_4`, `USR_DT_PWD_LUPD`, `USR_PWD_VALIDTY`, `USR_LOGIN_INVCNT`, `USR_DT_LOGINOK`, `USR_DT_LOGINERR`, `USR_MBOX_ID`, `USR_MBOX_MAXCNT`, `USR_MBOX_MAXSIZ`, `USR_DUR_INBX`, `USR_DUR_ARCH`, `USR_DT_CREATE`, `USR_UID_CREATE`, `USR_DT_LUPD`, `USR_UID_LUPD`) 
VALUES ('MMD001', 'MMD', 'A', 'A', 'A', 'MMD001', 'MMD001', '', '', sysdate(), sysdate(), sysdate(), sysdate(), 'TEST', 'SSS', 'MMD001@guud.company', '761118', '1001 - CHHLOUNG', '10 - KRATIE', 'AD', '+85516919081', '', 'benjamin.lim+dsv@guud.company_123', '', '', '', '', '', '2024-07-16 21:17:45', '0', '0', '2024-07-16 21:03:36', '2024-07-16 21:03:36', 'Default', '0', '0', '0', '0', '2024-07-16 21:05:23', 'CKUS00323', '2024-09-11 00:19:34', 'TO_DSV_001');
UPDATE  `clickargo2`.`T_CORE_USR`  SET USR_PWD = md5('MMD001Password123!') where USR_UID = 'MMD001';

insert ignore into clickargo2.T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE)
SELECT USR_UID, 'CKT', 'OFFICER', 'N', 'A', SYSDATE(), 'SYS', SYSDATE(), 'SYS','N' FROM clickargo2.T_CORE_USR
where USR_UID IN ('DSCH001','LAP001','AWOT001','MMD001');

insert ignore into clickargo2.T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE)
SELECT USR_UID, 'CKT', 'ADMIN', 'N', 'A', SYSDATE(), 'SYS', SYSDATE(), 'SYS','N' FROM clickargo2.T_CORE_USR
where USR_UID IN ('DSCH001','LAP001','AWOT001','MMD001');

insert ignore into clickargo2.T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE)
SELECT USR_UID, 'CKT', 'FF_ADMIN', 'N', 'A', SYSDATE(), 'SYS', SYSDATE(), 'SYS','N' FROM clickargo2.T_CORE_USR
where USR_UID IN ('DSCH001','LAP001','AWOT001','MMD001');

-- Contract
INSERT INTO `clickargo2`.`T_CK_CT_CONTRACT_CHARGE` (`CONC_ID`, `CONC_PLTFEE_AMT`, `CONC_ADDTAX_AMT`, `CONC_ADDTAX_TYPE`, `CONC_WHTAX_AMT`, `CONC_STATUS`, `CONC_DT_CREATE`, `CONC_UID_CREATE`, `CONC_DT_LUPD`, `CONC_UID_LUPD`) 
VALUES ('CRCHGSSADSCH1', '0.00', '0.00', 'P', '0.00', 'A', sysdate(), '', sysdate(), '');
INSERT INTO `clickargo2`.`T_CK_CT_CONTRACT_CHARGE` (`CONC_ID`, `CONC_PLTFEE_AMT`, `CONC_ADDTAX_AMT`, `CONC_ADDTAX_TYPE`, `CONC_WHTAX_AMT`, `CONC_STATUS`, `CONC_DT_CREATE`, `CONC_UID_CREATE`, `CONC_DT_LUPD`, `CONC_UID_LUPD`) 
VALUES ('CRCHGSSADSCH2', '0.00', '0.00', 'P', '0.00', 'A', sysdate(), '', sysdate(), '');
INSERT INTO `clickargo2`.`T_CK_CT_CONTRACT` (`CON_ID`, `CON_NAME`, `CON_CCY`, `CON_DT_START`, `CON_DT_END`, `CON_TO`, `CON_CHARGE_TO`, `CON_PAYTERM_TO`, `CON_CO_FF`, `CON_CHARGE_CO_FF`, `CON_PAYTERM_CO_FF`, `CON_STATUS`, `CON_DT_CREATE`, `CON_UID_CREATE`) 
VALUES ('CRCHGSSADSCH', 'SSA-DSCH', 'SGD', '2024-05-01 00:00:00', '2030-12-31 00:00:00', 'SSA', 'CRCHGSSADSCH1', '30', 'DSCH', 'CRCHGSSADSCH2', '30', 'A', SYSDATE(), 'sys');

INSERT INTO `clickargo2`.`T_CK_CT_CONTRACT_CHARGE` (`CONC_ID`, `CONC_PLTFEE_AMT`, `CONC_ADDTAX_AMT`, `CONC_ADDTAX_TYPE`, `CONC_WHTAX_AMT`, `CONC_STATUS`, `CONC_DT_CREATE`, `CONC_UID_CREATE`, `CONC_DT_LUPD`, `CONC_UID_LUPD`) 
VALUES ('CRCHGSSALAP1', '0.00', '0.00', 'P', '0.00', 'A', sysdate(), '', sysdate(), '');
INSERT INTO `clickargo2`.`T_CK_CT_CONTRACT_CHARGE` (`CONC_ID`, `CONC_PLTFEE_AMT`, `CONC_ADDTAX_AMT`, `CONC_ADDTAX_TYPE`, `CONC_WHTAX_AMT`, `CONC_STATUS`, `CONC_DT_CREATE`, `CONC_UID_CREATE`, `CONC_DT_LUPD`, `CONC_UID_LUPD`) 
VALUES ('CRCHGSSALAP2', '0.00', '0.00', 'P', '0.00', 'A', sysdate(), '', sysdate(), '');
INSERT INTO `clickargo2`.`T_CK_CT_CONTRACT` (`CON_ID`, `CON_NAME`, `CON_CCY`, `CON_DT_START`, `CON_DT_END`, `CON_TO`, `CON_CHARGE_TO`, `CON_PAYTERM_TO`, `CON_CO_FF`, `CON_CHARGE_CO_FF`, `CON_PAYTERM_CO_FF`, `CON_STATUS`, `CON_DT_CREATE`, `CON_UID_CREATE`) 
VALUES ('CRCHGSSALAP', 'SSA-LAP', 'SGD', '2024-05-01 00:00:00', '2030-12-31 00:00:00', 'SSA', 'CRCHGSSALAP1', '30', 'LAP', 'CRCHGSSALAP2', '30', 'A', SYSDATE(), 'sys');

INSERT INTO `clickargo2`.`T_CK_CT_CONTRACT_CHARGE` (`CONC_ID`, `CONC_PLTFEE_AMT`, `CONC_ADDTAX_AMT`, `CONC_ADDTAX_TYPE`, `CONC_WHTAX_AMT`, `CONC_STATUS`, `CONC_DT_CREATE`, `CONC_UID_CREATE`, `CONC_DT_LUPD`, `CONC_UID_LUPD`) 
VALUES ('CRCHGSSAAWOT1', '0.00', '0.00', 'P', '0.00', 'A', sysdate(), '', sysdate(), '');
INSERT INTO `clickargo2`.`T_CK_CT_CONTRACT_CHARGE` (`CONC_ID`, `CONC_PLTFEE_AMT`, `CONC_ADDTAX_AMT`, `CONC_ADDTAX_TYPE`, `CONC_WHTAX_AMT`, `CONC_STATUS`, `CONC_DT_CREATE`, `CONC_UID_CREATE`, `CONC_DT_LUPD`, `CONC_UID_LUPD`) 
VALUES ('CRCHGSSAAWOT2', '0.00', '0.00', 'P', '0.00', 'A', sysdate(), '', sysdate(), '');
INSERT INTO `clickargo2`.`T_CK_CT_CONTRACT` (`CON_ID`, `CON_NAME`, `CON_CCY`, `CON_DT_START`, `CON_DT_END`, `CON_TO`, `CON_CHARGE_TO`, `CON_PAYTERM_TO`, `CON_CO_FF`, `CON_CHARGE_CO_FF`, `CON_PAYTERM_CO_FF`, `CON_STATUS`, `CON_DT_CREATE`, `CON_UID_CREATE`) 
VALUES ('CRCHGSSAAWOT', 'SSA-AWOT', 'SGD', '2024-05-01 00:00:00', '2030-12-31 00:00:00', 'SSA', 'CRCHGSSAAWOT1', '30', 'AWOT', 'CRCHGSSAAWOT2', '30', 'A', SYSDATE(), 'sys');

INSERT INTO `clickargo2`.`T_CK_CT_CONTRACT_CHARGE` (`CONC_ID`, `CONC_PLTFEE_AMT`, `CONC_ADDTAX_AMT`, `CONC_ADDTAX_TYPE`, `CONC_WHTAX_AMT`, `CONC_STATUS`, `CONC_DT_CREATE`, `CONC_UID_CREATE`, `CONC_DT_LUPD`, `CONC_UID_LUPD`) 
VALUES ('CRCHGSSAMMD1', '0.00', '0.00', 'P', '0.00', 'A', sysdate(), '', sysdate(), '');
INSERT INTO `clickargo2`.`T_CK_CT_CONTRACT_CHARGE` (`CONC_ID`, `CONC_PLTFEE_AMT`, `CONC_ADDTAX_AMT`, `CONC_ADDTAX_TYPE`, `CONC_WHTAX_AMT`, `CONC_STATUS`, `CONC_DT_CREATE`, `CONC_UID_CREATE`, `CONC_DT_LUPD`, `CONC_UID_LUPD`) 
VALUES ('CRCHGSSAMMD2', '0.00', '0.00', 'P', '0.00', 'A', sysdate(), '', sysdate(), '');
REPLACE INTO `clickargo2`.`T_CK_CT_CONTRACT` (`CON_ID`, `CON_NAME`, `CON_CCY`, `CON_DT_START`, `CON_DT_END`, `CON_TO`, `CON_CHARGE_TO`, `CON_PAYTERM_TO`, `CON_CO_FF`, `CON_CHARGE_CO_FF`, `CON_PAYTERM_CO_FF`, `CON_STATUS`, `CON_DT_CREATE`, `CON_UID_CREATE`) 
VALUES ('CRCHGSSAMMD', 'SSA-MMD', 'SGD', '2024-05-01 00:00:00', '2030-12-31 00:00:00', 'SSA', 'CRCHGSSAMMD1', '30', 'MMD', 'CRCHGSSAMMD2', '30', 'A', SYSDATE(), 'sys');

-- CWL(Crane Worldwide Logistics S Pte. Ltd.)
INSERT INTO `clickargo2`.`T_CK_CT_CONTRACT_CHARGE` (`CONC_ID`, `CONC_PLTFEE_AMT`, `CONC_ADDTAX_AMT`, `CONC_ADDTAX_TYPE`, `CONC_WHTAX_AMT`, `CONC_STATUS`, `CONC_DT_CREATE`, `CONC_UID_CREATE`, `CONC_DT_LUPD`, `CONC_UID_LUPD`) 
VALUES ('CRCHGSSACWL1', '0.00', '0.00', 'P', '0.00', 'A', sysdate(), '', sysdate(), '');
INSERT INTO `clickargo2`.`T_CK_CT_CONTRACT_CHARGE` (`CONC_ID`, `CONC_PLTFEE_AMT`, `CONC_ADDTAX_AMT`, `CONC_ADDTAX_TYPE`, `CONC_WHTAX_AMT`, `CONC_STATUS`, `CONC_DT_CREATE`, `CONC_UID_CREATE`, `CONC_DT_LUPD`, `CONC_UID_LUPD`) 
VALUES ('CRCHGSSACWL2', '0.00', '0.00', 'P', '0.00', 'A', sysdate(), '', sysdate(), '');
INSERT INTO `clickargo2`.`T_CK_CT_CONTRACT` (`CON_ID`, `CON_NAME`, `CON_CCY`, `CON_DT_START`, `CON_DT_END`, `CON_TO`, `CON_CHARGE_TO`, `CON_PAYTERM_TO`, `CON_CO_FF`, `CON_CHARGE_CO_FF`, `CON_PAYTERM_CO_FF`, `CON_STATUS`, `CON_DT_CREATE`, `CON_UID_CREATE`) 
VALUES ('CRCHGSSACWL', 'SSA-CWL', 'SGD', '2024-05-01 00:00:00', '2030-12-31 00:00:00', 'SSA', 'CRCHGSSACWL1', '30', 'CWL', 'CRCHGSSACWL2', '30', 'A', SYSDATE(), 'sys');

REPLACE INTO `clickargo2`.`T_CK_CT_CONTRACT` (`CON_ID`, `CON_NAME`, `CON_CCY`, `CON_DT_START`, `CON_DT_END`, `CON_TO`, `CON_CHARGE_TO`, `CON_PAYTERM_TO`, `CON_CO_FF`, `CON_CHARGE_CO_FF`, `CON_PAYTERM_CO_FF`, `CON_STATUS`, `CON_DT_CREATE`, `CON_UID_CREATE`) 
VALUES ('CRCHGSSAMMD', 'SSA-MMD', 'SGD', '2024-05-01 00:00:00', '2030-12-31 00:00:00', 'SSA', 'CRCHGSSAMMD1', '30', 'MMD', 'CRCHGSSAMMD2', '30', 'A', SYSDATE(), 'sys');


UPDATE `clickargo2`.`T_CORE_SYSPARAM` SET `SYS_VAL` = 'docs/epod/DsvShipmentTemplate.jrxml' WHERE (`SYS_KEY` = 'CLICTRUCK_JRXML_DSV_SHIPMENT_PATH');
