/** 2024-04-26 this is for SG CT2 remaining items */
-- truck rental for TO
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_MA_031000','CKT','','','Truck Rental','Truck Rental','31000','/administrations/truckrental',NULL,'CKT_MA_030000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM074', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_MA_031000', 'Truck Rental', 'Truck Rental','Truck Rental','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'OP_ADMIN', 'PM074', 'A', NOW(), 'SYS');

-- truck leasing for SP
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_OA_081400','CKT','','','Truck Leasing','Truck Leasing','81400','/opadmin/truckleasing/list',NULL,'CKT_OA_080000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM075', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_OA_081400', 'Truck Leasing', 'Truck Leasing','Truck Leasing','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'SP_OP_ADMIN', 'PM075', 'A', NOW(), 'SYS');

-- insurance application
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_MA_032000','CKT','','','Insurance Application','Insurance Application','32000','/administrations/insuranceapp',NULL,'CKT_MA_030000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM076', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_MA_032000', 'Insurance Application', 'Insurance Application','Insurance Application','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'SP_OP_ADMIN', 'PM076', 'A', NOW(), 'SYS');

-- new account type for truck operator without jobs
INSERT INTO `T_MST_ACCN_TYPE` (`ATYP_ID`, `ATYP_DESCRIPTION`, `ATYP_STATUS`, `ATYP_DT_CREATE`, `ATYP_UID_CREATE`, `ATYP_DT_LUPD`, `ATYP_UID_LUPD`) VALUES ('ACC_TYPE_TO_WJ', 'TRUCK OPERATOR WITHOUT JOB', 'A', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'SYS');

-- co2x monitoring
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_CS_070400','CKT','','','CO2x Monitoring','CO2x Monitoring','70400','/opadmin/co2x/list',NULL,'CKT_CS_070000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM077', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_CS_070400', 'CO2x Monitoring', 'CO2x Monitoring','CO2x Monitoring','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'SP_L1', 'PM077', 'A', NOW(), 'SYS');

CREATE TABLE `T_CK_CT_CO2X` (
  `CO2X_ID` varchar(35) NOT NULL COMMENT 'RECORD ID - UUID',
  `CO2X_ACCN` varchar(35) DEFAULT NULL COMMENT 'ACCOUNT - REFERENCES T_CORE_ACCN:ACCN_ID',
  `CO2X_ACCN_NAME` varchar(1024) DEFAULT NULL COMMENT 'ACCOUNT NAME',
  `CO2X_COY_ID` varchar(1024) DEFAULT NULL COMMENT 'COMPANY ID ALLOCATED BY ASCENT',
  `CO2X_DT_EXPIRY` datetime DEFAULT NULL COMMENT 'EXPIRY DATE',
  `CO2X_UID` varchar(256) DEFAULT NULL COMMENT 'USER ID FOR SSO',
  `CO2X_PWD` varchar(256) DEFAULT NULL COMMENT 'PASSWORD FOR SSO',
  `CO2X_STATUS` char(1) DEFAULT NULL COMMENT 'CONTRACT STATE STATUS',
  `CO2X_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CO2X_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CO2X_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CO2X_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CO2X_ID`),
  CONSTRAINT `FK_CK_CT_CO2X_CORE_ACCN` FOREIGN KEY (`CO2X_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='CO2X SSO TABLE';

-- co2x monitoring for trucking operator redirect to ASCENT sso
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_CO2_100000','CKT','C02x Monitoring','C02x Monitoring','C02x Monitoring','C02x Monitoring','100000','/co2x','co2',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM078', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_CO2_100000', 'C02x Monitoring', 'C02x Monitoring','C02x Monitoring','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'OP_ADMIN', 'PM078', 'A', NOW(), 'SYS');


-- department categorization
CREATE TABLE `T_CK_CT_DEPT` (
  `DEPT_ID` varchar(35) NOT NULL COMMENT 'RECORD ID - UUID',
  `DEPT_ACCN` varchar(35) DEFAULT NULL COMMENT 'ACCOUNT - REFERENCES T_CORE_ACCN:ACCN_ID',
  `DEPT_NAME` varchar(256) DEFAULT NULL COMMENT 'DEPARTMENT NAME',
  `DEPT_DESC` varchar(1024) DEFAULT NULL COMMENT 'DEPARTMENT DESCRIPTION',
  `DEPT_COLOR` char(1) DEFAULT NULL COMMENT 'COLOR CODE - 1..9',
  `DEPT_STATUS` char(1) DEFAULT NULL COMMENT 'CONTRACT STATE STATUS',
  `DEPT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `DEPT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `DEPT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `DEPT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`DEPT_ID`),
  CONSTRAINT `FK_CK_CT_DEPT_CORE_ACCN` FOREIGN KEY (`DEPT_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DEPARTMENT TABLE';


CREATE TABLE `T_CK_CT_DEPT_USR` (
  `DU_ID` varchar(35) NOT NULL COMMENT 'RECORD ID - UUID',
  `DU_DEPT` varchar(35) DEFAULT NULL COMMENT 'DEPARTMENT - REFERENCES T_CK_CT_DEPT:DEPT_ID',
  `DU_USR` varchar(35) DEFAULT NULL COMMENT 'DEPARTMENT USER - REFERENCES T_CORE_USR:USR_UID',
  `DU_STATUS` char(1) DEFAULT NULL COMMENT 'CONTRACT STATE STATUS',
  `DU_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `DU_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `DU_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `DU_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`DU_ID`),
  CONSTRAINT `FK_CK_CT_DU_CK_CT_DEPT` FOREIGN KEY (`DU_DEPT`) REFERENCES `T_CK_CT_DEPT` (`DEPT_ID`),  
  CONSTRAINT `FK_CK_CT_DU_CORE_USR` FOREIGN KEY (`DU_USR`) REFERENCES `T_CORE_USR` (`USR_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DEPARTMENT USERS TABLE';


CREATE TABLE `T_CK_CT_DEPT_VEH` (
  `DV_ID` varchar(35) NOT NULL COMMENT 'RECORD ID - UUID',
  `DV_DEPT` varchar(35) DEFAULT NULL COMMENT 'DEPARTMENT - REFERENCES T_CK_CT_DEPT:DEPT_ID',
  `DV_VEH` varchar(35) DEFAULT NULL COMMENT 'DEPARTMENT USER - REFERENCES T_CK_CT_VEH:VH_ID',
  `DV_STATUS` char(1) DEFAULT NULL COMMENT 'CONTRACT STATE STATUS',
  `DV_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `DV_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `DV_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `DV_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`DV_ID`),
  CONSTRAINT `FK_CK_CT_DV_CK_CT_DEPT` FOREIGN KEY (`DV_DEPT`) REFERENCES `T_CK_CT_DEPT` (`DEPT_ID`),  
  CONSTRAINT `FK_CK_CT_DV_CORE_USR` FOREIGN KEY (`DV_VEH`) REFERENCES `T_CK_CT_VEH` (`VH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DEPARTMENT VEHICLE TABLE';

INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_MA_033000','CKT','','','Manage Department','Manage Department','33000','/administrations/department/list',NULL,'CKT_MA_030000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM079', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_MA_033000', 'Manage Department', 'Manage Department','Manage Department','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'OP_ADMIN', 'PM079', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'ADMIN', 'PM079', 'A', NOW(), 'SYS');





DROP TABLE IF EXISTS T_CK_JOB_UPLOAD;

CREATE TABLE `T_CK_JOB_UPLOAD` (
  `UP_ID` varchar(35) NOT NULL COMMENT 'RECORD FILE LOG ID - UUID',
  `UP_ACCN_ID` varchar(35) DEFAULT NULL COMMENT 'ACCOUNT ID',
  `UP_FILE_NAME` varchar(256) DEFAULT NULL COMMENT 'EXCEL FILE NAME',
  `UP_FILE_PATH` varchar(512) DEFAULT NULL COMMENT 'EXCEL FILE NAME AND PATH IN LOCAL',
  `UP_FILE_SIZE` int DEFAULT NULL COMMENT 'EXCEL FILE LEGNTH',
  `UP_TOTAL_LINES` int DEFAULT NULL COMMENT 'EXCEL FILE TOTAL LINES',
  `UP_SUCCESS_JOB_IDS` varchar(2048) DEFAULT NULL COMMENT 'SUCCESS LINES AND JOBID: 2:JOBID, 4:JOBID, 6:JOBID, 8:JOBID',
  `UP_FAIL_LINES` varchar(2048) DEFAULT NULL COMMENT 'FAILED LINES: 1,3,5,7',
  `UP_REMARK` varchar(2048) DEFAULT NULL,
  `UP_STATUS` char(1) DEFAULT NULL COMMENT 'OPM STATE STATUS',
  `UP_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `UP_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `UP_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `UP_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`UP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='JOB UPLOAD LOG TABLE';

ALTER TABLE `clickargo2`.`T_CK_ACCN` 
ADD COLUMN `CACCN_EXCEL_TEMPLATE` TEXT NULL COMMENT 'EXCEL TEMPLATE FOR JOB UPLOAD' AFTER `CACCN_FINANCER`;

-- Shell card integration
CREATE TABLE `T_CK_CT_SHELL_CARD` (
  `SC_ID` varchar(35) NOT NULL COMMENT 'CARD ID',
  `SC_DT_EXPIRY` datetime DEFAULT NULL COMMENT 'CARD EXPIRY DATE',
  `SC_STATUS` char(1) DEFAULT NULL COMMENT 'CARD STATUS - A:ACTIVE I:EXPIRED',
  `SC_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `SC_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `SC_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `SC_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`SC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='SHELL CARD TABLE';


CREATE TABLE `T_CK_CT_SHELL_KIOSK` (
  `SK_ID` varchar(35) NOT NULL COMMENT 'KIOSK ID',
  `SK_NAME` varchar(1024) DEFAULT NULL COMMENT 'KIOSK NAME',
  `SK_STATUS` char(1) DEFAULT NULL COMMENT 'KIOSK STATE STATUS - A:ACTIVE I:EXPIRED',
  `SK_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `SK_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `SK_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `SK_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`SK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='SHELL KIOSK TABLE';


CREATE TABLE `T_CK_CT_SHELL_BATCH_WINDOW` (
  `SB_ID` varchar(35) NOT NULL COMMENT 'BATCH ID - UNIQUE ID',
  `SB_NAME` varchar(1024) DEFAULT NULL COMMENT 'BATCH NAME',
  `SB_DT_WINDOW` datetime DEFAULT NULL COMMENT 'BATCH WINDOW',
  `SB_STATUS` char(1) DEFAULT NULL COMMENT 'BATCH STATUS - A:ACTIVE I:EXPIRED',
  `SB_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `SB_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `SB_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `SB_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`SB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='SHELL BATCH WINDOW TABLE';


CREATE TABLE `T_CK_CT_SHELL_TXN` (
  `ST_ID` varchar(35) NOT NULL COMMENT 'TXN ID - UNIQUE ID',
  `ST_CARD` varchar(35) DEFAULT NULL COMMENT 'CARD PAN NUMBER - REFERENCE T_CK_CT_SHELL_CARD:SC_ID',
  `ST_ACCN` varchar(35) DEFAULT NULL COMMENT 'CARD ASSOICATED ACCOUNT - REFERENCE T_CORE_ACCN:ACCN_ID',  
  `ST_QTY` decimal(8,2) DEFAULT 0.0 COMMENT 'TXN QUANTITY',
  `ST_PRODUCT` varchar(512) DEFAULT NULL COMMENT 'TXN PRODUCT NAME',
  `ST_TXN_ID` varchar(256) DEFAULT NULL COMMENT 'TXN ID FROM SHELL',
  `ST_TXN_DATE` datetime DEFAULT NULL COMMENT 'TXN DATE TIME',
  `ST_INV_NET` decimal(15,2) DEFAULT 0.0 COMMENT 'TXN INVOICE NET - BEFORE TAX',
  `ST_INV_GROSS` decimal(15,2) DEFAULT 0.0 COMMENT 'TXN INVOICE GROSS - AFTER TAX',
  `ST_CRV_NET` decimal(15,2) DEFAULT 0.0 COMMENT 'CUSTOMER RETAIL VALUE NET - BEFORE TAX',
  `ST_CRV_GROSS` decimal(15,2) DEFAULT 0.0 COMMENT 'CUSTOMER RETAIL VALUE GROSS - AFTER TAX',
  `SB_STATUS` char(1) DEFAULT NULL COMMENT 'BATCH STATUS - A:ACTIVE I:EXPIRED',
  `SB_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `SB_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `SB_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `SB_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`ST_ID`),
  CONSTRAINT `FK_CK_CT_SHELL_TXN_CK_CT_SHELL_CARD` FOREIGN KEY (`ST_CARD`) REFERENCES `T_CK_CT_SHELL_CARD` (`SC_ID`),
  CONSTRAINT `FK_CK_CT_SHELL_TXN_CORE_ACCN` FOREIGN KEY (`ST_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='SHELL TXN TABLE';


CREATE TABLE `T_CK_CT_SHELL_CARD_TRUCK` (
  `CT_ID` varchar(35) NOT NULL COMMENT 'ASSIGNMENT ID - UUID',
  `CT_ACCN` varchar(35) DEFAULT NULL COMMENT 'ACCN - REFERENCES T_CORE_ACCN:ACCN_ID',
  `CT_TRUCK` varchar(35) DEFAULT NULL COMMENT 'TRUCK - REFERENCES T_CK_CT_VEH:VH_ID',
  `CT_CARD` varchar(35) DEFAULT NULL COMMENT 'CARD - REFERENCES T_CK_CT_SHELL_CARD:SC_ID',
  `CT_STATUS` char(1) DEFAULT NULL COMMENT 'ASSIGNMENT STATUS - A:ACTIVE I:INACTIVE',
  `CT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CT_ID`),
  CONSTRAINT `FK_CK_CT_SHELL_CARD_TRUCK_CORE_ACCN` FOREIGN KEY (`CT_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_CT_SHELL_CARD_TRUCK_CK_CT_VEH` FOREIGN KEY (`CT_TRUCK`) REFERENCES `T_CK_CT_VEH` (`VH_ID`),
  CONSTRAINT `FK_CK_CT_SHELL_CARD_TRUCK_CK_CT_SHELL_CARD` FOREIGN KEY (`CT_CARD`) REFERENCES `T_CK_CT_SHELL_CARD` (`SC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='SHELL CARD ASSIGNMENT TABLE';


CREATE TABLE `T_CK_CT_SHELL_INVOICE` (
  `INV_ID` varchar(35) NOT NULL COMMENT 'INVOICE ID - UNIQUE ID',
  `INV_NO` varchar(256) DEFAULT NULL COMMENT 'INVOICE NUMNER',
  `INV_ACCN` varchar(35) DEFAULT NULL COMMENT 'CARD ASSOICATED ACCOUNT - REFERENCE T_CORE_ACCN:ACCN_ID',  
  `INV_DT` datetime DEFAULT NULL COMMENT 'INVOICE DATE',
  `INV_AMT` decimal(15,2) DEFAULT 0.0 COMMENT 'INVOICE AMT', 
  `INV_PAYMENT_DT` datetime DEFAULT NULL COMMENT 'INVOICE PAYMENT DATE',
  `INV_PAYMENT_AMT` decimal(15,2) DEFAULT 0.0 COMMENT 'PAYMENT AMT', 
  `INV_BALANCE_AMT` decimal(15,2) DEFAULT 0.0 COMMENT 'BALANCE AMT', 
  `INV_STATUS` char(1) DEFAULT NULL COMMENT 'INVOICE STATUS - A:ACTIVE P:APID',
  `INV_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `INV_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `INV_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `INV_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`INV_ID`),
  CONSTRAINT `FK_CK_CT_SHELL_INVOICE_CORE_ACCN` FOREIGN KEY (`INV_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='SHELL INVOICE TABLE';


CREATE TABLE `T_CK_CT_SHELL_INVOICE_ITEM` (
  `ITM_ID` varchar(35) NOT NULL COMMENT 'INVOICE ITEM ID - UNIQUE ID',
  `ITM_INV` varchar(256) DEFAULT NULL COMMENT 'INVOICE - REFERENCE T_CK_CT_SHELL_INVOICE:INV_ID',
  `ITM_TRUCK` varchar(35) DEFAULT NULL COMMENT 'TRUCK - REFERENCES T_CK_CT_VEH:VH_ID',
  `ITM_CARD` varchar(35) DEFAULT NULL COMMENT 'CARD - REFERENCES T_CK_CT_SHELL_CARD:SC_ID',
  `ITM_DESC` varchar(512) DEFAULT NULL COMMENT 'ITEM DESCRIPTION',
  `ITM_DT_TXN` datetime DEFAULT NULL COMMENT 'TRANSACTION DATE TIME',
  `ITM_COST` decimal(15,2) DEFAULT 0.0 COMMENT 'ITEM COST',
  `ITM_DISCOUNT` decimal(15,2) DEFAULT 0.0 COMMENT 'DISCOUNT AMOUNT',
  `ITM_TAX` decimal(15,2) DEFAULT 0.0 COMMENT 'TAX AMOUNT',
  `ITM_CO2` decimal(15,2) DEFAULT 0.0 COMMENT 'CO2 COMPENSATION FEE',
  `ITM_TOTAL` decimal(15,2) DEFAULT 0.0 COMMENT 'TOTAL AMOUNT FOR ITEM LINE',
  `ITM_STATUS` char(1) DEFAULT NULL COMMENT 'INVOICE STATUS - A:ACTIVE P:APID',
  `ITM_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `ITM_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `ITM_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `ITM_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`ITM_ID`),
  CONSTRAINT `FK_CK_CT_SHELL_INVOICE_ITEM_CK_CT_SHELL_INVOICE` FOREIGN KEY (`ITM_INV`) REFERENCES `T_CK_CT_SHELL_INVOICE` (`INV_ID`),
  CONSTRAINT `FK_CK_CT_SHELL_INVOICE_ITEM_CK_CT_VEH` FOREIGN KEY (`ITM_TRUCK`) REFERENCES `T_CK_CT_VEH` (`VH_ID`),
  CONSTRAINT `FK_CK_CT_SHELL_INVOICE_ITEM_CK_CT_SHELL_CARD` FOREIGN KEY (`ITM_CARD`) REFERENCES `T_CK_CT_SHELL_CARD` (`SC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='SHELL INVOICE ITEM TABLE';


-- menu navigation for shell card management
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_CS_070500','CKT','','','Shell Card Management','Shell Card Management','70500','/opadmin/shellcard',NULL,'CKT_CS_070000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM080', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_CS_070500', 'Shell Card Management', 'Shell Card Management','Shell Card Management','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'SP_OP_ADMIN', 'PM080', 'A', NOW(), 'SYS');

/** 2024-05-06 this INERT TRUCKS RENTALS PROVIDERS TO SYS PARAMS */
CREATE TABLE `T_CK_CT_RENTAL_APP` (
    `VR_ID` varchar(35) NOT NULL COMMENT 'RENTAL ID - UUID',
    `VR_ACCN` varchar(35) DEFAULT NULL COMMENT 'ACCN INTIATING THE RENTAL - REFERENCES T_CORE_ACCN:ACCN_ID',
    `VR_PROVIDER` varchar(256) DEFAULT NULL COMMENT 'RENTAL PROVIDER',
    `VR_TRUCK` varchar(256) DEFAULT NULL COMMENT 'RENTAL TRUCK',
    `VR_LEASE` smallint DEFAULT 0 COMMENT 'RENTAL LEASE PERIOD',
    `VR_PRICE` decimal(15,2) DEFAULT 0.0 COMMENT 'RENTAL PRICE',
    `VR_QTY` smallint DEFAULT 0 COMMENT 'RENTAL QUANTITY',
    `VR_CT_NAME` varchar(256) DEFAULT NULL COMMENT 'CONTACT NAME',
    `VR_CT_MOBILE` varchar(256) DEFAULT NULL COMMENT 'CONTACT MOBILE',
    `VR_CT_EMAIL` varchar(256) DEFAULT NULL COMMENT 'CONTACT EMAIL',
    `VR_STATUS` char(1) DEFAULT NULL COMMENT 'VEHICLE STATE STATUS – N:NEW S:SUCCESS R:REJCTED',
    `VR_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
    `VR_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
    `VR_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
    `VR_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
    PRIMARY KEY (`VR_ID`),
    CONSTRAINT `FK_CK_CT_RENTAL_CORE_ACCN` FOREIGN KEY (`VR_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='VEHICLE RENTAL APPLICATION TABLE';

-- sso url for co2 connect
INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_CO2_CONNECT', 'https://co2xconnect.com/api/co2/sso/subscribe-login', 'SSO for CO2 Connect subscribers', '2023-12-04 03:27:26', 'SYS', '2023-12-04 03:27:26', 'SYS', 'A');


-- new user role for ACC_TYPE_TO_WJ (TO without job), if we are to use the OP_ADMIN, the rest of the OPERATIONS ADMIN menu will be visible
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','OP_ADMIN_WJ','A','OPERATIONS ADMIN FOR WJ ACCOUNTS',NOW(),'SYS',NOW(),'SYS');
-- grant menus for the new role
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'OP_ADMIN_WJ', 'PM029', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'OP_ADMIN_WJ', 'PM079', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'OP_ADMIN_WJ', 'PM037', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'OP_ADMIN_WJ', 'PM038', 'A', NOW(), 'SYS');

-- to associate job with department if the CO user who created the job belongs to department, or if TO user who accepted the job belongs to a department
ALTER TABLE `clickargo2`.`T_CK_JOB_TRUCK`
ADD COLUMN `JOB_CO_DEPARTMENT` VARCHAR(35) NULL AFTER `JOB_PROCESS_VIA`,
ADD COLUMN `JOB_TO_DEPARTMENT` VARCHAR(35) NULL AFTER `JOB_CO_DEPARTMENT`,
ADD INDEX `FK_CK_JOB_TRUCK_K_CO_DEPT_idx` (`JOB_CO_DEPARTMENT` ASC) VISIBLE,
ADD INDEX `FK_CK_JOB_TRUCK_K_TO_DEPT_idx` (`JOB_TO_DEPARTMENT` ASC) VISIBLE;
;
ALTER TABLE `clickargo2`.`T_CK_JOB_TRUCK`
ADD CONSTRAINT `FK_CK_JOB_TRUCK_K_CO_DEPT`
  FOREIGN KEY (`JOB_CO_DEPARTMENT`)
  REFERENCES `clickargo2`.`T_CK_CT_DEPT` (`DEPT_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `clickargo2`.`T_CK_JOB_TRUCK`
ADD CONSTRAINT `FK_CK_JOB_TRUCK_K_TO_DEPT`
  FOREIGN KEY (`JOB_TO_DEPARTMENT`)
  REFERENCES `clickargo2`.`T_CK_CT_DEPT` (`DEPT_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
-- UPDATE TO ADD NEW JSON  DASHBOARD
UPDATE T_CORE_SYSPARAM  SET SYS_VAL='[{"id":0,"dbType":"TRACKING","transStatistic":{},"accnType":"ACC_TYPE_CO"},{"id":0,"dbType":"TRACKING","transStatistic":{"ONGOING":0},"accnType":"ACC_TYPE_TO"},{"id":0,"dbType":"TRACKING","transStatistic":{},"accnType":"ACC_TYPE_FF"},{"id":0,"dbType":"TRUCK_TRACKING","transStatistic":{},"accnType":"ACC_TYPE_TO_WJ"},{"id":1,"dbType":"TRUCK_JOBS","transStatistic":{"NEW":0,"ONGOING":0},"accnType":"ACC_TYPE_TO"},{"id":2,"dbType":"TRUCK_JOBS","transStatistic":{},"accnType":"ACC_TYPE_CO"},{"id":3,"dbType":"TRUCK_JOBS","transStatistic":{"ACTIVE":0},"accnType":"ACC_TYPE_FF"},{"id":4,"dbType":"DRIVER_AVAILABILITY","transStatistic":{"ASSIGNED":0,"UNASSIGNED":0},"accnType":"ACC_TYPE_TO"},{"id":5,"dbType":"DRIVER_AVAILABILITY","transStatistic":{"ASSIGNED":0,"UNASSIGNED":0},"accnType":"ACC_TYPE_CO"},{"id":6,"dbType":"DRIVER_AVAILABILITY","transStatistic":{"ASSIGNED":0,"UNASSIGNED":0},"accnType":"ACC_TYPE_FF"}]' WHERE SYS_KEY='CLICTRUCK_DEFAULT_DASHBOARD';
ALTER TABLE `clickargo2`.`T_CK_JOB_TRUCK` 
ADD COLUMN `JOB_DT_EPOD` DATETIME NULL COMMENT 'SEND EPOD TIME' AFTER `JOB_TO_DEPARTMENT`;

-- ADD SCRIPT FOR ASSURE FORM TO T_CORE_SYSPARAM
INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_INSURER_ASSURE_FORM', '{\r\n    \"coverage\": [\r\n        \"Comprehensive\",\r\n		\"Liability coverage\",\r\n		\"Comprehensive coverage\"\r\n    ],\r\n    \"usage\": [\r\n        \"Commercial\",\r\n		\"Social only\",\r\n		\"Social and commuting\"\r\n    ],\r\n    \"claims\": [\r\n        \"Yes\",\r\n        \"No\"\r\n    ],\r\n    \"suspension\": [\r\n        \"Yes\",\r\n        \"No\"\r\n    ]\r\n} ', 'CLICTRUCK_INSURER_ASSURE_FORM', '2024-04-30 00:00:00', 'SYS', '2024-04-30 00:00:00', 'SYS', 'A');
INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_INSURER_ASSURE_TMPLT', 'sagar.subudhi@guud.company', 'CLICTRUCK_INSURER_ASSURE_TMPLT', '2024-04-30 00:00:00', 'SYS', '2024-04-30 00:00:00', 'SYS', 'A');
INSERT INTO `clickargo2`.`T_CORE_NOTIFICATION_TEMPLATE` (`NTPL_ID`, `NTPL_APPSCODE`, `NTPL_CHANNEL_TYPE`, `NTPL_CONTENT_TYPE`, `NTPL_SUBJECT`, `NTPL_TEMPALTE`, `NTPL_SEQ`, `NTPL_DESC`, `NTPL_STATUS`, `NTPL_UID_CREATE`, `NTPL_DT_CREATE`, `NTPL_UID_LUPD`, `NTPL_DT_LUPD`) VALUES ('CKT_NTL_00100', 'CKT', 'CHN_TYPE_EMAIL', 'CNT_TYPE_HTML', 'Insurance Application', '<html> <style> html, body{font-family: \"Roboto\", sans-serif;} #container {width: 800px;border: 1px solid gray;padding: 10px 20px;} .innerContainer {padding: 0px 0px;} #footerContainer {background-color: #f2f3f4;color: darkslategray;padding: 5px 15px;margin-top: 15px;} .button {width: 300px;height: 50px;background-color:steelblue;color: white;margin:50px 0px;justify-content: center;align-items: center;display: flex;} \r\n</style> <body> <div id=container> <div id=titleContainer class=innerContainer> \r\n<img width=100 height=62 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> \r\n<div id=bodyContainer class=innerContainer> <h1>Appliation Insurance submitted!</h1>\r\n<p>Make sure you have checked the attachment.</p>\r\n</div> </div> </body> </html>', 50, 'Insurance Application', 'A', 'SYS', '2024-10-25 01:57:10', 'SYS', '2024-10-25 01:57:10');


ALTER TABLE `clickargo2`.`T_CK_ACCN` 
ADD COLUMN `CACCN_EPOD_JRXML` VARCHAR(256) NULL COMMENT 'EPOD JRXML FILE PATH' AFTER `CACCN_EXCEL_TEMPLATE`;

ALTER TABLE `clickargo2`.`T_CK_ACCN` 
ADD COLUMN `CACCN_EPOD_SERVICE` VARCHAR(256) NULL COMMENT 'EPOD SPRING BEEN SERVICE NAME' AFTER `CACCN_EPOD_JRXML`;


-- Menu Navigation for Shell Card Transaction Payments
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_FN_070400','CKT','','','Shell Card Payments','Shell Card Payments','70400','/shell/payments',NULL,'CKT_FN_070000','A',NOW(),'SYS',NOW(),'SYS');

INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM081', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_FN_070400', 'Shell Card Payments', 'Shell Card Payments','Shell Card Payments','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');

INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'SP_FIN_HD', 'PM081', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'SP_FIN_ADMIN', 'PM081', 'A', NOW(), 'SYS');

-- - -  - - - - - -  - - - - - -  - - - - - - - - - - - -- - - - - -

-- Shell SYS Params (CREDENTIAL & INVOICING DISCOUNT)
INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_SHEL_CREDENTIAL_TYPE', '{\"url\":\"https://api-test.shell.com\",\"secondaryUrl\":\"https://api-test.shell.com/test\",\"apikey\":\"h1E0frAhGADRzGX5oVAa9vE30efAAmyM\",\"secret\":\"DRPwxF7iKddpjf1X\",\"colcocode\":87,\"colcoid\":87,\"colcocode1\":5,\"colcoid1\":5,\"payer_number\":\"SG00008809\",\"account_number\":\"SG00008809\",\"payer_number1\":\"GB00000001\",\"payer_number2\":\"SG00000041\",\"account_number1\":\"GB00000001\",\"apikeyT1\":\"Sq9C95PeqUJBXYE7nqOc1C3GTGtAYJGW\",\"secretT1\":\"SGX8aCicZHOEvGG1\"}', 'Shell APIs Credential', '2024-05-10 00:00:00', 'SYS', '2024-05-10 00:00:00', 'SYS', 'A');
INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_SHELL_INVOICING_DISCOUNT', '[{\"accn\":\"GUUD\",\"discount\":{\"petrol\":\"5.0\",\"dissels\":\"8.0\",\"lubricant\":\"7.0\",\"electric\":\"2.0\"}},{\"accn\":\"BREAM\",\"discount\":{\"petrol\":\"5.0\",\"dissels\":\"4.1\",\"lubricant\":\"5.7\",\"electric\":\"2.0\"}}]', 'Shell Invoicing Discount', '2024-05-23 00:00:00', 'SYS', '2024-05-23 00:00:00', 'SYS', 'A');
-- INV NO Seq
INSERT INTO `clickargo2`.`T_CK_SEQUENCE_NO` (`SQN_ID`, `SQN_DESC`, `SQN_KEY`, `SQN_SEQ`, `SQN_DT_CREATE`, `SQN_UID_CREATE`, `SQN_DT_LUPD`, `SQN_UID_LUPD`) VALUES ('CT_SHELL_INV_NO', 'CT SHELL INVOICE NO', 'CT-INV-YYMMDD-%05d', 1, '2024-05-21 03:47:51', 'SYS', '2024-05-21 11:52:49', 'SYS');
-- Shell Cards & Invoicing for TO Admin
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_MA_060800','CKT','','','Shell Cards & Invoicing','Shell Cards & Invoicing','60800','/administrations/shellInvoicing',NULL,'CKT_MA_030000','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM082', 'N', 'CKT', NULL, 'M', NULL, NULL, 'CKT_MA_060800', 'Shell Cards & Invoicing', 'Shell Cards & Invoicing','Shell Cards & Invoicing','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'OP_ADMIN', 'PM082', 'A', NOW(), 'SYS');
-- Shell Batch Window update transaction daily default date (2024-05-01 22:59:59)
INSERT INTO `clickargo2`.`T_CK_CT_SHELL_BATCH_WINDOW` (`SB_ID`, `SB_NAME`, `SB_DT_WINDOW`, `SB_STATUS`, `SB_DT_CREATE`, `SB_UID_CREATE`, `SB_DT_LUPD`, `SB_UID_LUPD`) VALUES ('SHELL_CARD_TXN', 'Shell Card Transaction Batch Update', '2024-05-27 00:58:38', 'A', '2024-05-01 22:59:59', 'SYS', '2024-05-01 22:59:44', 'SYS');

-- ------ - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

-- Updated notification template for account registration approval
UPDATE `clickargo2`.`T_CORE_NOTIFICATION_TEMPLATE` SET `NTPL_TEMPALTE` = '<html> <style> html, body{font-family: \"Roboto\", sans-serif;} #container {width: 800px;border: 1px solid gray;padding: 10px 20px;} .innerContainer {padding: 0px 0px;} #footerContainer {background-color: #f2f3f4;color: darkslategray;padding: 5px 15px;margin-top: 15px;} .button {width: 300px;height: 50px;background-color:steelblue;color: white;margin:50px 0px;justify-content: center;align-items: center;display: flex;} </style> <body> <div id=container> <div id=titleContainer class=innerContainer> <img width=100 height=62 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> <div id=bodyContainer class=innerContainer> <h1>Account Registration approved!</h1> <p> :accnName</p> <p>For a complete details, <a href=:accnRegLink>click here</a></p>  </div> <div id=footerContainer class=innerContainer> <p>:sp_details</p> <img width=50 height=31 src=https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png> </div> </div> </body> </html>' WHERE (`NTPL_ID` = 'CKT_NTL_0017') and (`NTPL_APPSCODE` = 'CKT');

/** 2024-06-04 Inert trucks rentals providers to sys params base json path */
INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_TRUCKS_RENTAL_PROVIDERS', '/home/vcc/appAttachments/clictruck/json', 'Clictruck truck providers JSON location', '2024-06-04 00:00:00', 'SYS', '2024-06-04 17:14:40', 'GLI_SYS_ADMIN', 'A');
-- upload the file truck_providers.json in /home/vcc/appAttachments

-- truck provider email template
INSERT INTO `clickargo2`.`T_CORE_NOTIFICATION_TEMPLATE` (`NTPL_ID`, `NTPL_APPSCODE`, `NTPL_CHANNEL_TYPE`, `NTPL_CONTENT_TYPE`, `NTPL_SUBJECT`, `NTPL_TEMPALTE`, `NTPL_SEQ`, `NTPL_DESC`, `NTPL_STATUS`, `NTPL_UID_CREATE`, `NTPL_DT_CREATE`, `NTPL_UID_LUPD`, `NTPL_DT_LUPD`) VALUES ('CKT_NTL_0063', 'CKT', 'CHN_TYPE_EMAIL', 'CNT_TYPE_HTML', 'Truck Rental Submitted', '<!DOCTYPE html><html><style>body,html{font-family:Roboto,sans-serif}#container{width:800px;border:1px solid gray;padding:10px 20px}.innerContainer{padding:0 0}#footerContainer{background-color:#f2f3f4;color:#2f4f4f;padding:5px 15px;margin-top:15px}.button{width:300px;height:50px;background-color:#4682b4;color:#fff;margin:50px 0;justify-content:center;align-items:center;display:flex}</style><body><div id=\"container\"><div id=\"titleContainer\" class=\"innerContainer\"><img width=\"100\" height=\"62\" src=\"https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png\"></div><div id=\"bodyContainer\" class=\"innerContainer\"><h1>Truck Rental request has been submitted to you!</h1><p>Request from&nbsp;<i>:jobNumber</i>&nbsp;has been submitted to you!</p></p></div><div id=\"footerContainer\" class=\"innerContainer\"><p>:sp_details</p><img width=\"50\" height=\"31\" src=\"https://home.clickargo.com/wp-content/uploads/2022/02/Clic-Logo_Colour-300x187.png\"></div></div></body></html>', 63, 'Notification to Truck Provider when TO procced to submitted.', 'A', 'SYS', '2024-06-11 13:55:37', 'SYS', '2024-06-11 13:55:37');

-- truck location history api acent
INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_TRUCK_LOCATION_HISTORY', '{\"apiUrl\":\"https://ext.logistics.myascents.net/api/3rdparty/unit/historical2\",\"apiKey\":\"$2a$11$26PJS1FkqWkvQdq2H0m1EOukmOlnkfmkoANJMGaKuVXU7bpT0zS3C\"}', 'Truck Location History', '2024-06-18 00:00:00', 'SYS', '2024-05-10 00:00:00', 'SYS', 'A');

-- Remove assigning the parent menu 
DELETE FROM `clickargo2`.`T_CORE_GRANT_ROLE_EX` WHERE (`GNTRLEX_APPS_CODE` = 'CKT') and (`GNTRLEX_ROLE_ID` = 'OP_ADMIN') and (`GNTRLEX_PERM_ID` = 'PM028');

-- insert child menu of Administration
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'OP_ADMIN', 'PM070', 'A', NOW(), 'SYS');
INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'OP_ADMIN', 'PM076', 'A', NOW(), 'SYS');


REPLACE INTO `clickargo2`.`T_CK_CT_MST_SHIPMENT_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`)
 VALUES ('NEED_NOT_CREATE_JOB_MIGRATION', 'NEED_NOT_CREATE_JOB_MIGRATION', 'NEED_NOT_CREATE_JOB_MIGRATION', 'A', sysdate(), 'sys');

REPLACE INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_STATUS`) 
VALUES ('CLICKTRUCK_DSV_CHECK_SCHEDULEDSHIPMENTARRIVAL', 'Y', 'CLICKTRUCK_DSV_CHECK_SCHEDULEDSHIPMENTARRIVAL', sysdate(), 'SYS', 'A');

REPLACE INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_STATUS`) 
VALUES ('CLICKTRUCK_DSV_EXCEL_UPLOAD_CHECK_DELIVERY_DATE', 'Y', 'CLICKTRUCK_DSV_EXCEL_UPLOAD_CHECK_DELIVERY_DATE', sysdate(), 'SYS', 'A');

-- update report script for RPT_ALL_JOBS_TO
UPDATE `clickargo2`.`T_CORE_RPT_TABLE` SET `RPTT_NAME` = 'All Trucking Jobs', `RPTT_WIDTH_PERC` = 100.0000, `RPTT_SHOW` = 'Y', `RPTT_COLS` = 0, `RPTT_RPT_QRY` = 'SELECT TRUCK.JOB_ID    												 AS JOB_ID,\r\n          JOB.JOB_SHIPMENT_TYPE                                      AS SHIPMENT_TYPE,\r\n          IFNULL(DATE_FORMAT(TRUCK.JOB_DT_BOOKING, \'%Y-%m-%d\'), \'-\') AS JOB_DT_BOOKING,\r\n          STATE.JBST_NAME                                            AS JOB_STATE,\r\n          COFF_ACCN.ACCN_NAME                                        AS CO_FF_ACCN,\r\n          TO_ACCN.ACCN_NAME                                          AS TO_ACCN,\r\n          TRIP_LOC_FROM.TLOC_LOC_NAME                                AS TLOC_LOC_NAME_FROM,\r\n          TRIP_LOC_TO.TLOC_LOC_NAME                                  AS TLOC_LOC_NAME_TO,\r\n          ( CASE\r\n              WHEN TRUCK.JOB_DRV IS NOT NULL THEN (SELECT DRV.DRV_NAME FROM T_CK_CT_DRV DRV WHERE DRV.DRV_ID = TRUCK.JOB_DRV)\r\n			  WHEN TRUCK.JOB_DRV IS NULL AND TRUCK.JOB_DRV_OTH IS NULL THEN \'-\'\r\n              WHEN TRUCK.JOB_DRV IS NULL THEN SUBSTRING_INDEX(SUBSTRING_INDEX(TRUCK.JOB_DRV_OTH, \'drvName=\', -1), \'}\', 1)\r\n              ELSE TRUCK.JOB_DRV\r\n            END )                                                    AS DRV_NAME,\r\n          ( CASE\r\n              WHEN TRUCK.JOB_VEH IS NOT NULL THEN (SELECT VEH.VH_PLATE_NO FROM T_CK_CT_VEH VEH WHERE  VEH.VH_ID = TRUCK.JOB_VEH)\r\n			  WHEN TRUCK.JOB_VEH IS NULL AND TRUCK.JOB_VEH_OTH IS NULL THEN \'-\'\r\n              WHEN TRUCK.JOB_VEH IS NULL THEN SUBSTRING_INDEX(SUBSTRING_INDEX(TRUCK.JOB_VEH_OTH, \'vhPlateNo=\', -1), \',\', 1)\r\n              ELSE TRUCK.JOB_VEH\r\n            END )                                                    AS VH_PLATE_NO,\r\n		  ( CASE\r\n              WHEN TRUCK.JOB_PROCESS_VIA IS NULL THEN \'WEB\' ELSE TRUCK.JOB_PROCESS_VIA\r\n            END )  AS PROCESS_VIA,\r\n            \r\n          IFNULL(DATE_FORMAT(RECORD.RCD_DT_SUBMIT, \'%Y-%m-%d\'), \'-\') AS RCD_DT_SUBMIT,\r\n		  IFNULL(DATE_FORMAT(RECORD.RCD_DT_CANCEL, \'%Y-%m-%d\'), \'-\') AS RCD_DT_CANCEL,\r\n		  IFNULL(DATE_FORMAT(RECORD.RCD_DT_ACCEPTED, \'%Y-%m-%d\'), \'-\') AS RCD_DT_ACCEPTED,\r\n		  IFNULL(DATE_FORMAT(RECORD.RCD_DT_START, \'%Y-%m-%d\'), \'-\') AS RCD_DT_START,\r\n          IFNULL(DATE_FORMAT(RECORD.RCD_DT_COMPLETE, \'%Y-%m-%d\'), \'-\') AS RCD_DT_COMPLETE\r\n   FROM   T_CK_JOB_TRUCK TRUCK\r\n          LEFT JOIN T_CK_JOB JOB\r\n                 ON TRUCK.JOB_PARENT = JOB.JOB_ID\r\n          LEFT JOIN T_CK_CT_TRIP TRIP\r\n                 ON TRIP.TR_JOB = TRUCK.JOB_ID\r\n          LEFT JOIN T_CK_CT_TRIP_LOCATION TRIP_LOC_FROM\r\n                 ON TRIP_LOC_FROM.TLOC_ID = TRIP.TR_FROM\r\n          LEFT JOIN T_CK_CT_TRIP_LOCATION TRIP_LOC_TO\r\n                 ON TRIP_LOC_TO.TLOC_ID = TRIP.TR_TO\r\n          LEFT JOIN T_CORE_ACCN COFF_ACCN\r\n                 ON COFF_ACCN.ACCN_ID = TRUCK.JOB_PARTY_CO_FF\r\n          LEFT JOIN T_CORE_ACCN TO_ACCN\r\n                 ON TO_ACCN.ACCN_ID = TRUCK.JOB_PARTY_TO\r\n          LEFT JOIN T_CK_MST_JOB_STATE STATE\r\n                 ON JOB.JOB_STATE = STATE.JBST_ID\r\n          LEFT JOIN T_CK_RECORD_DATE RECORD\r\n                 ON RECORD.RCD_ID = JOB.JOB_DATES\r\n WHERE  \r\n    TRUCK.JOB_PARTY_TO = \'@ACCNID@\'\r\n    AND (\r\n        \'@FIL_JOB_STATE_CAP@\' = \'ALL\' \r\n        OR (JOB.JOB_STATE = \'@FIL_JOB_STATE_CAP@\'\r\n					OR (\r\n						JOB.JOB_STATE = \'@FIL_JOB_STATE_CAP@\'\r\n						AND (\r\n							CASE \r\n									WHEN JOB.JOB_STATE = \'CAN\' THEN DATE_FORMAT(RECORD.RCD_DT_CANCEL, \'%Y-%m-%d\') BETWEEN \'@FIL_RCD_DT_CANCEL_FROM@\' AND \'@FIL_RCD_DT_CANCEL_TO@\'\r\n									WHEN JOB.JOB_STATE = \'DLV\' THEN DATE_FORMAT(RECORD.RCD_DT_COMPLETE, \'%Y-%m-%d\') BETWEEN \'@FIL_RCD_DT_COMPLETE_FROM@\' AND \'@FIL_RCD_DT_COMPLETE_TO@\'\r\n									WHEN JOB.JOB_STATE = \'ACP\' THEN DATE_FORMAT(RECORD.RCD_DT_ACCEPTED, \'%Y-%m-%d\') BETWEEN \'@FIL_RCD_DT_ACCEPTED_FROM@\' AND \'@FIL_RCD_DT_ACCEPTED_TO@\'\r\n									WHEN JOB.JOB_STATE = \'ONGOING\' THEN DATE_FORMAT(RECORD.RCD_DT_START, \'%Y-%m-%d\') BETWEEN \'@FIL_RCD_DT_START_FROM@\' AND \'@FIL_RCD_DT_START_TO@\'\r\n									ELSE DATE_FORMAT(RECORD.RCD_DT_SUBMIT, \'%Y-%m-%d\') BETWEEN \'@FIL_RCD_DT_SUBMIT_FROM@\' AND \'@FIL_RCD_DT_SUBMIT_TO@\'\r\n							END\r\n					)\r\n				)\r\n			)\r\n    )\r\n		AND (\r\n			CASE \r\n             WHEN \'@FIL_JOB_PROCESS_VIA_CAP@\' = \'WEB\' THEN (TRUCK.JOB_PROCESS_VIA = \'@FIL_JOB_PROCESS_VIA_CAP@\' OR TRUCK.JOB_PROCESS_VIA IS NULL)\r\n             WHEN \'@FIL_JOB_PROCESS_VIA_CAP@\' = \'MOBILE\' THEN TRUCK.JOB_PROCESS_VIA = \'@FIL_JOB_PROCESS_VIA_CAP@\'\r\n			 ELSE (TRUCK.JOB_PROCESS_VIA = \'@FIL_JOB_PROCESS_VIA_CAP@\' OR TRUCK.JOB_PROCESS_VIA IS NULL) END\r\n          )' WHERE `RPTT_RPTID` = 'RPT_ALL_JOBS_TO' AND `RPTT_ACCN_TYPE` = 'ACC_TYPE_TO' AND `RPTT_TBL_IDX` = 0;

-- update & add new company Logo attach for print out
UPDATE `clickargo2`.`T_CORE_ACCN_ATT` SET `AATT_ACCNID` = 'BERAM', `AATT_DOC_TYPE` = 'image', `AATT_TYPE_ID` = 'CLO', `AATT_NAME` = 'beram.jpg', `AATT_LOC_TYPE` = 'F', `AATT_LOC` = '/home/vcc/appAttachments/BERAM/beram.jpg', `AATT_STORE` = NULL, `AATT_STATUS` = 'A', `AATT_VALID_FROM_DT` = '2024-01-16 17:53:04', `AATT_VALID_TO_DT` = '2034-01-16 17:53:04', `AATT_CREATE_UID` = 'BERAM_U001', `AATT_CREATE_DT` = '2024-01-16 17:53:04', `AATT_LUPD_UID` = 'BERAM_U001', `AATT_LUPD_DT` = '2024-02-12 14:25:35' WHERE `AATT_DOC_ID` = '368614611197275';
UPDATE `clickargo2`.`T_CORE_ACCN_ATT` SET `AATT_ACCNID` = 'CK0032', `AATT_DOC_TYPE` = 'image', `AATT_TYPE_ID` = 'CLO', `AATT_NAME` = 'CLICTRUCK.png', `AATT_LOC_TYPE` = 'F', `AATT_LOC` = '/home/vcc/appAttachments/CK0032/CLICTRUCK.png', `AATT_STORE` = NULL, `AATT_STATUS` = 'A', `AATT_VALID_FROM_DT` = '2024-01-16 19:39:02', `AATT_VALID_TO_DT` = '2034-01-16 19:39:02', `AATT_CREATE_UID` = 'GLI_U001', `AATT_CREATE_DT` = '2024-01-16 19:39:02', `AATT_LUPD_UID` = 'GLI_U001', `AATT_LUPD_DT` = '2024-01-17 15:24:22' WHERE `AATT_DOC_ID` = '374973093370225';
UPDATE `clickargo2`.`T_CORE_ACCN_ATT` SET `AATT_ACCNID` = 'GLI', `AATT_DOC_TYPE` = 'image', `AATT_TYPE_ID` = 'CLO', `AATT_NAME` = 'GUUD_LOGO.jpg', `AATT_LOC_TYPE` = 'F', `AATT_LOC` = '/home/vcc/appAttachments/GLI/GUUD_LOGO.jpg', `AATT_STORE` = NULL, `AATT_STATUS` = 'A', `AATT_VALID_FROM_DT` = '2024-01-17 12:02:56', `AATT_VALID_TO_DT` = '2034-01-17 12:02:56', `AATT_CREATE_UID` = 'GLI_U001', `AATT_CREATE_DT` = '2024-01-17 12:02:56', `AATT_LUPD_UID` = 'GLI_U001', `AATT_LUPD_DT` = '2024-01-17 17:54:05' WHERE `AATT_DOC_ID` = '434006505622256';
INSERT INTO `clickargo2`.`T_CORE_ACCN_ATT` (`AATT_ACCNID`, `AATT_DOC_ID`, `AATT_DOC_TYPE`, `AATT_TYPE_ID`, `AATT_NAME`, `AATT_LOC_TYPE`, `AATT_LOC`, `AATT_STORE`, `AATT_STATUS`, `AATT_VALID_FROM_DT`, `AATT_VALID_TO_DT`, `AATT_CREATE_UID`, `AATT_CREATE_DT`, `AATT_LUPD_UID`, `AATT_LUPD_DT`) VALUES ('DSVTS', '434006505622257', 'image', 'CLO', 'CLICTRUCK.png', 'F', '/home/vcc/appAttachments/DSVTS/CLICTRUCK.png', NULL, 'A', '2024-01-17 12:02:56', '2034-01-17 12:02:56', 'GLI_U001', '2024-01-17 12:02:56', 'SYS', '2024-01-17 17:54:05');

-- update & add new company IODSF Logo attach for print out
INSERT INTO `clickargo2`.`T_CORE_ACCN_ATT` (`AATT_ACCNID`, `AATT_DOC_ID`, `AATT_DOC_TYPE`, `AATT_TYPE_ID`, `AATT_NAME`, `AATT_LOC_TYPE`, `AATT_LOC`, `AATT_STORE`, `AATT_STATUS`, `AATT_VALID_FROM_DT`, `AATT_VALID_TO_DT`, `AATT_CREATE_UID`, `AATT_CREATE_DT`, `AATT_LUPD_UID`, `AATT_LUPD_DT`) VALUES ('IODSF', '434006505622258', 'image', 'CLO', 'CLICTRUCK.png', 'F', '/home/vcc/appAttachments/IODSF/CLICTRUCK.png', NULL, 'A', '2024-01-17 12:02:56', '2034-01-17 12:02:56', 'SYS', '2024-01-17 12:02:56', 'SYS', '2024-07-26 17:11:04');

-- execute SG.Reports > Jobs_FF.sql

ALTER TABLE `clickargo2`.`T_CK_ACCN` 
ADD COLUMN `CACCN_EXCEL_TEMPLATE_EXAMPLE` VARCHAR(128) NULL AFTER `CACCN_EXCEL_TEMPLATE`;

UPDATE `clickargo2`.`T_CK_ACCN` SET `CACCN_EXCEL_TEMPLATE_EXAMPLE` = '/docs/UploadExcelTemplate/Clasquin.xlsx' WHERE (`CACCN_ID` = 'CQS');
UPDATE `clickargo2`.`T_CK_ACCN` SET `CACCN_EXCEL_TEMPLATE_EXAMPLE` = '/docs/UploadExcelTemplate/Clasquin.xlsx' WHERE (`CACCN_ID` = 'CSP');
UPDATE `clickargo2`.`T_CK_ACCN` SET `CACCN_EXCEL_TEMPLATE_EXAMPLE` = '/docs/UploadExcelTemplate/DSVS_DSVTS.xlsx' WHERE (`CACCN_ID` = 'DSVS');

UPDATE `clickargo2`.`T_CK_ACCN` SET `CACCN_EXCEL_TEMPLATE` = '/docs/UploadExcelTemplate/Clasquin.json' WHERE (`CACCN_ID` = 'CQS');
UPDATE `clickargo2`.`T_CK_ACCN` SET `CACCN_EXCEL_TEMPLATE` = '/docs/UploadExcelTemplate/Clasquin.json' WHERE (`CACCN_ID` = 'CSP');
UPDATE `clickargo2`.`T_CK_ACCN` SET `CACCN_EXCEL_TEMPLATE` = '/docs/UploadExcelTemplate/DSVS_DSVTS-DSVRubyBSH.json' WHERE (`CACCN_ID` = 'DSVS');

-- Jira Number CT2SG-165
INSERT INTO `clickargo2`.`T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`, `GNTRLEX_DT_LUPD`, `GNTRLEX_UID_LUPD`) VALUES ('CKT', 'ADMIN', 'PM050', 'A', '2024-05-20 13:59:28', 'SYS', NULL, NULL);

ALTER TABLE `clickargo2`.`T_CK_ACCN` 
ADD COLUMN `CACCN_ISPOT_SUB_ACCN` VARCHAR(128) NULL COMMENT 'Sub account for ISPOT, regist in ASCENT' AFTER `CACCN_EPOD_SERVICE`;


INSERT INTO `clickargo2`.`T_CK_WHITELABEL` (`WL_ID`, `WL_ACCN_ID`, `WL_NAME`, `WL_STATUS`, `WL_IMG_LOC`, `WL_DT_CREATE`, `WT_UID_CREATE`) 
VALUES ('DSVSLOGIN', 'DSVS', 'DSVS', 'A', '/home/vcc/appAttachments/customLogin/dsvsLogin.png', SYSDATE(), 'GLI_U001');

-- 
delete FROM clickargo2.T_CORE_USR_ROLE where UROL_ROLEID = 'FF_FINANCE';
delete FROM clickargo2.T_CK_SVC_ACTION_MASK where SAM_ROLE = 'FF_FINANCE';
DELETE FROM clickargo2.T_CK_SVC_WORKFLOW WHERE WKFL_ID LIKE 'RT_%';
DELETE FROM clickargo2.T_CK_SVC_WORKFLOW WHERE WKFL_ID LIKE 'JOB_1%' 
	AND WKFL_ID IN ('JOB_15','JOB_16','JOB_17','JOB_18','JOB_19');
DELETE FROM clickargo2.T_CK_SVC_WORKFLOW WHERE WKFL_ID LIKE 'JOB_2%';

DELETE FROM `clickargo2`.`T_CORE_ROLE` WHERE (`ROLE_APPSCODE` = 'CKT') and (`ROLE_ID` = 'FF_FINANCE');
--
INSERT INTO `clickargo2`.`T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) 
VALUES ('CKT', 'FF_ADMIN', 'PM059', 'A', SYSDATE(), 'SYS');

DELETE FROM `clickargo2`.`T_CORE_GRANT_ROLE_EX` WHERE (`GNTRLEX_APPS_CODE` = 'CKT') and (`GNTRLEX_ROLE_ID` = 'OP_ADMIN') and (`GNTRLEX_PERM_ID` = 'PM079');

DELETE FROM `clickargo2`.`T_CORE_GRANT_ROLE_EX` WHERE (`GNTRLEX_APPS_CODE` = 'CKT') and (`GNTRLEX_ROLE_ID` = 'OP_ADMIN') and (`GNTRLEX_PERM_ID` = 'PM036');
DELETE FROM `clickargo2`.`T_CORE_GRANT_ROLE_EX` WHERE (`GNTRLEX_APPS_CODE` = 'CKT') and (`GNTRLEX_ROLE_ID` = 'OP_ADMIN') and (`GNTRLEX_PERM_ID` = 'PM037');
DELETE FROM `clickargo2`.`T_CORE_GRANT_ROLE_EX` WHERE (`GNTRLEX_APPS_CODE` = 'CKT') and (`GNTRLEX_ROLE_ID` = 'OP_ADMIN') and (`GNTRLEX_PERM_ID` = 'PM038');
DELETE FROM `clickargo2`.`T_CORE_GRANT_ROLE_EX` WHERE (`GNTRLEX_APPS_CODE` = 'CKT') and (`GNTRLEX_ROLE_ID` = 'OP_ADMIN') and (`GNTRLEX_PERM_ID` = 'PM076');
DELETE FROM `clickargo2`.`T_CORE_GRANT_ROLE_EX` WHERE (`GNTRLEX_APPS_CODE` = 'CKT') and (`GNTRLEX_ROLE_ID` = 'OP_ADMIN') and (`GNTRLEX_PERM_ID` = 'PM082');

ALTER TABLE `clickargo2`.`T_CK_ACCN` 
ADD COLUMN `CACCN_WHATSAPP` TINYINT(1) NULL DEFAULT 0 AFTER `CACCN_ISPOT_SUB_ACCN`,
ADD COLUMN `CACCN_SMS` TINYINT(1) NULL DEFAULT 0 AFTER `CACCN_WHATSAPP`,
ADD COLUMN `CACCN_CO2X` TINYINT(1) NULL DEFAULT 0 AFTER `CACCN_SMS`,
ADD COLUMN `CACCN_ROUTE_PLANNING` TINYINT(1) NULL DEFAULT 0 AFTER `CACCN_CO2X`;
-- ADD Address for GUUD admin SG
INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_ADDR_SG_API_CALL', '{\"accnAddr\":\"8 Aljunied Ave 3, The Pulse\",\"accnName\":\"GUUD LOGISTICS SINGAPORE\",\"addrCity\":\"Singapore\",\"addrPcode\":\"389933\",\"ctyDescription\":\"SINGAPORE\"}', 'CLICTRUCK_ADDR_SG_API_CALL', '2023-05-05 00:00:00', 'SYS', '2023-05-05 00:00:00', 'SYS', 'A');


ALTER TABLE `clickargo2`.`T_CK_CT_DRV` 
CHANGE COLUMN `DRV_MOBILE_ID` `DRV_MOBILE_ID` VARCHAR(256) NOT NULL COMMENT 'DRIVER EMAIL CONTACT' ,
ADD UNIQUE INDEX `DRV_MOBILE_ID_UNIQUE` (`DRV_MOBILE_ID` ASC) VISIBLE;

INSERT INTO `clickargo2`.`T_CK_MST_FORM_ACTION` (`FMACT_ID`, `FMACT_NAME`, `FMACT_DESC`, `FMACT_DESC_OTH`, `FMACT_STATUS`, `FMACT_DT_CREATE`, `FMACT_UID_CREATE`, `FMACT_DT_LUPD`, `FMACT_UID_LUPD`) 
VALUES ('SPLIT', 'Form Split', 'Form Split', 'Form Split', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');

INSERT INTO `clickargo2`.`T_CK_FORM_CONTROL` (`CTRL_ID`, `CTRL_ACCN_TYPE`, `CTRL_USR_ROLE`, `CTRL_ENTITY_TYPE`, `CTRL_ENTITY_STATE`, `CTRL_FORM_TYPE`, `CTRL_FORM_ACTION`, `CTRL_STATUS`, `CTRL_DT_CREATE`, `CTRL_UID_CREATE`, `CTRL_DT_LUPD`, `CTRL_UID_LUPD`, `CTRL_APPS_CODE`)
 VALUES ('185', 'ACC_TYPE_TO', 'OFFICER', 'JOB_TRUCK', 'ACP', 'VIEW', 'SPLIT', 'A', SYSDATE(), 'SYS', SYSDATE(), 'SYS', 'CKT');

/*ADD NEW Column to T_CK_JOB name JOB_LOADING */
;
ALTER TABLE T_CK_JOB
ADD COLUMN JOB_LOADING VARCHAR(35) DEFAULT NULL;

-- ZHANG JI
-- 7 OCT
-- SAGAWA HAS 6 TEMPLATES
drop table if exists clickargo2.T_CK_CT_EPOD_TEMPLATE;

CREATE TABLE `T_CK_CT_EPOD_TEMPLATE` (
  `EPOD_ID` varchar(70) NOT NULL,
  `EPOD_ACCN_FF` varchar(70) DEFAULT NULL,
  `EPOD_ACCN_TO` varchar(70) DEFAULT NULL,
  `EPOD_ACCN_CO` varchar(70) DEFAULT NULL,
  `EPOD_EPOD_JRXML` varchar(256) DEFAULT NULL COMMENT 'EPOD JRXML FILE PATH',
  `EPOD_EPOD_LOGO` varchar(256) DEFAULT NULL COMMENT 'EPOD LOGO FILE PATH',
  `EPOD_EPOD_SUB_REPORT` varchar(256) DEFAULT NULL COMMENT 'EPOD JRXML SUB REPORT',
  `EPOD_EPOD_SERVICE` varchar(256) DEFAULT NULL COMMENT 'EPOD SPRING BEEN SERVICE NAME',
  `EPOD_STATUS` char(1) NOT NULL,
  `EPOD_DT_CREATE` datetime NOT NULL COMMENT 'Contains the date where this record is created.',
  `EPOD_UID_CREATE` varchar(35) NOT NULL COMMENT 'Contains the User ID that create this record.',
  `EPOD_DT_LUPD` datetime DEFAULT NULL COMMENT 'Contains the date where this record is last updated.',
  `EPOD_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'Contains the User ID that last update this record.',
  PRIMARY KEY (`EPOD_ID`),
  CONSTRAINT `FKY_EPOD_ACCN_FF` FOREIGN KEY (`EPOD_ACCN_FF`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FKY_EPOD_ACCN_TO` FOREIGN KEY (`EPOD_ACCN_TO`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FKY_EPOD_ACCN_CO` FOREIGN KEY (`EPOD_ACCN_CO`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

INSERT INTO `clickargo2`.`T_CK_CT_EPOD_TEMPLATE` (`EPOD_ID`, `EPOD_ACCN_FF`, `EPOD_ACCN_TO`, `EPOD_EPOD_JRXML`, `EPOD_EPOD_LOGO`, `EPOD_STATUS`, `EPOD_DT_CREATE`, `EPOD_UID_CREATE`) 
VALUES ('SSADSVAS', 'DSVAS', 'SSA', 'docs/epod/Epod_SSA_DSCH.jrxml', NULL, 'A', SYSDATE(), 'SYS');

INSERT INTO `clickargo2`.`T_CK_CT_EPOD_TEMPLATE` (`EPOD_ID`, `EPOD_ACCN_FF`, `EPOD_ACCN_TO`, `EPOD_EPOD_JRXML`, `EPOD_EPOD_LOGO`, `EPOD_STATUS`, `EPOD_DT_CREATE`, `EPOD_UID_CREATE`) 
VALUES ('SSASCHENKER', 'DSCH', 'SSA', 'docs/epod/Epod_SSA_DSCH.jrxml', 'docs/epod/LOGO_DSCH.jpg', 'A', SYSDATE(), 'SYS');

INSERT INTO `clickargo2`.`T_CK_CT_EPOD_TEMPLATE` (`EPOD_ID`, `EPOD_ACCN_FF`, `EPOD_ACCN_TO`, `EPOD_EPOD_JRXML`, `EPOD_EPOD_LOGO`, `EPOD_STATUS`, `EPOD_DT_CREATE`, `EPOD_UID_CREATE`) 
VALUES ('SSACWL', 'CWL', 'SSA', 'docs/epod/Epod_SSA_CWL.jrxml', NULL, 'A', SYSDATE(), 'SYS');

INSERT INTO `clickargo2`.`T_CK_CT_EPOD_TEMPLATE` (`EPOD_ID`, `EPOD_ACCN_FF`, `EPOD_ACCN_TO`, `EPOD_EPOD_JRXML`, `EPOD_EPOD_LOGO`, `EPOD_STATUS`, `EPOD_DT_CREATE`, `EPOD_UID_CREATE`) 
VALUES ('SSALAP', 'LAP', 'SSA', 'docs/epod/Epod_SSA_LAP.jrxml', NULL, 'A', SYSDATE(), 'SYS');

INSERT INTO `clickargo2`.`T_CK_CT_EPOD_TEMPLATE` (`EPOD_ID`, `EPOD_ACCN_FF`, `EPOD_ACCN_TO`, `EPOD_EPOD_JRXML`, `EPOD_EPOD_LOGO`, `EPOD_STATUS`, `EPOD_DT_CREATE`, `EPOD_UID_CREATE`) 
VALUES ('SSAAWOT', 'AWOT', 'SSA', 'docs/epod/Epod_SSA_AWOT.jrxml', 'docs/epod/LOGO_AWOT.png', 'A', SYSDATE(), 'SYS');

INSERT INTO `clickargo2`.`T_CK_CT_EPOD_TEMPLATE` (`EPOD_ID`, `EPOD_ACCN_FF`, `EPOD_ACCN_TO`, `EPOD_EPOD_JRXML`, `EPOD_EPOD_LOGO`, `EPOD_STATUS`, `EPOD_DT_CREATE`, `EPOD_UID_CREATE`) 
VALUES ('SSAMMD', 'MMD', 'SSA', 'docs/epod/Epod_SSA_MMD.jrxml', 'docs/epod/LOGO_MMD.png', 'A', SYSDATE(), 'SYS');

-- Clasquin
REPLACE INTO `clickargo2`.`T_CK_CT_EPOD_TEMPLATE` (`EPOD_ID`, `EPOD_ACCN_FF`, `EPOD_ACCN_TO`, `EPOD_ACCN_CO`, `EPOD_EPOD_JRXML`, `EPOD_EPOD_LOGO`, `EPOD_STATUS`, `EPOD_DT_CREATE`, `EPOD_UID_CREATE`) 
VALUES ('CSPMLS', 'CSP', 'CQS', 'MLS', 'docs/epod/Epod_Clasquin.jrxml', NULL, 'A', '2024-10-07 09:35:44', 'SYS');

UPDATE `clickargo2`.`T_CK_ACCN` SET `CACCN_EPOD_JRXML` = NULL WHERE (`CACCN_ID` = 'CSP');
UPDATE `clickargo2`.`T_CK_ACCN` SET `CACCN_EPOD_JRXML` = NULL WHERE (`CACCN_ID` = 'CQS');

UPDATE `clickargo2`.`T_CK_CT_EPOD_TEMPLATE` SET `EPOD_EPOD_SUB_REPORT` = 'docs/epod/EPOD_SSA_MMD_SUB.jasper' WHERE (`EPOD_ID` = 'SSAMMD');

INSERT INTO `clickargo2`.`T_CK_CT_EPOD_TEMPLATE` (`EPOD_ID`, `EPOD_ACCN_FF`, `EPOD_ACCN_TO`, `EPOD_EPOD_JRXML`, `EPOD_EPOD_LOGO`, `EPOD_STATUS`, `EPOD_DT_CREATE`, `EPOD_UID_CREATE`) 
VALUES ('SSA', NULL, 'SSA', 'docs/epod/Epod_SSA.jrxml', NULL, 'A', sysdate(), 'SYS');

ALTER TABLE `clickargo2`.`T_CK_JOB_TRUCK_EXT` 
ADD COLUMN `JEXT_VAL_TYPE` VARCHAR(45) NULL AFTER `JEXT_VAL`;

/* Update column CG_CARGO_QTY and CG_CARGO_WEIGHT from INT to DOUBLE */
ALTER TABLE T_CK_CT_TRIP_CARGO_MM MODIFY COLUMN CG_CARGO_QTY DOUBLE;
ALTER TABLE T_CK_CT_TRIP_CARGO_MM MODIFY COLUMN CG_CARGO_WEIGHT DOUBLE;

ALTER TABLE `clickargo2`.`T_CK_CT_TRIP_CARGO_MM`
ADD COLUMN `CG_PICKUP_STATUS` char(1) NULL COMMENT 'CARGO PICKUP CHECKLIST STATUS - C-checked : U-unchecked' AFTER `CG_UID_LUPD`,
ADD COLUMN `CG_DROPOFF_STATUS` char(1) NULL COMMENT 'CARGO DROPOFF CHECKLIST STATUS - C-checked : U-unchecked' AFTER `CG_PICKUP_STATUS`;

INSERT INTO `clickargo2`.`T_CK_SVC_WORKFLOW` (`WKFL_ID`, `WKFL_APPS_CODE`, `WKFL_ACCN_TYPE`, `WKFL_ROLE`, `WKFL_SCV_TYPE`, `WKFL_ACTION`, `WKFL_FROM_STATE`, `WKFL_TO_STATE`, `WKFL_URI`, `WKFL_STATUS`, `WKFL_DT_CREATE`, `WKFL_UID_CREATE`, `WKFL_DT_LUPD`, `WKFL_UID_LUPD`) VALUES ('JOB_15', 'CKT', 'ACC_TYPE_TO', 'OFFICER', 'CLICTRUCK', 'STOP', 'PAUSED', 'DLV', '', 'A', '2023-12-19 10:16:22', 'SYS', '2023-12-19 10:16:22', 'SYS');
INSERT INTO `clickargo2`.`T_CK_SVC_WORKFLOW` (`WKFL_ID`, `WKFL_APPS_CODE`, `WKFL_ACCN_TYPE`, `WKFL_ROLE`, `WKFL_SCV_TYPE`, `WKFL_ACTION`, `WKFL_FROM_STATE`, `WKFL_TO_STATE`, `WKFL_URI`, `WKFL_STATUS`, `WKFL_DT_CREATE`, `WKFL_UID_CREATE`, `WKFL_DT_LUPD`, `WKFL_UID_LUPD`) VALUES ('JOB_16', 'CKT', 'ACC_TYPE_TO', 'OFFICER', 'CLICTRUCK', 'STOP', 'ASG', 'DLV', '', 'A', '2023-12-19 10:16:22', 'SYS', '2023-12-19 10:16:22', 'SYS');

INSERT INTO `clickargo2`.`T_CK_ACCN` (`CACCN_ID`, `CACCN_FINANCING_TYPE`, `CACCN_FINANCER`, `CACCN_EXCEL_TEMPLATE`, `CACCN_EXCEL_TEMPLATE_EXAMPLE`, `CACCN_EPOD_JRXML`, `CACCN_EPOD_SERVICE`, `CACCN_ISPOT_SUB_ACCN`, `CACCN_WHATSAPP`, `CACCN_SMS`, `CACCN_CO2X`, `CACCN_ROUTE_PLANNING`, `CACCN_STATUS`, `CACCN_DT_CREATE`, `CACCN_UID_CREATE`, `CACCN_DT_LUPD`, `CACCN_UID_LUPD`) VALUES ('AWOT', 'BC', NULL, '/docs/UploadExcelTemplate/SagawaFF.json', '/docs/UploadExcelTemplate/SagawaFF.xlsx', NULL, NULL, NULL, 0, 0, 0, 0, 'A', '2024-12-05 15:34:52', 'GLI', '2024-12-05 15:34:52', 'GLI');
INSERT INTO `clickargo2`.`T_CK_ACCN` (`CACCN_ID`, `CACCN_FINANCING_TYPE`, `CACCN_FINANCER`, `CACCN_EXCEL_TEMPLATE`, `CACCN_EXCEL_TEMPLATE_EXAMPLE`, `CACCN_EPOD_JRXML`, `CACCN_EPOD_SERVICE`, `CACCN_ISPOT_SUB_ACCN`, `CACCN_WHATSAPP`, `CACCN_SMS`, `CACCN_CO2X`, `CACCN_ROUTE_PLANNING`, `CACCN_STATUS`, `CACCN_DT_CREATE`, `CACCN_UID_CREATE`, `CACCN_DT_LUPD`, `CACCN_UID_LUPD`) VALUES ('CK0007', 'NF', NULL, '/docs/UploadExcelTemplate/SagawaFF.json', '/docs/UploadExcelTemplate/SagawaFF.xlsx', NULL, NULL, NULL, 0, 0, 0, 0, 'A', '2024-08-06 11:04:18', 'GLI', '2024-09-30 23:43:23', 'GLI');
INSERT INTO `clickargo2`.`T_CK_ACCN` (`CACCN_ID`, `CACCN_FINANCING_TYPE`, `CACCN_FINANCER`, `CACCN_EXCEL_TEMPLATE`, `CACCN_EXCEL_TEMPLATE_EXAMPLE`, `CACCN_EPOD_JRXML`, `CACCN_EPOD_SERVICE`, `CACCN_ISPOT_SUB_ACCN`, `CACCN_WHATSAPP`, `CACCN_SMS`, `CACCN_CO2X`, `CACCN_ROUTE_PLANNING`, `CACCN_STATUS`, `CACCN_DT_CREATE`, `CACCN_UID_CREATE`, `CACCN_DT_LUPD`, `CACCN_UID_LUPD`) VALUES ('CWL', 'BC', NULL, '/docs/UploadExcelTemplate/SagawaFF.json', '/docs/UploadExcelTemplate/SagawaFF.xlsx', NULL, NULL, NULL, 0, 0, 0, 0, 'A', '2024-12-05 15:34:52', 'GLI', '2024-12-05 15:34:52', 'GLI');
INSERT INTO `clickargo2`.`T_CK_ACCN` (`CACCN_ID`, `CACCN_FINANCING_TYPE`, `CACCN_FINANCER`, `CACCN_EXCEL_TEMPLATE`, `CACCN_EXCEL_TEMPLATE_EXAMPLE`, `CACCN_EPOD_JRXML`, `CACCN_EPOD_SERVICE`, `CACCN_ISPOT_SUB_ACCN`, `CACCN_WHATSAPP`, `CACCN_SMS`, `CACCN_CO2X`, `CACCN_ROUTE_PLANNING`, `CACCN_STATUS`, `CACCN_DT_CREATE`, `CACCN_UID_CREATE`, `CACCN_DT_LUPD`, `CACCN_UID_LUPD`) VALUES ('DSCH', 'BC', NULL, '/docs/UploadExcelTemplate/SagawaFF.json', '/docs/UploadExcelTemplate/SagawaFF.xlsx', NULL, NULL, NULL, 0, 0, 0, 0, 'A', '2024-12-05 15:34:52', 'GLI', '2024-12-05 15:34:52', 'GLI');
INSERT INTO `clickargo2`.`T_CK_ACCN` (`CACCN_ID`, `CACCN_FINANCING_TYPE`, `CACCN_FINANCER`, `CACCN_EXCEL_TEMPLATE`, `CACCN_EXCEL_TEMPLATE_EXAMPLE`, `CACCN_EPOD_JRXML`, `CACCN_EPOD_SERVICE`, `CACCN_ISPOT_SUB_ACCN`, `CACCN_WHATSAPP`, `CACCN_SMS`, `CACCN_CO2X`, `CACCN_ROUTE_PLANNING`, `CACCN_STATUS`, `CACCN_DT_CREATE`, `CACCN_UID_CREATE`, `CACCN_DT_LUPD`, `CACCN_UID_LUPD`) VALUES ('DSVAS', 'BC', NULL, '/docs/UploadExcelTemplate/SagawaFF.json', '/docs/UploadExcelTemplate/SagawaFF.xlsx', NULL, NULL, NULL, 0, 0, 0, 0, 'A', '2024-12-04 15:34:52', 'GLI', '2024-12-04 15:34:52', 'GLI');
INSERT INTO `clickargo2`.`T_CK_ACCN` (`CACCN_ID`, `CACCN_FINANCING_TYPE`, `CACCN_FINANCER`, `CACCN_EXCEL_TEMPLATE`, `CACCN_EXCEL_TEMPLATE_EXAMPLE`, `CACCN_EPOD_JRXML`, `CACCN_EPOD_SERVICE`, `CACCN_ISPOT_SUB_ACCN`, `CACCN_WHATSAPP`, `CACCN_SMS`, `CACCN_CO2X`, `CACCN_ROUTE_PLANNING`, `CACCN_STATUS`, `CACCN_DT_CREATE`, `CACCN_UID_CREATE`, `CACCN_DT_LUPD`, `CACCN_UID_LUPD`) VALUES ('LAP', 'BC', NULL, '/docs/UploadExcelTemplate/SagawaFF.json', '/docs/UploadExcelTemplate/SagawaFF.xlsx', NULL, NULL, NULL, 0, 0, 0, 0, 'A', '2024-12-05 15:34:52', 'GLI', '2024-12-05 15:34:52', 'GLI');
INSERT INTO `clickargo2`.`T_CK_ACCN` (`CACCN_ID`, `CACCN_FINANCING_TYPE`, `CACCN_FINANCER`, `CACCN_EXCEL_TEMPLATE`, `CACCN_EXCEL_TEMPLATE_EXAMPLE`, `CACCN_EPOD_JRXML`, `CACCN_EPOD_SERVICE`, `CACCN_ISPOT_SUB_ACCN`, `CACCN_WHATSAPP`, `CACCN_SMS`, `CACCN_CO2X`, `CACCN_ROUTE_PLANNING`, `CACCN_STATUS`, `CACCN_DT_CREATE`, `CACCN_UID_CREATE`, `CACCN_DT_LUPD`, `CACCN_UID_LUPD`) VALUES ('MMD', 'BC', NULL, '/docs/UploadExcelTemplate/SagawaFF.json', '/docs/UploadExcelTemplate/SagawaFF.xlsx', NULL, NULL, NULL, 0, 0, 0, 0, 'A', '2024-12-05 15:34:52', 'GLI', '2024-12-05 15:34:52', 'GLI');
INSERT INTO `clickargo2`.`T_CK_ACCN` (`CACCN_ID`, `CACCN_FINANCING_TYPE`, `CACCN_FINANCER`, `CACCN_EXCEL_TEMPLATE`, `CACCN_EXCEL_TEMPLATE_EXAMPLE`, `CACCN_EPOD_JRXML`, `CACCN_EPOD_SERVICE`, `CACCN_ISPOT_SUB_ACCN`, `CACCN_WHATSAPP`, `CACCN_SMS`, `CACCN_CO2X`, `CACCN_ROUTE_PLANNING`, `CACCN_STATUS`, `CACCN_DT_CREATE`, `CACCN_UID_CREATE`, `CACCN_DT_LUPD`, `CACCN_UID_LUPD`) VALUES ('TVH', 'BC', NULL, '/docs/UploadExcelTemplate/TvhFF.json', '/docs/UploadExcelTemplate/TvhFF.xlsx', NULL, NULL, NULL, 0, 0, 0, 0, 'A', '2024-12-10 15:34:52', 'GLI', '2024-12-10 15:34:52', 'GLI');
INSERT INTO `clickargo2`.`T_CK_ACCN` (`CACCN_ID`, `CACCN_FINANCING_TYPE`, `CACCN_FINANCER`, `CACCN_EXCEL_TEMPLATE`, `CACCN_EXCEL_TEMPLATE_EXAMPLE`, `CACCN_EPOD_JRXML`, `CACCN_EPOD_SERVICE`, `CACCN_ISPOT_SUB_ACCN`, `CACCN_WHATSAPP`, `CACCN_SMS`, `CACCN_CO2X`, `CACCN_ROUTE_PLANNING`, `CACCN_STATUS`, `CACCN_DT_CREATE`, `CACCN_UID_CREATE`, `CACCN_DT_LUPD`, `CACCN_UID_LUPD`) VALUES ('SSA', 'BC', NULL, '/docs/UploadExcelTemplate/SagawaTO.json', '/docs/UploadExcelTemplate/SagawaTO.xlsx', NULL, NULL, NULL, 0, 0, 0, 0, 'A', '2024-04-04 12:59:24', 'GLI_U001', '2024-08-06 18:03:19', 'GLI');

UPDATE `clickargo2`.`T_CK_ACCN` SET `CACCN_FINANCING_TYPE` = 'BC', `CACCN_FINANCER` = NULL, `CACCN_EXCEL_TEMPLATE` = NULL, `CACCN_EXCEL_TEMPLATE_EXAMPLE` = NULL, `CACCN_EPOD_JRXML` = NULL, `CACCN_EPOD_SERVICE` = NULL, `CACCN_ISPOT_SUB_ACCN` = NULL, `CACCN_WHATSAPP` = 0, `CACCN_SMS` = 0, `CACCN_CO2X` = 0, `CACCN_ROUTE_PLANNING` = 0, `CACCN_STATUS` = 'A', `CACCN_DT_CREATE` = '2024-07-30 15:34:52', `CACCN_UID_CREATE` = 'FF_DSVAS001', `CACCN_DT_LUPD` = '2024-07-30 15:34:52', `CACCN_UID_LUPD` = 'FF_DSVAS001' WHERE `CACCN_ID` = 'DSVAS';

-- New FF TVH
INSERT INTO `clickargo2`.`T_CORE_ACCN` (`ACCN_ID`, `ACCN_STATUS`, `ACCN_NAME`, `ACCN_NAME_OTH`, `ACCN_TYPE`, `ACCN_COY_REGN`, `ACCN_PASS_NID`, `ACCN_NATIONALITY`, `ACCN_VAT_FLAG`, `ACCN_VAT_NO`, `ACCN_ADDR1`, `ACCN_ADDR2`, `ACCN_ADDR3`, `ACCN_PCODE`, `ACCN_CITY`, `ACCN_PROV`, `ACCN_CTYCODE`, `ACCN_TEL`, `ACCN_FAX`, `ACCN_EMAIL`, `ACCN_LOCALE_CD`, `ACCN_DT_AGREE`, `ACCN_DT_REG`, `ACCN_DT_DEREG`, `ACCN_DT_REREG`, `ACCN_DT_SUSP`, `ACCN_DT_REINS`, `ACCN_DT_CREATE`, `ACCN_UID_CREATE`, `ACCN_DT_LUPD`, `ACCN_UID_LUPD`, `ACCN_OWNER_NAME`, `ACCN_BUSS_ACT`, `ACCN_OWN_NATIONALITY`, `ACCN_CITY_CODE`) VALUES ('TVH', 'A', 'TVH Singapore Pte. Ltd.', NULL, 'ACC_TYPE_FF', '1', NULL, NULL, NULL, NULL, '37 Tuas Basin Link 638771, Singapore', NULL, NULL, '638771', 'Singapore', 'Singapore', 'SG', '+855', NULL, 'devinkeo@guud.company', NULL, NULL, '2024-12-10 17:21:16', NULL, NULL, NULL, NULL, '2024-12-10 17:21:16', 'GLI_U001', '2024-12-10 17:21:16', 'GLI_U001', NULL, NULL, NULL, NULL);
INSERT INTO `clickargo2`.`T_CORE_USR` (`USR_UID`, `USR_ACCNID`, `USR_STATUS`, `USR_TYPE_ONLINE`, `USR_TYPE_MBOX`, `USR_NAME`, `USR_PASS_NID`, `USR_TITLE`, `USR_DEPT`, `USR_DT_REG`, `USR_DT_COMM`, `USR_DT_DEREG`, `USR_DT_REREG`, `USR_CLASS`, `USR_ADDR1`, `USR_ADDR2`, `USR_ADDR3`, `USR_PCODE`, `USR_CITY`, `USR_PROV`, `USR_CTYCODE`, `USR_TEL`, `USR_FAX`, `USR_EMAIL`, `USR_PWD`, `USR_PWD_1`, `USR_PWD_2`, `USR_PWD_3`, `USR_PWD_4`, `USR_DT_PWD_LUPD`, `USR_PWD_VALIDTY`, `USR_PWD_FORCE`, `USR_LOGIN_INVCNT`, `USR_DT_LOGINOK`, `USR_DT_LOGINERR`, `USR_MBOX_ID`, `USR_MBOX_MAXCNT`, `USR_MBOX_MAXSIZ`, `USR_DUR_INBX`, `USR_DUR_ARCH`, `USR_DT_CREATE`, `USR_UID_CREATE`, `USR_DT_LUPD`, `USR_UID_LUPD`) VALUES ('TVH_USER001', 'TVH', 'A', 'A', 'A', 'TVH FF USER001', 'TVH_FF_USER001', '', '', '2024-12-10 15:12:00', '2024-12-10 15:12:00', '2024-10-07 15:12:00', '2024-10-07 15:12:00', NULL, 'TVH Singapore Pte. Ltd. is 638771', 'VH Singapore Pte. Ltd. is 638771', 'devinkeo@guud.company', '638771', '1001 - CHHLOUNG', '10 - KRATIE', 'AD', '+855969063608', '', 'devinkeo@guud.company', '3040e6869fd2f871d2d542e817fb5908', '', '', '', '', '2024-12-10 00:00:00', 0, NULL, 0, '2024-07-16 21:03:36', '2024-07-16 21:03:36', 'Default', 0, 0, 0, 0, '2024-12-10 21:05:23', 'CKUS00323', '2024-12-10 00:19:34', 'TO_DSV_001');
INSERT INTO `clickargo2`.`T_CORE_USR_ROLE` (`UROL_UID`, `UROL_APPSCODE`, `UROL_ROLEID`, `UROL_ADMIN_OPT`, `UROL_STATUS`, `UROL_DT_CREATE`, `UROL_UID_CREATE`, `UROL_DT_LUPD`, `UROL_UID_LUPD`, `UROL_TEMP_ROLE`) VALUES ('TVH_USER001', 'CKT', 'OFFICER', 'A', 'A', '2024-12-10 12:20:51', 'SYS', '2024-12-10 12:20:51', 'SYS', 'N');
INSERT INTO `clickargo2`.`T_CK_CT_EPOD_TEMPLATE` (`EPOD_ID`, `EPOD_ACCN_FF`, `EPOD_ACCN_TO`, `EPOD_ACCN_CO`, `EPOD_EPOD_JRXML`, `EPOD_EPOD_LOGO`, `EPOD_EPOD_SUB_REPORT`, `EPOD_EPOD_SERVICE`, `EPOD_STATUS`, `EPOD_DT_CREATE`, `EPOD_UID_CREATE`, `EPOD_DT_LUPD`, `EPOD_UID_LUPD`) VALUES ('SSA-TVH', 'TVH', 'SSA', NULL, 'docs/epod/Epod_SSA_TVH.jrxml', 'docs/epod/TVH_LOGO.png', NULL, NULL, 'A', '2024-12-11 16:21:50', 'SYS', NULL, NULL);
INSERT INTO `clickargo2`.`T_CK_ACCN` (`CACCN_ID`, `CACCN_FINANCING_TYPE`, `CACCN_FINANCER`, `CACCN_EXCEL_TEMPLATE`, `CACCN_EXCEL_TEMPLATE_EXAMPLE`, `CACCN_EPOD_JRXML`, `CACCN_EPOD_SERVICE`, `CACCN_ISPOT_SUB_ACCN`, `CACCN_WHATSAPP`, `CACCN_SMS`, `CACCN_CO2X`, `CACCN_ROUTE_PLANNING`, `CACCN_STATUS`, `CACCN_DT_CREATE`, `CACCN_UID_CREATE`, `CACCN_DT_LUPD`, `CACCN_UID_LUPD`) VALUES ('TVH', 'BC', NULL, '/docs/UploadExcelTemplate/TvhFF.json', '/docs/UploadExcelTemplate/TvhFF.xlsx', NULL, NULL, NULL, 0, 0, 0, 0, 'A', '2024-12-10 15:34:52', 'GLI', '2024-12-10 15:34:52', 'GLI');
INSERT INTO `clickargo2`.`T_CK_CT_CONTRACT` (`CON_ID`, `CON_NAME`, `CON_DESCRIPTION`, `CON_CCY`, `CON_DT_START`, `CON_DT_END`, `CON_FINANCE_MODEL`, `CON_TO`, `CON_CHARGE_TO`, `CON_PAYTERM_TO`, `CON_CO_FF`, `CON_CHARGE_CO_FF`, `CON_PAYTERM_CO_FF`, `CON_OPM`, `CON_OPM_BANK`, `CON_STATUS`, `CON_DT_CREATE`, `CON_UID_CREATE`, `CON_DT_LUPD`, `CON_UID_LUPD`) VALUES ('CKTCC0000016', 'SSA-TVH', 'Sagawa TO with TVH FF', 'IDR', '2024-12-09 00:00:00', '2030-11-30 00:00:00', NULL, 'SSA', 'CKTCT000005', 30, 'TVH', 'CKCCF000005', 30, NULL, NULL, 'A', '2024-12-09 09:21:21', 'GLI', '2024-12-09 13:40:33', 'GLI');

ALTER TABLE `clickargo2`.`T_CK_CT_TRIP_CARGO_MM`
    MODIFY COLUMN `CG_CARGO_LENGTH` decimal(10, 3) NULL DEFAULT 0.00 COMMENT 'LENGTH OF CARGO IN METRES' AFTER `CG_CARGO_MARKS_NO`,
    MODIFY COLUMN `CG_CARGO_WIDTH` decimal(10, 3) NULL DEFAULT 0.00 COMMENT 'CG_CARGO_WIDTH OF CARGO IN METRES' AFTER `CG_CARGO_LENGTH`,
    MODIFY COLUMN `CG_CARGO_HEIGHT` decimal(10, 3) NULL DEFAULT 0.00 COMMENT 'HEIGHT OF CARGO IN METRES' AFTER `CG_CARGO_WIDTH`,
    MODIFY COLUMN `CG_CARGO_WEIGHT` double(10, 3) NULL DEFAULT NULL AFTER `CG_CARGO_HEIGHT`;

-- New Column for Job sub type
ALTER TABLE `clickargo2`.`T_CK_JOB`
    ADD COLUMN `JOB_SUB_TYPE` VARCHAR(35) DEFAULT NULL;

-- CT2SG-296
ALTER TABLE `clickargo2`.`T_CK_CT_TRIP_LOCATION` ADD COLUMN `TLOC_CARGO_REC` varchar(255) NULL COMMENT 'Cargo Recipient Name length 255' AFTER `TLOC_REMARKS`;

-- UPDATE cargo volume to double
ALTER TABLE T_CK_CT_TRIP_CARGO_MM MODIFY COLUMN CG_CARGO_VOLUME DOUBLE;


-- 01/19/2025 SG2 INSERT SCRIPT FOR SFTP CONFIG Sysfreight
INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_SFTP_SYSFREIGHT', '{\"host\":\"52.76.119.90\",\"userId\":\"ck1sftpuat\",\"password\":\"ClickSftp@2024\",\"path\": \"/UAT/HUB/inbound/\",\"port\":\"22\"}', 'Sysfreight Sftp config', '2025-01-19 00:00:00', 'SYS', '2025-01-19 00:00:00', 'SYS', 'A');
INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('SYSFREIGHT_CLICTRUCK_ACCN', '{\"accnTo\":\"HDS\",\"accnff\":\"HDSF\",\"accnCo\":\"HDSF\"}', 'Hub Distributor Account', '2025-01-19 00:00:00', 'SYS', '2025-01-19 00:00:00', 'SYS', 'A');
INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('SYSFREIGHT_CLICTRUCK_PATH', 'SFTP/UAT/HUB/inbound/', 'Sysfreight Path', '2025-01-19 00:00:00', 'SYS', '2025-01-19 00:00:00', 'SYS', 'A');

-- 01/21/2025 SG2 UPDATE SCRIPT FOR DASHBOARD CONFIGURE
UPDATE `clickargo2`.`T_CORE_SYSPARAM` SET `SYS_VAL` = '[{\"id\":0,\"dbType\":\"TRACKING\",\"transStatistic\":{},\"accnType\":\"ACC_TYPE_CO\"},{\"id\":0,\"dbType\":\"TRACKING\",\"transStatistic\":{\"ONGOING\":0},\"accnType\":\"ACC_TYPE_TO\"},{\"id\":0,\"dbType\":\"TRACKING\",\"transStatistic\":{},\"accnType\":\"ACC_TYPE_FF\"},{\"id\":0,\"dbType\":\"TRUCK_TRACKING\",\"transStatistic\":{},\"accnType\":\"ACC_TYPE_TO_WJ\"},{\"id\":1,\"dbType\":\"TRUCK_JOBS\",\"transStatistic\":{\"NEW\":0,\"ONGOING\":0},\"accnType\":\"ACC_TYPE_TO\"},{\"id\":2,\"dbType\":\"TRUCK_JOBS\",\"transStatistic\":{},\"accnType\":\"ACC_TYPE_CO\"},{\"id\":3,\"dbType\":\"TRUCK_JOBS\",\"transStatistic\":{\"ACTIVE\":0},\"accnType\":\"ACC_TYPE_FF\"},{\"id\":4,\"dbType\":\"DRIVER_AVAILABILITY\",\"transStatistic\":{\"ASSIGNED\":0,\"UNASSIGNED\":0},\"accnType\":\"ACC_TYPE_TO\"}]', `SYS_DESC` = 'Default dashboard per account type. If this is set this will be used, otherwise the dashboard in the code will be used', `SYS_DT_CREATE` = '2022-11-18 00:00:00', `SYS_UID_CREATE` = 'SYS', `SYS_DT_LUPD` = '2024-05-30 11:35:02', `SYS_UID_LUPD` = 'GLI_U001', `SYS_STATUS` = 'A' WHERE `SYS_KEY` = 'CLICTRUCK_DEFAULT_DASHBOARD';

-- 01/27/2025 [CT2SG-333] - 1.Put GENERAL option at the top for Cargo Details -> General Details
ALTER TABLE `clickargo2`.`T_CK_CT_MST_CARGO_TYPE` ADD COLUMN `CRTYP_SEQ` int NULL COMMENT 'GOODS TYPE SEQUAN NUMBER ORDERING' AFTER `CRTYP_DESC_OTH`;
UPDATE `clickargo2`.`T_CK_CT_MST_CARGO_TYPE` SET `CRTYP_SEQ` = 2 WHERE `CRTYP_ID` = 'DANGEROUS';
UPDATE `clickargo2`.`T_CK_CT_MST_CARGO_TYPE` SET `CRTYP_SEQ` = 1 WHERE `CRTYP_ID` = 'GENERAL';
-- 01/30/2025 UPDATE SCRIPT REPORTS TO FLAG NEW JOBS AS REJECTED IF THE JOB CONTAINS REMARKS
UPDATE `clickargo2`.`T_CORE_RPT_TABLE` SET `RPTT_NAME` = 'All Trucking Jobs', `RPTT_WIDTH_PERC` = 100.0000, `RPTT_SHOW` = 'Y', `RPTT_COLS` = 0, `RPTT_RPT_QRY` = 'SELECT TRUCK.JOB_ID    												 AS JOB_ID,\r\n          JOB.JOB_SHIPMENT_TYPE                                      AS SHIPMENT_TYPE,\r\n          TRUCK.JOB_SHIPMENT_REF                                      AS SHIPPING_REF,\r\n          IFNULL(DATE_FORMAT(TRUCK.JOB_DT_BOOKING, \'%Y-%m-%d\'), \'-\') AS JOB_DT_BOOKING,\r\n           CASE \r\n             WHEN REMARKS.JOBR_DT_REMARKS IS NOT NULL AND STATE.JBST_DESC = \'NEW\' THEN \'REJECTED\' \r\n               ELSE STATE.JBST_NAME END AS JOB_STATE,\r\n          COFF_ACCN.ACCN_NAME                                        AS CO_FF_ACCN,\r\n          TO_ACCN.ACCN_NAME                                          AS TO_ACCN,\r\n          TRIP_LOC_FROM.TLOC_LOC_NAME                                AS TLOC_LOC_NAME_FROM,\r\n          TRIP_LOC_TO.TLOC_LOC_NAME                                  AS TLOC_LOC_NAME_TO,\r\n          ( CASE\r\n              WHEN TRUCK.JOB_DRV IS NOT NULL THEN (SELECT DRV.DRV_NAME FROM T_CK_CT_DRV DRV WHERE DRV.DRV_ID = TRUCK.JOB_DRV)\r\n			  WHEN TRUCK.JOB_DRV IS NULL AND TRUCK.JOB_DRV_OTH IS NULL THEN \'-\'\r\n              WHEN TRUCK.JOB_DRV IS NULL THEN SUBSTRING_INDEX(SUBSTRING_INDEX(TRUCK.JOB_DRV_OTH, \'drvName=\', -1), \'}\', 1)\r\n              ELSE TRUCK.JOB_DRV\r\n            END )                                                    AS DRV_NAME,\r\n          ( CASE\r\n              WHEN TRUCK.JOB_VEH IS NOT NULL THEN (SELECT VEH.VH_PLATE_NO FROM T_CK_CT_VEH VEH WHERE  VEH.VH_ID = TRUCK.JOB_VEH)\r\n			  WHEN TRUCK.JOB_VEH IS NULL AND TRUCK.JOB_VEH_OTH IS NULL THEN \'-\'\r\n              WHEN TRUCK.JOB_VEH IS NULL THEN SUBSTRING_INDEX(SUBSTRING_INDEX(TRUCK.JOB_VEH_OTH, \'vhPlateNo=\', -1), \',\', 1)\r\n              ELSE TRUCK.JOB_VEH\r\n            END )                                                    AS VH_PLATE_NO,\r\n		  ( CASE\r\n              WHEN TRUCK.JOB_PROCESS_VIA IS NULL THEN \'WEB\' ELSE TRUCK.JOB_PROCESS_VIA\r\n            END )  AS PROCESS_VIA,\r\n            \r\n          IFNULL(DATE_FORMAT(RECORD.RCD_DT_SUBMIT, \'%Y-%m-%d\'), \'-\') AS RCD_DT_SUBMIT,\r\n		  IFNULL(DATE_FORMAT(RECORD.RCD_DT_CANCEL, \'%Y-%m-%d\'), \'-\') AS RCD_DT_CANCEL,\r\n		  IFNULL(DATE_FORMAT(RECORD.RCD_DT_ACCEPTED, \'%Y-%m-%d\'), \'-\') AS RCD_DT_ACCEPTED,\r\n		  IFNULL(DATE_FORMAT(RECORD.RCD_DT_START, \'%Y-%m-%d\'), \'-\') AS RCD_DT_START,\r\n          IFNULL(DATE_FORMAT(RECORD.RCD_DT_COMPLETE, \'%Y-%m-%d\'), \'-\') AS RCD_DT_COMPLETE\r\n   FROM   T_CK_JOB_TRUCK TRUCK\r\n          LEFT JOIN T_CK_JOB JOB\r\n                 ON TRUCK.JOB_PARENT = JOB.JOB_ID\r\n          LEFT JOIN T_CK_CT_TRIP TRIP\r\n                 ON TRIP.TR_JOB = TRUCK.JOB_ID\r\n          LEFT JOIN T_CK_CT_TRIP_LOCATION TRIP_LOC_FROM\r\n                 ON TRIP_LOC_FROM.TLOC_ID = TRIP.TR_FROM\r\n          LEFT JOIN T_CK_CT_TRIP_LOCATION TRIP_LOC_TO\r\n                 ON TRIP_LOC_TO.TLOC_ID = TRIP.TR_TO\r\n          LEFT JOIN T_CORE_ACCN COFF_ACCN\r\n                 ON COFF_ACCN.ACCN_ID = TRUCK.JOB_PARTY_CO_FF\r\n          LEFT JOIN T_CORE_ACCN TO_ACCN\r\n                 ON TO_ACCN.ACCN_ID = TRUCK.JOB_PARTY_TO\r\n          LEFT JOIN T_CK_MST_JOB_STATE STATE\r\n                 ON JOB.JOB_STATE = STATE.JBST_ID\r\n          LEFT JOIN T_CK_RECORD_DATE RECORD\r\n                 ON RECORD.RCD_ID = JOB.JOB_DATES\r\n          LEFT JOIN T_CK_JOB_REMARKS REMARKS ON REMARKS.JOBR_JOB = JOB.JOB_ID\r\n WHERE  \r\n    TRUCK.JOB_PARTY_TO = \'@ACCNID@\'\r\n        AND (\r\n        \'@FIL_JOB_STATE_CAP@\' = \'ALL\' \r\n        OR (JOB.JOB_STATE = \'@FIL_JOB_STATE_CAP@\'\r\n					OR (\r\n						JOB.JOB_STATE = \'@FIL_JOB_STATE_CAP@\'\r\n						AND (\r\n							CASE \r\n									WHEN JOB.JOB_STATE = \'CAN\' THEN DATE_FORMAT(RECORD.RCD_DT_CANCEL, \'%Y-%m-%d\') BETWEEN \'@FIL_RCD_DT_CANCEL_FROM@\' AND \'@FIL_RCD_DT_CANCEL_TO@\'\r\n									WHEN JOB.JOB_STATE = \'DLV\' THEN DATE_FORMAT(RECORD.RCD_DT_COMPLETE, \'%Y-%m-%d\') BETWEEN \'@FIL_RCD_DT_COMPLETE_FROM@\' AND \'@FIL_RCD_DT_COMPLETE_TO@\'\r\n									WHEN JOB.JOB_STATE = \'ACP\' THEN DATE_FORMAT(RECORD.RCD_DT_ACCEPTED, \'%Y-%m-%d\') BETWEEN \'@FIL_RCD_DT_ACCEPTED_FROM@\' AND \'@FIL_RCD_DT_ACCEPTED_TO@\'\r\n									WHEN JOB.JOB_STATE = \'ONGOING\' THEN DATE_FORMAT(RECORD.RCD_DT_START, \'%Y-%m-%d\') BETWEEN \'@FIL_RCD_DT_START_FROM@\' AND \'@FIL_RCD_DT_START_TO@\'\r\n									ELSE DATE_FORMAT(RECORD.RCD_DT_SUBMIT, \'%Y-%m-%d\') BETWEEN \'@FIL_RCD_DT_SUBMIT_FROM@\' AND \'@FIL_RCD_DT_SUBMIT_TO@\'\r\n							END\r\n					)\r\n				)\r\n			)\r\n    )\r\n		AND (\r\n			CASE \r\n             WHEN \'@FIL_JOB_PROCESS_VIA_CAP@\' = \'WEB\' THEN (TRUCK.JOB_PROCESS_VIA = \'@FIL_JOB_PROCESS_VIA_CAP@\' OR TRUCK.JOB_PROCESS_VIA IS NULL)\r\n             WHEN \'@FIL_JOB_PROCESS_VIA_CAP@\' = \'MOBILE\' THEN TRUCK.JOB_PROCESS_VIA = \'@FIL_JOB_PROCESS_VIA_CAP@\'\r\n			 ELSE (TRUCK.JOB_PROCESS_VIA = \'@FIL_JOB_PROCESS_VIA_CAP@\' OR TRUCK.JOB_PROCESS_VIA IS NULL) END\r\n          )' WHERE `RPTT_RPTID` = 'RPT_ALL_JOBS_TO' AND `RPTT_ACCN_TYPE` = 'ACC_TYPE_TO' AND `RPTT_TBL_IDX` = 0;

-- 02/10/2025 Create table to store value UOMs
CREATE TABLE `T_CK_CT_MST_UOM_WEIGHT` (
  `WEI_ID` VARCHAR(35) NOT NULL COMMENT 'WEIGHT ID - UUID',
  `WEI_NAME` VARCHAR(35) NOT NULL COMMENT 'WEIGHT NAME',
  `WEI_DESC` VARCHAR(35) NOT NULL COMMENT 'WEIGHT DESCRIPTION - UUID',
  `WEI_STATUS` ENUM('A', 'I') DEFAULT 'A' COMMENT 'RECORD STATUS - A: Active, I: Inactive',
  `WEI_DT_CREATE` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'RECORD CREATED DATE',
  `WEI_UID_CREATE` VARCHAR(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `WEI_DT_LUPD` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'RECORD LAST UPDATED DATE',
  `WEI_UID_LUPD` VARCHAR(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`WEI_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='TABLE FOR UOM WEIGHT';

CREATE TABLE `T_CK_CT_MST_UOM_VOLUME` (
  `VOL_ID` VARCHAR(35) NOT NULL COMMENT 'VOLDOR ID - UUID',
  `VOL_NAME` VARCHAR(35) NOT NULL COMMENT 'VOLUME NAME',
  `VOL_DESC` VARCHAR(35) NOT NULL COMMENT 'VOLDOR ID - UUID',
  `VOL_STATUS` ENUM('A', 'I') DEFAULT 'A' COMMENT 'RECORD STATUS - A: Active, I: Inactive',
  `VOL_DT_CREATE` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'RECORD CREATED DATE',
  `VOL_UID_CREATE` VARCHAR(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `VOL_DT_LUPD` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'RECORD LAST UPDATED DATE',
  `VOL_UID_LUPD` VARCHAR(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`VOL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='TABLE FOR UOM VOLUME';

CREATE TABLE `T_CK_CT_MST_UOM_SIZE` (
    `SIZ_ID` VARCHAR(35) NOT NULL COMMENT 'SIZE ID - UUID',
    `SIZ_NAME` VARCHAR(35) NOT NULL COMMENT 'SIZE NAME',
    `SIZ_DESC` VARCHAR(35) NOT NULL COMMENT 'SIZE ID - UUID',
    `SIZ_STATUS` ENUM('A', 'I') DEFAULT 'A' COMMENT 'RECORD STATUS - A: Active, I: Inactive',
    `SIZ_DT_CREATE` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'RECORD CREATED DATE',
    `SIZ_UID_CREATE` VARCHAR(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
    `SIZ_DT_LUPD` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'RECORD LAST UPDATED DATE',
    `SIZ_UID_LUPD` VARCHAR(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
    PRIMARY KEY (`SIZ_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='TABLE FOR UOM SIZE';

-- Add columns for the new references
ALTER TABLE `T_CK_CT_TRIP_CARGO_MM`
    ADD COLUMN `CG_CARGO_UOM_WEIGHT` VARCHAR(35) DEFAULT NULL COMMENT 'UOM WEIGHT - REFERENCES T_CK_CT_MST_UOM_WEIGHT:WEI_ID',
    ADD COLUMN `CG_CARGO_UOM_VOLUME` VARCHAR(35) DEFAULT NULL COMMENT 'UOM VOLUME - REFERENCES T_CK_CT_MST_UOM_VOLUME:VOL_ID',
    ADD COLUMN `CG_CARGO_UOM_SIZE` VARCHAR(35) DEFAULT NULL COMMENT 'UOM SIZE - REFERENCES T_CK_CT_MST_UOM_SIZE:SIZ_ID',
    ADD COLUMN `CG_CARGO_UOM_QTY` VARCHAR(35) DEFAULT NULL COMMENT 'UOM Quantity';

-- Add foreign key constraints for the new references
ALTER TABLE `T_CK_CT_TRIP_CARGO_MM`
    ADD CONSTRAINT `FK_CK_CT_TRIP_CARGO_MM_UOM_WEIGHT`
        FOREIGN KEY (`CG_CARGO_UOM_WEIGHT`) REFERENCES `T_CK_CT_MST_UOM_WEIGHT` (`WEI_ID`),
    ADD CONSTRAINT `FK_CK_CT_TRIP_CARGO_MM_UOM_VOLUME`
        FOREIGN KEY (`CG_CARGO_UOM_VOLUME`) REFERENCES `T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`),
    ADD CONSTRAINT `FK_CK_CT_TRIP_CARGO_MM_UOM_SIZE`
        FOREIGN KEY (`CG_CARGO_UOM_SIZE`) REFERENCES `T_CK_CT_MST_UOM_SIZE` (`SIZ_ID`);

-- [26-02-2025] Add Values T_CK_CT_MST_UOM_WEIGHT
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_WEIGHT` (`WEI_ID`, `WEI_NAME`, `WEI_DESC`, `WEI_STATUS`, `WEI_DT_CREATE`, `WEI_UID_CREATE`, `WEI_DT_LUPD`, `WEI_UID_LUPD`) VALUES ('GRM', 'gram', 'g', 'A', '2025-02-20 15:31:07', 'SYSTEM', '2025-02-26 03:52:33', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_WEIGHT` (`WEI_ID`, `WEI_NAME`, `WEI_DESC`, `WEI_STATUS`, `WEI_DT_CREATE`, `WEI_UID_CREATE`, `WEI_DT_LUPD`, `WEI_UID_LUPD`) VALUES ('KGM', 'kilogram', 'kg', 'A', '2025-02-20 15:31:07', 'SYSTEM', '2025-02-26 03:52:33', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_WEIGHT` (`WEI_ID`, `WEI_NAME`, `WEI_DESC`, `WEI_STATUS`, `WEI_DT_CREATE`, `WEI_UID_CREATE`, `WEI_DT_LUPD`, `WEI_UID_LUPD`) VALUES ('KTN', 'kilotonne', 'kt', 'A', '2025-02-20 15:31:07', 'SYSTEM', '2025-02-26 03:52:33', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_WEIGHT` (`WEI_ID`, `WEI_NAME`, `WEI_DESC`, `WEI_STATUS`, `WEI_DT_CREATE`, `WEI_UID_CREATE`, `WEI_DT_LUPD`, `WEI_UID_LUPD`) VALUES ('LBR', 'pound', 'lb', 'A', '2025-02-20 15:31:07', 'SYSTEM', '2025-02-26 03:52:33', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_WEIGHT` (`WEI_ID`, `WEI_NAME`, `WEI_DESC`, `WEI_STATUS`, `WEI_DT_CREATE`, `WEI_UID_CREATE`, `WEI_DT_LUPD`, `WEI_UID_LUPD`) VALUES ('LTN', 'ton (UK) or long ton (US)', 'ton (UK)', 'A', '2025-02-20 15:31:07', 'SYSTEM', '2025-02-26 03:52:33', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_WEIGHT` (`WEI_ID`, `WEI_NAME`, `WEI_DESC`, `WEI_STATUS`, `WEI_DT_CREATE`, `WEI_UID_CREATE`, `WEI_DT_LUPD`, `WEI_UID_LUPD`) VALUES ('MGM', 'milligram', 'mg', 'A', '2025-02-20 15:31:07', 'SYSTEM', '2025-02-26 03:52:33', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_WEIGHT` (`WEI_ID`, `WEI_NAME`, `WEI_DESC`, `WEI_STATUS`, `WEI_DT_CREATE`, `WEI_UID_CREATE`, `WEI_DT_LUPD`, `WEI_UID_LUPD`) VALUES ('ONZ', 'ounce (avoirdupois)', 'oz', 'A', '2025-02-20 15:31:07', 'SYSTEM', '2025-02-26 03:52:33', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_WEIGHT` (`WEI_ID`, `WEI_NAME`, `WEI_DESC`, `WEI_STATUS`, `WEI_DT_CREATE`, `WEI_UID_CREATE`, `WEI_DT_LUPD`, `WEI_UID_LUPD`) VALUES ('STN', 'ton (US) or short ton (UK/US)', 'ton (US)', 'A', '2025-02-20 15:31:07', 'SYSTEM', '2025-02-26 03:52:33', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_WEIGHT` (`WEI_ID`, `WEI_NAME`, `WEI_DESC`, `WEI_STATUS`, `WEI_DT_CREATE`, `WEI_UID_CREATE`, `WEI_DT_LUPD`, `WEI_UID_LUPD`) VALUES ('TNE', 'tonne (metric ton)', 't', 'A', '2025-02-20 15:31:07', 'SYSTEM', '2025-02-26 03:52:33', 'SYSTEM');

-- [26-02-2025] Add Values T_CK_CT_MST_UOM_WEIGHT
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('5I', 'standard cubic foot', 'std', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('BLD', 'dry barrel (US)', 'bbl (US)', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('BLL', 'barrel (US)', 'barrel (US)', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('CLT', 'centilitre', 'cl', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('FTQ', 'cubic foot', 'ft³', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('GLD', 'dry gallon (US)', 'dry gal (US)', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('GLI', 'gallon (UK)', 'gal (UK)', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('GLL', 'gallon (US)', 'gal (US)', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('H20', 'cubic kilometre', 'km³', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('INQ', 'cubic inch', 'in³', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('J57', 'barrel (UK petroleum)', 'bbl (UK liq.)', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('K6', 'kilolitre', 'kl', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('L84', 'ton (UK shipping)', 'British shipping ton', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('L86', 'ton (US shipping)', '(US) shipping ton', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('M69', 'cubic mile (UK statute)', 'mi³', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('M70', 'ton, register', 'RT', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('MTQ', 'cubic metre', 'm³', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('OZA', 'fluid ounce (US)', 'fl oz (US)', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('OZI', 'fluid ounce (UK)', 'fl oz (UK)', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('PT', 'pint (US)', 'pt (US)', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('PTD', 'dry pint (US)', 'dry pt (US)', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('PTI', 'pint (UK)', 'pt (UK)', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('PTL', 'liquid pint (US)', 'liq pt (US)', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('QT', 'quart (US)', 'qt (US)', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('QTD', 'dry quart (US)', 'dry qt (US)', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('QTI', 'quart (UK)', 'qt (UK)', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('QTL', 'liquid quart (US)', 'liq qt (US)', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('SM3', 'Standard cubic metre', 'CBM', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_VOLUME` (`VOL_ID`, `VOL_NAME`, `VOL_DESC`, `VOL_STATUS`, `VOL_DT_CREATE`, `VOL_UID_CREATE`, `VOL_DT_LUPD`, `VOL_UID_LUPD`) VALUES ('YDQ', 'cubic yard', 'yd³', 'A', '2025-02-20 15:29:51', 'SYSTEM', '2025-02-26 03:37:25', 'SYSTEM');

-- [26-02-2025] Add Values T_CK_CT_MST_UOM_WEIGHT
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_SIZE` (`SIZ_ID`, `SIZ_NAME`, `SIZ_DESC`, `SIZ_STATUS`, `SIZ_DT_CREATE`, `SIZ_UID_CREATE`, `SIZ_DT_LUPD`, `SIZ_UID_LUPD`) VALUES ('CMT', 'centimetre', 'cm', 'A', '2025-02-26 02:29:45', 'SYSTEM', '2025-02-26 03:33:39', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_SIZE` (`SIZ_ID`, `SIZ_NAME`, `SIZ_DESC`, `SIZ_STATUS`, `SIZ_DT_CREATE`, `SIZ_UID_CREATE`, `SIZ_DT_LUPD`, `SIZ_UID_LUPD`) VALUES ('FOT', 'foot', 'ft', 'A', '2025-02-26 02:29:45', 'SYSTEM', '2025-02-26 03:33:39', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_SIZE` (`SIZ_ID`, `SIZ_NAME`, `SIZ_DESC`, `SIZ_STATUS`, `SIZ_DT_CREATE`, `SIZ_UID_CREATE`, `SIZ_DT_LUPD`, `SIZ_UID_LUPD`) VALUES ('INH', 'inch', 'in', 'A', '2025-02-26 02:29:45', 'SYSTEM', '2025-02-26 03:33:39', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_SIZE` (`SIZ_ID`, `SIZ_NAME`, `SIZ_DESC`, `SIZ_STATUS`, `SIZ_DT_CREATE`, `SIZ_UID_CREATE`, `SIZ_DT_LUPD`, `SIZ_UID_LUPD`) VALUES ('KMT', 'kilometre', 'km', 'A', '2025-02-26 02:29:45', 'SYSTEM', '2025-02-26 03:33:39', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_SIZE` (`SIZ_ID`, `SIZ_NAME`, `SIZ_DESC`, `SIZ_STATUS`, `SIZ_DT_CREATE`, `SIZ_UID_CREATE`, `SIZ_DT_LUPD`, `SIZ_UID_LUPD`) VALUES ('MMT', 'millimetre', 'mm', 'A', '2025-02-26 02:29:45', 'SYSTEM', '2025-02-26 03:33:39', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_SIZE` (`SIZ_ID`, `SIZ_NAME`, `SIZ_DESC`, `SIZ_STATUS`, `SIZ_DT_CREATE`, `SIZ_UID_CREATE`, `SIZ_DT_LUPD`, `SIZ_UID_LUPD`) VALUES ('MTR', 'M', 'm', 'A', '2025-02-20 07:28:34', 'SYSTEM', '2025-02-26 02:23:58', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_SIZE` (`SIZ_ID`, `SIZ_NAME`, `SIZ_DESC`, `SIZ_STATUS`, `SIZ_DT_CREATE`, `SIZ_UID_CREATE`, `SIZ_DT_LUPD`, `SIZ_UID_LUPD`) VALUES ('SMI', 'mile (statute mile)', 'mile', 'A', '2025-02-26 02:29:45', 'SYSTEM', '2025-02-26 03:33:40', 'SYSTEM');
INSERT INTO `clickargo2`.`T_CK_CT_MST_UOM_SIZE` (`SIZ_ID`, `SIZ_NAME`, `SIZ_DESC`, `SIZ_STATUS`, `SIZ_DT_CREATE`, `SIZ_UID_CREATE`, `SIZ_DT_LUPD`, `SIZ_UID_LUPD`) VALUES ('YRD', 'yard', 'yd', 'A', '2025-02-26 02:29:45', 'SYSTEM', '2025-02-26 03:33:40', 'SYSTEM');
