-- UPDATE OLD VEHICLE TYPE TO STATUS I
UPDATE `clickargo2`.`T_CK_CT_MST_VEH_TYPE`
SET `VHTY_STATUS` = 'I'
WHERE `VHTY_ID` IN (
    'GOODS (CLOSED) LORRY (BOX)',
    'GOODS (OPEN) REFRIGERATEDVEHICLE',
    'GOODS (OPEN) LORRY (METALBODY)/P',
    'GOODS (OPEN) LORRY (WOODENBODY)',
    'GOODS(CLOSED)VANPANEL',
    'MERCEDESBENZ',
    'GOODSCUMPASSENGERTWINCABINGO',
    'CITROEN',
    'EV',
    'EVEHICLE',
    'UNDEFINE',
    'AIRPLANE',
    'FUSOBOX',
    'TRONTONWB40',
    'AIRLINES',
    'FUSO(01-JPP)',
    'PICKUP',
    'SELF-LOADER',
    'TRAILER45F',
    'CDDLONGREEFER',
    'TRONTONWB25',
    'BOX',
    'BYPASS',
    'TRUCKTRAILER',
    'CDDBOX',
    'CDDFLATDECK',
    'CDDLIGHTTRUCKBOX',
    'FUSOWING',
    'CDDREEFER',
    'VANBLIND',
    'CDEBOX',
    'CDELONG',
    'CDELONGREEFER',
    'CDEREEFER',
    'CDETRUCK',
    'CDDLONGBOX',
    'VANBOX',
    'VOLVO',
    'DTAXOR',
    'DTSANY',
    'DUMPTRUCK',
    'ENGKEL',
    'EURO',
    'FLATBED',
    'FUSO',
    'FUSOLONG',
    'LOSSBAK',
    'LOWBED',
    'HINO',
    'MIT',
    'NISSANPK260CT',
    'NISSANUD',
    'HINO500',
    'POK(KAS)',
    'HINOFM320',
    'SEMIFUSOWB',
    'TOYOTA',
    'TRAILER',
    'TRAILER20F',
    'TRAILER40F',
    'ISOTANK',
    'TRAILERCARCARRIER',
    'TRONTON',
    'TRONTON(AIRSUSPENSION)',
    'TRONTONREEFER',
    'TRONTONTRUCK',
    'TRONTONWB',
    'TRONTONWB15',
    'ISUZU',
    'L300BOX',
    'TRONTONWB50',
    'TRUCK',
    'TRUCKBOX',
    'CDD',
    'CDDLONG',
    'CDE',
    'CONTAINER20FT',
    'CONTAINER40FT',
    'WINGBOX',
    '48'
    );
-- INSERT NEW VEHICLE TYPE
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('10FT', '10 FT', '10 FT', '10 FT', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('10FT_EV', '10 FT - EV', '10 FT - EV', '10 FT - EV', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('14FT_BOX', '14 FT - BOX', '14 FT - BOX', '14 FT - BOX', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('14FT_BOX_TG', '14 FT - BOX TAILGATE', '14 FT - BOX TAILGATE', '14 FT - BOX TAILGATE', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('14FT_EV', '14 FT - EV', '14 FT - EV', '14 FT - EV', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('14FT_REEFER', '14 FT - REEFER', '14 FT - REEFER', '14 FT - REEFER', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('18FT', '18 FT', '18 FT', '18 FT', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('18FT_BOX', '18 FT - BOX', '18 FT - BOX', '18 FT - BOX', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('18FT_BOX_TG', '18 FT - BOX TAILGATE', '18 FT - BOX TAILGATE', '18 FT - BOX TAILGATE', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('18FT_EV', '18 FT - EV', '18 FT - EV', '18 FT - EV', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('18FT_REEFER', '18 FT - REEFER', '18 FT - REEFER', '18 FT - REEFER', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('24FT', '24 FT', '24 FT', '24 FT', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('24FT_BOX', '24 FT - BOX', '24 FT - BOX', '24 FT - BOX', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('24FT_BOX_DG_TG', '24 FT - BOX HAZMAT TAILGATE (DG)', '24 FT - BOX HAZMAT TAILGATE (DG)', '24 FT - BOX HAZMAT TAILGATE (DG)', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('24FT_BOX_TG', '24 FT - BOX TAILGATE', '24 FT - BOX TAILGATE', '24 FT - BOX TAILGATE', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('24FT_CURTAIN', '24 FT - CURTAIN SIDER', '24 FT - CURTAIN SIDER', '24 FT - CURTAIN SIDER', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('24FT_CURTAIN_DG', '24 FT - CURTAIN SIDER HAZMAT (DG)', '24 FT - CURTAIN SIDER HAZMAT (DG)', '24 FT - CURTAIN SIDER HAZMAT (DG)', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('24FT_EV', '24 FT - EV', '24 FT - EV', '24 FT - EV', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('24FT_REEFER', '24 FT - REEFER', '24 FT - REEFER', '24 FT - REEFER', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('25FT_REEFER', '25 FT - REEFER', '25 FT - REEFER', '25 FT - REEFER', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('PRIME_MOVER', 'PRIME MOVER', 'PRIME MOVER', 'PRIME MOVER', 'A', '2024-12-16 00:00:00', 'SYS', '2024-12-16 00:00:00', 'SYS');
INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`, `VHTY_DT_LUPD`, `VHTY_UID_LUPD`) VALUES ('VAN- EV', 'VAN - EV', 'VAN - EV', 'VAN - EV', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
