-- CREATE TABLE FOR RELATIONSHIP BETWEEN 3RD PARTY VENDORS AND COMPANIES
CREATE TABLE `T_CK_CT_VENDOR_COMPANY` (
  `VEN_ID` VARCHAR(35) NOT NULL COMMENT 'VENDOR ID - UUID',
  `VEN_VENDOR_ACCN` VARCHAR(35) NOT NULL COMMENT '3RD PARTY VENDOR ACCOUNT ID - REFERENCE T_CORE_ACCN:ACCN_ID',
  `VEN_COMPANY_ACCN` VARCHAR(35) NOT NULL COMMENT 'COMPANY ACCOUNT ID - REFERENCE T_CORE_ACCN:ACCN_ID',
  `VEN_STATUS` ENUM('A', 'I') DEFAULT 'A' COMMENT 'RECORD STATUS - A: Active, I: Inactive',
  `VEN_DT_CREATE` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'RECORD CREATED DATE',
  `VEN_UID_CREATE` VARCHAR(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `VEN_DT_LUPD` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'RECORD LAST UPDATED DATE',
  `VEN_UID_LUPD` VARCHAR(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`VEN_ID`),
  CONSTRAINT `FK_VENDOR_ACCN` FOREIGN KEY (`VEN_VENDOR_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_COM_ACCN` FOREIGN KEY (`VEN_COMPANY_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='TABLE FOR RELATIONSHIP BETWEEN 3RD PARTY VENDORS AND COMPANIES';


-- INSERT 3RD PARTY VENDORS AND COMPANY
INSERT INTO `clickargo2`.`T_CK_CT_VENDOR_COMPANY` (`VEN_ID`, `VEN_VENDOR_ACCN`, `VEN_COMPANY_ACCN`, `VEN_STATUS`, `VEN_DT_CREATE`, `VEN_UID_CREATE`, `VEN_DT_LUPD`, `VEN_UID_LUPD`) VALUES ('COY001', 'COY', 'HDS', 'A', '2025-02-02 19:59:39', 'SYS', '2025-02-02 19:59:39', 'SYS');
