/** For Additional Dynamic Fields SG Requirement */
CREATE TABLE `T_CK_CT_ADD_ATTR_LIST` (
  `AAL_ID` varchar(35) NOT NULL COMMENT 'ADDITIONAL ATTRIBUTES LIST ID - UUID',
  `AAL_LIST` mediumtext DEFAULT NULL COMMENT 'ADDITIONAL ATTRIBUTE LIST IN JSON',
  `AAL_DESCRIPTION`  varchar(1024) DEFAULT NULL COMMENT 'ADDITIONAL ATTRIBUTE LIST DESCRIPTION',
  `AAL_STATUS` char(1) DEFAULT NULL COMMENT 'CONTRACT STATE STATUS',
  `AAL_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `AAL_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `AAL_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `AAL_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`AAL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='ADDITIONAL ATTRIBUTE LISTS';


CREATE TABLE `T_CK_CT_CON_ADD_ATTR` (
  `CAA_ID` varchar(35) NOT NULL COMMENT 'ADDITIONAL ATTRIBUTES ID - UUID',
  `CAA_CON` varchar(35) NOT NULL COMMENT 'CONTRACT - REFERENCES T_CK_CT_CONTRACT:CON_ID',
  `CAA_TYPE` char(1) DEFAULT 'T' COMMENT 'ADDITIONAL ATTRIBUTE TYPE - T:L',
  `CAA_REQUIRED` char(1) DEFAULT 'N',
  `CAA_SEQ` smallint DEFAULT '0' COMMENT 'ADDITIONAL ATTRIBUTE SEQUENCE',
  `CAA_LABEL` varchar(1024) DEFAULT NULL COMMENT 'LABEL NAME',
  `CAA_REF_LIST` varchar(35) DEFAULT NULL COMMENT 'ADDITIONAL ATTRIBUTE REFERNCE LIST - T_CK_CT_ADD_ATTR_LIST:AAL_ID',
  `CAA_DESCRIPTION` varchar(1024) DEFAULT NULL COMMENT 'ADDITIONAL ATTRIBUTE DESCRIPTION',
  `CAA_STATUS` char(1) DEFAULT NULL COMMENT 'CONTRACT STATE STATUS',
  `CAA_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CAA_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CAA_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CAA_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CAA_ID`),
  KEY `FK_CK_CT_ADD_ATTR_CK_CT_CONTRACT` (`CAA_CON`),
  KEY `FK_CK_CT_CON_ADD_ATTR_CK_CT_ADD_ATTR_LIST` (`CAA_REF_LIST`),
  CONSTRAINT `FK_CK_CT_ADD_ATTR_CK_CT_CONTRACT` FOREIGN KEY (`CAA_CON`) REFERENCES `T_CK_CT_CONTRACT` (`CON_ID`),
  CONSTRAINT `FK_CK_CT_CON_ADD_ATTR_CK_CT_ADD_ATTR_LIST` FOREIGN KEY (`CAA_REF_LIST`) REFERENCES `T_CK_CT_ADD_ATTR_LIST` (`AAL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='CONTRACT ADDITIONAL ATTRIBUTES';


CREATE TABLE `T_CK_JOB_TRUCK_ADD_ATTR` (
  `JAA_ID` varchar(35) NOT NULL COMMENT 'JOB ADDITIONAL ATTRIBUTE ID - UUID',
  `JAA_JOB` varchar(35) DEFAULT NULL COMMENT 'TRUCK JOB - REFERENCES T_CK_JOB_TRUCK:JOB_ID',
  `JAA_CON_ATTR` varchar(35) DEFAULT NULL COMMENT 'CONTRACT ATTRIBUTE  - REFERENCES T_CK_CT_CON_ADD_ATTR:CAA_ID',
  `JAA_VALUE` varchar(1024) NOT NULL COMMENT 'JOB ADDITIONAL ATTRIBUTE VALUE',
  `JAA_STATUS` char(1) DEFAULT NULL COMMENT 'CONTRACT STATE STATUS',
  `JAA_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `JAA_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `JAA_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `JAA_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`JAA_ID`),
  CONSTRAINT `FK_CK_JOB_TRUCK_ADD_ATTR_CK_JOB_TRUCK` FOREIGN KEY (`JAA_JOB`) REFERENCES `T_CK_JOB_TRUCK` (`JOB_ID`),
  CONSTRAINT `FK_CK_JOB_TRUCK_ADD_ATTR_CK_CT_CON_ADD_ATTR` FOREIGN KEY (`JAA_CON_ATTR`) REFERENCES `T_CK_CT_CON_ADD_ATTR` (`CAA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='JOB ADDITIONAL ATTRIBUTES';
