/**For closure tasks start **/
/**20230816 New Menus from Closure Items*/
-- INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_OA_070200','CKT','','','Bank Account','Bank Account','70200','/opadmin/bankaccounts',NULL,'CKT_OA_070000','A',NOW(),'SYS',NOW(),'SYS');
-- INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_OA_070300','CKT','','','Static Virtual Account','Static Virtual Account','70300','/opadmin/staticva',NULL,'CKT_OA_070000','A',NOW(),'SYS',NOW(),'SYS');
-- INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_OA_070400','CKT','','','Tracking Device','Tracking Device','70400','/opadmin/trackingdevice',NULL,'CKT_OA_070000','A',NOW(),'SYS',NOW(),'SYS');

-- INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM048', 'N', 'CK', NULL, 'M', NULL, NULL, 'CKT_OA_070200', 'Bank Account', 'Bank Account','Bank Account','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
-- INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM049', 'N', 'CK', NULL, 'M', NULL, NULL, 'CKT_OA_070300', 'Static Virtual Account', 'Static Virtual Account','Static Virtual Account','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
-- INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM050', 'N', 'CK', NULL, 'M', NULL, NULL, 'CKT_OA_070400', 'Tracking Device', 'Tracking Device','Tracking Device','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');

-- INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'SP_OP_ADMIN', 'PM048', 'A', NOW(), 'SYS');
-- INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'SP_OP_ADMIN', 'PM049', 'A', NOW(), 'SYS');
-- INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'SP_OP_ADMIN', 'PM050', 'A', NOW(), 'SYS');


CREATE TABLE `T_CK_CT_MST_SAGE_INT_STATE` (
  `SIS_ID` varchar(35) NOT NULL COMMENT 'SAGE INTEGRATION STATE ID - SUBMITTED:PARTIAL:SUCCESS',
  `SIS_NAME` varchar(100) NOT NULL COMMENT 'SAGE INTEGRATION STATE NAME',
  `SIS_DESC` varchar(255) DEFAULT NULL COMMENT 'SAGE INTEGRATION STATE DESCRIPTION',
  `SIS_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'SAGE INTEGRATION STATE DESCRIPTION OTHER LANGUAGE',
  `SIS_STATUS` char(1) DEFAULT NULL COMMENT 'SAGE INTEGRATION STATE STATUS',
  `SIS_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `SIS_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `SIS_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `SIS_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`SIS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='SAGE INTEGRATION STATE MASTER TABLE';

CREATE TABLE `T_CK_CT_MST_SAGE_INT_TYPE` (
  `SIT_ID` varchar(35) NOT NULL COMMENT 'SAGE INTEGRATION TYPE ID - BOOKING:PAYMENT_IN:PAYMENT_OUT',
  `SIT_NAME` varchar(100) NOT NULL COMMENT 'SAGE INTEGRATION TYPE NAME',
  `SIT_DESC` varchar(255) DEFAULT NULL COMMENT 'SAGE INTEGRATION TYPE DESCRIPTION',
  `SIT_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'SAGE INTEGRATION TYPE DESCRIPTION OTHER LANGUAGE',
  `SIT_STATUS` char(1) DEFAULT NULL COMMENT 'SAGE INTEGRATION TYPE STATUS',
  `SIT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `SIT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `SIT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `SIT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`SIT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='SAGE INTEGRATION TYPE MASTER TABLE';


CREATE TABLE `T_CK_SAGE_INTEGRATION` (
  `SINT_ID` varchar(35) NOT NULL COMMENT 'SAGE INTEGRATION RECORD ID - UUID',
  `SINT_SVC` varchar(35) DEFAULT NULL COMMENT 'CLICKARGO SERVICES - REFERENCE T_CK_MST_SERVICE_TYPE:SVCT_ID',  
  `SINT_STATE` varchar(35) NOT NULL COMMENT 'SAGE INTEGRATION STATE - REFERENCES T_CK_CT_MST_SAGE_INT_STATE:SIS_ID',
  `SINT_INT_TYPE` varchar(35) DEFAULT NULL COMMENT 'INTEGRATION - REFERENCES T_CK_CT_MST_SAGE_INT_TYPE:SIT_ID',
  `SINT_DT_START` datetime DEFAULT NULL COMMENT 'SAGE INTEGRATION START DATE TIME',
  `SINT_DT_END` datetime DEFAULT NULL COMMENT 'SAGE INTEGRATION END DATE TIME',
  `SINT_NO_RECORDS` mediumint DEFAULT 0 COMMENT 'SAGE INTEGRATION NUMBER OF RECORDS',
  `SINT_NO_SUCCESS` mediumint DEFAULT 0 COMMENT 'SAGE INTEGRATION NUMBER OF SUCCESS RECORDS',
  `SINT_NO_FAIL` mediumint DEFAULT 0 COMMENT 'SAGE INTEGRATION NUMBER OF FAIL RECORDS',
  `SINT_DT_EXPORT` datetime DEFAULT NULL COMMENT 'SAGE INTEGRATION EXPORT DATE',
  `SINT_DT_IMPORT` datetime DEFAULT NULL COMMENT 'SAGE INTEGRATION IMPORT DATE',
  `SINT_LOC_EXPORT` varchar(1024) DEFAULT NULL COMMENT 'PHYSICAL LOCATION OF THE EXPORT EXCEL FILE FROM  CLICTRCUK',
  `SINT_LOC_IMPORT` varchar(1024) DEFAULT NULL COMMENT 'PHYSICAL LOCATION OF THE IMPORT EXCEL FILE FROM SAGE',
  `SINT_STATUS` char(1) DEFAULT NULL COMMENT 'VEHICLE STATE STATUS',
  `SINT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `SINT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `SINT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `SINT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`SINT_ID`),
	CONSTRAINT `FK_CK_SAGE_INTEGRARTION_CK_MST_SERVICE_TYPE` FOREIGN KEY (`SINT_SVC`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),
  CONSTRAINT `FK_CK_SAGE_INTEGRARTION_CK_CT_MST_SAGE_INT_STATE` FOREIGN KEY (`SINT_STATE`) REFERENCES `T_CK_CT_MST_SAGE_INT_STATE` (`SIS_ID`),  
  CONSTRAINT `FK_CK_SAGE_INTEGRARTION_CK_CT_MST_SAGE_INT_TYPE` FOREIGN KEY (`SINT_INT_TYPE`) REFERENCES `T_CK_CT_MST_SAGE_INT_TYPE` (`SIT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='SAGE INTEGRATION MAINTENACNE TABLE';

REPLACE INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) 
VALUES ('CLICTRUCK_SAGE_SFTP', '{\"host\":\"ct2-demo.vcargocloud.com\",\"userId\":\"sageUser\",\"password\":\"3nt3r@!\",\"path\":\"/sageSftp/toSage/\",\"outpath\":\"/sageSftp/fromSage/\"}', 'Sage Sftp config', '2023-05-05 00:00:00', 'SYS', '2023-05-05 00:00:00', 'SYS', 'A');

INSERT INTO `clickargo2`.`T_CK_CT_MST_SAGE_INT_TYPE` (`SIT_ID`, `SIT_NAME`, `SIT_DESC`, `SIT_DESC_OTH`, `SIT_STATUS`, `SIT_DT_CREATE`, `SIT_UID_CREATE`) 
VALUES ('BOOKING', 'BOOKING', 'BOOKING', 'BOOKING', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_SAGE_INT_TYPE` (`SIT_ID`, `SIT_NAME`, `SIT_DESC`, `SIT_DESC_OTH`, `SIT_STATUS`, `SIT_DT_CREATE`, `SIT_UID_CREATE`) 
VALUES ('PAYMENT_IN', 'PAYMENT_IN', 'PAYMENT_IN', 'PAYMENT_IN', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_SAGE_INT_TYPE` (`SIT_ID`, `SIT_NAME`, `SIT_DESC`, `SIT_DESC_OTH`, `SIT_STATUS`, `SIT_DT_CREATE`, `SIT_UID_CREATE`) 
VALUES ('PAYMENT_OUT', 'PAYMENT_OUT', 'PAYMENT_OUT', 'PAYMENT_OUT', 'A', sysdate(), 'sys');

INSERT INTO `clickargo2`.`T_CK_CT_MST_SAGE_INT_STATE` (`SIS_ID`, `SIS_NAME`, `SIS_DESC`, `SIS_DESC_OTH`, `SIS_STATUS`, `SIS_DT_CREATE`, `SIS_UID_CREATE`) 
VALUES ('SUBMITTED', 'SUBMITTED', 'SUBMITTED', 'SUBMITTED', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_SAGE_INT_STATE` (`SIS_ID`, `SIS_NAME`, `SIS_DESC`, `SIS_DESC_OTH`, `SIS_STATUS`, `SIS_DT_CREATE`, `SIS_UID_CREATE`) 
VALUES ('PARTIAL', 'PARTIAL', 'PARTIAL', 'PARTIAL', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_SAGE_INT_STATE` (`SIS_ID`, `SIS_NAME`, `SIS_DESC`, `SIS_DESC_OTH`, `SIS_STATUS`, `SIS_DT_CREATE`, `SIS_UID_CREATE`) 
VALUES ('SUCCESS', 'SUCCESS', 'SUCCESS', 'SUCCESS', 'A', sysdate(), 'sys');


CREATE TABLE `T_CK_CT_MST_TRACK_DEVICE_STATE` (
  `TDS_ID` varchar(35) NOT NULL COMMENT 'TRACK DEVICE STATE ID - NEW:ACTIVATE:DEACTIVATE',
  `TDS_NAME` varchar(100) NOT NULL COMMENT 'TRACK DEVICE STATE NAME',
  `TDS_DESC` varchar(255) DEFAULT NULL COMMENT 'TRACK DEVICE STATE DESCRIPTION',
  `TDS_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'TRACK DEVICE STATE DESCRIPTION OTHER LANGUAGE',
  `TDS_STATUS` char(1) DEFAULT NULL COMMENT 'TRACK DEVICE STATE STATUS',
  `TDS_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `TDS_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `TDS_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `TDS_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`TDS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='TRACK DEVICE STATE MASTER TABLE';


CREATE TABLE `T_CK_CT_TRACK_DEVICE` (
  `TD_ID` varchar(35) NOT NULL COMMENT 'TRACKING DEVICE RECORD ID - UUID',
  `TD_STATE` varchar(35) NOT NULL COMMENT 'TRACKING DEVICE STATE - REFERENCES T_CK_CT_MST_TRACK_DEVICE_STATE:TDS_ID',
  `TD_VEH_ID` varchar(35) DEFAULT NULL COMMENT 'VEHICLE TYPE - REFERENCES T_CK_CT_VEH:VH_ID',
  `TD_VEH_PLATE_NO` varchar(256) DEFAULT NULL COMMENT 'VEHICLE PLATE NUMBER',
  `TD_COMPANY` varchar(35) DEFAULT NULL COMMENT 'COMPANY  - REFERENCES T_CORE_ACCN:ACCN_ID',
  `TD_COMPANY_TYPE` varchar(35) DEFAULT NULL COMMENT 'COMAPNY TYPE - REFERENCES T_MST_ACCN_TYPE:ATYP_ID',
  `TD_GPS_IMEI` varchar(1024) DEFAULT NULL COMMENT 'GPS IMEI ASSIGNED TO TRUCK',
  `TD_DT_ACTIVATTION` datetime DEFAULT NULL COMMENT 'ACTIVATION DATE IS AFTER INSTALLATION THEN WE TELL ASCENT THEN ASCENT TELLS US WHEN IT IS ACTIVATED',
  `TD_DT_ACTIVATE` datetime DEFAULT NULL COMMENT 'TRACKING DEVICE ACTIVATION DATE TIME, WHEN GLI USER CLICK <ACTIVE> BUTTON',
  `TD_DT_DEACTIVATE` datetime DEFAULT NULL COMMENT 'TRACKING DEVICE DEACTIVATION DATE TIME',
  `TD_UID_ACTIVATE` varchar(35) DEFAULT NULL COMMENT 'TRACKING DEVICE ACTIVATION BY',
  `TD_UID_DEACTIVATE` varchar(35) DEFAULT NULL COMMENT 'TRACKING DEVICE DEACTIVATION BY',
  `TD_STATUS` char(1) DEFAULT NULL COMMENT 'VEHICLE STATE STATUS',
  `TD_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `TD_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `TD_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `TD_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`TD_ID`),
  CONSTRAINT `FK_CK_CT_TRACK_DEVICE_CK_CT_MST_TRACK_DEVICE_STATE` FOREIGN KEY (`TD_STATE`) REFERENCES `T_CK_CT_MST_TRACK_DEVICE_STATE` (`TDS_ID`),  
  CONSTRAINT `FK_CK_CT_TRACK_DEVICE_CK_CT_VEH` FOREIGN KEY (`TD_VEH_ID`) REFERENCES `T_CK_CT_VEH` (`VH_ID`),
  CONSTRAINT `FK_CK_CT_TRACK_DEVICE_CORE_ACCN` FOREIGN KEY (`TD_COMPANY`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_CT_TRACK_DEVICE_MST_ACCN_TYPE` FOREIGN KEY (`TD_COMPANY_TYPE`) REFERENCES `T_MST_ACCN_TYPE` (`ATYP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='TRACKING DEVICE MAINTENACNE TABLE';

INSERT INTO `clickargo2`.`T_CK_CT_MST_TRACK_DEVICE_STATE` (`TDS_ID`, `TDS_NAME`, `TDS_DESC`, `TDS_DESC_OTH`, `TDS_STATUS`, `TDS_DT_CREATE`, `TDS_UID_CREATE`)
 VALUES ('NEW', 'NEW', 'NEW', 'NEW', 'A', sysdate(), 'sys');
 
INSERT INTO `clickargo2`.`T_CK_CT_MST_TRACK_DEVICE_STATE` (`TDS_ID`, `TDS_NAME`, `TDS_DESC`, `TDS_DESC_OTH`, `TDS_STATUS`, `TDS_DT_CREATE`, `TDS_UID_CREATE`)
 VALUES ('ACTIVATE', 'ACTIVATE', 'ACTIVATE', 'ACTIVATE', 'A', sysdate(), 'sys');
 
INSERT INTO `clickargo2`.`T_CK_CT_MST_TRACK_DEVICE_STATE` (`TDS_ID`, `TDS_NAME`, `TDS_DESC`, `TDS_DESC_OTH`, `TDS_STATUS`, `TDS_DT_CREATE`, `TDS_UID_CREATE`)
 VALUES ('DEACTIVATE', 'DEACTIVATE', 'DEACTIVATE', 'DEACTIVATE', 'A', sysdate(), 'sys');
 
ALTER TABLE `clickargo2`.`T_CK_CT_TRACK_DEVICE` DROP FOREIGN KEY `FK_CK_CT_TRACK_DEVICE_CK_CT_VEH`;

ALTER TABLE `clickargo2`.`T_CK_CT_TRACK_DEVICE` 
CHANGE COLUMN `TD_VEH_ID` `TD_VEH_ID` VARCHAR(35) NULL COMMENT 'VEHICLE TYPE - REFERENCES T_CK_CT_VEH:VH_ID' ,
ADD UNIQUE INDEX `TD_VEH_ID_UNIQUE` (`TD_VEH_ID` ASC) VISIBLE;

ALTER TABLE `clickargo2`.`T_CK_CT_TRACK_DEVICE` 
ADD CONSTRAINT `FK_CK_CT_TRACK_DEVICE_CK_CT_VEH`
  FOREIGN KEY (`TD_VEH_ID`)  REFERENCES `clickargo2`.`T_CK_CT_VEH` (`VH_ID`);

-- Above scripts executed in UAT -- 

/** For SP_0000 users */
-- INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','OP_CS','A','CUSTOMER SERVICE',NOW(),'SYS',NOW(),'SYS');

-- for testing only
-- INSERT INTO `T_CORE_USR` (`USR_UID`, `USR_ACCNID`, `USR_STATUS`, `USR_TYPE_ONLINE`, `USR_TYPE_MBOX`, `USR_NAME`, `USR_PASS_NID`, `USR_TITLE`, `USR_DEPT`, `USR_DT_REG`, `USR_DT_COMM`, `USR_ADDR1`, `USR_ADDR2`, `USR_ADDR3`, `USR_PCODE`, `USR_CITY`, `USR_PROV`, `USR_CTYCODE`, `USR_TEL`, `USR_FAX`, `USR_EMAIL`, `USR_PWD`, `USR_PWD_1`, `USR_PWD_2`, `USR_PWD_3`, `USR_PWD_4`, `USR_DT_PWD_LUPD`, `USR_PWD_FORCE`, `USR_LOGIN_INVCNT`, `USR_DT_LOGINOK`, `USR_DT_LOGINERR`, `USR_MBOX_ID`, `USR_DT_CREATE`, `USR_UID_CREATE`, `USR_DT_LUPD`, `USR_UID_LUPD`) VALUES ('SP_ALKNAR_0000', 'ALKNAR', 'A', 'Y', 'N', 'ALKNAR Customer Servier', '88888888', 'Officer', 'OP', '2022-10-01 00:00:00', '2022-10-01 00:00:00', 'Kawasan Industri Cimareme', 'Jalan Industri Cimareme II No. 14', 'Padalarang, West Bandung - 40553', '40553', 'Jakarta', 'Jakarta', 'ID', '+627221056111', '', 'nina.catudio@guud.company', '001bfd9566b8523747a4b5f87f3544ab', '001bfd9566b8523747a4b5f87f3544ab', '', '', '', '2023-08-24 12:22:51', '', '0', '2022-10-01 00:00:00', '2022-10-01 00:00:00', '', '2022-10-01 00:00:00', 'SYS', '2023-08-31 15:11:01', 'ALKNAR_U001');
-- INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('SP_ALKNAR_0000','CKT','OP_CS','N','A',NOW(),'SYS', NOW(),'SYS','N');

CREATE TABLE `T_CK_CS_ACCN` (
  `CSA_ID` varchar(35) NOT NULL COMMENT 'RECORD ID - UUID',
  `CSA_SERVICE_TYPE` varchar(35) DEFAULT NULL COMMENT 'SERVICE TYPE - REFERENCES T_CK_MST_SERVICE_TYPE:SVCT_ID',
  `CSA_COMPANY` varchar(35) DEFAULT NULL COMMENT 'COMPANY ACCOUNT - REFERENCES T_CORE_ACCN:ACCN_ID',  
  `CSA_USR` varchar(35) DEFAULT NULL COMMENT 'CUSTOMER SERVICE - REFERENCES T_CORE_USR:USR_UID',  
  `CSA_STATUS` char(1) DEFAULT NULL COMMENT 'CREDIT RECORD STATUS',
  `CSA_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CSA_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CSA_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CSA_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CSA_ID`),
  CONSTRAINT `FK_CK_CS_ACCN_CK_MST_SERVICE_TYPE` FOREIGN KEY (`CSA_SERVICE_TYPE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),
  CONSTRAINT `FK_CK_CS_ACCN_CORE_ACCN` FOREIGN KEY (`CSA_COMPANY`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),  
  CONSTRAINT `FK_CK_CS_ACCN_CORE_USR` FOREIGN KEY (`CSA_USR`) REFERENCES `T_CORE_USR` (`USR_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='CUSTOMER SERVICE ACCOUNTS TABLE';


ALTER TABLE `T_CK_PAYMENT_TXN` 
ADD COLUMN `PTX_PAYEE_BANK_ACCN_NAME` VARCHAR(255) NULL COMMENT 'BANK ACCOUNT NAME CAPTURE FROM T_CORE_ACCN_CONFIG' AFTER `PTX_PAYEE_BANK_ACCN`;

/** Added DN_DT_PAID and DN_PAYMENT_TXN_REF for T_CK_CT_DEBIT_NOTE */
ALTER TABLE `T_CK_CT_DEBIT_NOTE` 
ADD COLUMN `DN_DT_PAID` DATETIME NULL DEFAULT NULL COMMENT 'Debit Note Paid Date' AFTER `DN_DT_DUE`;
ALTER TABLE `T_CK_CT_DEBIT_NOTE` 
ADD COLUMN `DN_PAYMENT_TXN_REF` VARCHAR(35) NULL DEFAULT NULL COMMENT 'Debit Note Transaction Reference from ID of Payment Transaction' AFTER `DN_PAYMENT_REF`;

/** Added INV_DT_PAID and INV_PAYMENT_TXN_REF for T_CK_CT_PLATFORM_INVOICE */
ALTER TABLE `T_CK_CT_PLATFORM_INVOICE` 
ADD COLUMN `INV_DT_PAID` DATETIME NULL DEFAULT NULL COMMENT 'Platform Invoice Paid Date' AFTER `INV_DT_DUE`;
ALTER TABLE `T_CK_CT_PLATFORM_INVOICE` 
ADD COLUMN `INV_PAYMENT_TXN_REF` VARCHAR(35) NULL DEFAULT NULL COMMENT 'Platform Invoice Transaction Reference from ID of Payment Transaction' AFTER `INV_NO`;

/** CT-138 User Management */
	/** Delete previously created CUSTOMER_SERVICE - START */
	DELETE FROM `T_CORE_USR_ROLE` WHERE UROL_ROLEID = 'CUSTOMER_SERVICE' AND UROL_APPSCODE = 'CKT';
	DELETE FROM `T_CORE_ROLE` WHERE ROLE_ID = 'CUSTOMER_SERVICE' AND ROLE_APPSCODE = 'CKT';
	DELETE FROM `T_CORE_GRANT_ROLE_EX` WHERE GNTRLEX_ROLE_ID = 'CUSTOMER_SERVICE' AND GNTRLEX_APPS_CODE = 'CKT';
	/** Delete previously created CUSTOMER_SERVICE - END */
	
INSERT INTO T_CORE_SYSPARAM (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) 
VALUES ('CLICKTRUCK_MAP_TRACE_URL', 'https://ext.logistics.myascents.net/customised/map?key=$2a$11$oo7.I606K/DVjUdZi88UzeFu.tLQiwTChnty4KATKbf3Dq0T8s2Ii', 'CLICKTRUCK_MAP_TRACE_URL', '2023-05-05 00:00:00', 'SYS', '2023-05-05 00:00:00', 'SYS', 'A');
/*whatApp notification JSON FORM*/
INSERT INTO t_core_sysparam (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_WHATAPP_FORM', '{\"from\":\"+6591459697\",\"to\":null,\"type\":\"template\",\"template\":{\"name\":null,\"language\":{\"code\":\"en\",\"policy\":\"deterministic\"},\"components\":[{\"type\":\"body\",\"parameters\":[{\"type\":\"text\",\"text\":null},{\"type\":\"text\",\"text\":null}]}]}}', 'CLICTRUCK_WHATAPP_FORM', '2024-04-30 00:00:00', 'SYS', '2024-04-30 00:00:00', 'SYS', 'A');
INSERT INTO t_core_sysparam (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_WHATSAPP_NOTIF_ACCNS', 'CQS', 'CLICTRUCK_WHATSAPP_NOTIF_ACCNS', '2024-04-30 00:00:00', 'SYS', '2024-04-30 00:00:00', 'SYS', 'A');
INSERT INTO t_core_sysparam VALUES ('CLICTRUCK_UAT_BASE_URL', 'https://ct2-uat.clickargo.com', 'CLICTRUCK_UAT_BASE_URL', '2024-04-30 00:00:00', 'SYS', '2024-04-30 00:00:00', 'SYS', 'A');
-- below executed in UAT -
DELETE FROM T_CORE_GRANT_ROLE_EX WHERE GNTRLEX_PERM_ID = 'PM076' AND GNTRLEX_ROLE_ID = 'SP_OP_ADMIN' AND GNTRLEX_STATUS='A';
/*whatApp notification JSON FORM*/
INSERT INTO T_CORE_SYSPARAM (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_WHATAPP_FORM', '{\"from\":\"+6591459697\",\"to\":null,\"type\":\"template\",\"template\":{\"name\":null,\"language\":{\"code\":\"en\",\"policy\":\"deterministic\"},\"components\":[{\"type\":\"body\",\"parameters\":[{\"type\":\"text\",\"text\":null},{\"type\":\"text\",\"text\":null}]}]}}', 'CLICTRUCK_WHATAPP_FORM', '2024-04-30 00:00:00', 'SYS', '2024-04-30 00:00:00', 'SYS', 'A');
INSERT INTO T_CORE_SYSPARAM (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_WHATSAPP_NOTIF_ACCNS', 'CQS', 'CLICTRUCK_WHATSAPP_NOTIF_ACCNS', '2024-04-30 00:00:00', 'SYS', '2024-04-30 00:00:00', 'SYS', 'A');
INSERT INTO T_CORE_SYSPARAM VALUES ('CLICTRUCK_UAT_BASE_URL', 'https://ct2-uat.clickargo.com', 'CLICTRUCK_UAT_BASE_URL', '2024-04-30 00:00:00', 'SYS', '2024-04-30 00:00:00', 'SYS', 'A');
/*Add new column for T_CK_CT_JOB_TRIP_DELIVERY to set state of delivery*/
ALTER TABLE T_CK_CT_JOB_TRIP_DELIVERY
ADD COLUMN JTD_MSG_STATE VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT 'SET STATE WHATSAPP NOTIFICATION IS SENT DONE';
/*UPDATE T_MST_ACCN_TYPE Text Incorrect*/
UPDATE `clickargo2`.`T_MST_ACCN_TYPE` SET `ATYP_DESCRIPTION` = 'FREIGHT FORWARDER' WHERE `ATYP_ID` = 'ACC_TYPE_FF';
/*ADD WHATSAPP API-KEY AND FORM*/
INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_WHATAPP_FORM', '{\"from\":\"+6591459697\",\"to\":null,\"type\":\"template\",\"template\":{\"name\":null,\"language\":{\"code\":\"en\",\"policy\":\"deterministic\"},\"components\":[{\"type\":\"body\",\"parameters\":[{\"type\":\"text\",\"text\":null}]}]}}', 'CLICTRUCK_WHATAPP_FORM', '2024-04-30 00:00:00', 'SYS', '2024-04-30 00:00:00', 'SYS', 'A');
INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_WHATAPP_YCLOUD_APIKEY', 'cd54dca22321ab4d6d322ebd9cb2b007', 'CLICTRUCK_WHATAPP_FORM', '2024-04-30 00:00:00', 'SYS', '2024-04-30 00:00:00', 'SYS', 'A');

CREATE TABLE `T_CK_CT_MST_ALERT` (
 `ALT_ID` varchar(100) NOT NULL COMMENT 'UNIQUE ID: SYSTEM GENERATED',
 `ALT_NAME` varchar(100) NOT NULL COMMENT 'THE NAME OF THE ALERT. SHOWN TO USERS TO SELECT',
 `ALT_MODULE` varchar(100) NOT NULL COMMENT 'THE MODULE/FEATURE THE ALERT IS RELATED TO. USED TO DEFINE WHICH ALERTS WILL BE SHOWN TO USER WHEN CREATING A NEW ALERT',
 `ALT_NOTIFICATION_TYPE` varchar(100) DEFAULT NULL COMMENT 'THE DEVICE TYPE USED TO SEND THE ALERT',
 `ALT_TEMPLATE_ID` varchar(100) DEFAULT NULL COMMENT 'REFERENCES THE TEMPLATES TO BE USED FOR POPULATING THE ALERT MESSAGE',
 `ALT_CONDITION_TYPE` varchar(100) DEFAULT NULL COMMENT 'THE DIFFERENT CONDITIONS APPLICABLE TO THIS ALERT. USED TO DEFINE WHICH CONDITION TYPES WILL BE SHOWN TO USER WHEN CREATING A NEW ALERT NOTE: WILL BE NULL FOR JOB MODULE ALERTS SINCE THEY ARE TRIGGERED BY JOB EVENTS',
 `ALT_STATUS` char(1) DEFAULT NULL COMMENT 'ACTIVE, INACTIVE',
 `ALT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
 `ALT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
 `ALT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
 `ALT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
 PRIMARY KEY (`ALT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='SAGE INTEGRATION STATE MASTER TABLE';

CREATE TABLE `T_CK_CT_ALERT` (
 `ALT_ID` VARCHAR(100) NOT NULL COMMENT 'UNIQUE ID. SYSTEM GENERATED',
 `ALT_ACCN_ID` VARCHAR(35) NOT NULL COMMENT 'ACCOUNT THE ALERT BELONGS TO. REFERENCES T_CORE_ACCN: ACCN_ID',
 `ALT_ALERT_MASTER_TABLE_REF_ID` VARCHAR(100) NOT NULL COMMENT 'REFERENCE ALERT ID FROM ALERT MASTER TABLE. REFERENCES T_CK_CT_MST_ALERT: ALERT ID',
 `ALT_CONDITION_TYPE` varchar(100) NOT NULL COMMENT 'RULE TO CHECK AGAINST TO DECIDE IF THE ALERT IS TRIGGERED. VALUES: DAYS_BEFORE, DISTANCE',
 `ALT_CONDITION_VALUE` varchar(255) DEFAULT NULL COMMENT 'VALUE RELATED TO CONDITION TYPE, E.G., 10',
 `ALT_CONDITION_DATE` DATE DEFAULT NULL COMMENT 'DATE RELATED TO CONDITION TYPE. DISPLAY LABEL: DUE DATE OR EXPIRY DATE. DISPLAY FORMAT: DD/MM/YYYY',
 `ALT_REFERENCE_ID` VARCHAR(35) DEFAULT NULL COMMENT 'THE UNIQUE ID OF THE DRIVER/TRUCK THAT THIS ALERT IS RELATED TO',
 `ALT_RECIPIENT_CONTACT` VARCHAR(100) DEFAULT NULL COMMENT 'CONTACT INFO THAT WILL RECEIVE THE ALERT, E.G., +6512345678 OR TEST@EXAMPLE.COM',
 `ALT_REMARKS` MEDIUMTEXT COMMENT 'REMARKS ENTERED BY USER FOR THIS ALERT, E.G., SPECIFIC PARTS TO TAKE NOTE DURING MAINTENANCE CHECK',
 `ALT_STATUS` CHAR(1) DEFAULT NULL COMMENT 'ACTIVE, INACTIVE',
 `ALT_DT_CREATE` DATETIME DEFAULT NULL COMMENT 'RECORD CREATED DATE',
 `ALT_UID_CREATE` VARCHAR(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
 `ALT_DT_LUPD` DATETIME DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
 `ALT_UID_LUPD` VARCHAR(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
 PRIMARY KEY (`ALT_ID`),
 FOREIGN KEY (`ALT_ACCN_ID`) REFERENCES `T_CORE_ACCN`(`ACCN_ID`),
 FOREIGN KEY (`ALT_ALERT_MASTER_TABLE_REF_ID`) REFERENCES `T_CK_CT_MST_ALERT`(`ALT_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb3 COMMENT='TABLE TO STORE EACH ACCOUNT''S CONFIGURED ALERTS DETAILS';

-- do not add below this line --
