/** For Track & Trace SG Requirement */
DROP TABLE IF EXISTS T_CK_CT_VEH_EXT;
CREATE TABLE `T_CK_CT_VEH_EXT` (
  `VEXT_ID` varchar(35) NOT NULL COMMENT 'VEHICLE ID - REFERENCES T_CK_CT_VEH',
  `VEXT_PARAM` varchar(255) NOT NULL COMMENT 'VEHICLE EXT PARAM',
  `VEXT_VALUE` varchar(2048) DEFAULT NULL COMMENT 'VEHICLE EXT VALUE',
  `VEXT_MONITOR_MTHD` char(1) DEFAULT 'D' COMMENT 'VEHICLE EXT MONITOR MTHD - Date|Odometer|',  
  `VEXT_MONITOR_VALUE` varchar(2048) DEFAULT NULL COMMENT 'VEHICLE EXT MONITOR VALUE', 
  `VEXT_NOTIFY` char(1) DEFAULT 'N' COMMENT 'VEHICLE EXT NOTIFICATION - Y|N',
  `VEXT_NOTIFY_EMAIL` varchar(1024) DEFAULT NULL COMMENT 'VEHICLE EXT NOTIFICATION EMAIL',
  `VEXT_NOTIFY_WHATSAPP` varchar(1024) DEFAULT NULL COMMENT 'VEHICLE EXT NOTIFICATION WHATSAPP',
  `VEXT_REMARKS` mediumtext COMMENT 'REMARKS FOR VEH EXT DETAILS',
  `VEXT_STATUS` char(1) DEFAULT NULL COMMENT 'VEHICLE STATE STATUS',
  `VEXT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `VEXT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `VEXT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `VEXT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`VEXT_ID`, `VEXT_PARAM`),
  CONSTRAINT `FK_CK_CT_VEH_EXT_CK_CT_VEH` FOREIGN KEY (`VEXT_ID`) REFERENCES `T_CK_CT_VEH` (`VH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='VEHICLE EXTENSION TABLE';

CREATE TABLE `T_CK_CT_VEH_MLOG` (
  `VML_ID` varchar(35) NOT NULL COMMENT 'VEHICLE MAINTENANCE LOG ID - UUID',
  `VML_VEH_ID` varchar(35) NOT NULL COMMENT 'VEHICLE ID - REFERENCES T_CK_CT_VEH',
  `VML_DT_START` datetime DEFAULT NULL COMMENT 'MAINTENANCE START DATE',
  `VML_DT_END` datetime DEFAULT NULL COMMENT 'MAINTENANCE END DATE',
  `VML_COST` decimal(15,2) DEFAULT '0.00' COMMENT 'MAINTENANCE COST - 320.50',
  `VML_REMARKS` mediumtext COMMENT 'REMARKS FOR VEH EXT DETAILS',
  `VML_STATUS` char(1) DEFAULT NULL COMMENT 'VEHICLE STATE STATUS - A|C',
  `VML_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `VML_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `VML_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `VML_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`VML_ID`),
  CONSTRAINT `FK_CK_CT_VEH_MLOG_CK_CT_VEH` FOREIGN KEY (`VML_VEH_ID`) REFERENCES `T_CK_CT_VEH` (`VH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='VEHICLE MAINTENANCE LOG TABLE';


-- for the sys admin
INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','SYS_SUPER_ADMIN','A','SYSTEM SUPER ADMIN',NOW(),'SYS',NOW(),'SYS');
INSERT INTO `T_CORE_USR` (`USR_UID`, `USR_ACCNID`, `USR_STATUS`, `USR_TYPE_ONLINE`, `USR_TYPE_MBOX`, `USR_NAME`, `USR_PASS_NID`, `USR_TITLE`, `USR_DEPT`, `USR_DT_REG`, `USR_DT_COMM`, `USR_ADDR1`, `USR_ADDR2`, `USR_ADDR3`, `USR_PCODE`, `USR_CITY`, `USR_PROV`, `USR_CTYCODE`, `USR_TEL`, `USR_FAX`, `USR_EMAIL`, `USR_PWD`, `USR_PWD_1`, `USR_PWD_2`, `USR_PWD_3`, `USR_PWD_4`, `USR_DT_PWD_LUPD`, `USR_PWD_FORCE`, `USR_LOGIN_INVCNT`, `USR_DT_LOGINOK`, `USR_DT_LOGINERR`, `USR_MBOX_ID`, `USR_DT_CREATE`, `USR_UID_CREATE`, `USR_DT_LUPD`, `USR_UID_LUPD`) VALUES ('GLI_SYS_ADMIN', 'GLI', 'A', 'Y', 'N', 'GLI SYSTEM ADMINISTRATOR', '888888888', 'Officer', 'OP', '2022-10-01 00:00:00', '2022-10-01 00:00:00', 'Wisma Keiai 12A Floor', 'l.Jendral Sudirman Kav. 3', 'Jakarta 10220', '10220', 'Jakarta', '', 'ID', '622476928448', '', 'nina.catudio+glisysad@guud.company', 'd8a2765ad56c1cde39206acb5e1d6fb9', '', '', '', '', '2023-12-01 00:00:00', '', '0', '2022-10-01 00:00:00', '2022-10-01 00:00:00', '', '2022-10-01 00:00:00', 'SYS', '2023-12-18 16:50:59', 'SYS');
INSERT INTO T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE) VALUES('GLI_SYS_ADMIN','CKT','SYS_SUPER_ADMIN','N','A',NOW(),'SYS', NOW(),'SYS','N');

INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_SA_090000','CKT','System Administrations','System Administrations','System Administrations','System Administrations','90000','/reports/list','settings',NULL,'A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO T_CORE_MENU_EX (MENU_ID, MENU_APPS_CODE, MENU_GROUP_LABEL, MENU_GROUP_LABEL_OTH, MENU_NAME, MENU_NAME_OTH, MENU_SEQ, MENU_PATH, MENU_ICON, MENU_PARENT, MENU_STATUS, MENU_DT_CREATE, MENU_UID_CREATE, MENU_DT_LUPD, MENU_UID_LUPD)  VALUES('CKT_SA_090100','CKT','','','System Parameters','System Parameters','90100','/administrations/sysparam/list',NULL,'CKT_SA_090000','A',NOW(),'SYS',NOW(),'SYS');

INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM071', 'Y', 'CKT', NULL, 'M', NULL, NULL, 'CKT_SA_090000', 'System Administrations', 'System Administrations','System Administrations','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');
INSERT INTO `T_CORE_PERM_EX` (`PERM_ID`, `PERM_GROUP`, `PERM_APPS`, `PERM_MODULE`, `PERM_TYPE`, `PERM_SERVICE`, `PERM_SERVICE_URI`, `PERM_MENU`,`PERM_MENU_NAME`,`PERM_DESC`, `PERM_DESC_OTH`, `PERM_ACCESS`, `PERM_DT_ACTIVE`, `PERM_DT_DEACTIVE`, `PERM_STATUS`, `PERM_DT_CREATE`, `PERM_UID_CREATE`,`PERM_DT_LUPD`, `PERM_UID_LUPD`) VALUES ('PM072', 'Y', 'CKT', NULL, 'M', NULL, NULL, 'CKT_SA_090100', 'System Parameters', 'System Parameters','System Parameters','R', '2021-04-14 11:08:00', '2999-12-31 23:59:59', 'A', '2021-04-14 11:08:00', 'SYS', '2021-04-14 11:08:00', 'SYS');

INSERT INTO `T_CORE_GRANT_ROLE_EX` (`GNTRLEX_APPS_CODE`, `GNTRLEX_ROLE_ID`, `GNTRLEX_PERM_ID`, `GNTRLEX_STATUS`, `GNTRLEX_DT_CREATE`, `GNTRLEX_UID_CREATE`) VALUES ('CKT', 'SYS_SUPER_ADMIN', 'PM072', 'A', NOW(), 'SYS');

INSERT INTO T_CORE_SYSPARAM (SYS_KEY,SYS_VAL,SYS_DESC,SYS_DT_CREATE,SYS_UID_CREATE,SYS_DT_LUPD,SYS_UID_LUPD,SYS_STATUS) values
	('CLICTRUCK_MYASCENTS_ODOMETER_REGISTER_URL','https://ext.logistics.myascents.net/api/3rdparty/unit/odometer/notification?key=%242a%2411%24oo7.I606K%2FDVjUdZi88UzeFu.tLQiwTChnty4KATKbf3Dq0T8s2Ii','Ascent odometer register notification',NOW(),'SYS',NOW(),'SYS','A'),
	('CLICTRUCK_MYASCENTS_ODOMETER_DEREGISTER_URL','https://ext.logistics.myascents.net/api/3rdparty/unit/odometer/notification?key=%242a%2411%24oo7.I606K%2FDVjUdZi88UzeFu.tLQiwTChnty4KATKbf3Dq0T8s2Ii&imei=','Ascent odometer deregister notification',NOW(),'SYS',NOW(),'SYS','A');
	