/** For 2.0.1 items **/

CREATE TABLE `T_CK_CT_RATE_TABLE_REMARK` (
  `RTR_ID` varchar(35) NOT NULL COMMENT 'RATE TABLE REMARK ID - UUID',
  `RTR_RATE_TABLE` varchar(35) NOT NULL COMMENT 'RATE TABLE TABLE - REFERENCES  T_CK_CT_RATE_TABLE:RT_ID',
  `RTR_TYPE` char(1) NOT NULL COMMENT 'REMARK TYPE – A (APPROVE):R (REJECT)',
  `RTR_COMMENT` mediumtext DEFAULT NULL COMMENT 'COMMENT',
  `RTR_STATUS` char(1) DEFAULT NULL COMMENT 'RATE TABLE REMARK STATE STATUS',
  `RTR_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `RTR_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `RTR_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `RTR_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`RTR_ID`),
  CONSTRAINT `FK_CK_CT_RATE_TABLE_REMARK_CK_CT_RATE_TABLE` FOREIGN KEY (`RTR_RATE_TABLE`) REFERENCES `T_CK_CT_RATE_TABLE` (`RT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='RATE TABLE REMARK';

INSERT INTO `T_CK_MST_ENTITY_TYPE` (`ENTY_ID`, `ENTY_NAME`, `ENTY_DESC`, `ENTY_DESC_OTH`, `ENTY_STATUS`, `ENTY_DT_CREATE`, `ENTY_UID_CREATE`, `ENTY_DT_LUPD`, `ENTY_UID_LUPD`) VALUES ('TRIP_RATE_TABLE', 'TRUCK Trip Rate Table', 'TRUCK Trip Rate Table', 'TRUCK Trip Rate Table', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');

INSERT INTO `T_CK_MST_FORM_ACTION` (`FMACT_ID`, `FMACT_NAME`, `FMACT_DESC`, `FMACT_DESC_OTH`, `FMACT_STATUS`, `FMACT_DT_CREATE`, `FMACT_UID_CREATE`, `FMACT_DT_LUPD`, `FMACT_UID_LUPD`) VALUES ('DEACTIVATE', 'Form Deactivate', 'Form Deactivate', 'Form Deactivate', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');
INSERT INTO `T_CK_MST_FORM_ACTION` (`FMACT_ID`, `FMACT_NAME`, `FMACT_DESC`, `FMACT_DESC_OTH`, `FMACT_STATUS`, `FMACT_DT_CREATE`, `FMACT_UID_CREATE`, `FMACT_DT_LUPD`, `FMACT_UID_LUPD`) VALUES ('ACTIVATE', 'Form Activate', 'Form Activate', 'Form Activate', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');

INSERT INTO `T_CK_MST_JOB_STATE` (`JBST_ID`, `JBST_NAME`, `JBST_DESC`, `JBST_DESC_OTH`, `JBST_STATUS`, `JBST_DT_CREATE`, `JBST_UID_CREATE`, `JBST_DT_LUPD`, `JBST_UID_LUPD`) VALUES ('INACTIVE', 'INACTIVE', 'INACTIVE', 'INACTIVE', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

INSERT INTO `T_CK_MST_ENTITY_STATE` (`ENST_ID`, `ENST_NAME`, `ENST_DESC`, `ENST_DESC_OTH`, `ENST_STATUS`, `ENST_DT_CREATE`, `ENST_UID_CREATE`, `ENST_DT_LUPD`, `ENST_UID_LUPD`) VALUES ('INACTIVE', 'INACTIVE', 'INACTIVE', 'INACTIVE', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');




-- For credit limit update -- 
CREATE TABLE `T_CK_MST_CREDIT_UPDATE_STATE` (
  `ST_ID` varchar(35) NOT NULL COMMENT 'CREDIT UPDATE STATE ID - NEW : SUBMITTED : DELETED : APPROVE : REJECTED : ACTIVE',
  `ST_NAME` varchar(100) NOT NULL COMMENT 'CREDIT UPDATE  STATE NAME',
  `ST_DESC` varchar(255) DEFAULT NULL COMMENT 'CREDIT UPDATE STATE DESCRIPTION',
  `ST_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'CREDIT UPDATE STATE DESCRIPTION OTHER LANGUAGE',
  `ST_STATUS` char(1) DEFAULT NULL COMMENT 'CREDIT UPDATE STATE STATUS',
  `ST_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `ST_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `ST_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `ST_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`ST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='CREDIT UPDATE STATE TABLE';

INSERT INTO `T_CK_MST_CREDIT_UPDATE_STATE` (`ST_ID`,`ST_NAME`,`ST_DESC`,`ST_DESC_OTH`,`ST_STATUS`,`ST_DT_CREATE`,`ST_UID_CREATE`,`ST_DT_LUPD`,`ST_UID_LUPD`)  VALUES('NEW','NEW','NEW','NEW','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO `T_CK_MST_CREDIT_UPDATE_STATE` (`ST_ID`,`ST_NAME`,`ST_DESC`,`ST_DESC_OTH`,`ST_STATUS`,`ST_DT_CREATE`,`ST_UID_CREATE`,`ST_DT_LUPD`,`ST_UID_LUPD`)  VALUES('SUB','SUBMITTED','SUBMITTED','SUBMITTED','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO `T_CK_MST_CREDIT_UPDATE_STATE` (`ST_ID`,`ST_NAME`,`ST_DESC`,`ST_DESC_OTH`,`ST_STATUS`,`ST_DT_CREATE`,`ST_UID_CREATE`,`ST_DT_LUPD`,`ST_UID_LUPD`)  VALUES('DEL','DELETED','DELETED','DELETED','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO `T_CK_MST_CREDIT_UPDATE_STATE` (`ST_ID`,`ST_NAME`,`ST_DESC`,`ST_DESC_OTH`,`ST_STATUS`,`ST_DT_CREATE`,`ST_UID_CREATE`,`ST_DT_LUPD`,`ST_UID_LUPD`)  VALUES('APP','APPROVED','APPROVED','APPROVED','A',NOW(),'SYS',NOW(),'SYS');
INSERT INTO `T_CK_MST_CREDIT_UPDATE_STATE` (`ST_ID`,`ST_NAME`,`ST_DESC`,`ST_DESC_OTH`,`ST_STATUS`,`ST_DT_CREATE`,`ST_UID_CREATE`,`ST_DT_LUPD`,`ST_UID_LUPD`)  VALUES('REJ','REJECTED','REJECTED','REJECTED','A',NOW(),'SYS',NOW(),'SYS');

CREATE TABLE `T_CK_CREDIT_UPDATE` (
  `CRU_ID` varchar(35) NOT NULL COMMENT 'RECORD ID - UUID',
  `CRU_SERVICE_TYPE` varchar(35) DEFAULT NULL COMMENT 'CREDIT SERVICE TYPE - REFERENCES T_CK_MST_CREDIT_UPDATE_STATE:ST_ID',
  `CRU_COMPANY` varchar(35) DEFAULT NULL COMMENT 'CREDIT COMPANY ACCOUNT - REFERENCES T_CORE_ACCN:ACCN_ID',
  `CRU_STATE` varchar(35) DEFAULT NULL COMMENT 'CREDIT STATE - REFERENCES T_CK_MST_CREDIT_STATE:CRST_ID',
  `CRU_AMT` double(15,2) DEFAULT '0.00' COMMENT 'CREDIT AMOUNT',
  `CRU_TXN_CAP` double(15,2) DEFAULT NULL COMMENT 'MONTHLY TRANSACTION CAP',
  `CRU_CCY` varchar(3) DEFAULT NULL COMMENT 'CURRENCY  - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `CRU_DT_START` datetime DEFAULT NULL COMMENT 'CREDIT START DATE TIME',
  `CRU_DT_END` datetime DEFAULT NULL COMMENT 'CREDIT END DATE TIME',
  `CRU_REMARKS` mediumtext COMMENT 'REMARKS FROM REQUESTER',
  `CRU_USR_VERIFY` varchar(35) DEFAULT NULL COMMENT 'CREDIT VERIFIER',
  `CRU_DT_VERIFY` datetime DEFAULT NULL COMMENT 'CREDIT VERIFIED DATE TIME',
  `CRU_USR_APPROVE` varchar(35) DEFAULT NULL COMMENT 'CREDIT APPROVER',
  `CRU_DT_APPROVE` datetime DEFAULT NULL COMMENT 'CREDIT APPROVED DATE TIME',
  `CRU_USR_REJECT` varchar(35) DEFAULT NULL COMMENT 'CREDIT REJECT',
  `CRU_DT_REJECT` datetime DEFAULT NULL COMMENT 'CREDIT REJECT DATE TIME',
  `CRU_APPROVER_REMARKS` mediumtext COMMENT 'REMARKS FOR CREDIT APPROVAL OR REJECTION',
  `CRU_STATUS` char(1) DEFAULT NULL COMMENT 'CREDIT RECORD STATUS',
  `CRU_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CRU_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CRU_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CRU_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CRU_ID`),
  CONSTRAINT `FK_CK_CREDIT_UPDATE_CK_MST_CREDIT_UPDATE_STATE` FOREIGN KEY (`CRU_STATE`) REFERENCES `T_CK_MST_CREDIT_UPDATE_STATE` (`ST_ID`),
  CONSTRAINT `FK_CK_CREDIT_UPDATE_CK_MST_SERVICE_TYPE` FOREIGN KEY (`CRU_SERVICE_TYPE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),
  CONSTRAINT `FK_CK_CREDIT_UPDATE_CORE_ACCN` FOREIGN KEY (`CRU_COMPANY`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_CREDIT_UPDATE_MST_CURRENCY` FOREIGN KEY (`CRU_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='CREDIT UPDATE TABLE';

INSERT INTO `T_CK_MST_ENTITY_TYPE` (`ENTY_ID`, `ENTY_NAME`, `ENTY_DESC`, `ENTY_DESC_OTH`, `ENTY_STATUS`, `ENTY_DT_CREATE`, `ENTY_UID_CREATE`, `ENTY_DT_LUPD`, `ENTY_UID_LUPD`) VALUES ('CREDIT_LIMIT', 'Credit Limit', 'Credit Limit', 'Credit Limit', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');
INSERT INTO `T_CK_MST_ENTITY_TYPE` (`ENTY_ID`, `ENTY_NAME`, `ENTY_DESC`, `ENTY_DESC_OTH`, `ENTY_STATUS`, `ENTY_DT_CREATE`, `ENTY_UID_CREATE`, `ENTY_DT_LUPD`, `ENTY_UID_LUPD`) VALUES ('JOB_TERMINATION', 'JOB Termination', 'JOB Termination', 'JOB Termination', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');


CREATE TABLE `T_CK_CT_JOB_TERM_REQ` (
  `JTR_ID` varchar(35) NOT NULL COMMENT 'JOB TERMINATION REQUEST ID - UUID',
  `JTR_ACCN` varchar(35) NOT NULL COMMENT 'CO COMPANY RELATED TO JOBS - REFERENCES T_CORE_ACCN:ACCN_ID',
  `JTR_CR_LIMIT` double(15,2) DEFAULT '0.00' COMMENT 'CREDIT AMOUNT',
  `JTR_CR_BAL` double(15,2) DEFAULT '0.00' COMMENT 'CREDIT BALANCE',
  `JTR_INV_OPEN` int DEFAULT 0 COMMENT 'NUMBER OF OPEN INVOICES',
  `JTR_AMT_OPEN` double(15,2) DEFAULT '0.00' COMMENT 'OUTSTANDING AM OUNT OF DN+INV',
  `JTR_DT_DUE_INV` datetime DEFAULT NULL COMMENT 'EARLIEST DUED INVOICE',
  `JTR_NO_JOBS` smallint DEFAULT 0 COMMENT 'NUMBER OF JOBS TO BE TERMINATED',
  `JTR_JOBS_PLTFEE_AMT` decimal(15,2) DEFAULT '0.00' COMMENT 'JOBS TOTAL PLATFORM FEE',
  `JTR_JOBS_DN_AMT` decimal(15,2) DEFAULT '0.00' COMMENT 'JOBS TOTAL DN FEE',
  `JTR_JOBS_DEFAULT` decimal(15,2) DEFAULT '0.00' COMMENT 'JOBS TOTAL DEFAULTED',
  `JTR_UID_REQUESTOR` varchar(35) DEFAULT NULL COMMENT 'UID REQUESTOR',
  `JTR_COMMENT_REQUESTOR` mediumtext DEFAULT NULL COMMENT 'REQUESTOR COMMENT',
  `JTR_DT_SUBMIT` datetime DEFAULT NULL COMMENT 'DATE OF SUMBISSION',
  `JTR_UID_APPROVER` varchar(35) DEFAULT NULL COMMENT 'UID APPROVER',
  `JTR_COMMENT_APPROVER` mediumtext DEFAULT NULL COMMENT 'APPROVER COMMENT',
  `JTR_DT_APPROVE_REJECT` datetime DEFAULT NULL COMMENT 'DATE OF APPROVAL OR REJECTION',
  `JTR_COMMENT` mediumtext DEFAULT NULL COMMENT 'COMMENT FOR THE REJECTION',
  `JTR_STATUS` char(1) DEFAULT NULL COMMENT 'RATE TABLE REJECT STATE STATUS',
  `JTR_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `JTR_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `JTR_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `JTR_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`JTR_ID`),
  CONSTRAINT `FK_CK_CT_JOB_TERM_CORE_ACCN` FOREIGN KEY (`JTR_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='JOB TERMINATION REQUEST TABLE';


CREATE TABLE `T_CK_CT_JOB_TERM` (
  `JT_ID` varchar(35) NOT NULL COMMENT 'JOB TERMINATION ID - UUID',
  `JT_REQ` varchar(35) NOT NULL COMMENT 'TERMINATION REQUEST - REFERENCES T_CK_CT_JOB_TERM_REQ:JTR_ID',
  `JT_JOB` varchar(35) NOT NULL COMMENT 'TERMINATION REQUEST - REFERENCES T_CK_JOB_TRUCK:JOB_ID',
  `JT_JOB_DN` double(15,2) DEFAULT '0.00' COMMENT 'DN AMOUNT',
  `JT_JOB_PLTFEE_AMT_COFF` double(15,2) DEFAULT '0.00' COMMENT 'COFF PLATFORM FEE AMOUNT',
  `JT_JOB_PLTFEE_AMT_TO` double(15,2) DEFAULT '0.00' COMMENT 'TO PLATFORM FEE AMOUNT',
  `JT_STATUS` char(1) DEFAULT NULL COMMENT 'RATE TABLE REJECT STATE STATUS',
  `JT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `JT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `JT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `JT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`JT_ID`),
  CONSTRAINT `FK_CK_CT_JOB_TERM_CK_CT_JOB_TERM_REQ` FOREIGN KEY (`JT_REQ`) REFERENCES `T_CK_CT_JOB_TERM_REQ` (`JTR_ID`),
  CONSTRAINT `FK_CK_CT_JOB_TERM_CK_JOB_TRUCK` FOREIGN KEY (`JT_JOB`) REFERENCES `T_CK_JOB_TRUCK` (`JOB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='JOB TERMINATION TABLE';


INSERT INTO `T_CK_MST_FORM_ACTION` (`FMACT_ID`, `FMACT_NAME`, `FMACT_DESC`, `FMACT_DESC_OTH`, `FMACT_STATUS`, `FMACT_DT_CREATE`, `FMACT_UID_CREATE`, `FMACT_DT_LUPD`, `FMACT_UID_LUPD`) VALUES ('SUSPEND', 'Form Suspend', 'Form Suspend', 'Form Suspend', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');
INSERT INTO `T_CK_MST_ENTITY_STATE` (`ENST_ID`, `ENST_NAME`, `ENST_DESC`, `ENST_DESC_OTH`, `ENST_STATUS`, `ENST_DT_CREATE`, `ENST_UID_CREATE`, `ENST_DT_LUPD`, `ENST_UID_LUPD`) VALUES ('SUS', 'SUSPENDED', 'SUSPENDED', 'BILLING VERIFIED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

INSERT INTO `T_CK_MST_FORM_ACTION` (`FMACT_ID`, `FMACT_NAME`, `FMACT_DESC`, `FMACT_DESC_OTH`, `FMACT_STATUS`, `FMACT_DT_CREATE`, `FMACT_UID_CREATE`, `FMACT_DT_LUPD`, `FMACT_UID_LUPD`) VALUES ('TERMINATE', 'Form Terminate', 'Form Terminate', 'Form Verify', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');
INSERT INTO `T_CK_MST_ENTITY_STATE` (`ENST_ID`, `ENST_NAME`, `ENST_DESC`, `ENST_DESC_OTH`, `ENST_STATUS`, `ENST_DT_CREATE`, `ENST_UID_CREATE`, `ENST_DT_LUPD`, `ENST_UID_LUPD`) VALUES ('TERMINATED', 'TERMINATED', 'TERMINATED', 'TERMINATED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

INSERT INTO `T_CK_MST_ENTITY_TYPE` (`ENTY_ID`, `ENTY_NAME`, `ENTY_DESC`, `ENTY_DESC_OTH`, `ENTY_STATUS`, `ENTY_DT_CREATE`, `ENTY_UID_CREATE`, `ENTY_DT_LUPD`, `ENTY_UID_LUPD`) VALUES ('ACCN_REGISTRATION', 'Account Registration', 'Account Registration', 'Account Registration', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');
INSERT INTO `T_CK_MST_ENTITY_TYPE` (`ENTY_ID`, `ENTY_NAME`, `ENTY_DESC`, `ENTY_DESC_OTH`, `ENTY_STATUS`, `ENTY_DT_CREATE`, `ENTY_UID_CREATE`, `ENTY_DT_LUPD`, `ENTY_UID_LUPD`) VALUES ('ACCN_SUSPENSION', 'Account Suspension', 'Account Suspension', 'Account Suspension', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');
INSERT INTO `T_CK_MST_ENTITY_TYPE` (`ENTY_ID`, `ENTY_NAME`, `ENTY_DESC`, `ENTY_DESC_OTH`, `ENTY_STATUS`, `ENTY_DT_CREATE`, `ENTY_UID_CREATE`, `ENTY_DT_LUPD`, `ENTY_UID_LUPD`) VALUES ('ACCN_TERMINATION', 'Account Termination', 'Account Termination', 'Account Suspension', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');
INSERT INTO `T_CK_MST_ENTITY_TYPE` (`ENTY_ID`, `ENTY_NAME`, `ENTY_DESC`, `ENTY_DESC_OTH`, `ENTY_STATUS`, `ENTY_DT_CREATE`, `ENTY_UID_CREATE`, `ENTY_DT_LUPD`, `ENTY_UID_LUPD`) VALUES ('CONTRACT_REQUEST', 'CONTRACT Update Request', 'CONTRACT Update Request', 'CONTRACT Update Request', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');

INSERT INTO `T_CK_MST_JOB_STATE` (`JBST_ID`, `JBST_NAME`, `JBST_DESC`, `JBST_DESC_OTH`, `JBST_STATUS`, `JBST_DT_CREATE`, `JBST_UID_CREATE`, `JBST_DT_LUPD`, `JBST_UID_LUPD`) VALUES ('SUS', 'SUSPENDED', 'SUSPENDED', 'SUSPENDED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
INSERT INTO `T_CK_MST_JOB_STATE` (`JBST_ID`, `JBST_NAME`, `JBST_DESC`, `JBST_DESC_OTH`, `JBST_STATUS`, `JBST_DT_CREATE`, `JBST_UID_CREATE`, `JBST_DT_LUPD`, `JBST_UID_LUPD`) VALUES ('TERMINATED', 'TERMINATED', 'TERMINATED', 'TERMINATED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

CREATE TABLE `T_CK_MST_WORKFLOW_TYPE` (
  `WKT_ID` varchar(35) NOT NULL COMMENT 'WORKFLOW TYPE ID  - ACCN_REG:ACCN_SUS:ACCN_TERM:SVC_REG_CLT:SVC_REG_CGP:SVC_REG_CDC',  
  `WKT_NAME` varchar(128) DEFAULT NULL COMMENT 'SHORT NAME FOR TYPE OF PROCESS TYPE.',
  `WKT_DESC` varchar(45) DEFAULT NULL COMMENT 'DESCRIPTION OF THIS TYPE OF PROCESS TYPE',
  `WKT_DESC_OTH` varchar(512) DEFAULT NULL,
  `WKT_STATUS` char(1) DEFAULT NULL COMMENT 'STATUS OF THE PROCESS TYPE TYPE',
  `WKT_DT_CREATE` datetime DEFAULT NULL COMMENT 'CREATED DATE',
  `WKT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'CREATED BY UID',
  `WKT_DT_LUPD` datetime DEFAULT NULL COMMENT 'UPDATED DATE',
  `WKT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'UPDATED BY UID',
  PRIMARY KEY (`WKT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT = 'CK WORKFLOW TYPE TABLE';

INSERT INTO `T_CK_MST_WORKFLOW_TYPE` (`WKT_ID`, `WKT_NAME`, `WKT_DESC`, `WKT_DESC_OTH`, `WKT_STATUS`, `WKT_DT_CREATE`, `WKT_UID_CREATE`, `WKT_DT_LUPD`, `WKT_UID_LUPD`) VALUES ('ACCN_REG', 'ACCOUNT REGISTRATION', 'ACCOUNT REGISTRATION', 'ACCOUNT REGISTRATION', 'A', '2023-09-23 07:49:32', 'SYS', '2023-09-23 07:49:32', 'SYS');
INSERT INTO `T_CK_MST_WORKFLOW_TYPE` (`WKT_ID`, `WKT_NAME`, `WKT_DESC`, `WKT_DESC_OTH`, `WKT_STATUS`, `WKT_DT_CREATE`, `WKT_UID_CREATE`, `WKT_DT_LUPD`, `WKT_UID_LUPD`) VALUES ('ACCN_SUS', 'ACCOUNT SUSPENSION', 'ACCOUNT SUSPENSION', 'ACCOUNT SUSPENSION', 'A', '2023-09-23 07:49:32', 'SYS', '2023-09-23 07:49:32', 'SYS');
INSERT INTO `T_CK_MST_WORKFLOW_TYPE` (`WKT_ID`, `WKT_NAME`, `WKT_DESC`, `WKT_DESC_OTH`, `WKT_STATUS`, `WKT_DT_CREATE`, `WKT_UID_CREATE`, `WKT_DT_LUPD`, `WKT_UID_LUPD`) VALUES ('ACCN_TERM', 'ACCOUNT TERMINATION', 'TERMINATION', 'TERMINATION', 'A', '2023-09-23 07:49:32', 'SYS', '2023-09-23 07:49:32', 'SYS');
INSERT INTO `T_CK_MST_WORKFLOW_TYPE` (`WKT_ID`, `WKT_NAME`, `WKT_DESC`, `WKT_DESC_OTH`, `WKT_STATUS`, `WKT_DT_CREATE`, `WKT_UID_CREATE`, `WKT_DT_LUPD`, `WKT_UID_LUPD`) VALUES ('SVC_REG_CLT', 'SERVICE REGISTRATION CLICTRUCK', 'SERVICE REGISTRATION CLICTRUCK', 'SERVICE REGISTRATION CLICTRUCK', 'A', '2023-09-23 07:49:32', 'SYS', '2023-09-23 07:49:32', 'SYS');
INSERT INTO `T_CK_MST_WORKFLOW_TYPE` (`WKT_ID`, `WKT_NAME`, `WKT_DESC`, `WKT_DESC_OTH`, `WKT_STATUS`, `WKT_DT_CREATE`, `WKT_UID_CREATE`, `WKT_DT_LUPD`, `WKT_UID_LUPD`) VALUES ('SVC_REG_CGP', 'SERVICE REGISTRATION GATEPASS', 'SERVICE REGISTRATION GATEPASS', 'SERVICE REGISTRATION GATEPASS', 'A', '2023-09-23 07:49:32', 'SYS', '2023-09-23 07:49:32', 'SYS');
INSERT INTO `T_CK_MST_WORKFLOW_TYPE` (`WKT_ID`, `WKT_NAME`, `WKT_DESC`, `WKT_DESC_OTH`, `WKT_STATUS`, `WKT_DT_CREATE`, `WKT_UID_CREATE`, `WKT_DT_LUPD`, `WKT_UID_LUPD`) VALUES ('SVC_REG_CDC', 'SERVICE REGISTRATION DECLARE', 'SERVICE REGISTRATION DECLARE', 'SERVICE REGISTRATION DECLARE', 'A', '2023-09-23 07:49:32', 'SYS', '2023-09-23 07:49:32', 'SYS');


CREATE TABLE `T_CK_MST_ACCN_ATT_TYPE` (
  `AT_ID` varchar(35) NOT NULL COMMENT 'ATTACHMENT TYPE ID  - NIB:NPWB',
  `AT_WORKFLOW` varchar(35) NOT NULL COMMENT 'WORKFLOW TYPE ID  - REFERENCE T_CK_MST_WORKFLOW_TYPE:WKT_ID',  
  `AT_NAME` varchar(128) DEFAULT NULL COMMENT 'SHORT NAME FOR TYPE OF ATTACHMENT.',
  `AT_DESC` varchar(45) DEFAULT NULL COMMENT 'DESCRIPTION OF THIS TYPE OF ATTACHMENT',
  `AT_DESC_OTH` varchar(512) DEFAULT NULL,
  `AT_MANDATORY` char(1) DEFAULT NULL COMMENT 'MANDATORY STATUS - Y:N',
  `AT_STATUS` char(1) DEFAULT NULL COMMENT 'STATUS OF THE ATTACHMENT TYPE',
  `AT_DT_CREATE` datetime DEFAULT NULL COMMENT 'CREATED DATE',
  `AT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'CREATED BY UID',
  `AT_DT_LUPD` datetime DEFAULT NULL COMMENT 'UPDATED DATE',
  `AT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'UPDATED BY UID',
  PRIMARY KEY (`AT_ID`, `AT_WORKFLOW`),
  CONSTRAINT `FK_CK_MST_ACCN_ATT_TYPE_CK_MST_WORKFLOW_TYPE` FOREIGN KEY (`AT_WORKFLOW`) REFERENCES `T_CK_MST_WORKFLOW_TYPE` (`WKT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT = 'CK ACCOUNT ATTACHMENT TYPE TABLE';

INSERT INTO `T_CK_MST_ACCN_ATT_TYPE` (`AT_ID`, `AT_WORKFLOW`, `AT_NAME`, `AT_DESC`, `AT_DESC_OTH`, `AT_MANDATORY`, `AT_STATUS`, `AT_DT_CREATE`, `AT_UID_CREATE`, `AT_DT_LUPD`, `AT_UID_LUPD`) VALUES ('OTHER', 'ACCN_REG', 'OTHER', 'OTHER', 'OTHER', 'N', 'A', '2023-09-23 07:49:32', 'SYS', '2023-09-23 07:49:32', 'SYS');
INSERT INTO `T_CK_MST_ACCN_ATT_TYPE` (`AT_ID`, `AT_WORKFLOW`, `AT_NAME`, `AT_DESC`, `AT_DESC_OTH`, `AT_MANDATORY`, `AT_STATUS`, `AT_DT_CREATE`, `AT_UID_CREATE`, `AT_DT_LUPD`, `AT_UID_LUPD`) VALUES ('OTHER', 'ACCN_SUS', 'OTHER', 'OTHER', 'OTHER', 'N', 'A', '2023-09-23 07:49:32', 'SYS', '2023-09-23 07:49:32', 'SYS');
INSERT INTO `T_CK_MST_ACCN_ATT_TYPE` (`AT_ID`, `AT_WORKFLOW`, `AT_NAME`, `AT_DESC`, `AT_DESC_OTH`, `AT_MANDATORY`, `AT_STATUS`, `AT_DT_CREATE`, `AT_UID_CREATE`, `AT_DT_LUPD`, `AT_UID_LUPD`) VALUES ('OTHER', 'ACCN_TERM', 'OTHER', 'OTHER', 'OTHER', 'N', 'A', '2023-09-23 07:49:32', 'SYS', '2023-09-23 07:49:32', 'SYS');
INSERT INTO `T_CK_MST_ACCN_ATT_TYPE` (`AT_ID`, `AT_WORKFLOW`, `AT_NAME`, `AT_DESC`, `AT_DESC_OTH`, `AT_MANDATORY`, `AT_STATUS`, `AT_DT_CREATE`, `AT_UID_CREATE`, `AT_DT_LUPD`, `AT_UID_LUPD`) VALUES ('OTHER', 'SVC_REG_CLT', 'OTHER', 'OTHER', 'OTHER', 'N', 'A', '2023-09-23 07:49:32', 'SYS', '2023-09-23 07:49:32', 'SYS');
INSERT INTO `T_CK_MST_ACCN_ATT_TYPE` (`AT_ID`, `AT_WORKFLOW`, `AT_NAME`, `AT_DESC`, `AT_DESC_OTH`, `AT_MANDATORY`, `AT_STATUS`, `AT_DT_CREATE`, `AT_UID_CREATE`, `AT_DT_LUPD`, `AT_UID_LUPD`) VALUES ('OTHER', 'SVC_REG_CGP', 'OTHER', 'OTHER', 'OTHER', 'N', 'A', '2023-09-23 07:49:32', 'SYS', '2023-09-23 07:49:32', 'SYS');
INSERT INTO `T_CK_MST_ACCN_ATT_TYPE` (`AT_ID`, `AT_WORKFLOW`, `AT_NAME`, `AT_DESC`, `AT_DESC_OTH`, `AT_MANDATORY`, `AT_STATUS`, `AT_DT_CREATE`, `AT_UID_CREATE`, `AT_DT_LUPD`, `AT_UID_LUPD`) VALUES ('OTHER', 'SVC_REG_CDC', 'OTHER', 'OTHER', 'OTHER', 'N', 'A', '2023-09-23 07:49:32', 'SYS', '2023-09-23 07:49:32', 'SYS');


CREATE TABLE `T_CK_ACCN_ATT` (
  `AAT_ID` varchar(35) NOT NULL COMMENT 'ACCOUNT ATTACHED ID  - UUID',
  `AAT_ACCN` varchar(35) NOT NULL COMMENT 'ACCOUNT FOR THE ATTACHMENT - REFERENCES T_CORE_ACCN:ACCN_ID',
  `AAT_TYPE_ID` varchar(35) NOT NULL COMMENT 'ATTACHMENT TYPE ID  -  REFERENCE T_CK_MST_ACCN_ATT_TYPE:AT_ID',
  `AAT_TYPE_WORKFLOW` varchar(35) NOT NULL COMMENT 'WORKFLOW TYPE ID  - REFERENCE T_CK_MST_ACCN_ATT_TYPE:AT_WORKFLOW',  
  `AAT_NAME` varchar(256) DEFAULT NULL COMMENT 'SHORT NAME FOR TYPE OF PROCESS TYPE.',
  `AAT_NO` varchar(256) DEFAULT NULL COMMENT 'ATTACHMENT NUMBER',  
  `AT_DT_VALIDILITY` datetime DEFAULT NULL COMMENT 'VALIDILITY DATE OF ATTACHMENT',
  `AAT_LOC` varchar(1024) DEFAULT NULL COMMENT 'RELATIVE PATH NAME TO THE LOCATION OF THE ATTACHMENT',  
  `AT_STATUS` char(1) DEFAULT NULL COMMENT 'STATUS OF THE ATTACHMENT',
  `AT_DT_CREATE` datetime DEFAULT NULL COMMENT 'CREATED DATE',
  `AT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'CREATED BY UID',
  `AT_DT_LUPD` datetime DEFAULT NULL COMMENT 'UPDATED DATE',
  `AT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'UPDATED BY UID',
  PRIMARY KEY (`AAT_ID`),
  CONSTRAINT `FK_CK_ACCN_ATT_CORE_ACCN` FOREIGN KEY (`AAT_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_ACCN_ATT_CK_MST_ACCN_ATT_TYPE` FOREIGN KEY (`AAT_TYPE_ID`, `AAT_TYPE_WORKFLOW`) REFERENCES `T_CK_MST_ACCN_ATT_TYPE` (`AT_ID`,`AT_WORKFLOW`)  
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT = 'CK ACCN WORKFLOW ATTACHMENT TABLE';

CREATE TABLE `T_CK_MST_REMARK_TYPE` (
  `RT_ID` varchar(35) NOT NULL COMMENT 'REMARK TYPE ID  - REG_REQ:REG_APPROVE:REG_REJECT:SUS_REQ:SUS_APPROVE:SUS_REJECT:TERM_REQ:TERM_APPROVE:TERM_REJECT',  
  `RT_NAME` varchar(128) DEFAULT NULL COMMENT 'SHORT NAME FOR REMARK TYPE.',
  `RT_DESC` varchar(45) DEFAULT NULL COMMENT 'DESCRIPTION OF REMARK TYPE',
  `RT_DESC_OTH` varchar(512) DEFAULT NULL,
  `RT_STATUS` char(1) DEFAULT NULL COMMENT 'STATUS OF THE REMARK TYPE',
  `RT_DT_CREATE` datetime DEFAULT NULL COMMENT 'CREATED DATE',
  `RT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'CREATED BY UID',
  `RT_DT_LUPD` datetime DEFAULT NULL COMMENT 'UPDATED DATE',
  `RT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'UPDATED BY UID',
  PRIMARY KEY (`RT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT = 'CK REMARK TYPE TABLE';


INSERT INTO `T_CK_MST_REMARK_TYPE` (`RT_ID`, `RT_NAME`, `RT_DESC`, `RT_DESC_OTH`, `RT_STATUS`, `RT_DT_CREATE`, `RT_UID_CREATE`, `RT_DT_LUPD`, `RT_UID_LUPD`) VALUES ('REG_REQ', 'REGISTRATION REQUEST', 'REGISTRATION REQUEST', 'REGISTRATION REQUEST', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_MST_REMARK_TYPE` (`RT_ID`, `RT_NAME`, `RT_DESC`, `RT_DESC_OTH`, `RT_STATUS`, `RT_DT_CREATE`, `RT_UID_CREATE`, `RT_DT_LUPD`, `RT_UID_LUPD`) VALUES ('REG_APPROVE', 'REGISTRATION APPROVED', 'APPROVED', 'APPROVED', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_MST_REMARK_TYPE` (`RT_ID`, `RT_NAME`, `RT_DESC`, `RT_DESC_OTH`, `RT_STATUS`, `RT_DT_CREATE`, `RT_UID_CREATE`, `RT_DT_LUPD`, `RT_UID_LUPD`) VALUES ('REG_REJECT', 'REGISTRATION REJECTED', 'REGISTRATION REJECTED', 'REGISTRATION REJECTED', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_MST_REMARK_TYPE` (`RT_ID`, `RT_NAME`, `RT_DESC`, `RT_DESC_OTH`, `RT_STATUS`, `RT_DT_CREATE`, `RT_UID_CREATE`, `RT_DT_LUPD`, `RT_UID_LUPD`) VALUES ('SUS_REQ', 'SUSPENSION REQUEST', 'SUSPENSION REQUEST', 'SUSPENSION REQUEST', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_MST_REMARK_TYPE` (`RT_ID`, `RT_NAME`, `RT_DESC`, `RT_DESC_OTH`, `RT_STATUS`, `RT_DT_CREATE`, `RT_UID_CREATE`, `RT_DT_LUPD`, `RT_UID_LUPD`) VALUES ('SUS_APPROVE', 'SUSPENSION APPROVED', 'SUSPENSION APPROVED', 'SUSPENSION APPROVED', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_MST_REMARK_TYPE` (`RT_ID`, `RT_NAME`, `RT_DESC`, `RT_DESC_OTH`, `RT_STATUS`, `RT_DT_CREATE`, `RT_UID_CREATE`, `RT_DT_LUPD`, `RT_UID_LUPD`) VALUES ('SUS_REJECT', 'SUSPENSION REJECTED', 'SUSPENSION REJECTED', 'SUSPENSION REJECTED', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_MST_REMARK_TYPE` (`RT_ID`, `RT_NAME`, `RT_DESC`, `RT_DESC_OTH`, `RT_STATUS`, `RT_DT_CREATE`, `RT_UID_CREATE`, `RT_DT_LUPD`, `RT_UID_LUPD`) VALUES ('TERM_REQ', 'TERMINATION REQUEST', 'TERMINATION REQUEST', 'TERMINATION REQUEST', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_MST_REMARK_TYPE` (`RT_ID`, `RT_NAME`, `RT_DESC`, `RT_DESC_OTH`, `RT_STATUS`, `RT_DT_CREATE`, `RT_UID_CREATE`, `RT_DT_LUPD`, `RT_UID_LUPD`) VALUES ('TERM_APPROVE', 'TERMINATION APPROVED', 'TERMINATION APPROVED', 'TERMINATION APPROVED', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_MST_REMARK_TYPE` (`RT_ID`, `RT_NAME`, `RT_DESC`, `RT_DESC_OTH`, `RT_STATUS`, `RT_DT_CREATE`, `RT_UID_CREATE`, `RT_DT_LUPD`, `RT_UID_LUPD`) VALUES ('TERM_REJECT', 'TERMINATION REJECTED', 'TERMINATION REJECTED', 'TERMINATION APPROVED', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');



CREATE TABLE `T_CK_WORKFLOW_REMARK` (
  `AR_ID` varchar(35) NOT NULL COMMENT 'REMARK ID  - UUID',
  `AR_TYPE` varchar(35) NOT NULL COMMENT 'REMARK TYPE  - REFERENCES T_CK_MST_REMARK_TYPE:RT_ID',  
  `AR_WORKFLOW` varchar(35) NOT NULL COMMENT 'WORKFLOW TYPE  - REFERENCES T_CK_MST_WORKFLOW_TYPE:WKT_ID',  
  `AR_ACCN` varchar(35) NOT NULL COMMENT 'ACCOUNT FOR THE ATTACHMENT - REFERENCES T_CORE_ACCN:ACCN_ID',
  `AR_REMARK` mediumtext NOT NULL COMMENT 'REMARKS',  
  `AT_STATUS` char(1) DEFAULT NULL COMMENT 'STATUS OF THE ATTACHMENT',
  `AT_DT_CREATE` datetime DEFAULT NULL COMMENT 'CREATED DATE',
  `AT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'CREATED BY UID',
  `AT_DT_LUPD` datetime DEFAULT NULL COMMENT 'UPDATED DATE',
  `AT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'UPDATED BY UID',
  PRIMARY KEY (`AR_ID`),
  CONSTRAINT `FK_CK_ACCN_REMARK_CK_MST_REMARK_TYPE` FOREIGN KEY (`AR_TYPE`) REFERENCES `T_CK_MST_REMARK_TYPE` (`RT_ID`),  
  CONSTRAINT `FK_CK_ACCN_REMARK_CK_MST_WORKFLOW_TYPE` FOREIGN KEY (`AR_WORKFLOW`) REFERENCES `T_CK_MST_WORKFLOW_TYPE` (`WKT_ID`),
  CONSTRAINT `FK_CK_ACCN_REMARK_CORE_ACCN` FOREIGN KEY (`AR_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT = 'CK REMARK TABLE';


CREATE TABLE `T_CK_CT_MST_CONTRACT_REQ_STATE` (
  `ST_ID` varchar(35) NOT NULL COMMENT 'STATE ID  - NEW_REQ:NEW_UPDATE:NEW_SUBMITTED:UPDATE_SUBMITTED:NEW_APPROVED:UPDATE_APPROVED:NEW_REJECTED:UPDATE_REJECTED:DELETED',  
  `ST_NAME` varchar(128) DEFAULT NULL COMMENT 'SHORT NAME FOR CONTRACT REQUEST STATE',
  `ST_DESC` varchar(45) DEFAULT NULL COMMENT 'DESCRIPTION OF CONTRACT REQUEST STATE',
  `ST_DESC_OTH` varchar(512) DEFAULT NULL,
  `ST_STATUS` char(1) DEFAULT NULL COMMENT 'STATUS OF THE CONTRACT REQUEST STATE',
  `ST_DT_CREATE` datetime DEFAULT NULL COMMENT 'CREATED DATE',
  `ST_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'CREATED BY UID',
  `ST_DT_LUPD` datetime DEFAULT NULL COMMENT 'UPDATED DATE',
  `ST_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'UPDATED BY UID',
  PRIMARY KEY (`ST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT = 'CONTACT REQUEST STATE TABLE';


INSERT INTO `T_CK_CT_MST_CONTRACT_REQ_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_DESC_OTH`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`, `ST_DT_LUPD`, `ST_UID_LUPD`) VALUES ('NEW_REQ', 'NEW REQUEST', 'NEW REQUEST', 'NEW REQUEST', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_CT_MST_CONTRACT_REQ_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_DESC_OTH`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`, `ST_DT_LUPD`, `ST_UID_LUPD`) VALUES ('NEW_UPDATE', 'NEW UPDATE', 'NEW UPDATE', 'NEW UPDATE', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_CT_MST_CONTRACT_REQ_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_DESC_OTH`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`, `ST_DT_LUPD`, `ST_UID_LUPD`) VALUES ('NEW_SUBMITTED', 'NEW SUBMIT', 'NEW SUBMIT', 'NEW SUBMIT', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_CT_MST_CONTRACT_REQ_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_DESC_OTH`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`, `ST_DT_LUPD`, `ST_UID_LUPD`) VALUES ('UPDATE_SUBMITTED', 'UPDATE SUBMITTED', 'UPDATE SUBMITTED', 'UPDATE SUBMITTED', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_CT_MST_CONTRACT_REQ_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_DESC_OTH`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`, `ST_DT_LUPD`, `ST_UID_LUPD`) VALUES ('NEW_APPROVED', 'NEW APPROVED', 'NEW APPROVED', 'NEW APPROVED', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_CT_MST_CONTRACT_REQ_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_DESC_OTH`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`, `ST_DT_LUPD`, `ST_UID_LUPD`) VALUES ('UPDATE_APPROVED', 'UPDATE APPROVED', 'UPDATE APPROVED', 'UPDATE APPROVED', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_CT_MST_CONTRACT_REQ_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_DESC_OTH`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`, `ST_DT_LUPD`, `ST_UID_LUPD`) VALUES ('NEW_REJECTED', 'NEW REJECTED', 'NEW REJECTED', 'NEW REJECTED', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_CT_MST_CONTRACT_REQ_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_DESC_OTH`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`, `ST_DT_LUPD`, `ST_UID_LUPD`) VALUES ('UPDATE_REJECTED', 'UPDATE REJECTED', 'UPDATE REJECTED', 'UPDATE REJECTED', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_CT_MST_CONTRACT_REQ_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_DESC_OTH`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`, `ST_DT_LUPD`, `ST_UID_LUPD`) VALUES ('DELETED', 'DELETED', 'DELETED', 'DELETED', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_CT_MST_CONTRACT_REQ_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_DESC_OTH`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`, `ST_DT_LUPD`, `ST_UID_LUPD`) VALUES ('EXPIRED', 'EXPIRED', 'EXPIRED', 'EXPIRED', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_CT_MST_CONTRACT_REQ_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_DESC_OTH`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`, `ST_DT_LUPD`, `ST_UID_LUPD`) VALUES ('RENEWAL_REQ', 'NEW RENEWAL', 'NEW RENEWAL', 'NEW RENEWAL', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_CT_MST_CONTRACT_REQ_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_DESC_OTH`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`, `ST_DT_LUPD`, `ST_UID_LUPD`) VALUES ('RENEWAL_APPROVED', 'RENEWAL APPROVED', 'RENEWAL APPROVED', 'RENEWAL APPROVED', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_CT_MST_CONTRACT_REQ_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_DESC_OTH`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`, `ST_DT_LUPD`, `ST_UID_LUPD`) VALUES ('RENEWAL_REJECTED', 'RENEWAL REJECTED', 'RENEWAL REJECTED', 'RENEWAL REJECTED', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_CT_MST_CONTRACT_REQ_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_DESC_OTH`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`, `ST_DT_LUPD`, `ST_UID_LUPD`) VALUES ('RENEWAL_SUBMITTED', 'RENEWAL SUBMITTED', 'RENEWAL SUBMITTED', 'RENEWAL SUBMITTED', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');
INSERT INTO `T_CK_CT_MST_CONTRACT_REQ_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_DESC_OTH`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`, `ST_DT_LUPD`, `ST_UID_LUPD`) VALUES ('EXPORTED', 'EXPORTED', 'EXPORTED', 'EXPORTED', 'A', '2023-09-23 07:56:04', 'SYS', '2023-09-23 07:56:04', 'SYS');


CREATE TABLE `T_CK_CT_CONTRACT_REQ` (
  `CR_ID` varchar(35) NOT NULL COMMENT 'CONTRACT REQUEST ID - UUID',
  `CR_STATE` varchar(35) NOT NULL COMMENT 'CONTRACT REQUEST STATE - REFERENCE T_CK_CT_MST_CONTRACT_REQ_STATE:ST_ID',
  `CR_NAME` varchar(1024) DEFAULT NULL COMMENT 'RATE TABLE NAME',
  `CR_DESCRIPTION` mediumtext COMMENT 'RATE TABLE NAME',
  `CR_CCY` varchar(3) DEFAULT NULL COMMENT 'CONTRACT CURRENCY - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `CR_DT_START` datetime DEFAULT NULL COMMENT 'CONTRACT VALIDITY START',
  `CR_DT_END` datetime DEFAULT NULL COMMENT 'CONTRACT VALIDITY END',
  `CR_TO` varchar(35) DEFAULT NULL COMMENT 'CONTRACT TRUCK OPERATOR - REFERENCES T_CORE_ACCN:ACCN_ID',
  `CR_CHARGE_TO` varchar(35) DEFAULT NULL COMMENT 'CONTRACT TRUCK OPERATOR CHARGE - REFERENCES T_CK_CT_CONTRACT_REQ_CHARGE:CONC_ID',
  `CR_PAYTERM_TO` int DEFAULT NULL,
  `CR_CO_FF` varchar(35) DEFAULT NULL COMMENT 'CONTRACT CARGO OWNER - REFERENCES T_CORE_ACCN:ACCN_ID',
  `CR_CHARGE_CO_FF` varchar(35) DEFAULT NULL COMMENT 'CONTRACT CARGO OWNER CHARGE - REFERENCES T_CK_CT_CONTRACT_REQ_CHARGE:CONC_ID',
  `CR_PAYTERM_CO_FF` int DEFAULT NULL,
  `CR_UID_REQUESTOR` varchar(35) DEFAULT NULL COMMENT 'UID REQUESTOR',
  `CR_COMMENT_REQUESTOR` mediumtext DEFAULT NULL COMMENT 'REQUESTOR COMMENT',
  `CR_DT_SUBMIT` datetime DEFAULT NULL COMMENT 'DATE OF SUMBISSION',
  `CR_UID_APPROVER` varchar(35) DEFAULT NULL COMMENT 'UID APPROVER',
  `CR_COMMENT_APPROVER` mediumtext DEFAULT NULL COMMENT 'APPROVER COMMENT',
  `CR_DT_APPROVE_REJECT` datetime DEFAULT NULL COMMENT 'DATE OF APPROVAL OR REJECTION',
  `CR_COMMENT` mediumtext DEFAULT NULL COMMENT 'COMMENT FOR THE REJECTION',
  `CR_STATUS` char(1) DEFAULT NULL COMMENT 'CONTRACT STATE STATUS',
  `CR_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CR_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CR_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CR_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CR_ID`),
  CONSTRAINT `FK_CK_CT_CONTRACT_REQ_CK_CT_MST_CONTRACT_REQ_STATE` FOREIGN KEY (`CR_STATE`) REFERENCES `T_CK_CT_MST_CONTRACT_REQ_STATE` (`ST_ID`),  
  CONSTRAINT `FK_CK_CT_CONTRACT_REQ_CK_CT_CONTRACT_REQ_CHARGE1` FOREIGN KEY (`CR_CHARGE_TO`) REFERENCES `T_CK_CT_CONTRACT_CHARGE` (`CONC_ID`),
  CONSTRAINT `FK_CK_CT_CONTRACT_REQ_CK_CT_CONTRACT_REQ_CHARGE2` FOREIGN KEY (`CR_CHARGE_CO_FF`) REFERENCES `T_CK_CT_CONTRACT_CHARGE` (`CONC_ID`),
  CONSTRAINT `FK_CK_CT_CONTRACT_REQ_CORE_ACCN1` FOREIGN KEY (`CR_TO`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_CT_CONTRACT_REQ_CORE_ACCN2` FOREIGN KEY (`CR_CO_FF`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_CT_CONTRACT_REQ_MST_CURRENCY` FOREIGN KEY (`CR_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='CONTRACT REQUEST TABLE';


-- execute roles.sql

-- execute formcontrol.sql

-- execute workflow.sql

-- execute navigation.sql

-- NOTE TO UPDATE THE GLI USER ROLES BASED ON THE NEW ROLES REFER TO TABLES_SETUP.XLS WHEN DEPLOY IN DEMO -> PRODUCTION

INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_TO_PAYMENT_TERMS', '5,7', 'NO. OF DAYS FOR TRUCKING OPERATOR PAYMENT TERMS', '2022-11-30 00:00:00', 'SYS', '2022-11-30 00:00:00', 'SYS', 'A');
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_COFF_PAYMENT_TERMS', '30,45,60,90', 'NO. OF DAYS FOR CO/FF PAYMENT TERMS', '2022-11-30 00:00:00', 'SYS', '2022-11-30 00:00:00', 'SYS', 'A');


ALTER TABLE `T_CK_CT_JOB_TERM_REQ` ADD COLUMN `JTR_STATE` CHAR(3) NOT NULL AFTER `JTR_ACCN`;

INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_CTC_VALID_MONTHS_INTERVAL', '6', 'NO. OF MONTHS INTERVAL FOR START DATE AND END DATE', '2022-11-30 00:00:00', 'SYS', '2022-11-30 00:00:00', 'SYS', 'A');

 
INSERT INTO `clickargo2`.`T_CK_CT_MST_DEBIT_NOTE_STATE` (`DNST_ID`, `DNST_NAME`, `DNST_DESC`, `DNST_DESC_OTH`, `DNST_STATUS`, `DNST_DT_CREATE`, `DNST_UID_CREATE`, `DNST_DT_LUPD`, `DNST_UID_LUPD`) 
VALUES ('TERMINATED', 'TERMINATED', 'TERMINATED', 'TERMINATED', 'A', sysdate(), 'SYS', sysdate(), 'SYS');

INSERT INTO `clickargo2`.`T_CK_CT_MST_TO_INVOICE_STATE` (`INST_ID`, `INST_NAME`, `INST_DESC`, `INST_DESC_OTH`, `INST_STATUS`, `INST_DT_CREATE`, `INST_UID_CREATE`, `INST_DT_LUPD`, `INST_UID_LUPD`) 
VALUES ('TERMINATED', 'TERMINATED', 'TERMINATED', 'TERMINATED', 'A', sysdate(), 'SYS', sysdate(), 'SYS');

ALTER TABLE `clickargo2`.`T_CK_CT_PAYMENT` 
CHANGE COLUMN `CTP_STATE` `CTP_STATE` VARCHAR(35) NULL DEFAULT NULL ;

/** Note: Get the max accnId value then replace in t_ck_sequence_no*/
INSERT INTO `T_CK_SEQUENCE_NO` (`SQN_ID`, `SQN_DESC`, `SQN_KEY`, `SQN_SEQ`, `SQN_DT_CREATE`, `SQN_UID_CREATE`) VALUES ('CT_ACCN_CODE', 'ACCOUNT CODE FORMAT', 'CK%04d', '4', '2023-06-03 03:47:51', 'SYS');

-- Work Flow Credit Limit Update
-- INSERT INTO clickargo2.T_CK_SVC_WORKFLOW (WKFL_ID, WKFL_APPS_CODE, WKFL_ACCN_TYPE, WKFL_ROLE, WKFL_SCV_TYPE, WKFL_ACTION, WKFL_FROM_STATE, WKFL_TO_STATE, WKFL_URI, WKFL_STATUS, WKFL_DT_CREATE, WKFL_UID_CREATE, WKFL_DT_LUPD, WKFL_UID_LUPD) VALUES('CRU_1', 'CKT', 'ACC_TYPE_SP', 'SP_L1', 'CLICTRUCK', 'SUBMIT', 'NEW', 'SUB', '', 'A', '2023-10-04 11:38:45', 'SYS', '2023-10-04 11:38:45', 'SYS');
-- INSERT INTO clickargo2.T_CK_SVC_WORKFLOW (WKFL_ID, WKFL_APPS_CODE, WKFL_ACCN_TYPE, WKFL_ROLE, WKFL_SCV_TYPE, WKFL_ACTION, WKFL_FROM_STATE, WKFL_TO_STATE, WKFL_URI, WKFL_STATUS, WKFL_DT_CREATE, WKFL_UID_CREATE, WKFL_DT_LUPD, WKFL_UID_LUPD) VALUES('CRU_2', 'CKT', 'ACC_TYPE_SP', 'SP_FIN_HD', 'CLICTRUCK', 'APPROVE', 'SUB', 'APP', '', 'A', '2023-10-04 11:38:45', 'SYS', '2023-10-04 11:38:45', 'SYS');
-- INSERT INTO clickargo2.T_CK_SVC_WORKFLOW (WKFL_ID, WKFL_APPS_CODE, WKFL_ACCN_TYPE, WKFL_ROLE, WKFL_SCV_TYPE, WKFL_ACTION, WKFL_FROM_STATE, WKFL_TO_STATE, WKFL_URI, WKFL_STATUS, WKFL_DT_CREATE, WKFL_UID_CREATE, WKFL_DT_LUPD, WKFL_UID_LUPD) VALUES('CRU_3', 'CKT', 'ACC_TYPE_SP', 'SP_FIN_HD', 'CLICTRUCK', 'REJECT', 'SUB', 'REJ', '', 'A', '2023-10-04 11:38:45', 'SYS', '2023-10-04 11:38:45', 'SYS');
-- INSERT INTO clickargo2.T_CK_SVC_WORKFLOW (WKFL_ID, WKFL_APPS_CODE, WKFL_ACCN_TYPE, WKFL_ROLE, WKFL_SCV_TYPE, WKFL_ACTION, WKFL_FROM_STATE, WKFL_TO_STATE, WKFL_URI, WKFL_STATUS, WKFL_DT_CREATE, WKFL_UID_CREATE, WKFL_DT_LUPD, WKFL_UID_LUPD) VALUES('CRU_4', 'CKT', 'ACC_TYPE_SP', 'SP_FIN_HD', 'CLICTRUCK', 'DELETE', 'APP', 'DEL', '', 'A', '2023-10-04 11:38:45', 'SYS', '2023-10-04 11:38:45', 'SYS');
-- INSERT INTO clickargo2.T_CK_SVC_WORKFLOW (WKFL_ID, WKFL_APPS_CODE, WKFL_ACCN_TYPE, WKFL_ROLE, WKFL_SCV_TYPE, WKFL_ACTION, WKFL_FROM_STATE, WKFL_TO_STATE, WKFL_URI, WKFL_STATUS, WKFL_DT_CREATE, WKFL_UID_CREATE, WKFL_DT_LUPD, WKFL_UID_LUPD) VALUES('CRU_5', 'CKT', 'ACC_TYPE_SP', 'SP_L1', 'CLICTRUCK', 'DELETE', 'NEW', 'DEL', '', 'A', '2023-10-04 11:38:45', 'SYS', '2023-10-04 11:38:45', 'SYS');

ALTER TABLE clickargo2.T_CK_CREDIT_UPDATE ADD COLUMN CRU_DT_SUBMITTED DATETIME;
ALTER TABLE clickargo2.T_CK_CREDIT_UPDATE ADD COLUMN CRU_UID_SUBMITTED VARCHAR(35);
ALTER TABLE clickargo2.T_CK_CREDIT_UPDATE ADD COLUMN CRU_REQUESTER VARCHAR(35);




CREATE TABLE `T_CK_CT_TRACK_LOC` (
  TL_ID varchar(35) NOT NULL COMMENT 'TRACK LOCATION ID - UUID',
  TL_JOB_ID varchar(35) NOT NULL COMMENT 'JOB_ID - REFERENCE T_CK_JOB_TRUCK:JOB_ID',
  TL_IMEI varchar(128) DEFAULT NULL COMMENT 'IMEI',
  TL_DT_START datetime DEFAULT NULL COMMENT 'CALL ASCENT API URL: REQUEST START TIME PARAMETER',
  TL_DT_END datetime DEFAULT NULL COMMENT 'CALL ASCENT API URL: REQUEST END TIME PARAMETER',
  TL_REQ_URL varchar(1024) DEFAULT '' COMMENT 'CALL ASCENT API REQUEST URL',
  TL_RSP_BODY mediumtext DEFAULT NULL COMMENT 'CALL ASCENT API RESPONSE BODY',
  TL_REMARK varchar(1024) DEFAULT '' COMMENT 'REMARK',
  TL_STATUS char(1) DEFAULT NULL COMMENT 'CONTRACT STATE STATUS',
  TL_DT_CREATE datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  TL_UID_CREATE varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  TL_DT_LUPD datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  TL_UID_LUPD varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`TL_ID`),
  CONSTRAINT `FK_T_CK_CT_TRACK_LOC_JOB_TRUCK` FOREIGN KEY (`TL_JOB_ID`) REFERENCES `T_CK_JOB_TRUCK` (`JOB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='TRACK AND TRACE LOCATION TABLE';


CREATE TABLE `T_CK_CT_TRACK_LOC_ITEM` (
  TLI_ID varchar(35) NOT NULL COMMENT 'TRACK LOCATION ITEM ID - UUID',
  TLI_TRACK_LOC_ID varchar(35) NOT NULL COMMENT 'TRACK_LOC_ID - REFERENCE T_CK_CT_TRACK_LOC:TL_ID',
  TLI_LOC_ID varchar(35) DEFAULT NULL COMMENT 'LOC_ID - REFERENCE T_CK_CT_LOCATION:LOC_ID',
  TLI_GPS varchar(128) NOT NULL COMMENT 'FROM ASCENT API RESPONSE BODY',
  TLI_RADIUS int NOT NULL COMMENT 'RADIUS:10,30,100',
  TLI_DT_ENTER datetime DEFAULT NULL COMMENT 'ENTER TIME',
  TLI_DT_EXIT datetime DEFAULT NULL COMMENT 'EXIT TIME',
  TLI_STATUS char(1) DEFAULT NULL COMMENT 'CONTRACT STATE STATUS',
  TLI_DT_CREATE datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  TLI_UID_CREATE varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  TLI_DT_LUPD datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  TLI_UID_LUPD varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`TLI_ID`),
  CONSTRAINT `FK_T_CK_CT_TRACK_LOC_ITEM_TRACK_LOC_ID` FOREIGN KEY (`TLI_TRACK_LOC_ID`) REFERENCES `T_CK_CT_TRACK_LOC` (`TL_ID`),
  CONSTRAINT `FK_T_CK_CT_TRACK_LOC_ITEM_TL_ID` FOREIGN KEY (`TLI_LOC_ID`) REFERENCES `T_CK_CT_LOCATION` (`LOC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='TRACK AND TRACE LOCATION ITEM TABLE';


-- execute navigation.sql , formcontrol.sql, workflow.sql


ALTER TABLE `clickargo2`.`T_CK_CT_DEBIT_NOTE` 
CHANGE COLUMN `DN_PAYMENT_REF` `DN_PAYMENT_REF` VARCHAR(255) NULL DEFAULT NULL COMMENT 'DEBIT NOTE PAYMENT REFERENCE' ;

INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) 
VALUES ('CLICTRUCK_TRACK_TIME_URL', 'https://ext.logistics.myascents.net/api/3rdparty/unit/enterexit?key=$2a$11$oo7.I606K/DVjUdZi88UzeFu.tLQiwTChnty4KATKbf3Dq0T8s2Ii', 'Enter Exit Time of Location', sysdate(), 'SYS', sysdate(), 'SYS', 'A');


-- update GLI t_core_usr_role one by one-- 
select * from T_CORE_USR_ROLE WHERE UROL_UID LIKE 'GLI%' AND UROL_APPSCODE='CKT' AND UROL_ROLEID LIKE 'FINANCE%';

-- end of line, please do not add more scripts below --