/** For 2.1.0 SG CHANGES script */

DROP TABLE IF EXISTS T_CK_UNGRANT_USER_EX;
CREATE TABLE `T_CK_UNGRANT_USER_EX` (
  `GRNTUE_USR_ID` varchar(35) NOT NULL,
  `GRNTUE_APPS_CODE` varchar(35)  NOT NULL COMMENT 'Reference to T_CORE_APPS',
  `GRNTUE_ROLE_ID` varchar(35) NOT NULL COMMENT 'References T_CORE_ROLE',
  `GRNTUE_PERM_EX_ID` varchar(35) NOT NULL,
  `GRNTUE_STATUS` char(1) NOT NULL COMMENT 'A is active,I is inactive,Default is A',
  `GRNTUE_DT_CREATE` datetime NOT NULL,
  `GRNTUE_UID_CREATE` varchar(35) NOT NULL,
  `GRNTUE_DT_LUPD` datetime DEFAULT NULL,
  `GRNTUE_UID_LUPD` varchar(35) DEFAULT NULL,
  PRIMARY KEY (`GRNTUE_USR_ID`,`GRNTUE_APPS_CODE`,`GRNTUE_PERM_EX_ID`,`GRNTUE_ROLE_ID`),
  KEY `FKY__T_CORE_PERM_EX_GRNTU_PERM_ID_idx` (`GRNTUE_PERM_EX_ID`),
  KEY `FKY__T_CORE_APPS_GRNTUE_APPS_CODE_idx` (`GRNTUE_APPS_CODE`),
  KEY `FKY__T_CORE_ROLE_GRNTUE_ROLE_ID_idx` (`GRNTUE_ROLE_ID`),
  CONSTRAINT `FKY__T_CORE_PERM_EX_GRNTUE_PERM_ID` FOREIGN KEY (`GRNTUE_PERM_EX_ID`) REFERENCES `T_CORE_PERM_EX` (`PERM_ID`),
  CONSTRAINT `FKY__T_CORE_USER_GRNTUE_USR_ID` FOREIGN KEY (`GRNTUE_USR_ID`) REFERENCES `T_CORE_USR` (`USR_UID`),
  CONSTRAINT `FKY__T_CORE_APPS_GRNTUE_APPS_CODE` FOREIGN KEY (`GRNTUE_APPS_CODE`) REFERENCES `T_CORE_APPS` (`APPS_CODE`),
  CONSTRAINT `FK_T_GRNTRLE_ROLE_GRNTUE_ROLE_ID` FOREIGN KEY (`GRNTUE_APPS_CODE`, `GRNTUE_ROLE_ID`) REFERENCES `T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;


DROP TABLE IF EXISTS T_CK_UNGRANT_ACCOUNT_EX;
CREATE TABLE `T_CK_UNGRANT_ACCOUNT_EX` (
  `GRNTA_ACCN_ID` varchar(35) NOT NULL,
  `GRNTA_APPS_CODE` varchar(35) NOT NULL COMMENT 'Reference to T_CORE_APPS',
  `GRNTA_ROLE_ID` varchar(35) NOT NULL COMMENT 'References T_CORE_ROLE',
  `GRNTA_PERM_EX_ID` varchar(35) NOT NULL COMMENT 'Reference to T_CORE_PERM_EX',
  `GRNTA_STATUS` char(1) NOT NULL COMMENT 'A is active,I is inactive,Default is A',
  `GRNTA_DT_CREATE` datetime NOT NULL,
  `GRNTA_UID_CREATE` varchar(35) NOT NULL,
  `GRNTA_DT_LUPD` datetime DEFAULT NULL,
  `GRNTA_UID_LUPD` varchar(35) DEFAULT NULL,
  PRIMARY KEY (`GRNTA_ACCN_ID`,`GRNTA_APPS_CODE`,`GRNTA_PERM_EX_ID`,`GRNTA_ROLE_ID`),
  KEY `FKY__T_CORE_PERM_EX_GRNTA_PERM_ID_idx` (`GRNTA_PERM_EX_ID`),
  KEY `FKY__T_CORE_APPS_GRNTA_APPS_CODE_idx` (`GRNTA_APPS_CODE`),
  KEY `FKY__T_CORE_ROLE_GRNTA_ROLE_ID_idx` (`GRNTA_ROLE_ID`),
  KEY `FK_T_GRNTRLE_ROLE_GRNTA_ROLE_ID` (`GRNTA_APPS_CODE`,`GRNTA_ROLE_ID`),
  CONSTRAINT `FK_T_GRNTRLE_ROLE_GRNTA_ROLE_ID` FOREIGN KEY (`GRNTA_APPS_CODE`, `GRNTA_ROLE_ID`) REFERENCES `T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`),
  CONSTRAINT `FKY__T_CORE_ACCN_GRNTU_ACCN_ID` FOREIGN KEY (`GRNTA_ACCN_ID`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FKY__T_CORE_APPS_GRNTA_APPS_CODE` FOREIGN KEY (`GRNTA_APPS_CODE`) REFERENCES `T_CORE_APPS` (`APPS_CODE`),
  CONSTRAINT `FKY__T_CORE_PERM_EX_GRNTU_PERM_ID` FOREIGN KEY (`GRNTA_PERM_EX_ID`) REFERENCES `T_CORE_PERM_EX` (`PERM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;



DROP TABLE IF EXISTS T_CK_ACCN_CONFIG_EXT;
CREATE TABLE `T_CK_ACCN_CONFIG_EXT` (
  `CAE_ACCN_ID` varchar(35) NOT NULL COMMENT 'REFERENCE TO T_CORE_ACCN:ACCN_ID',
  `CAE_APPS_CODE` varchar(35) NOT NULL COMMENT 'Reference to T_CORE_APPS',
  `CAE_ROLE_ID` varchar(35) NOT NULL COMMENT 'References T_CORE_ROLE',
  `CAE_TYPE` varchar(35) NOT NULL COMMENT 'VALUES CAN BE TABS | DASHBOARD',
  `CAE_VALUE` MEDIUMTEXT DEFAULT NULL COMMENT 'VALUES CAN BE IN JSON OR OTHERS DEPENDING ON THE FE NEEDS',
  `CAE_STATUS` char(1) DEFAULT NULL,
  `CAE_DT_CREATE` datetime DEFAULT NULL,
  `CAE_UID_CREATE` varchar(35) DEFAULT NULL,
  `CAE_DT_LUPD` datetime DEFAULT NULL,
  `CAE_UID_LUPD` varchar(35) DEFAULT NULL,
  PRIMARY KEY (`CAE_ACCN_ID`,`CAE_TYPE`,`CAE_ROLE_ID`,`CAE_APPS_CODE`),
  CONSTRAINT `FK_T_CK_ACCN_CONFIG_EXT_ACCN_ID` FOREIGN KEY (`CAE_ACCN_ID`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_T_CK_ACCN_CONFIG_EXT_CAE_ROLE_ID` FOREIGN KEY (`CAE_APPS_CODE`, `CAE_ROLE_ID`) REFERENCES `T_CORE_ROLE` (`ROLE_APPSCODE`, `ROLE_ID`),
  CONSTRAINT `FK_T_CK_ACCN_CONFIG_EXT_CAE_APPS_CODE` FOREIGN KEY (`CAE_APPS_CODE`) REFERENCES `T_CORE_APPS` (`APPS_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;




-- SAMPLE DATA
SET SQL_SAFE_UPDATES = 0;
DELETE FROM `T_CK_UNGRANT_ACCOUNT_EX`;
SET SQL_SAFE_UPDATES = 1;
INSERT INTO T_CK_UNGRANT_ACCOUNT_EX (GRNTA_APPS_CODE, GRNTA_ACCN_ID, GRNTA_ROLE_ID,GRNTA_PERM_EX_ID, GRNTA_STATUS, GRNTA_DT_CREATE, GRNTA_UID_CREATE) VALUES ('CKT', 'BERAM', 'FF_FINANCE','PM033', 'A', NOW(), 'SYS');
INSERT INTO T_CK_UNGRANT_ACCOUNT_EX (GRNTA_APPS_CODE, GRNTA_ACCN_ID, GRNTA_ROLE_ID,GRNTA_PERM_EX_ID, GRNTA_STATUS, GRNTA_DT_CREATE, GRNTA_UID_CREATE) VALUES ('CKT', 'ALKNAR', 'FF_FINANCE','PM033', 'A', NOW(), 'SYS');
INSERT INTO T_CK_UNGRANT_ACCOUNT_EX (GRNTA_APPS_CODE, GRNTA_ACCN_ID, GRNTA_ROLE_ID,GRNTA_PERM_EX_ID, GRNTA_STATUS, GRNTA_DT_CREATE, GRNTA_UID_CREATE) VALUES ('CKT', 'BERAM', 'OP_ADMIN','PM033', 'A', NOW(), 'SYS');

SET SQL_SAFE_UPDATES = 0;
DELETE FROM `T_CK_UNGRANT_USER_EX`;
SET SQL_SAFE_UPDATES = 1;
INSERT INTO T_CK_UNGRANT_USER_EX (GRNTUE_APPS_CODE, GRNTUE_USR_ID, GRNTUE_ROLE_ID,GRNTUE_PERM_EX_ID, GRNTUE_STATUS, GRNTUE_DT_CREATE, GRNTUE_UID_CREATE) VALUES ('CKT', 'ALKNAR_U001', 'FF_FINANCE','PM069', 'A', NOW(), 'SYS');

SET SQL_SAFE_UPDATES = 0;
DELETE FROM `T_CK_ACCN_CONFIG_EXT`;
SET SQL_SAFE_UPDATES = 1;
INSERT INTO T_CK_ACCN_CONFIG_EXT(CAE_ACCN_ID,CAE_APPS_CODE,CAE_ROLE_ID,CAE_TYPE,CAE_VALUE,CAE_STATUS,CAE_DT_CREATE,CAE_UID_CREATE) VALUES('IODSF','CKT','OFFICER','DASHBOARD','[{"id":0,"dbType":"TRUCK_JOBS","transStatistic":{"NEW":0,"ONGOING":0},"accnType":"ACC_TYPE_TO"}]','A',NOW(),'SYS');
INSERT INTO T_CK_ACCN_CONFIG_EXT(CAE_ACCN_ID,CAE_APPS_CODE,CAE_ROLE_ID,CAE_TYPE,CAE_VALUE,CAE_STATUS,CAE_DT_CREATE,CAE_UID_CREATE) VALUES('DSV','CKT','OFFICER','DASHBOARD','[{"id":0,"dbType":"TRUCK_JOBS","transStatistic":{"NEW":0,"ONGOING":0},"accnType":"ACC_TYPE_TO"}]','A',NOW(),'SYS');
INSERT INTO T_CK_ACCN_CONFIG_EXT(CAE_ACCN_ID,CAE_APPS_CODE,CAE_ROLE_ID,CAE_TYPE,CAE_VALUE,CAE_STATUS,CAE_DT_CREATE,CAE_UID_CREATE) VALUES('DSV','CKT','OFFICER','TABS','jobDetails,fmTrip,mmTrip,documents,driver,deliveryOrders,audit,rejectRemarks,tracking','A',NOW(),'SYS');
INSERT INTO T_CK_ACCN_CONFIG_EXT(CAE_ACCN_ID,CAE_APPS_CODE,CAE_ROLE_ID,CAE_TYPE,CAE_VALUE,CAE_STATUS,CAE_DT_CREATE,CAE_UID_CREATE) VALUES('IODSF','CKT','OFFICER','TABS','jobDetails,fmTrip,mmTrip,documents,driver,deliveryOrders,audit,rejectRemarks,tracking','A',NOW(),'SYS');INSERT INTO T_CK_ACCN_CONFIG_EXT(CAE_ACCN_ID,CAE_APPS_CODE,CAE_ROLE_ID,CAE_TYPE,CAE_VALUE,CAE_STATUS,CAE_DT_CREATE,CAE_UID_CREATE) VALUES('IODSF','CKT','OFFICER','TABS','["jobDetails","fmTrip", "mmTrip","documents","driver","deliveryOrders", "audit","rejectRemarks","tracking"]','A',NOW(),'SYS');
INSERT INTO T_CK_ACCN_CONFIG_EXT(CAE_ACCN_ID,CAE_APPS_CODE,CAE_ROLE_ID,CAE_TYPE,CAE_VALUE,CAE_STATUS,CAE_DT_CREATE,CAE_UID_CREATE) VALUES('IODSF','CKT','OFFICER','HIDDEN_FIELDS','tripcharges','A',NOW(),'SYS');

/** COUNTRY CLICKTRUCK IS DEPLOYED TO DETERMINE WHAT VALIDATION, CONFIGURATIONS NEED TO APPLY*/
select * from T_CORE_SYSPARAM;
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICKARGO_COUNTRY_CONFIG', '{"country":"SG","currency":"SGD"}', 'Country configurations where clickargo is deployed', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');
INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_DEFAULT_TABS', 'jobDetails,fmTrip,mmTrip,documents,driver,deliveryOrders,audit,rejectRemarks,tracking', 'Default tabs for the jobs. If this is set, this will be used. Otherwise, use the one in the code', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

ALTER TABLE `clickargo2`.`T_CORE_SYSPARAM` 
CHANGE COLUMN `SYS_VAL` `SYS_VAL` VARCHAR(1024) NULL DEFAULT NULL ;

-- 19May2024 TODO to test in demo if not executed will not cause issue
-- INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_DEFAULT_DASHBOARD', '[{\"id\":0,\"dbType\":\"TRUCK_JOBS\",\"transStatistic\":{\"NEW\":0,\"ONGOING\":0},\"accnType\":\"ACC_TYPE_TO\"},{\"id\":1,\"dbType\":\"TRUCK_JOBS\",\"transStatistic\":{\"ACTIVE\":0},\"accnType\":\"ACC_TYPE_CO\"},{\"id\":2,\"dbType\":\"TRUCK_JOBS\",\"transStatistic\":{\"ACTIVE\":0},\"accnType\":\"ACC_TYPE_FF\"}]', 'Default dashboard per account type. If this is set this will be used, otherwise the dashboard in the code will be used', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');
INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_DEFAULT_STATE_FILTER', 'NEW,SUB,ACP,REJ,ASG,CAN,ONGOING,DLV', 'Default job state filter. If this is not set, it, existing code will be used.', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_DEFAULT_HIDE_FIELDS', 'tripcharges', 'Default fields to hide. Application wide config. If this is not set, existing codes still apply. ', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_DEFAULT_DASHBOARD', '[{\"id\":0,\"dbType\":\"TRUCK_JOBS\",\"transStatistic\":{\"NEW\":0,\"ONGOING\":0},\"accnType\":\"ACC_TYPE_TO\"},{\"id\":1,\"dbType\":\"TRUCK_JOBS\",\"transStatistic\":{\"ACTIVE\":0},\"accnType\":\"ACC_TYPE_CO\"},{\"id\":2,\"dbType\":\"TRUCK_JOBS\",\"transStatistic\":{\"ACTIVE\":0},\"accnType\":\"ACC_TYPE_FF\"}]', 'Default dashboard per account type. If this is set this will be used, otherwise the dashboard in the code will be used', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

UPDATE
	`clickargo2`.`T_CORE_SYSPARAM` 
SET
	`SYS_VAL` = '[{\"id\":0,\"dbType\":\"TRUCK_JOBS\",\"transStatistic\":{\"NEW\":0,\"ONGOING\":0},\"accnType\":\"ACC_TYPE_TO\"},{\"id\":1,\"dbType\":\"TRUCK_JOBS\",\"transStatistic\":{\"ACTIVE\":0},\"accnType\":\"ACC_TYPE_CO\"},{\"id\":2,\"dbType\":\"TRUCK_JOBS\",\"transStatistic\":{\"ACTIVE\":0},\"accnType\":\"ACC_TYPE_FF\"},{\"id\":3,\"dbType\":\"DRIVER_AVAILABILITY\",\"transStatistic\":{\"ASSIGNED\":0,\"UNASSIGNED\":0},\"accnType\":\"ACC_TYPE_TO\"},{\"id\":4,\"dbType\":\"DRIVER_AVAILABILITY\",\"transStatistic\":{\"ASSIGNED\":0,\"UNASSIGNED\":0},\"accnType\":\"ACC_TYPE_CO\"},{\"id\":5,\"dbType\":\"DRIVER_AVAILABILITY\",\"transStatistic\":{\"ASSIGNED\":0,\"UNASSIGNED\":0},\"accnType\":\"ACC_TYPE_FF\"}]'
WHERE
	`SYS_KEY` = 'CLICTRUCK_DEFAULT_DASHBOARD';
-- 19May2024 TODO to test in demo if not executed will not cause issue

/** T_CK_CT_CHASSIS */
DROP TABLE IF EXISTS T_CK_CT_CHASSIS;
CREATE TABLE `T_CK_CT_CHASSIS` (
  `CHS_ID` VARCHAR(35) NOT NULL COMMENT 'CHASSIS ID - UUID',
  `CHS_COMPANY` VARCHAR(35) DEFAULT NULL COMMENT 'CHASSIS COMPANY - REFERENCES T_CORE_ACCN:ACCN_ID',  
  `CHS_NO` VARCHAR(256) DEFAULT NULL COMMENT 'CHASSIS NUMBER',
  `CHS_CHASSIS_TYPE` VARCHAR(35) DEFAULT NULL COMMENT 'VEHICLE CHASSIS TYPE - REFERENCES T_CK_CT_MST_CHASSIS_TYPE:CHTY_ID',
  `CHS_STATUS` CHAR(1) DEFAULT NULL COMMENT 'CHASSIS STATUS',
  `CHS_DT_CREATE` DATETIME DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CHS_UID_CREATE` VARCHAR(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CHS_DT_LUPD` DATETIME DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CHS_UID_LUPD` VARCHAR(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CHS_ID`),
  KEY `FK_CK_CT_CHASSIS_CK_CT_MST_CHASSIS_TYPE` (`CHS_CHASSIS_TYPE`),
  CONSTRAINT `FK_CK_CT_CHASSIS_CORE_ACCN` FOREIGN KEY (`CHS_COMPANY`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_CT_CHASSIS_CK_CT_MST_CHASSIS_TYPE` FOREIGN KEY (`CHS_CHASSIS_TYPE`) REFERENCES `T_CK_CT_MST_CHASSIS_TYPE` (`CHTY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='CHASSIS TABLE';
SET FOREIGN_KEY_CHECKS=1;

INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICKARGO_ACCN_ATTACH_BASE_LOCATION', '/home/vcc/appAttachments/', 'BASE ATTACHMENT FOR ACCOUNTS RELATED FILES', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

-- execute SG.Reports/reports_SG.sql

-- execute navigation.sql but before that execute the ungrant tables as it is referencing to the t_core_perm_ex table
