/** For 2.1.0 script */

ALTER TABLE `T_CK_JOB_TRUCK` 
ADD COLUMN `JOB_IS_FINANCED` CHAR(1) NULL DEFAULT 'F' COMMENT 'JOB FINANCED STATUS -  F:E:N' AFTER `JOB_OUT_PAYMENT_DT_DUE`;

ALTER TABLE `T_CK_CT_TRIP_LOCATION` 
ADD COLUMN `TLOC_SPECIAL_INSTN` MEDIUMTEXT NULL DEFAULT NULL COMMENT 'SPECIAL INSTRUCTION AT LOCATION' AFTER `TLOC_REMARKS`,
ADD COLUMN `TLOC_DT_START` DATETIME NULL DEFAULT NULL COMMENT 'START TIME HEADING TO THE LOCATION' AFTER `TLOC_SPECIAL_INSTN`,
ADD COLUMN `TLOC_DT_REACH` DATETIME NULL DEFAULT NULL COMMENT 'TIME GPS TRACKED TRUCK TO BE AT LOCATION' AFTER `TLOC_DT_START`,
ADD COLUMN `TLOC_DT_END` DATETIME NULL DEFAULT NULL COMMENT 'TIME LEAVING THE LOCATION' AFTER `TLOC_DT_REACH`;


ALTER TABLE `T_CK_CT_TRIP_LOCATION` 
ADD COLUMN `TLOC_IS_DEVIATED` CHAR(1) NULL DEFAULT 'N' COMMENT 'DISCREPANCIES OR DAMAGE DETECTED - Y:N' AFTER `TLOC_DT_END`,
ADD COLUMN `TLOC_DEVIATION_COMMENT` MEDIUMTEXT NULL DEFAULT NULL AFTER `TLOC_IS_DEVIATED`;

ALTER TABLE `T_CK_CT_TRIP_LOCATION` 
ADD COLUMN `TLOC_COMMENT` MEDIUMTEXT NULL DEFAULT NULL COMMENT 'COMMENTS PROVIDED AT THE LOCATION BY THE RECIPENT' AFTER `TLOC_SPECIAL_INSTN`;

ALTER TABLE `T_CK_CT_TRIP_LOCATION` 
ADD COLUMN `TLOC_NAME` VARCHAR(50) NULL DEFAULT NULL AFTER `TLOC_STATUS`;

CREATE TABLE `T_CK_CT_MST_TRIP_ATTACH_TYPE` (
  `ATYP_ID` varchar(35) NOT NULL COMMENT 'ATTACHMENT TYPE ID - PHOTO : SIGNATURE : DOCUMENT',
  `ATYP_NAME` varchar(100) NOT NULL COMMENT 'ATTACHMENT TYPE NAME',
  `ATYP_DESC` varchar(255) DEFAULT NULL COMMENT 'ATTACHMENT TYPE DESCRIPTION',
  `ATYP_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'ATTACHMENT TYPE DESCRIPTION OTHER LANGUAGE',
  `ATYP_STATUS` char(1) DEFAULT NULL COMMENT 'ATTACHMENT TYPE STATUS',
  `ATYP_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `ATYP_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `ATYP_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `ATYP_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`ATYP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='TRIP ATTACHMENT TYPE TABLE';

INSERT INTO `T_CK_CT_MST_TRIP_ATTACH_TYPE` (`ATYP_ID`, `ATYP_NAME`, `ATYP_DESC`, `ATYP_DESC_OTH`, `ATYP_STATUS`, `ATYP_DT_CREATE`, `ATYP_UID_CREATE`, `ATYP_DT_LUPD`, `ATYP_UID_LUPD`) VALUES ('PHOTO', 'PHOTO', 'PHOTO', 'PHOTO', 'A', '2023-10-20 04:22:44', 'SYS', '2023-10-20 04:22:44', 'SYS');
INSERT INTO `T_CK_CT_MST_TRIP_ATTACH_TYPE` (`ATYP_ID`, `ATYP_NAME`, `ATYP_DESC`, `ATYP_DESC_OTH`, `ATYP_STATUS`, `ATYP_DT_CREATE`, `ATYP_UID_CREATE`, `ATYP_DT_LUPD`, `ATYP_UID_LUPD`) VALUES ('DOCUMENT', 'DOCUMENT', 'DOCUMENT', 'DOCUMENT', 'A', '2023-10-20 04:22:44', 'SYS', '2023-10-20 04:22:44', 'SYS');
INSERT INTO `T_CK_CT_MST_TRIP_ATTACH_TYPE` (`ATYP_ID`, `ATYP_NAME`, `ATYP_DESC`, `ATYP_DESC_OTH`, `ATYP_STATUS`, `ATYP_DT_CREATE`, `ATYP_UID_CREATE`, `ATYP_DT_LUPD`, `ATYP_UID_LUPD`) VALUES ('SIGNATURE', 'SIGNATURE', 'SIGNATURE', 'SIGNATURE', 'A', '2023-10-20 04:22:44', 'SYS', '2023-10-20 04:22:44', 'SYS');


CREATE TABLE `T_CK_CT_TRIP_ATTACH` (
  `AT_ID` varchar(35) NOT NULL COMMENT 'ATTACHMENT ID - UUID',
  `AT_TRIP_LOC` varchar(35) DEFAULT NULL COMMENT 'LOCATON - REFERENCES T_CK_CT_TRIP_LOCATION:TLOC_ID',
  `AT_TYPE` varchar(35) DEFAULT NULL COMMENT 'ATTACHMENT TYPE - REFERENCES T_CK_CT_MST_TRIP_ATTACH_TYPE:ATYP_ID',
  `AT_NAME` varchar(256) DEFAULT NULL COMMENT 'SHORT NAME FOR TYPE OF PROCESS TYPE.',
  `AT_LOC` varchar(1024) DEFAULT NULL COMMENT 'RELATIVE PATH NAME TO THE LOCATION OF THE ATTACHMENT',
  `AT_STATUS` char(1) DEFAULT NULL COMMENT 'STATUS OF THE ATTACHMENT',
  `AT_DT_CREATE` datetime DEFAULT NULL COMMENT 'CREATED DATE',
  `AT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'CREATED BY UID',
  `AT_DT_LUPD` datetime DEFAULT NULL COMMENT 'UPDATED DATE',
  `AT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'UPDATED BY UID',
  PRIMARY KEY (`AT_ID`),
  CONSTRAINT `FK_CK_CT_TRIP_ATTACH_CK_CT_TRIP_LOCATION` FOREIGN KEY (`AT_TRIP_LOC`) REFERENCES `T_CK_CT_TRIP_LOCATION` (`TLOC_ID`),
  CONSTRAINT `FK_CK_CT_TRIP_ATTACH_CK_CT_MST_TRIP_ATTACH_TYPE` FOREIGN KEY (`AT_TYPE`) REFERENCES `T_CK_CT_MST_TRIP_ATTACH_TYPE` (`ATYP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='TRIP ATTACHMENT TABLE';


ALTER TABLE `T_CK_JOB_TRUCK` 
ADD COLUMN `JOB_MOBILE_ENABLED` CHAR(1) NULL DEFAULT 'N' COMMENT 'JOB MOBILE ENABLED -  Y: N' AFTER `JOB_IS_FINANCED`;


CREATE TABLE `T_CK_CT_MST_PARTY_TYPE` (
  `PT_ID` varchar(35) NOT NULL COMMENT 'PARTY TYPE ID - CONSIGNEE:CONSIGNOR:AGENT',
  `PT_NAME` varchar(100) NOT NULL COMMENT 'PARTY TYPE NAME',
  `PT_DESC` varchar(255) DEFAULT NULL COMMENT 'PARTY TYPE DESCRIPTION',
  `PT_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'PARTY TYPE DESCRIPTION OTHER LANGUAGE',
  `PT_STATUS` char(1) DEFAULT NULL COMMENT 'PARTY TYPE STATUS',
  `PT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `PT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `PT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `PT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`PT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='PARTY TYPE TABLE';

CREATE TABLE `T_CK_CT_PARTY` (
  `PTY_ID` varchar(70) NOT NULL COMMENT 'PARTY ID',
  `PTY_NAME` varchar(256) DEFAULT NULL COMMENT 'PARTY NAME',
  `PTY_NAME_OTH` varchar(512) DEFAULT NULL COMMENT 'PARTY NAME IN OTHER LANGUAGE',
  `PTY_TYPE` varchar(35) NOT NULL COMMENT 'PARTY TYPE - REFERENCES T_CK_CT_MPT_PARTY_TYPE:PT_ID',
  `PTY_ADDR1` varchar(250) DEFAULT NULL COMMENT 'PARTY ADDRESS LINE 1',
  `PTY_ADDR2` varchar(70) DEFAULT NULL COMMENT 'PARTY ADDRESS LINE 2',
  `PTY_ADDR3` varchar(70) DEFAULT NULL COMMENT 'PARTY ADDRESS LINE 3',
  `PTY_PCODE` varchar(17) DEFAULT NULL COMMENT 'PARTY POSTAL CODE',
  `PTY_CITY` varchar(256) DEFAULT NULL COMMENT 'PARTY CITY',
  `PTY_CTYCODE` varchar(3) DEFAULT NULL COMMENT 'PARTY COUNTRY CODE',
  `PTY_STATUS` char(1) DEFAULT NULL COMMENT 'RECORD STATUS - A : I',
  `PTY_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `PTY_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `PTY_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `PTY_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`PTY_ID`),
  CONSTRAINT `FK_CK_CT_PARTY_CK_CT_MST_PARTY_TYPE` FOREIGN KEY (`PTY_TYPE`) REFERENCES `T_CK_CT_MST_PARTY_TYPE` (`PT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT = 'CLICTRUCK PARTT TABLE';


ALTER TABLE `T_CK_CT_DRV` 
ADD COLUMN `DRV_MOBILE_LANG` VARCHAR(3) NULL DEFAULT 'en' COMMENT 'Language for mobile app - ISO 639 code en:zh:in' AFTER `DRV_MOBILE_PASSWORD`;

ALTER TABLE `T_CK_CT_DRV` 
ADD COLUMN `DRV_LOGIN_FAILURE` SMALLINT NULL DEFAULT 0 COMMENT 'NUMBER OF TIMES OF LOGIN FAILURE FROM MOBILE APPLICAITON' AFTER `DRV_MOBILE_PASSWORD`;

INSERT INTO `T_CK_MST_JOB_STATE` (`JBST_ID`, `JBST_NAME`, `JBST_DESC`, `JBST_DESC_OTH`, `JBST_STATUS`, `JBST_DT_CREATE`, `JBST_UID_CREATE`, `JBST_DT_LUPD`, `JBST_UID_LUPD`) VALUES ('PAUSED', 'PAUSED', 'PAUSED', 'PAUSED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
INSERT INTO `T_CK_MST_FORM_ACTION` (`FMACT_ID`, `FMACT_NAME`, `FMACT_DESC`, `FMACT_DESC_OTH`, `FMACT_STATUS`, `FMACT_DT_CREATE`, `FMACT_UID_CREATE`, `FMACT_DT_LUPD`, `FMACT_UID_LUPD`) VALUES ('PAUSE', 'Form Pause', 'Form Pause', 'Form Pause', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');

-- execute workflow.sql

INSERT INTO `T_CK_MST_ENTITY_TYPE` (`ENTY_ID`, `ENTY_NAME`, `ENTY_DESC`, `ENTY_DESC_OTH`, `ENTY_STATUS`, `ENTY_DT_CREATE`, `ENTY_UID_CREATE`, `ENTY_DT_LUPD`, `ENTY_UID_LUPD`) VALUES ('JOB_TRUCK_MOBILE', 'TRUCK Job Mobile', 'TRUCK Job Mobile', 'TRUCK Job Mobile', 'A', '2022-10-01 01:00:00', 'SYS', '2022-10-01 01:00:00', 'SYS');

INSERT INTO T_CORE_ROLE(ROLE_APPSCODE, ROLE_ID, ROLE_STATUS, ROLE_DESC, ROLE_DT_CREATE, ROLE_UID_CREATE, ROLE_DT_LUPD, ROLE_UID_LUPD) VALUES ('CKT','DRIVER','A','DRIVER',NOW(),'SYS',NOW(),'SYS');

-- INSERT INTO T_CK_MST_FORM_ACTION (`FMACT_ID`,`FMACT_NAME`,`FMACT_DESC`,`FMACT_DESC_OTH`,`FMACT_STATUS`,`FMACT_DT_CREATE`,`FMACT_UID_CREATE`,`FMACT_DT_LUPD`,`FMACT_UID_LUPD`) VALUES('MCARGO','Mobile Form to View Cargo Details','Mobile Form to View Cargo Details','Mobile Form to View Cargo Details','A',NOW(),'SYS',NOW(),'SYS'); 
-- INSERT INTO T_CK_MST_FORM_ACTION (`FMACT_ID`,`FMACT_NAME`,`FMACT_DESC`,`FMACT_DESC_OTH`,`FMACT_STATUS`,`FMACT_DT_CREATE`,`FMACT_UID_CREATE`,`FMACT_DT_LUPD`,`FMACT_UID_LUPD`) VALUES('MREMARKS','Mobile Form to Show Remarks/Special Instructions','Mobile Form to Show Remarks/Special Instructions','Mobile Form to Show Remarks/Special Instructions','A',NOW(),'SYS',NOW(),'SYS'); 
-- INSERT INTO T_CK_MST_FORM_ACTION (`FMACT_ID`,`FMACT_NAME`,`FMACT_DESC`,`FMACT_DESC_OTH`,`FMACT_STATUS`,`FMACT_DT_CREATE`,`FMACT_UID_CREATE`,`FMACT_DT_LUPD`,`FMACT_UID_LUPD`) VALUES('MPICKUP','Mobile Form to Pickup Cargo','Mobile Form to Pickup Cargo','Mobile Form to Pickup Cargo','A',NOW(),'SYS',NOW(),'SYS'); 
-- INSERT INTO T_CK_MST_FORM_ACTION (`FMACT_ID`,`FMACT_NAME`,`FMACT_DESC`,`FMACT_DESC_OTH`,`FMACT_STATUS`,`FMACT_DT_CREATE`,`FMACT_UID_CREATE`,`FMACT_DT_LUPD`,`FMACT_UID_LUPD`) VALUES('MDELIVER','Mobile Form to Start Delivering Cargo','Mobile Form to Start Delivering Cargo','Mobile Form to Start Delivering Cargo','A',NOW(),'SYS',NOW(),'SYS'); 
-- INSERT INTO T_CK_MST_FORM_ACTION (`FMACT_ID`,`FMACT_NAME`,`FMACT_DESC`,`FMACT_DESC_OTH`,`FMACT_STATUS`,`FMACT_DT_CREATE`,`FMACT_UID_CREATE`,`FMACT_DT_LUPD`,`FMACT_UID_LUPD`) VALUES('MDROPOFF','Mobile Form to DropOff Cargo','Mobile Form to DropOff Cargo','Mobile Form to DropOff Cargo','A',NOW(),'SYS',NOW(),'SYS'); 

-- INSERT INTO `T_CK_MST_ENTITY_STATE` (`ENST_ID`, `ENST_NAME`, `ENST_DESC`, `ENST_DESC_OTH`, `ENST_STATUS`, `ENST_DT_CREATE`, `ENST_UID_CREATE`, `ENST_DT_LUPD`, `ENST_UID_LUPD`) VALUES ('TRIP_ACTIVE', 'ACTIVE TRIP STATUS (A)', 'ACTIVE TRIP STATUS, WAITING FOR DRV TO PICKUP', 'ACTIVE TRIP STATUS, WAITING FOR DRV TO PICKUP', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
-- INSERT INTO `T_CK_MST_ENTITY_STATE` (`ENST_ID`, `ENST_NAME`, `ENST_DESC`, `ENST_DESC_OTH`, `ENST_STATUS`, `ENST_DT_CREATE`, `ENST_UID_CREATE`, `ENST_DT_LUPD`, `ENST_UID_LUPD`) VALUES ('TRIP_PICKEDUP', 'PENDING TRIP STATUS (P)', 'PENDING TRIP STATUS, CARGO IS PICKED UP BY DRV', 'PENDING TRIP STATUS, CARGO IS PICKED UP BY DRV', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
-- INSERT INTO `T_CK_MST_ENTITY_STATE` (`ENST_ID`, `ENST_NAME`, `ENST_DESC`, `ENST_DESC_OTH`, `ENST_STATUS`, `ENST_DT_CREATE`, `ENST_UID_CREATE`, `ENST_DT_LUPD`, `ENST_UID_LUPD`) VALUES ('TRIP_DELIVER', 'DELIVER TRIP STATUS (R)', 'DELIVER TRIP STATUS, CARGO IS PICKED UP BY DRV AND STARTS DELIVERY', 'DELIVER TRIP STATUS, CARGO IS PICKED UP BY DRV AND STARTS DELIVERY', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
-- INSERT INTO `T_CK_MST_ENTITY_STATE` (`ENST_ID`, `ENST_NAME`, `ENST_DESC`, `ENST_DESC_OTH`, `ENST_STATUS`, `ENST_DT_CREATE`, `ENST_UID_CREATE`, `ENST_DT_LUPD`, `ENST_UID_LUPD`) VALUES ('TRIP_DROP_OFF', 'DELIVERED/DROP OFF TRIP STATUS (D)', 'DELIVERED TRIP STATUS, CARGO IS DELIVERED', 'DELIVERED TRIP STATUS, CARGO IS DELIVERED', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');


INSERT INTO `T_CK_MST_JOB_STATE` (`JBST_ID`, `JBST_NAME`, `JBST_DESC`, `JBST_DESC_OTH`, `JBST_STATUS`, `JBST_DT_CREATE`, `JBST_UID_CREATE`, `JBST_DT_LUPD`, `JBST_UID_LUPD`) VALUES ('M_ACTIVE', '(A) MOBILE JOB ACTIVE TRIP STATUS', 'MOBILE JOB ACTIVE TRIP STATUS', 'MOBILE JOB ACTIVE TRIP STATUS', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
INSERT INTO `T_CK_MST_JOB_STATE` (`JBST_ID`, `JBST_NAME`, `JBST_DESC`, `JBST_DESC_OTH`, `JBST_STATUS`, `JBST_DT_CREATE`, `JBST_UID_CREATE`, `JBST_DT_LUPD`, `JBST_UID_LUPD`) VALUES ('M_PICKED_UP', '(P) MOBILE JOB PICKED UP', 'MOBILE JOB PICKED UP', 'MOBILE JOB PICKED UP', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');
INSERT INTO `T_CK_MST_JOB_STATE` (`JBST_ID`, `JBST_NAME`, `JBST_DESC`, `JBST_DESC_OTH`, `JBST_STATUS`, `JBST_DT_CREATE`, `JBST_UID_CREATE`, `JBST_DT_LUPD`, `JBST_UID_LUPD`) VALUES ('M_DELIVERED', '(R) MOBILE JOB START DELIVERY', 'MOBILE JOB START DELIVERY', 'MOBILE JOB START DELIVERY', 'A', '2020-10-01 00:00:00', 'SYS', '2020-10-01 00:00:00', 'SYS');

-- execute formcontrol.sql
-- execute workflow.sql

replace INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_STATUS`) 
VALUES ('CLICTRUCK_TRACK_LATESTSTATUS_URL', 'https://ext.logistics.myascents.net/api/3rdparty/unit/lateststatus?key=$2a$11$oo7.I606K/DVjUdZi88UzeFu.tLQiwTChnty4KATKbf3Dq0T8s2Ii', 'iMei location', sysdate(), 'SYS', 'A');

CREATE TABLE T_CK_CT_TRACK_IMEI_STATUS (
  TIS_ID varchar(35) NOT NULL COMMENT 'TRACK LOCATION ID - UUID',
  TIS_JOB_ID varchar(35) NULL COMMENT 'JOB_ID - REFERENCE T_CK_JOB_TRUCK:JOB_ID',
  TIS_IMEI varchar(128) DEFAULT NULL COMMENT 'IMEI',
  TIS_DT_START datetime DEFAULT NULL COMMENT 'CALL ASCENT API URL: REQUEST START TIME PARAMETER',
  TIS_DT_END datetime DEFAULT NULL COMMENT 'CALL ASCENT API URL: REQUEST END TIME PARAMETER',
  TIS_REQ_URL varchar(1024) DEFAULT '' COMMENT 'CALL ASCENT API REQUEST URL',
  TIS_RSP_BODY mediumtext DEFAULT NULL COMMENT 'CALL ASCENT API RESPONSE BODY',
  TIS_GPS varchar(128) DEFAULT '' COMMENT 'GPS',
  TIS_HTTP_STATUS varchar(35) DEFAULT '' COMMENT 'HTTP RESPONSE STATUS',
  TIS_REMARK varchar(1024) DEFAULT '' COMMENT 'REMARK',
  TIS_STATUS char(1) DEFAULT NULL COMMENT 'CONTRACT STATE STATUS',
  TIS_DT_CREATE datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  TIS_UID_CREATE varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  TIS_DT_LUPD datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  TIS_UID_LUPD varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`TIS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='TRACK AND TRACE IMEI STATUS TABLE';


CREATE TABLE T_CK_CT_TRACK_DISTANCE (
  TD_ID varchar(35) NOT NULL COMMENT 'TRACK LOCATION ID - UUID',
  TD_JOB_ID varchar(35) NULL COMMENT 'JOB_ID - REFERENCE T_CK_JOB_TRUCK:JOB_ID',
  TD_ORIGINS varchar(1024) DEFAULT NULL COMMENT 'ORIGINS LOCATION: ADDRESS or GPS',
  TD_DESTINATION varchar(1024) DEFAULT NULL COMMENT 'DESTINATION LOCATION: ADDRESS or GPS',
  TD_TRANSPORTAION_MODE varchar(35) DEFAULT NULL COMMENT 'TRANSPORTAION: DRIVING, WALKING, BICYCLING OR TRANSIT, DEFAULT IS DRIVING',
  TD_DT_START datetime DEFAULT NULL COMMENT 'CALL ASCENT API URL: REQUEST START TIME PARAMETER',
  TD_DT_END datetime DEFAULT NULL COMMENT 'CALL ASCENT API URL: REQUEST END TIME PARAMETER',
  TD_REQ_URL varchar(1024) DEFAULT '' COMMENT 'CALL ASCENT API REQUEST URL',
  TD_RSP_BODY mediumtext DEFAULT NULL COMMENT 'CALL ASCENT API RESPONSE BODY',
  TD_DISTANCE INT DEFAULT 0 COMMENT 'DISTANCE XX METER',
  TD_DURATION INT DEFAULT 0 COMMENT 'DURATION XX MINUTE',
  TD_HTTP_STATUS varchar(35) DEFAULT '' COMMENT 'HTTP RESPONSE STATUS',
  TD_REMARK varchar(1024) DEFAULT '' COMMENT 'REMARK',
  TD_STATUS char(1) DEFAULT NULL COMMENT 'CONTRACT STATE STATUS',
  TD_DT_CREATE datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  TD_UID_CREATE varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  TD_DT_LUPD datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  TD_UID_LUPD varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`TD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='TRACK AND TRACE DISTANCE TABLE';



CREATE TABLE T_CK_CT_TRACK_NOTIFY (
  TN_ID varchar(35) NOT NULL COMMENT 'TRACK NOTIFY ID - UUID',
  TN_JOB_ID varchar(35) NULL COMMENT 'JOB_ID - REFERENCE T_CK_JOB_TRUCK:JOB_ID',
  TN_RECEIVER varchar(1024) DEFAULT NULL COMMENT 'WHATSAPP RECEIVER',
  TN_MESSAGE varchar(2048) DEFAULT NULL COMMENT 'WHATSAPP MESSAGE',
  TN_DT_START datetime DEFAULT NULL COMMENT 'CALL ASCENT API URL: REQUEST START TIME PARAMETER',
  TN_DT_END datetime DEFAULT NULL COMMENT 'CALL ASCENT API URL: REQUEST END TIME PARAMETER',
  TN_REQ_URL varchar(2048) DEFAULT '' COMMENT 'CALL ASCENT API REQUEST URL',
  TN_RSP_BODY mediumtext DEFAULT NULL COMMENT 'CALL ASCENT API RESPONSE BODY',
  TN_SEND_STATUS INT DEFAULT 0 COMMENT 'SEND STATUS, PARSE FROM RESPONSE BODY',
  TN_HTTP_STATUS varchar(35) DEFAULT '' COMMENT 'HTTP RESPONSE STATUS',
  TN_REMARK varchar(1024) DEFAULT '' COMMENT 'REMARK',
  TN_STATUS char(1) DEFAULT NULL COMMENT 'CONTRACT STATE STATUS',
  TN_DT_CREATE datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  TN_UID_CREATE varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  TN_DT_LUPD datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  TN_UID_LUPD varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`TN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='TRACK AND TRACE WHATSAPP NOTIFICATION LOG TABLE';

-- change T_CK_CT_TRACK_LOC_ITEM foreign key
ALTER TABLE `clickargo2`.`T_CK_CT_TRACK_LOC_ITEM` 
DROP FOREIGN KEY `FK_T_CK_CT_TRACK_LOC_ITEM_TL_ID`;

ALTER TABLE `clickargo2`.`T_CK_CT_TRACK_LOC_ITEM` 
DROP COLUMN `TLI_LOC_ID` ;

ALTER TABLE `clickargo2`.`T_CK_CT_TRACK_LOC_ITEM` 
ADD COLUMN `TLI_TRIP_LOC_ID` VARCHAR(45) NULL AFTER `TLI_TRACK_LOC_ID`;

ALTER TABLE `clickargo2`.`T_CK_CT_TRACK_LOC_ITEM` 
ADD CONSTRAINT `T_CK_CT_TRACK_LOC_ITEM_TLI_TRIP_LOC_ID`
  FOREIGN KEY (`TLI_TRIP_LOC_ID`)
  REFERENCES `clickargo2`.`T_CK_CT_TRIP_LOCATION` (`TLOC_ID`);
  
SET SQL_SAFE_UPDATES = 0;
UPDATE `clickargo2`.`T_CK_CT_TRIP_ATTACH` SET `AT_TRIP_LOC`=NULL;
SET SQL_SAFE_UPDATES = 1;

ALTER TABLE `clickargo2`.`T_CK_CT_TRIP_ATTACH`
DROP FOREIGN KEY `FK_CK_CT_TRIP_ATTACH_CK_CT_TRIP_LOCATION`;

ALTER TABLE `clickargo2`.`T_CK_CT_TRIP_ATTACH`
DROP COLUMN `AT_TRIP_LOC`;

ALTER TABLE `clickargo2`.`T_CK_CT_TRIP_ATTACH`
ADD COLUMN `AT_TRIP` VARCHAR(35) DEFAULT NULL COMMENT 'ATTACHMENT TRIP - REFERENCES T_CK_CT_TRIP:TR_ID' AFTER `AT_ID`;

ALTER TABLE `clickargo2`.`T_CK_CT_TRIP_ATTACH`
ADD CONSTRAINT `FK_CK_CT_TRIP_ATTACH_CK_CT_TRIP`
FOREIGN KEY (`AT_TRIP`)
REFERENCES `clickargo2`.`T_CK_CT_TRIP` (`TR_ID`);

UPDATE `clickargo2`.`T_CK_CT_MST_TRIP_ATTACH_TYPE` SET ATYP_ID='PHOTO_PICKUP', ATYP_NAME='PHOTO PICK UP', ATYP_DESC='PHOTO PICK UP', ATYP_DESC_OTH='PHOTO PICK UP' WHERE ATYP_ID='PHOTO';
INSERT INTO `clickargo2`.`T_CK_CT_MST_TRIP_ATTACH_TYPE` (ATYP_ID,ATYP_NAME,ATYP_DESC,ATYP_DESC_OTH,ATYP_STATUS,ATYP_DT_CREATE,ATYP_UID_CREATE,ATYP_DT_LUPD,ATYP_UID_LUPD) VALUES
	 ('PHOTO_DROPOFF','PHOTO DROP OFF','PHOTO DROP OFF','PHOTO DROP OFF','A','2023-10-20 04:22:44','SYS','2023-10-20 04:22:44','SYS');


 


-- Track and Trace report for CO CO CO CO
INSERT INTO `clickargo2`.`T_CORE_RPT` (`RPT_RPTID`, `RPT_ACCN_TYPE`, `RPT_APPSID`, `RPT_CAT`, `RPT_ROLE_ID`, `RPT_NAME`, `RPT_TITLE`, `RPT_LANDSCAPE`, `RPT_SHOW`, `RPT_JSPR`, `RPT_BORDER`, `RPT_DT_CRT`, `RPT_UID_CRT`, `RPT_DT_LUPD`, `RPT_UID_LUPD`) 
VALUES ('RPT_CO_TRACK', 'ACC_TYPE_CO', 'CKT', 'OP_ADMIN', 'ADMIN', 'Track and Trace', 'Track and Trace', 'Y', 'Y', 'N', 'N', '2021-10-25 00:00:00', 'SYS', '2021-10-25 00:00:00', 'SYS');

INSERT INTO `clickargo2`.`T_CORE_RPT_ACL` (`RPTA_RPTID`, `RPTA_ACCN_TYPE`, `RPTA_ROLEID`, `RPTA_APPSID`, `RPTA_ACCNID`) 
VALUES ('RPT_CO_TRACK', 'ACC_TYPE_CO', 'ADMIN', 'CKT', 'ALKNAR');

INSERT INTO `clickargo2`.`T_CORE_RPT_FILTER` (`RPTF_ID`, `RPTF_ACCN_TYPE`, `RPTF_IDX`, `RPTF_NAME`, `RPTF_FILTYPE`, `RPTF_CAPTION`, `RPTF_BASIC_ROW`, `RPTF_LISTBOX_TBL`, `RPTF_SHOW`, `RPTF_MANDATORY`) 
VALUES ('RPT_CO_TRACK', 'ACC_TYPE_CO', '0', 'APPROVE_DATE', 'R', 'APPROVE Date', '1', '', 'Y', 'N');

REPLACE INTO `clickargo2`.`T_CORE_RPT_TABLE` (`RPTT_RPTID`, `RPTT_ACCN_TYPE`, `RPTT_TBL_IDX`, `RPTT_NAME`, `RPTT_WIDTH_PERC`, `RPTT_SHOW`, `RPTT_COLS`, `RPTT_RPT_QRY`) 
VALUES ('RPT_CO_TRACK', 'ACC_TYPE_CO', '0', 'Truck Enter Destination Time', '100.0000', 'Y', '0', 'SELECT * FROM V_CK_CT_TRACK_LOC WHERE  RCD_DT_BILL_APPROVED > \'@FIL_APPROVE_DATE_FROM@\'         AND RCD_DT_BILL_APPROVED < \'@FIL_APPROVE_DATE_TO@\' order by TR_JOB desc');



REPLACE INTO `clickargo2`.`T_CORE_RPT_COLUMN` (`RPTCO_RPTID`, `RPTCO_ACCN_TYPE`, `RPTCO_TBL_IDX`, `RPTCO_IDX`, `RPTCO_DBCOL`, `RPTCO_CAPTION`, `RPTCO_COLTYPE`, `RPTCO_NUM_PRECISION`, `RPTCO_NUM_NO_ZERO`, `RPTCO_NUM_ACCFORMAT`, `RPTCO_NUM_NEG_ONLY`, `RPTCO_NUM_POS_ONLY`, `RPTCO_NUM_NOSIGN`, `RPTCO_IN_SUBTOTAL`, `RPTCO_IN_TOTAL`, `RPTCO_WIDTH`, `RPTCO_ROW_IDX`, `RPTCO_COL_IDX`, `RPTCO_SHOW`, `RPTCO_SORT_IDX`, `RPTCO_TAG`) 
VALUES ('RPT_CO_TRACK', 'ACC_TYPE_CO', '0', '1', 'RCD_DT_BILL_APPROVED', 'Approve Date', 'T ', '0', 'N', '0', 'N', 'N', 'N', 'N', 'N', '80', '1', '2', 'y', '-1', '');
REPLACE INTO `clickargo2`.`T_CORE_RPT_COLUMN` (`RPTCO_RPTID`, `RPTCO_ACCN_TYPE`, `RPTCO_TBL_IDX`, `RPTCO_IDX`, `RPTCO_DBCOL`, `RPTCO_CAPTION`, `RPTCO_COLTYPE`, `RPTCO_NUM_PRECISION`, `RPTCO_NUM_NO_ZERO`, `RPTCO_NUM_ACCFORMAT`, `RPTCO_NUM_NEG_ONLY`, `RPTCO_NUM_POS_ONLY`, `RPTCO_NUM_NOSIGN`, `RPTCO_IN_SUBTOTAL`, `RPTCO_IN_TOTAL`, `RPTCO_WIDTH`, `RPTCO_ROW_IDX`, `RPTCO_COL_IDX`, `RPTCO_SHOW`, `RPTCO_SORT_IDX`, `RPTCO_TAG`) 
VALUES ('RPT_CO_TRACK', 'ACC_TYPE_CO', '0', '2', 'TR_JOB', 'Job ID', 'T', '0', 'N', '0', 'N', 'N', 'N', 'N', 'N', '110', '1', '2', 'y', '-1', '');
REPLACE INTO `clickargo2`.`T_CORE_RPT_COLUMN` (`RPTCO_RPTID`, `RPTCO_ACCN_TYPE`, `RPTCO_TBL_IDX`, `RPTCO_IDX`, `RPTCO_DBCOL`, `RPTCO_CAPTION`, `RPTCO_COLTYPE`, `RPTCO_NUM_PRECISION`, `RPTCO_NUM_NO_ZERO`, `RPTCO_NUM_ACCFORMAT`, `RPTCO_NUM_NEG_ONLY`, `RPTCO_NUM_POS_ONLY`, `RPTCO_NUM_NOSIGN`, `RPTCO_IN_SUBTOTAL`, `RPTCO_IN_TOTAL`, `RPTCO_WIDTH`, `RPTCO_ROW_IDX`, `RPTCO_COL_IDX`, `RPTCO_SHOW`, `RPTCO_SORT_IDX`, `RPTCO_TAG`) 
VALUES ('RPT_CO_TRACK', 'ACC_TYPE_CO', '0', '3', 'ADDRESS', 'Destination', 'T', '0', 'N', '0', 'N', 'N', 'N', 'N', 'N', '200', '1', '2', 'y', '-1', '');
REPLACE INTO `clickargo2`.`T_CORE_RPT_COLUMN` (`RPTCO_RPTID`, `RPTCO_ACCN_TYPE`, `RPTCO_TBL_IDX`, `RPTCO_IDX`, `RPTCO_DBCOL`, `RPTCO_CAPTION`, `RPTCO_COLTYPE`, `RPTCO_NUM_PRECISION`, `RPTCO_NUM_NO_ZERO`, `RPTCO_NUM_ACCFORMAT`, `RPTCO_NUM_NEG_ONLY`, `RPTCO_NUM_POS_ONLY`, `RPTCO_NUM_NOSIGN`, `RPTCO_IN_SUBTOTAL`, `RPTCO_IN_TOTAL`, `RPTCO_WIDTH`, `RPTCO_ROW_IDX`, `RPTCO_COL_IDX`, `RPTCO_SHOW`, `RPTCO_SORT_IDX`, `RPTCO_TAG`) 
VALUES ('RPT_CO_TRACK', 'ACC_TYPE_CO', '0', '4', 'SCHEDULER_TIME', 'Scheduler Time', 'T', '0', 'N', '0', 'N', 'N', 'N', 'N', 'N', '100', '1', '2', 'y', '-1', '');
REPLACE INTO `clickargo2`.`T_CORE_RPT_COLUMN` (`RPTCO_RPTID`, `RPTCO_ACCN_TYPE`, `RPTCO_TBL_IDX`, `RPTCO_IDX`, `RPTCO_DBCOL`, `RPTCO_CAPTION`, `RPTCO_COLTYPE`, `RPTCO_NUM_PRECISION`, `RPTCO_NUM_NO_ZERO`, `RPTCO_NUM_ACCFORMAT`, `RPTCO_NUM_NEG_ONLY`, `RPTCO_NUM_POS_ONLY`, `RPTCO_NUM_NOSIGN`, `RPTCO_IN_SUBTOTAL`, `RPTCO_IN_TOTAL`, `RPTCO_WIDTH`, `RPTCO_ROW_IDX`, `RPTCO_COL_IDX`, `RPTCO_SHOW`, `RPTCO_SORT_IDX`, `RPTCO_TAG`) 
VALUES ('RPT_CO_TRACK', 'ACC_TYPE_CO', '0', '5', 'TLI_DT_ENTER_30', 'Enter time(30M)', 'T', '0', 'N', '0', 'N', 'N', 'N', 'N', 'N', '80', '1', '2', 'y', '-1', '');
REPLACE INTO `clickargo2`.`T_CORE_RPT_COLUMN` (`RPTCO_RPTID`, `RPTCO_ACCN_TYPE`, `RPTCO_TBL_IDX`, `RPTCO_IDX`, `RPTCO_DBCOL`, `RPTCO_CAPTION`, `RPTCO_COLTYPE`, `RPTCO_NUM_PRECISION`, `RPTCO_NUM_NO_ZERO`, `RPTCO_NUM_ACCFORMAT`, `RPTCO_NUM_NEG_ONLY`, `RPTCO_NUM_POS_ONLY`, `RPTCO_NUM_NOSIGN`, `RPTCO_IN_SUBTOTAL`, `RPTCO_IN_TOTAL`, `RPTCO_WIDTH`, `RPTCO_ROW_IDX`, `RPTCO_COL_IDX`, `RPTCO_SHOW`, `RPTCO_SORT_IDX`, `RPTCO_TAG`) 
VALUES ('RPT_CO_TRACK', 'ACC_TYPE_CO', '0', '6', 'TLI_DT_ENTER_100', 'Enter time(100M)', 'T', '0', 'N', '0', 'N', 'N', 'N', 'N', 'N', '80', '1', '2', 'y', '-1', '');

-- Track and Trace report for TO TO TO
INSERT INTO `clickargo2`.`T_CORE_RPT` (`RPT_RPTID`, `RPT_ACCN_TYPE`, `RPT_APPSID`, `RPT_CAT`, `RPT_ROLE_ID`, `RPT_NAME`, `RPT_TITLE`, `RPT_LANDSCAPE`, `RPT_SHOW`, `RPT_JSPR`, `RPT_BORDER`, `RPT_DT_CRT`, `RPT_UID_CRT`, `RPT_DT_LUPD`, `RPT_UID_LUPD`) 
VALUES ('RPT_TO_TRACK', 'ACC_TYPE_TO', 'CKT', 'OP_ADMIN', 'ADMIN', 'Track and Trace', 'Track and Trace', 'Y', 'Y', 'N', 'N', '2021-10-25 00:00:00', 'SYS', '2021-10-25 00:00:00', 'SYS');

INSERT INTO `clickargo2`.`T_CORE_RPT_ACL` (`RPTA_RPTID`, `RPTA_ACCN_TYPE`, `RPTA_ROLEID`, `RPTA_APPSID`, `RPTA_ACCNID`) 
VALUES ('RPT_TO_TRACK', 'ACC_TYPE_TO', 'ADMIN', 'CKT', null);

INSERT INTO `clickargo2`.`T_CORE_RPT_FILTER` (`RPTF_ID`, `RPTF_ACCN_TYPE`, `RPTF_IDX`, `RPTF_NAME`, `RPTF_FILTYPE`, `RPTF_CAPTION`, `RPTF_BASIC_ROW`, `RPTF_LISTBOX_TBL`, `RPTF_SHOW`, `RPTF_MANDATORY`) 
VALUES ('RPT_TO_TRACK', 'ACC_TYPE_TO', '0', 'APPROVE_DATE', 'R', 'APPROVE Date', '1', '', 'Y', 'N');

REPLACE INTO `clickargo2`.`T_CORE_RPT_TABLE` (`RPTT_RPTID`, `RPTT_ACCN_TYPE`, `RPTT_TBL_IDX`, `RPTT_NAME`, `RPTT_WIDTH_PERC`, `RPTT_SHOW`, `RPTT_COLS`, `RPTT_RPT_QRY`) 
VALUES ('RPT_TO_TRACK', 'ACC_TYPE_TO', '0', 'Truck Enter Destination Time', '100.0000', 'Y', '0', 'SELECT * FROM V_CK_CT_TRACK_LOC WHERE  RCD_DT_BILL_APPROVED > \'@FIL_APPROVE_DATE_FROM@\'         AND RCD_DT_BILL_APPROVED < \'@FIL_APPROVE_DATE_TO@\' order by TR_JOB desc');


REPLACE INTO `clickargo2`.`T_CORE_RPT_COLUMN` (`RPTCO_RPTID`, `RPTCO_ACCN_TYPE`, `RPTCO_TBL_IDX`, `RPTCO_IDX`, `RPTCO_DBCOL`, `RPTCO_CAPTION`, `RPTCO_COLTYPE`, `RPTCO_NUM_PRECISION`, `RPTCO_NUM_NO_ZERO`, `RPTCO_NUM_ACCFORMAT`, `RPTCO_NUM_NEG_ONLY`, `RPTCO_NUM_POS_ONLY`, `RPTCO_NUM_NOSIGN`, `RPTCO_IN_SUBTOTAL`, `RPTCO_IN_TOTAL`, `RPTCO_WIDTH`, `RPTCO_ROW_IDX`, `RPTCO_COL_IDX`, `RPTCO_SHOW`, `RPTCO_SORT_IDX`, `RPTCO_TAG`) 
VALUES ('RPT_TO_TRACK', 'ACC_TYPE_TO', '0', '1', 'RCD_DT_BILL_APPROVED', 'Approve Date', 'T ', '0', 'N', '0', 'N', 'N', 'N', 'N', 'N', '80', '1', '2', 'y', '-1', '');
REPLACE INTO `clickargo2`.`T_CORE_RPT_COLUMN` (`RPTCO_RPTID`, `RPTCO_ACCN_TYPE`, `RPTCO_TBL_IDX`, `RPTCO_IDX`, `RPTCO_DBCOL`, `RPTCO_CAPTION`, `RPTCO_COLTYPE`, `RPTCO_NUM_PRECISION`, `RPTCO_NUM_NO_ZERO`, `RPTCO_NUM_ACCFORMAT`, `RPTCO_NUM_NEG_ONLY`, `RPTCO_NUM_POS_ONLY`, `RPTCO_NUM_NOSIGN`, `RPTCO_IN_SUBTOTAL`, `RPTCO_IN_TOTAL`, `RPTCO_WIDTH`, `RPTCO_ROW_IDX`, `RPTCO_COL_IDX`, `RPTCO_SHOW`, `RPTCO_SORT_IDX`, `RPTCO_TAG`) 
VALUES ('RPT_TO_TRACK', 'ACC_TYPE_TO', '0', '2', 'TR_JOB', 'Job ID', 'T', '0', 'N', '0', 'N', 'N', 'N', 'N', 'N', '110', '1', '2', 'y', '-1', '');
REPLACE INTO `clickargo2`.`T_CORE_RPT_COLUMN` (`RPTCO_RPTID`, `RPTCO_ACCN_TYPE`, `RPTCO_TBL_IDX`, `RPTCO_IDX`, `RPTCO_DBCOL`, `RPTCO_CAPTION`, `RPTCO_COLTYPE`, `RPTCO_NUM_PRECISION`, `RPTCO_NUM_NO_ZERO`, `RPTCO_NUM_ACCFORMAT`, `RPTCO_NUM_NEG_ONLY`, `RPTCO_NUM_POS_ONLY`, `RPTCO_NUM_NOSIGN`, `RPTCO_IN_SUBTOTAL`, `RPTCO_IN_TOTAL`, `RPTCO_WIDTH`, `RPTCO_ROW_IDX`, `RPTCO_COL_IDX`, `RPTCO_SHOW`, `RPTCO_SORT_IDX`, `RPTCO_TAG`) 
VALUES ('RPT_TO_TRACK', 'ACC_TYPE_TO', '0', '3', 'ADDRESS', 'Destination', 'T', '0', 'N', '0', 'N', 'N', 'N', 'N', 'N', '200', '1', '2', 'y', '-1', '');
REPLACE INTO `clickargo2`.`T_CORE_RPT_COLUMN` (`RPTCO_RPTID`, `RPTCO_ACCN_TYPE`, `RPTCO_TBL_IDX`, `RPTCO_IDX`, `RPTCO_DBCOL`, `RPTCO_CAPTION`, `RPTCO_COLTYPE`, `RPTCO_NUM_PRECISION`, `RPTCO_NUM_NO_ZERO`, `RPTCO_NUM_ACCFORMAT`, `RPTCO_NUM_NEG_ONLY`, `RPTCO_NUM_POS_ONLY`, `RPTCO_NUM_NOSIGN`, `RPTCO_IN_SUBTOTAL`, `RPTCO_IN_TOTAL`, `RPTCO_WIDTH`, `RPTCO_ROW_IDX`, `RPTCO_COL_IDX`, `RPTCO_SHOW`, `RPTCO_SORT_IDX`, `RPTCO_TAG`) 
VALUES ('RPT_TO_TRACK', 'ACC_TYPE_TO', '0', '4', 'SCHEDULER_TIME', 'Scheduler Time', 'T', '0', 'N', '0', 'N', 'N', 'N', 'N', 'N', '100', '1', '2', 'y', '-1', '');
REPLACE INTO `clickargo2`.`T_CORE_RPT_COLUMN` (`RPTCO_RPTID`, `RPTCO_ACCN_TYPE`, `RPTCO_TBL_IDX`, `RPTCO_IDX`, `RPTCO_DBCOL`, `RPTCO_CAPTION`, `RPTCO_COLTYPE`, `RPTCO_NUM_PRECISION`, `RPTCO_NUM_NO_ZERO`, `RPTCO_NUM_ACCFORMAT`, `RPTCO_NUM_NEG_ONLY`, `RPTCO_NUM_POS_ONLY`, `RPTCO_NUM_NOSIGN`, `RPTCO_IN_SUBTOTAL`, `RPTCO_IN_TOTAL`, `RPTCO_WIDTH`, `RPTCO_ROW_IDX`, `RPTCO_COL_IDX`, `RPTCO_SHOW`, `RPTCO_SORT_IDX`, `RPTCO_TAG`) 
VALUES ('RPT_TO_TRACK', 'ACC_TYPE_TO', '0', '5', 'TLI_DT_ENTER_30', 'Enter time(30M)', 'T', '0', 'N', '0', 'N', 'N', 'N', 'N', 'N', '80', '1', '2', 'y', '-1', '');
REPLACE INTO `clickargo2`.`T_CORE_RPT_COLUMN` (`RPTCO_RPTID`, `RPTCO_ACCN_TYPE`, `RPTCO_TBL_IDX`, `RPTCO_IDX`, `RPTCO_DBCOL`, `RPTCO_CAPTION`, `RPTCO_COLTYPE`, `RPTCO_NUM_PRECISION`, `RPTCO_NUM_NO_ZERO`, `RPTCO_NUM_ACCFORMAT`, `RPTCO_NUM_NEG_ONLY`, `RPTCO_NUM_POS_ONLY`, `RPTCO_NUM_NOSIGN`, `RPTCO_IN_SUBTOTAL`, `RPTCO_IN_TOTAL`, `RPTCO_WIDTH`, `RPTCO_ROW_IDX`, `RPTCO_COL_IDX`, `RPTCO_SHOW`, `RPTCO_SORT_IDX`, `RPTCO_TAG`) 
VALUES ('RPT_TO_TRACK', 'ACC_TYPE_TO', '0', '6', 'TLI_DT_ENTER_100', 'Enter time(100M)', 'T', '0', 'N', '0', 'N', 'N', 'N', 'N', 'N', '80', '1', '2', 'y', '-1', '');

-- SET foreign_key_checks = 0;

INSERT INTO clickargo2.T_CK_MST_FORM_ACTION (FMACT_ID,FMACT_NAME,FMACT_DESC,FMACT_DESC_OTH,FMACT_STATUS,FMACT_DT_CREATE,FMACT_UID_CREATE,FMACT_DT_LUPD,FMACT_UID_LUPD) VALUES
('MREDO','Mobile Form to Redo Pickup Cargo','Mobile Form to Redo Pickup Cargo','Mobile Form to Redo Pickup Cargo','A','2023-10-31 13:37:57','SYS','2023-10-31 13:37:57','SYS');

-- DSV

CREATE TABLE `T_CK_CT_MST_SHIPMENT_STATE` (
  `ST_ID` varchar(35) NOT NULL COMMENT 'SHIPMENT STATE ID - JOB_CREATED : JOB_NOT_CREATED : CONTENT_ERROR : CONTENT_EMPTY',
  `ST_NAME` varchar(100) NOT NULL COMMENT 'SHIPMENT STATE NAME',
  `ST_DESC` varchar(255) DEFAULT NULL COMMENT 'SHIPMENT STATE DESCRIPTION',
  `ST_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'SHIPMENT STATE DESCRIPTION OTHER LANGUAGE',
  `ST_STATUS` char(1) DEFAULT NULL COMMENT 'SHIPMENT STATE STATUS',
  `ST_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `ST_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `ST_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `ST_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`ST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='SHIPMENT STATE TABLE';

CREATE TABLE `T_CK_CT_DSV_SHIPMENT` (
  `SH_ID` varchar(35) NOT NULL COMMENT 'MESSAGE LOG ID - UUID',
  `SH_MSG_ID` varchar(35) NOT NULL COMMENT 'MESSAGE ID - FROM Header.MessageId',
  `SH_MSG_VER` smallint NOT NULL DEFAULT 1 COMMENT 'MESSAGE ID VERSION - NUMBER OF COUNT OF SAME SH_MSG_ID',
  `SH_NAME` varchar(1024) DEFAULT NULL COMMENT 'FILE NAME OF THE XML',
  `SH_DT_ISSUE` datetime DEFAULT NULL COMMENT 'ISSUE DATE - Header.DocumentDate.DateTime WHERE DocumentDate.Type = IssueDate',
  `SH_DT_LOAD` datetime DEFAULT NULL COMMENT 'DATE TIME WHERE THE XML FILE IS LOADED',
  `SH_JOB` varchar(35) DEFAULT NULL COMMENT 'JOB CREATED - REFERENCE T_CK_JOB:JOB_ID',
  `SH_DT_JOB` datetime DEFAULT NULL COMMENT 'DATE TIME WHEN JOB IS CREATED',
  `SH_STATE` varchar(35) DEFAULT NULL COMMENT 'SHIPMENT STATE - REFERENCES T_CK_CT_MST_SHIPMENT_STATE:ST_ID',
  `SH_ERR_CODE` varchar(5) DEFAULT NULL COMMENT 'ERROR OR PROCESSING CODE - NULL WHEN JOB IS CREATED',
  `SH_CONTENT` mediumtext DEFAULT NULL COMMENT 'SHIPMENT CONTENT - XML',
  `SH_STATUS` char(1) DEFAULT NULL COMMENT 'SHIPMENT STATE STATUS',
  `SH_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `SH_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `SH_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `SH_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  CONSTRAINT `FK_CK_CT_DSV_SHIPMENT_CK_JOB` FOREIGN KEY (`SH_JOB`) REFERENCES `T_CK_JOB` (`JOB_ID`),
  CONSTRAINT `FK_CK_CT_DSV_SHIPMENT_CK_CT_MST_SHIPMENT_STATE` FOREIGN KEY (`SH_STATE`) REFERENCES `T_CK_CT_MST_SHIPMENT_STATE` (`ST_ID`),
  PRIMARY KEY (`SH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DSV SHIPMENT TABLE';

CREATE TABLE `T_CK_JOB_TRUCK_POD` (
  `JPOD_JOB_ID` varchar(35) NOT NULL COMMENT 'JOB PARENT - REFERENCE T_CK_JOB:JOB_ID',
  `JPOD_TEMPLATE_BEAN` varchar(35) DEFAULT NULL COMMENT 'TEMPLATE BEAN NAME - SPRING BEAN NAME',
  `JPOD_DT_DOC_CREATE` datetime DEFAULT NULL COMMENT 'DATE TIME THAT POD DOC WAS CREATED',
  `JPOD_DOC_LOC` varchar(1024) DEFAULT NULL COMMENT 'POD DOC ATTACHMENT PATH REFERENCE FROM SYS_PARAM SETUP',
  `JPOD_STATUS` char(1) DEFAULT NULL COMMENT 'RECORD STATUS - A (ACTIVE) : C (COMPLETED)',
  `JPOD_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `JPOD_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `JPOD_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `JPOD_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`JPOD_JOB_ID`),
  CONSTRAINT `FK_CK_JOB_TRUCK_POD_CK_JOB` FOREIGN KEY (`JPOD_JOB_ID`) REFERENCES `T_CK_JOB` (`JOB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='TRUCK JOB POD TABLE';

CREATE TABLE `T_CK_CT_POD_TEMPALTE` (
  `JPT_ID` varchar(35) NOT NULL COMMENT 'POD TEMPALTE ID - UUID',
  `JPT_ACCN` varchar(35) DEFAULT NULL COMMENT 'ACCN POD TEMPLATE - REFERENCE T_CORE_ACCN:ACCN_ID',
  `JPT_PRTY` varchar(35) DEFAULT NULL COMMENT 'PARTY POD TEMPLATE - REFERENCE T_CK_CT_PARTY:PT_ID',
  `JPT_BEAN` varchar(1024) DEFAULT NULL COMMENT 'SPRING BEAN NAME',
  `JPT_STATUS` char(1) DEFAULT NULL COMMENT 'RECORD STATUS - A (ACTIVE) : I (INACTIVE)',
  `JPT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `JPT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `JPT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `JPT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`JPT_ID`),
  CONSTRAINT `FK_CK_CT_POD_TEMPALTE_CORE_ACCN` FOREIGN KEY (`JPT_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_CT_POD_TEMPALTE_CK_CT_PARTY` FOREIGN KEY (`JPT_PRTY`) REFERENCES `T_CK_CT_PARTY` (`PTY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='POD TEMPLATE BY ACCOUNT';


INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) 
VALUES ('CLICTRUCK_SFTP_DSV', '{\"host\":\"ct2-demo.vcargocloud.com\",\"userId\":\"dsvUser\",\"password\":\"3nt3r@!\",\"path\":\"/sftpDsv/fromGuud/\",\"outpath\":\"/sftpDsv/toGuud/\"}', 'Sage Sftp config', '2023-05-05 00:00:00', 'SYS', '2023-05-05 00:00:00', 'SYS', 'A');
INSERT INTO clickargo2.T_CORE_SYSPARAM (SYS_KEY, SYS_VAL, SYS_DESC, SYS_DT_CREATE, SYS_UID_CREATE, SYS_DT_LUPD, SYS_UID_LUPD, SYS_STATUS) 
VALUES('CLICTRUCK_DSV_PATH', '/home/vcc/appAttachments/clictruck', 'dsv path', '2023-05-05 00:00:00', 'SYS', '2023-05-05 00:00:00', 'SYS', 'A');
INSERT INTO clickargo2.T_CORE_SYSPARAM (SYS_KEY, SYS_VAL, SYS_DESC, SYS_DT_CREATE, SYS_UID_CREATE, SYS_DT_LUPD, SYS_UID_LUPD, SYS_STATUS) 
VALUES('CLICTRUCK_JRXML_DSV_SEA_PATH', 'docs/DsvShipmentSeaTemplate.jrxml', 'File Report Sea', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

DROP TABLE IF EXISTS T_CK_JOB_TRUCK_EXT;

CREATE TABLE `T_CK_JOB_TRUCK_EXT` (
  `JEXT_ID` varchar(35) NOT NULL COMMENT 'JOB TRUCK EXTENSION ID - JOB_CREATED : JOB_NOT_CREATED : CONTENT_ERROR : CONTENT_EMPTY',
  `JEXT_ACCN` varchar(35) DEFAULT NULL COMMENT 'ACCOUNT - REFERENCES T_CORE_ACCN:ACCN_ID',
  `JEXT_JOB` varchar(35) DEFAULT NULL COMMENT 'TRUCK JOB - REFERENCES T_CK_JOB_TRUCK:JOB_ID',
  `JEXT_KEY` varchar(1024) NOT NULL COMMENT 'JOB EXTENSION KEY',
  `JEXT_VAL` varchar(1024) DEFAULT NULL COMMENT 'JOB EXTENSION VALUE',
  `JEXT_DESC` varchar(1024) DEFAULT NULL COMMENT 'JOB EXTENSION DESCRIPTION',
  `JEXT_STATUS` char(1) DEFAULT NULL COMMENT 'SHIPMENT STATE STATUS',
  `JEXT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `JEXT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `JEXT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `JEXT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`JEXT_ID`),
  CONSTRAINT `FK_CK_JOB_TRUCK_EXT_CORE_ACCN` FOREIGN KEY (`JEXT_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_JOB_TRUCK_EXT_CK_JOB_TRUCK` FOREIGN KEY (`JEXT_JOB`) REFERENCES `T_CK_JOB_TRUCK` (`JOB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='TRUCK JOB EXTENSION ATTRIBUTES';

DROP TABLE IF EXISTS T_CK_CT_JOB_TRIP_DELIVERY;
CREATE TABLE `T_CK_CT_JOB_TRIP_DELIVERY` (
  `JTD_ID` VARCHAR(35) NOT NULL,
  `JTD_JOB_ID` VARCHAR(45) NULL COMMENT 'JOB TRUCK ID ASSOCIATED TO THE TRIP',
  `JTD_JOB_TRIP` VARCHAR(45) NULL COMMENT 'REFERENCE TO T_CK_CT_TRIP ASSOCIATED TO THE JOB',
  `JTD_IMEI` VARCHAR(1024) NOT NULL COMMENT 'IMEI CAPTURED FROM T_CK_CT_VEH ASSOCIATED TO THE JOB',
  `JTD_DT_DELIVER` DATETIME NOT NULL COMMENT 'DATETIME THE TRIP IS MARKED AS DELIVERING',
  `JTD_DT_NOTIFIED_DELIVER` DATETIME NULL COMMENT 'DATETIME WHATSAPP NOTIFICATION IS SENT WHEN TRIP IS ABOUT TO BE DELIVERED',
  `JTD_DT_LAST_SCAN` DATETIME NULL,
  `JTD_ORIGIN_LOC` MEDIUMTEXT NOT NULL COMMENT 'GPS FROM T_CK_TRIP_LOCATION INITIAL VALUE, THIS SHOULD BE UPDATED EVERY SCHEDULER RUN',
  `JTD_DEST_LOC` MEDIUMTEXT NULL COMMENT 'GPS FROM T_CK_TRIP_LOCATION INITIAL VALUE',
  `JTD_DISTANCE` INT NULL COMMENT 'DISTANCE CAPTURED FROM AN API CALL',
  `JTD_DURATION` DOUBLE NULL COMMENT 'DURATION OF TRIP FROM/TO LOCATION',
  `JTD_DT_PRE_NOTIFY` DATETIME NULL COMMENT 'WHAT’S APP PRE-NOTIFICATION DATETIME WHEN THE DURATION IS < 30 MINUTES ARRIVING TO THE DESTINATION',
  `JTD_STATUS` VARCHAR(35) DEFAULT 'NEW' COMMENT 'NEW | DELIVERING | DROPPED OFF',
  `JTD_DT_CREATE` DATETIME NULL,
  `JTD_DT_LUPD` DATETIME NULL,
  PRIMARY KEY (`JTD_ID`));


ALTER TABLE `T_CK_CT_TRIP_LOCATION`
ADD COLUMN `TLOC_MOBILE_NO` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Mobile Number of Truck Operator' AFTER `TLOC_REMARKS`;



DROP TABLE IF EXISTS T_CK_CT_DSV_SHIPMENT;
DROP TABLE IF EXISTS T_CK_CT_SHIPMENT;

CREATE TABLE T_CK_CT_SHIPMENT (
  SH_ID varchar(35) NOT NULL COMMENT 'MESSAGE LOG ID - UUID',
  SH_MSG_ID varchar(35) DEFAULT NULL COMMENT 'MESSAGE ID - FROM Header.MessageId',
  SH_MSG_VER smallint DEFAULT NULL DEFAULT '1' COMMENT 'MESSAGE ID VERSION - NUMBER OF COUNT OF SAME SH_MSG_ID',
  SH_NAME varchar(1024) DEFAULT NULL COMMENT 'FILE NAME OF THE XML',
  SH_DT_ISSUE datetime DEFAULT NULL COMMENT 'ISSUE DATE - Header.DocumentDate.DateTime WHERE DocumentDate.Type = IssueDate',
  SH_DT_LOAD datetime DEFAULT NULL COMMENT 'DATE TIME WHERE THE XML FILE IS LOADED',
  SH_JOB varchar(35) DEFAULT NULL COMMENT 'JOB CREATED - REFERENCE T_CK_JOB:JOB_ID',
  SH_DT_JOB datetime DEFAULT NULL COMMENT 'DATE TIME WHEN JOB IS CREATED',
  SH_STATE varchar(35) DEFAULT NULL COMMENT 'SHIPMENT STATE - REFERENCES T_CK_CT_MST_SHIPMENT_STATE:ST_ID',
  SH_ERR_CODE varchar(5) DEFAULT NULL COMMENT 'ERROR OR PROCESSING CODE - NULL WHEN JOB IS CREATED',
  SH_CONTENT mediumtext COMMENT 'SHIPMENT CONTENT - XML',
  SH_SOURCE_PATH varchar(256) DEFAULT NULL COMMENT 'PATH OF THE SOURCE XML',
  SH_STATUSMESSAGE_PATH varchar(256) DEFAULT NULL COMMENT 'PATH OF THE STATUS MESSAGE XML',
  SH_REFRESH SMALLINT DEFAULT NULL COMMENT 'IS REFRESH THE RECORD',
  SH_PUSH2SFTP SMALLINT DEFAULT NULL COMMENT 'IS PUSH STATUS MESSAGE XML TO SFTP',
  SH_REMARK varchar(1024) DEFAULT NULL,
  SH_STATUS char(1) DEFAULT NULL COMMENT 'SHIPMENT STATE STATUS',
  SH_DT_CREATE datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  SH_UID_CREATE varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  SH_DT_LUPD datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  SH_UID_LUPD varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (SH_ID),
  KEY FK_CK_CT_DSV_SHIPMENT_CK_JOB (SH_JOB),
  KEY FK_CK_CT_DSV_SHIPMENT_CK_CT_MST_SHIPMENT_STATE (SH_STATE),
  KEY T_CK_CT_DSV_SHIPMENT_IDX_MSG_ID (SH_MSG_ID),
  CONSTRAINT FK_CK_CT_DSV_SHIPMENT_CK_CT_MST_SHIPMENT_STATE FOREIGN KEY (SH_STATE) REFERENCES T_CK_CT_MST_SHIPMENT_STATE (ST_ID),
  CONSTRAINT FK_CK_CT_DSV_SHIPMENT_CK_JOB FOREIGN KEY (SH_JOB) REFERENCES T_CK_JOB (JOB_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT=' SHIPMENT TABLE';



INSERT INTO T_CORE_SYSPARAM (SYS_KEY,SYS_VAL,SYS_DESC,SYS_DT_CREATE,SYS_UID_CREATE,SYS_DT_LUPD,SYS_UID_LUPD,SYS_STATUS) VALUES 
('CLICTRUCK_GOOGLE_RESCAN','5','No. in minutes to rescan the google api to get update of the distance and duration has context menu','2018-12-01 00:00:00','SYS','2018-12-01 00:00:00','SYS','A'),
('CLICTRUCK_RESEND_WA','30','No. in minutes to resend WA','2018-12-01 00:00:00','SYS','2018-12-01 00:00:00','SYS','A'),
('CLICTRUCK_DELIVERY_API_CALL','N','N for testing. Y for Actual API','2018-12-01 00:00:00','SYS','2018-12-01 00:00:00','SYS','A');
	 
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_DESTINATION_TIME_BUFFER', '30', 'TIME BUFFER IN MINUTES FOR THE ACTIVE JOB TRIP PICKUP/DROPOFF COLOR INDICATOR', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

INSERT INTO `clickargo2`.`T_CK_CT_MST_SHIPMENT_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`) 
VALUES ('JOB_CREATED', 'JOB_CREATED', 'JOB_CREATED', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_SHIPMENT_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`) 
VALUES ('JOB_UPDATED', 'JOB_UPDATED', 'JOB_UPDATED', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_SHIPMENT_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`) 
VALUES ('JOB_NOT_CREATED', 'JOB_NOT_CREATED', 'JOB_NOT_CREATED', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_SHIPMENT_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`) 
VALUES ('FAIL_TO_CREATE_JOB', 'FAIL_TO_CREATE_JOB', 'FAIL_TO_CREATE_JOB', 'A', sysdate(), 'sys');

INSERT INTO `clickargo2`.`T_CK_CT_MST_SHIPMENT_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`) 
VALUES ('NEED_NOT_CREATE_JOB', 'NEED_NOT_CREATE_JOB', 'NEED_NOT_CREATE_JOB', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_SHIPMENT_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`) 
VALUES ('CONTENT_ERROR', 'CONTENT_ERROR', 'CONTENT_ERROR', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_SHIPMENT_STATE` (`ST_ID`, `ST_NAME`, `ST_DESC`, `ST_STATUS`, `ST_DT_CREATE`, `ST_UID_CREATE`) 
VALUES ('CONTENT_EMPTY', 'CONTENT_EMPTY', 'CONTENT_EMPTY', 'A', sysdate(), 'sys');

-- ---
-- T_CK_CT_PARTY
INSERT INTO `clickargo2`.`T_CK_CT_MST_PARTY_TYPE` (`PT_ID`, `PT_NAME`, `PT_STATUS`, `PT_DT_CREATE`, `PT_UID_CREATE`) 
VALUES ('DSVOPERATOR', 'DSV OPERATOR', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_PARTY_TYPE` (`PT_ID`, `PT_NAME`, `PT_STATUS`, `PT_DT_CREATE`, `PT_UID_CREATE`) 
VALUES ('FREIGHTFORWARDER', 'FREIGHT', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_PARTY_TYPE` (`PT_ID`, `PT_NAME`, `PT_STATUS`, `PT_DT_CREATE`, `PT_UID_CREATE`) 
VALUES ('CONSIGNOR', 'CONSIGNOR', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_PARTY_TYPE` (`PT_ID`, `PT_NAME`, `PT_STATUS`, `PT_DT_CREATE`, `PT_UID_CREATE`) 
VALUES ('CONSIGNEE', 'CONSIGNEE', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_PARTY_TYPE` (`PT_ID`, `PT_NAME`, `PT_STATUS`, `PT_DT_CREATE`, `PT_UID_CREATE`) 
VALUES ('DESPATCH', 'DESPATCH', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_PARTY_TYPE` (`PT_ID`, `PT_NAME`, `PT_STATUS`, `PT_DT_CREATE`, `PT_UID_CREATE`) 
VALUES ('DELIVERY', 'DELIVERY', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_PARTY_TYPE` (`PT_ID`, `PT_NAME`, `PT_STATUS`, `PT_DT_CREATE`, `PT_UID_CREATE`) 
VALUES ('ORDERINGCUSTOMER', 'ORDERING CUSTOMER', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_PARTY_TYPE` (`PT_ID`, `PT_NAME`, `PT_STATUS`, `PT_DT_CREATE`, `PT_UID_CREATE`) 
VALUES ('AGENT', 'AGENT', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_PARTY_TYPE` (`PT_ID`, `PT_NAME`, `PT_STATUS`, `PT_DT_CREATE`, `PT_UID_CREATE`) 
VALUES ('SHIPFROM', 'SHIPFROM', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_PARTY_TYPE` (`PT_ID`, `PT_NAME`, `PT_STATUS`, `PT_DT_CREATE`, `PT_UID_CREATE`) 
VALUES ('SHIPTO', 'SHIPTO', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_PARTY_TYPE` (`PT_ID`, `PT_NAME`, `PT_STATUS`, `PT_DT_CREATE`, `PT_UID_CREATE`) 
VALUES ('DELIVERYLOCALCARTAGE', 'DELIVERY LOCAL CARTAGE', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_PARTY_TYPE` (`PT_ID`, `PT_NAME`, `PT_STATUS`, `PT_DT_CREATE`, `PT_UID_CREATE`) 
VALUES ('CONSOLIDATOR', 'CONSOLIDATOR', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_PARTY_TYPE` (`PT_ID`, `PT_NAME`, `PT_STATUS`, `PT_DT_CREATE`, `PT_UID_CREATE`) 
VALUES ('DECONSOLIDATOR', 'DE CONSOLIDATOR', 'A', sysdate(), 'sys');
INSERT INTO `clickargo2`.`T_CK_CT_MST_PARTY_TYPE` (`PT_ID`, `PT_NAME`, `PT_STATUS`, `PT_DT_CREATE`, `PT_UID_CREATE`) 
VALUES ('CARRIER', 'CARRIER', 'A', sysdate(), 'sys');

INSERT INTO `clickargo2`.`T_CK_CT_PARTY` (`PTY_ID`, `PTY_NAME`, `PTY_TYPE`, `PTY_ADDR1`, `PTY_CITY`, `PTY_STATUS`, `PTY_UID_CREATE`) 
VALUES ('DYNEX', 'DYNEX TECHNOLOGIES', 'FREIGHTFORWARDER', '14340 SULLYFIELD CIRCLE', 'CHANTILLY', 'A', 'sys');

INSERT INTO `clickargo2`.`T_CK_CT_POD_TEMPALTE` (`JPT_ID`, `JPT_PRTY`, `JPT_BEAN`, `JPT_STATUS`, `JPT_DT_CREATE`, `JPT_UID_CREATE`) 
VALUES ('DYNEX', 'DYNEX', 'podDynexService', 'A', sysdate(), 'sys');

ALTER TABLE `clickargo2`.`T_CK_CT_PARTY` 
ADD COLUMN `PTY_XML_ID` VARCHAR(70) NULL COMMENT 'ID in DSV XML file' AFTER `PTY_ID`;

/** Added Google Geocoding API and API key in sysparam. */
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_GOOGLE_GEOCODE_API', 'https://maps.googleapis.com/maps/api/geocode/json?address=', 'Google API for geocoding lookups', NOW(), 'SYS', NOW(), 'SYS', 'A');
/** Needs to here the API key in SYS_VAL for CLICTRUCK_GOOGLE_MAP_KEY once available */
INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) VALUES ('CLICTRUCK_GOOGLE_MAP_KEY', null, 'Google API key for geocoding lookups', NOW(), 'SYS', NOW(), 'SYS', 'A')
;

ALTER TABLE `clickargo2`.T_CK_CT_SHIPMENT 
ADD COLUMN SH_CONTENT_SIZE INT NULL COMMENT 'XML CONTEXT LEGNTH' AFTER `SH_CONTENT`;

ALTER TABLE `clickargo2`.T_CK_CT_SHIPMENT 
ADD COLUMN SH_STATUSMESSAGE_SIZE INT NULL COMMENT 'STATUS MESSAGE XML CONTEXT LENGTH' AFTER SH_STATUSMESSAGE_PATH;

ALTER TABLE `clickargo2`.T_CK_CT_SHIPMENT 
ADD COLUMN SH_DT_STATUSMESSAGE_ISSUE DATETIME NULL COMMENT 'STATUS MESSAGE ISSUE DATE' AFTER SH_STATUSMESSAGE_SIZE;

SET SQL_SAFE_UPDATES = 0;
delete from T_CK_CT_POD_TEMPALTE;
SET SQL_SAFE_UPDATES = 1;

INSERT INTO `clickargo2`.`T_CK_CT_POD_TEMPALTE` (`JPT_ID`, `JPT_ACCN`, `JPT_BEAN`, `JPT_STATUS`, `JPT_DT_CREATE`, `JPT_UID_CREATE`) 
VALUES ('DSV', 'DSV', 'podDsvService', 'A', sysdate(), 'sys');

INSERT INTO clickargo2.T_CORE_SYSPARAM (SYS_KEY, SYS_VAL, SYS_DESC, SYS_DT_CREATE, SYS_UID_CREATE, SYS_DT_LUPD, SYS_UID_LUPD, SYS_STATUS) 
VALUES('CLICTRUCK_JRXML_DSV_SHIPMENT_PATH', 'docs/DsvShipmentTemplate.jrxml', 'File Report', '2022-11-18 00:00:00', 'SYS', '2022-11-18 00:00:00', 'SYS', 'A');

-- NEW COLUMN TO IDENTIFY THAT THE JOB IS CREATED FROM EXCEL/XML FILE UPLOAD
ALTER TABLE `clickargo2`.`T_CK_JOB_TRUCK` 
ADD COLUMN `JOB_FROM_FILE_UPLOAD` CHAR(1) NULL AFTER `JOB_MOBILE_ENABLED`;

ALTER TABLE `clickargo2`.`T_CK_JOB_TRUCK` 
CHANGE COLUMN `JOB_FROM_FILE_UPLOAD` `JOB_FROM_FILE_UPLOAD` CHAR(1) NULL DEFAULT 'N' ;

ALTER TABLE `clickargo2`.`T_CK_JOB_TRUCK` 
CHANGE COLUMN `JOB_FROM_FILE_UPLOAD` `JOB_SOURCE` VARCHAR(256) NULL DEFAULT 'WEB' COMMENT 'SOURCE WHERE THE JOB IS CREATED FROM: WEB | XML | EXCEL | CSV | DSV_XML | DSV_CSV' ;




INSERT INTO `clickargo2`.`T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) 
VALUES ('CLICTRUCK_DSVAS_ACCN_ID', 'DSV', 'DSV Account Id', '2023-05-05 00:00:00', 'SYS', '2023-05-05 00:00:00', 'SYS', 'A');


DROP TABLE IF EXISTS T_CK_CT_SHIPMENT;

CREATE TABLE `T_CK_CT_SHIPMENT` (
  `SH_ID` varchar(35) NOT NULL COMMENT 'MESSAGE LOG ID - UUID',
  `SH_MSG_ID` varchar(35) DEFAULT NULL COMMENT 'MESSAGE ID - FROM Header.MessageId',
  `SH_MSG_VER` smallint DEFAULT '1' COMMENT 'MESSAGE ID VERSION - NUMBER OF COUNT OF SAME SH_MSG_ID',
  `SH_NAME` varchar(1024) DEFAULT NULL COMMENT 'FILE NAME OF THE XML',
  `SH_DT_ISSUE` datetime DEFAULT NULL COMMENT 'ISSUE DATE - Header.DocumentDate.DateTime WHERE DocumentDate.Type = IssueDate',
  `SH_DT_LOAD` datetime DEFAULT NULL COMMENT 'DATE TIME WHERE THE XML FILE IS LOADED',
  `SH_JOB` varchar(35) DEFAULT NULL COMMENT 'JOB CREATED - REFERENCE T_CK_JOB:JOB_ID',
  `SH_DT_JOB` datetime DEFAULT NULL COMMENT 'DATE TIME WHEN JOB IS CREATED',
  `SH_STATE` varchar(35) DEFAULT NULL COMMENT 'SHIPMENT STATE - REFERENCES T_CK_CT_MST_SHIPMENT_STATE:ST_ID',
  `SH_ERR_CODE` varchar(5) DEFAULT NULL COMMENT 'ERROR OR PROCESSING CODE - NULL WHEN JOB IS CREATED',
  `SH_CONTENT` mediumtext COMMENT 'SHIPMENT CONTENT - XML',
  `SH_CONTENT_SIZE` int DEFAULT NULL COMMENT 'XML CONTEXT LEGNTH',
  `SH_SOURCE_PATH` varchar(256) DEFAULT NULL COMMENT 'PATH OF THE SOURCE XML',
  `SH_REMARK` varchar(1024) DEFAULT NULL,
  `SH_REFRESH` smallint DEFAULT NULL COMMENT 'IS REFRESH THE RECORD',
  `SH_DIRECTION` varchar(35) DEFAULT NULL COMMENT 'IMPORT OR EXPORT',
  `SH_PROCESS_BY` varchar(35) DEFAULT NULL COMMENT 'WEB OR MOBILE, DEFAULT: WEB',
  `SH_STATUSMESSAGE_PATH` varchar(256) DEFAULT NULL COMMENT 'PATH OF THE STATUS MESSAGE XML',
  `SH_STATUSMESSAGE_SIZE` int DEFAULT NULL COMMENT 'STATUS MESSAGE XML CONTEXT LENGTH',
  `SH_STATUSMESSAGE_STATUS` smallint DEFAULT NULL COMMENT 'IS PUSH STATUS MESSAGE XML TO SFTP',
  `SH_DT_STATUSMESSAGE_CREATE` datetime DEFAULT NULL COMMENT 'STATUS MESSAGE ISSUE DATE',
  `SH_DT_STATUSMESSAGE_PUSH2SFTP` datetime DEFAULT NULL,
  `SH_STATUSMESSAGE_REMARK` varchar(1024) DEFAULT NULL,
  `SH_POD_PATH` varchar(256) DEFAULT NULL,
  `SH_POD_SIZE` int DEFAULT NULL,
  `SH_POD_STATUS` smallint DEFAULT NULL,
  `SH_DT_POD_CREATE` datetime DEFAULT NULL,
  `SH_DT_POD_EMAIL_NOTIFY` datetime DEFAULT NULL,
  `SH_POD_REMARK` varchar(1024) DEFAULT NULL,
  `SH_PHOTO_PATH` varchar(256) DEFAULT NULL,
  `SH_PHOTO_SIZE` int DEFAULT NULL,
  `SH_PHOTO_STATUS` smallint DEFAULT NULL,
  `SH_DT_PHOTO_CREATE` datetime DEFAULT NULL,
  `SH_DT_PHOTO_EMAIL_NOTIFY` datetime DEFAULT NULL,
  `SH_PHOTO_REMARK` varchar(1024) DEFAULT NULL,
  `SH_STATUS` char(1) DEFAULT NULL COMMENT 'SHIPMENT STATE STATUS',
  `SH_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `SH_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `SH_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `SH_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`SH_ID`),
  KEY `FK_CK_CT_DSV_SHIPMENT_CK_JOB` (`SH_JOB`),
  KEY `FK_CK_CT_DSV_SHIPMENT_CK_CT_MST_SHIPMENT_STATE` (`SH_STATE`),
  KEY `T_CK_CT_DSV_SHIPMENT_IDX_MSG_ID` (`SH_MSG_ID`),
  CONSTRAINT `FK_CK_CT_DSV_SHIPMENT_CK_CT_MST_SHIPMENT_STATE` FOREIGN KEY (`SH_STATE`) REFERENCES `T_CK_CT_MST_SHIPMENT_STATE` (`ST_ID`),
  CONSTRAINT `FK_CK_CT_DSV_SHIPMENT_CK_JOB` FOREIGN KEY (`SH_JOB`) REFERENCES `T_CK_JOB` (`JOB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT=' SHIPMENT TABLE';

ALTER TABLE `clickargo2`.`T_CK_JOB_TRUCK` 
ADD COLUMN `JOB_PROCESS_VIA` VARCHAR(35) NULL DEFAULT NULL COMMENT 'PROCESSED VIA WEB OR MOBILE' AFTER `JOB_SOURCE`;


ALTER TABLE `clickargo2`.`T_CK_CT_SHIPMENT` 
ADD COLUMN `SH_REPLACED` CHAR(1) NULL COMMENT 'REPLACE PREAVIOUS IF SAME SHIPMENTID' DEFAULT NULL AFTER `SH_PROCESS_BY`,
ADD COLUMN `SH_HAWB` VARCHAR(64) NULL COMMENT 'HOUSE AIR WAYBILL' AFTER `SH_REPLACED`,
ADD COLUMN `SH_MAWB` VARCHAR(64) NULL COMMENT 'MASTER AIR WAYBILL' AFTER `SH_HAWB`;


INSERT INTO `clickargo2`.`T_CK_CT_MST_VEH_TYPE` (`VHTY_ID`, `VHTY_NAME`, `VHTY_DESC`, `VHTY_DESC_OTH`, `VHTY_STATUS`, `VHTY_DT_CREATE`, `VHTY_UID_CREATE`) 
VALUES ('UNDEFINE', 'UNDEFINE', 'UNDEFINE', 'UNDEFINE', 'A', SYSDATE(), 'SYS');

INSERT INTO `T_CORE_SYSPARAM` (`SYS_KEY`, `SYS_VAL`, `SYS_DESC`, `SYS_DT_CREATE`, `SYS_UID_CREATE`, `SYS_DT_LUPD`, `SYS_UID_LUPD`, `SYS_STATUS`) 
VALUES ('CLICTRUCK_MOBILE_LOGIN_RETRIES', '3', 'Max limit login retries', now(), 'SYS', now(), 'SYS', 'A');

ALTER TABLE `clickargo2`.`T_CK_CT_TRIP_DO_ATTACH` 
ADD COLUMN `DOA_SOURCE` VARCHAR(45) NULL COMMENT 'SCHEDULER: CREATE VIA SCHEDULER, WEB: UPLOAD VIA WEB' AFTER `DOA_LOC`;

ALTER TABLE `clickargo2`.`T_CK_CT_TRIP_ATTACH` 
ADD COLUMN `AT_SOURCE` VARCHAR(45) NULL COMMENT 'MOBILE: UPLOAD VIA MOBILE, WEB: UPLOAD VIA WEB' AFTER `AT_LOC`;

