DROP VIEW IF EXISTS V_CK_CT_TRACK_LOC;

CREATE VIEW V_CK_CT_TRACK_LOC AS 
with job as (SELECT jt.*, job.JOB_SHIPMENT_TYPE, job.JOB_STATE, rd.RCD_DT_BILL_APPROVED 
	FROM clickargo2.T_CK_JOB_TRUCK jt, clickargo2.T_CK_JOB job, clickargo2.T_CK_RECORD_DATE rd
		where jt.JOB_PARENT = job.JOB_ID and job.JOB_DATES = rd.RCD_ID),
	loc as (SELECT trip.TR_JOB, trip.TR_ID, tl.TLOC_DT_LOC as SCHEDULER_TIME
		, REPLACE(trim(IFNULL(TLOC_LOC_ADDRESS, TLOC_LOC_NAME)), '\t\n', '') ADDRESS
		, tl.*, job.*
		FROM clickargo2.T_CK_CT_TRIP_LOCATION tl, clickargo2.T_CK_CT_TRIP trip, job
        where trip.TR_JOB = job.JOB_ID
			and tl.TLOC_ID = IF(job.JOB_SHIPMENT_TYPE = 'IMPORT', trip.TR_DEPO, trip.TR_TO) ),
	track as ( select TL_JOB_ID, TL_IMEI,TLI_TRIP_LOC_ID ,
			  MAX(CASE WHEN TLI_RADIUS = 10 THEN TLI_DT_ENTER END) AS TLI_DT_ENTER_10,
			  MAX(CASE WHEN TLI_RADIUS = 10 THEN TLI_DT_EXIT END) AS TLI_DT_EXIT_10,
			  MAX(CASE WHEN TLI_RADIUS = 30 THEN TLI_DT_ENTER END) AS TLI_DT_ENTER_30,
			  MAX(CASE WHEN TLI_RADIUS = 30 THEN TLI_DT_EXIT END) AS TLI_DT_EXIT_30,
			  MAX(CASE WHEN TLI_RADIUS = 100 THEN TLI_DT_ENTER END) AS TLI_DT_ENTER_100,
			  MAX(CASE WHEN TLI_RADIUS = 100 THEN TLI_DT_EXIT END) AS TLI_DT_EXIT_100
					from clickargo2.T_CK_CT_TRACK_LOC tl, clickargo2.T_CK_CT_TRACK_LOC_ITEM tli
					where tl.TL_ID = tli.TLI_TRACK_LOC_ID
					group by TL_JOB_ID, TL_IMEI, TLI_TRIP_LOC_ID )
select loc.JOB_PARTY_TO, loc.JOB_PARTY_CO_FF
	, loc.RCD_DT_BILL_APPROVED as RCD_DT_BILL_APPROVED
	, IFNULL(loc.RCD_DT_BILL_APPROVED,'') RCD_DT_BILL_APPROVED_STR
    , loc.TR_JOB
	, max(ADDRESS) ADDRESS
    ,max(SCHEDULER_TIME) as SCHEDULER_TIME
    ,max(track.TLI_DT_ENTER_10) as TLI_DT_ENTER_10
    ,max(track.TLI_DT_EXIT_10) as TLI_DT_EXIT_10
    ,max(track.TLI_DT_ENTER_30) as TLI_DT_ENTER_30
    ,max(track.TLI_DT_EXIT_30) as TLI_DT_EXIT_30
    ,max(track.TLI_DT_ENTER_100) as TLI_DT_ENTER_100
    ,max(track.TLI_DT_EXIT_100) as TLI_DT_EXIT_100
	, max(IFNULL(SCHEDULER_TIME,'')) SCHEDULER_TIME_STR
	, max(IFNULL(track.TLI_DT_ENTER_10,'')) TLI_DT_ENTER_10_STR
    , max(IFNULL(track.TLI_DT_EXIT_10,'')) TLI_DT_EXIT_10_STR
    , max(IFNULL(track.TLI_DT_ENTER_30,'')) TLI_DT_ENTER_30_STR
    , max(IFNULL(track.TLI_DT_EXIT_30,'')) TLI_DT_EXIT_30_STR
    , max(IFNULL(track.TLI_DT_ENTER_100,'')) TLI_DT_ENTER_100_STR
    , max(IFNULL(track.TLI_DT_EXIT_100,'')) TLI_DT_EXIT_100_STR
from loc left join track on track.TL_JOB_ID = loc.TR_JOB
where loc.JOB_STATE in ('APP_BILL', 'ACK_BILL')
group by loc.JOB_PARTY_TO, loc.JOB_PARTY_CO_FF, loc.RCD_DT_BILL_APPROVED, loc.TR_JOB
ORDER BY TR_JOB DESC;
;
