package com.guudint.clickargo.common.enums;

public enum ClickargoNotifTemplates {

	ACCN_REG_SUB("CKT_NTL_0016"),
	ACCN_REG_APP("CKT_NTL_0017"),
	ACCN_REG_REJ("CKT_NTL_0018"),
	ACCN_SUS_SUB("CKT_NTL_0019"),
	ACCN_SUS_APP("CKT_NTL_0020"),
	ACCN_SUS_REJ("CKT_NTL_0021"),
  	ACCN_TER_SUB("CKT_NTL_0022"),
	ACCN_TER_APP("CKT_NTL_0023"),
	ACCN_TER_REJ("CKT_NTL_0024"),
	CNTRCT_EXPIRING("CKT_NTL_0025"),
	ACCN_RESUMPT_SUB("CKT_NTL_0026"),
	ACCN_RESUMPT_APP("CKT_NTL_0027"),
	ACCN_RESUMPT_REJ("CKT_NTL_0028"),
	CONTRACT_UPDATE_REQ("CKT_NTL_0029"),
	CONTRACT_UPDATE_APP("CKT_NTL_0030"),
	CONTRACT_UPDATE_REJ("CKT_NTL_0031"),
	CONTRACT_RENEWAL_REQ("CKT_NTL_0032"),
	CONTRACT_RENEWAL_APP("CKT_NTL_0033"),
	CONTRACT_RENEWAL_REJ("CKT_NTL_0034"),
	NEW_CONTRACT_REQ("CKT_NTL_0035"),
	NEW_CONTRACT_APP("CKT_NTL_0036"),
	NEW_CONTRACT_REJ("CKT_NTL_0037"),
	RATE_TABLE_SUB("CKT_NTL_0038"),
	RATE_TABLE_VER("CKT_NTL_0039"),
	RATE_TABLE_APP("CKT_NTL_0040"),
	RATE_TABLE_REJ("CKT_NTL_0041"),
	CREDIT_LIMIT_UPDATE_SUB("CKT_NTL_0042"),
	CREDIT_LIMIT_UPDATE_APP("CKT_NTL_0043"),
	CREDIT_LIMIT_UPDATE_ACTIVE("CKT_NTL_0044"),
	CREDIT_LIMIT_UPDATE_REJ("CKT_NTL_0045"),
	JOB_TERM_SUB("CKT_NTL_0046"),
	JOB_TERM_APP("CKT_NTL_0047"),
	JOB_TERM_REJ("CKT_NTL_0048"),
	ACCN_SUS_DUE_CONTRACT_EXP("CKT_NTL_0049"),
	ACCN_SUS_DUE_UNPAID_INV("CKT_NTL_0050"),
	VEH_DISTANCE("CKT_NTL_0062"),
	VEH_EXPIRY("CKT_NTL_0062"),
	DRIVER_LICENSE("CKT_NTL_0062"),
	VPC_EXPIRY("CKT_NTL_0062"),
	INSURANCE("CKT_NTL_0062");
	
	private String id;
	
	ClickargoNotifTemplates(String id){
		this.id = id;
	}
	
	public String getId() {
		return this.id;
	}
}
