package com.guudint.clickargo.common.enums;

public enum WorkflowTypeEnum {

	ACCN_REG("ACCOUNT REGISTRATION"), 
	ACCN_SUS("ACCOUNT SUSPENSION"), 
	ACCN_RESUMPT("ACCOUNT RESUMPTION"),
	ACCN_TERM("ACCOUNT TERMINATION"), 
	CONTRACT_REQ("CONTRACT REQUEST"), 
	RATE_TABLE("RATE TABLE"), 
	JOB_TERM("JOB TERMINATE"), 
	CREDIT_LIMIT_UPDATE("CREDIT LIMIT UPDATE"),
	SVC_REG_CDC("SERVICE REGISTRATION DECLARE"),
	SVC_REG_CGP("SERVICE REGISTRATION GATEPASS"), 
	SVC_REG_CLT("SERVICE REGISTRATION CLICTRUCK"),
	VEH_DISTANCE("VEHICLE DISTANCE"),
	VEH_EXPIRY("VEHICLE EXPIRY"),
	DRIVER_LICENSE("DRIVER LICENSE"),
	VPC_EXPIRY("VPC EXPIRY"),
	INSURANCE("INSURANCE");

	private String desc;

	WorkflowTypeEnum(String desc) {
		this.desc = desc;
	}

	public String getDesc() {
		return this.desc;
	}

}
