
INSERT INTO clickargo2.T_CORE_USR_ROLE (
    UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, 
    UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, 
    UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE
) 
VALUES (
    'CKU01446', 'CKDO', 'OFFICER_FINANCE', 'N', 
    'A', SYSDATE(), 'SYS', 
    SYSDATE(), 'SYS', 'N'
);

INSERT INTO clickargo2.T_CORE_USR_ROLE (
    UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, 
    UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, 
    UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE
) 
VALUES (
    'CKU01451', 'CKDO', 'OFFICER_FINANCE', 'N', 
    'A', SYSDATE(), 'SYS', 
    SYSDATE(), 'SYS', 'N'
);

INSERT INTO clickargo2.T_CORE_USR_ROLE (
    UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, 
    UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, 
    UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE
) 
VALUES (
    'CKU01450', 'CKDO', 'OFFICER_FINANCE', 'N', 
    'A', SYSDATE(), 'SYS', 
    SYSDATE(), 'SYS', 'N'
);