package com.guudint.clickargo.clicservice.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.master.model.TCkMstServiceType;
import com.guudint.clickargo.master.model.TCkMstSvcSubState;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkSvcSub generated by hbm2java
 */
@Entity
@Table(name = "T_CK_SVC_SUB")
public class TCkSvcSub extends COAbstractEntity<TCkSvcSub> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 3084145577587641490L;
	
	// Attributes
	//////////////
	private String subId;
	private TCkMstServiceType TCkMstServiceType;
	private TCkMstSvcSubState TCkMstSvcSubState;
	private TCoreAccn TCoreAccn;
	private Date subDtStart;
	private Date subDtValid;
	private Character subAutoRenew;
	private String subUidVerify;
	private Date subDtVerify;
	private String subUidApprove;
	private Date subDtApprove;
	private Character subStatus;
	private Date subDtCreate;
	private String subUidCreate;
	private Date subDtLupd;
	private String subUidLupd;

	// Constructors
	public TCkSvcSub() {
	}

	/**
	 * @param subId
	 */
	public TCkSvcSub(String subId) {
		this.subId = subId;
	}

	/**
	 * @param subId
	 * @param TCkMstServiceType
	 * @param TCkMstSvcSubState
	 * @param TCoreAccn
	 * @param subDtStart
	 * @param subDtValid
	 * @param subAutoRenew
	 * @param subUidVerify
	 * @param subDtVerify
	 * @param subUidApprove
	 * @param subDtApprove
	 * @param subStatus
	 * @param subDtCreate
	 * @param subUidCreate
	 * @param subDtLupd
	 * @param subUidLupd
	 */
	public TCkSvcSub(String subId, TCkMstServiceType TCkMstServiceType, TCkMstSvcSubState TCkMstSvcSubState,
			TCoreAccn TCoreAccn, Date subDtStart, Date subDtValid, Character subAutoRenew, String subUidVerify,
			Date subDtVerify, String subUidApprove, Date subDtApprove, Character subStatus, Date subDtCreate,
			String subUidCreate, Date subDtLupd, String subUidLupd) {
		this.subId = subId;
		this.TCkMstServiceType = TCkMstServiceType;
		this.TCkMstSvcSubState = TCkMstSvcSubState;
		this.TCoreAccn = TCoreAccn;
		this.subDtStart = subDtStart;
		this.subDtValid = subDtValid;
		this.subAutoRenew = subAutoRenew;
		this.subUidVerify = subUidVerify;
		this.subDtVerify = subDtVerify;
		this.subUidApprove = subUidApprove;
		this.subDtApprove = subDtApprove;
		this.subStatus = subStatus;
		this.subDtCreate = subDtCreate;
		this.subUidCreate = subUidCreate;
		this.subDtLupd = subDtLupd;
		this.subUidLupd = subUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkSvcSub o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}
	
	@Override
	public String toString() {
		return "TCkSvcSub [subId=" + subId + ", TCkMstServiceType=" + TCkMstServiceType + ", TCkMstSvcSubState="
				+ TCkMstSvcSubState + ", TCoreAccn=" + TCoreAccn + ", subDtStart=" + subDtStart + ", subDtValid="
				+ subDtValid + ", subAutoRenew=" + subAutoRenew + ", subUidVerify=" + subUidVerify + ", subDtVerify="
				+ subDtVerify + ", subUidApprove=" + subUidApprove + ", subDtApprove=" + subDtApprove + ", subStatus="
				+ subStatus + ", subDtCreate=" + subDtCreate + ", subUidCreate=" + subUidCreate + ", subDtLupd="
				+ subDtLupd + ", subUidLupd=" + subUidLupd + "]";
	}

	// Properties
	//////////////
	@Id
	@Column(name = "SUB_ID", unique = true, nullable = false, length = 35)
	public String getSubId() {
		return this.subId;
	}

	public void setSubId(String subId) {
		this.subId = subId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUB_TYPE")
	public TCkMstServiceType getTCkMstServiceType() {
		return this.TCkMstServiceType;
	}

	public void setTCkMstServiceType(TCkMstServiceType TCkMstServiceType) {
		this.TCkMstServiceType = TCkMstServiceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUB_STATE")
	public TCkMstSvcSubState getTCkMstSvcSubState() {
		return this.TCkMstSvcSubState;
	}

	public void setTCkMstSvcSubState(TCkMstSvcSubState TCkMstSvcSubState) {
		this.TCkMstSvcSubState = TCkMstSvcSubState;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUB_SUBSCRIBER")
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SUB_DT_START", length = 19)
	public Date getSubDtStart() {
		return this.subDtStart;
	}

	public void setSubDtStart(Date subDtStart) {
		this.subDtStart = subDtStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SUB_DT_VALID", length = 19)
	public Date getSubDtValid() {
		return this.subDtValid;
	}

	public void setSubDtValid(Date subDtValid) {
		this.subDtValid = subDtValid;
	}

	@Column(name = "SUB_AUTO_RENEW", length = 1)
	public Character getSubAutoRenew() {
		return this.subAutoRenew;
	}

	public void setSubAutoRenew(Character subAutoRenew) {
		this.subAutoRenew = subAutoRenew;
	}

	@Column(name = "SUB_UID_VERIFY", length = 35)
	public String getSubUidVerify() {
		return this.subUidVerify;
	}

	public void setSubUidVerify(String subUidVerify) {
		this.subUidVerify = subUidVerify;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SUB_DT_VERIFY", length = 19)
	public Date getSubDtVerify() {
		return this.subDtVerify;
	}

	public void setSubDtVerify(Date subDtVerify) {
		this.subDtVerify = subDtVerify;
	}

	@Column(name = "SUB_UID_APPROVE", length = 35)
	public String getSubUidApprove() {
		return this.subUidApprove;
	}

	public void setSubUidApprove(String subUidApprove) {
		this.subUidApprove = subUidApprove;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SUB_DT_APPROVE", length = 19)
	public Date getSubDtApprove() {
		return this.subDtApprove;
	}

	public void setSubDtApprove(Date subDtApprove) {
		this.subDtApprove = subDtApprove;
	}

	@Column(name = "SUB_STATUS", length = 1)
	public Character getSubStatus() {
		return this.subStatus;
	}

	public void setSubStatus(Character subStatus) {
		this.subStatus = subStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SUB_DT_CREATE", length = 19)
	public Date getSubDtCreate() {
		return this.subDtCreate;
	}

	public void setSubDtCreate(Date subDtCreate) {
		this.subDtCreate = subDtCreate;
	}

	@Column(name = "SUB_UID_CREATE", length = 35)
	public String getSubUidCreate() {
		return this.subUidCreate;
	}

	public void setSubUidCreate(String subUidCreate) {
		this.subUidCreate = subUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SUB_DT_LUPD", length = 19)
	public Date getSubDtLupd() {
		return this.subDtLupd;
	}

	public void setSubDtLupd(Date subDtLupd) {
		this.subDtLupd = subDtLupd;
	}

	@Column(name = "SUB_UID_LUPD", length = 35)
	public String getSubUidLupd() {
		return this.subUidLupd;
	}

	public void setSubUidLupd(String subUidLupd) {
		this.subUidLupd = subUidLupd;
	}
}
