package com.guudint.clickargo.clicservice.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.master.model.TCkMstAuthState;
import com.guudint.clickargo.master.model.TCkMstServiceType;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.ccm.model.TCoreUsr;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkSvcAuth generated by hbm2java
 */
@Entity
@Table(name = "T_CK_SVC_AUTH")
public class TCkSvcAuth extends COAbstractEntity<TCkSvcAuth> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -8856087636240107315L;
	
	// Attributes
	/////////////
	private String svauId;
	private TCkMstAuthState TCkMstAuthState;
	private TCkMstServiceType TCkMstServiceType;
	private TCoreAccn TCoreAccnBySvauAccnService;
	private TCoreAccn TCoreAccnBySvauAccnAuthorizer;
	private TCoreAccn TCoreAccnBySvauAccnAuthorized;
	private TCoreUsr TCoreUsrBySvauUsrAuthorizer;
	private TCoreUsr TCoreUsrBySvauUsrAuthorized;
	private String svauPositionAuthorizer;
	private String svauPositionAuthorized;
	private Date svauDtServiceStart;
	private Date svauDtServiceValid;
	private String svauRemarksAuthorizer;
	private String svauRemarksAuthorized;
	private Character svauStatus;
	private Date svauDtCreate;
	private String svauUidCreate;
	private Date svauDtLupd;
	private String svauUidLupd;


	// Constructors
	///////////////
	public TCkSvcAuth() {
	}

	/**
	 * @param svauId
	 */
	public TCkSvcAuth(String svauId) {
		this.svauId = svauId;
	}

	/**
	 * @param svauId
	 * @param TCkMstAuthState
	 * @param TCkMstServiceType
	 * @param TCoreAccnBySvauAccnService
	 * @param TCoreAccnBySvauAccnAuthorizer
	 * @param TCoreAccnBySvauAccnAuthorized
	 * @param TCoreUsrBySvauUsrAuthorizer
	 * @param TCoreUsrBySvauUsrAuthorized
	 * @param svauPositionAuthorizer
	 * @param svauPositionAuthorized
	 * @param svauDtServiceStart
	 * @param svauDtServiceValid
	 * @param svauRemarksAuthorizer
	 * @param svauRemarksAuthorized
	 * @param svauStatus
	 * @param svauDtCreate
	 * @param svauUidCreate
	 * @param svauDtLupd
	 * @param svauUidLupd
	 */
	public TCkSvcAuth(String svauId, TCkMstAuthState TCkMstAuthState, TCkMstServiceType TCkMstServiceType,
			TCoreAccn TCoreAccnBySvauAccnService, TCoreAccn TCoreAccnBySvauAccnAuthorizer,
			TCoreAccn TCoreAccnBySvauAccnAuthorized, TCoreUsr TCoreUsrBySvauUsrAuthorizer,
			TCoreUsr TCoreUsrBySvauUsrAuthorized, String svauPositionAuthorizer, String svauPositionAuthorized,
			Date svauDtServiceStart, Date svauDtServiceValid, String svauRemarksAuthorizer,
			String svauRemarksAuthorized, Character svauStatus, Date svauDtCreate, String svauUidCreate,
			Date svauDtLupd, String svauUidLupd) {
		this.svauId = svauId;
		this.TCkMstAuthState = TCkMstAuthState;
		this.TCkMstServiceType = TCkMstServiceType;
		this.TCoreAccnBySvauAccnService = TCoreAccnBySvauAccnService;
		this.TCoreAccnBySvauAccnAuthorizer = TCoreAccnBySvauAccnAuthorizer;
		this.TCoreAccnBySvauAccnAuthorized = TCoreAccnBySvauAccnAuthorized;
		this.TCoreUsrBySvauUsrAuthorizer = TCoreUsrBySvauUsrAuthorizer;
		this.TCoreUsrBySvauUsrAuthorized = TCoreUsrBySvauUsrAuthorized;
		this.svauPositionAuthorizer = svauPositionAuthorizer;
		this.svauPositionAuthorized = svauPositionAuthorized;
		this.svauDtServiceStart = svauDtServiceStart;
		this.svauDtServiceValid = svauDtServiceValid;
		this.svauRemarksAuthorizer = svauRemarksAuthorizer;
		this.svauRemarksAuthorized = svauRemarksAuthorized;
		this.svauStatus = svauStatus;
		this.svauDtCreate = svauDtCreate;
		this.svauUidCreate = svauUidCreate;
		this.svauDtLupd = svauDtLupd;
		this.svauUidLupd = svauUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkSvcAuth o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

	
	// Properties
	/////////////
	@Id
	@Column(name = "SVAU_ID", unique = true, nullable = false, length = 35)
	public String getSvauId() {
		return this.svauId;
	}

	public void setSvauId(String svauId) {
		this.svauId = svauId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SVAU_STATE")
	public TCkMstAuthState getTCkMstAuthState() {
		return this.TCkMstAuthState;
	}

	public void setTCkMstAuthState(TCkMstAuthState TCkMstAuthState) {
		this.TCkMstAuthState = TCkMstAuthState;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SVAU_SERVICE")
	public TCkMstServiceType getTCkMstServiceType() {
		return this.TCkMstServiceType;
	}

	public void setTCkMstServiceType(TCkMstServiceType TCkMstServiceType) {
		this.TCkMstServiceType = TCkMstServiceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SVAU_ACCN_SERVICE")
	public TCoreAccn getTCoreAccnBySvauAccnService() {
		return this.TCoreAccnBySvauAccnService;
	}

	public void setTCoreAccnBySvauAccnService(TCoreAccn TCoreAccnBySvauAccnService) {
		this.TCoreAccnBySvauAccnService = TCoreAccnBySvauAccnService;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SVAU_ACCN_AUTHORIZER")
	public TCoreAccn getTCoreAccnBySvauAccnAuthorizer() {
		return this.TCoreAccnBySvauAccnAuthorizer;
	}

	public void setTCoreAccnBySvauAccnAuthorizer(TCoreAccn TCoreAccnBySvauAccnAuthorizer) {
		this.TCoreAccnBySvauAccnAuthorizer = TCoreAccnBySvauAccnAuthorizer;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SVAU_ACCN_AUTHORIZED")
	public TCoreAccn getTCoreAccnBySvauAccnAuthorized() {
		return this.TCoreAccnBySvauAccnAuthorized;
	}

	public void setTCoreAccnBySvauAccnAuthorized(TCoreAccn TCoreAccnBySvauAccnAuthorized) {
		this.TCoreAccnBySvauAccnAuthorized = TCoreAccnBySvauAccnAuthorized;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SVAU_USR_AUTHORIZER")
	public TCoreUsr getTCoreUsrBySvauUsrAuthorizer() {
		return this.TCoreUsrBySvauUsrAuthorizer;
	}

	public void setTCoreUsrBySvauUsrAuthorizer(TCoreUsr TCoreUsrBySvauUsrAuthorizer) {
		this.TCoreUsrBySvauUsrAuthorizer = TCoreUsrBySvauUsrAuthorizer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SVAU_USR_AUTHORIZED")
	public TCoreUsr getTCoreUsrBySvauUsrAuthorized() {
		return this.TCoreUsrBySvauUsrAuthorized;
	}

	public void setTCoreUsrBySvauUsrAuthorized(TCoreUsr TCoreUsrBySvauUsrAuthorized) {
		this.TCoreUsrBySvauUsrAuthorized = TCoreUsrBySvauUsrAuthorized;
	}

	@Column(name = "SVAU_POSITION_AUTHORIZER")
	public String getSvauPositionAuthorizer() {
		return this.svauPositionAuthorizer;
	}

	public void setSvauPositionAuthorizer(String svauPositionAuthorizer) {
		this.svauPositionAuthorizer = svauPositionAuthorizer;
	}

	@Column(name = "SVAU_POSITION_AUTHORIZED")
	public String getSvauPositionAuthorized() {
		return this.svauPositionAuthorized;
	}

	public void setSvauPositionAuthorized(String svauPositionAuthorized) {
		this.svauPositionAuthorized = svauPositionAuthorized;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SVAU_DT_SERVICE_START", length = 19)
	public Date getSvauDtServiceStart() {
		return this.svauDtServiceStart;
	}

	public void setSvauDtServiceStart(Date svauDtServiceStart) {
		this.svauDtServiceStart = svauDtServiceStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SVAU_DT_SERVICE_VALID", length = 19)
	public Date getSvauDtServiceValid() {
		return this.svauDtServiceValid;
	}

	public void setSvauDtServiceValid(Date svauDtServiceValid) {
		this.svauDtServiceValid = svauDtServiceValid;
	}

	@Column(name = "SVAU_REMARKS_AUTHORIZER", length = 16777215)
	public String getSvauRemarksAuthorizer() {
		return this.svauRemarksAuthorizer;
	}

	public void setSvauRemarksAuthorizer(String svauRemarksAuthorizer) {
		this.svauRemarksAuthorizer = svauRemarksAuthorizer;
	}

	@Column(name = "SVAU_REMARKS_AUTHORIZED", length = 16777215)
	public String getSvauRemarksAuthorized() {
		return this.svauRemarksAuthorized;
	}

	public void setSvauRemarksAuthorized(String svauRemarksAuthorized) {
		this.svauRemarksAuthorized = svauRemarksAuthorized;
	}

	@Column(name = "SVAU_STATUS", length = 1)
	public Character getSvauStatus() {
		return this.svauStatus;
	}

	public void setSvauStatus(Character svauStatus) {
		this.svauStatus = svauStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SVAU_DT_CREATE", length = 19)
	public Date getSvauDtCreate() {
		return this.svauDtCreate;
	}

	public void setSvauDtCreate(Date svauDtCreate) {
		this.svauDtCreate = svauDtCreate;
	}

	@Column(name = "SVAU_UID_CREATE", length = 35)
	public String getSvauUidCreate() {
		return this.svauUidCreate;
	}

	public void setSvauUidCreate(String svauUidCreate) {
		this.svauUidCreate = svauUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SVAU_DT_LUPD", length = 19)
	public Date getSvauDtLupd() {
		return this.svauDtLupd;
	}

	public void setSvauDtLupd(Date svauDtLupd) {
		this.svauDtLupd = svauDtLupd;
	}

	@Column(name = "SVAU_UID_LUPD", length = 35)
	public String getSvauUidLupd() {
		return this.svauUidLupd;
	}

	public void setSvauUidLupd(String svauUidLupd) {
		this.svauUidLupd = svauUidLupd;
	}

}
