package com.guudint.clickargo.clicservice.model;
// Generated 11 Aug 2023, 4:26:15 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.master.model.TCkMstJobState;
import com.guudint.clickargo.master.model.TCkMstServiceType;
import com.vcc.camelone.cac.model.TCoreRole;
import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.core.model.TCoreApps;
import com.vcc.camelone.master.model.TMstAccnType;

/**
 * TCkSvcActionMask generated by hbm2java
 */
@Entity
@Table(name = "T_CK_SVC_ACTION_MASK")
public class TCkSvcActionMask extends COAbstractEntity<TCkSvcActionMask> {

	private static final long serialVersionUID = 4968165547558552574L;
	private String samId;
	private TCkMstJobState TCkMstJobState;
	private TCkMstServiceType TCkMstServiceType;
	private TCoreApps TCoreApps;
	private TCoreRole TCoreRole;
	private TMstAccnType TMstAccnType;
	private Integer samMask;
	private char samStatus;
	private Date samDtCreate;
	private String samUidCreate;
	private Date samDtLupd;
	private String samUidLupd;

	public TCkSvcActionMask() {
	}

	public TCkSvcActionMask(String samId, TCkMstJobState TCkMstJobState, TCkMstServiceType TCkMstServiceType,
			TCoreApps TCoreApps, TCoreRole TCoreRole, TMstAccnType TMstAccnType, Integer samMask, char samStatus) {
		this.samId = samId;
		this.TCkMstJobState = TCkMstJobState;
		this.TCkMstServiceType = TCkMstServiceType;
		this.TCoreApps = TCoreApps;
		this.TCoreRole = TCoreRole;
		this.TMstAccnType = TMstAccnType;
		this.samMask = samMask;
		this.samStatus = samStatus;
	}

	public TCkSvcActionMask(String samId, TCkMstJobState TCkMstJobState, TCkMstServiceType TCkMstServiceType,
			TCoreApps TCoreApps, TCoreRole TCoreRole, TMstAccnType TMstAccnType, Integer samMask, char samStatus,
			Date samDtCreate, String samUidCreate, Date samDtLupd, String samUidLupd) {
		this.samId = samId;
		this.TCkMstJobState = TCkMstJobState;
		this.TCkMstServiceType = TCkMstServiceType;
		this.TCoreApps = TCoreApps;
		this.TCoreRole = TCoreRole;
		this.TMstAccnType = TMstAccnType;
		this.samMask = samMask;
		this.samStatus = samStatus;
		this.samDtCreate = samDtCreate;
		this.samUidCreate = samUidCreate;
		this.samDtLupd = samDtLupd;
		this.samUidLupd = samUidLupd;
	}

	@Id

	@Column(name = "SAM_ID", unique = true, nullable = false, length = 35)
	public String getSamId() {
		return this.samId;
	}

	public void setSamId(String samId) {
		this.samId = samId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SAM_STATE", nullable = false)
	public TCkMstJobState getTCkMstJobState() {
		return this.TCkMstJobState;
	}

	public void setTCkMstJobState(TCkMstJobState TCkMstJobState) {
		this.TCkMstJobState = TCkMstJobState;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SAM_SCV_TYPE", nullable = false)
	public TCkMstServiceType getTCkMstServiceType() {
		return this.TCkMstServiceType;
	}

	public void setTCkMstServiceType(TCkMstServiceType TCkMstServiceType) {
		this.TCkMstServiceType = TCkMstServiceType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SAM_APPS_CODE", nullable = false)
	public TCoreApps getTCoreApps() {
		return this.TCoreApps;
	}

	public void setTCoreApps(TCoreApps TCoreApps) {
		this.TCoreApps = TCoreApps;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "SAM_APPS_CODE", referencedColumnName = "ROLE_APPSCODE", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "SAM_ROLE", referencedColumnName = "ROLE_ID", nullable = false, insertable = false, updatable = false) })
	public TCoreRole getTCoreRole() {
		return this.TCoreRole;
	}

	public void setTCoreRole(TCoreRole TCoreRole) {
		this.TCoreRole = TCoreRole;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SAM_ACCN_TYPE", nullable = false)
	public TMstAccnType getTMstAccnType() {
		return this.TMstAccnType;
	}

	public void setTMstAccnType(TMstAccnType TMstAccnType) {
		this.TMstAccnType = TMstAccnType;
	}

	@Column(name = "SAM_MASK", nullable = false, columnDefinition = "BIT")
	public Integer getSamMask() {
		return this.samMask;
	}

	public void setSamMask(Integer samMask) {
		this.samMask = samMask;
	}

	@Column(name = "SAM_STATUS", nullable = false, length = 1)
	public char getSamStatus() {
		return this.samStatus;
	}

	public void setSamStatus(char samStatus) {
		this.samStatus = samStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SAM_DT_CREATE", length = 19)
	public Date getSamDtCreate() {
		return this.samDtCreate;
	}

	public void setSamDtCreate(Date samDtCreate) {
		this.samDtCreate = samDtCreate;
	}

	@Column(name = "SAM_UID_CREATE", length = 35)
	public String getSamUidCreate() {
		return this.samUidCreate;
	}

	public void setSamUidCreate(String samUidCreate) {
		this.samUidCreate = samUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SAM_DT_LUPD", length = 19)
	public Date getSamDtLupd() {
		return this.samDtLupd;
	}

	public void setSamDtLupd(Date samDtLupd) {
		this.samDtLupd = samDtLupd;
	}

	@Column(name = "SAM_UID_LUPD", length = 35)
	public String getSamUidLupd() {
		return this.samUidLupd;
	}

	public void setSamUidLupd(String samUidLupd) {
		this.samUidLupd = samUidLupd;
	}

	@Override
	public int compareTo(TCkSvcActionMask o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
