
-- . This USR_ID will start on the series CKU9xxxx and the email will be GLI0000@[company email] and the password will be the same for each for these T_CORE_USR accounts.
drop table if exists ctMigration.T_CORE_ACCN_SP;

create table ctMigration.T_CORE_ACCN_SP as SELECT ACCN_ID, ACCN_EMAIL FROM clickargo2.T_CORE_ACCN 
WHERE LOCATE('GMAIL.COM',ACCN_EMAIL) <= 0 
	AND LOCATE('CLICKARGO.COM',ACCN_EMAIL) <= 0
	AND LOCATE('YAHOO.COM',ACCN_EMAIL) <= 0 
	AND LOCATE('NOTREADY.COM',ACCN_EMAIL) <= 0 
	AND LOCATE('GLTERMINAL.COM',ACCN_EMAIL) <= 0 
	AND LOCATE('KENCANACORP.COM',ACCN_EMAIL) <= 0 
	AND LOCATE('YAHOO.CO.ID',ACCN_EMAIL) <= 0 
	AND LOCATE('SATAS.CO.ID',ACCN_EMAIL) <= 0 ;


ALTER TABLE ctMigration.T_CORE_ACCN_SP  ADD COLUMN ACCN_EMAIL_SUFFIX VARCHAR(45) NULL;
ALTER TABLE ctMigration.T_CORE_ACCN_SP  ADD COLUMN GLI_USER_ID VARCHAR(45) NULL;
ALTER TABLE ctMigration.T_CORE_ACCN_SP  ADD COLUMN GLI_USER_EMAIL VARCHAR(45) NULL;
ALTER TABLE ctMigration.T_CORE_ACCN_SP  ADD COLUMN GLI_USER_PWD VARCHAR(45) NULL;


UPDATE ctMigration.T_CORE_ACCN_SP
SET ACCN_EMAIL_SUFFIX = substring_index(ACCN_EMAIL, '@', -1);

UPDATE ctMigration.T_CORE_ACCN_SP
SET GLI_USER_EMAIL = CONCAT('GLI0000@', ACCN_EMAIL_SUFFIX);

UPDATE ctMigration.T_CORE_ACCN_SP AS c JOIN
 ( SELECT ACCN_ID, row_number() OVER (ORDER BY ACCN_ID) AS rn 
      FROM ctMigration.T_CORE_ACCN_SP
    ) AS sub
  ON  c.ACCN_ID = sub.ACCN_ID
SET c.GLI_USER_ID = concat('CKU9', lpad(sub.rn,4,'0') );

UPDATE ctMigration.T_CORE_ACCN_SP
SET GLI_USER_PWD = MD5(CONCAT(GLI_USER_ID, GLI_USER_EMAIL, '123'));

SELECT * FROM ctMigration.T_CORE_ACCN_SP;

replace into clickargo2.T_CORE_USR(USR_UID, USR_ACCNID, USR_STATUS, USR_TYPE_ONLINE, USR_TYPE_MBOX
, USR_NAME, USR_EMAIL, USR_DT_REG, USR_DT_COMM, USR_PWD, USR_DT_PWD_LUPD, USR_LOGIN_INVCNT, USR_MBOX_ID, USR_CTYCODE) 
SELECT GLI_USER_ID, ACCN_ID, 'A','Y', 'N', GLI_USER_EMAIL, GLI_USER_EMAIL, sysdate(), sysdate(), GLI_USER_PWD, sysdate(), 0, '', 'ID'
FROM ctMigration.T_CORE_ACCN_SP ;

