
CREATE table zBackup.T_CK_JOB_TRUCK_0723 as select * FROM clickargo2.T_CK_JOB_TRUCK;

-- Is JOB_TOTAL_CHARGE == total(trip charge)
create table zBackup.PATCH_TOTAL_CHARGE AS with job as (SELECT jt.*, job.JOB_STATE 
	FROM clickargo2.T_CK_JOB_TRUCK jt, clickargo2.T_CK_JOB job
		where jt.JOB_PARENT = job.JOB_ID),
	tripCharge as ( SELECT * 
		FROM clickargo2.T_CK_CT_TRIP t,  clickargo2.T_CK_CT_TRIP_CHARGE tc
		where t.TR_CHARGE = tc.TC_ID 
    )
select tripCharge.TR_JOB, JOB_TOTAL_CHARGE, JOB_TOTAL_REIMBURSEMENTS, sum(TC_PRICE) as SUM_TC_PRICE, JOB_TOTAL_CHARGE - sum(TC_PRICE), JOB_DT_CREATE
from job, tripCharge
where job.JOB_ID = tripCharge.TR_JOB and JOB_TOTAL_REIMBURSEMENTS !=0
group by tripCharge.TR_JOB
	HAVING JOB_TOTAL_CHARGE - SUM_TC_PRICE!= 0
order by JOB_DT_CREATE asc;

select * from zBackup.PATCH_TOTAL_CHARGE;

-- 1:  T_CK_JOB_TRUCK
update T_CK_JOB_TRUCK as jobTruck join zBackup.PATCH_TOTAL_CHARGE
on jobTruck.JOB_ID = PATCH_TOTAL_CHARGE.TR_JOB
set jobTruck.JOB_TOTAL_CHARGE = PATCH_TOTAL_CHARGE.SUM_TC_PRICE 
where jobTruck.JOB_TOTAL_REIMBURSEMENTS !=0;

-- 2: T_CK_CT_DEBIT_NOTE, T_CK_CT_DEBIT_NOTE_ITEM
update clickargo2.T_CK_CT_DEBIT_NOTE_ITEM dni join zBackup.PATCH_TOTAL_CHARGE
on PATCH_TOTAL_CHARGE.TR_JOB = dni.ITM_REF
set dni.ITM_UNIT_PRICE = PATCH_TOTAL_CHARGE.SUM_TC_PRICE 
where locate('trip',ITM_ITEM) > 0 ;

update clickargo2.T_CK_CT_DEBIT_NOTE_ITEM dni
set dni.ITM_AMOUNT = dni.ITM_UNIT_PRICE * dni.ITM_QTY;

update T_CK_CT_DEBIT_NOTE dn join (select ITM_DEBIT_NOTE, sum(ITM_AMOUNT) sumDnAmt from T_CK_CT_DEBIT_NOTE_ITEM group by ITM_DEBIT_NOTE) dni
on dn.DN_ID = dni.ITM_DEBIT_NOTE
set dn.DN_AMT = dni.sumDnAmt, dn.DN_TOTAL = dni.sumDnAmt;

update T_CK_CT_DEBIT_NOTE dn join zBackup.PATCH_TOTAL_CHARGE
on PATCH_TOTAL_CHARGE.TR_JOB = dn.DN_JOB_ID
set dn.DN_REFRESH = 1;

-- 3: T_CK_CT_PLATFORM_INVOICE, T_CK_CT_PLATFORM_INVOICE_ITEM
update clickargo2.T_CK_CT_PLATFORM_INVOICE_ITEM pii join zBackup.PATCH_TOTAL_CHARGE
on PATCH_TOTAL_CHARGE.TR_JOB = pii.ITM_REF
set pii.ITM_UNIT_PRICE = round(0.03* (PATCH_TOTAL_CHARGE.SUM_TC_PRICE +JOB_TOTAL_REIMBURSEMENTS))
where ITM_UNIT_PRICE != '22500.00';

update clickargo2.T_CK_CT_PLATFORM_INVOICE_ITEM pii
set pii.ITM_AMOUNT = pii.ITM_UNIT_PRICE * pii.ITM_QTY;

update T_CK_CT_PLATFORM_INVOICE inv join (select ITM_INVOICE, sum(ITM_AMOUNT) sumInvItmAmt from T_CK_CT_PLATFORM_INVOICE_ITEM group by ITM_INVOICE) pii
on inv.INV_ID = pii.ITM_INVOICE
set inv.INV_AMT = pii.sumInvItmAmt;

-- INV_REFRESH
update T_CK_CT_PLATFORM_INVOICE inv join zBackup.PATCH_TOTAL_CHARGE
on PATCH_TOTAL_CHARGE.TR_JOB = inv.INV_JOB_ID
set inv.INV_REFRESH = 1
where INV_TO = 'CK0143';

-- tax
update T_CK_CT_PLATFORM_INVOICE inv set INV_VAT = round(INV_AMT * 0.11);
-- total
update T_CK_CT_PLATFORM_INVOICE inv set INV_TOTAL = INV_AMT + INV_VAT;

-- 4: T_CK_PAYMENT_TXN
-- debit note - plaftform fee
update clickargo2.T_CK_PAYMENT_TXN set PTX_AMOUNT = '328736' 
where PTX_PAYEE = 'CK0143' and PTX_SVC_REF = 'CKCTJ2023070627553' ;


-- 5: T_CK_CREDIT_JOURNAL

update clickargo2.T_CK_CREDIT_JOURNAL cj join zBackup.PATCH_TOTAL_CHARGE
on PATCH_TOTAL_CHARGE.TR_JOB = cj.CJN_TXN_REF and  CJN_TXN_TYPE = 'JOB_PAYMENT_APPROVE'
set CJN_UTILIZED = (PATCH_TOTAL_CHARGE.SUM_TC_PRICE + PATCH_TOTAL_CHARGE.JOB_TOTAL_REIMBURSEMENTS )
where CJN_UTILIZED != 0;


update clickargo2.T_CK_CREDIT_JOURNAL cj join zBackup.PATCH_TOTAL_CHARGE
on PATCH_TOTAL_CHARGE.TR_JOB = cj.CJN_TXN_REF and  CJN_TXN_TYPE = 'JOB_PAYMENT_APPROVE'
set CJN_RESERVE = -(PATCH_TOTAL_CHARGE.SUM_TC_PRICE + PATCH_TOTAL_CHARGE.JOB_TOTAL_REIMBURSEMENTS )
where CJN_RESERVE != 0;

-- 24 July
-- forget to update T_CK_CT_PAYMENT
UPDATE `clickargo2`.`T_CK_CT_PAYMENT` SET `CTP_AMOUNT` = '340060' WHERE (`CTP_ID` = 'CTPSP2519280328674861');
UPDATE `clickargo2`.`T_CK_CT_PAYMENT` SET `CTP_AMOUNT` = '11324' WHERE (`CTP_ID` = 'CTPSP2519280335257297');


