
-- slowly, carefully, danger, patient.
/*
T_CK_CT_PLATFORM_INVOICE_ITEM, T_CK_CT_PLATFORM_INVOICE_ITEM
1: delete duplicate record, manually to delete(4 transaction)
2: update INV_STAMP_DUTY to 0; run SQL to update
3: reset INV_NO, INV_LOC, INV_SAGE_TAX_NO, ???


T_CK_CT_DEBIT_NOTE, T_CK_CT_DEBIT_NOTE_ITEM
1: delete duplicate record, manually to delete(4 transaction)
2: update DN_STAMP_DUTY to 0
3: reset DN_NO, DN_LOC
*/
--  delete by ID;
-- item:
DELETE FROM `clickargo2`.`T_CK_CT_PLATFORM_INVOICE_ITEM` WHERE (`ITM_INVOICE` = 'PFINV2023070403944');
DELETE FROM `clickargo2`.`T_CK_CT_PLATFORM_INVOICE_ITEM` WHERE (`ITM_INVOICE` = 'PFINV2023070443994');
DELETE FROM `clickargo2`.`T_CK_CT_PLATFORM_INVOICE` WHERE (`INV_ID` = 'PFINV2023070403944');
DELETE FROM `clickargo2`.`T_CK_CT_PLATFORM_INVOICE` WHERE (`INV_ID` = 'PFINV2023070443994');
--
DELETE FROM `clickargo2`.`T_CK_CT_PLATFORM_INVOICE_ITEM` WHERE (`ITM_INVOICE` = 'PFINV2023070428592');
DELETE FROM `clickargo2`.`T_CK_CT_PLATFORM_INVOICE_ITEM` WHERE (`ITM_INVOICE` = 'PFINV2023070431067');
DELETE FROM `clickargo2`.`T_CK_CT_PLATFORM_INVOICE` WHERE (`INV_ID` = 'PFINV2023070428592');
DELETE FROM `clickargo2`.`T_CK_CT_PLATFORM_INVOICE` WHERE (`INV_ID` = 'PFINV2023070431067');
--
DELETE FROM `clickargo2`.`T_CK_CT_PLATFORM_INVOICE_ITEM` WHERE (`ITM_INVOICE` = 'PFINV2023070428814');
DELETE FROM `clickargo2`.`T_CK_CT_PLATFORM_INVOICE_ITEM` WHERE (`ITM_INVOICE` = 'PFINV2023070488741');
DELETE FROM `clickargo2`.`T_CK_CT_PLATFORM_INVOICE` WHERE (`INV_ID` = 'PFINV2023070428814');
DELETE FROM `clickargo2`.`T_CK_CT_PLATFORM_INVOICE` WHERE (`INV_ID` = 'PFINV2023070488741');
--
DELETE FROM `clickargo2`.`T_CK_CT_PLATFORM_INVOICE_ITEM` WHERE (`ITM_INVOICE` = 'PFINV2023070454566');
DELETE FROM `clickargo2`.`T_CK_CT_PLATFORM_INVOICE_ITEM` WHERE (`ITM_INVOICE` = 'PFINV2023070474334');
DELETE FROM `clickargo2`.`T_CK_CT_PLATFORM_INVOICE` WHERE (`INV_ID` = 'PFINV2023070454566');
DELETE FROM `clickargo2`.`T_CK_CT_PLATFORM_INVOICE` WHERE (`INV_ID` = 'PFINV2023070474334');

-- total 
update clickargo2.T_CK_SEQUENCE_NO set SQN_SEQ = '281' where SQN_ID = 'CT_PF_INV_NO';

ALTER TABLE `clickargo2`.`T_CK_CT_PLATFORM_INVOICE` ADD COLUMN `INV_TMP_SEQ` VARCHAR(5) DEFAULT NULL AFTER `INV_UID_LUPD`;

UPDATE T_CK_CT_PLATFORM_INVOICE AS c JOIN
 ( SELECT INV_ID, row_number() OVER (ORDER BY  INV_DT_ISSUE, INV_ID) AS rn 
      FROM T_CK_CT_PLATFORM_INVOICE
    ) AS sub
  ON  c.INV_ID = sub.INV_ID
SET c.INV_TMP_SEQ = lpad(sub.rn,5,'0');

update T_CK_CT_PLATFORM_INVOICE set INV_NO = replace(INV_NO, SUBSTRING_INDEX(INV_NO, '-', -1), INV_TMP_SEQ);
-- update tax no
update T_CK_CT_PLATFORM_INVOICE set INV_SAGE_TAX_NO = concat('010.009.23.', CAST(INV_TMP_SEQ AS UNSIGNED)+ 13087857-1);

-- 
update clickargo2.T_CK_CT_PLATFORM_INVOICE set INV_STAMP_DUTY = 0;
update clickargo2.T_CK_CT_PLATFORM_INVOICE set INV_TOTAL = INV_AMT + INV_VAT;
--
DELETE FROM `clickargo2`.`T_CK_CT_DEBIT_NOTE_ITEM` WHERE (`ITM_DEBIT_NOTE` = 'DN2023070445624');
DELETE FROM `clickargo2`.`T_CK_CT_DEBIT_NOTE_ITEM` WHERE (`ITM_DEBIT_NOTE` = 'DN2023070499677');
DELETE FROM `clickargo2`.`T_CK_CT_DEBIT_NOTE` WHERE (`DN_ID` = 'DN2023070445624');
DELETE FROM `clickargo2`.`T_CK_CT_DEBIT_NOTE` WHERE (`DN_ID` = 'DN2023070499677');
--
DELETE FROM `clickargo2`.`T_CK_CT_DEBIT_NOTE_ITEM` WHERE (`ITM_DEBIT_NOTE` = 'DN2023070430730');
DELETE FROM `clickargo2`.`T_CK_CT_DEBIT_NOTE_ITEM` WHERE (`ITM_DEBIT_NOTE` = 'DN2023070439040');
DELETE FROM `clickargo2`.`T_CK_CT_DEBIT_NOTE` WHERE (`DN_ID` = 'DN2023070430730');
DELETE FROM `clickargo2`.`T_CK_CT_DEBIT_NOTE` WHERE (`DN_ID` = 'DN2023070439040');
--
DELETE FROM `clickargo2`.`T_CK_CT_DEBIT_NOTE_ITEM` WHERE (`ITM_DEBIT_NOTE` = 'DN2023070441840');
DELETE FROM `clickargo2`.`T_CK_CT_DEBIT_NOTE_ITEM` WHERE (`ITM_DEBIT_NOTE` = 'DN2023070443817');
DELETE FROM `clickargo2`.`T_CK_CT_DEBIT_NOTE` WHERE (`DN_ID` = 'DN2023070441840');
DELETE FROM `clickargo2`.`T_CK_CT_DEBIT_NOTE` WHERE (`DN_ID` = 'DN2023070443817');
--
DELETE FROM `clickargo2`.`T_CK_CT_DEBIT_NOTE_ITEM` WHERE (`ITM_DEBIT_NOTE` = 'DN2023070419469');
DELETE FROM `clickargo2`.`T_CK_CT_DEBIT_NOTE_ITEM` WHERE (`ITM_DEBIT_NOTE` = 'DN2023070439602');
DELETE FROM `clickargo2`.`T_CK_CT_DEBIT_NOTE` WHERE (`DN_ID` = 'DN2023070419469');
DELETE FROM `clickargo2`.`T_CK_CT_DEBIT_NOTE` WHERE (`DN_ID` = 'DN2023070439602');
--
update clickargo2.T_CK_CT_DEBIT_NOTE set DN_STAMP_DUTY = 0 where DN_STAMP_DUTY !=0;
update clickargo2.T_CK_CT_DEBIT_NOTE set DN_TOTAL = DN_AMT;

-- -----------------------
-- total 280 Debit Note
update clickargo2.T_CK_SEQUENCE_NO set SQN_SEQ = '281' where SQN_ID = 'CT_DN_NO';

ALTER TABLE `clickargo2`.`T_CK_CT_DEBIT_NOTE` ADD COLUMN `DIN_TMP_SEQ` VARCHAR(5) DEFAULT NULL AFTER `DN_UID_LUPD`;

UPDATE T_CK_CT_DEBIT_NOTE AS c JOIN
 ( SELECT DN_ID, row_number() OVER (ORDER BY  DN_DT_ISSUE, DN_ID) AS rn 
      FROM T_CK_CT_DEBIT_NOTE
    ) AS sub
  ON  c.DN_ID = sub.DN_ID
SET c.DIN_TMP_SEQ = lpad(sub.rn,5,'0');

update T_CK_CT_DEBIT_NOTE set DN_NO = replace(DN_NO, SUBSTRING_INDEX(DN_NO, '-', -1), DIN_TMP_SEQ)
where DN_DT_ISSUE < '2023-07-05 11:00:00';

-- -----------------------
-- backup
create table zBackup.BU_CK_CT_PLATFORM_INVOICE_ITEM SELECT * FROM clickargo2.T_CK_CT_PLATFORM_INVOICE_ITEM;
create table zBackup.BU_CK_CT_PLATFORM_INVOICE SELECT * FROM clickargo2.T_CK_CT_PLATFORM_INVOICE;

create table zBackup.BU_T_CK_CT_DEBIT_NOTE_ITEM SELECT * FROM clickargo2.T_CK_CT_DEBIT_NOTE_ITEM;
create table zBackup.BU_T_CK_CT_DEBIT_NOTE SELECT * FROM clickargo2.T_CK_CT_DEBIT_NOTE;


--  ---------------------------

-- ALTER TABLE `clickargo2`.`T_CK_CT_PLATFORM_INVOICE`
-- CHANGE COLUMN `INV_JOB_ID` `INV_JOB_ID` VARCHAR(35) NOT NULL COMMENT 'JOB ID - NO REFERENCE HERE JUST FOR QUICK JOINT' ,
-- CHANGE COLUMN `INV_TO` `INV_TO` VARCHAR(35) NOT NULL COMMENT 'INVOICE TO - REFERENCES T_CORE_ACCN:ACCN_ID' ;
 
CREATE UNIQUE INDEX uniqueIdxPlatFeeJobTo
ON clickargo2.T_CK_CT_PLATFORM_INVOICE(INV_JOB_ID, INV_TO);

 
CREATE UNIQUE INDEX uniqueIdxPlatFeeInvNo
ON clickargo2.T_CK_CT_PLATFORM_INVOICE(INV_NO);

 
CREATE UNIQUE INDEX uniqueIdxPlatFeeTaxNo
ON clickargo2.T_CK_CT_PLATFORM_INVOICE(INV_SAGE_TAX_NO);

-- ------------


