
update clickargo2.T_CK_RECORD_DATE d 
set RCD_DT_BILL_APPROVED = RCD_DT_APPROVED 
where RCD_DT_BILL_APPROVED is null and RCD_DT_APPROVED is not null;

SELECT RCD_DT_BILL_APPROVED, RCD_DT_APPROVED, d.* 
FROM clickargo2.T_CK_RECORD_DATE d
-- where RCD_DT_BILL_APPROVED is null and RCD_DT_APPROVED is not null
order by RCD_DT_BILL_APPROVED desc, RCD_DT_APPROVED desc;
-- 
create table zBackup.T_CK_RECORD_DATE_1017 SELECT * FROM clickargo2.T_CK_RECORD_DATE;
-- -----

update clickargo2.T_CK_CT_DEBIT_NOTE set DN_REFRESH = 1  where DN_STAMP_DUTY !=0;

update clickargo2.T_CK_CT_DEBIT_NOTE set DN_STAMP_DUTY = 0 where DN_STAMP_DUTY !=0;
update clickargo2.T_CK_CT_DEBIT_NOTE set DN_TOTAL = DN_AMT where DN_TOTAL != DN_AMT;

UPDATE `clickargo2`.`T_CK_PAYMENT_TXN` SET `PTX_AMOUNT` =  '9182850.00' WHERE (`PTX_ID` = 'TXNDO1318854413090143') and PTX_AMOUNT  = '9192850.00';
UPDATE `clickargo2`.`T_CK_PAYMENT_TXN` SET `PTX_AMOUNT` = '29377500.00' WHERE (`PTX_ID` = 'TXNDO1308064437805732') and PTX_AMOUNT = '29387500.00';


--
create table zBackup.BU_T_CK_CT_DEBIT_NOTE_0717 SELECT * FROM clickargo2.T_CK_CT_DEBIT_NOTE;

-- 
ALTER TABLE `clickargo2`.`T_CK_JOB_TRUCK` 
CHANGE COLUMN `JOB_TOTAL_CHARGE` `JOB_TOTAL_CHARGE` DECIMAL(15,2) NULL DEFAULT NULL COMMENT 'TOTAL JOB CHARGE (TOTAL TRIP CHARGES )' ;
