package com.guudint.clickargo.master.enums;

public enum FormActions {

	ACCEPT("JOB ACCEPTED"),
	APPROVE("JOB APPROVED"),
	ASSIGN("JOB ASSIGNED"),
	BILLJOB("JOB BILLED"),
	CANCEL("JOB CANCELLED"),
	CLONE("JOB CLONED"),
	DELETE("JOB DELETED"),
	EXIT("EXIT"),
	NEW("NEW JOB"),
	PAY("JOB PAID"),
	QUERY("JOB QUERIED"),
	REJECT("JOB REJECTED"),
	REVERIFY("JOB REVERIFIED"),
	SAVE("JOB SAVED"),
	START("JOB STARTED"),
	STOP("JOB DELIVERED"),
	VERIFY_BILL("JOB BILLING VERIFIED"),
	APPROVE_BILL("JOB BILLING APPROVED"),
	ACKNOWLEDGE_BILL("JOB BILLING ACKNOWLEDGED"),
	REJECT_BILL("JOB BILLING REJECTED"),
	SUBMIT("JOB SUBMITTED"),
	VERIFY("JOB BILLING VERIFIED"),
	WITHDRAW("JOB WITHDRAWN"),
	ACTIVATE("ACTIVATE"),
	DEACTIVATE("DEACTIVATE"),
	SUSPEND("SUSPEND"),
	RESUMPTION("RESUMPTION"),
	TERMINATE("TERMINATE"),
	MPICKUP("MPICKUP"),
	MREDO("MREDO"),
	MDELIVER("MDELIVER"),
	MDROPOFF("MDROPOFF"),
	PAUSE("PAUSE"),
	SPLIT("SPLIT");
	
	private String audit;
	
	private FormActions(String audit) {
		this.audit = audit;
	}
	
	public String getAudit() {
		return this.audit;
	}
	

}
