package com.guudint.clickargo.master.enums;

public enum Roles {

	OFFICER("OFFICER"), 
	FINANCE("SHIPPING LINE FINANCE"),
	FF_FINANCE("CO/FF FINANCE"), 
	OPERATIONS("SHIPPING LINE DOC VERIFIER"),
	ADMIN("ACCOUNT ADMINISTRATOR"), 
	FF_ADMIN("FF ADMINISTRATOR"), 
	FF_CO_ADMIN("FF-CO ADMINISTRATOR"), 
	SYS_SUPER_ADMIN("SYSTEM SUPER ADMIN"),
//	FINANCE_VERIFIER("FINANCE VERIFIER"),
//	FINANCE_APPROVER("FINANCE APPROVER"),
	// Added 06/07/2023
	OP_ADMIN("OPERATIONS ADMINISTRATOR"),
//	FINANCE_ADMIN("FINANCE ADMINISTRATOR"),
	OFFICER_FINANCE("FINANCE OFFICER"),
	SP_OP_ADMIN("SERVICE PROVIDER OPERATIONS ADMIN"),
	// 15Sep23 New user roles 
	SP_FIN_HD("FINANCE APPROVER"),
	SP_FIN_ADMIN("FINANCE VERIFIER/ADMIN"),
	SP_L1("LEVEL 1 CS"),
	SP_COM("COMMERCIAL"),
	SP_BZ_HD("BUSINESS HEAD"),
	DRIVER("DRIVER"),
	OP_ADMIN_WJ("OPERATIONS ADMINISTRATOR WITH JOB");
	

	private String desc;

	private Roles(String desc) {
		this.desc = desc;
	}

	public String getDesc() {
		return this.desc;
	}
}
