SELECT TRUCK.JOB_ID    												 AS JOB_ID,
          JOB.JOB_SHIPMENT_TYPE                                      AS SHIPMENT_TYPE,
          IFNULL(DATE_FORMAT(TRUCK.JOB_DT_BOOKING, '%Y-%m-%d'), '-') AS JOB_DT_BOOKING,
          STATE.JBST_NAME                                            AS JOB_STATE,
          COFF_ACCN.ACCN_NAME                                        AS CO_FF_ACCN,
          TO_ACCN.ACCN_NAME                                          AS TO_ACCN,
          TRIP_LOC_FROM.TLOC_LOC_NAME                                AS TLOC_LOC_NAME_FROM,
          TRIP_LOC_TO.TLOC_LOC_NAME                                  AS TLOC_LOC_NAME_TO,
          ( CASE
              WHEN TRUCK.JOB_DRV IS NOT NULL THEN (SELECT DRV.DRV_NAME FROM T_CK_CT_DRV DRV WHERE DRV.DRV_ID = TRUCK.JOB_DRV)
			  WHEN TRUCK.JOB_DRV IS NULL AND TRUCK.JOB_DRV_OTH IS NULL THEN '-'
              WHEN TRUCK.JOB_DRV IS NULL THEN SUBSTRING_INDEX(SUBSTRING_INDEX(TRUCK.JOB_DRV_OTH, 'drvName=', -1), '}', 1)
              ELSE TRUCK.JOB_DRV
            END )                                                    AS DRV_NAME,
          ( CASE
              WHEN TRUCK.JOB_VEH IS NOT NULL THEN (SELECT VEH.VH_PLATE_NO FROM T_CK_CT_VEH VEH WHERE  VEH.VH_ID = TRUCK.JOB_VEH)
			  WHEN TRUCK.JOB_VEH IS NULL AND TRUCK.JOB_VEH_OTH IS NULL THEN '-'
              WHEN TRUCK.JOB_VEH IS NULL THEN SUBSTRING_INDEX(SUBSTRING_INDEX(TRUCK.JOB_VEH_OTH, 'vhPlateNo=', -1), ',', 1)
              ELSE TRUCK.JOB_VEH
            END )                                                    AS VH_PLATE_NO,
		  ( CASE
              WHEN TRUCK.JOB_PROCESS_VIA IS NULL THEN 'WEB' ELSE TRUCK.JOB_PROCESS_VIA
            END )  AS PROCESS_VIA,
          IFNULL(DATE_FORMAT(RECORD.RCD_DT_COMPLETE, '%Y-%m-%d'), '-') AS RCD_DT_COMPLETE,
          TRIP_LOC_TO.TLOC_IS_DEVIATED AS IS_DEVIATED,
          TRIP_LOC_TO.TLOC_DEVIATION_COMMENT AS DEVIATION_COMMENT,
          TRIP_LOC_TO.TLOC_COMMENT AS DISCREPANCY_COMMENT
   FROM   T_CK_JOB_TRUCK TRUCK
          LEFT JOIN T_CK_JOB JOB
                 ON TRUCK.JOB_PARENT = JOB.JOB_ID
          LEFT JOIN T_CK_CT_TRIP TRIP
                 ON TRIP.TR_JOB = TRUCK.JOB_ID
          LEFT JOIN T_CK_CT_TRIP_LOCATION TRIP_LOC_FROM
                 ON TRIP_LOC_FROM.TLOC_ID = TRIP.TR_FROM
          LEFT JOIN T_CK_CT_TRIP_LOCATION TRIP_LOC_TO
                 ON TRIP_LOC_TO.TLOC_ID = TRIP.TR_TO
          LEFT JOIN T_CORE_ACCN COFF_ACCN
                 ON COFF_ACCN.ACCN_ID = TRUCK.JOB_PARTY_CO_FF
          LEFT JOIN T_CORE_ACCN TO_ACCN
                 ON TO_ACCN.ACCN_ID = TRUCK.JOB_PARTY_TO
          LEFT JOIN T_CK_MST_JOB_STATE STATE
                 ON JOB.JOB_STATE = STATE.JBST_ID
          LEFT JOIN T_CK_RECORD_DATE RECORD
                 ON RECORD.RCD_ID = JOB.JOB_DATES
   WHERE  
           TRUCK.JOB_PARTY_CO_FF='@ACCNID@'
			  AND JOB.JOB_STATE = 'DLV'
			  AND TRUCK.JOB_PROCESS_VIA = 'MOBILE'
			  AND DATE_FORMAT(RECORD.RCD_DT_COMPLETE, '%Y-%m-%d') >= '@FIL_RCD_DT_COMPLETE_FROM@'
			  AND DATE_FORMAT(RECORD.RCD_DT_COMPLETE, '%Y-%m-%d') <= '@FIL_RCD_DT_COMPLETE_TO@'
              AND (
				CASE WHEN '@FIL_IS_DEVIATED_CAP@' = 'N' THEN (TRIP_LOC_TO.TLOC_IS_DEVIATED = '@FIL_IS_DEVIATED_CAP@' OR TRIP_LOC_TO.TLOC_IS_DEVIATED IS NULL)
					ELSE TRIP_LOC_TO.TLOC_IS_DEVIATED = '@FIL_IS_DEVIATED_CAP@'
                END
              )
              AND (
				CASE WHEN '@FIL_HAS_DISCREPANCY_CAP@' = 'N' THEN TRIP_LOC_TO.TLOC_COMMENT IS NULL OR TRIP_LOC_TO.TLOC_COMMENT = ''
					ELSE TRIP_LOC_TO.TLOC_COMMENT IS NOT NULL OR TRIP_LOC_TO.TLOC_COMMENT <> ''
				END
              )