-- update bank Account CV WILLIAN

UPDATE clickargo2.T_CORE_ACCN_CONFIG
SET ACFG_VAL='MANDIRI:1320004757515'
WHERE ACFG_ACCNID='CK0682' AND ACFG_KEY='BANK_DETAIL';

-- enable locked user PT KINARYA MANDIRI TRANS

UPDATE clickargo2.T_CORE_USR
SET USR_STATUS='A'
WHERE USR_UID='CKU00295';