


create table zBackup.T_CK_CT_TO_PAYMENT_0828 as select * from clickargo2.T_CK_CT_TO_PAYMENT ;

UPDATE `clickargo2`.`T_CK_CT_TO_PAYMENT` SET `TOP_STATUS` = 'N' WHERE (`TOP_ID` = 'TOP2023082503182') and TOP_STATUS = 'F';
UPDATE `clickargo2`.`T_CK_CT_TO_PAYMENT` SET `TOP_STATUS` = 'N' WHERE (`TOP_ID` = 'TOP2023082593122') and TOP_STATUS = 'F';

-- updated to APP_BILL is correct, NEW is not correct.
UPDATE `clickargo2`.`T_CK_PAYMENT_TXN` SET `PTX_PAYMENT_STATE` = 'NEW' WHERE (`PTX_ID` = 'TXNDO5198771306279096') and PTX_PAYMENT_STATE = 'FAILED';
UPDATE `clickargo2`.`T_CK_PAYMENT_TXN` SET `PTX_PAYMENT_STATE` = 'NEW' WHERE (`PTX_ID` = 'TXNDO5198798208450943') and PTX_PAYMENT_STATE = 'FAILED';

