INSERT INTO `clickargo2`.`T_MST_BANK` (`BANK_ID`, `BANK_STATUS`, `BANK_DESCRIPTION`, `BANK_DESCRIPTION_OTH`, `BANK_ADDR1`, `BANK_ADDR2`, `BANK_PCODE`, `BANK_CITY`, `BANK_CTYCODE`, `BANK_TEL`, `BANK_EMAIL`, `BANK_DT_CREATE`, `BANK_UID_CREATE`, `BANK_DT_LUPD`, `BANK_UID_LUPD`, `BANK_IS_ONLINE`, `BANK_LOGO_FILE_DATA`) 
VALUES ('MNC', 'A', 'MNC', 'MNC', 'MNC', 'Jakarta 12190', '12190', 'Jakarta ', 'ID', '+62-21-52997777', 'mandiricare@bankmandiri.co.id', '2022-10-01 00:00:00', 'SYS', '2022-10-01 00:00:00', 'SYS', 'Y', null);

UPDATE `clickargo2`.`T_MST_BANK` SET `BANK_FAX` = 'BUMIIDJA' WHERE (`BANK_ID` = 'MNC');


UPDATE `clickargo2`.`T_CK_CT_TO_PAYMENT` SET `TOP_STATUS` = 'N' WHERE (`TOP_ID` = 'TOP2023081479097');
