use clickargo2;

create table zBackup.T_MST_BANK_0815 select * FROM clickargo2.T_MST_BANK c;

INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('ALLO', 'A', 'ALLO BANK INDONESIA', 'ALLO BANK INDONESIA', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'HRDAIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BAGI', 'A', 'BANK ARTHA GRAHA INTERNASIONAL', 'BANK ARTHA GRAHA INTERNASIONAL', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'ARTGIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BBA', 'A', 'BANK BUMI ARTA', 'BANK BUMI ARTA', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'BBAIIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BCAD', 'A', 'BCA Digital', 'BCA Digital', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'ROYBIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BCAS', 'A', 'BCA SYARIAH', 'BCA SYARIAH', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SYCAIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BCI', 'A', 'PT. BANK CAPITAL INDONESIA', 'PT. BANK CAPITAL INDONESIA', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'BCIAIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BDKI', 'A', 'BANK DKI', 'BANK DKI', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'BDKIIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BDKIS', 'A', 'BANK DKI SYARIAH', 'BANK DKI SYARIAH', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SYDKIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BI', 'A', 'BANK INDONESIA', 'BANK INDONESIA', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'INDOIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BIP', 'A', 'BANK INA PERDANA', 'BANK INA PERDANA', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'IAPTIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BJBS', 'A', 'BJB SYARIAH', 'BJB SYARIAH', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SYJBIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BJTM', 'A', 'BANK PEMBANGUNAN DAERAH JAWA BARAT DAN BANTEN', 'BANK PEMBANGUNAN DAERAH JAWA BARAT DAN BANTEN', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'PDJBIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BMAS', 'A', 'BANK MULTI ARTA SENTOSA', 'BANK MULTI ARTA SENTOSA', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'BMSEIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BMTP', 'A', 'PT BANK MANDIRI TASPEN POS', 'PT BANK MANDIRI TASPEN POS', 'KPO DENPASAR', 'KPO DENPASAR', 'KPO DENPASAR', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SIHBIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BPDB', 'A', 'BPD BALI', 'BPD BALI', 'PT. BPD BALI KANTOR PUSAT', 'PT. BPD BALI KANTOR PUSAT', 'PT. BPD BALI KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'ABALIDBS', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BPDDIY', 'A', 'BPD DIY', 'BPD DIY', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'PDYKIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BPDDIYS', 'A', 'BPD DIY SYARIAH', 'BPD DIY SYARIAH', 'KP SYARIAH DI YOGYAKARTA', 'KP SYARIAH DI YOGYAKARTA', 'KP SYARIAH DI YOGYAKARTA', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SYYKIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BPDJTG', 'A', 'BPD JAWA TENGAH', 'BPD JAWA TENGAH', 'KCU SEMARANG', 'KCU SEMARANG', 'KCU SEMARANG', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'PDJGIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BPDJTGS', 'A', 'BPD JAWA TENGAH SYARIAH', 'BPD JAWA TENGAH SYARIAH', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SYJGIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BPDJTM', 'A', 'BPD JAWA TIMUR', 'BPD JAWA TIMUR', 'KC JAKARTA', 'KC JAKARTA', 'KC JAKARTA', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'PDJTIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BPDJTMS', 'A', 'BPD JAWA TIMUR SYARIAH', 'BPD JAWA TIMUR SYARIAH', 'KC BANK JATIM SYARIAH', 'KC BANK JATIM SYARIAH', 'KC BANK JATIM SYARIAH', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SYJTIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BPDK', 'A', 'BPD KALBAR', 'BPD KALBAR', 'KCU PONTIANAK PUSAT', 'KCU PONTIANAK PUSAT', 'KCU PONTIANAK PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'PDKBIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BPDKS', 'A', 'BPD KALBAR SYARIAH', 'BPD KALBAR SYARIAH', 'KP SYARIAH PONTIANAK', 'KP SYARIAH PONTIANAK', 'KP SYARIAH PONTIANAK', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SYKBIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BPDKSL', 'A', 'BPD KALSEL', 'BPD KALSEL', 'BPD KALSEL CABANG UTAMA', 'BPD KALSEL CABANG UTAMA', 'BPD KALSEL CABANG UTAMA', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'PDKSIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BPDKSLS', 'A', 'BPD KALSEL SYARIAH', 'BPD KALSEL SYARIAH', 'KP SYARIAH BANJARMASIN', 'KP SYARIAH BANJARMASIN', 'KP SYARIAH BANJARMASIN', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SYKSIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BPDN', 'A', 'BPD NTT', 'BPD NTT', 'KANTOR CABANG UTAMA', 'KANTOR CABANG UTAMA', 'KANTOR CABANG UTAMA', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'PDNTIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BPDP', 'A', 'PT.BANK PEMBANGUNAN DAERAH PAPUA', 'PT.BANK PEMBANGUNAN DAERAH PAPUA', 'KANTOR CABANG UTAMA JAYAPURA', 'KANTOR CABANG UTAMA JAYAPURA', 'KANTOR CABANG UTAMA JAYAPURA', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'PDIJIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BPDRK', 'A', 'BPD RIAU KEPRI', 'BPD RIAU KEPRI', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'PDRIIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BPDSB', 'A', 'BPD SUMSEL BABEL', 'BPD SUMSEL BABEL', 'KP PALEMBANG', 'KP PALEMBANG', 'KP PALEMBANG', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'BSSPIDSP', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BPDSBS', 'A', 'BPD SUMSEL BABEL SYARIAH', 'BPD SUMSEL BABEL SYARIAH', 'KC SYARIAH PALEMBANG', 'KC SYARIAH PALEMBANG', 'KC SYARIAH PALEMBANG', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SYSSIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BSI', 'A', 'BANK SYARIAH INDONESIA', 'BANK SYARIAH INDONESIA', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'BSMDIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BSS', 'A', 'PT BANK SAHABAT SAMPOERNA', 'PT BANK SAHABAT SAMPOERNA', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'BDIPIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BTN', 'A', 'BTN', 'BTN', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'BTANIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BTNS', 'A', 'BTN SYARIAH', 'BTN SYARIAH', 'KC SYARIAH JAKARTA', 'KC SYARIAH JAKARTA', 'KC SYARIAH JAKARTA', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SYBTIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BTPN', 'A', 'BTPN', 'BTPN', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SUNIIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('BWS', 'A', 'PT BANK WOORI SAUDARA INDONESIA 1906', 'PT BANK WOORI SAUDARA INDONESIA 1906', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'BSDRIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('CIMBS', 'A', 'CIMB NIAGA SYARIAH', 'CIMB NIAGA SYARIAH', 'KC SYARIAH VICTORIA', 'KC SYARIAH VICTORIA', 'KC SYARIAH VICTORIA', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SYNAIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('CITI', 'A', 'CITIBANK NA', 'CITIBANK NA', 'KC JAKARTA', 'KC JAKARTA', 'KC JAKARTA', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'CITIIDJX', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('CTBC', 'A', 'PT BANK CTBC INDONESIA', 'PT BANK CTBC INDONESIA', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'CTCBIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('DNOS', 'A', 'BANK DANAMON SYARIAH', 'BANK DANAMON SYARIAH', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SYBDIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('GANESHA', 'A', 'GANESHA', 'GANESHA', 'KPO', 'KPO', 'KPO', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'GNESIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('HSBC', 'A', 'PT. BANK HSBC INDONESIA', 'PT. BANK HSBC INDONESIA', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'HSBCIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('ICBC', 'A', 'ICBC INDONESIA', 'ICBC INDONESIA', 'KC THE CITY TOWER', 'KC THE CITY TOWER', 'KC THE CITY TOWER', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'ICBKIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('INDEX', 'A', 'INDEX SELINDO', 'INDEX SELINDO', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'BIDXIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('JAGO', 'A', 'BANK JAGO', 'BANK JAGO', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'ATOSIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('JAGOS', 'A', 'PT. BANK JAGO TBK UNIT USAHA SYARIAH', 'PT. BANK JAGO TBK UNIT USAHA SYARIAH', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SYATIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('KEB', 'A', 'PT BANK KEB HANA INDONESIA', 'PT BANK KEB HANA INDONESIA', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'HNBNIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('KSEI', 'A', 'KUSTODIAN SENTRAL EFEK INDONESIA', 'KUSTODIAN SENTRAL EFEK INDONESIA', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'KSEIIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('MASPION', 'A', 'MASPION', 'MASPION', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'MASDIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('MAYAPADA', 'A', 'MAYAPADA', 'MAYAPADA', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'MAYAIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('MAYBANK', 'A', 'PT BANK MAYBANK INDONESIA Tbk', 'PT BANK MAYBANK INDONESIA Tbk', 'KANTOR PUSAT OPERASIONAL', 'KANTOR PUSAT OPERASIONAL', 'KANTOR PUSAT OPERASIONAL', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'IBBKIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('MAYBANKS', 'A', 'PT BANK MAYBANK INDONESIA Tbk SYARIAH', 'PT BANK MAYBANK INDONESIA Tbk SYARIAH', 'KC SYARIAH THAMRIN', 'KC SYARIAH THAMRIN', 'KC SYARIAH THAMRIN', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SYBKIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('MAYORA', 'A', 'MAYORA INDONESIA', 'MAYORA INDONESIA', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'MAYOIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('MEGA', 'A', 'MEGA', 'MEGA', 'KC JAKARTA SUDIRMAN SQUARE', 'KC JAKARTA SUDIRMAN SQUARE', 'KC JAKARTA SUDIRMAN SQUARE', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'MEGAIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('MESTIKA', 'A', 'MESTIKA DHARMA', 'MESTIKA DHARMA', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'MEDHIDS1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('MUAMMALAT', 'A', 'MUAMALAT', 'MUAMALAT', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'MUABIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('NAGARI', 'A', 'PT. BANK NAGARI - UNIT USAHA SYARIAH', 'PT. BANK NAGARI - UNIT USAHA SYARIAH', 'KCS SOLOK', 'KCS SOLOK', 'KCS SOLOK', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SYSBIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('NAGARIS', 'A', 'PT. BANK NAGARI', 'PT. BANK NAGARI', 'KCS SOLOK', 'KCS SOLOK', 'KCS SOLOK', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'PDSBIDSP', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('NEO', 'A', 'BANK NEO COMMERCE', 'BANK NEO COMMERCE', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'YUDBIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('NOBU', 'A', 'NATIONALNOBU', 'NATIONALNOBU', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'LFIBIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('OCBC', 'A', 'OCBC NISP', 'OCBC NISP', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'NISPIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('PANIN', 'A', 'PANIN', 'PANIN', 'KANTOR PUSAT OPERASIONAL', 'KANTOR PUSAT OPERASIONAL', 'KANTOR PUSAT OPERASIONAL', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'PINBIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('PERMATA', 'A', 'PERMATA', 'PERMATA', 'KC HAYAM WURUK JAKARTA', 'KC HAYAM WURUK JAKARTA', 'KC HAYAM WURUK JAKARTA', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'BBBAIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('PERMATAS', 'A', 'PERMATA SYARIAH', 'PERMATA SYARIAH', 'KCS ARTERI PDK INDAH JAKARTA', 'KCS ARTERI PDK INDAH JAKARTA', 'KCS ARTERI PDK INDAH JAKARTA', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SYBBIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('RAYA', 'A', 'BANK RAYA INDONESIA', 'BANK RAYA INDONESIA', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'AGTBIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('SEABANK', 'A', 'BANK SEABANK INDONESIA', 'BANK SEABANK INDONESIA', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'KSEBIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('SINARMAS', 'A', 'SINARMAS', 'SINARMAS', 'KANTOR PUSAT', 'KANTOR PUSAT', 'KANTOR PUSAT', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SBJKIDJA', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);
INSERT INTO T_MST_BANK
(BANK_ID, BANK_STATUS, BANK_DESCRIPTION, BANK_DESCRIPTION_OTH, BANK_ADDR1, BANK_ADDR2, BANK_ADDR3, BANK_PCODE, BANK_CITY, BANK_PROV, BANK_CTYCODE, BANK_TEL, BANK_FAX, BANK_EMAIL, BANK_DT_CREATE, BANK_UID_CREATE, BANK_DT_LUPD, BANK_UID_LUPD, BANK_IS_ONLINE, BANK_LOGO_FILE_DATA)
VALUES('SINARMASS', 'A', 'SINARMAS SYARIAH', 'SINARMAS SYARIAH', 'KCS JAKARTA-TEUKU CIK DITIRO', 'KCS JAKARTA-TEUKU CIK DITIRO', 'KCS JAKARTA-TEUKU CIK DITIRO', '10310', 'Jakarta ', 'DKI Jakarta', 'ID', '', 'SYTBIDJ1', '', NULL, 'SYS', NULL, 'SYS', 'Y', null);

update clickargo2.T_MST_BANK b
set BANK_DT_CREATE = sysdate()
where b.BANK_ID not in (select BANK_ID from zBackup.T_MST_BANK_0815);

