
-- backup
create table zBackup.BU_CK_CT_PLATFORM_INVOICE_ITEM_0810 SELECT * FROM clickargo2.T_CK_CT_PLATFORM_INVOICE_ITEM;
create table zBackup.BU_CK_CT_PLATFORM_INVOICE_0810 SELECT * FROM clickargo2.T_CK_CT_PLATFORM_INVOICE;


UPDATE clickargo2.T_CK_CT_PLATFORM_INVOICE_ITEM
SET ITM_UNIT_PRICE = '534000.00'
where ITM_INVOICE in (SELECT INV_ID FROM clickargo2.T_CK_CT_PLATFORM_INVOICE
	where INV_TO = 'CK0605' );
    
UPDATE clickargo2.T_CK_CT_PLATFORM_INVOICE_ITEM
SET ITM_UNIT_PRICE = '567000.00'
where ITM_INVOICE in (SELECT INV_ID FROM clickargo2.T_CK_CT_PLATFORM_INVOICE
	where INV_TO = 'CK0605' )
    and ITM_INVOICE = 'PFINV2023080493587';
    
update clickargo2.T_CK_CT_PLATFORM_INVOICE_ITEM set ITM_AMOUNT = round(ITM_UNIT_PRICE)
where ITM_AMOUNT != ITM_UNIT_PRICE;

-- 
update T_CK_CT_PLATFORM_INVOICE inv join (select ITM_INVOICE, sum(ITM_AMOUNT) sumInvItmAmt from T_CK_CT_PLATFORM_INVOICE_ITEM group by ITM_INVOICE) pii
on inv.INV_ID = pii.ITM_INVOICE
set inv.INV_AMT = pii.sumInvItmAmt;

-- tax
update T_CK_CT_PLATFORM_INVOICE inv set INV_VAT = round(INV_AMT * 0.11);

-- total
update T_CK_CT_PLATFORM_INVOICE inv set INV_TOTAL = INV_AMT + INV_VAT
where INV_TO = 'CK0605';

-- INV_REFRESH
update T_CK_CT_PLATFORM_INVOICE inv
set inv.INV_REFRESH = 1
where INV_TO = 'CK0605';
