insert  into clickargo2.T_CK_CREDIT_JOURNAL(CJN_ID, CJN_SERVICE_TYPE, CJN_COMPANY, CJN_TXN_TYPE
, CJN_RESERVE, CJN_UTILIZED,CJN_TXN_REF, CJN_CCY, CJN_STATUS, CJN_DT_CREATE, CJN_UID_CREATE)
	select UNIX_TIMESTAMP() +ROUND(rand()*1000), 'CLICTRUCK', ACCN_ID, 'CR_ADJUSTMENT', -19550000, 0,'CK/COM Net of Job CKCTJ2023090120040 ', 'IDR', 'A',sysdate(),'sys'
	from clickargo2.T_CORE_ACCN where ACCN_ID ='CK0210'
	UNION
	select UNIX_TIMESTAMP() +ROUND(rand()*1000), 'CLICTRUCK', ACCN_ID, 'CR_ADJUSTMENT', -7500000, 0,'CK/COM Net of Job CKCTJ2023082536271 ', 'IDR', 'A',sysdate(),'sys'
	from clickargo2.T_CORE_ACCN where ACCN_ID ='CK0210' ;