package com.guudint.clickargo.sage.model;
// Generated 23 Aug 2023, 9:52:50 am by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtMstSageIntType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_MST_SAGE_INT_TYPE")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtMstSageIntType extends COAbstractEntity<TCkCtMstSageIntType> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1L;
	
	private String sitId;
	private String sitName;
	private String sitDesc;
	private String sitDescOth;
	private Character sitStatus;
	private Date sitDtCreate;
	private String sitUidCreate;
	private Date sitDtLupd;
	private String sitUidLupd;

	public TCkCtMstSageIntType() {
	}

	public TCkCtMstSageIntType(String sitId, String sitName) {
		this.sitId = sitId;
		this.sitName = sitName;
	}

	public TCkCtMstSageIntType(String sitId, String sitName, String sitDesc, String sitDescOth, Character sitStatus,
			Date sitDtCreate, String sitUidCreate, Date sitDtLupd, String sitUidLupd) {
		this.sitId = sitId;
		this.sitName = sitName;
		this.sitDesc = sitDesc;
		this.sitDescOth = sitDescOth;
		this.sitStatus = sitStatus;
		this.sitDtCreate = sitDtCreate;
		this.sitUidCreate = sitUidCreate;
		this.sitDtLupd = sitDtLupd;
		this.sitUidLupd = sitUidLupd;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtMstSageIntType arg0) {
		return 0;
	}

	@Override
	public void init() {
	}

	@Id

	@Column(name = "SIT_ID", unique = true, nullable = false, length = 35)
	public String getSitId() {
		return this.sitId;
	}

	public void setSitId(String sitId) {
		this.sitId = sitId;
	}

	@Column(name = "SIT_NAME", nullable = false, length = 100)
	public String getSitName() {
		return this.sitName;
	}

	public void setSitName(String sitName) {
		this.sitName = sitName;
	}

	@Column(name = "SIT_DESC")
	public String getSitDesc() {
		return this.sitDesc;
	}

	public void setSitDesc(String sitDesc) {
		this.sitDesc = sitDesc;
	}

	@Column(name = "SIT_DESC_OTH", length = 512)
	public String getSitDescOth() {
		return this.sitDescOth;
	}

	public void setSitDescOth(String sitDescOth) {
		this.sitDescOth = sitDescOth;
	}

	@Column(name = "SIT_STATUS", length = 1)
	public Character getSitStatus() {
		return this.sitStatus;
	}

	public void setSitStatus(Character sitStatus) {
		this.sitStatus = sitStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SIT_DT_CREATE", length = 19)
	public Date getSitDtCreate() {
		return this.sitDtCreate;
	}

	public void setSitDtCreate(Date sitDtCreate) {
		this.sitDtCreate = sitDtCreate;
	}

	@Column(name = "SIT_UID_CREATE", length = 35)
	public String getSitUidCreate() {
		return this.sitUidCreate;
	}

	public void setSitUidCreate(String sitUidCreate) {
		this.sitUidCreate = sitUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SIT_DT_LUPD", length = 19)
	public Date getSitDtLupd() {
		return this.sitDtLupd;
	}

	public void setSitDtLupd(Date sitDtLupd) {
		this.sitDtLupd = sitDtLupd;
	}

	@Column(name = "SIT_UID_LUPD", length = 35)
	public String getSitUidLupd() {
		return this.sitUidLupd;
	}

	public void setSitUidLupd(String sitUidLupd) {
		this.sitUidLupd = sitUidLupd;
	}

}
