package com.guudint.clickargo.sage.model;
// Generated 23 Aug 2023, 9:52:50 am by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtMstSageIntState generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_MST_SAGE_INT_STATE")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkCtMstSageIntState extends COAbstractEntity<TCkCtMstSageIntState> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1L;
	
	private String sisId;
	private String sisName;
	private String sisDesc;
	private String sisDescOth;
	private Character sisStatus;
	private Date sisDtCreate;
	private String sisUidCreate;
	private Date sisDtLupd;
	private String sisUidLupd;

	public TCkCtMstSageIntState() {
	}

	public TCkCtMstSageIntState(String sisId) {
		this.sisId = sisId;
	}

	public TCkCtMstSageIntState(String sisId, String sisName) {
		this.sisId = sisId;
		this.sisName = sisName;
	}

	public TCkCtMstSageIntState(String sisId, String sisName, String sisDesc, String sisDescOth, Character sisStatus,
			Date sisDtCreate, String sisUidCreate, Date sisDtLupd, String sisUidLupd) {
		this.sisId = sisId;
		this.sisName = sisName;
		this.sisDesc = sisDesc;
		this.sisDescOth = sisDescOth;
		this.sisStatus = sisStatus;
		this.sisDtCreate = sisDtCreate;
		this.sisUidCreate = sisUidCreate;
		this.sisDtLupd = sisDtLupd;
		this.sisUidLupd = sisUidLupd;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtMstSageIntState arg0) {
		return 0;
	}

	@Override
	public void init() {
	}

	@Id

	@Column(name = "SIS_ID", unique = true, nullable = false, length = 35)
	public String getSisId() {
		return this.sisId;
	}

	public void setSisId(String sisId) {
		this.sisId = sisId;
	}

	@Column(name = "SIS_NAME", nullable = false, length = 100)
	public String getSisName() {
		return this.sisName;
	}

	public void setSisName(String sisName) {
		this.sisName = sisName;
	}

	@Column(name = "SIS_DESC")
	public String getSisDesc() {
		return this.sisDesc;
	}

	public void setSisDesc(String sisDesc) {
		this.sisDesc = sisDesc;
	}

	@Column(name = "SIS_DESC_OTH", length = 512)
	public String getSisDescOth() {
		return this.sisDescOth;
	}

	public void setSisDescOth(String sisDescOth) {
		this.sisDescOth = sisDescOth;
	}

	@Column(name = "SIS_STATUS", length = 1)
	public Character getSisStatus() {
		return this.sisStatus;
	}

	public void setSisStatus(Character sisStatus) {
		this.sisStatus = sisStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SIS_DT_CREATE", length = 19)
	public Date getSisDtCreate() {
		return this.sisDtCreate;
	}

	public void setSisDtCreate(Date sisDtCreate) {
		this.sisDtCreate = sisDtCreate;
	}

	@Column(name = "SIS_UID_CREATE", length = 35)
	public String getSisUidCreate() {
		return this.sisUidCreate;
	}

	public void setSisUidCreate(String sisUidCreate) {
		this.sisUidCreate = sisUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SIS_DT_LUPD", length = 19)
	public Date getSisDtLupd() {
		return this.sisDtLupd;
	}

	public void setSisDtLupd(Date sisDtLupd) {
		this.sisDtLupd = sisDtLupd;
	}

	@Column(name = "SIS_UID_LUPD", length = 35)
	public String getSisUidLupd() {
		return this.sisUidLupd;
	}

	public void setSisUidLupd(String sisUidLupd) {
		this.sisUidLupd = sisUidLupd;
	}
}
