package com.guudint.clickargo.sage.model;
// Generated 23 Aug 2023, 9:52:50 am by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.guudint.clickargo.master.model.TCkMstServiceType;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkSageIntegration generated by hbm2java
 */
@Entity
@Table(name = "T_CK_SAGE_INTEGRATION")
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler", "fieldHandler" })
public class TCkSageIntegration extends COAbstractEntity<TCkSageIntegration> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1L;
	public static final String PREFIX_ID = "SINT";
	
	private String sintId;
	private TCkCtMstSageIntState TCkCtMstSageIntState;
	private TCkCtMstSageIntType TCkCtMstSageIntType;
	private TCkMstServiceType TCkMstServiceType;
	private Date sintDtStart;
	private Date sintDtEnd;
	private Integer sintNoRecords;
	private Integer sintNoSuccess;
	private Integer sintNoFail;
	private Date sintDtExport;
	private Date sintDtImport;
	private String sintLocExport;
	private String sintLocImport;
	private Character sintStatus;
	private Date sintDtCreate;
	private String sintUidCreate;
	private Date sintDtLupd;
	private String sintUidLupd;

	public TCkSageIntegration() {
	}

	public TCkSageIntegration(String sintId, TCkCtMstSageIntState TCkCtMstSageIntState) {
		this.sintId = sintId;
		this.TCkCtMstSageIntState = TCkCtMstSageIntState;
	}

	public TCkSageIntegration(String sintId, TCkCtMstSageIntState TCkCtMstSageIntState,
			TCkCtMstSageIntType TCkCtMstSageIntType, TCkMstServiceType TCkMstServiceType, Date sintDtStart,
			Date sintDtEnd, Integer sintNoRecords, Integer sintNoSuccess, Integer sintNoFail, Date sintDtExport,
			Date sintDtImport, String sintLocExport, String sintLocImport, Character sintStatus, Date sintDtCreate,
			String sintUidCreate, Date sintDtLupd, String sintUidLupd) {
		this.sintId = sintId;
		this.TCkCtMstSageIntState = TCkCtMstSageIntState;
		this.TCkCtMstSageIntType = TCkCtMstSageIntType;
		this.TCkMstServiceType = TCkMstServiceType;
		this.sintDtStart = sintDtStart;
		this.sintDtEnd = sintDtEnd;
		this.sintNoRecords = sintNoRecords;
		this.sintNoSuccess = sintNoSuccess;
		this.sintNoFail = sintNoFail;
		this.sintDtExport = sintDtExport;
		this.sintDtImport = sintDtImport;
		this.sintLocExport = sintLocExport;
		this.sintLocImport = sintLocImport;
		this.sintStatus = sintStatus;
		this.sintDtCreate = sintDtCreate;
		this.sintUidCreate = sintUidCreate;
		this.sintDtLupd = sintDtLupd;
		this.sintUidLupd = sintUidLupd;
	}

	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkSageIntegration arg0) {
		return 0;
	}

	@Override
	public void init() {
	}

	@Id

	@Column(name = "SINT_ID", unique = true, nullable = false, length = 35)
	public String getSintId() {
		return this.sintId;
	}

	public void setSintId(String sintId) {
		this.sintId = sintId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SINT_STATE", nullable = false)
	public TCkCtMstSageIntState getTCkCtMstSageIntState() {
		return this.TCkCtMstSageIntState;
	}

	public void setTCkCtMstSageIntState(TCkCtMstSageIntState TCkCtMstSageIntState) {
		this.TCkCtMstSageIntState = TCkCtMstSageIntState;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SINT_INT_TYPE")
	public TCkCtMstSageIntType getTCkCtMstSageIntType() {
		return this.TCkCtMstSageIntType;
	}

	public void setTCkCtMstSageIntType(TCkCtMstSageIntType TCkCtMstSageIntType) {
		this.TCkCtMstSageIntType = TCkCtMstSageIntType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SINT_SVC")
	public TCkMstServiceType getTCkMstServiceType() {
		return this.TCkMstServiceType;
	}

	public void setTCkMstServiceType(TCkMstServiceType TCkMstServiceType) {
		this.TCkMstServiceType = TCkMstServiceType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SINT_DT_START", length = 19)
	public Date getSintDtStart() {
		return this.sintDtStart;
	}

	public void setSintDtStart(Date sintDtStart) {
		this.sintDtStart = sintDtStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SINT_DT_END", length = 19)
	public Date getSintDtEnd() {
		return this.sintDtEnd;
	}

	public void setSintDtEnd(Date sintDtEnd) {
		this.sintDtEnd = sintDtEnd;
	}

	@Column(name = "SINT_NO_RECORDS")
	public Integer getSintNoRecords() {
		return this.sintNoRecords;
	}

	public void setSintNoRecords(Integer sintNoRecords) {
		this.sintNoRecords = sintNoRecords;
	}

	@Column(name = "SINT_NO_SUCCESS")
	public Integer getSintNoSuccess() {
		return this.sintNoSuccess;
	}

	public void setSintNoSuccess(Integer sintNoSuccess) {
		this.sintNoSuccess = sintNoSuccess;
	}

	@Column(name = "SINT_NO_FAIL")
	public Integer getSintNoFail() {
		return this.sintNoFail;
	}

	public void setSintNoFail(Integer sintNoFail) {
		this.sintNoFail = sintNoFail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SINT_DT_EXPORT", length = 19)
	public Date getSintDtExport() {
		return this.sintDtExport;
	}

	public void setSintDtExport(Date sintDtExport) {
		this.sintDtExport = sintDtExport;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SINT_DT_IMPORT", length = 19)
	public Date getSintDtImport() {
		return this.sintDtImport;
	}

	public void setSintDtImport(Date sintDtImport) {
		this.sintDtImport = sintDtImport;
	}

	@Column(name = "SINT_LOC_EXPORT", length = 1024)
	public String getSintLocExport() {
		return this.sintLocExport;
	}

	public void setSintLocExport(String sintLocExport) {
		this.sintLocExport = sintLocExport;
	}

	@Column(name = "SINT_LOC_IMPORT", length = 1024)
	public String getSintLocImport() {
		return this.sintLocImport;
	}

	public void setSintLocImport(String sintLocImport) {
		this.sintLocImport = sintLocImport;
	}

	@Column(name = "SINT_STATUS", length = 1)
	public Character getSintStatus() {
		return this.sintStatus;
	}

	public void setSintStatus(Character sintStatus) {
		this.sintStatus = sintStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SINT_DT_CREATE", length = 19)
	public Date getSintDtCreate() {
		return this.sintDtCreate;
	}

	public void setSintDtCreate(Date sintDtCreate) {
		this.sintDtCreate = sintDtCreate;
	}

	@Column(name = "SINT_UID_CREATE", length = 35)
	public String getSintUidCreate() {
		return this.sintUidCreate;
	}

	public void setSintUidCreate(String sintUidCreate) {
		this.sintUidCreate = sintUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SINT_DT_LUPD", length = 19)
	public Date getSintDtLupd() {
		return this.sintDtLupd;
	}

	public void setSintDtLupd(Date sintDtLupd) {
		this.sintDtLupd = sintDtLupd;
	}

	@Column(name = "SINT_UID_LUPD", length = 35)
	public String getSintUidLupd() {
		return this.sintUidLupd;
	}

	public void setSintUidLupd(String sintUidLupd) {
		this.sintUidLupd = sintUidLupd;
	}

}
