package com.guudint.clickargo.master.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstJobState generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_JOB_STATE")
public class TCkMstJobState extends COAbstractEntity<TCkMstJobState> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -511317347528661860L;
	
	// Attributes
	/////////////
	private String jbstId;
	private String jbstName;
	private String jbstDesc;
	private String jbstDescOth;
	private Character jbstStatus;
	private Date jbstDtCreate;
	private String jbstUidCreate;
	private Date jbstDtLupd;
	private String jbstUidLupd;

	// Constructors
	////////////////
	public TCkMstJobState() {
	}

	/**
	 * @param jbstId
	 * @param jbstName
	 */
	public TCkMstJobState(String jbstId, String jbstName) {
		this.jbstId = jbstId;
		this.jbstName = jbstName;
	}

	/**
	 * @param jbstId
	 * @param jbstName
	 * @param jbstDesc
	 * @param jbstDescOth
	 * @param jbstStatus
	 * @param jbstDtCreate
	 * @param jbstUidCreate
	 * @param jbstDtLupd
	 * @param jbstUidLupd
	 */
	public TCkMstJobState(String jbstId, String jbstName, String jbstDesc, String jbstDescOth, Character jbstStatus,
			Date jbstDtCreate, String jbstUidCreate, Date jbstDtLupd, String jbstUidLupd) {
		this.jbstId = jbstId;
		this.jbstName = jbstName;
		this.jbstDesc = jbstDesc;
		this.jbstDescOth = jbstDescOth;
		this.jbstStatus = jbstStatus;
		this.jbstDtCreate = jbstDtCreate;
		this.jbstUidCreate = jbstUidCreate;
		this.jbstDtLupd = jbstDtLupd;
		this.jbstUidLupd = jbstUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 *      
	 */
	public int compareTo(TCkMstJobState o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 *      
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

	// Properties
	/////////////
	@Id
	@Column(name = "JBST_ID", unique = true, nullable = false, length = 35)
	public String getJbstId() {
		return this.jbstId;
	}

	public void setJbstId(String jbstId) {
		this.jbstId = jbstId;
	}

	@Column(name = "JBST_NAME", nullable = false, length = 100)
	public String getJbstName() {
		return this.jbstName;
	}

	public void setJbstName(String jbstName) {
		this.jbstName = jbstName;
	}

	@Column(name = "JBST_DESC")
	public String getJbstDesc() {
		return this.jbstDesc;
	}

	public void setJbstDesc(String jbstDesc) {
		this.jbstDesc = jbstDesc;
	}

	@Column(name = "JBST_DESC_OTH", length = 512)
	public String getJbstDescOth() {
		return this.jbstDescOth;
	}

	public void setJbstDescOth(String jbstDescOth) {
		this.jbstDescOth = jbstDescOth;
	}

	@Column(name = "JBST_STATUS", length = 1)
	public Character getJbstStatus() {
		return this.jbstStatus;
	}

	public void setJbstStatus(Character jbstStatus) {
		this.jbstStatus = jbstStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JBST_DT_CREATE", length = 19)
	public Date getJbstDtCreate() {
		return this.jbstDtCreate;
	}

	public void setJbstDtCreate(Date jbstDtCreate) {
		this.jbstDtCreate = jbstDtCreate;
	}

	@Column(name = "JBST_UID_CREATE", length = 35)
	public String getJbstUidCreate() {
		return this.jbstUidCreate;
	}

	public void setJbstUidCreate(String jbstUidCreate) {
		this.jbstUidCreate = jbstUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JBST_DT_LUPD", length = 19)
	public Date getJbstDtLupd() {
		return this.jbstDtLupd;
	}

	public void setJbstDtLupd(Date jbstDtLupd) {
		this.jbstDtLupd = jbstDtLupd;
	}

	@Column(name = "JBST_UID_LUPD", length = 35)
	public String getJbstUidLupd() {
		return this.jbstUidLupd;
	}

	public void setJbstUidLupd(String jbstUidLupd) {
		this.jbstUidLupd = jbstUidLupd;
	}

}
