package com.guudint.clickargo.master.model;
// Generated 6 Dec, 2022 12:37:38 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstDoPartyType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_DO_PARTY_TYPE")
public class TCkMstDoPartyType extends COAbstractEntity<TCkMstDoPartyType> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -113774920317902403L;

	// Attributes
	/////////////
	private String doptId;
	private String doptName;
	private String doptDesc;
	private String doptDescOth;
	private Character doptStatus;
	private Date doptDtCreate;
	private String doptUidCreate;
	private Date doptDtLupd;
	private String doptUidLupd;

	// Constructors
	///////////////
	public TCkMstDoPartyType() {
	}

	/**
	 * @param doptId
	 * @param doptName
	 */
	public TCkMstDoPartyType(String doptId, String doptName) {
		this.doptId = doptId;
		this.doptName = doptName;
	}

	/**
	 * @param doptId
	 * @param doptName
	 * @param doptDesc
	 * @param doptDescOth
	 * @param doptStatus
	 * @param doptDtCreate
	 * @param doptUidCreate
	 * @param doptDtLupd
	 * @param doptUidLupd
	 */
	public TCkMstDoPartyType(String doptId, String doptName, String doptDesc, String doptDescOth, Character doptStatus,
			Date doptDtCreate, String doptUidCreate, Date doptDtLupd, String doptUidLupd) {
		this.doptId = doptId;
		this.doptName = doptName;
		this.doptDesc = doptDesc;
		this.doptDescOth = doptDescOth;
		this.doptStatus = doptStatus;
		this.doptDtCreate = doptDtCreate;
		this.doptUidCreate = doptUidCreate;
		this.doptDtLupd = doptDtLupd;
		this.doptUidLupd = doptUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkMstDoPartyType o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	// Properties
	/////////////
	@Id
	@Column(name = "DOPT_ID", unique = true, nullable = false, length = 35)
	public String getDoptId() {
		return this.doptId;
	}

	public void setDoptId(String doptId) {
		this.doptId = doptId;
	}

	@Column(name = "DOPT_NAME", nullable = false, length = 100)
	public String getDoptName() {
		return this.doptName;
	}

	public void setDoptName(String doptName) {
		this.doptName = doptName;
	}

	@Column(name = "DOPT_DESC")
	public String getDoptDesc() {
		return this.doptDesc;
	}

	public void setDoptDesc(String doptDesc) {
		this.doptDesc = doptDesc;
	}

	@Column(name = "DOPT_DESC_OTH", length = 512)
	public String getDoptDescOth() {
		return this.doptDescOth;
	}

	public void setDoptDescOth(String doptDescOth) {
		this.doptDescOth = doptDescOth;
	}

	@Column(name = "DOPT_STATUS", length = 1)
	public Character getDoptStatus() {
		return this.doptStatus;
	}

	public void setDoptStatus(Character doptStatus) {
		this.doptStatus = doptStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DOPT_DT_CREATE", length = 19)
	public Date getDoptDtCreate() {
		return this.doptDtCreate;
	}

	public void setDoptDtCreate(Date doptDtCreate) {
		this.doptDtCreate = doptDtCreate;
	}

	@Column(name = "DOPT_UID_CREATE", length = 35)
	public String getDoptUidCreate() {
		return this.doptUidCreate;
	}

	public void setDoptUidCreate(String doptUidCreate) {
		this.doptUidCreate = doptUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DOPT_DT_LUPD", length = 19)
	public Date getDoptDtLupd() {
		return this.doptDtLupd;
	}

	public void setDoptDtLupd(Date doptDtLupd) {
		this.doptDtLupd = doptDtLupd;
	}

	@Column(name = "DOPT_UID_LUPD", length = 35)
	public String getDoptUidLupd() {
		return this.doptUidLupd;
	}

	public void setDoptUidLupd(String doptUidLupd) {
		this.doptUidLupd = doptUidLupd;
	}
}
