package com.guudint.clickargo.master.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstJobType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_JOB_TYPE")
public class TCkMstJobType extends COAbstractEntity<TCkMstJobType> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -2405736611924834422L;
	
	// Attributes
	//////////////
	private String jbtId;
	private String jbtName;
	private String jbtDesc;
	private String jbtDescOth;
	private Character jbtStatus;
	private Date jbtDtCreate;
	private String jbtUidCreate;
	private Date jbtDtLupd;
	private String jbtUidLupd;

	// Constructors
	///////////////
	public TCkMstJobType() {
	}

	/**
	 * @param jbtId
	 * @param jbtName
	 */
	public TCkMstJobType(String jbtId, String jbtName) {
		this.jbtId = jbtId;
		this.jbtName = jbtName;
	}

	/**
	 * @param jbtId
	 * @param jbtName
	 * @param jbtDesc
	 * @param jbtDescOth
	 * @param jbtStatus
	 * @param jbtDtCreate
	 * @param jbtUidCreate
	 * @param jbtDtLupd
	 * @param jbtUidLupd
	 */
	public TCkMstJobType(String jbtId, String jbtName, String jbtDesc, String jbtDescOth, Character jbtStatus,
			Date jbtDtCreate, String jbtUidCreate, Date jbtDtLupd, String jbtUidLupd) {
		this.jbtId = jbtId;
		this.jbtName = jbtName;
		this.jbtDesc = jbtDesc;
		this.jbtDescOth = jbtDescOth;
		this.jbtStatus = jbtStatus;
		this.jbtDtCreate = jbtDtCreate;
		this.jbtUidCreate = jbtUidCreate;
		this.jbtDtLupd = jbtDtLupd;
		this.jbtUidLupd = jbtUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 *      
	 */
	public int compareTo(TCkMstJobType o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 *      
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}
	
	// Properties
	/////////////
	@Id
	@Column(name = "JBT_ID", unique = true, nullable = false, length = 35)
	public String getJbtId() {
		return this.jbtId;
	}

	public void setJbtId(String jbtId) {
		this.jbtId = jbtId;
	}

	@Column(name = "JBT_NAME", nullable = false, length = 100)
	public String getJbtName() {
		return this.jbtName;
	}

	public void setJbtName(String jbtName) {
		this.jbtName = jbtName;
	}

	@Column(name = "JBT_DESC")
	public String getJbtDesc() {
		return this.jbtDesc;
	}

	public void setJbtDesc(String jbtDesc) {
		this.jbtDesc = jbtDesc;
	}

	@Column(name = "JBT_DESC_OTH", length = 512)
	public String getJbtDescOth() {
		return this.jbtDescOth;
	}

	public void setJbtDescOth(String jbtDescOth) {
		this.jbtDescOth = jbtDescOth;
	}

	@Column(name = "JBT_STATUS", length = 1)
	public Character getJbtStatus() {
		return this.jbtStatus;
	}

	public void setJbtStatus(Character jbtStatus) {
		this.jbtStatus = jbtStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JBT_DT_CREATE", length = 19)
	public Date getJbtDtCreate() {
		return this.jbtDtCreate;
	}

	public void setJbtDtCreate(Date jbtDtCreate) {
		this.jbtDtCreate = jbtDtCreate;
	}

	@Column(name = "JBT_UID_CREATE", length = 35)
	public String getJbtUidCreate() {
		return this.jbtUidCreate;
	}

	public void setJbtUidCreate(String jbtUidCreate) {
		this.jbtUidCreate = jbtUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JBT_DT_LUPD", length = 19)
	public Date getJbtDtLupd() {
		return this.jbtDtLupd;
	}

	public void setJbtDtLupd(Date jbtDtLupd) {
		this.jbtDtLupd = jbtDtLupd;
	}

	@Column(name = "JBT_UID_LUPD", length = 35)
	public String getJbtUidLupd() {
		return this.jbtUidLupd;
	}

	public void setJbtUidLupd(String jbtUidLupd) {
		this.jbtUidLupd = jbtUidLupd;
	}
}
