package com.guudint.clickargo.master.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstServiceType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_SERVICE_TYPE")
public class TCkMstServiceType extends COAbstractEntity<TCkMstServiceType> {

	/**
	 * Static Attributes
	 */
	private static final long serialVersionUID = 7547901505198205129L;

	// Attributes
	/////////////
	private String svctId;
	private String svctName;
	private String svctDesc;
	private String svctDescOth;
	private Character svctStatus;
	private Date svctDtCreate;
	private String svctUidCreate;
	private Date svctDtLupd;
	private String svctUidLupd;

	// Constructors
	///////////////
	public TCkMstServiceType() {
	}
	public TCkMstServiceType(String svctId) {
		this.svctId = svctId;
	}

	/**
	 * @param svctId
	 * @param svctName
	 */
	public TCkMstServiceType(String svctId, String svctName) {
		this.svctId = svctId;
		this.svctName = svctName;
	}

	/**
	 * @param svctId
	 * @param svctName
	 * @param svctDesc
	 * @param svctDescOth
	 * @param svctStatus
	 * @param svctDtCreate
	 * @param svctUidCreate
	 * @param svctDtLupd
	 * @param svctUidLupd
	 */
	public TCkMstServiceType(String svctId, String svctName, String svctDesc, String svctDescOth, Character svctStatus,
			Date svctDtCreate, String svctUidCreate, Date svctDtLupd, String svctUidLupd) {
		this.svctId = svctId;
		this.svctName = svctName;
		this.svctDesc = svctDesc;
		this.svctDescOth = svctDescOth;
		this.svctStatus = svctStatus;
		this.svctDtCreate = svctDtCreate;
		this.svctUidCreate = svctUidCreate;
		this.svctDtLupd = svctDtLupd;
		this.svctUidLupd = svctUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	public int compareTo(TCkMstServiceType o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	// Properties
	/////////////
	@Id
	@Column(name = "SVCT_ID", unique = true, nullable = false, length = 35)
	public String getSvctId() {
		return this.svctId;
	}

	public void setSvctId(String svctId) {
		this.svctId = svctId;
	}

	@Column(name = "SVCT_NAME", nullable = false, length = 100)
	public String getSvctName() {
		return this.svctName;
	}

	public void setSvctName(String svctName) {
		this.svctName = svctName;
	}

	@Column(name = "SVCT_DESC")
	public String getSvctDesc() {
		return this.svctDesc;
	}

	public void setSvctDesc(String svctDesc) {
		this.svctDesc = svctDesc;
	}

	@Column(name = "SVCT_DESC_OTH", length = 512)
	public String getSvctDescOth() {
		return this.svctDescOth;
	}

	public void setSvctDescOth(String svctDescOth) {
		this.svctDescOth = svctDescOth;
	}

	@Column(name = "SVCT_STATUS", length = 1)
	public Character getSvctStatus() {
		return this.svctStatus;
	}

	public void setSvctStatus(Character svctStatus) {
		this.svctStatus = svctStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SVCT_DT_CREATE", length = 19)
	public Date getSvctDtCreate() {
		return this.svctDtCreate;
	}

	public void setSvctDtCreate(Date svctDtCreate) {
		this.svctDtCreate = svctDtCreate;
	}

	@Column(name = "SVCT_UID_CREATE", length = 35)
	public String getSvctUidCreate() {
		return this.svctUidCreate;
	}

	public void setSvctUidCreate(String svctUidCreate) {
		this.svctUidCreate = svctUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SVCT_DT_LUPD", length = 19)
	public Date getSvctDtLupd() {
		return this.svctDtLupd;
	}

	public void setSvctDtLupd(Date svctDtLupd) {
		this.svctDtLupd = svctDtLupd;
	}

	@Column(name = "SVCT_UID_LUPD", length = 35)
	public String getSvctUidLupd() {
		return this.svctUidLupd;
	}

	public void setSvctUidLupd(String svctUidLupd) {
		this.svctUidLupd = svctUidLupd;
	}
}
