package com.guudint.clickargo.master.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstTaskState generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_TASK_STATE")
public class TCkMstTaskState extends COAbstractEntity<TCkMstTaskState> {

	// Static Attributes
	///////////////////
	private static final long serialVersionUID = -5635060284122675732L;

	// Attributes
	////////////
	private String tskstId;
	private String tskstName;
	private String tskstDesc;
	private String tskstDescOth;
	private Character tskstStatus;
	private Date tskstDtCreate;
	private String tskstUidCreate;
	private Date tskstDtLupd;
	private String tskstUidLupd;

	// Constructors
	///////////////
	public TCkMstTaskState() {
	}

	/**
	 * @param tskstId
	 * @param tskstName
	 */
	public TCkMstTaskState(String tskstId, String tskstName) {
		this.tskstId = tskstId;
		this.tskstName = tskstName;
	}

	/**
	 * @param tskstId
	 * @param tskstName
	 * @param tskstDesc
	 * @param tskstDescOth
	 * @param tskstStatus
	 * @param tskstDtCreate
	 * @param tskstUidCreate
	 * @param tskstDtLupd
	 * @param tskstUidLupd
	 */
	public TCkMstTaskState(String tskstId, String tskstName, String tskstDesc, String tskstDescOth,
			Character tskstStatus, Date tskstDtCreate, String tskstUidCreate, Date tskstDtLupd, String tskstUidLupd) {
		this.tskstId = tskstId;
		this.tskstName = tskstName;
		this.tskstDesc = tskstDesc;
		this.tskstDescOth = tskstDescOth;
		this.tskstStatus = tskstStatus;
		this.tskstDtCreate = tskstDtCreate;
		this.tskstUidCreate = tskstUidCreate;
		this.tskstDtLupd = tskstDtLupd;
		this.tskstUidLupd = tskstUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	public int compareTo(TCkMstTaskState o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	// Properties
	/////////////
	@Id
	@Column(name = "TSKST_ID", unique = true, nullable = false, length = 35)
	public String getTskstId() {
		return this.tskstId;
	}

	public void setTskstId(String tskstId) {
		this.tskstId = tskstId;
	}

	@Column(name = "TSKST_NAME", nullable = false, length = 100)
	public String getTskstName() {
		return this.tskstName;
	}

	public void setTskstName(String tskstName) {
		this.tskstName = tskstName;
	}

	@Column(name = "TSKST_DESC")
	public String getTskstDesc() {
		return this.tskstDesc;
	}

	public void setTskstDesc(String tskstDesc) {
		this.tskstDesc = tskstDesc;
	}

	@Column(name = "TSKST_DESC_OTH", length = 512)
	public String getTskstDescOth() {
		return this.tskstDescOth;
	}

	public void setTskstDescOth(String tskstDescOth) {
		this.tskstDescOth = tskstDescOth;
	}

	@Column(name = "TSKST_STATUS", length = 1)
	public Character getTskstStatus() {
		return this.tskstStatus;
	}

	public void setTskstStatus(Character tskstStatus) {
		this.tskstStatus = tskstStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TSKST_DT_CREATE", length = 19)
	public Date getTskstDtCreate() {
		return this.tskstDtCreate;
	}

	public void setTskstDtCreate(Date tskstDtCreate) {
		this.tskstDtCreate = tskstDtCreate;
	}

	@Column(name = "TSKST_UID_CREATE", length = 35)
	public String getTskstUidCreate() {
		return this.tskstUidCreate;
	}

	public void setTskstUidCreate(String tskstUidCreate) {
		this.tskstUidCreate = tskstUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TSKST_DT_LUPD", length = 19)
	public Date getTskstDtLupd() {
		return this.tskstDtLupd;
	}

	public void setTskstDtLupd(Date tskstDtLupd) {
		this.tskstDtLupd = tskstDtLupd;
	}

	@Column(name = "TSKST_UID_LUPD", length = 35)
	public String getTskstUidLupd() {
		return this.tskstUidLupd;
	}

	public void setTskstUidLupd(String tskstUidLupd) {
		this.tskstUidLupd = tskstUidLupd;
	}
}
