package com.guudint.clickargo.master.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstTaskType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_TASK_TYPE")
public class TCkMstTaskType extends COAbstractEntity<TCkMstTaskType> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 2695661206759478710L;

	// Attributes
	/////////////
	private String tsktId;
	private String tsktName;
	private String tsktDesc;
	private String tsktDescOth;
	private Character tsktStatus;
	private Date tsktDtCreate;
	private String tsktUidCreate;
	private Date tsktDtLupd;
	private String tsktUidLupd;

	// Constructors
	///////////////
	public TCkMstTaskType() {
	}

	/**
	 * @param tsktId
	 * @param tsktName
	 */
	public TCkMstTaskType(String tsktId, String tsktName) {
		this.tsktId = tsktId;
		this.tsktName = tsktName;
	}

	/**
	 * @param tsktId
	 * @param tsktName
	 * @param tsktDesc
	 * @param tsktDescOth
	 * @param tsktStatus
	 * @param tsktDtCreate
	 * @param tsktUidCreate
	 * @param tsktDtLupd
	 * @param tsktUidLupd
	 */
	public TCkMstTaskType(String tsktId, String tsktName, String tsktDesc, String tsktDescOth, Character tsktStatus,
			Date tsktDtCreate, String tsktUidCreate, Date tsktDtLupd, String tsktUidLupd) {
		this.tsktId = tsktId;
		this.tsktName = tsktName;
		this.tsktDesc = tsktDesc;
		this.tsktDescOth = tsktDescOth;
		this.tsktStatus = tsktStatus;
		this.tsktDtCreate = tsktDtCreate;
		this.tsktUidCreate = tsktUidCreate;
		this.tsktDtLupd = tsktDtLupd;
		this.tsktUidLupd = tsktUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	public int compareTo(TCkMstTaskType o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	// Properties
	/////////////
	@Id
	@Column(name = "TSKT_ID", unique = true, nullable = false, length = 35)
	public String getTsktId() {
		return this.tsktId;
	}

	public void setTsktId(String tsktId) {
		this.tsktId = tsktId;
	}

	@Column(name = "TSKT_NAME", nullable = false, length = 100)
	public String getTsktName() {
		return this.tsktName;
	}

	public void setTsktName(String tsktName) {
		this.tsktName = tsktName;
	}

	@Column(name = "TSKT_DESC")
	public String getTsktDesc() {
		return this.tsktDesc;
	}

	public void setTsktDesc(String tsktDesc) {
		this.tsktDesc = tsktDesc;
	}

	@Column(name = "TSKT_DESC_OTH", length = 512)
	public String getTsktDescOth() {
		return this.tsktDescOth;
	}

	public void setTsktDescOth(String tsktDescOth) {
		this.tsktDescOth = tsktDescOth;
	}

	@Column(name = "TSKT_STATUS", length = 1)
	public Character getTsktStatus() {
		return this.tsktStatus;
	}

	public void setTsktStatus(Character tsktStatus) {
		this.tsktStatus = tsktStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TSKT_DT_CREATE", length = 19)
	public Date getTsktDtCreate() {
		return this.tsktDtCreate;
	}

	public void setTsktDtCreate(Date tsktDtCreate) {
		this.tsktDtCreate = tsktDtCreate;
	}

	@Column(name = "TSKT_UID_CREATE", length = 35)
	public String getTsktUidCreate() {
		return this.tsktUidCreate;
	}

	public void setTsktUidCreate(String tsktUidCreate) {
		this.tsktUidCreate = tsktUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TSKT_DT_LUPD", length = 19)
	public Date getTsktDtLupd() {
		return this.tsktDtLupd;
	}

	public void setTsktDtLupd(Date tsktDtLupd) {
		this.tsktDtLupd = tsktDtLupd;
	}

	@Column(name = "TSKT_UID_LUPD", length = 35)
	public String getTsktUidLupd() {
		return this.tsktUidLupd;
	}

	public void setTsktUidLupd(String tsktUidLupd) {
		this.tsktUidLupd = tsktUidLupd;
	}
}
