package com.guudint.clickargo.master.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstPaymentAuditType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_PAYMENT_AUDIT_TYPE")
public class TCkMstPaymentAuditType extends COAbstractEntity<TCkMstPaymentAuditType> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -7493912000476640775L;

	// Attributes
	/////////////
	private String patyId;
	private String pytName;
	private String pytDesc;
	private String pytDescOth;
	private Character pytStatus;
	private Date pytDtCreate;
	private String pytUidCreate;
	private Date pytDtLupd;
	private String pytUidLupd;

	// Constructors
	///////////////
	public TCkMstPaymentAuditType() {
	}

	/**
	 * @param patyId
	 * @param pytName
	 */
	public TCkMstPaymentAuditType(String patyId, String pytName) {
		this.patyId = patyId;
		this.pytName = pytName;
	}

	/**
	 * @param patyId
	 * @param pytName
	 * @param pytDesc
	 * @param pytDescOth
	 * @param pytStatus
	 * @param pytDtCreate
	 * @param pytUidCreate
	 * @param pytDtLupd
	 * @param pytUidLupd
	 */
	public TCkMstPaymentAuditType(String patyId, String pytName, String pytDesc, String pytDescOth, Character pytStatus,
			Date pytDtCreate, String pytUidCreate, Date pytDtLupd, String pytUidLupd) {
		this.patyId = patyId;
		this.pytName = pytName;
		this.pytDesc = pytDesc;
		this.pytDescOth = pytDescOth;
		this.pytStatus = pytStatus;
		this.pytDtCreate = pytDtCreate;
		this.pytUidCreate = pytUidCreate;
		this.pytDtLupd = pytDtLupd;
		this.pytUidLupd = pytUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	public int compareTo(TCkMstPaymentAuditType o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	// Properties
	/////////////
	@Id
	@Column(name = "PATY_ID", unique = true, nullable = false, length = 35)
	public String getPatyId() {
		return this.patyId;
	}

	public void setPatyId(String patyId) {
		this.patyId = patyId;
	}

	@Column(name = "PYT_NAME", nullable = false, length = 100)
	public String getPytName() {
		return this.pytName;
	}

	public void setPytName(String pytName) {
		this.pytName = pytName;
	}

	@Column(name = "PYT_DESC")
	public String getPytDesc() {
		return this.pytDesc;
	}

	public void setPytDesc(String pytDesc) {
		this.pytDesc = pytDesc;
	}

	@Column(name = "PYT_DESC_OTH", length = 512)
	public String getPytDescOth() {
		return this.pytDescOth;
	}

	public void setPytDescOth(String pytDescOth) {
		this.pytDescOth = pytDescOth;
	}

	@Column(name = "PYT_STATUS", length = 1)
	public Character getPytStatus() {
		return this.pytStatus;
	}

	public void setPytStatus(Character pytStatus) {
		this.pytStatus = pytStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PYT_DT_CREATE", length = 19)
	public Date getPytDtCreate() {
		return this.pytDtCreate;
	}

	public void setPytDtCreate(Date pytDtCreate) {
		this.pytDtCreate = pytDtCreate;
	}

	@Column(name = "PYT_UID_CREATE", length = 35)
	public String getPytUidCreate() {
		return this.pytUidCreate;
	}

	public void setPytUidCreate(String pytUidCreate) {
		this.pytUidCreate = pytUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PYT_DT_LUPD", length = 19)
	public Date getPytDtLupd() {
		return this.pytDtLupd;
	}

	public void setPytDtLupd(Date pytDtLupd) {
		this.pytDtLupd = pytDtLupd;
	}

	@Column(name = "PYT_UID_LUPD", length = 35)
	public String getPytUidLupd() {
		return this.pytUidLupd;
	}

	public void setPytUidLupd(String pytUidLupd) {
		this.pytUidLupd = pytUidLupd;
	}
}
