package com.guudint.clickargo.master.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstCntType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_CNT_TYPE")
public class TCkMstCntType extends COAbstractEntity<TCkMstCntType> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -7794216146006809158L;

	// Attributes
	/////////////
	private String cnttId;
	private String cnttName;
	private String cnttDesc;
	private String cnttDescOth;
	private Character cnttStatus;
	private Date cnttDtCreate;
	private String cnttUidCreate;
	private Date cnttDtLupd;
	private String cnttUidLupd;

	// Constructors
	///////////////
	public TCkMstCntType() {
	}

	/**
	 * @param cnttId
	 * @param cnttName
	 */
	public TCkMstCntType(String cnttId, String cnttName) {
		this.cnttId = cnttId;
		this.cnttName = cnttName;
	}

	/**
	 * @param cnttId
	 * @param cnttName
	 * @param cnttDesc
	 * @param cnttDescOth
	 * @param cnttStatus
	 * @param cnttDtCreate
	 * @param cnttUidCreate
	 * @param cnttDtLupd
	 * @param cnttUidLupd
	 */
	public TCkMstCntType(String cnttId, String cnttName, String cnttDesc, String cnttDescOth, Character cnttStatus,
			Date cnttDtCreate, String cnttUidCreate, Date cnttDtLupd, String cnttUidLupd) {
		this.cnttId = cnttId;
		this.cnttName = cnttName;
		this.cnttDesc = cnttDesc;
		this.cnttDescOth = cnttDescOth;
		this.cnttStatus = cnttStatus;
		this.cnttDtCreate = cnttDtCreate;
		this.cnttUidCreate = cnttUidCreate;
		this.cnttDtLupd = cnttDtLupd;
		this.cnttUidLupd = cnttUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	public int compareTo(TCkMstCntType o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	// Properties
	/////////////
	@Id
	@Column(name = "CNTT_ID", unique = true, nullable = false, length = 35)
	public String getCnttId() {
		return this.cnttId;
	}

	public void setCnttId(String cnttId) {
		this.cnttId = cnttId;
	}

	@Column(name = "CNTT_NAME", nullable = false, length = 100)
	public String getCnttName() {
		return this.cnttName;
	}

	public void setCnttName(String cnttName) {
		this.cnttName = cnttName;
	}

	@Column(name = "CNTT_DESC")
	public String getCnttDesc() {
		return this.cnttDesc;
	}

	public void setCnttDesc(String cnttDesc) {
		this.cnttDesc = cnttDesc;
	}

	@Column(name = "CNTT_DESC_OTH", length = 512)
	public String getCnttDescOth() {
		return this.cnttDescOth;
	}

	public void setCnttDescOth(String cnttDescOth) {
		this.cnttDescOth = cnttDescOth;
	}

	@Column(name = "CNTT_STATUS", length = 1)
	public Character getCnttStatus() {
		return this.cnttStatus;
	}

	public void setCnttStatus(Character cnttStatus) {
		this.cnttStatus = cnttStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNTT_DT_CREATE", length = 19)
	public Date getCnttDtCreate() {
		return this.cnttDtCreate;
	}

	public void setCnttDtCreate(Date cnttDtCreate) {
		this.cnttDtCreate = cnttDtCreate;
	}

	@Column(name = "CNTT_UID_CREATE", length = 35)
	public String getCnttUidCreate() {
		return this.cnttUidCreate;
	}

	public void setCnttUidCreate(String cnttUidCreate) {
		this.cnttUidCreate = cnttUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNTT_DT_LUPD", length = 19)
	public Date getCnttDtLupd() {
		return this.cnttDtLupd;
	}

	public void setCnttDtLupd(Date cnttDtLupd) {
		this.cnttDtLupd = cnttDtLupd;
	}

	@Column(name = "CNTT_UID_LUPD", length = 35)
	public String getCnttUidLupd() {
		return this.cnttUidLupd;
	}

	public void setCnttUidLupd(String cnttUidLupd) {
		this.cnttUidLupd = cnttUidLupd;
	}
}
