package com.guudint.clickargo.master.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstCntSize generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_CNT_SIZE")
public class TCkMstCntSize extends COAbstractEntity<TCkMstCntSize> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 6751239185144820542L;
	
	// Attributes
	/////////////
	private String cntzId;
	private String cntzName;
	private String cntzDesc;
	private String cntzDescOth;
	private Character cntzStatus;
	private Date cntzDtCreate;
	private String cntzUidCreate;
	private Date cntzDtLupd;
	private String cntzUidLupd;

	// Constructors
	///////////////
	public TCkMstCntSize() {
	}

	/**
	 * @param cntzId
	 * @param cntzName
	 */
	public TCkMstCntSize(String cntzId, String cntzName) {
		this.cntzId = cntzId;
		this.cntzName = cntzName;
	}

	/**
	 * @param cntzId
	 * @param cntzName
	 * @param cntzDesc
	 * @param cntzDescOth
	 * @param cntzStatus
	 * @param cntzDtCreate
	 * @param cntzUidCreate
	 * @param cntzDtLupd
	 * @param cntzUidLupd
	 */
	public TCkMstCntSize(String cntzId, String cntzName, String cntzDesc, String cntzDescOth, Character cntzStatus,
			Date cntzDtCreate, String cntzUidCreate, Date cntzDtLupd, String cntzUidLupd) {
		this.cntzId = cntzId;
		this.cntzName = cntzName;
		this.cntzDesc = cntzDesc;
		this.cntzDescOth = cntzDescOth;
		this.cntzStatus = cntzStatus;
		this.cntzDtCreate = cntzDtCreate;
		this.cntzUidCreate = cntzUidCreate;
		this.cntzDtLupd = cntzDtLupd;
		this.cntzUidLupd = cntzUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 *      
	 */
	public int compareTo(TCkMstCntSize o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 *      
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

	// Properties
	/////////////
	@Id
	@Column(name = "CNTZ_ID", unique = true, nullable = false, length = 35)
	public String getCntzId() {
		return this.cntzId;
	}

	public void setCntzId(String cntzId) {
		this.cntzId = cntzId;
	}

	@Column(name = "CNTZ_NAME", nullable = false, length = 100)
	public String getCntzName() {
		return this.cntzName;
	}

	public void setCntzName(String cntzName) {
		this.cntzName = cntzName;
	}

	@Column(name = "CNTZ_DESC")
	public String getCntzDesc() {
		return this.cntzDesc;
	}

	public void setCntzDesc(String cntzDesc) {
		this.cntzDesc = cntzDesc;
	}

	@Column(name = "CNTZ_DESC_OTH", length = 512)
	public String getCntzDescOth() {
		return this.cntzDescOth;
	}

	public void setCntzDescOth(String cntzDescOth) {
		this.cntzDescOth = cntzDescOth;
	}

	@Column(name = "CNTZ_STATUS", length = 1)
	public Character getCntzStatus() {
		return this.cntzStatus;
	}

	public void setCntzStatus(Character cntzStatus) {
		this.cntzStatus = cntzStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNTZ_DT_CREATE", length = 19)
	public Date getCntzDtCreate() {
		return this.cntzDtCreate;
	}

	public void setCntzDtCreate(Date cntzDtCreate) {
		this.cntzDtCreate = cntzDtCreate;
	}

	@Column(name = "CNTZ_UID_CREATE", length = 35)
	public String getCntzUidCreate() {
		return this.cntzUidCreate;
	}

	public void setCntzUidCreate(String cntzUidCreate) {
		this.cntzUidCreate = cntzUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CNTZ_DT_LUPD", length = 19)
	public Date getCntzDtLupd() {
		return this.cntzDtLupd;
	}

	public void setCntzDtLupd(Date cntzDtLupd) {
		this.cntzDtLupd = cntzDtLupd;
	}

	@Column(name = "CNTZ_UID_LUPD", length = 35)
	public String getCntzUidLupd() {
		return this.cntzUidLupd;
	}

	public void setCntzUidLupd(String cntzUidLupd) {
		this.cntzUidLupd = cntzUidLupd;
	}

}
