package com.guudint.clickargo.master.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstAuthAccnType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_AUTH_ACCN_TYPE")
public class TCkMstAuthAccnType extends COAbstractEntity<TCkMstAuthAccnType> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -6080495113188700019L;

	// Attributes
	//////////////
	private String auatId;
	private String auatName;
	private String auatDesc;
	private String auatDescOth;
	private Character auatStatus;
	private Date auatDtCreate;
	private String auatUidCreate;
	private Date auatDtLupd;
	private String auatUidLupd;

	// Constructors
	///////////////
	public TCkMstAuthAccnType() {
	}

	/**
	 * @param auatId
	 * @param auatName
	 */
	public TCkMstAuthAccnType(String auatId, String auatName) {
		this.auatId = auatId;
		this.auatName = auatName;
	}

	/**
	 * @param auatId
	 * @param auatName
	 * @param auatDesc
	 * @param auatDescOth
	 * @param auatStatus
	 * @param auatDtCreate
	 * @param auatUidCreate
	 * @param auatDtLupd
	 * @param auatUidLupd
	 */
	public TCkMstAuthAccnType(String auatId, String auatName, String auatDesc, String auatDescOth, Character auatStatus,
			Date auatDtCreate, String auatUidCreate, Date auatDtLupd, String auatUidLupd) {
		this.auatId = auatId;
		this.auatName = auatName;
		this.auatDesc = auatDesc;
		this.auatDescOth = auatDescOth;
		this.auatStatus = auatStatus;
		this.auatDtCreate = auatDtCreate;
		this.auatUidCreate = auatUidCreate;
		this.auatDtLupd = auatDtLupd;
		this.auatUidLupd = auatUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	public int compareTo(TCkMstAuthAccnType arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	// Properties
	/////////////
	@Id
	@Column(name = "AUAT_ID", unique = true, nullable = false, length = 35)
	public String getAuatId() {
		return this.auatId;
	}

	public void setAuatId(String auatId) {
		this.auatId = auatId;
	}

	@Column(name = "AUAT_NAME", nullable = false, length = 100)
	public String getAuatName() {
		return this.auatName;
	}

	public void setAuatName(String auatName) {
		this.auatName = auatName;
	}

	@Column(name = "AUAT_DESC")
	public String getAuatDesc() {
		return this.auatDesc;
	}

	public void setAuatDesc(String auatDesc) {
		this.auatDesc = auatDesc;
	}

	@Column(name = "AUAT_DESC_OTH", length = 512)
	public String getAuatDescOth() {
		return this.auatDescOth;
	}

	public void setAuatDescOth(String auatDescOth) {
		this.auatDescOth = auatDescOth;
	}

	@Column(name = "AUAT_STATUS", length = 1)
	public Character getAuatStatus() {
		return this.auatStatus;
	}

	public void setAuatStatus(Character auatStatus) {
		this.auatStatus = auatStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUAT_DT_CREATE", length = 19)
	public Date getAuatDtCreate() {
		return this.auatDtCreate;
	}

	public void setAuatDtCreate(Date auatDtCreate) {
		this.auatDtCreate = auatDtCreate;
	}

	@Column(name = "AUAT_UID_CREATE", length = 35)
	public String getAuatUidCreate() {
		return this.auatUidCreate;
	}

	public void setAuatUidCreate(String auatUidCreate) {
		this.auatUidCreate = auatUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUAT_DT_LUPD", length = 19)
	public Date getAuatDtLupd() {
		return this.auatDtLupd;
	}

	public void setAuatDtLupd(Date auatDtLupd) {
		this.auatDtLupd = auatDtLupd;
	}

	@Column(name = "AUAT_UID_LUPD", length = 35)
	public String getAuatUidLupd() {
		return this.auatUidLupd;
	}

	public void setAuatUidLupd(String auatUidLupd) {
		this.auatUidLupd = auatUidLupd;
	}
}
