package com.guudint.clickargo.master.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstSvcSubState generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_SVC_SUB_STATE")
public class TCkMstSvcSubState extends COAbstractEntity<TCkMstSvcSubState> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 5849220816753319974L;
	
	// Attributes
	/////////////
	private String ssstId;
	private String ssstName;
	private String ssstDesc;
	private String ssstDescOth;
	private Character ssstStatus;
	private Date ssstDtCreate;
	private String ssstUidCreate;
	private Date ssstDtLupd;
	private String ssstUidLupd;

	// Constructors
	///////////////
	public TCkMstSvcSubState() {
	}

	/**
	 * @param ssstId
	 * @param ssstName
	 */
	public TCkMstSvcSubState(String ssstId, String ssstName) {
		this.ssstId = ssstId;
		this.ssstName = ssstName;
	}

	/**
	 * @param ssstId
	 * @param ssstName
	 * @param ssstDesc
	 * @param ssstDescOth
	 * @param ssstStatus
	 * @param ssstDtCreate
	 * @param ssstUidCreate
	 * @param ssstDtLupd
	 * @param ssstUidLupd
	 */
	public TCkMstSvcSubState(String ssstId, String ssstName, String ssstDesc, String ssstDescOth, Character ssstStatus,
			Date ssstDtCreate, String ssstUidCreate, Date ssstDtLupd, String ssstUidLupd) {
		this.ssstId = ssstId;
		this.ssstName = ssstName;
		this.ssstDesc = ssstDesc;
		this.ssstDescOth = ssstDescOth;
		this.ssstStatus = ssstStatus;
		this.ssstDtCreate = ssstDtCreate;
		this.ssstUidCreate = ssstUidCreate;
		this.ssstDtLupd = ssstDtLupd;
		this.ssstUidLupd = ssstUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 *      
	 */
	public int compareTo(TCkMstSvcSubState o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 *      
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}
	
	// Properties
	/////////////
	@Id
	@Column(name = "SSST_ID", unique = true, nullable = false, length = 35)
	public String getSsstId() {
		return this.ssstId;
	}

	public void setSsstId(String ssstId) {
		this.ssstId = ssstId;
	}

	@Column(name = "SSST_NAME", nullable = false, length = 100)
	public String getSsstName() {
		return this.ssstName;
	}

	public void setSsstName(String ssstName) {
		this.ssstName = ssstName;
	}

	@Column(name = "SSST_DESC")
	public String getSsstDesc() {
		return this.ssstDesc;
	}

	public void setSsstDesc(String ssstDesc) {
		this.ssstDesc = ssstDesc;
	}

	@Column(name = "SSST_DESC_OTH", length = 512)
	public String getSsstDescOth() {
		return this.ssstDescOth;
	}

	public void setSsstDescOth(String ssstDescOth) {
		this.ssstDescOth = ssstDescOth;
	}

	@Column(name = "SSST_STATUS", length = 1)
	public Character getSsstStatus() {
		return this.ssstStatus;
	}

	public void setSsstStatus(Character ssstStatus) {
		this.ssstStatus = ssstStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SSST_DT_CREATE", length = 19)
	public Date getSsstDtCreate() {
		return this.ssstDtCreate;
	}

	public void setSsstDtCreate(Date ssstDtCreate) {
		this.ssstDtCreate = ssstDtCreate;
	}

	@Column(name = "SSST_UID_CREATE", length = 35)
	public String getSsstUidCreate() {
		return this.ssstUidCreate;
	}

	public void setSsstUidCreate(String ssstUidCreate) {
		this.ssstUidCreate = ssstUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SSST_DT_LUPD", length = 19)
	public Date getSsstDtLupd() {
		return this.ssstDtLupd;
	}

	public void setSsstDtLupd(Date ssstDtLupd) {
		this.ssstDtLupd = ssstDtLupd;
	}

	@Column(name = "SSST_UID_LUPD", length = 35)
	public String getSsstUidLupd() {
		return this.ssstUidLupd;
	}

	public void setSsstUidLupd(String ssstUidLupd) {
		this.ssstUidLupd = ssstUidLupd;
	}
}
