package com.guudint.clickargo.master.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstAuthState generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_AUTH_STATE")
public class TCkMstAuthState extends COAbstractEntity<TCkMstAuthState> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 3995540877727824544L;
	
	// Attributes
	/////////////
	private String austId;
	private String austName;
	private String austDesc;
	private String austDescOth;
	private Character austStatus;
	private Date austDtCreate;
	private String austUidCreate;
	private Date austDtLupd;
	private String austUidLupd;

	// Constructors
	////////////////
	public TCkMstAuthState() {
	}

	/**
	 * @param austId
	 * @param austName
	 */
	public TCkMstAuthState(String austId, String austName) {
		this.austId = austId;
		this.austName = austName;
	}

	/**
	 * @param austId
	 * @param austName
	 * @param austDesc
	 * @param austDescOth
	 * @param austStatus
	 * @param austDtCreate
	 * @param austUidCreate
	 * @param austDtLupd
	 * @param austUidLupd
	 */
	public TCkMstAuthState(String austId, String austName, String austDesc, String austDescOth, Character austStatus,
			Date austDtCreate, String austUidCreate, Date austDtLupd, String austUidLupd) {
		this.austId = austId;
		this.austName = austName;
		this.austDesc = austDesc;
		this.austDescOth = austDescOth;
		this.austStatus = austStatus;
		this.austDtCreate = austDtCreate;
		this.austUidCreate = austUidCreate;
		this.austDtLupd = austDtLupd;
		this.austUidLupd = austUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 *      
	 */
	public int compareTo(TCkMstAuthState o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 *      
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}
	
	// Properties
	/////////////
	@Id
	@Column(name = "AUST_ID", unique = true, nullable = false, length = 35)
	public String getAustId() {
		return this.austId;
	}

	public void setAustId(String austId) {
		this.austId = austId;
	}

	@Column(name = "AUST_NAME", nullable = false, length = 100)
	public String getAustName() {
		return this.austName;
	}

	public void setAustName(String austName) {
		this.austName = austName;
	}

	@Column(name = "AUST_DESC")
	public String getAustDesc() {
		return this.austDesc;
	}

	public void setAustDesc(String austDesc) {
		this.austDesc = austDesc;
	}

	@Column(name = "AUST_DESC_OTH", length = 512)
	public String getAustDescOth() {
		return this.austDescOth;
	}

	public void setAustDescOth(String austDescOth) {
		this.austDescOth = austDescOth;
	}

	@Column(name = "AUST_STATUS", length = 1)
	public Character getAustStatus() {
		return this.austStatus;
	}

	public void setAustStatus(Character austStatus) {
		this.austStatus = austStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUST_DT_CREATE", length = 19)
	public Date getAustDtCreate() {
		return this.austDtCreate;
	}

	public void setAustDtCreate(Date austDtCreate) {
		this.austDtCreate = austDtCreate;
	}

	@Column(name = "AUST_UID_CREATE", length = 35)
	public String getAustUidCreate() {
		return this.austUidCreate;
	}

	public void setAustUidCreate(String austUidCreate) {
		this.austUidCreate = austUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUST_DT_LUPD", length = 19)
	public Date getAustDtLupd() {
		return this.austDtLupd;
	}

	public void setAustDtLupd(Date austDtLupd) {
		this.austDtLupd = austDtLupd;
	}

	@Column(name = "AUST_UID_LUPD", length = 35)
	public String getAustUidLupd() {
		return this.austUidLupd;
	}

	public void setAustUidLupd(String austUidLupd) {
		this.austUidLupd = austUidLupd;
	}

}
