package com.guudint.clickargo.master.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstShipmentType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_SHIPMENT_TYPE")
public class TCkMstShipmentType extends COAbstractEntity<TCkMstShipmentType> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -4539610576731011148L;

	// Attributes
	//////////////
	private String shtId;
	private String shtName;
	private String shtDesc;
	private String shtDescOth;
	private Character shtStatus;
	private Date shtDtCreate;
	private String shtUidCreate;
	private Date shtDtLupd;
	private String shtUidLupd;

	// Constructors
	///////////////
	public TCkMstShipmentType() {
	}

	/**
	 * @param shtId
	 * @param shtName
	 */
	public TCkMstShipmentType(String shtId, String shtName) {
		this.shtId = shtId;
		this.shtName = shtName;
	}

	/**
	 * @param shtId
	 * @param shtName
	 * @param shtDesc
	 * @param shtDescOth
	 * @param shtStatus
	 * @param shtDtCreate
	 * @param shtUidCreate
	 * @param shtDtLupd
	 * @param shtUidLupd
	 */
	public TCkMstShipmentType(String shtId, String shtName, String shtDesc, String shtDescOth, Character shtStatus,
			Date shtDtCreate, String shtUidCreate, Date shtDtLupd, String shtUidLupd) {
		this.shtId = shtId;
		this.shtName = shtName;
		this.shtDesc = shtDesc;
		this.shtDescOth = shtDescOth;
		this.shtStatus = shtStatus;
		this.shtDtCreate = shtDtCreate;
		this.shtUidCreate = shtUidCreate;
		this.shtDtLupd = shtDtLupd;
		this.shtUidLupd = shtUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	public int compareTo(TCkMstShipmentType o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	// Properties
	/////////////
	@Id
	@Column(name = "SHT_ID", unique = true, nullable = false, length = 35)
	public String getShtId() {
		return this.shtId;
	}

	public void setShtId(String shtId) {
		this.shtId = shtId;
	}

	@Column(name = "SHT_NAME", nullable = false, length = 100)
	public String getShtName() {
		return this.shtName;
	}

	public void setShtName(String shtName) {
		this.shtName = shtName;
	}

	@Column(name = "SHT_DESC")
	public String getShtDesc() {
		return this.shtDesc;
	}

	public void setShtDesc(String shtDesc) {
		this.shtDesc = shtDesc;
	}

	@Column(name = "SHT_DESC_OTH", length = 512)
	public String getShtDescOth() {
		return this.shtDescOth;
	}

	public void setShtDescOth(String shtDescOth) {
		this.shtDescOth = shtDescOth;
	}

	@Column(name = "SHT_STATUS", length = 1)
	public Character getShtStatus() {
		return this.shtStatus;
	}

	public void setShtStatus(Character shtStatus) {
		this.shtStatus = shtStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SHT_DT_CREATE", length = 19)
	public Date getShtDtCreate() {
		return this.shtDtCreate;
	}

	public void setShtDtCreate(Date shtDtCreate) {
		this.shtDtCreate = shtDtCreate;
	}

	@Column(name = "SHT_UID_CREATE", length = 35)
	public String getShtUidCreate() {
		return this.shtUidCreate;
	}

	public void setShtUidCreate(String shtUidCreate) {
		this.shtUidCreate = shtUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SHT_DT_LUPD", length = 19)
	public Date getShtDtLupd() {
		return this.shtDtLupd;
	}

	public void setShtDtLupd(Date shtDtLupd) {
		this.shtDtLupd = shtDtLupd;
	}

	@Column(name = "SHT_UID_LUPD", length = 35)
	public String getShtUidLupd() {
		return this.shtUidLupd;
	}

	public void setShtUidLupd(String shtUidLupd) {
		this.shtUidLupd = shtUidLupd;
	}
}
