INSERT INTO clickargo2.T_MST_PORT (PORT_CODE,PORT_STATUS,PORT_COUNTRY,PORT_TYPE,PORT_DESCRIPTION,PORT_DT_CREATE,PORT_UID_CREATE)
	VALUES (
	'USNYC',
	'A',
	'US',
	'PORTT_SEA',
	'NEW YORK HARBOR',
	SYSDATE(),
	'SYS'
	);
 