package com.guudint.clickargo.job.model;
// Generated 11 Jun 2023, 7:20:46 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkJobReject generated by hbm2java
 */
@Entity
@Table(name = "T_CK_JOB_REJECT")
public class TCkJobReject extends COAbstractEntity<TCkJobReject> {

	private static final long serialVersionUID = 1840649912421139088L;
	private String jobrId;
	private TCkJob TCkJob;
	private Integer jobrSeq;
	private String jobrUidReject;
	private Date jobrDtReject;
	private String jobrReason;

	public TCkJobReject() {
	}

	public TCkJobReject(String jobrId) {
		this.jobrId = jobrId;
	}

	public TCkJobReject(String jobrId, TCkJob TCkJob, Integer jobrSeq, String jobrUidReject, Date jobrDtReject,
			String jobrReason) {
		this.jobrId = jobrId;
		this.TCkJob = TCkJob;
		this.jobrSeq = jobrSeq;
		this.jobrUidReject = jobrUidReject;
		this.jobrDtReject = jobrDtReject;
		this.jobrReason = jobrReason;
	}

	@Id

	@Column(name = "JOBR_ID", unique = true, nullable = false, length = 35)
	public String getJobrId() {
		return this.jobrId;
	}

	public void setJobrId(String jobrId) {
		this.jobrId = jobrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOBR_JOB")
	public TCkJob getTCkJob() {
		return this.TCkJob;
	}

	public void setTCkJob(TCkJob TCkJob) {
		this.TCkJob = TCkJob;
	}

	@Column(name = "JOBR_SEQ")
	public Integer getJobrSeq() {
		return this.jobrSeq;
	}

	public void setJobrSeq(Integer jobrSeq) {
		this.jobrSeq = jobrSeq;
	}

	@Column(name = "JOBR_UID_REJECT", length = 35)
	public String getJobrUidReject() {
		return this.jobrUidReject;
	}

	public void setJobrUidReject(String jobrUidReject) {
		this.jobrUidReject = jobrUidReject;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JOBR_DT_REJECT", length = 19)
	public Date getJobrDtReject() {
		return this.jobrDtReject;
	}

	public void setJobrDtReject(Date jobrDtReject) {
		this.jobrDtReject = jobrDtReject;
	}

	@Column(name = "JOBR_REASON", length = 16777215)
	public String getJobrReason() {
		return this.jobrReason;
	}

	public void setJobrReason(String jobrReason) {
		this.jobrReason = jobrReason;
	}

	@Override
	public int compareTo(TCkJobReject o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
