package com.guudint.clickargo.job.model;
// Generated 12 Oct 2023, 5:50:02 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkJobRemarks generated by hbm2java
 */
@Entity
@Table(name = "T_CK_JOB_REMARKS")
public class TCkJobRemarks extends COAbstractEntity<TCkJobRemarks> {

	private static final long serialVersionUID = -6223092437091630526L;
	private String jobrId;
	private TCkJob TCkJob;
	private char jobrRemarkType;
	private Integer jobrSeq;
	private String jobrUidCreated;
	private Date jobrDtRemarks;
	private String jobrReason;

	public TCkJobRemarks() {
	}

	public TCkJobRemarks(String jobrId, char jobrRemarkType) {
		this.jobrId = jobrId;
		this.jobrRemarkType = jobrRemarkType;
	}

	public TCkJobRemarks(String jobrId, TCkJob TCkJob, char jobrRemarkType, Integer jobrSeq, String jobrUidCreated,
			Date jobrDtRemarks, String jobrReason) {
		this.jobrId = jobrId;
		this.TCkJob = TCkJob;
		this.jobrRemarkType = jobrRemarkType;
		this.jobrSeq = jobrSeq;
		this.jobrUidCreated = jobrUidCreated;
		this.jobrDtRemarks = jobrDtRemarks;
		this.jobrReason = jobrReason;
	}

	@Id

	@Column(name = "JOBR_ID", unique = true, nullable = false, length = 35)
	public String getJobrId() {
		return this.jobrId;
	}

	public void setJobrId(String jobrId) {
		this.jobrId = jobrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOBR_JOB")
	public TCkJob getTCkJob() {
		return this.TCkJob;
	}

	public void setTCkJob(TCkJob TCkJob) {
		this.TCkJob = TCkJob;
	}

	@Column(name = "JOBR_REMARK_TYPE", nullable = false, length = 1)
	public char getJobrRemarkType() {
		return this.jobrRemarkType;
	}

	public void setJobrRemarkType(char jobrRemarkType) {
		this.jobrRemarkType = jobrRemarkType;
	}

	@Column(name = "JOBR_SEQ")
	public Integer getJobrSeq() {
		return this.jobrSeq;
	}

	public void setJobrSeq(Integer jobrSeq) {
		this.jobrSeq = jobrSeq;
	}

	@Column(name = "JOBR_UID_CREATED", length = 35)
	public String getJobrUidCreated() {
		return this.jobrUidCreated;
	}

	public void setJobrUidCreated(String jobrUidCreated) {
		this.jobrUidCreated = jobrUidCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JOBR_DT_REMARKS", length = 19)
	public Date getJobrDtRemarks() {
		return this.jobrDtRemarks;
	}

	public void setJobrDtRemarks(Date jobrDtRemarks) {
		this.jobrDtRemarks = jobrDtRemarks;
	}

	@Column(name = "JOBR_REASON", length = 16777215)
	public String getJobrReason() {
		return this.jobrReason;
	}

	public void setJobrReason(String jobrReason) {
		this.jobrReason = jobrReason;
	}

	@Override
	public int compareTo(TCkJobRemarks o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
