package com.guudint.clickargo.job.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.common.COAbstractEntity;
import com.vcc.camelone.master.model.TMstAttType;

/**
 * TCkJobAttach generated by hbm2java
 */
@Entity
@Table(name = "T_CK_JOB_ATTACH")
public class TCkJobAttach extends COAbstractEntity<TCkJobAttach> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 492221142718717628L;

	// Attributes
	/////////////
	private String attId;
	private TCkJob TCkJob;
	private TMstAttType TMstAttType;
	private String attName;
	private String attDoc;
	private Character attStatus;
	private String attRemarks;
	private Date attDtCreate;
	private String attUidCreate;
	private Date attDtLupd;
	private String attUidLupd;
	
	private Character attReqReturn;
	private Date attDtReturn;
	private String attReturnVerifier;
	private String attRefNo;
	private Date attDtValid;

	// Constructors
	///////////////
	public TCkJobAttach() {
	}

	/**
	 * @param attId
	 * @param TCkJob
	 * @param TMstAttType
	 */
	public TCkJobAttach(String attId, TCkJob TCkJob, TMstAttType TMstAttType) {
		this.attId = attId;
		this.TCkJob = TCkJob;
		this.TMstAttType = TMstAttType;
	}

	/**
	 * @param attId
	 * @param TCkJob
	 * @param TMstAttType
	 * @param attName
	 * @param attDoc
	 * @param attStatus
	 * @param attDtCreate
	 * @param attUidCreate
	 * @param attDtLupd
	 * @param attUidLupd
	 * @param attDtValid
	 */
	public TCkJobAttach(String attId, TCkJob TCkJob, TMstAttType TMstAttType, String attName, String attDoc,
			Character attStatus, String attRemarks, Date attDtCreate, String attUidCreate, Date attDtLupd, String attUidLupd, 
			Character attReqReturn, Date attDtReturn, String attRefNo,  Date attDtValid) {
		this.attId = attId;
		this.TCkJob = TCkJob;
		this.TMstAttType = TMstAttType;
		this.attName = attName;
		this.attDoc = attDoc;
		this.attStatus = attStatus;
		this.attRemarks = attRemarks;
		this.attDtCreate = attDtCreate;
		this.attUidCreate = attUidCreate;
		this.attDtLupd = attDtLupd;
		this.attUidLupd = attUidLupd;
		this.attReqReturn = attReqReturn;
		this.attDtReturn = attDtReturn;
		this.attRefNo = attRefNo;
		this.attDtValid = attDtValid;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkJobAttach o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	// Properties
	/////////////
	@Id
	@Column(name = "ATT_ID", unique = true, nullable = false, length = 35)
	public String getAttId() {
		return this.attId;
	}

	public void setAttId(String attId) {
		this.attId = attId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ATT_JOB", nullable = false)
	public TCkJob getTCkJob() {
		return this.TCkJob;
	}

	public void setTCkJob(TCkJob TCkJob) {
		this.TCkJob = TCkJob;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ATT_TYPE", nullable = false)
	public TMstAttType getTMstAttType() {
		return this.TMstAttType;
	}

	public void setTMstAttType(TMstAttType TMstAttType) {
		this.TMstAttType = TMstAttType;
	}

	@Column(name = "ATT_NAME", length = 256)
	public String getAttName() {
		return this.attName;
	}

	public void setAttName(String attName) {
		this.attName = attName;
	}

	@Column(name = "ATT_DOC", length = 1024)
	public String getAttDoc() {
		return this.attDoc;
	}

	public void setAttDoc(String attDoc) {
		this.attDoc = attDoc;
	}

	@Column(name = "ATT_STATUS", length = 1)
	public Character getAttStatus() {
		return this.attStatus;
	}

	public void setAttStatus(Character attStatus) {
		this.attStatus = attStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ATT_DT_CREATE", length = 19)
	public Date getAttDtCreate() {
		return this.attDtCreate;
	}

	public void setAttDtCreate(Date attDtCreate) {
		this.attDtCreate = attDtCreate;
	}

	@Column(name = "ATT_UID_CREATE", length = 35)
	public String getAttUidCreate() {
		return this.attUidCreate;
	}

	public void setAttUidCreate(String attUidCreate) {
		this.attUidCreate = attUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ATT_DT_LUPD", length = 19)
	public Date getAttDtLupd() {
		return this.attDtLupd;
	}

	public void setAttDtLupd(Date attDtLupd) {
		this.attDtLupd = attDtLupd;
	}

	@Column(name = "ATT_UID_LUPD", length = 35)
	public String getAttUidLupd() {
		return this.attUidLupd;
	}

	public void setAttUidLupd(String attUidLupd) {
		this.attUidLupd = attUidLupd;
	}

	@Column(name = "ATT_REQ_RETURN", length = 1)
	public Character getAttReqReturn() {
		return attReqReturn;
	}

	public void setAttReqReturn(Character attReqReturn) {
		this.attReqReturn = attReqReturn;
	}

	@Column(name = "ATT_DT_RETURN", length = 19)
	public Date getAttDtReturn() {
		return attDtReturn;
	}

	public void setAttDtReturn(Date attDtReturn) {
		this.attDtReturn = attDtReturn;
	}

	@Column(name = "ATT_RETURN_VERIFIER", length = 35)
	public String getAttReturnVerifier() {
		return attReturnVerifier;
	}

	public void setAttReturnVerifier(String attReturnVerifier) {
		this.attReturnVerifier = attReturnVerifier;
	}
	
	@Column(name = "ATT_REF_NO", length = 255)
	public String getAttRefNo() {
		return attRefNo;
	}

	public void setAttRefNo(String attRefNo) {
		this.attRefNo = attRefNo;
	}

	@Column(name = "ATT_REMARKS", length = 2048)
	public String getAttRemarks() {
		return attRemarks;
	}

	public void setAttRemarks(String attRemarks) {
		this.attRemarks = attRemarks;
	}

	@Column(name = "ATT_DT_VALID", length = 19)
	public Date getAttDtValid() {
		return attDtValid;
	}

	public void setAttDtValid(Date attDtValid) {
		this.attDtValid = attDtValid;
	}
	
}
