package com.guudint.clickargo.job.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.common.model.TCkRecordDate;
import com.guudint.clickargo.master.model.TCkMstJobState;
import com.guudint.clickargo.master.model.TCkMstJobType;
import com.guudint.clickargo.master.model.TCkMstShipmentType;
import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkJob generated by hbm2java
 */
@Entity
@Table(name = "T_CK_JOB")
public class TCkJob extends COAbstractEntity<TCkJob> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = -1613482284885660216L;
	
	// Attributes
	/////////////
	private String jobId;
	private TCkMstJobState TCkMstJobState;
	private TCkMstJobType TCkMstJobType;
	private TCkMstShipmentType TCkMstShipmentType;
	private TCkRecordDate TCkRecordDate;
	private TCoreAccn TCoreAccnByJobFfAccn;
	private TCoreAccn TCoreAccnByJobToAccn;
	private TCoreAccn TCoreAccnByJobSlAccn;
	private TCoreAccn TCoreAccnByJobCoAccn;
	private TCoreAccn TCoreAccnByJobOwnerAccn;
	private String jobReference;
	private String jobRemarks;
	private Character jobStatus;
	private Date jobDtCreate;
	private String jobUidCreate;
	private Date jobDtLupd;
	private String jobUidLupd;

	private String jobLoading;

	private String jobSubType;
	// Constructors
	///////////////
	public TCkJob() {
	}

	/**
	 * @param jobId
	 * @param TCkMstJobState
	 * @param TCkMstJobType
	 * @param TCkMstShipmentType
	 */
	public TCkJob(String jobId, TCkMstJobState TCkMstJobState, TCkMstJobType TCkMstJobType,
			TCkMstShipmentType TCkMstShipmentType) {
		this.jobId = jobId;
		this.TCkMstJobState = TCkMstJobState;
		this.TCkMstJobType = TCkMstJobType;
		this.TCkMstShipmentType = TCkMstShipmentType;
	}

	public TCkJob(String jobId, TCkMstJobState TCkMstJobState, TCkMstJobType TCkMstJobType,
			TCkMstShipmentType TCkMstShipmentType, TCkRecordDate TCkRecordDate, TCoreAccn TCoreAccnByJobFfAccn, TCoreAccn TCoreAccnByJobToAccn, 
			TCoreAccn TCoreAccnByJobSlAccn, TCoreAccn TCoreAccnByJobCoAccn, TCoreAccn TCoreAccnByJobOwnerAccn, String jobReference, String jobRemarks,
			Character jobStatus, Date jobDtCreate, String jobUidCreate, Date jobDtLupd, String jobUidLupd, String jobLoading, String jobSubType) {
		this.jobId = jobId;
		this.TCkMstJobState = TCkMstJobState;
		this.TCkMstJobType = TCkMstJobType;
		this.TCkMstShipmentType = TCkMstShipmentType;
		this.TCkRecordDate = TCkRecordDate;
		this.TCoreAccnByJobFfAccn = TCoreAccnByJobFfAccn;
		this.TCoreAccnByJobToAccn = TCoreAccnByJobToAccn;
		this.TCoreAccnByJobSlAccn = TCoreAccnByJobSlAccn;
		this.TCoreAccnByJobCoAccn = TCoreAccnByJobCoAccn;
		this.TCoreAccnByJobOwnerAccn = TCoreAccnByJobOwnerAccn;
		this.jobReference = jobReference;
		this.jobRemarks = jobRemarks;
		this.jobStatus = jobStatus;
		this.jobDtCreate = jobDtCreate;
		this.jobUidCreate = jobUidCreate;
		this.jobDtLupd = jobDtLupd;
		this.jobUidLupd = jobUidLupd;
		this.jobLoading = jobLoading;
		this.jobSubType = jobSubType;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 *      
	 */
	@Override
	public int compareTo(TCkJob o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 *      
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub
		
	}

	// Properties
	/////////////
	@Id
	@Column(name = "JOB_ID", unique = true, nullable = false, length = 35)
	public String getJobId() {
		return this.jobId;
	}

	public void setJobId(String jobId) {
		this.jobId = jobId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_STATE", nullable = false)
	public TCkMstJobState getTCkMstJobState() {
		return this.TCkMstJobState;
	}

	public void setTCkMstJobState(TCkMstJobState TCkMstJobState) {
		this.TCkMstJobState = TCkMstJobState;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_TYPE", nullable = false)
	public TCkMstJobType getTCkMstJobType() {
		return this.TCkMstJobType;
	}

	public void setTCkMstJobType(TCkMstJobType TCkMstJobType) {
		this.TCkMstJobType = TCkMstJobType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_SHIPMENT_TYPE", nullable = false)
	public TCkMstShipmentType getTCkMstShipmentType() {
		return this.TCkMstShipmentType;
	}

	public void setTCkMstShipmentType(TCkMstShipmentType TCkMstShipmentType) {
		this.TCkMstShipmentType = TCkMstShipmentType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_DATES")
	public TCkRecordDate getTCkRecordDate() {
		return this.TCkRecordDate;
	}

	public void setTCkRecordDate(TCkRecordDate TCkRecordDate) {
		this.TCkRecordDate = TCkRecordDate;
	}

	@Column(name = "JOB_REFERENCE")
	public String getJobReference() {
		return this.jobReference;
	}

	public void setJobReference(String jobReference) {
		this.jobReference = jobReference;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_FF_ACCN")
	public TCoreAccn getTCoreAccnByJobFfAccn() {
		return this.TCoreAccnByJobFfAccn;
	}

	public void setTCoreAccnByJobFfAccn(TCoreAccn TCoreAccnByJobFfAccn) {
		this.TCoreAccnByJobFfAccn = TCoreAccnByJobFfAccn;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_TO_ACCN")
	public TCoreAccn getTCoreAccnByJobToAccn() {
		return this.TCoreAccnByJobToAccn;
	}

	public void setTCoreAccnByJobToAccn(TCoreAccn TCoreAccnByJobToAccn) {
		this.TCoreAccnByJobToAccn = TCoreAccnByJobToAccn;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_SL_ACCN")
	public TCoreAccn getTCoreAccnByJobSlAccn() {
		return this.TCoreAccnByJobSlAccn;
	}

	public void setTCoreAccnByJobSlAccn(TCoreAccn TCoreAccnByJobSlAccn) {
		this.TCoreAccnByJobSlAccn = TCoreAccnByJobSlAccn;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_CO_ACCN")
	public TCoreAccn getTCoreAccnByJobCoAccn() {
		return this.TCoreAccnByJobCoAccn;
	}

	public void setTCoreAccnByJobCoAccn(TCoreAccn TCoreAccnByJobCoAccn) {
		this.TCoreAccnByJobCoAccn = TCoreAccnByJobCoAccn;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "JOB_OWNER_ACCN")
	public TCoreAccn getTCoreAccnByJobOwnerAccn() {
		return this.TCoreAccnByJobOwnerAccn;
	}

	public void setTCoreAccnByJobOwnerAccn(TCoreAccn TCoreAccnByJobOwnerAccn) {
		this.TCoreAccnByJobOwnerAccn = TCoreAccnByJobOwnerAccn;
	}
	
	@Column(name = "JOB_REMARKS", length = 16777215)
	public String getJobRemarks() {
		return this.jobRemarks;
	}

	public void setJobRemarks(String jobRemarks) {
		this.jobRemarks = jobRemarks;
	}
	@Column(name = "JOB_LOADING", length = 35)
	public String getJobLoading() {
		return jobLoading;
	}

	public void setJobLoading(String jobLoading) {
		this.jobLoading = jobLoading;
	}
	@Column(name = "JOB_SUB_TYPE", length = 35)
	public String getJobSubType() {
		return jobSubType;
	}

	public void setJobSubType(String jobSubType) {
		this.jobSubType = jobSubType;
	}
	@Column(name = "JOB_STATUS", length = 1)
	public Character getJobStatus() {
		return this.jobStatus;
	}

	public void setJobStatus(Character jobStatus) {
		this.jobStatus = jobStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JOB_DT_CREATE", length = 19)
	public Date getJobDtCreate() {
		return this.jobDtCreate;
	}

	public void setJobDtCreate(Date jobDtCreate) {
		this.jobDtCreate = jobDtCreate;
	}

	@Column(name = "JOB_UID_CREATE", length = 35)
	public String getJobUidCreate() {
		return this.jobUidCreate;
	}

	public void setJobUidCreate(String jobUidCreate) {
		this.jobUidCreate = jobUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JOB_DT_LUPD", length = 19)
	public Date getJobDtLupd() {
		return this.jobDtLupd;
	}

	public void setJobDtLupd(Date jobDtLupd) {
		this.jobDtLupd = jobDtLupd;
	}

	@Column(name = "JOB_UID_LUPD", length = 35)
	public String getJobUidLupd() {
		return this.jobUidLupd;
	}

	public void setJobUidLupd(String jobUidLupd) {
		this.jobUidLupd = jobUidLupd;
	}

}
