package com.guudint.clickargo.job.model;
// Generated 31 Oct, 2022 11:55:25 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.ccm.model.TCoreUsr;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkJobQuery generated by hbm2java
 */
@Entity
@Table(name = "T_CK_JOB_QUERY")
public class TCkJobQuery extends COAbstractEntity<TCkJobQuery> {

	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 8557169857806813550L;

	// Attributes
	/////////////
	private String qryId;
	private TCkJob TCkJob;
	private TCoreUsr TCoreUsrByQryRequester;
	private TCoreUsr TCoreUsrByQryResponder;
	private Date qryDtQuery;
	private String qryQuery;
	private Date qryDtResponse;
	private String qryResponse;
	private Character qryStatus;
	private Date qryDtCreate;
	private String qryUidCreate;
	private Date qryDtLupd;
	private String qryUidLupd;

	// Constructors
	///////////////
	public TCkJobQuery() {
	}

	/**
	 * @param qryId
	 * @param TCkJob
	 */
	public TCkJobQuery(String qryId, TCkJob TCkJob) {
		this.qryId = qryId;
		this.TCkJob = TCkJob;
	}

	/**
	 * @param qryId
	 * @param TCkJob
	 * @param TCoreUsrByQryRequester
	 * @param TCoreUsrByQryResponder
	 * @param qryDtQuery
	 * @param qryQuery
	 * @param qryDtResponse
	 * @param qryResponse
	 * @param qryStatus
	 * @param qryDtCreate
	 * @param qryUidCreate
	 * @param qryDtLupd
	 * @param qryUidLupd
	 */
	public TCkJobQuery(String qryId, TCkJob TCkJob, TCoreUsr TCoreUsrByQryRequester, TCoreUsr TCoreUsrByQryResponder,
			Date qryDtQuery, String qryQuery, Date qryDtResponse, String qryResponse, Character qryStatus,
			Date qryDtCreate, String qryUidCreate, Date qryDtLupd, String qryUidLupd) {
		this.qryId = qryId;
		this.TCkJob = TCkJob;
		this.TCoreUsrByQryRequester = TCoreUsrByQryRequester;
		this.TCoreUsrByQryResponder = TCoreUsrByQryResponder;
		this.qryDtQuery = qryDtQuery;
		this.qryQuery = qryQuery;
		this.qryDtResponse = qryDtResponse;
		this.qryResponse = qryResponse;
		this.qryStatus = qryStatus;
		this.qryDtCreate = qryDtCreate;
		this.qryUidCreate = qryUidCreate;
		this.qryDtLupd = qryDtLupd;
		this.qryUidLupd = qryUidLupd;
	}

	// Override Methods
	///////////////////
	/**
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Comparable#compareTo(java.lang.Object)
	 * 
	 */
	@Override
	public int compareTo(TCkJobQuery o) {
		// TODO Auto-generated method stub
		return 0;
	}

	/**
	 * (non-Javadoc)
	 * 
	 * @see com.vcc.camelone.common.COAbstractEntity#init()
	 * 
	 */
	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

	// Properties
	/////////////
	@Id
	@Column(name = "QRY_ID", unique = true, nullable = false, length = 35)
	public String getQryId() {
		return this.qryId;
	}

	public void setQryId(String qryId) {
		this.qryId = qryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QRY_JOB", nullable = false)
	public TCkJob getTCkJob() {
		return this.TCkJob;
	}

	public void setTCkJob(TCkJob TCkJob) {
		this.TCkJob = TCkJob;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QRY_REQUESTER")
	public TCoreUsr getTCoreUsrByQryRequester() {
		return this.TCoreUsrByQryRequester;
	}

	public void setTCoreUsrByQryRequester(TCoreUsr TCoreUsrByQryRequester) {
		this.TCoreUsrByQryRequester = TCoreUsrByQryRequester;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QRY_RESPONDER")
	public TCoreUsr getTCoreUsrByQryResponder() {
		return this.TCoreUsrByQryResponder;
	}

	public void setTCoreUsrByQryResponder(TCoreUsr TCoreUsrByQryResponder) {
		this.TCoreUsrByQryResponder = TCoreUsrByQryResponder;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QRY_DT_QUERY", length = 19)
	public Date getQryDtQuery() {
		return this.qryDtQuery;
	}

	public void setQryDtQuery(Date qryDtQuery) {
		this.qryDtQuery = qryDtQuery;
	}

	@Column(name = "QRY_QUERY", length = 16777215)
	public String getQryQuery() {
		return this.qryQuery;
	}

	public void setQryQuery(String qryQuery) {
		this.qryQuery = qryQuery;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QRY_DT_RESPONSE", length = 19)
	public Date getQryDtResponse() {
		return this.qryDtResponse;
	}

	public void setQryDtResponse(Date qryDtResponse) {
		this.qryDtResponse = qryDtResponse;
	}

	@Column(name = "QRY_RESPONSE", length = 16777215)
	public String getQryResponse() {
		return this.qryResponse;
	}

	public void setQryResponse(String qryResponse) {
		this.qryResponse = qryResponse;
	}

	@Column(name = "QRY_STATUS", length = 1)
	public Character getQryStatus() {
		return this.qryStatus;
	}

	public void setQryStatus(Character qryStatus) {
		this.qryStatus = qryStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QRY_DT_CREATE", length = 19)
	public Date getQryDtCreate() {
		return this.qryDtCreate;
	}

	public void setQryDtCreate(Date qryDtCreate) {
		this.qryDtCreate = qryDtCreate;
	}

	@Column(name = "QRY_UID_CREATE", length = 35)
	public String getQryUidCreate() {
		return this.qryUidCreate;
	}

	public void setQryUidCreate(String qryUidCreate) {
		this.qryUidCreate = qryUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QRY_DT_LUPD", length = 19)
	public Date getQryDtLupd() {
		return this.qryDtLupd;
	}

	public void setQryDtLupd(Date qryDtLupd) {
		this.qryDtLupd = qryDtLupd;
	}

	@Column(name = "QRY_UID_LUPD", length = 35)
	public String getQryUidLupd() {
		return this.qryUidLupd;
	}

	public void setQryUidLupd(String qryUidLupd) {
		this.qryUidLupd = qryUidLupd;
	}

}
