
-- SERVICE TYPE (MASTER) ----------------------------------------------------------------------------
CREATE TABLE `T_CK_MST_SERVICE_TYPE` (
  `SVCT_ID` varchar(35) NOT NULL COMMENT 'SERVICE ID - CLICDO : CLICGP : CLICTDS',
  `SVCT_NAME` varchar(100) NOT NULL COMMENT 'SERVICE TYPE NAME',
  `SVCT_DESC` varchar(255) DEFAULT NULL COMMENT 'SERVICE TYPE DESCRIPTION',
  `SVCT_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'SERVICE TYPE DESCRIPTION OTHER LANGUAGE',
  `SVCT_STATUS` char(1) DEFAULT NULL COMMENT 'SERVICE TYPE STATUS',
  `SVCT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `SVCT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `SVCT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `SVCT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`SVCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='SERVICE TYPE TABLE';

-- SERVICE SUBSCRIPTION STATE --------------------------------------------------------------------
CREATE TABLE `T_CK_MST_SVC_SUB_STATE` (
  `SSST_ID` varchar(35) NOT NULL COMMENT 'SERVICE SUBSCRIPTION STATE ID - DRF : VER : APR : EXP',
  `SSST_NAME` varchar(100) NOT NULL COMMENT 'SERVICE SUBSCRIPTION STATE NAME',
  `SSST_DESC` varchar(255) DEFAULT NULL COMMENT 'SERVICE SUBSCRIPTION STATE DESCRIPTION',
  `SSST_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'SERVICE SUBSCRIPTION STATE DESCRIPTION OTHER LANGUAGE',
  `SSST_STATUS` char(1) DEFAULT NULL COMMENT 'SERVICE SUBSCRIPTION STATE STATUS',
  `SSST_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `SSST_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `SSST_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `SSST_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`SSST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='SERVICE SUBSCRIPTION STATE TABLE';

-- SERVICE SUBSCRIPTION ----------------------------------------------------------------------------
CREATE TABLE `T_CK_SVC_SUB` (
  `SUB_ID` varchar(35) NOT NULL COMMENT 'SERVICE SUBSCRIPTION ID - UUID',
  `SUB_TYPE` varchar(35) DEFAULT NULL COMMENT 'SERVICE SUBSCRIPTION TYPE - REFERENCE T_CK_MST_SERVICE_TYPE:SSST_ID',
  `SUB_STATE` varchar(35) DEFAULT NULL COMMENT 'SERVICE SUBSCRIPTION STATE - REFERENCE T_CK_MST_SVC_SUB_STATE:SSST_ID',
  `SUB_SUBSCRIBER` varchar(35) DEFAULT NULL COMMENT 'SERVICE SUBSCRIPTION ACCOUNT - REFERENCE T_CORE_ACCN:ACCN_ID',
  `SUB_DT_START` datetime DEFAULT NULL COMMENT 'SERVICE SUBSCRIPTION START DATE',
  `SUB_DT_VALID` datetime DEFAULT NULL COMMENT 'SERVICE SUBSCRIPTION VALIDILITY DATE',
  `SUB_AUTO_RENEW` char(1) DEFAULT 'N' COMMENT 'SERVICE SUBSCRIPTION AUTO RENEWAL - Y:N',
  `SUB_UID_VERIFY` varchar(35) DEFAULT NULL COMMENT 'SERVICE SUBSCRIPTION VERIFIY BY',
  `SUB_DT_VERIFY` datetime DEFAULT NULL COMMENT 'SERVICE SUBSCRIPTION VERIFIY DATE',
  `SUB_UID_APPROVE` varchar(35) DEFAULT NULL COMMENT 'SERVICE SUBSCRIPTION APPROVE BY',
  `SUB_DT_APPROVE` datetime DEFAULT NULL COMMENT 'SERVICE SUBSCRIPTION APPROVE DATE',
  `SUB_STATUS` char(1) DEFAULT NULL COMMENT 'SERVICE TYPE STATUS',
  `SUB_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `SUB_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `SUB_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `SUB_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`SUB_ID`),
  CONSTRAINT `FK_CK_SVC_SUB_CK_MST_SERVICE_TYPE` FOREIGN KEY (`SUB_TYPE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),
  CONSTRAINT `FK_CK_SVC_SUB_CK_MST_SVC_SUB_STATE` FOREIGN KEY (`SUB_STATE`) REFERENCES `T_CK_MST_SVC_SUB_STATE` (`SSST_ID`),
  CONSTRAINT `FK_CK_SVC_SUB_CORE_ACCN` FOREIGN KEY (`SUB_SUBSCRIBER`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='SERVICE SUBSCRIPTION TABLE';

-- SERVICE SUBSCRIPTION ATTACHMENT ----------------------------------------------------------------------------
CREATE TABLE `T_CK_SVC_SUB_ATTACH` (
  `ATT_ID` varchar(35) NOT NULL COMMENT 'SERVICE SUBSCRIPTION  ATTACHMENT ID - UUID',
  `ATT_SUB` varchar(35) NOT NULL COMMENT 'SERVICE SUBSCRIPTION - REFERENCE T_CK_SVC_SUB:SUB_ID',  
  `ATT_TYPE` varchar(3) NOT NULL COMMENT 'SERVICE SUBSCRIPTION ATTACHMENT TYPE - REFERENCE T_MST_ATT_TYPE:MATT_ID',
  `ATT_NAME` varchar(256) DEFAULT NULL COMMENT 'JOB ATTACHMENT NAME',
  `ATT_LOC` varchar(1024) DEFAULT NULL COMMENT 'JOB ATTACHMENT PATH REFERENCE FROM SYS_PARAM SETUP',    
  `ATT_STATUS` char(1) DEFAULT NULL COMMENT 'JOB ATTACHMENT STATUS - A : I ',
  `ATT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `ATT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `ATT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `ATT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`ATT_ID`), 
  CONSTRAINT `FK_CK_SVC_SUB_ATTACH_CK_SVC_SUB` FOREIGN KEY (`ATT_SUB`) REFERENCES `T_CK_SVC_SUB` (`SUB_ID`),
  CONSTRAINT `FK_CK_SVC_SUB_ATTACH_MST_ATT_TYPE` FOREIGN KEY (`ATT_TYPE`) REFERENCES `T_MST_ATT_TYPE` (`MATT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='SERVICE SUBSCRIPTION TABLE';


-- CONTAINER TYPE (MASTER) ----------------------------------------------------------------------------
CREATE TABLE `T_CK_MST_CNT_TYPE` (
  `CNTT_ID` varchar(35) NOT NULL COMMENT 'CONTAINER TYPE ID - DRYC : FLRC : OTC',
  `CNTT_NAME` varchar(100) NOT NULL COMMENT 'CONTAINER TYPE NAME',
  `CNTT_DESC` varchar(255) DEFAULT NULL COMMENT 'CONTAINER TYPE DESCRIPTION',
  `CNTT_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'CONTAINER TYPE DESCRIPTION OTHER LANGUAGE',
  `CNTT_STATUS` char(1) DEFAULT NULL COMMENT 'CONTAINER TYPE STATUS',
  `CNTT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CNTT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CNTT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CNTT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CNTT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='CONTAINER TYPE TABLE';

-- CONTAINER SIZE (MASTER) ----------------------------------------------------------------------------
CREATE TABLE `T_CK_MST_CNT_SIZE` (
  `CNTZ_ID` varchar(35) NOT NULL COMMENT 'CONTAINER SIZE ID - 6FC : 8FC : 10FC',
  `CNTZ_NAME` varchar(100) NOT NULL COMMENT 'CONTAINER SIZE NAME',
  `CNTZ_DESC` varchar(255) DEFAULT NULL COMMENT 'CONTAINER SIZE DESCRIPTION',
  `CNTZ_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'CONTAINER SIZE DESCRIPTION OTHER LANGUAGE',
  `CNTZ_STATUS` char(1) DEFAULT NULL COMMENT 'CONTAINER SIZE STATUS',
  `CNTZ_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CNTZ_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CNTZ_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CNTZ_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CNTZ_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='CONTAINER SIZE TABLE';

-- CONTAINER ----------------------------------------------------------------------------
CREATE TABLE `T_CK_CNT` (
  `CNT_ID` varchar(35) NOT NULL COMMENT 'CONTAINER ID - UUID',
  `CNT_NO` varchar(255) NOT NULL COMMENT 'CONTAINER NUMBER',
  `CNT_ISO_CODE` varchar(35) DEFAULT NULL COMMENT 'ISO 6346 CODE - 20PF : 45R9 : 42G0',
  `CNT_IMO_CODE` varchar(35) DEFAULT NULL COMMENT 'IMO CODE - THE IMO CHARACTERIZES DANGEROUS GOODS INTO NINE CLASSES. EXAMPLE GASES IMO 1, EXPLOSIVES IMO 2 AND CORROSIVE SUBSTANCES IMO4',
  `CNT_TYPE` varchar(35) DEFAULT NULL COMMENT 'CONTAINER TYPE - REFERENCE T_CK_MST_CNT_TYPE:CNTT_ID',
  `CNT_SIZE` varchar(35) DEFAULT NULL COMMENT 'CONTAINER SIZE - REFERENCE T_CK_MST_CNT_SIZE:CNTZ_ID',
  `CNT_HEIGHT` mediumint DEFAULT 0 COMMENT 'CONTAINER HEIGHT (M)',
  `CNT_WEIGHT` mediumint DEFAULT 0 COMMENT 'CONTAINER WEIGHT (KG)',
  `CNT_BRUTO` mediumint DEFAULT 0 COMMENT 'CONTAINER BRUTO (KG)',
  `CNT_FULL_EMPTY_INDR` char(1) DEFAULT 'F' COMMENT 'CONTAINER FULL INDCIATOR (FCL/LCL) - F : E',
  `CNT_IMDG` char(1) DEFAULT 'N' COMMENT 'INTERNATIONAL MARITIME DANGEROUS GOODS - Y : N',
  `CNT_IMDG_UN_NO` varchar(255) DEFAULT NULL COMMENT 'IMDG UN NO - 0030',
  `CNT_IMDG_IMDG_CLASS` tinyint DEFAULT 0 COMMENT 'IMDG CLASS - 1:2:3...9',
  `CNT_IMDG_VALUE` varchar(255) DEFAULT NULL COMMENT 'EXTENSION OF IMDG CLASS - 1b mean class is 1.1B',
  `CNT_RFR_INDR` char(1) DEFAULT 'Y' COMMENT 'CONTAINER REEFER INDICATOR - Y : N',
  `CNT_RFR_REQUIRED_VOLTAGE` smallint DEFAULT 0 COMMENT 'CONTAINER REEFER REQUIRED VOLTAGE',
  `CNT_RFR_REQUIRED_TEMPERATURE` decimal(5,2) DEFAULT 0 COMMENT 'CONTAINER REEFER REQUIRED TEMPERATURE',
  `CNT_RFR_START_PLUG` datetime DEFAULT NULL COMMENT 'CONTAINER REEFER PLUG IN DATETIME',
  `CNT_RFR_STOP_PLUG` datetime DEFAULT NULL COMMENT 'CONTAINER REEFER PLUG OUT DATETIME',
  `CNT_OOG_TOP` mediumint DEFAULT 0 COMMENT 'OUT OF GUAGE CARGO TOP (M)',
  `CNT_OOG_LEFT` mediumint DEFAULT 0 COMMENT 'OUT OF GUAGE CARGO LEFT (M)',
  `CNT_OOG_RIGHT` mediumint DEFAULT 0 COMMENT 'OUT OF GUAGE CARGO RIGHT (M)',
  `CNT_SEAL_NO` varchar(255) DEFAULT NULL COMMENT 'CONTAINER SEAL NUMBER',
  `CNT_STACKING` datetime DEFAULT NULL COMMENT 'CONTAINER STACKING DATETIME',
  `CNT_GATE_IN` datetime DEFAULT NULL COMMENT 'CONTAINER GATE IN TIME',
  `CNT_GATE_OUT` datetime DEFAULT NULL COMMENT 'CONTAINER GATE OUT TIME',
  `CNT_LOCATION` varchar(255) DEFAULT NULL COMMENT 'CONTAINER LOCATION - IMPORT_AREA:TRUCK_PAD:STACKING_YARD:EXPORT_AREA:EXPORT_STACKING_YARD',
  `CNT_VESSEL_NO` varchar(255) DEFAULT NULL COMMENT 'CONTAINER VESSEL OFFICAL NO (VON) - CG002972',
  `CNT_VESSEL_NAME` varchar(255) DEFAULT NULL COMMENT 'CONTAINER VESSEL NAME - EVERGREEN TERESA',  
  `CNT_VOYAGE_NO` varchar(255) DEFAULT NULL COMMENT 'CONTAINER VOYAGE NO - V.284',
  `CNT_VESSEL_ETA` datetime DEFAULT NULL COMMENT 'CONTAINER VESSEL ESTIMATED ARRIVAL TIME - 20201001 00:00:00',
  `CNT_VESSEL_ATA` datetime DEFAULT NULL COMMENT 'CONTAINER VESSEL ACTUAL ARRIVAL TIME - 20201001 00:00:00',
  `CNT_VESSEL_ETD` datetime DEFAULT NULL COMMENT 'CONTAINER VESSEL ESTIMATED DEPARTURE TIME - 20201001 00:00:00',
  `CNT_VESSEL_ATD` datetime DEFAULT NULL COMMENT 'CONTAINER VESSEL ACUTAL DEPARTURE TIME - 20201001 00:00:00',
  `CNT_POD` varchar(5) DEFAULT NULL COMMENT 'CONTAINER PORT OF DISCHARGE - REFERENCE T_MST_PORT:PORT_CODE',
  `CNT_POL` varchar(5) DEFAULT NULL COMMENT 'CONTAINER PORT OF LOADING - REFERENCE T_MST_PORT:PORT_CODE',
  `CNT_MARKS_NO` varchar(1024) DEFAULT NULL COMMENT 'CONTAINER CONTENT MARKS AND NUMBER',
  `CNT_NO_PACKAGES` varchar(1024) DEFAULT NULL COMMENT 'CONTAINER NUMBER OF PACKAGES',
  `CNT_DESCRIPTION` mediumtext DEFAULT NULL COMMENT 'CONTAINER DESCRIPTION',
  `CNT_OWNER` varchar(255) DEFAULT NULL COMMENT 'CONTAINER OWNER NAME - ',
  `CNT_TAXID` varchar(255) DEFAULT NULL COMMENT 'CONTAINER OWNER TAX IDENTIFICATION  - NPWP',
  `CNT_SENDER` varchar(255) DEFAULT NULL COMMENT 'CONTAINER SENDER OR EXPORTER NAME - ',
  `CNT_FORWARDER` varchar(255) DEFAULT NULL COMMENT 'CONTAINER FREIGHT FORWARDER NAME - NM_ANGKUT',
  `CNT_CCAC_NO` varchar(255) DEFAULT NULL COMMENT 'CONTAINER CUSTOMS CLEARANCE APPROVAL CERTIFCATE NO (CCP) - SPPB',
  `CNT_BL_AWB_NO` varchar(255) DEFAULT NULL COMMENT 'CONTAINER BL OR AWB NO - ',
  `CNT_STATUS_CUSTOMS` varchar(255) DEFAULT NULL COMMENT 'CONTAINER CUSTOMS CLEARANCE STATUS - ',
  `CNT_STATUS_QUARANTINE` varchar(255) DEFAULT NULL COMMENT 'CONTAINER QUARANTINE CLEARANCE STATUS - ',
  `CNT_DO_LAST_PAID_THRU` datetime DEFAULT NULL COMMENT 'CONTAINER DO LAST PAID THRU DATE - 20201001 00:00:00',
  `CNT_REMARKS` varchar(512) DEFAULT NULL COMMENT 'CONTAINER REMARKS',
  `CNT_STATUS` char(1) DEFAULT NULL COMMENT 'CONTAINER TYPE STATUS',
  `CNT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CNT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CNT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CNT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CNT_ID`),
  CONSTRAINT `FK_CK_CNT_CK_MST_CNT_TYPE` FOREIGN KEY (`CNT_TYPE`) REFERENCES `T_CK_MST_CNT_TYPE` (`CNTT_ID`),
  CONSTRAINT `FK_CK_CNT_CK_MST_CNT_SIZE` FOREIGN KEY (`CNT_SIZE`) REFERENCES `T_CK_MST_CNT_SIZE` (`CNTZ_ID`),  
  CONSTRAINT `FK_CK_CNT_MST_PORT1` FOREIGN KEY (`CNT_POD`) REFERENCES `T_MST_PORT` (`PORT_CODE`),  
  CONSTRAINT `FK_CK_CNT_MST_PORT2` FOREIGN KEY (`CNT_POL`) REFERENCES `T_MST_PORT` (`PORT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='CONTAINER TABLE';

-- ========================================================================================================
-- DELIVERY ORDER STATE --------------------------------------------------------------------
CREATE TABLE `T_CK_MST_DO_STATE` (
  `DOST_ID` varchar(35) NOT NULL COMMENT 'DELIVERY ORDER STATE ID - UNRDY : RDY : PAID : CLM : EXP',
  `DOST_NAME` varchar(100) NOT NULL COMMENT 'DELIVERY ORDER STATE NAME',
  `DOST_DESC` varchar(255) DEFAULT NULL COMMENT 'DELIVERY ORDER STATE DESCRIPTION',
  `DOST_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'DELIVERY ORDER STATE DESCRIPTION OTHER LANGUAGE',
  `DOST_STATUS` char(1) DEFAULT NULL COMMENT 'DELIVERY ORDER STATE STATUS',
  `DOST_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `DOST_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `DOST_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `DOST_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`DOST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DELIVERY ORDER STATE TABLE';

-- DELIVERY ORDER --------------------------------------------------------------------
CREATE TABLE `T_CK_DOI` (
  `DOI_ID` varchar(35) NOT NULL COMMENT 'DO IMPORT ID - UUID',
  `DOI_NO` varchar(255) DEFAULT NULL COMMENT 'DO NUMBER',
  `DOI_CONSIGEE_USR` varchar(35) DEFAULT NULL COMMENT 'DO CONSIGNEE USER DETALS - REFERENCE T_CORE_USR:USR_UID',
  `DOI_CONSIGEE_ACCN` varchar(35) DEFAULT NULL COMMENT 'DO CONSIGNEE ACCN DETALS - REFERENCE T_CORE_ACCN:ACCN_ID',
  `DOI_NOTIFY_USR` varchar(35) DEFAULT NULL COMMENT 'DO NOTIFY USER DETALS - REFERENCE T_CORE_USR:USR_UID',
  `DOI_NOTIFY_ACCN` varchar(35) DEFAULT NULL COMMENT 'DO NOTIFY ACCN DETALS - REFERENCE T_CORE_ACCN:ACCN_ID',
  `DOI_VESSEL_NO` varchar(255) DEFAULT NULL COMMENT 'DO VESSEL OFFICAL NO (VON) - CG002972',
  `DOI_VESSEL_NAME` varchar(255) DEFAULT NULL COMMENT 'DO VESSEL NAME - EVERGREEN TERESA',  
  `DOI_VESSEL_ETA` datetime DEFAULT NULL COMMENT 'DO VESSEL ESTIMATED ARRIVAL TIME - 20201001',   
  `DOI_VOYAGE_NO` varchar(255) DEFAULT NULL COMMENT 'DO VOYAGE NO - V.284',
  `DOI_VESSEL_ATA` datetime DEFAULT NULL COMMENT 'DO VESSEL ACTUAL ARRIVAL TIME - 20201001 00:00:00',
  `DOI_TERMINAL` varchar(255) DEFAULT NULL COMMENT  'DO TERMINAL OF DISCHARGE',
  `DOI_POL` varchar(5) DEFAULT NULL COMMENT 'DO PORT OF LOADING - REFERENCE T_MST_PORT:PORT_CODE',
  `DOI_POD` varchar(5) DEFAULT NULL COMMENT 'DO PORT OF DISCHARGE - REFERENCE T_MST_PORT:PORT_CODE',
  `DOI_BL_NO` varchar(255) DEFAULT NULL COMMENT 'DO BL NUMBER - ',  
  `DOI_BL` varchar(1024) DEFAULT NULL COMMENT 'BL ATTACHMENT PATH REFERENCE FROM SYS_PARAM SETUP',     
  `DOI_DO` varchar(1024) DEFAULT NULL COMMENT 'DO ATTACHMENT PATH REFERENCE FROM SYS_PARAM SETUP',       
  `DOI_CARHGES_SL` decimal(15,2) DEFAULT 0.00 COMMENT 'DO CHARGES FROM SL',  
  `DOI_TAX_SL` decimal(15,2) DEFAULT 0.00 COMMENT 'DO TAX FROM SL',  
  `DOI_CARHGES_PLATFORM` decimal(15,2) DEFAULT 0.00 COMMENT 'DO CHARGES FROM PLATFORM',  
  `DOI_TAX_PLATFORM` decimal(15,2) DEFAULT 0.00 COMMENT 'DO TAX FROM PLATFORM',  
  `DOI_CARHGES_OTHERS` decimal(15,2) DEFAULT 0.00 COMMENT 'DO CHARGES FROM OTHERS',  
  `DOI_TAX_OTHERS` decimal(15,2) DEFAULT 0.00 COMMENT 'DO CHARGES FROM OTHERS',  
  `DOI_NO_CNT` smallint DEFAULT 0 COMMENT 'DO NUMBER OF CONTAINERS',       
  `DOI_DELIVERY_PLACE` varchar(1024) DEFAULT NULL COMMENT 'DO PLACE OF DELIVERY - ',  
  `DOI_PAID_THRU_DATE` datetime DEFAULT NULL COMMENT 'DO PAID THRU DATE - 20201001 00:00:00',
  `DOI_RETURN_DEPOT` varchar(1024) DEFAULT NULL COMMENT 'DO RETURN DEPOT',  
  `DOI_STATE` varchar(35) DEFAULT NULL COMMENT 'DO STATE - REFERENCE T_CK_MST_DO_STATE:DOST_ID',  
  `DOI_INVOICE_PROFOMA` varchar(1024) DEFAULT NULL COMMENT 'PROFORMA INVOICE PATH REFERENCE FROM SYS_PARAM SETUP',     
  `DOI_INVOICE_SHIPPING_LINE` varchar(1024) DEFAULT NULL COMMENT 'SHIPPING LINE INVOICE PATH REFERENCE FROM SYS_PARAM SETUP',       
  `DOI_DT_BL_SUBMIT` datetime DEFAULT NULL COMMENT 'DO SUBMITTED DATE',  
  `DOI_DT_DO_CLAIM` datetime DEFAULT NULL COMMENT 'DO CLAIM DATE',  
  `DOI_STATUS` char(1) DEFAULT NULL COMMENT 'DO STATUS - A : I ',
  `DOI_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `DOI_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `DOI_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `DOI_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`DOI_ID`), 
  CONSTRAINT `FK_CK_DOI_CORE_USR1` FOREIGN KEY (`DOI_CONSIGEE_USR`) REFERENCES `T_CORE_USR` (`USR_UID`), 
  CONSTRAINT `FK_CK_DOI_CORE_ACCN1` FOREIGN KEY (`DOI_CONSIGEE_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`), 
  CONSTRAINT `FK_CK_DOI_CORE_USR2` FOREIGN KEY (`DOI_NOTIFY_USR`) REFERENCES `T_CORE_USR` (`USR_UID`), 
  CONSTRAINT `FK_CK_DOI_CORE_ACCN2` FOREIGN KEY (`DOI_NOTIFY_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`), 
  CONSTRAINT `FK_CK_DOI_MST_PORT1` FOREIGN KEY (`DOI_POL`) REFERENCES `T_MST_PORT` (`PORT_CODE`),  
  CONSTRAINT `FK_CK_DOI_MST_PORT2` FOREIGN KEY (`DOI_POD`) REFERENCES `T_MST_PORT` (`PORT_CODE`),  
  CONSTRAINT `FK_CK_DOI_CK_MST_DOI_STATE` FOREIGN KEY (`DOI_STATE`) REFERENCES `T_CK_MST_DO_STATE` (`DOST_ID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DELIVERY ORDER IMPORT TABLE';

-- DELIVERY ORDER (IMPORT) CONTAINERS --------------------------------------------------------------------
CREATE TABLE `T_CK_DOI_CNT` (
  `DOIC_DOI_ID` varchar(35) NOT NULL COMMENT 'DO ID - REFERENCE T_CK_DO:DO_ID',
  `DOIC_CNT_ID` varchar(35) NOT NULL COMMENT 'CONTAINER ID - REFERENCE T_CK_CNT:CNT_ID',
  PRIMARY KEY (`DOIC_DOI_ID`, `DOIC_CNT_ID`), 
  CONSTRAINT `FK_CK_DOI_CNT_CK_DO` FOREIGN KEY (`DOIC_DOI_ID`) REFERENCES `T_CK_DOI` (`DOI_ID`), 
  CONSTRAINT `FK_CK_DOI_CNT_CK_CNT` FOREIGN KEY (`DOIC_CNT_ID`) REFERENCES `T_CK_CNT` (`CNT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DELIVERY ORDER CONTAINERS TABLE';

-- ========================================================================================================
-- SHIPMENT TYPE --------------------------------------------------------------------
CREATE TABLE `T_CK_MST_SHIPMENT_TYPE` (
  `SHT_ID` varchar(35) NOT NULL COMMENT 'SHIPMENT TYPE ID - EXP : IMP',
  `SHT_NAME` varchar(100) NOT NULL COMMENT 'SHIPMENT TYPE NAME',
  `SHT_DESC` varchar(255) DEFAULT NULL COMMENT 'SHIPMENT TYPE DESCRIPTION',
  `SHT_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'SHIPMENT TYPE DESCRIPTION OTHER LANGUAGE',
  `SHT_STATUS` char(1) DEFAULT NULL COMMENT 'SHIPMENT TYPE STATUS',
  `SHT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `SHT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `SHT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `SHT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`SHT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='SHIPMENT TYPE TABLE';

-- JOB TYPE --------------------------------------------------------------------
CREATE TABLE `T_CK_MST_JOB_TYPE` (
  `JBT_ID` varchar(35) NOT NULL COMMENT 'JOB TYPE ID - EXP : IMP',
  `JBT_NAME` varchar(100) NOT NULL COMMENT 'JOB TYPE NAME',
  `JBT_DESC` varchar(255) DEFAULT NULL COMMENT 'JOB TYPE DESCRIPTION',
  `JBT_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'JOB TYPE DESCRIPTION OTHER LANGUAGE',
  `JBT_STATUS` char(1) DEFAULT NULL COMMENT 'JOB TYPE STATUS',
  `JBT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `JBT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `JBT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `JBT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`JBT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='JOB TYPE TABLE';

-- JOB STATE --------------------------------------------------------------------
CREATE TABLE `T_CK_MST_JOB_STATE` (
  `JBST_ID` varchar(35) NOT NULL COMMENT 'JOB STATE ID - EXP : IMP',
  `JBST_NAME` varchar(100) NOT NULL COMMENT 'JOB STATE NAME',
  `JBST_DESC` varchar(255) DEFAULT NULL COMMENT 'JOB STATE DESCRIPTION',
  `JBST_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'JOB STATE DESCRIPTION OTHER LANGUAGE',
  `JBST_STATUS` char(1) DEFAULT NULL COMMENT 'JOB STATE STATUS',
  `JBST_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `JBST_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `JBST_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `JBST_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`JBST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='JOB STATE TABLE';

-- RECORD STATE DATES --------------------------------------------------------------------
CREATE TABLE `T_CK_RECORD_DATE` (
  `RCD_ID` varchar(35) NOT NULL COMMENT 'DATE  ID - EXP : IMP',
  `RCD_DT_DRFT` datetime DEFAULT NULL COMMENT 'RECORD DRAFT DATE', 
  `RCD_DT_START` datetime DEFAULT NULL COMMENT 'RECORD START DATE',
  `RCD_DT_EXPIRY` datetime DEFAULT NULL COMMENT 'RECORD EXPIRY DATE',
  `RCD_DT_SUBMIT` datetime DEFAULT NULL COMMENT 'RECORD SUBMITTED DATE', 
  `RCD_DT_COMPLETE` datetime DEFAULT NULL COMMENT 'RECORD COMPLETED DATE',
  `RCD_DT_CANCEL` datetime DEFAULT NULL COMMENT 'RECORD CANCELLED DATE',
  `RCD_DT_REJECT` datetime DEFAULT NULL COMMENT 'RECORD REJECTED DATE',  
  `RCD_DT_DELETE` datetime DEFAULT NULL COMMENT 'RECORD DELTED DATE',
  PRIMARY KEY (`RCD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='RECORD DATE TABLE';

-- JOB  --------------------------------------------------------------------
CREATE TABLE `T_CK_JOB` (
  `JOB_ID` varchar(35) NOT NULL COMMENT 'JOB ID - UUID',
  `JOB_TYPE` varchar(35) NOT NULL COMMENT 'JOB TYPE - REFERENCE T_CK_MST_JOB_TYPE:JBT_ID',
  `JOB_STATE` varchar(35) NOT NULL COMMENT 'JOB STATE - REFERENCE T_CK_MST_JOB_STATE:JBST_ID',
  `JOB_SHIPMENT_TYPE` varchar(35) NOT NULL COMMENT 'JOB SHIPMENT TYPE - REFERENCE T_CK_MST_SHIPMENT_TYPE:SHT_ID',
  `JOB_REFERENCE` varchar(255) DEFAULT NULL COMMENT 'JOB REFERENCE - CUSTOMER REFERENCE',
  `JOB_REMARKS` mediumtext DEFAULT NULL COMMENT 'JOB REMARKS',
  `JOB_DATES` varchar(35) DEFAULT NULL COMMENT 'JOB STATE DATES - REFERENCE T_CK_RECORD_DATE:RCD_ID',
  `JOB_STATUS` char(1) DEFAULT NULL COMMENT 'RECORD STATUS - A : I',  
  `JOB_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `JOB_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `JOB_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `JOB_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`JOB_ID`), 
  CONSTRAINT `FK_CK_JOB_CK_MST_JOB_TYPE` FOREIGN KEY (`JOB_TYPE`) REFERENCES `T_CK_MST_JOB_TYPE` (`JBT_ID`),
  CONSTRAINT `FK_CK_JOB_CK_MST_JOB_STATE` FOREIGN KEY (`JOB_STATE`) REFERENCES `T_CK_MST_JOB_STATE` (`JBST_ID`),
  CONSTRAINT `FK_CK_JOB_CK_MST_SHIPMENT_TYPE` FOREIGN KEY (`JOB_SHIPMENT_TYPE`) REFERENCES `T_CK_MST_SHIPMENT_TYPE` (`SHT_ID`),
  CONSTRAINT `FK_CK_JOB_CK_RECORD_DATE` FOREIGN KEY (`JOB_DATES`) REFERENCES `T_CK_RECORD_DATE` (`RCD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='JOB TABLE';

-- JOB ATTACHMENTS --------------------------------------------------------------------
CREATE TABLE `T_CK_JOB_ATTACH` (
  `ATT_ID` varchar(35) NOT NULL COMMENT 'JOB ATTACHMENT ID - UUID',
  `ATT_JOB` varchar(35) NOT NULL COMMENT 'JOB - REFERENCE T_CK_JOB:JOB_ID',  
  `ATT_TYPE` varchar(3) NOT NULL COMMENT 'JOB ATTACHMENT TYPE - REFERENCE T_MST_ATT_TYPE:MATT_ID',
  `ATT_NAME` varchar(256) DEFAULT NULL COMMENT 'JOB ATTACHMENT NAME',
  `ATT_LOC` varchar(1024) DEFAULT NULL COMMENT 'JOB ATTACHMENT PATH REFERENCE FROM SYS_PARAM SETUP',    
  `ATT_STATUS` char(1) DEFAULT NULL COMMENT 'JOB ATTACHMENT STATUS - A : I ',
  `ATT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `ATT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `ATT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `ATT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`ATT_ID`), 
  CONSTRAINT `FK_CK_JOB_ATTACH_MST_ATT_TYPE` FOREIGN KEY (`ATT_TYPE`) REFERENCES `T_MST_ATT_TYPE` (`MATT_ID`),   
  CONSTRAINT `FK_CK_JOB_ATTACH_CK_JOB` FOREIGN KEY (`ATT_JOB`) REFERENCES `T_CK_JOB` (`JOB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='JOB ATTACHMENT TABLE';

-- JOB QUERY/RESPONSE --------------------------------------------------------------------
CREATE TABLE `T_CK_JOB_QUERY` (
  `QRY_ID` varchar(35) NOT NULL COMMENT 'QUERY ID - UUID',
  `QRY_JOB` varchar(35) NOT NULL COMMENT 'JOB QUERY JOB - REFERENCE REFERENCE T_CK_JOB:JOB_ID',
  `QRY_REQUESTER` varchar(35) DEFAULT NULL COMMENT 'QUERY REQUESTER - REFERENCE T_CORE_USR:USR_UID',
  `QRY_DT_QUERY`  datetime DEFAULT NULL COMMENT 'QUERY DATE',
  `QRY_QUERY`  mediumtext DEFAULT NULL COMMENT 'QUERY',  
  `QRY_RESPONDER` varchar(35) DEFAULT NULL COMMENT 'QUERY RESPONDER - REFERENCE T_CORE_USR:USR_UID',
  `QRY_DT_RESPONSE`  datetime DEFAULT NULL COMMENT 'JOB QUERY DATE',
  `QRY_RESPONSE`  mediumtext DEFAULT NULL COMMENT 'RESPONSE',    
  `QRY_STATUS` char(1) DEFAULT NULL COMMENT 'JOB ATTACHMENT STATUS - A : I ',
  `QRY_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `QRY_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `QRY_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `QRY_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`QRY_ID`), 
  CONSTRAINT `FK_CK_JOB_QUERY_CK_JOB` FOREIGN KEY (`QRY_JOB`) REFERENCES `T_CK_JOB` (`JOB_ID`),
  CONSTRAINT `FK_CK_JOB_QUERY_CORE_USR1` FOREIGN KEY (`QRY_REQUESTER`) REFERENCES `T_CORE_USR` (`USR_UID`),
  CONSTRAINT `FK_CK_JOB_QUERY_CORE_USR2` FOREIGN KEY (`QRY_RESPONDER`) REFERENCES `T_CORE_USR` (`USR_UID`)   
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='JOB QUERY TABLE';

-- DO IMPORT JOB - FREIGHT FORWARDERS   --------------------------------------------------------------------
CREATE TABLE `T_CK_JOB_DOI_FF` (
  `JOB_ID` varchar(35) NOT NULL COMMENT 'JOB ID - UUID',
  `JOB_PARENT` varchar(35) NOT NULL COMMENT 'JOB PARENT - REFERENCE T_CK_JOB:JOB_ID',
  `JOB_AUTHORIZED_PARTY_ACCN` varchar(35) NOT NULL COMMENT 'JOB AUTHORIZED PARTY ACCN - REFERENCE T_CORE_ACCN:ACCN_ID', 
  `JOB_NO_DO` smallint DEFAULT 0 COMMENT 'NUMBER OF DOs ATTACH TO JOB - MUST TALLY WITH T_CK_JOB_DOI_FF_DO RECORDS', 
  `JOB_INVOICE` varchar(1024) NOT NULL COMMENT 'JOB PROFOMA INVOICE PDF FULL PATH',
  `JOB_DT_PAID` datetime DEFAULT NULL COMMENT 'JOB PAID DATE', 
  `JOB_DT_PAYMENT_VERIFIED` datetime DEFAULT NULL COMMENT 'JOB PAYMENT VERIFIED DATE', 
  `JOB_DT_DOC_VERIFIED` datetime DEFAULT NULL COMMENT 'JOB PAYMENT VERIFIED DATE', 
  `JOB_STATUS` char(1) DEFAULT NULL COMMENT 'RECORD STATUS - A : I',
  `JOB_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `JOB_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `JOB_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `JOB_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`JOB_ID`), 
  CONSTRAINT `FK_CK_JOB_DOI_CO_FF_JOB` FOREIGN KEY (`JOB_PARENT`) REFERENCES `T_CK_JOB` (`JOB_ID`),
  CONSTRAINT `FK_CK_JOB_DOI_CO_CORE_ACCN` FOREIGN KEY (`JOB_AUTHORIZED_PARTY_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DO IMPORT FREIGHT FORWARDERS JOB TABLE';

-- DO IMPORT JOB - CARGO OWNER --------------------------------------------------------------------
CREATE TABLE `T_CK_JOB_DOI_CO` (
  `JOB_ID` varchar(35) NOT NULL COMMENT 'JOB ID - UUID',
  `JOB_PARENT` varchar(35) NOT NULL COMMENT 'JOB PARENT - REFERENCE T_CK_JOB:JOB_ID',
  `JOB_AUTHORIZER_ACCN` varchar(35) DEFAULT NULL COMMENT 'JOB AUTHORIZER ACCN - REFERENCE T_CORE_ACCN:ACCN_ID',
  `JOB_AUTHORIZED_PARTY_ACCN` varchar(35) DEFAULT NULL COMMENT 'JOB AUTHORIZED PARTY ACCN - REFERENCE T_CORE_ACCN:ACCN_ID', 
  `JOB_ASSIGNED_JOB_FF` varchar(35) DEFAULT NULL COMMENT 'DOI FF JOB THAT IT IS ASSIGNED TO - REFERENCE T_CK_JOB_DOI_FF:JOB_ID', 
  `JOB_DO` varchar(35) DEFAULT NULL COMMENT 'JOB DO DETAILS  - REFERENCE T_CK_DOI:DOI_ID',   
  `JOB_STATUS` char(1) DEFAULT NULL COMMENT 'RECORD STATUS - A : I',    
  `JOB_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `JOB_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `JOB_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `JOB_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`JOB_ID`), 
  CONSTRAINT `FK_CK_JOB_DOI_CO_CK_JOB` FOREIGN KEY (`JOB_PARENT`) REFERENCES `T_CK_JOB` (`JOB_ID`),
  CONSTRAINT `FK_CK_JOB_DOI_CO_CK_DOI` FOREIGN KEY (`JOB_DO`) REFERENCES `T_CK_DOI` (`DOI_ID`),
  CONSTRAINT `FK_CK_JOB_DOI_CO_CORE_ACCN1` FOREIGN KEY (`JOB_AUTHORIZER_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_JOB_DOI_CO_CORE_ACCN2` FOREIGN KEY (`JOB_AUTHORIZED_PARTY_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_JOB_DOI_CK_JOB_DOI_FF` FOREIGN KEY (`JOB_ASSIGNED_JOB_FF`) REFERENCES `T_CK_JOB_DOI_FF` (`JOB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DO IMPORT CARGO OWNER JOB TABLE';

-- DO IMPORT JOB DOs - FREIGHT FORWARDERS   --------------------------------------------------------------------
CREATE TABLE `T_CK_JOB_DOI_FF_DO` (
  `JDO_ID` varchar(35) NOT NULL COMMENT 'JOBL ID - UUID',
  `JDO_JOB` varchar(35) NOT NULL COMMENT 'JOB ID FOR THE BL - REFERENCE T_CK_JOB_DOI_FF:JOB_ID',
  `JDO_AUTHORIZER_ACCN` varchar(35) NOT NULL COMMENT 'JOB AUTHORIZER ACCN - REFERENCE T_CORE_ACCN:ACCN_ID',
  `JDO_AUTHORIZED_PARTY_ACCN` varchar(35) NOT NULL COMMENT 'JOB AUTHORIZED PARTY ACCN - REFERENCE T_CORE_ACCN:ACCN_ID', 
  `JDO_DO` varchar(35) DEFAULT NULL COMMENT 'JOB DETAILS - REFERENCE T_CK_DOI:DOI_ID',  
  `JDO_JOB_CO` varchar(35) DEFAULT NULL COMMENT 'JOB CO IF PRESENT - REFERENCE T_CK_JOB:JOB_ID',    
  `JDO_STATUS` char(1) DEFAULT NULL COMMENT 'RECORD STATUS - A : I',
  `JDO_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `JDO_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `JDO_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `JDO_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`JDO_ID`), 
  CONSTRAINT `FK_CK_JOB_DOI_BL_CK_JOB_DOI_FF` FOREIGN KEY (`JDO_JOB`) REFERENCES `T_CK_JOB_DOI_FF` (`JOB_ID`),
  CONSTRAINT `FK_CK_JOB_DOI_BL_CORE_ACCN1` FOREIGN KEY (`JDO_AUTHORIZER_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_JOB_DOI_BL_CORE_ACCN2` FOREIGN KEY (`JDO_AUTHORIZED_PARTY_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_JOB_DOI_BL_CK_DOI` FOREIGN KEY (`JDO_DO`) REFERENCES `T_CK_DOI` (`DOI_ID`),
  CONSTRAINT `FK_CK_JOB_DOI_FF_DO_CK_JOB` FOREIGN KEY (`JDO_JOB_CO`) REFERENCES `T_CK_JOB` (`JOB_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DO IMPORT FREIGHT FORWARDERS JOB DOs TABLE';


-- ========================================================================================================
-- TASK TYPE --------------------------------------------------------------------
CREATE TABLE `T_CK_MST_TASK_TYPE` (
  `TSKT_ID` varchar(35) NOT NULL COMMENT 'TASK TYPE ID - EXP : IMP',
  `TSKT_NAME` varchar(100) NOT NULL COMMENT 'TASK TYPE NAME',
  `TSKT_DESC` varchar(255) DEFAULT NULL COMMENT 'TASK TYPE DESCRIPTION',
  `TSKT_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'TASK TYPE DESCRIPTION OTHER LANGUAGE',
  `TSKT_STATUS` char(1) DEFAULT NULL COMMENT 'TASK TYPE STATUS',
  `TSKT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `TSKT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `TSKT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `TSKT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`TSKT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TASK TYPE TABLE';

-- TASK STATE --------------------------------------------------------------------
CREATE TABLE `T_CK_MST_TASK_STATE` (
  `TSKST_ID` varchar(35) NOT NULL COMMENT 'TASK STATE ID - EXP : IMP',  
  `TSKST_NAME` varchar(100) NOT NULL COMMENT 'TASK STATE NAME',
  `TSKST_DESC` varchar(255) DEFAULT NULL COMMENT 'TASK STATE DESCRIPTION',
  `TSKST_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'TASK STATE DESCRIPTION OTHER LANGUAGE',
  `TSKST_STATUS` char(1) DEFAULT NULL COMMENT 'TASK STATE STATUS',
  `TSKST_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `TSKST_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `TSKST_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `TSKST_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`TSKST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TASK STATE TABLE';

-- TASK  --------------------------------------------------------------------
CREATE TABLE `T_CK_TASK` (
  `TSK_ID` varchar(35) NOT NULL COMMENT 'TASK ID - UUID',
  `TSK_JOB` varchar(35) NOT NULL COMMENT 'TASK PARENT JOB - REFERENCE T_CK_JOB:JOB_ID',
  `TSK_TYPE` varchar(35) NOT NULL COMMENT 'TASK TYPE - REFERENCE T_CK_MST_TASK_TYPE:TSKT_ID',
  `TSK_STATE` varchar(35) NOT NULL COMMENT 'TASK STATE - REFERENCE T_CK_MST_TASK_STATE:TSKST_ID',
  `TSK_SHIPMENT_TYPE` varchar(35) NOT NULL COMMENT 'TASK SHIPMENT TYPE - REFERENCE T_CK_MST_SHIPMENT_TYPE:SHT_ID',  
  `TSK_REFERENCE` varchar(255) DEFAULT NULL COMMENT 'TASK REFERENCE - CUSTOMER REFERENCE',
  `TSK_DATES` varchar(35) DEFAULT NULL COMMENT 'TASK STATE DATES - REFERENCE T_CK_RECORD_DATE:RCD_ID',
  `TSK_REMARKS` mediumtext DEFAULT NULL COMMENT 'TASK REMARKS',
  `TSK_STATUS` char(1) DEFAULT NULL COMMENT 'RECORD STATUS - A : I',    
  `TSK_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `TSK_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `TSK_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `TSK_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`TSK_ID`), 
  CONSTRAINT `FK_CK_TASK_CK_JOB` FOREIGN KEY (`TSK_JOB`) REFERENCES `T_CK_JOB` (`JOB_ID`),  
  CONSTRAINT `FK_CK_TASK_CK_MST_TSK_TYPE` FOREIGN KEY (`TSK_TYPE`) REFERENCES `T_CK_MST_TASK_TYPE` (`TSKT_ID`),
  CONSTRAINT `FK_CK_TASK_CK_MST_TSK_STATE` FOREIGN KEY (`TSK_STATE`) REFERENCES `T_CK_MST_TASK_STATE` (`TSKST_ID`),
  CONSTRAINT `FK_CK_TASK_CK_MST_SHIPMENT_TYPE` FOREIGN KEY (`TSK_SHIPMENT_TYPE`) REFERENCES `T_CK_MST_SHIPMENT_TYPE` (`SHT_ID`),
  CONSTRAINT `FK_CK_TASK_CK_RECORD_DATE` FOREIGN KEY (`TSK_DATES`) REFERENCES `T_CK_RECORD_DATE` (`RCD_ID`)   
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TASK TABLE';

-- TASK ATTACHMENTS --------------------------------------------------------------------
CREATE TABLE `T_CK_TASK_ATTACH` (
  `ATT_ID` varchar(35) NOT NULL COMMENT 'TASK ATTACHMENT ID - UUID',
  `ATT_TASK` varchar(35) NOT NULL COMMENT 'TASK - REFERENCE T_CK_TASK:TSK_ID',  
  `ATT_TYPE` varchar(3) NOT NULL COMMENT 'TASK ATTACHMENT TYPE - REFERENCE T_MST_ATT_TYPE:MATT_ID',
  `ATT_NAME` varchar(256) DEFAULT NULL COMMENT 'TASK ATTACHMENT NAME',
  `ATT_LOC` varchar(1024) DEFAULT NULL COMMENT 'TASK ATTACHMENT PATH REFERENCE FROM SYS_PARAM SETUP',    
  `ATT_STATUS` char(1) DEFAULT NULL COMMENT 'TASK ATTACHMENT STATUS - A : I ',
  `ATT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `ATT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `ATT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `ATT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`ATT_ID`), 
  CONSTRAINT `FK_CK_TASK_ATTACH_MST_ATT_TYPE` FOREIGN KEY (`ATT_TYPE`) REFERENCES `T_MST_ATT_TYPE` (`MATT_ID`),   
  CONSTRAINT `FK_CK_TASK_ATTACH_CK_TASK` FOREIGN KEY (`ATT_TASK`) REFERENCES `T_CK_TASK` (`TSK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='TASK ATTACHMENT TABLE';

-- DO IMPORT TASK - FREIGHT FORWARDERS   --------------------------------------------------------------------
CREATE TABLE `T_CK_TASK_DOI_FF` (
  `TSK_ID` varchar(35) NOT NULL COMMENT 'TASK ID - UUID',
  `TSK_PARENT` varchar(35) NOT NULL COMMENT 'TASK PARENT - REFERENCE T_CK_TASK:TSK_ID',
  `TSK_NO_BL` smallint DEFAULT 0 COMMENT 'NUMBER OF BL IN TASK',
  `TSK_NO_CNT` smallint DEFAULT 0 COMMENT 'NUMBER OF CONTAINERS IN TASK',
  `TSK_STATUS` char(1) DEFAULT NULL COMMENT 'RECORD STATUS - A : I',
  `TSK_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `TSK_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `TSK_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `TSK_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`TSK_ID`), 
  CONSTRAINT `FK_CK_TASK_DOI_FF_CK_TASK` FOREIGN KEY (`TSK_PARENT`) REFERENCES `T_CK_TASK` (`TSK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DO IMPORT FREIGHT FORWARDERS TASK TABLE';

-- DO IMPORT TASK - FREIGHT FORWARDERS   --------------------------------------------------------------------
CREATE TABLE `T_CK_TASK_DOI_FF_DO` (
  `TDO_ID` varchar(35) NOT NULL COMMENT 'TASK ID - UUID',
  `TDO_TASK` varchar(35) NOT NULL COMMENT 'TASK PARENT - REFERENCE T_CK_TASK_DOI_FF:TSK_ID',
  `TDO_JOB_DO` varchar(35) NOT NULL COMMENT 'TASK DO - REFERENCE T_CK_JOB_DOI_FF_DO:JDO_ID',
  `TDO_STATUS` char(1) DEFAULT NULL COMMENT 'RECORD STATUS - A : I',
  `TDO_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `TDO_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `TDO_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `TDO_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`TDO_ID`), 
  CONSTRAINT `FK_CK_TASK_DOI_FF_DO_CK_TASK_DOI_FF` FOREIGN KEY (`TDO_TASK`) REFERENCES `T_CK_TASK_DOI_FF` (`TSK_ID`),
  CONSTRAINT `FK_CK_TASK_DOI_FF_DO_T_CK_JOB_DOI_FF_DO` FOREIGN KEY (`TDO_JOB_DO`) REFERENCES `T_CK_JOB_DOI_FF_DO` (`JDO_ID`)  
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DO IMPORT FREIGHT FORWARDERS TASK TABLE';

-- ========================================================================================================
-- PAYMENT TYPE (MASTER)   --------------------------------------------------------------------
CREATE TABLE `T_CK_MST_PAYMENT_TYPE` (
  `PTY_ID` varchar(35) NOT NULL COMMENT 'PAYMENT TYPE ID - VA : BNKTF : CRL',
  `PYT_NAME` varchar(100) NOT NULL COMMENT 'PAYMENT  TYPE NAME',
  `PYT_DESC` varchar(255) DEFAULT NULL COMMENT 'PAYMENT  TYPE DESCRIPTION',
  `PYT_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'PAYMENT  TYPE DESCRIPTION OTHER LANGUAGE',
  `PYT_STATUS` char(1) DEFAULT NULL COMMENT 'PAYMENT  TYPE STATUS',
  `PYT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `PYT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `PYT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `PYT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`PTY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='PAYMENT  TYPE TABLE';

-- DO PAYMENT LEDGER   --------------------------------------------------------------------
CREATE TABLE `T_CK_PAYMENT_LEDGER` (
  `PYL_ID` varchar(35) NOT NULL COMMENT 'PAYMENT LEDGER ID - UUID',
  `PYL_TYPE` varchar(35) DEFAULT NULL COMMENT 'PAYMENT TYPE - REFERENCE T_CK_MST_PAYMENT_TYPE:PTY_ID',
  `PYL_SERVICE` varchar(35) DEFAULT NULL COMMENT 'CLICKARGO SERVICES - REFERENCE T_CK_MST_SERVICE_TYPE:SVCT_ID',
  `PYL_SERVICE_REFERENCE` varchar(35) DEFAULT NULL COMMENT 'PAYMENT REFERENCE - JOB ID : TASK ID',  
  `PYL_MERCHANT_BANK` varchar(35) DEFAULT NULL COMMENT 'PAYMENT MERCHANT BANK',  
  `PYL_PAYER` varchar(35) DEFAULT NULL COMMENT 'PAYER - REFERENCES T_CORE_ACCN:ACCN_ID',
  `PYL_PAYER_BANK_ACCN` varchar(255) DEFAULT NULL COMMENT 'PAYER BANK ACCOUNT NUMBER',  
  `PYL_PAYEE` varchar(35) DEFAULT NULL COMMENT 'PAYEE - REFERENCES T_CORE_ACCN:ACCN_ID',
  `PYL_PAYEE_BANK_ACCN` varchar(255) DEFAULT NULL COMMENT 'PAYER BANK ACCOUNT NUMBER',    
  `PYL_AMOUNT` decimal(15,2) DEFAULT 0.00 COMMENT 'PAYEE - REFERENCES T_CORE_ACCN:ACCN_ID',
  `PYL_CCY` varchar(3) DEFAULT NULL COMMENT 'CURRENCY  - REFERENCES T_MST_CURRENCY:CCY_CODE',
  `PYL_BANK_REF` varchar(255) DEFAULT NULL COMMENT 'BANK REFERENCE NUMBER - VA',
  `PYL_PAYMENT_STATE` varchar(35) DEFAULT NULL COMMENT 'PAYMENT STATE - SUCCESS : FAIL : NEW',
  `PYL_STATUS` char(1) DEFAULT NULL COMMENT 'RECORD STATUS - A : I',
  `PYL_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `PYL_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `PYL_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `PYL_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`PYL_ID`),
  CONSTRAINT `FK_CK_PAYMENT_LEDGER_CK_MST_PAYMENT_TYPE` FOREIGN KEY (`PYL_TYPE`) REFERENCES `T_CK_MST_PAYMENT_TYPE` (`PTY_ID`),
  CONSTRAINT `FK_CK_PAYMENT_LEDGER_CK_MST_SERVICE_TYPE` FOREIGN KEY (`PYL_SERVICE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),
  CONSTRAINT `FK_CK_PAYMENT_LEDGER_CORE_ACCN1` FOREIGN KEY (`PYL_PAYER`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_PAYMENT_LEDGER_CORE_ACCN2` FOREIGN KEY (`PYL_PAYEE`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_PAYMENT_LEDGER_MST_CCY` FOREIGN KEY (`PYL_CCY`) REFERENCES `T_MST_CURRENCY` (`CCY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='DO PAYMENT LEDGER';

-- PAYMENT AUDIT TYPE (MASTER)   --------------------------------------------------------------------
CREATE TABLE `T_CK_MST_PAYMENT_AUDIT_TYPE` (
  `PATY_ID` varchar(35) NOT NULL COMMENT 'PAYMENT AUDIT TYPE ID - VA_REQ : VA_CB : PY_CB : TR_REQ : TR_CB',
  `PYT_NAME` varchar(100) NOT NULL COMMENT 'PAYMENT AUDIT TYPE NAME',
  `PYT_DESC` varchar(255) DEFAULT NULL COMMENT 'PAYMENT AUDIT TYPE DESCRIPTION',
  `PYT_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'PAYMENT AUDIT TYPE DESCRIPTION OTHER LANGUAGE',
  `PYT_STATUS` char(1) DEFAULT NULL COMMENT 'PAYMENT AUDIT TYPE STATUS',
  `PYT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `PYT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `PYT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `PYT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`PATY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='PAYMENT AUDIT TYPE TABLE';

-- DO PAYMENT TXN   --------------------------------------------------------------------
CREATE TABLE `T_CK_PAYMENT_AUDIT` (
  `PYA_ID` varchar(35) NOT NULL COMMENT 'PAYMENT AUDIT ID - UUID',
  `PYA_TYPE` varchar(35) NOT NULL COMMENT 'PAYMENT AUDIT TYPE - REFERENCE T_CK_MST_PAYMENT_AUDIT_TYPE:PATY_ID',
  `PYA_REFERENCE` varchar(1024) DEFAULT NULL COMMENT 'PAYMENT REFERENCE - UUID PASS TO PAYMENT GATEWAY TO LINK TO CALLBACK',
  `PYA_LEDGER` varchar(35) NOT NULL COMMENT 'PAYMENT LEDGER RECORD - REFERENCE T_CK_PAYMENT_LEDGER:PYL_ID',
  `PYA_REQ` mediumtext COMMENT 'PAYMENT REQUEST JSON',
  `PYA_RESP` mediumtext COMMENT 'PAYMENT RESPONSE JSON',
  `PYA_CB` mediumtext COMMENT 'PAYMENT CALLBACK JSON',
  `PYA_REMARK` mediumtext COMMENT 'PAYMENT CALLBACK JSON',
  `PYA_STATUS` char(1) DEFAULT NULL COMMENT 'PAYMENT AUDIT TYPE STATUS',
  `PYA_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `PYA_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `PYA_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `PYA_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`PYA_ID`),
  KEY `FK_CK_DO_PAYMENT_AUDIT_CK_MST_PAYMENT_AUDIT_TYPE` (`PYA_TYPE`),
  KEY `FK_CK_DO_PAYMENT_AUDIT_CK_PAYMENT_LEDGER` (`PYA_LEDGER`),
  CONSTRAINT `FK_CK_DO_PAYMENT_AUDIT_CK_MST_PAYMENT_AUDIT_TYPE` FOREIGN KEY (`PYA_TYPE`) REFERENCES `T_CK_MST_PAYMENT_AUDIT_TYPE` (`PATY_ID`),
  CONSTRAINT `FK_CK_DO_PAYMENT_AUDIT_CK_PAYMENT_LEDGER` FOREIGN KEY (`PYA_LEDGER`) REFERENCES `T_CK_PAYMENT_LEDGER` (`PYL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='DO PAYMENT TRANSACTION';


-- ========================================================================================================
-- AUTHORIZATION STATE (MASTER) ----------------------------------------------------------------------------
CREATE TABLE `T_CK_MST_AUTH_STATE` (
  `AUST_ID` varchar(35) NOT NULL COMMENT 'AUTHORISATION STATE - DRFT : SUBM : PENA : AUTH : EXP',
  `AUST_NAME` varchar(100) NOT NULL COMMENT 'AUTHORISATION STATE NAME',
  `AUST_DESC` varchar(255) DEFAULT NULL COMMENT 'AUTHORISATION STATE DESCRIPTION',
  `AUST_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'AUTHORISATION STATE DESCRIPTION OTHER LANGUAGE',
  `AUST_STATUS` char(1) DEFAULT NULL COMMENT 'AUTHORISATION STATE STATUS',
  `AUST_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `AUST_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `AUST_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `AUST_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`AUST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='AUTHORISATION STATE TABLE';

-- AUTHORIZATION ACCOUNT TYPE (MASTER) ----------------------------------------------------------------------------
CREATE TABLE `T_CK_MST_AUTH_ACCN_TYPE` (
  `AUAT_ID` varchar(35) NOT NULL COMMENT 'AUTHORISATION ACCN TYPE  - AUTHR : AUTHD',
  `AUAT_NAME` varchar(100) NOT NULL COMMENT 'AUTHORISATION ACCN TYPE NAME',
  `AUAT_DESC` varchar(255) DEFAULT NULL COMMENT 'AUTHORISATION ACCN TYPE DESCRIPTION',
  `AUAT_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'AUTHORISATION ACCN TYPE DESCRIPTION OTHER LANGUAGE',
  `AUAT_STATUS` char(1) DEFAULT NULL COMMENT 'AUTHORISATION ACCN TYPE STATUS',
  `AUAT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `AUAT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `AUAT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `AUAT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`AUAT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='AUTHORISATION ACCN TYPE TABLE';


-- SERVICE AUTHORIZATION ----------------------------------------------------------------------------
CREATE TABLE `T_CK_SVC_AUTH` (
  `SVAU_ID` varchar(35) NOT NULL COMMENT 'SERVICE AUTHORISATION ID - UUID',
  `SVAU_SERVICE` varchar(35) DEFAULT NULL COMMENT 'SERVICE AUTHORISATION SERVICE - REFERENCE T_CK_MST_SERVICE_TYPE:SVCT_ID',
  `SVAU_STATE` varchar(35) DEFAULT NULL COMMENT 'SERVICE AUTHORISATION STATE - REFERENCE T_CK_MST_AUTH_STATE:AUST_ID',
  `SVAU_ACCN_AUTHORIZER` varchar(35) DEFAULT NULL COMMENT 'AUTHORIZER ACCN  - REFERENCE T_CORE_ACCN:ACCN_ID',
  `SVAU_USR_AUTHORIZER` varchar(35) DEFAULT NULL COMMENT 'AUTHORIZER USR  - REFERENCE T_CORE_USR:USR_UID',
  `SVAU_POSITION_AUTHORIZER` varchar(255) DEFAULT NULL COMMENT 'AUTHORIZER USR POSITION - MANAGER',
  `SVAU_ACCN_AUTHORIZED` varchar(35) DEFAULT NULL COMMENT 'AUTHORIZED PARTY ACCN  - REFERENCE T_CORE_ACCN:ACCN_ID',
  `SVAU_USR_AUTHORIZED` varchar(35) DEFAULT NULL COMMENT 'AUTHORIZER PARTY USR  - REFERENCE T_CORE_USR:USR_UID',
  `SVAU_POSITION_AUTHORIZED` varchar(255) DEFAULT NULL COMMENT 'AUTHORIZED PARTY USR POSITION - MANAGER',
  `SVAU_ACCN_SERVICE` varchar(35) DEFAULT NULL COMMENT 'SERVICE PROVIDER ACCN  - REFERENCE T_CORE_ACCN:ACCN_ID',
  `SVAU_DT_SERVICE_START` datetime DEFAULT NULL COMMENT 'AUTHORISATION START DATE',
  `SVAU_DT_SERVICE_VALID` datetime DEFAULT NULL COMMENT 'AUTHORISATION VALIDILITY DATE',
  `SVAU_REMARKS_AUTHORIZER` mediumtext COMMENT 'AUTHORIZER REMARKS',
  `SVAU_REMARKS_AUTHORIZED` mediumtext COMMENT 'AUTHORIZER PARTY REMARKS',
  `SVAU_STATUS` char(1) DEFAULT NULL COMMENT 'AUTHORISATION STATE STATUS',
  `SVAU_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `SVAU_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `SVAU_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `SVAU_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`SVAU_ID`),
  KEY `FK_CK_SERVICE_AUTH_CK_MST_SERVICE_TYPE` (`SVAU_SERVICE`),
  KEY `FK_CK_SERVICE_AUTH_CK_MST_AUTH_STATE` (`SVAU_STATE`),
  KEY `FK_CK_SERVICE_AUTH_CORE_ACCN1` (`SVAU_ACCN_AUTHORIZER`),
  KEY `FK_CK_SERVICE_AUTH_CORE_USR1` (`SVAU_USR_AUTHORIZER`),
  KEY `FK_CK_SERVICE_AUTH_CORE_ACCN2` (`SVAU_ACCN_AUTHORIZED`),
  KEY `FK_CK_SERVICE_AUTH_CORE_USR2` (`SVAU_USR_AUTHORIZED`),
  KEY `FK_CK_SERVICE_AUTH_CORE_ACCN3` (`SVAU_ACCN_SERVICE`),
  CONSTRAINT `FK_CK_SERVICE_AUTH_CK_MST_AUTH_STATE` FOREIGN KEY (`SVAU_STATE`) REFERENCES `T_CK_MST_AUTH_STATE` (`AUST_ID`),
  CONSTRAINT `FK_CK_SERVICE_AUTH_CK_MST_SERVICE_TYPE` FOREIGN KEY (`SVAU_SERVICE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`),
  CONSTRAINT `FK_CK_SERVICE_AUTH_CORE_ACCN1` FOREIGN KEY (`SVAU_ACCN_AUTHORIZER`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_SERVICE_AUTH_CORE_ACCN2` FOREIGN KEY (`SVAU_ACCN_AUTHORIZED`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_SERVICE_AUTH_CORE_ACCN3` FOREIGN KEY (`SVAU_ACCN_SERVICE`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_SERVICE_AUTH_CORE_USR1` FOREIGN KEY (`SVAU_USR_AUTHORIZER`) REFERENCES `T_CORE_USR` (`USR_UID`),
  CONSTRAINT `FK_CK_SERVICE_AUTH_CORE_USR2` FOREIGN KEY (`SVAU_USR_AUTHORIZED`) REFERENCES `T_CORE_USR` (`USR_UID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='AUTHORISATION STATE TABLE';


-- SERVICE SUBSCRIPTION ATTACHMENT ----------------------------------------------------------------------------
CREATE TABLE `T_CK_SVC_AUTH_ATTACH` (
  `ATT_ID` varchar(35) NOT NULL COMMENT 'SERVICE AUTHORIZATION  ATTACHMENT ID - UUID',
  `ATT_SUA` varchar(35) NOT NULL COMMENT 'SERVICE AUTHORIZATION - REFERENCE T_CK_SVC_AUTH:SVAU_ID',  
  `ATT_TYPE` varchar(3) NOT NULL COMMENT 'SERVICE AUTHORIZATION ATTACHMENT TYPE - REFERENCE T_MST_ATT_TYPE:MATT_ID',
  `ATT_ACCN_TYPE` varchar(35) NOT NULL COMMENT 'SERVICE AUTHORIZATION ACCN TYPE - REFERENCE T_CK_MST_AUTH_ACCN_TYPE:AUAT_ID',
  `ATT_NAME` varchar(256) DEFAULT NULL COMMENT 'SERVICE AUTHORIZATION NAME',
  `ATT_LOC` varchar(1024) DEFAULT NULL COMMENT 'SERVICE AUTHORIZATION PATH REFERENCE FROM SYS_PARAM SETUP',    
  `ATT_STATUS` char(1) DEFAULT NULL COMMENT 'SERVICE AUTHORIZATION STATUS - A : I ',
  `ATT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `ATT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `ATT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `ATT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`ATT_ID`), 
  CONSTRAINT `FK_CK_SVC_AUTH_CK_MST_AUTH_ACCN_TYPE` FOREIGN KEY (`ATT_ACCN_TYPE`) REFERENCES `T_CK_MST_AUTH_ACCN_TYPE` (`AUAT_ID`),  
  CONSTRAINT `FK_CK_SVC_AUTH_CK_SVC_AUTH` FOREIGN KEY (`ATT_SUA`) REFERENCES `T_CK_SVC_AUTH` (`SVAU_ID`),
  CONSTRAINT `FK_CK_SVC_AUTH_MST_ATT_TYPE` FOREIGN KEY (`ATT_TYPE`) REFERENCES `T_MST_ATT_TYPE` (`MATT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='SERVICE AUTHORIZATION ATTACHMENT TABLE';

-- COMPONENT GUIDE ----------------------------------------------------------------------------
CREATE TABLE `T_CK_COMPONENT_GUIDE` (
  `CMGU_ID` varchar(35) NOT NULL COMMENT 'COMPONENT GUIDE  - UUID',
  `CMGU_APPS_CODE` varchar(35) NOT NULL COMMENT 'COMPONENT GUIDE APPS CODE - REFERENCE T_CORE_APPS:APPS_CODE',
  `CMGU_SERVICE_TYPE` varchar(35) DEFAULT NULL COMMENT 'COMPONENT GUIDE SERVICE - REFERENCE T_CK_MST_SERVICE_TYPE:SSST_ID',
  `CMGU_COMPONENT_ID` varchar(1024) NOT NULL COMMENT 'COMPONENT GUIDE COMPONENT ID - clicdo.claim.doi.list.table_jobs : clicdo.claim.doi.list.page',
  `CMGU_GUIDE` mediumtext DEFAULT NULL COMMENT 'COMPONENT GUIDE DESCRIPTION',
  `CMGU_GUIDE_OTH` mediumtext  DEFAULT NULL COMMENT 'COMPONENT GUIDE DESCRIPTION OTHER LANGUAGE',
  `CMGU_STATUS` char(1) DEFAULT NULL COMMENT 'COMPONENT GUIDE STATUS',
  `CMGU_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `CMGU_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `CMGU_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `CMGU_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`CMGU_ID`),
  INDEX `ID_CK_CMP_GUIDE_COMPONET_ID` (`CMGU_COMPONENT_ID`),
  CONSTRAINT `FK_CK_CMP_GUIDE_CORE_APPS` FOREIGN KEY (`CMGU_APPS_CODE`) REFERENCES `T_CORE_APPS` (`APPS_CODE`),
  CONSTRAINT `FK_CK_CMP_GUIDE_CK_MST_SERVICE_TYPE` FOREIGN KEY (`CMGU_SERVICE_TYPE`) REFERENCES `T_CK_MST_SERVICE_TYPE` (`SVCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='COMPONENT GUIDE TABLE';


-- FORM ENTITY TYPE (MASTER) -----------------------------------------------------------------------------
CREATE TABLE `T_CK_MST_ENTITY_TYPE` (
  `ENTY_ID` varchar(35) NOT NULL COMMENT 'ENTITY TYPE ID - CLICDO : DOICO : DOIFF',
  `ENTY_NAME` varchar(100) NOT NULL COMMENT 'ENTITY TYPE NAME',
  `ENTY_DESC` varchar(255) DEFAULT NULL COMMENT 'ENTITY TYPE DESCRIPTION',
  `ENTY_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'ENTITY TYPE DESCRIPTION OTHER LANGUAGE',
  `ENTY_STATUS` char(1) DEFAULT NULL COMMENT 'ENTITY TYPE STATUS',
  `ENTY_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `ENTY_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `ENTY_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `ENTY_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`ENTY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ENTITY TYPE TABLE';

-- FORM ENTITY STATE (MASTER) -----------------------------------------------------------------------------
CREATE TABLE `T_CK_MST_ENTITY_STATE` (
  `ENST_ID` varchar(35) NOT NULL COMMENT 'ENTITY STATE ID - DRAFT : NEW : SUBMITTED : ...',
  `ENST_NAME` varchar(100) NOT NULL COMMENT 'ENTITY STATE NAME',
  `ENST_DESC` varchar(255) DEFAULT NULL COMMENT 'ENTITY STATE DESCRIPTION',
  `ENST_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'ENTITY STATE DESCRIPTION OTHER LANGUAGE',
  `ENST_STATUS` char(1) DEFAULT NULL COMMENT 'ENTITY STATE STATUS',
  `ENST_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `ENST_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `ENST_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `ENST_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`ENST_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='ENTITY STATE TABLE';

-- FORM TYPE (MASTER) -----------------------------------------------------------------------------
CREATE TABLE `T_CK_MST_FORM_TYPE` (
  `FMTYP_ID` varchar(35) NOT NULL COMMENT 'FORM TYPE ID - EDIT : VIEW : RETURN',
  `FMTYP_NAME` varchar(100) NOT NULL COMMENT 'FORM TYPE NAME',
  `FMTYP_DESC` varchar(255) DEFAULT NULL COMMENT 'FORM TYPE DESCRIPTION',
  `FMTYP_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'FORM TYPE DESCRIPTION OTHER LANGUAGE',
  `FMTYP_STATUS` char(1) DEFAULT NULL COMMENT 'FORM TYPE STATUS',
  `FMTYP_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `FMTYP_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `FMTYP_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `FMTYP_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`FMTYP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='FORM TYPE TABLE';

-- FORM ACTION (MASTER) -----------------------------------------------------------------------------
CREATE TABLE `T_CK_MST_FORM_ACTION` (
  `FMACT_ID` varchar(35) NOT NULL COMMENT 'FORM ACTION ID - SAVE : SUBMIT : DELETE : EXIT : PAY',
  `FMACT_NAME` varchar(100) NOT NULL COMMENT 'FORM ACTION NAME',
  `FMACT_DESC` varchar(255) DEFAULT NULL COMMENT 'FORM ACTION DESCRIPTION',
  `FMACT_DESC_OTH` varchar(512) DEFAULT NULL COMMENT 'FORM ACTION DESCRIPTION OTHER LANGUAGE',
  `FMACT_STATUS` char(1) DEFAULT NULL COMMENT 'FORM ACTION STATUS',
  `FMACT_DT_CREATE` datetime DEFAULT NULL COMMENT 'RECORD CREATED DATE',
  `FMACT_UID_CREATE` varchar(35) DEFAULT NULL COMMENT 'RECORD CREATED USER',
  `FMACT_DT_LUPD` datetime DEFAULT NULL COMMENT 'RECORD LAST UPDATED DATE',
  `FMACT_UID_LUPD` varchar(35) DEFAULT NULL COMMENT 'RECORD LAST UPDATED USER',
  PRIMARY KEY (`FMACT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='FORM ACTION TABLE';

-- FORM CONTROL -----------------------------------------------------------------------------
CREATE TABLE `T_CK_FORM_CONTROL` (
  `CTRL_ID` varchar(35) NOT NULL COMMENT 'CONTROL ID UUDID ',
  `CTRL_ACCN_TYPE` varchar(35) NOT NULL COMMENT 'CONTROL ACCOUNT TYPE - REFERENCE T_MST_ACCN_TYPE:ATYP_ID',
  `CTRL_ACCN` varchar(35) DEFAULT NULL COMMENT 'OPTIONAL ACCOUNT SPECIFIC CONTROL - REFEREMCE T_CORE_ACCN:ACCN_ID',
  `CTRL_USR_ROLE` varchar(35) NOT NULL COMMENT 'CONTROL USER ROLE - USE T_CORE_ROLES',
  `CTRL_ENTITY_TYPE` varchar(35) NOT NULL COMMENT 'CONTROL ENTITY TYPE - REFERENCE T_CK_MST_ENTITY_TYPE:ENTY_ID',
  `CTRL_ENTITY_STATE` varchar(35) NOT NULL COMMENT 'CONTROL ENTITY STATE - REFERENCE T_CK_MST_ENTITY_STATE:ENST_ID',
  `CTRL_FORM_TYPE` varchar(35) NOT NULL COMMENT 'CONTROL FORM TYPE - REFERENCE T_CK_MST_FORM_TYPE:FMTYP_ID',
  `CTRL_FORM_ACTION` varchar(35) NOT NULL COMMENT 'CONTROL FORM ACTION - REFERENCE T_CK_MST_FORM_ACTION:FMACT_ID',
  `CTRL_FORM_ACTION_MENU` varchar(255) DEFAULT NULL COMMENT 'CONTROL FORM ACTION MENU - OPTIONAL',
  `CTRL_STATUS` char(1) NOT NULL,
  `CTRL_DT_CREATE` datetime DEFAULT NULL,
  `CTRL_UID_CREATE` varchar(35) DEFAULT NULL,
  `CTRL_DT_LUPD` datetime DEFAULT NULL,
  `CTRL_UID_LUPD` varchar(35) DEFAULT NULL,
  PRIMARY KEY (`CTRL_ID`),
  KEY `IDX_FORMCTRL_CTRL_ACCN_TYPE` (`CTRL_ACCN_TYPE`),
  KEY `IDX_CK_FORM_CONTROL_CTRL_FORM_ACTION` (`CTRL_FORM_ACTION`),
  KEY `IDX_CK_FORM_CONTROL_CTRL_USR_ROLE` (`CTRL_USR_ROLE`),
  CONSTRAINT `FK_CK_FORM_CONTROL_MST_ACCN_TYPE` FOREIGN KEY (`CTRL_ACCN_TYPE`) REFERENCES `T_MST_ACCN_TYPE` (`ATYP_ID`),
  CONSTRAINT `FK_CK_FORM_CONTROL_CORE_ACCN` FOREIGN KEY (`CTRL_ACCN`) REFERENCES `T_CORE_ACCN` (`ACCN_ID`),
  CONSTRAINT `FK_CK_FORM_CONTROL_CK_MST_ENTITY_TYPE` FOREIGN KEY (`CTRL_ENTITY_TYPE`) REFERENCES `T_CK_MST_ENTITY_TYPE` (`ENTY_ID`),
  CONSTRAINT `FK_CK_FORM_CONTROL_CK_MST_ENTITY_STATE` FOREIGN KEY (`CTRL_ENTITY_STATE`) REFERENCES `T_CK_MST_ENTITY_STATE` (`ENST_ID`),
  CONSTRAINT `FK_CK_FORM_CONTROL_CK_MST_FORM_TYPE` FOREIGN KEY (`CTRL_FORM_TYPE`) REFERENCES `T_CK_MST_FORM_TYPE` (`FMTYP_ID`),
  CONSTRAINT `FK_CK_FORM_CONTROL_CK_MST_FORM_ACTION` FOREIGN KEY (`CTRL_FORM_ACTION`) REFERENCES `T_CK_MST_FORM_ACTION` (`FMACT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;