

INSERT ignore INTO clickargo2.T_CORE_ACCN_CONFIG(ACFG_ACCNID, ACFG_KEY, ACFG_VAL, ACFG_DESC
, ACFG_VALID_FROM_DT, ACFG_VALID_TO_DT, ACFG_SEQ, ACFG_STATUS, ACFG_DT_CREATE, ACFG_UID_CREATE)
SELECT ACCN_ID, 'SAGE_ACCN_ID', SAGE_ID,  'SAGE_ACCN_ID', SYSDATE(), '2024-11-30',1,'A',SYSDATE(), 'SYS' 
FROM ctMigration.SAGE_BANK_ACCOUNT;


INSERT ignore INTO clickargo2.T_CORE_ACCN_CONFIG(ACFG_ACCNID, ACFG_KEY, ACFG_VAL, ACFG_DESC
, ACFG_VALID_FROM_DT, ACFG_VALID_TO_DT, ACFG_SEQ, ACFG_STATUS, ACFG_DT_CREATE, ACFG_UID_CREATE)
SELECT ACCN_ID, 'BANK_DETAIL', BANK_ACCOUNT,  'BANK_DETAIL', SYSDATE(), '2024-11-30',1,'A',SYSDATE(), 'SYS' 
FROM ctMigration.SAGE_BANK_ACCOUNT
where BANK_ACCOUNT is not null and BANK_ACCOUNT != '';
