
insert ignore into clickargo2.T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE)
SELECT USR_UID, 'CKT', 'ADMIN', 'N', 'A', SYSDATE(), 'SYS', SYSDATE(), 'SYS','N' FROM clickargo2.T_CORE_USR
where USR_ACCNID in (SELECT ACCN_ID FROM clickargo2.T_CORE_ACCN where ACCN_TYPE = 'ACC_TYPE_CO') and USR_UID not in (select UROL_UID from clickargo2.T_CORE_USR_ROLE where UROL_ROLEID ='ADMIN');


insert ignore into clickargo2.T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE)
SELECT USR_UID, 'CKT', 'FF_FINANCE', 'N', 'A', SYSDATE(), 'SYS', SYSDATE(), 'SYS','N' FROM clickargo2.T_CORE_USR
where USR_ACCNID in (SELECT ACCN_ID FROM clickargo2.T_CORE_ACCN where ACCN_TYPE = 'ACC_TYPE_CO') and USR_UID not in (select UROL_UID from clickargo2.T_CORE_USR_ROLE where UROL_ROLEID ='FF_FINANCE');


insert ignore into clickargo2.T_CORE_USR_ROLE(UROL_UID, UROL_APPSCODE, UROL_ROLEID, UROL_ADMIN_OPT, UROL_STATUS, UROL_DT_CREATE, UROL_UID_CREATE, UROL_DT_LUPD, UROL_UID_LUPD, UROL_TEMP_ROLE)
SELECT USR_UID, 'CKT', 'OFFICER', 'N', 'A', SYSDATE(), 'SYS', SYSDATE(), 'SYS','N' FROM clickargo2.T_CORE_USR
where USR_ACCNID in (SELECT ACCN_ID FROM clickargo2.T_CORE_ACCN where ACCN_TYPE = 'ACC_TYPE_CO') and USR_UID not in (select UROL_UID from clickargo2.T_CORE_USR_ROLE where UROL_ROLEID ='OFFICER');