package com.guudint.clickargo.manageaccn.model;
// Generated 23 Sep 2023, 2:27:49 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkAccnAtt generated by hbm2java
 */
@Entity
@Table(name = "T_CK_ACCN_ATT")
public class TCkAccnAtt extends COAbstractEntity<TCkAccnAtt> {

	private static final long serialVersionUID = -3468903299323428311L;
	private String aatId;
	private TCkMstAccnAttType TCkMstAccnAttType;
	private TCoreAccn TCoreAccn;
	private String aatName;
	private String aatNo;
	private Date atDtValidility;
	private String aatLoc;
	private Character atStatus;
	private Date atDtCreate;
	private String atUidCreate;
	private Date atDtLupd;
	private String atUidLupd;

	public TCkAccnAtt() {
	}

	public TCkAccnAtt(String aatId, TCkMstAccnAttType TCkMstAccnAttType, TCoreAccn TCoreAccn) {
		this.aatId = aatId;
		this.TCkMstAccnAttType = TCkMstAccnAttType;
		this.TCoreAccn = TCoreAccn;
	}

	public TCkAccnAtt(String aatId, TCkMstAccnAttType TCkMstAccnAttType, TCoreAccn TCoreAccn, String aatName,
			String aatNo, Date atDtValidility, String aatLoc, Character atStatus, Date atDtCreate, String atUidCreate,
			Date atDtLupd, String atUidLupd) {
		this.aatId = aatId;
		this.TCkMstAccnAttType = TCkMstAccnAttType;
		this.TCoreAccn = TCoreAccn;
		this.aatName = aatName;
		this.aatNo = aatNo;
		this.atDtValidility = atDtValidility;
		this.aatLoc = aatLoc;
		this.atStatus = atStatus;
		this.atDtCreate = atDtCreate;
		this.atUidCreate = atUidCreate;
		this.atDtLupd = atDtLupd;
		this.atUidLupd = atUidLupd;
	}

	@Id

	@Column(name = "AAT_ID", unique = true, nullable = false, length = 35)
	public String getAatId() {
		return this.aatId;
	}

	public void setAatId(String aatId) {
		this.aatId = aatId;
	}

	@ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@JoinColumns({ @JoinColumn(name = "AAT_TYPE_ID", referencedColumnName = "AT_ID", nullable = false),
			@JoinColumn(name = "AAT_TYPE_WORKFLOW", referencedColumnName = "AT_WORKFLOW", nullable = false) })
	public TCkMstAccnAttType getTCkMstAccnAttType() {
		return this.TCkMstAccnAttType;
	}

	public void setTCkMstAccnAttType(TCkMstAccnAttType TCkMstAccnAttType) {
		this.TCkMstAccnAttType = TCkMstAccnAttType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AAT_ACCN", nullable = false)
	public TCoreAccn getTCoreAccn() {
		return this.TCoreAccn;
	}

	public void setTCoreAccn(TCoreAccn TCoreAccn) {
		this.TCoreAccn = TCoreAccn;
	}

	@Column(name = "AAT_NAME", length = 256)
	public String getAatName() {
		return this.aatName;
	}

	public void setAatName(String aatName) {
		this.aatName = aatName;
	}

	@Column(name = "AAT_NO", length = 256)
	public String getAatNo() {
		return this.aatNo;
	}

	public void setAatNo(String aatNo) {
		this.aatNo = aatNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AT_DT_VALIDILITY", length = 19)
	public Date getAtDtValidility() {
		return this.atDtValidility;
	}

	public void setAtDtValidility(Date atDtValidility) {
		this.atDtValidility = atDtValidility;
	}

	@Column(name = "AAT_LOC", length = 1024)
	public String getAatLoc() {
		return this.aatLoc;
	}

	public void setAatLoc(String aatLoc) {
		this.aatLoc = aatLoc;
	}

	@Column(name = "AT_STATUS", length = 1)
	public Character getAtStatus() {
		return this.atStatus;
	}

	public void setAtStatus(Character atStatus) {
		this.atStatus = atStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AT_DT_CREATE", length = 19)
	public Date getAtDtCreate() {
		return this.atDtCreate;
	}

	public void setAtDtCreate(Date atDtCreate) {
		this.atDtCreate = atDtCreate;
	}

	@Column(name = "AT_UID_CREATE", length = 35)
	public String getAtUidCreate() {
		return this.atUidCreate;
	}

	public void setAtUidCreate(String atUidCreate) {
		this.atUidCreate = atUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AT_DT_LUPD", length = 19)
	public Date getAtDtLupd() {
		return this.atDtLupd;
	}

	public void setAtDtLupd(Date atDtLupd) {
		this.atDtLupd = atDtLupd;
	}

	@Column(name = "AT_UID_LUPD", length = 35)
	public String getAtUidLupd() {
		return this.atUidLupd;
	}

	public void setAtUidLupd(String atUidLupd) {
		this.atUidLupd = atUidLupd;
	}

	@Override
	public int compareTo(TCkAccnAtt o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
