package com.guudint.clickargo.manageaccn.model;
// Generated 18 Dec 2023, 10:41:15 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.vcc.camelone.ccm.model.TCoreAccn;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkCtFfCo generated by hbm2java
 */
@Entity
@Table(name = "T_CK_CT_FF_CO")
public class TCkCtFfCo  extends COAbstractEntity<TCkCtFfCo> {


	// Static Attributes
	////////////////////
	private static final long serialVersionUID = 1L;
	public static final String PREFIX_ID = "FFCO";

	// Attributes
	/////////////
	private String ffcoId;
	private TCoreAccn TCoreAccnByFfcoCo;
	private TCoreAccn TCoreAccnByFfcoFf;
	private String ffcoRef;
	private String ffcoRemarks;
	private Date ffcoDtStart;
	private Date ffcoDtEnd;
	private Character ffcoStatus;
	private Date ffcoDtCreate;
	private String ffcoUidCreate;
	private Date ffcoDtLupd;
	private String ffcoUidLupd;


	// Constructors
	///////////////
	public TCkCtFfCo() {
	}

	public TCkCtFfCo(String ffcoId) {
		this.ffcoId = ffcoId;
	}

	public TCkCtFfCo(String ffcoId, TCoreAccn TCoreAccnByFfcoCo, TCoreAccn TCoreAccnByFfcoFf, String ffcoRef,
			String ffcoRemarks, Date ffcoDtStart, Date ffcoDtEnd, Character ffcoStatus, Date ffcoDtCreate,
			String ffcoUidCreate, Date ffcoDtLupd, String ffcoUidLupd) {
		this.ffcoId = ffcoId;
		this.TCoreAccnByFfcoCo = TCoreAccnByFfcoCo;
		this.TCoreAccnByFfcoFf = TCoreAccnByFfcoFf;
		this.ffcoRef = ffcoRef;
		this.ffcoRemarks = ffcoRemarks;
		this.ffcoDtStart = ffcoDtStart;
		this.ffcoDtEnd = ffcoDtEnd;
		this.ffcoStatus = ffcoStatus;
		this.ffcoDtCreate = ffcoDtCreate;
		this.ffcoUidCreate = ffcoUidCreate;
		this.ffcoDtLupd = ffcoDtLupd;
		this.ffcoUidLupd = ffcoUidLupd;
	}


	// Override Methods
	///////////////////
	@Override
	public int compareTo(TCkCtFfCo o) {
		return 0;
	}

	@Override
	public void init() {
		
	}
	
	// Properties
	/////////////
	@Id

	@Column(name = "FFCO_ID", unique = true, nullable = false, length = 35)
	public String getFfcoId() {
		return this.ffcoId;
	}

	public void setFfcoId(String ffcoId) {
		this.ffcoId = ffcoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FFCO_CO")
	public TCoreAccn getTCoreAccnByFfcoCo() {
		return this.TCoreAccnByFfcoCo;
	}

	public void setTCoreAccnByFfcoCo(TCoreAccn TCoreAccnByFfcoCo) {
		this.TCoreAccnByFfcoCo = TCoreAccnByFfcoCo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FFCO_FF")
	public TCoreAccn getTCoreAccnByFfcoFf() {
		return this.TCoreAccnByFfcoFf;
	}

	public void setTCoreAccnByFfcoFf(TCoreAccn TCoreAccnByFfcoFf) {
		this.TCoreAccnByFfcoFf = TCoreAccnByFfcoFf;
	}

	@Column(name = "FFCO_REF")
	public String getFfcoRef() {
		return this.ffcoRef;
	}

	public void setFfcoRef(String ffcoRef) {
		this.ffcoRef = ffcoRef;
	}

	@Column(name = "FFCO_REMARKS", length = 16777215)
	public String getFfcoRemarks() {
		return this.ffcoRemarks;
	}

	public void setFfcoRemarks(String ffcoRemarks) {
		this.ffcoRemarks = ffcoRemarks;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FFCO_DT_START", length = 19)
	public Date getFfcoDtStart() {
		return this.ffcoDtStart;
	}

	public void setFfcoDtStart(Date ffcoDtStart) {
		this.ffcoDtStart = ffcoDtStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FFCO_DT_END", length = 19)
	public Date getFfcoDtEnd() {
		return this.ffcoDtEnd;
	}

	public void setFfcoDtEnd(Date ffcoDtEnd) {
		this.ffcoDtEnd = ffcoDtEnd;
	}

	@Column(name = "FFCO_STATUS", length = 1)
	public Character getFfcoStatus() {
		return this.ffcoStatus;
	}

	public void setFfcoStatus(Character ffcoStatus) {
		this.ffcoStatus = ffcoStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FFCO_DT_CREATE", length = 19)
	public Date getFfcoDtCreate() {
		return this.ffcoDtCreate;
	}

	public void setFfcoDtCreate(Date ffcoDtCreate) {
		this.ffcoDtCreate = ffcoDtCreate;
	}

	@Column(name = "FFCO_UID_CREATE", length = 35)
	public String getFfcoUidCreate() {
		return this.ffcoUidCreate;
	}

	public void setFfcoUidCreate(String ffcoUidCreate) {
		this.ffcoUidCreate = ffcoUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FFCO_DT_LUPD", length = 19)
	public Date getFfcoDtLupd() {
		return this.ffcoDtLupd;
	}

	public void setFfcoDtLupd(Date ffcoDtLupd) {
		this.ffcoDtLupd = ffcoDtLupd;
	}

	@Column(name = "FFCO_UID_LUPD", length = 35)
	public String getFfcoUidLupd() {
		return this.ffcoUidLupd;
	}

	public void setFfcoUidLupd(String ffcoUidLupd) {
		this.ffcoUidLupd = ffcoUidLupd;
	}

}
