package com.guudint.clickargo.manageaccn.model;
// Generated 23 Sep 2023, 2:27:49 pm by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.guudint.clickargo.common.model.TCkMstWorkflowType;
import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstAccnAttType generated by hbm2java
 */
@Entity
@Table(name = "T_CK_MST_ACCN_ATT_TYPE")
public class TCkMstAccnAttType extends COAbstractEntity<TCkMstAccnAttType> {

	private static final long serialVersionUID = 2056064172040550471L;
	private TCkMstAccnAttTypeId id;
	private TCkMstWorkflowType TCkMstWorkflowType;
	private String atName;
	private String atDesc;
	private String atDescOth;
	private Character atMandatory;
	private Character atStatus;
	private Date atDtCreate;
	private String atUidCreate;
	private Date atDtLupd;
	private String atUidLupd;

	public TCkMstAccnAttType() {
	}

	public TCkMstAccnAttType(TCkMstAccnAttTypeId id, TCkMstWorkflowType TCkMstWorkflowType) {
		this.id = id;
		this.TCkMstWorkflowType = TCkMstWorkflowType;
	}

	public TCkMstAccnAttType(TCkMstAccnAttTypeId id, TCkMstWorkflowType TCkMstWorkflowType, String atName,
			String atDesc, String atDescOth, Character atMandatory, Character atStatus, Date atDtCreate,
			String atUidCreate, Date atDtLupd, String atUidLupd) {
		this.id = id;
		this.TCkMstWorkflowType = TCkMstWorkflowType;
		this.atName = atName;
		this.atDesc = atDesc;
		this.atDescOth = atDescOth;
		this.atMandatory = atMandatory;
		this.atStatus = atStatus;
		this.atDtCreate = atDtCreate;
		this.atUidCreate = atUidCreate;
		this.atDtLupd = atDtLupd;
		this.atUidLupd = atUidLupd;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "atId", column = @Column(name = "AT_ID", nullable = false, length = 35)),
			@AttributeOverride(name = "atWorkflow", column = @Column(name = "AT_WORKFLOW", nullable = false, length = 35)) })
	public TCkMstAccnAttTypeId getId() {
		return this.id;
	}

	public void setId(TCkMstAccnAttTypeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AT_WORKFLOW", nullable = false, insertable = false, updatable = false)
	public TCkMstWorkflowType getTCkMstWorkflowType() {
		return this.TCkMstWorkflowType;
	}

	public void setTCkMstWorkflowType(TCkMstWorkflowType TCkMstWorkflowType) {
		this.TCkMstWorkflowType = TCkMstWorkflowType;
	}

	@Column(name = "AT_NAME", length = 128)
	public String getAtName() {
		return this.atName;
	}

	public void setAtName(String atName) {
		this.atName = atName;
	}

	@Column(name = "AT_DESC", length = 45)
	public String getAtDesc() {
		return this.atDesc;
	}

	public void setAtDesc(String atDesc) {
		this.atDesc = atDesc;
	}

	@Column(name = "AT_DESC_OTH", length = 512)
	public String getAtDescOth() {
		return this.atDescOth;
	}

	public void setAtDescOth(String atDescOth) {
		this.atDescOth = atDescOth;
	}

	@Column(name = "AT_MANDATORY", length = 1)
	public Character getAtMandatory() {
		return this.atMandatory;
	}

	public void setAtMandatory(Character atMandatory) {
		this.atMandatory = atMandatory;
	}

	@Column(name = "AT_STATUS", length = 1)
	public Character getAtStatus() {
		return this.atStatus;
	}

	public void setAtStatus(Character atStatus) {
		this.atStatus = atStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AT_DT_CREATE", length = 19)
	public Date getAtDtCreate() {
		return this.atDtCreate;
	}

	public void setAtDtCreate(Date atDtCreate) {
		this.atDtCreate = atDtCreate;
	}

	@Column(name = "AT_UID_CREATE", length = 35)
	public String getAtUidCreate() {
		return this.atUidCreate;
	}

	public void setAtUidCreate(String atUidCreate) {
		this.atUidCreate = atUidCreate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AT_DT_LUPD", length = 19)
	public Date getAtDtLupd() {
		return this.atDtLupd;
	}

	public void setAtDtLupd(Date atDtLupd) {
		this.atDtLupd = atDtLupd;
	}

	@Column(name = "AT_UID_LUPD", length = 35)
	public String getAtUidLupd() {
		return this.atUidLupd;
	}

	public void setAtUidLupd(String atUidLupd) {
		this.atUidLupd = atUidLupd;
	}

	@Override
	public int compareTo(TCkMstAccnAttType o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
