package com.guudint.clickargo.manageaccn.model;
// Generated 23 Sep 2023, 2:27:49 pm by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.vcc.camelone.common.COAbstractEntity;

/**
 * TCkMstAccnAttTypeId generated by hbm2java
 */
@Embeddable
public class TCkMstAccnAttTypeId extends COAbstractEntity<TCkMstAccnAttTypeId> {

	private static final long serialVersionUID = -7400026013961220065L;
	private String atId;
	private String atWorkflow;

	public TCkMstAccnAttTypeId() {
	}

	public TCkMstAccnAttTypeId(String atId, String atWorkflow) {
		this.atId = atId;
		this.atWorkflow = atWorkflow;
	}

	@Column(name = "AT_ID", nullable = false, length = 35)
	public String getAtId() {
		return this.atId;
	}

	public void setAtId(String atId) {
		this.atId = atId;
	}

	@Column(name = "AT_WORKFLOW", nullable = false, length = 35)
	public String getAtWorkflow() {
		return this.atWorkflow;
	}

	public void setAtWorkflow(String atWorkflow) {
		this.atWorkflow = atWorkflow;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TCkMstAccnAttTypeId))
			return false;
		TCkMstAccnAttTypeId castOther = (TCkMstAccnAttTypeId) other;

		return ((this.getAtId() == castOther.getAtId()) || (this.getAtId() != null && castOther.getAtId() != null
				&& this.getAtId().equals(castOther.getAtId())))
				&& ((this.getAtWorkflow() == castOther.getAtWorkflow())
						|| (this.getAtWorkflow() != null && castOther.getAtWorkflow() != null
								&& this.getAtWorkflow().equals(castOther.getAtWorkflow())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAtId() == null ? 0 : this.getAtId().hashCode());
		result = 37 * result + (getAtWorkflow() == null ? 0 : this.getAtWorkflow().hashCode());
		return result;
	}

	@Override
	public int compareTo(TCkMstAccnAttTypeId o) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void init() {
		// TODO Auto-generated method stub

	}

}
